### ISSUE TITLE
dubbo3.0.8序列化问题

### ISSUE THREAD

**Issue by a4363220** [apache/dubbo#10102]
dubbo：3.0.8
registry-center：zookeeper
protocol：tri
serialization：kryo

引入了：
           <dependency>
                <groupId>org.apache.dubbo.extensions</groupId>
                <artifactId>dubbo-serialization-kryo</artifactId>
                <version>1.0.0</version>
            </dependency>
启动项目时出错了，注意：在我没有使用kryo序列化时，我的服务是可以正常的发布订阅的.
请问一下这是什么原因导致的？tri协议不支持kryo序列化吗？还是我使用的方式不对。
出错位置：
![image](https://user-images.githubusercontent.com/35019507/170877402-81bb6d5a-3723-46ea-bbaa-1355e8264418.png)
错误打印：
一：
org.apache.zookeeper.ClientCnxn$EndOfStreamException: Unable to read additional data from server sessionid 0x100063b29b800f6, likely server has closed socket
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
二：
org.apache.zookeeper.ClientCnxn$EndOfStreamException: Unable to read additional data from server sessionid 0x100063b29b800f5, likely server has closed socket
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
三：
java.lang.NullPointerException: null
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:374)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:361)
	at org.apache.dubbo.config.ServiceConfig.lambda$doDelayExport$0(ServiceConfig.java:243)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

我的application.yaml:
# dubbo config
dubbo:
  # 应用配置
  application:
    # 服务名称
    name: pay-service-provider
    # 维护者
    owner: xiaoguzi
    # 日志
    logger: slf4j
    # 注册模式,只注册应用级
    register-mode: instance
    # 从远端获取元数据
    metadata-type: remote
  # 协议配置
  protocol:
    # 协议端口
    port: 20200
    # 协议名称
    name: tri
    # 序列化配置
    serialization: kryo
    # 序列化对象配置实现
    optimizer: com.grain.pay.service.api.serialization.SerializationOptimizerImpl
  # 消费者配置
  consumer:
    # 取消消费者订阅检查避免循环依赖
    check: false
    # 消费者默认版本号
    version: 1.0
  # 提供者服务配置
  provider:
    # 延迟2秒暴露
    delay: 2000
    # 默认超时10秒
    timeout: 10000
    # 提供者默认版本号
    version: 1.0
    # 默认最小活跃度
    loadbalance: leastactive
    # 默认快速失败
    cluster: failfast
    # 不进行重试
    retries: 0
  # 注册中心配置
  registry:
    # 注册中心ip
    address: zookeeper://192.168.207.195:2181
    # 分组
    group: dubbo-registry-dev
    # 超时
    timeout: 20000
    # 缓存文件
    file: dubbo-cache/${dubbo.application.name}-registry
  # 元数据中心配置
  metadata-report:
    # 元数据中心地址
    address: ${dubbo.registry.address}
    # 分组
    group: dubbo-metadata-dev
    # 超时
    timeout: 20000
    # 缓存文件
    file: dubbo-cache/${dubbo.application.name}-metadata
  # 配置中心配置
  config-center:
    # 配置中心地址
    address: ${dubbo.registry.address}
    # 分组
    namespace: dubbo-config-dev
    # 超时
    timeout: 20000
    # 配置文件
    config-file: dubbo-cache/${dubbo.application.name}-config
    # 应用业务配置文件
    app-config-file: dubbo-cache/${dubbo.application.name}-config-app

**Comment by haoyann** [comment]
试试引入这个呢？
```
<dependency>
    <groupId>org.apache.dubbo.extensions</groupId>
    <artifactId>dubbo-serialization-kryo</artifactId>
    <version>1.0.0</version>
</dependency>
```

**Comment by chickenlj** [comment]
出现的主要问题是这个？
```java
java.lang.NullPointerException: null
at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:374)
at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:361)
at org.apache.dubbo.config.ServiceConfig.lambda$doDelayExport$0(ServiceConfig.java:243)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at
```

从代码分析来看 `ModuleServiceRepository repository = getScopeModel().getServiceRepository();` 并不会为空

```java
   public ModuleModel(ApplicationModel applicationModel, boolean isInternal) {
        super(applicationModel, ExtensionScope.MODULE, isInternal);
        Assert.notNull(applicationModel, "ApplicationModel can not be null");
        this.applicationModel = applicationModel;
        applicationModel.addModule(this, isInternal);
        if (LOGGER.isInfoEnabled()) {
            LOGGER.info(getDesc() + " is created");
        }

        initialize();
        Assert.notNull(serviceRepository, "ModuleServiceRepository can not be null");
        Assert.notNull(moduleConfigManager, "ModuleConfigManager can not be null");
        Assert.assertTrue(moduleConfigManager.isInitialized(), "ModuleConfigManager can not be initialized");

        // notify application check state
        ApplicationDeployer applicationDeployer = applicationModel.getDeployer();
        if (applicationDeployer != null) {
            applicationDeployer.notifyModuleChanged(this, DeployState.PENDING);
        }
    }
```

**需要确认是否 Module 由于一些原因已经被销毁了** 
```java
    @Override
    protected void onDestroy() {
        // 1. remove from applicationModel
        applicationModel.removeModule(this);

        // 2. set stopping
        if (deployer != null) {
            deployer.preDestroy();
        }

        // 3. release services
        if (deployer != null) {
            deployer.postDestroy();
        }

        // destroy other resources
        notifyDestroy();

        if (serviceRepository != null) {
            serviceRepository.destroy();
            serviceRepository = null;
        }
```
