### ISSUE TITLE
无注册中心模式下，启动报错

### ISSUE THREAD

**Issue by Qyt-Coding** [apache/dubbo#10118]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### 环境

* Dubbo version: 3.0.4
* Operating System version: window10
* Java version: 1.8
* 项目有两个工程，两个工程相互调用（既是生产者也是消费者）
* 项目没有注册中心
### 启动错误过程

1.启动其中一个工程
2.  @DubboReference(check = false,url = "dubbo://127.0.0.1:20880")在引用的时候已经设置了check=false了，理论上就不会启动检查了
3. 启动的时候，控制台抛出异常，虽不影响，但是有时候看起来以为是错误
```java
2022-06-04 23:03:47.692  WARN 4816 --- [           main] o.a.d.remoting.transport.AbstractClient  :  [DUBBO] Failed to start NettyClient /192.168.8.1 connect to the server /127.0.0.1:20881 (check == false, ignore and retry later!), cause: client(url: dubbo://127.0.0.1:20881/com.yjs.test.TestService?application=dubbo-consumer&background=false&check=false&codec=dubbo&heartbeat=60000&interface=com.yjs.test.TestService&pid=4816&qos.enable=false&register.ip=192.168.8.1&side=consumer&sticky=false) failed to connect to server /127.0.0.1:20881, error message is:Connection refused: no further information: /192.168.8.1:20881, dubbo version: 3.0.4, current host: 192.168.8.1

org.apache.dubbo.remoting.RemotingException: client(url: dubbo://127.0.0.1:20881/com.yjs.test.TestService?application=dubbo-consumer&background=false&check=false&codec=dubbo&heartbeat=60000&interface=com.yjs.test.TestService&pid=4816&qos.enable=false&register.ip=192.168.8.1&side=consumer&sticky=false) failed to connect to server /127.0.0.1:20881, error message is:Connection refused: no further information: /192.168.8.1:20881
	at org.apache.dubbo.remoting.transport.netty4.NettyClient.doConnect(NettyClient.java:183) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:202) ~[dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.remoting.transport.AbstractClient.<init>(AbstractClient.java:72) ~[dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.remoting.transport.netty4.NettyClient.<init>(NettyClient.java:88) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.remoting.transport.netty4.NettyTransporter.connect(NettyTransporter.java:40) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.remoting.Transporter$Adaptive.connect(Transporter$Adaptive.java) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.remoting.Transporters.connect(Transporters.java:74) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchanger.connect(HeaderExchanger.java:39) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.remoting.exchange.Exchangers.connect(Exchangers.java:108) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.initClient(DubboProtocol.java:647) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.buildReferenceCountExchangeClient(DubboProtocol.java:610) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.buildReferenceCountExchangeClientList(DubboProtocol.java:597) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getSharedClient(DubboProtocol.java:522) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getClients(DubboProtocol.java:454) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.protocolBindingRefer(DubboProtocol.java:431) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.refer(DubboProtocol.java:422) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:77) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:85) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:74) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:52) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.config.ReferenceConfig.createInvokerForRemote(ReferenceConfig.java:474) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:379) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:266) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:203) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.config.utils.SimpleReferenceCache.get(SimpleReferenceCache.java:117) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:326) [dubbo-3.0.4.jar:3.0.4]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) ~[na:1.8.0_212-3-redhat]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:306) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:146) [dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:108) ~[dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:98) ~[dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:44) ~[dubbo-3.0.4.jar:3.0.4]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.12.jar:2.5.12]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[spring-boot-2.5.12.jar:2.5.12]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:448) ~[spring-boot-2.5.12.jar:2.5.12]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:339) ~[spring-boot-2.5.12.jar:2.5.12]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1365) ~[spring-boot-2.5.12.jar:2.5.12]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-2.5.12.jar:2.5.12]
	at com.DubboConsumerApplication.main(DubboConsumerApplication.java:11) ~[classes/:na]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.8.1:20881
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_212-3-redhat]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_212-3-redhat]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[netty-transport-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710) ~[netty-transport-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[netty-transport-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[netty-transport-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[netty-transport-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212-3-redhat]


```

Pls. provide [GitHub address] to reproduce this issue.

### 预期结果

能正常启动，并且控制台不报错

```
Just put your stack trace here!
```

**Comment by Qyt-Coding** [comment]
https://github.com/Qyt-Coding/dubbo-demo

**Comment by Qyt-Coding** [comment]
git地址：https://gitee.com/qytcoding/dubbo-demo
启动DubboProviderApplication类

**Comment by AlbumenJ** [comment]
这个应该是Dubbo启动顺序影响的，看了demo是应用内自己调用自己的，Dubbo 目前是先初始化消费端再初始化服务端的，所以在初始化消费端的时候服务端还没 ready，端口没打开，所以会报连接错误。可以拆分为两个应用，服务端先启动应该就没问题了

**Comment by AlbumenJ** [comment]
`@DubboReference(check = false)` 的作用是在检测报错的时候不中断初始化，如果过程中出现了连接不上日志可能还是要记录的，不然都不知道情况。这个报错本身不会有太大影响，但是还是建议先初始化 provider 再初始化 consumer

**Comment by coderSpw** [comment]
如果两个服务互相提供和消费的情况下，如何解决

**Comment by AlbumenJ** [comment]
> 如果两个服务互相提供和消费的情况下，如何解决

check 配置为 false。这种使用方式在生产中是不应该出现的，应该尽快被重构掉

**Comment by wenyyo** [comment]
> > 如果服务都提供和消费的情况下两个，如何解决
> 
> check 配置为 false。这种使用方式在生产中是不应该出现的，应该加速被重构掉



> `@DubboReference(check = false)`的作用是在检测报错的时候不中断初始化，如果过程中出现还是连接不上日志可能还是要记录的，否则都不知道情况。这个报错本身不会有严重的影响，但是建议先初始化provider再初始化消费者

配置中加了dubbo.reference.check=false且注解@DubboReference(check = false) 服务启动的时候仍然会校验提供方是否注册，如果提供方没注册，自己服务就起不来了，理论上说应该不会影响自己服务的启动了吧？
