### ISSUE TITLE
Dubbo3.0.8 正常停机时报错

### ISSUE THREAD

**Issue by GreatBareBear** [apache/dubbo#10124]
你好，windows10系统正常通过hook触发停机时会以下报错信息，该如何解决呢？

Dubbo配置：
    <dubbo:application name="${NAME}"/>
    <dubbo:registry cluster="failover" client="curator" protocol="zookeeper" address="${ADDRESS}" username="${USERNAME}" password="${PASSWORD}">
       	<dubbo:parameter key="qos.enable" value="true" />
		<dubbo:parameter key="qos.port" value="${PORT" />
 	</dubbo:registry>
	
    <dubbo:protocol name="dubbo" port="${PORT.DUBBO}" threads="100" serialization="kryo" optimizer="com.mobee.slot.rpc.dubbo.kryo.SerializationOptimizerImpl"/>
    <dubbo:provider server="netty" client="netty" cluster="failover" loadbalance="random" timeout="10000" retries="2"/>

日志错误信息：
2022-06-07 08:18:26,094 [DubboShutdownHook] INFO  o.a.d.c.d.DefaultApplicationDeployer -  [DUBBO] Dubbo Application[1.1](CENTER_SERVER_S1) has stopped., dubbo version: 3.0.8, current host: 192.168.100.181
2022-06-07 08:18:26,095 [Curator-Framework-0] INFO  o.a.c.f.imps.CuratorFrameworkImpl - backgroundOperationsLoop exiting2022-06-07 08:18:26,118 [main-SendThread(192.168.100.249:2181)] WARN  org.apache.zookeeper.ClientCnxn - An exception was thrown while closing send thread for session 0x100aaf0bf36014e.
org.apache.zookeeper.ClientCnxn$EndOfStreamException: Unable to read additional data from server sessionid 0x100aaf0bf36014e, likely server has closed socket
        at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1282)
2022-06-07 08:18:26,220 [DubboShutdownHook] INFO  org.apache.zookeeper.ZooKeeper - Session: 0x100aaf0bf36014e closed
2022-06-07 08:18:26,220 [main-EventThread] ERROR o.a.c.f.recipes.cache.NodeCache -
java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED]
        at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:823)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkState(CuratorFrameworkImpl.java:457)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkExists(CuratorFrameworkImpl.java:484)
        at org.apache.curator.framework.recipes.cache.NodeCache.reset(NodeCache.java:261)
        at org.apache.curator.framework.recipes.cache.NodeCache.access$100(NodeCache.java:60)
        at org.apache.curator.framework.recipes.cache.NodeCache$2.process(NodeCache.java:104)
        at org.apache.curator.framework.imps.NamespaceWatcher.process(NamespaceWatcher.java:77)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:578)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:553)
2022-06-07 08:18:26,220 [DubboShutdownHook] INFO  o.a.dubbo.rpc.model.FrameworkModel -  [DUBBO] Destroying default framework model: Dubbo Framework[1], dubbo version: 3.0.8, current host: 192.168.100.181
2022-06-07 08:18:26,221 [main-EventThread] ERROR o.a.c.f.recipes.cache.NodeCache -
java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED]
        at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:823)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkState(CuratorFrameworkImpl.java:457)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkExists(CuratorFrameworkImpl.java:484)
        at org.apache.curator.framework.recipes.cache.NodeCache.reset(NodeCache.java:261)
        at org.apache.curator.framework.recipes.cache.NodeCache.access$100(NodeCache.java:60)
        at org.apache.curator.framework.recipes.cache.NodeCache$2.process(NodeCache.java:104)
        at org.apache.curator.framework.imps.NamespaceWatcher.process(NamespaceWatcher.java:77)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:578)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:553)
2022-06-07 08:18:26,222 [DubboShutdownHook] INFO  o.a.dubbo.rpc.model.FrameworkModel -  [DUBBO] Dubbo Framework[1] is destroying ..., dubbo version: 3.0.8, current host: 192.168.100.181
2022-06-07 08:18:26,222 [main-EventThread] ERROR o.a.c.f.recipes.cache.NodeCache -
java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED]
        at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:823)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkState(CuratorFrameworkImpl.java:457)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkExists(CuratorFrameworkImpl.java:484)
        at org.apache.curator.framework.recipes.cache.NodeCache.reset(NodeCache.java:261)
        at org.apache.curator.framework.recipes.cache.NodeCache.access$100(NodeCache.java:60)
        at org.apache.curator.framework.recipes.cache.NodeCache$2.process(NodeCache.java:104)
        at org.apache.curator.framework.imps.NamespaceWatcher.process(NamespaceWatcher.java:77)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:578)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:553)
2022-06-07 08:18:26,222 [DubboShutdownHook] INFO  o.a.d.c.d.DefaultApplicationDeployer -  [DUBBO] Dubbo Application[1.0](DUBBO_INTERNAL_APPLICATION) is stopping., dubbo version: 3.0.8, current host: 192.168.100.181
2022-06-07 08:18:26,223 [main-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x100aaf0bf36014e
2022-06-07 08:18:26,223 [DubboShutdownHook] INFO  o.a.d.r.support.RegistryManager -  [DUBBO] Close all registries [], dubbo version: 3.0.8, current host: 192.168.100.181
2022-06-07 08:18:26,223 [DubboShutdownHook] INFO  o.a.d.c.deploy.DefaultModuleDeployer -  [DUBBO] Dubbo Module[1.0.0] is stopping., dubbo version: 3.0.8, current host: 192.168.100.181
2022-06-07 08:18:26,224 [DubboShutdownHook] INFO  o.a.d.c.deploy.DefaultModuleDeployer -  [DUBBO] Dubbo Module[1.0.0] has stopped., dubbo version: 3.0.8, current host: 192.168.100.181
2022-06-07 08:18:26,224 [DubboShutdownHook] INFO  o.a.d.c.t.m.DefaultExecutorRepository -  [DUBBO] destroying application executor repository .., dubbo version: 3.0.8, current host: 192.168.100.181

**Comment by AlbumenJ** [comment]
这个在我本地没有复现，可以看下是不是zk的链接提前断开了

**Comment by chickenlj** [comment]
Please provide more information and reopen. tks
