### ISSUE TITLE
spring boot 2.6.6 集成 dubbo 3.0.4启动报以下错误

### ISSUE THREAD

**Issue by pengsuwei** [apache/dubbo#10153]
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/core/metrics/ApplicationStartup
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:227)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:240)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290)
	at com.hihonor.ad.platform.engine.Application.main(Application.java:27)
Caused by: java.lang.ClassNotFoundException: org.springframework.core.metrics.ApplicationStartup
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more

### Environment

* Dubbo version: 3.0.4
* Operating System version: windows 10
* Java version: JDK 11 & Spring Boot 2.6.6

**Comment by chickenlj** [comment]
看起来是 spring 依赖之间的版本兼容问题

**Comment by pengsuwei** [comment]
是的，已排查出原因，引入以下dubbo依赖导致spring依赖冲突
            <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo-bom</artifactId>
                <version>3.0.4</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
