### ISSUE TITLE
ExtensionLoader cannot be resumed after interruption

### ISSUE THREAD

**Issue by AlbumenJ** [apache/dubbo#10191]
ExtensionLoader cannot be resumed after interruption.

```
java.lang.InterruptedException
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1302)
  at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
  at org.apache.dubbo.common.utils.ClassLoaderResourceLoader.loadResources(ClassLoaderResourceLoader.java:55)
  at org.apache.dubbo.common.extension.ExtensionLoader.loadDirectory(ExtensionLoader.java:1005)
  at org.apache.dubbo.common.extension.ExtensionLoader.loadDirectory(ExtensionLoader.java:943)
  at org.apache.dubbo.common.extension.ExtensionLoader.loadExtensionClasses(ExtensionLoader.java:931)
  at org.apache.dubbo.common.extension.ExtensionLoader.getExtensionClasses(ExtensionLoader.java:913)
  at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:752)
  at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:548)
  at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:523)
  at org.apache.dubbo.rpc.protocol.injvm.InjvmInvoker.<init>(InjvmInvoker.java:74)
```

**Comment by InscienceMan** [comment]
请问下，遇到相同问题并发加载Extension被interrupt，看本次merge只是把异常抛出，但是在类加载过程中调用这个并被interrupt岂不是不能恢复了

```
java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1302) ~[na:1.8.0_222]
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231) ~[na:1.8.0_222]
	at org.apache.dubbo.common.utils.ClassLoaderResourceLoader.loadResources(ClassLoaderResourceLoader.java:58) ~[dubbo-3.1.10.jar!/:3.1.10]
	at org.apache.dubbo.common.extension.ExtensionLoader.loadDirectoryInternal(ExtensionLoader.java:1051) [dubbo-3.1.10.jar!/:3.1.10]
	at org.apache.dubbo.common.extension.ExtensionLoader.loadDirectory(ExtensionLoader.java:974) [dubbo-3.1.10.jar!/:3.1.10]
	at org.apache.dubbo.common.extension.ExtensionLoader.loadExtensionClasses(ExtensionLoader.java:962) [dubbo-3.1.10.jar!/:3.1.10]
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtensionClasses(ExtensionLoader.java:939) [dubbo-3.1.10.jar!/:3.1.10]
	at org.apache.dubbo.common.extension.ExtensionLoader.getSupportedExtensions(ExtensionLoader.java:601) [dubbo-3.1.10.jar!/:3.1.10]
	at org.apache.dubbo.remoting.transport.CodecSupport.<clinit>(CodecSupport.java:58) [dubbo-3.1.10.jar!/:3.1.10]
```

服务启动后调用直接报错
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.dubbo.remoting.transport.CodecSupport
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.prepareInvocation(AbstractInvoker.java:200) ~[dubbo-3.1.10.jar!/:3.1.10]
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:180) ~[dubbo-3.1.10.jar!/:3.1.10]
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:71) ~[dubbo-3.1.10.jar!/:3.1.10]
```

**Comment by AlbumenJ** [comment]
> 请问下，遇到相同问题并发加载Extension被interrupt，看本次merge只是把异常抛出，但是在类加载过程中调用这个并被interrupt岂不是不能恢复了
> 
> ```
> java.lang.InterruptedException: null
> 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1302) ~[na:1.8.0_222]
> 	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231) ~[na:1.8.0_222]
> 	at org.apache.dubbo.common.utils.ClassLoaderResourceLoader.loadResources(ClassLoaderResourceLoader.java:58) ~[dubbo-3.1.10.jar!/:3.1.10]
> 	at org.apache.dubbo.common.extension.ExtensionLoader.loadDirectoryInternal(ExtensionLoader.java:1051) [dubbo-3.1.10.jar!/:3.1.10]
> 	at org.apache.dubbo.common.extension.ExtensionLoader.loadDirectory(ExtensionLoader.java:974) [dubbo-3.1.10.jar!/:3.1.10]
> 	at org.apache.dubbo.common.extension.ExtensionLoader.loadExtensionClasses(ExtensionLoader.java:962) [dubbo-3.1.10.jar!/:3.1.10]
> 	at org.apache.dubbo.common.extension.ExtensionLoader.getExtensionClasses(ExtensionLoader.java:939) [dubbo-3.1.10.jar!/:3.1.10]
> 	at org.apache.dubbo.common.extension.ExtensionLoader.getSupportedExtensions(ExtensionLoader.java:601) [dubbo-3.1.10.jar!/:3.1.10]
> 	at org.apache.dubbo.remoting.transport.CodecSupport.<clinit>(CodecSupport.java:58) [dubbo-3.1.10.jar!/:3.1.10]
> ```
> 
> 服务启动后调用直接报错
> 
> ```
> Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.dubbo.remoting.transport.CodecSupport
> 	at org.apache.dubbo.rpc.protocol.AbstractInvoker.prepareInvocation(AbstractInvoker.java:200) ~[dubbo-3.1.10.jar!/:3.1.10]
> 	at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:180) ~[dubbo-3.1.10.jar!/:3.1.10]
> 	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:71) ~[dubbo-3.1.10.jar!/:3.1.10]
> ```

Could you please try to fix it? We should refactor the static blocks in `CodecSupport` and make it lazy inited.
