### ISSUE TITLE
[3.0]Application discovery use http protocol throw NPX

### ISSUE THREAD

**Issue by haoyann** [apache/dubbo#10209]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.8
* Operating System version: xxx
* Java version: 1.8

### Steps to reproduce this issue

1. Import `dubbo-rpc-http` 
  ```
        <dependency>
            <groupId>org.apache.dubbo.extensions</groupId>
            <artifactId>dubbo-rpc-http</artifactId>
            <version>1.0.0</version>
            <exclusions>
                <exclusion>
                    <artifactId>dubbo-cluster</artifactId>
                    <groupId>org.apache.dubbo</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>dubbo-remoting-http</artifactId>
                    <groupId>org.apache.dubbo</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>dubbo-rpc-api</artifactId>
                    <groupId>org.apache.dubbo</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spring-context</artifactId>
                    <groupId>org.springframework</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-server</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-servlet</artifactId>
        </dependency>
  ```
2. Provider use `http` protocol 
   `dubbo.protocol.name=http`
3. Consumer reference use `http` protocol 
    `@DubboReference(protocol = "http")`

### Actual Behavior

If there is an exception, please attach the exception trace:

```
java.lang.NullPointerException
	at org.apache.dubbo.common.URL.setProtocol(URL.java:347)
	at org.apache.dubbo.rpc.protocol.http.HttpProtocol.doRefer(HttpProtocol.java:143)
	at org.apache.dubbo.rpc.protocol.AbstractProxyProtocol.protocolBindingRefer(AbstractProxyProtocol.java:109)
	at org.apache.dubbo.rpc.protocol.AbstractProtocol.refer(AbstractProtocol.java:126)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:77)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:85)
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:74)
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:52)
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.toInvokers(ServiceDiscoveryRegistryDirectory.java:294)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.refreshInvoker(ServiceDiscoveryRegistryDirectory.java:225)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.refreshOverrideAndInvoker(ServiceDiscoveryRegistryDirectory.java:153)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.notify(ServiceDiscoveryRegistryDirectory.java:147)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.lambda$notifyAddressChanged$5(ServiceInstancesChangedListener.java:397)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.notifyAddressChanged(ServiceInstancesChangedListener.java:388)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.doOnEvent(ServiceInstancesChangedListener.java:199)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.onEvent(ServiceInstancesChangedListener.java:112)
	at org.apache.dubbo.registry.zookeeper.ZookeeperServiceDiscovery.registerServiceWatcher(ZookeeperServiceDiscovery.java:171)
	at org.apache.dubbo.registry.zookeeper.ZookeeperServiceDiscovery.lambda$addServiceInstancesChangedListener$3(ZookeeperServiceDiscovery.java:120)
```
### How to solve
HttpProtocol will set url protocol to `http` , but `InstanceAddressURL#urlAddress`  is null. 

https://github.com/apache/dubbo-spi-extensions/blob/1a30787aee2dcab44c39c122120932dc5d0a2786/dubbo-rpc-extensions/dubbo-rpc-http/src/main/java/org/apache/dubbo/rpc/protocol/http/HttpProtocol.java#L143

![image](https://user-images.githubusercontent.com/43994656/175488798-25198fbf-1b5d-4a46-b555-d733eccb19f9.png)

Url protocol already is `http` , maybe this step should be removed.
![image](https://user-images.githubusercontent.com/43994656/175489138-a713ba03-8966-4410-be35-f677bfef7e93.png)

**Comment by MartianQiu** [comment]
I'll fix it, please assign to me.

**Comment by haoyann** [comment]
Fixed close.
