### ISSUE TITLE
启动时报java.lang.UnsupportedOperationException导致无法运行

### ISSUE THREAD

**Issue by applecyg** [apache/dubbo#10257]
org.apache.dubbo:dubbo:3.0.7及以上版本，程序运行会出现如下异常：
java.lang.IllegalStateException: Failed to override field value of config bean: <dubbo:service path="com.test.ApiDubboService" version="1.0.0" deprecated="false" protocolIds="dubbo" dynamic="true" id="ServiceBean:com.test.ApiDubboService:1.0.0" ref="com.test.ApiDubboServiceImpl@59e9bb43" interface="com.test.ApiDubboService" />
	at org.apache.dubbo.config.AbstractConfig.refresh(AbstractConfig.java:696) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServiceInternal(DefaultModuleDeployer.java:320) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServices(DefaultModuleDeployer.java:313) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:145) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:111) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:100) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:45) ~[dubbo-3.0.9.jar:3.0.9]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.21.jar:5.3.21]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.21.jar:5.3.21]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.21.jar:5.3.21]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.21.jar:5.3.21]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.21.jar:5.3.21]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938) ~[spring-context-5.3.21.jar:5.3.21]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.21.jar:5.3.21]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.1.jar:2.7.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.1.jar:2.7.1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.1.jar:2.7.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.1.jar:2.7.1]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164) ~[spring-boot-2.7.1.jar:2.7.1]
	at com.apsaras.platform.container.boot.PlatformJavaApplicationAw.main(PlatformJavaApplicationAw.java:37) ~[apsaras-pandora-launcher-2.0.0.RELEASE.jar:?]
	at com.brilliance.TestApplication.main(TestApplication.java:13) ~[test-classes/:?]
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractMap.put(AbstractMap.java:209) ~[?:?]
	at java.util.AbstractMap.putAll(AbstractMap.java:281) ~[?:?]
	at org.apache.dubbo.config.AbstractConfig.invokeSetParameters(AbstractConfig.java:828) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.config.AbstractConfig.assignProperties(AbstractConfig.java:766) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.config.AbstractConfig.refresh(AbstractConfig.java:689) ~[dubbo-3.0.9.jar:3.0.9]
	... 20 more
异常出现原因：在org.apache.dubbo.config.AbstractConfig类中如下函数中((Map)map).putAll(values);出错，真正的map是java.util.Collections.EmptyMap实例，此类没有实现put。
private void invokeSetParameters(Map<String, String> values, Object obj) {
        if (!CollectionUtils.isEmptyMap(values)) {
            Map<String, String> map = invokeGetParameters(obj.getClass(), obj);
            Map<String, String> map = map == null ? new HashMap() : map;
            ((Map)map).putAll(values);  /////此处
            invokeSetParameters(obj.getClass(), obj, (Map)map);
        }
    }
问题重现步骤：
1、在项目中定义一个xml配置文件，添加一些服务提供者参数，如将此配置文件命名为dubbo-conf.xml
<dubbo:provider protocol="dubbo" threads="1000" threadpool="cached" dispatcher="message">
        <dubbo:parameter key="appType" value="xxxxxxx"></dubbo:parameter>
</dubbo:provider>
2、通过@ImportResource(locations = {"classpath*:dubbo-conf.xml"})引入配置。
3、项目中任意做一个dubbo服务，运行程序则会出现如上异常导致程序不能正常启动。

**Comment by applecyg** [comment]
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/421994/177001450-24465533-a470-482d-aaa3-09b35aa7f049.png">

**Comment by AlbumenJ** [comment]
Would you please submit a PR to fix this?

**Comment by applecyg** [comment]
问题的根源在于org.apache.dubbo.config.spring.util.DubboAnnotationUtils类中的public static Map<String, String> convertParameters(String[] parameters)中的差异，在3.0.6及之前版本ArrayUtils.isEmpty(parameters)为空时直接返回的是null，在3.0.7开始的版本返回的是Collections.emptyMap();

当dubbo的服务bean的定义时用到了这个方法，见org.apache.dubbo.config.spring.beans.factory.annotation.ServiceAnnotationPostProcessor类的buildServiceBeanDefinition方法
<img width="1428" alt="Pasted Graphic 4" src="https://user-images.githubusercontent.com/421994/177032573-65d2ec96-3d66-478a-8feb-91e5654b263b.png">

在程序运行时refresh会调用到org.apache.dubbo.config.AbstractConfig的assignProperties方法，此方法又会调用到invokeSetParameters方法，在invokeSetParameters方法中又会调用private static Map<String, String> invokeGetParameters(Class c, Object o)方法，此方法里面有一个method的反射调用，其实最终调用到org.apache.dubbo.config.AbstractMethodConfig的getParameters方法，那么就要看setParameters是何时调用的了，
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/421994/177033265-4a26a988-29e3-4fe0-b803-9c0e9c621297.png">
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/421994/177033298-d63e6079-a11d-4f58-b6ba-6e0e5538debb.png">
通过追踪也就知道问题的症结就在于bean定义时赋值的Collections.emptyMap();导致的。

因此建议综合考虑org.apache.dubbo.config.spring.util.DubboAnnotationUtils.convertParameters的差异性

**Comment by cheese8** [comment]
> 问题的根源在于org.apache.dubbo.config.spring.util.DubboAnnotationUtils类中的public static Map<String, String> convertParameters(String[] parameters)中的差异，在3.0.6及之前版本ArrayUtils.isEmpty(parameters)为空时直接返回的是null，在3.0.7开始的版本返回的是Collections.emptyMap();
> 
> 当dubbo的服务bean的定义时用到了这个方法，见org.apache.dubbo.config.spring.beans.factory.annotation.ServiceAnnotationPostProcessor类的buildServiceBeanDefinition方法 <img alt="Pasted Graphic 4" width="1428" src="https://user-images.githubusercontent.com/421994/177032573-65d2ec96-3d66-478a-8feb-91e5654b263b.png">
> 
> 在程序运行时refresh会调用到org.apache.dubbo.config.AbstractConfig的assignProperties方法，此方法又会调用到invokeSetParameters方法，在invokeSetParameters方法中又会调用private static Map<String, String> invokeGetParameters(Class c, Object o)方法，此方法里面有一个method的反射调用，其实最终调用到org.apache.dubbo.config.AbstractMethodConfig的getParameters方法，那么就要看setParameters是何时调用的了， <img alt="image" width="1250" src="https://user-images.githubusercontent.com/421994/177033265-4a26a988-29e3-4fe0-b803-9c0e9c621297.png"> <img alt="image" width="1430" src="https://user-images.githubusercontent.com/421994/177033298-d63e6079-a11d-4f58-b6ba-6e0e5538debb.png"> 通过追踪也就知道问题的症结就在于bean定义时赋值的Collections.emptyMap();导致的。
> 
> 因此建议综合考虑org.apache.dubbo.config.spring.util.DubboAnnotationUtils.convertParameters的差异性

返回emptyMap比null好。

**Comment by applecyg** [comment]
既然返回emptyMap比null好是从全局性考虑，那么这个异常问题建议从局部改，org.apache.dubbo.config.AbstractConfig的方法
private void invokeSetParameters(Map<String, String> values, Object obj) {
        if (!CollectionUtils.isEmptyMap(values)) {
            Map<String, String> map = invokeGetParameters(obj.getClass(), obj);
            Map<String, String> map = **(map == null || map.equals(Collections.emptyMap()))** ? new HashMap() : map;
            ((Map)map).putAll(values);
            invokeSetParameters(obj.getClass(), obj, (Map)map);
        }
    }

加上Collections.emptyMap()判断即用HashMap

**Comment by AlbumenJ** [comment]
org.apache.dubbo.config.spring.util.DubboAnnotationUtils#convertParameters 的 `Collections.emptyMap()` 换成 new HashMap 是不是就可以了

**Comment by cheese8** [comment]
> 

1、return new HashMap<>()这种返回空Map写法，一般都会写成Collections.emptyMap()
2、判断map.equals(Collections.emptyMap())不知道说什么好

**Comment by applecyg** [comment]
原则上来说换成new HashMap是没有问题的，但从整体来说我也不确定从3.0.6之后换成Collections.emptyMap()是处于何种考虑而改，搜了一下这个方法在整个项目中的使用地方，只有两处，因此改成new HashMap要考虑另一处是否有影响。其实此处返回Collections.emptyMap()或null个人感觉比new HashMap好。

**Comment by AlbumenJ** [comment]
> 原则上来说换成new HashMap是没有问题的，但从整体来说我也不确定从3.0.6之后换成Collections.emptyMap()是处于何种考虑而改，搜了一下这个方法在整个项目中的使用地方，只有两处，因此改成new HashMap要考虑另一处是否有影响。其实此处返回Collections.emptyMap()或null个人感觉比new HashMap好。

换成 Collections.emptyMap() 是为了解决之前 null 的时候 get 出现 NPE

**Comment by AlbumenJ** [comment]
> 综合考虑吧： 1、return new HashMap<>()这种返回空Map写法，一般都会写成Collections.emptyMap() 2、判断map.equals(Collections.emptyMap())不知道咋说

1 2 两种对比起来个人感觉 1 比较好接受些 :)

**Comment by applecyg** [comment]
我个人感觉org.apache.dubbo.config.spring.util.DubboAnnotationUtils#convertParameters虽然是引起本bug的源头，但问题点org.apache.dubbo.config.AbstractConfig#invokeSetParameters里面确有需要斟酌的地方，毕竟map有时获得的就是Collections.emptyMap()，而此实例putAll确实会抛异常。因此怎么避免此处的Collections.emptyMap()情况或出现Collections.emptyMap()情况下的措施则是解决此bug的关键。因此对于Collections.emptyMap()做相应判断处理在此处我个人认为是需要的。

**Comment by AlbumenJ** [comment]
> 我个人感觉org.apache.dubbo.config.spring.util.DubboAnnotationUtils#convertParameters虽然是引起本bug的源头，但问题点org.apache.dubbo.config.AbstractConfig#invokeSetParameters里面确有需要斟酌的地方，毕竟map有时获得的就是Collections.emptyMap()，而此实例putAll确实会抛异常。因此怎么避免此处的Collections.emptyMap()情况或出现Collections.emptyMap()情况下的措施则是解决此bug的关键。因此对于Collections.emptyMap()做相应判断处理在此处我个人认为是需要的。

https://github.com/apache/dubbo/pull/10262 已经合并了

**Comment by applecyg** [comment]
超级棒，谢谢！
