### ISSUE TITLE
org.apache.dubbo.remoting.RemotingException: 0

### ISSUE THREAD

**Issue by 13567436138** [apache/dubbo#10273]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.03
* Operating System version: xxx
* Java version: 1.8

### Steps to reproduce this issue

```
SEVERE: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.apache.dubbo.rpc.RpcException: Failed to invoke the method dubboCallProiderService in the service org.example.api.ITestService. Tried 3 times of the providers [dubbo-hello-provider:20880] (1/1) from the registry dubbo-hello-provider:20880 on the consumer 172.20.0.245 using the dubbo version 3.0.3. Last error is: Failed to invoke remote method: dubboCallProiderService, provider: dubbo://dubbo-hello-provider:20880/org.example.api.ITestService?application=dubbo-demo-consumer&check=false&interface=org.example.api.ITestService&pid=1&qos.enable=false&register.ip=172.20.0.245&side=consumer&sticky=false, cause: org.apache.dubbo.remoting.RemotingException: 0] with root cause
org.apache.dubbo.remoting.RemotingException: 0
        at org.apache.dubbo.remoting.exchange.support.DefaultFuture.doReceived(DefaultFuture.java:207)
        at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:170)
        at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:158)
        at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleResponse(HeaderExchangeHandler.java:60)
        at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:181)
        at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
        at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
        at org.apache.dubbo.common.threadpool.ThreadlessExecutor$RunnableWrapper.run(ThreadlessExecutor.java:196)
        at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:99)
        at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:179)
        at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:275)
        at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:182)
        at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:78)
        at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invokeWithContext(AbstractClusterInvoker.java:300)
        at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:79)
        at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:268)
        at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:89)
        at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:84)
        at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:51)
        at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:84)
        at org.apache.dubbo.rpc.cluster.filter.support.ConsumerContextFilter.invoke(ConsumerContextFilter.java:108)
        at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:84)
        at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$ClusterFilterInvoker.invoke(AbstractCluster.java:92)
        at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:94)
        at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:92)
        at org.apache.dubbo.common.bytecode.proxy2.dubboCallProiderService(proxy2.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
        at com.sun.proxy.$Proxy59.dubboCallProiderService(Unknown Source)
        at org.example.DubboconsumerApplication.test(DubboconsumerApplication.java:38)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1064)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:228)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

client:
```
package org.example;

import org.apache.dubbo.config.annotation.DubboReference;
import org.apache.dubbo.config.spring.context.annotation.EnableDubboConfig;
import org.example.api.IGroupService;
import org.example.api.ITestService;
import org.example.api.IVersionService;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@SpringBootApplication
@EnableDubboConfig
@Controller
public class DubboconsumerApplication {
    @DubboReference(url="dubbo://dubbo-hello-provider:20880",check = false)
    private ITestService testService;
    @DubboReference(url="dubbo://dubbo-hello-provider:20880",check = false)
    private IGroupService iGroupService;
    @DubboReference(url="dubbo://dubbo-hello-provider:20880",check = false)
    private IVersionService iVersionService;

    public static void main(String[] args) {
        SpringApplication.run(DubboconsumerApplication.class, args);
    }

    /**
     * 测试
     * @param id 消息
     * @return 结果
     */
    @RequestMapping("/test")
    @ResponseBody
    public String test(@RequestParam("id") int id) {
        String result = testService.dubboCallProiderService(String.valueOf(id));
        return result;
    }

    @RequestMapping("/test/group")
    @ResponseBody
    public String testgroup(@RequestParam("id") int id) {
        String result = iGroupService.dubboCallProiderService(String.valueOf(id));
        return result;
    }

    @RequestMapping("/test/version")
    @ResponseBody
    public String testversion(@RequestParam("id") int id) {
        String result = iVersionService.dubboCallProiderService(String.valueOf(id));
        return result;
    }
}
```
```
dubbo:
  protocol:
    name: dubbo
    port: 20880
  application:
    name: dubbo-demo-consumer
    id: dubbo-demo-consumer
server:
  port: 8081
spring:
  application:
    name: dubbo-demo-consumer

```

server:
```
package org.example.impl;

import com.alibaba.dubbo.config.annotation.Service;
import org.apache.dubbo.config.annotation.DubboService;
import org.example.api.ITestService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.env.Environment;
import org.springframework.stereotype.Component;

@Component
@DubboService(interfaceClass = ITestService.class)
public class TestServiceImpl  implements ITestService {
    @Autowired
    private Environment env;

    @Override
    public String dubboCallProiderService(String params) {
        System.out.println("TestService dubboCallProiderService : " + params);
        return "hello"+env.getProperty("version")+" ： " + params;
    }
}

```
```
dubbo:
  application:
    name: dubbo-demo-provider
    id: dubbo-demo-provider
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: org.example
spring:
  application:
    name: dubbo-demo-provider
```
Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by jk-tonycui** [comment]
从报错看，是负载的时候没有找到 dubbo-hello-provider:20880 的实例。如果用这种方式是要依赖k8s的svc发现能力？

**Comment by chickenlj** [comment]
从堆栈来看，像是请求已经送达 provider 侧后收到了 RemotingException。可以检查下 provider 侧有没有异常信息

**Comment by chickenlj** [comment]
> org.apache.dubbo.remoting.RemotingException: 0

这个异常暂时没有匹配到框架内的任何具体异常点，所以还不确定是哪个位置、哪个组件报的错，需要协助排查一下

**Comment by Oliverwqcwrw** [comment]
没有配置注册中心调不通吧，没看到关于注册中心的配置呢

**Comment by chickenlj** [comment]
Could not reproduce, reopen when more informations provided

**Comment by wenlong139** [comment]
我也遇到这个问题了 dubbo版本 2.7

**Comment by wenlong139** [comment]
> * issues

我的场景是 service-mesh  使用腾讯的开源组件aeraki 创建这种小写域名

**Comment by AlbumenJ** [comment]
> > * issues
> 
> 我的场景是 service-mesh 使用腾讯的开源组件aeraki 创建这种小写域名

可以把能稳定复现的方式整理下吗

**Comment by zhaohuabing** [comment]
如果有重现的环境的话，我可以看一下 @wenlong139
