### ISSUE TITLE
ExtensionDirector is destroyed

### ISSUE THREAD

**Issue by neverlaughtingboy** [apache/dubbo#10394]
- [ ✅] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
which condition will trigger this error：
java.lang.IllegalStateException: ExtensionDirector is destroyed

**Comment by liuzhiguo630** [comment]
+1
补充下我这边遇到的报错信息，看起来停机时，只有 triple 协议没有关闭掉，还有请求调过来
```
[ERROR][2022-09-18 15:52:08.875][tri-protocol-20881-thread-200][org.apache.dubbo.rpc.filter.ExceptionFilter]  [DUBBO] Got unchecked and undeclared exception which called by 172.17.0.221. service: cn.jojo.api.service.bs.ms.IMediaService, method: getEditMediaResult, exception: java.lang.IllegalStateException: ExtensionDirector is destroyed, dubbo version: 3.1.0, current host: 172.17.0.28
java.lang.IllegalStateException: ExtensionDirector is destroyed
	at org.apache.dubbo.common.extension.ExtensionDirector.checkDestroyed(ExtensionDirector.java:157)
	at org.apache.dubbo.common.extension.ExtensionDirector.getExtensionLoader(ExtensionDirector.java:68)
	at org.apache.dubbo.common.extension.ExtensionAccessor.getExtensionLoader(ExtensionAccessor.java:27)
	at org.apache.dubbo.validation.Validation$Adaptive.getValidator(Validation$Adaptive.java)
	at org.apache.dubbo.validation.filter.ValidationFilter.invoke(ValidationFilter.java:88)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:326)
	at cn.jojo.infra.sdk.i18n.I18nDubboFilter.invoke(I18nDubboFilter.java:45)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:326)
	at cn.jojo.infra.sdk.rpc.dubbo.filter.MockFilter.invoke(MockFilter.java:52)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:326)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:77)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:326)
	at cn.jojo.infra.sdk.rpc.dubbo.filter.TraceFilter.invoke(TraceFilter.java:22)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:326)
	at org.apache.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:46)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:326)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke$original$xp2Hd4eO(MonitorFilter.java:99)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke$original$xp2Hd4eO$accessor$mqtVihNc(MonitorFilter.java)
	at org.apache.dubbo.monitor.support.MonitorFilter$auxiliary$4oveAI0y.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:326)
	at org.apache.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:52)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:326)
	at cn.jojo.infra.sdk.metrics.dubbo.AbstractMetricsFilter.invoke(AbstractMetricsFilter.java:56)
	at cn.jojo.infra.sdk.metrics.dubbo.DubboProviderMetricsFilter.invoke(DubboProviderMetricsFilter.java:40)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:326)
	at cn.jojo.infra.sdk.sentinel.adapter.dubbo.DubboProviderFilter.invoke(DubboProviderFilter.java:64)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:326)
	at cn.jojo.infra.sdk.context.request.plugins.dubbo.DubboProviderFilter.lambda$invoke$0(DubboProviderFilter.java:33)
	at cn.jojo.infra.sdk.context.request.plugins.RequestContextUpstreamHandler.injectContext(RequestContextUpstreamHandler.java:92)
	at cn.jojo.infra.sdk.context.request.plugins.RequestContextUpstreamHandler.injectContext(RequestContextUpstreamHandler.java:38)
	at cn.jojo.infra.sdk.context.request.plugins.dubbo.DubboProviderFilter.invoke(DubboProviderFilter.java:33)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:326)
	at org.apache.dubbo.auth.filter.ProviderAuthFilter.invoke(ProviderAuthFilter.java:53)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:326)
	at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:191)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:326)
	at org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:54)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:326)
	at org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:41)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:326)
	at org.apache.dubbo.rpc.filter.ProfilerServerFilter.invoke(ProfilerServerFilter.java:56)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:326)
	at org.apache.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:131)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:326)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CallbackRegistrationInvoker.invoke(FilterChainBuilder.java:193)
	at org.apache.dubbo.rpc.protocol.tri.call.AbstractServerCallListener.invoke(AbstractServerCallListener.java:61)
	at org.apache.dubbo.rpc.protocol.tri.call.UnaryServerCallListener.onComplete(UnaryServerCallListener.java:55)
	at org.apache.dubbo.rpc.protocol.tri.call.AbstractServerCall.onComplete(AbstractServerCall.java:172)
	at org.apache.dubbo.rpc.protocol.tri.stream.TripleServerStream$ServerTransportObserver$ServerDecoderListener.close(TripleServerStream.java:440)
	at org.apache.dubbo.rpc.protocol.tri.frame.TriDecoder.deliver(TriDecoder.java:102)
	at org.apache.dubbo.rpc.protocol.tri.frame.TriDecoder.close(TriDecoder.java:68)
	at org.apache.dubbo.rpc.protocol.tri.stream.TripleServerStream$ServerTransportObserver.doOnData(TripleServerStream.java:410)
	at org.apache.dubbo.rpc.protocol.tri.stream.TripleServerStream$ServerTransportObserver.lambda$onData$1(TripleServerStream.java:401)
	at org.apache.dubbo.common.threadpool.serial.SerializingExecutor.run(SerializingExecutor.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
	at java.lang.Thread.run(Thread.java:748)
```
