### ISSUE TITLE
能否彻底解决reconnect问题,  provider 关闭, consumer netty会永远重试旧的无效ip

### ISSUE THREAD

**Issue by moowcharnfu** [apache/dubbo#10477]
场景
docker容器，重启ip变更
dubbo 3.0.2.1
启动provider  ， consumer , ->  正常后   -> 关闭并重启provider   
！！！！！  consumer必现ReconnectTimerTask ，一直在重试   ！！！！！！

能否彻底解决下，   或者提供配置项，让调用方自己关闭

[dubbo-client-idleCheck-thread-1] ERROR org.apache.dubbo.remoting.exchange.support.header.ReconnectTimerTask -  [DUBBO] Fail to connect to HeaderExchangeClient [channel=org.apache.dubbo.remoting.transport.netty4.NettyClient [/******* -> /*****]], dubbo version: 3.0.2.1, current host: *****
org.apache.dubbo.remoting.RemotingException: client(url: dubbo://********* from netty client ******** using dubbo version 3.0.2.1
    at org.apache.dubbo.remoting.transport.netty4.NettyClient.doConnect(NettyClient.java:176) ~[dubbo-3.0.2.1.jar!/:3.0.2.1]
    at org.apache.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:197) ~[dubbo-3.0.2.1.jar!/:3.0.2.1]
    at org.apache.dubbo.remoting.transport.AbstractClient.reconnect(AbstractClient.java:253) ~[dubbo-3.0.2.1.jar!/:3.0.2.1]
    at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeClient.reconnect(HeaderExchangeClient.java:166) ~[dubbo-3.0.2.1.jar!/:3.0.2.1]
    at org.apache.dubbo.remoting.exchange.support.header.ReconnectTimerTask.doTask(ReconnectTimerTask.java:49) ~[dubbo-3.0.2.1.jar!/:3.0.2.1]
    at org.apache.dubbo.remoting.exchange.support.header.AbstractTimerTask.run(AbstractTimerTask.java:87) ~[dubbo-3.0.2.1.jar!/:3.0.2.1]
    at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:648) ~[dubbo-3.0.2.1.jar!/:3.0.2.1]
    at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:727) ~[dubbo-3.0.2.1.jar!/:3.0.2.1]
    at org.apache.dubbo.common.timer.HashedWheelTimer$Worker.run(HashedWheelTimer.java:449) ~[dubbo-3.0.2.1.jar!/:3.0.2.1]
    at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_192]

**Comment by AlbumenJ** [comment]
reconnect的状态是在服务端由于网络等原因离线，但是注册中心并没有踢出该 IP 的阶段。
从高可用和健壮性的本方面考虑，如果服务端抖动掉线了就不再重试会导致服务端地址越来越少，最终直接调不通。
