### ISSUE TITLE
adding a method in IDubboService may cause "Service not found" exception.

### ISSUE THREAD

**Issue by H-Bob** [apache/dubbo#10479]
- [X] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.7
* Operating System version: macOS 12.1
* Java version: 17

### Steps to reproduce this issue

1. IDubboService has a method which named **methodA**.
2. deploy IDubboService to **serverA**.
3. add a method whose name is **methodB** to IDubboService in **myLocalServer** but not in serverA
4. serverA and myLocalServer use the same register-center. 
5. when consumer side invokes IDubboService.methodB(), both of the providers in serverA and myLocalServer can be selected. 
6. then it will cause an exception that is "java.lang.IllegalArgumentException: Service not found:com.xxx. IDubboService, methodB" if it chose serverA as result-invoker  according to router and loadbalance rules.

### Expected Behavior

The expected behavior is that it only chose myLocalServer who has methodB as provider or result-invoker. 

### Actual Behavior

exception trace is here:

```
java.lang.IllegalArgumentException: Service not found:com.garena.core.logic.rpcservice.login.server.ILoginServerService, ping2
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:205)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:93)
	at org.apache.dubbo.remoting.transport.DecodeHandler.decode(DecodeHandler.java:57)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:44)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

I am confused that whether it is designed to be this or it is a bug. If it should be this, can anybody tell me why?

**Comment by AlbumenJ** [comment]
Dubbo consumers will now not check for method existence. Please try specifying another version for the service when upgrading. 
https://dubbo.apache.org/zh/docs3-v2/java-sdk/advanced-features-and-usage/service/multi-versions/

**Comment by H-Bob** [comment]
> Dubbo consumers will now not check for method existence. Please try specifying another version for the service when upgrading.
> https://dubbo.apache.org/zh/docs3-v2/java-sdk/advanced-features-and-usage/service/multi-versions/

Thank you so much. I learned that Dubbo service detective can based on interface or application but not method.
