### ISSUE TITLE
k8s 环境发布代码，provider重启后consumer无法找到服务提供者，consumer订阅旧的IP

### ISSUE THREAD

**Issue by wenlincheng** [apache/dubbo#10484]
* Dubbo version: 3.0.10
* Java version: 1.8
* SpringBoot：2.3.2
* Nacos: 2.0.3

### provider 重启中打印的日志，可以看到绑定的ip为 172.30.19.7

```
[DUBBO] Ignore empty notify urls for subscribe url provider://172.30.19.7:20880/com.xxxxxx.service.SubMailService?anyhost=true&application=ark-sailor&background=false&bind.ip=172.30.19.7&bind.port=20880&category=configurators&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.daddylab.ark.sailor.open.service.SubMailService&logger=slf4j&methods=verifyCode,send
```

### provider 重启后 consumer 打印日志 172.30.19.10:48052 -> /172.30.19.36:20880 is disconnected 连接已经断开
```
2022-08-19 14:02:28.031  INFO 7 --- [NettyClientWorker-12-2] o.a.d.r.t.netty4.NettyClientHandler      :   sampled:  [DUBBO] The connection of /172.30.19.10:42880 -> /172.30.19.36:20880 is disconnected., dubbo version: 3.0.10, current host: 172.30.19.10
2022-08-19 14:03:19.028  INFO 7 --- [client-idleCheck-thread-1] o.a.d.r.e.s.header.ReconnectTimerTask    :   sampled:  [DUBBO] Initial connection to HeaderExchangeClient [channel=org.apache.dubbo.remoting.transport.netty4.NettyClient [/172.30.19.10:42880 -> /172.30.19.36:20880]], dubbo version: 3.0.10, current host: 172.30.19.10
2022-08-19 14:03:19.028  INFO 7 --- [client-idleCheck-thread-1] o.a.d.r.transport.netty4.NettyChannel    :   sampled:  [DUBBO] Close netty channel [id: 0xb0d101c7, L:/172.30.19.10:42880 ! R:/172.30.19.36:20880], dubbo version: 3.0.10, current host: 172.30.19.10
2022-08-19 14:03:19.030  INFO 7 --- [client-idleCheck-thread-1] o.a.d.r.transport.netty4.NettyClient     :   sampled:  [DUBBO] Close old netty channel [id: 0xb0d101c7, L:/172.30.19.10:42880 ! R:/172.30.19.36:20880] on create new netty channel [id: 0xaf4964fc, L:/172.30.19.10:48052 - R:/172.30.19.36:20880], dubbo version: 3.0.10, current host: 172.30.19.10
2022-08-19 14:03:19.030  INFO 7 --- [NettyClientWorker-12-3] o.a.d.r.t.netty4.NettyClientHandler      :   sampled:  [DUBBO] The connection of /172.30.19.10:48052 -> /172.30.19.36:20880 is established., dubbo version: 3.0.10, current host: 172.30.19.10
2022-08-19 14:03:19.030  INFO 7 --- [client-idleCheck-thread-1] o.a.d.remoting.transport.AbstractClient  :   sampled:  [DUBBO] Successfully connect to server /172.30.19.36:20880 from NettyClient 172.30.19.10 using dubbo version 3.0.10, channel is NettyChannel [channel=[id: 0xaf4964fc, L:/172.30.19.10:48052 - R:/172.30.19.36:20880]], dubbo version: 3.0.10, current host: 172.30.19.10
2022-08-19 14:03:29.031  INFO 7 --- [NettyClientWorker-12-3] o.a.d.r.t.netty4.NettyClientHandler      :   sampled:  [DUBBO] The connection of /172.30.19.10:48052 -> /172.30.19.36:20880 is disconnected.
```
### 调用报错，consumer仍然找provider旧的ip地址172.30.19.36 ，provider重启后ip地址已经变为了 172.30.19.7
```
Failed to invoke the method getOptUser in the service com.xxxxx.system.service.ISysUserService. 
Tried 3 times of the providers [172.30.19.36:20880] (1/1) from the registry 172.16.12.151:8848 on the consumer 172.30.19.10 using the dubbo version 3.0.10. 
Last error is: Invoke remote method timeout. method: getOptUser, 
provider: dubbo://172.30.19.36:20880/com.xxxxxx.system.service.ISysUserService?anyhost=true&application=ark-sailor&background=false&category=providers&check=false&deprecated=false&d
  
```

**Comment by AlbumenJ** [comment]
这个需要看下是不是注册中心地址没更新

**Comment by AlbumenJ** [comment]
这个需要看下是不是注册中心地址没更新

**Comment by wenlincheng** [comment]
> 这个需要看下是不是注册中心地址没更新

注册中心地址应该是不变的吧

**Comment by wenlincheng** [comment]
> 这个需要看下是不是注册中心地址没更新

一直是这个 172.16.12.151:8848

**Comment by wenlincheng** [comment]
dubbo配置

```
# Dubbo
dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.xxxxx.service
  # 协议
  protocols:
    # dubbo 协议
    dubbo:
      name: dubbo
      port: -1
  registry:
    address: nacos://172.16.12.151:8848/?backup=172.16.12.193:8848,172.16.12.172:8848&username=nacos&password=nacos&namespace=${spring.profiles.active}&group=xxxx
  application:
    qos-enable: false
    logger: slf4j
    # interface / instance / all
    register-mode: interface
  consumer:
    check: false
    timeout: 5000

```

**Comment by liufeiyu1002** [comment]
> > 这个需要看下是不是注册中心地址没更新
> 
> 注册中心地址应该是不变的吧

他的意思是在注册中心看 provider 注册 的地址 是不是 变化了

**Comment by wenlincheng** [comment]
> > > 这个需要看下是不是注册中心地址没更新
> > 
> > 
> > 注册中心地址应该是不变的吧
> 
> 他的意思是在注册中心看 provider 注册 的地址 是不是 变化了
推代码重新部署后provider会注册不上去，在nacos上找不到，k8s手动重启provider的pod就能重新注册，consumer也就能调通。生产环境用的2.7.14版本不存在这个问题，同样是部署在k8s环境，现在是在对dubbo做升级出现的问题。

**Comment by liufeiyu1002** [comment]
> 



> > > > 这个需要看下是不是注册中心地址没更新
> > > 
> > > 
> > > 注册中心地址应该是不变的吧
> > 
> > 
> > 他的意思是在注册中心看 provider 注册 的地址 是不是 变化了
> > 推代码重新部署后provider会注册不上去，在nacos上找不到，k8s手动重启provider的pod就能重新注册，consumer也就能调通。生产环境用的2.7.14版本不存在这个问题，同样是部署在k8s环境，现在是在对dubbo做升级出现的问题。

最好是能看下 `推代码重新部署provider` 这个过程的日志

**Comment by wenlincheng** [comment]
> > 
> 
> > > > > 这个需要看下是不是注册中心地址没更新
> > > > 
> > > > 
> > > > 注册中心地址应该是不变的吧
> > > 
> > > 
> > > 他的意思是在注册中心看 provider 注册 的地址 是不是 变化了
> > > 推代码重新部署后provider会注册不上去，在nacos上找不到，k8s手动重启provider的pod就能重新注册，consumer也就能调通。生产环境用的2.7.14版本不存在这个问题，同样是部署在k8s环境，现在是在对dubbo做升级出现的问题。
> 
> 最好是能看下 `推代码重新部署provider` 这个过程的日志

在pod里启动会报这个错，本地启动不报

```
2022-08-22 11:36:14.590 [main] DEBUG c.a.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader - com_alibaba_nacos_shaded_io_grpc_netty_shaded_netty_transport_native_epoll cannot be loaded from java.library.path, now trying export to -Dio.netty.native.workdir: /tmp
java.lang.UnsatisfiedLinkError: no com_alibaba_nacos_shaded_io_grpc_netty_shaded_netty_transport_native_epoll in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:349)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:189)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.epoll.Native.<clinit>(Native.java:57)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.Utils.isEpollAvailable(Utils.java:220)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.Utils.<clinit>(Utils.java:92)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<clinit>(NettyChannelBuilder.java:72)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:37)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:23)
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.createNewChannelStub(GrpcClient.java:97)
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:265)
	at com.alibaba.nacos.common.remote.client.RpcClient.start(RpcClient.java:394)
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.ensureRpcClient(ClientWorker.java:941)
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.getOneRunningClient(ClientWorker.java:1104)
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.queryConfig(ClientWorker.java:996)
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:407)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:166)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:94)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.loadNacosData(NacosPropertySourceBuilder.java:85)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.build(NacosPropertySourceBuilder.java:73)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosPropertySource(NacosPropertySourceLocator.java:199)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosDataIfPresent(NacosPropertySourceLocator.java:186)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosConfiguration(NacosPropertySourceLocator.java:158)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadSharedConfiguration(NacosPropertySourceLocator.java:116)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:101)
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:52)
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:47)
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:98)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:626)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	at com.daddylab.ark.sailor.admin.ArkSailorApplication.main(ArkSailorApplication.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
	Suppressed: java.lang.UnsatisfiedLinkError: no com_alibaba_nacos_shaded_io_grpc_netty_shaded_netty_transport_native_epoll in java.library.path
		at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
		at java.lang.Runtime.loadLibrary0(Runtime.java:870)
		at java.lang.System.loadLibrary(System.java:1122)
		at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)
		at java.security.AccessController.doPrivileged(Native Method)
		at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
		at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
		... 44 common frames omitted
```

**Comment by zrlw** [comment]
最新的dubbo就是这个样，如果provider的ip地址变了，那么除非重启客户端，否则客户端会一直尝试连接旧地址。
社区反馈的理由是生产环境下服务实例数不能直接变为0，你如果把某个服务的实例变0，最后那个实例会变成不死鸟，所有客户端都会不间断地去尝试重连，即使后来再启动了1个服务实例也如此，直到你受不了把所有客户端都重启了事。
避免这个问题，每个dubbo服务至少要部署2个实例，还不能同时关闭或重启，时刻要留1个实例。
万一服务端因为停电了都挂了，那你就认栽了吧，dubbo客户端会给你留一个不死鸟的。

**Comment by wenlincheng** [comment]
> 最新的dubbo就是这个样，如果provider的ip地址变了，那么除非重启客户端，否则客户端会一直尝试连接旧地址。 社区反馈的理由是生产环境下服务实例数不能直接变为0，你如果把某个服务的实例变0，最后那个实例会变成不死鸟，所有客户端都会不间断地去尝试重连，即使后来再启动了1个服务实例也如此，直到你受不了把所有客户端都重启了事。 避免这个问题，每个dubbo服务至少要部署2个实例，还不能同时关闭或重启，时刻要留1个实例。 万一服务端因为停电了都挂了，那你就认栽了吧，dubbo客户端会给你留一个不死鸟的。

这么设计啥目的呢。像dev、test环境一般都是单个实例运行，每次发布还要重启消费者，也太麻烦了吧。我刚把两个服务都增加了一个实例，重新发布还是存在问题，设置的注册模式是双注册，双实例部署，A服务注册2个instance 2个interface ,B服务注册了2个instance 2个interface ,修改代码部署重启，A服务注册2个instance 1个interface ,B服务注册了0个instance 1个interface （重启后的情况不一定这样）,就很不稳定。

**Comment by AlbumenJ** [comment]
我自己手动在 k8s 上跑了下即使缩容到0然后再扩容也是可以正常调用的。

**Comment by pingod** [comment]
这个问题最后没见解决，issues就关闭了？？

**Comment by zrlw** [comment]
> 我自己手动在 k8s 上跑了下即使缩容到0然后再扩容也是可以正常调用的。

缩到0后不要马上扩容，注册中心向consumer推送服务数量为0之后再扩容就会出现这个问题

**Comment by longguiyun** [comment]
遇到过这种情况，查看了k8s pod 的配置，然后降低了dubbo服务配置的线程数。问题就没有出现了。猜测可能是k8s pod的资源配置不太够。导致dubbo服务发现更新提供者数据的线程没有执行。

**Comment by elvislou** [comment]
> consumer

我们这边dubbo2.x的最新版本，再k8s provider滚动重启的情况下consumer依然有概率(比较偶发)会一直连老的ip调用服务，导致服务调用失败，而且这个报错会一直持续无法恢复。

这个问题跟ReconnectTimerTask那个重连老ip还不一样，那个顶多是心跳失败，不影响业务调用，我碰到的问题直接影响到业务调用。

请问各位该怎么解决啊，生产环境也不可能经常去重启consumer服务。

**Comment by zrlw** [comment]
dubbo3应该解决这个问题了，但是dubbo2没有相关的机制，所以dubbo3的相关PR没办法用于dubbo2。
具体情况可以问问 @AlbumenJ

**Comment by peopleone** [comment]
> > consumer
> 
> 我们这边dubbo2.x的最新版本，再k8s provider滚动重启的情况下consumer依然有概率(比较偶发)会一直连老的ip调用服务，导致服务调用失败，而且这个报错会一直持续无法恢复。
> 
> 这个问题跟ReconnectTimerTask那个重连老ip还不一样，那个顶多是心跳失败，不影响业务调用，我碰到的问题直接影响到业务调用。
> 
> 请问各位该怎么解决啊，生产环境也不可能经常去重启consumer服务。

我们生产近期也出现了类似问题，consumer收到了provider变更的notify，并有close netty channel，但是仍然使用old provider ip去调用服务，报错几次后在无notify url的情况下又恢复正常了

**Comment by Dr-wgy** [comment]
k8s 情况下 可能还遇到 如果只有一个 ip 时候 这个ip 被别的服务使用了 因为本身是 a 服务 因为 a 服务因为某种原因 掉线了 然后 b服务使用这个ip 即便 我的a服务重新启动也不行 看起来只能重启 消费者吗
dubbo: 3.1.6 
nacos: 2.1.2

**Comment by Dr-wgy** [comment]
> 最新的dubbo就是这个样，如果provider的ip地址变了，那么除非重启客户端，否则客户端会一直尝试连接旧地址。 社区反馈的理由是生产环境下服务实例数不能直接变为0，你如果把某个服务的实例变0，最后那个实例会变成不死鸟，所有客户端都会不间断地去尝试重连，即使后来再启动了1个服务实例也如此，直到你受不了把所有客户端都重启了事。 避免这个问题，每个dubbo服务至少要部署2个实例，还不能同时关闭或重启，时刻要留1个实例。 万一服务端因为停电了都挂了，那你就认栽了吧，dubbo客户端会给你留一个不死鸟的。

这个说的是那个推空保护是吗 

![Image](https://github.com/user-attachments/assets/f9f51495-d764-4b4f-9f32-e2cd15396178)

**Comment by Dr-wgy** [comment]
![Image](https://github.com/user-attachments/assets/a52608f5-1027-40ac-9a24-0b3480614954)

**Comment by ph228228** [comment]
dubbo3.2.15仍然有这个问题
我的registry地址使用的是kubernetes://kubernetes.default.svc:443，没有用nacos作为注册中心。在provider pod重启后，仍然有一个重连线程去连接provider的老ip，多次重启pod，就会存在多个重连线程。即使配置了环境变量DUBBO_IP_TO_REGISTRY为svc的域名，consumer仍然使用provider的pod ip进行连接。请问有办法解决这个问题吗？


使用的k8s拓展依赖是：
          <dependency>
              <groupId>org.apache.dubbo.extensions</groupId>
              <artifactId>dubbo-kubernetes</artifactId>
              <version>3.2.0</version>
          </dependency>

下面是重连线程的报错：
failed to connect to server /192.168.0.117:8003 client-side timeout 3000ms (elapsed: 3001ms) from netty client 192.168.0.24 using dubbo version 3.2.15
	at org.apache.dubbo.remoting.transport.netty4.NettyClient.doConnect(NettyClient.java:257)
	at org.apache.dubbo.remoting.transport.netty4.NettyClient.doConnect(NettyClient.java:179)
	at org.apache.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:265)
	at org.apache.dubbo.remoting.transport.AbstractClient.reconnect(AbstractClient.java:346)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeClient.reconnect(HeaderExchangeClient.java:189)
	at org.apache.dubbo.remoting.exchange.support.header.ReconnectTimerTask.doTask(ReconnectTimerTask.java:56)
	at org.apache.dubbo.remoting.exchange.support.header.AbstractTimerTask.run(AbstractTimerTask.java:93)
	at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:653)
	at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:732)
	at org.apache.dubbo.common.timer.HashedWheelTimer$Worker.run(HashedWheelTimer.java:454)
	at java.base/java.lang.Thread.run(Unknown Source)
