### ISSUE TITLE
Dubbo3线程池配置无效?

### ISSUE THREAD

**Issue by GreenCypress** [apache/dubbo#10491]
application.xml的Dubbo配置如下
```
dubbo:
  scan:
    base-packages: cn.xxxxxx
  protocol:
    name: dubbo
    port: -1
    threads: 600
    threadpool: cached
    dispatcher: message
  provider:
    timeout: 30000
    retries: 0
  consumer:
    check: false
    timeout: 30000
    retries: 0
  registry:
    address: nacos://xxxxxxxx
  application:
    name: ${spring.application.name}
```
配置了dubbo.protocol.threads=600 但是在压测中还是报了如下错误：
```
Caused by: org.apache.dubbo.remoting.RemotingException: Server side(192.168.0.181,20880) thread pool is exhausted, detail msg:Thread pool is EXHAUSTED! Thread Name: DubboServerHandler-192.168.0.181:20880, Pool Size: 100 (active: 100, core: 0, max: 100, largest: 100), Task: 10790 (completed: 10690), Executor status:(isShutdown:false, isTerminated:false, isTerminating:false), in dubbo://192.168.0.181:20880!
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.doReceived(DefaultFuture.java:214)
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:176)
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:164)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleResponse(HeaderExchangeHandler.java:60)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:181)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor$RunnableWrapper.run(ThreadlessExecutor.java:184)
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:103)
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:193)
	... 55 more
```
其中 ` Pool Size: 100 (active: 100, core: 0, max: 100, largest: 100)`   

为什么pool Size还是100？无论如何配置报错提示都还是提示pool max size 100，100好像是默认配置的大小（貌似是配置失效，还是我的理解有误？）

Spring boot版本：2.6.7
maven dependency：
```
 <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
        </dependency>
```

**Comment by AlbumenJ** [comment]
Related with https://github.com/apache/dubbo/issues/10466
Will be fixed in 3.0.11 (will be released in the next few days)

**Comment by chickenlj** [comment]
This issue only exists in 3.0.9 and 3.010

**Comment by 139xuzhaohui** [comment]
楼主有解决吗？ 怎么感觉dubbo3.1.1 也还是 默认100 ，即使加了配置还是不可

**Comment by 139xuzhaohui** [comment]
> This issue only exists in 3.0.9 and 3.010

Why dubbo 3.1.1 is the same

![image](https://user-images.githubusercontent.com/57884638/216351486-35b61a68-3159-4559-8b6e-bce00b9d382d.png)

**Comment by AlbumenJ** [comment]
> > This issue only exists in 3.0.9 and 3.010
> 
> Why dubbo 3.1.1 is the same
> 
> ![image](https://user-images.githubusercontent.com/57884638/216351486-35b61a68-3159-4559-8b6e-bce00b9d382d.png)

可以单独抽一个可以复现的 demo 吗

**Comment by 139xuzhaohui** [comment]
demo 估计不太行了，现在线上部分项目是正常的，部分项目是不行的，给你看看我们日志里现在找到一些区别，怀疑是 dubbo线程池选择的不一样，线程数被其他的依赖项给覆盖了
1、报错日志：
![image](https://user-images.githubusercontent.com/57884638/216550394-dfe6a3c0-6b6c-4a00-b187-7f92bf8bbca3.png)
此报错 即使配置了 dubbo.protocol.threads = 300 也没有生效

2、没有生效项目的report日志
![image](https://user-images.githubusercontent.com/57884638/216550761-1942fe26-4849-4af2-9c15-74b57a8da0f2.png)

3、正常项目
![image](https://user-images.githubusercontent.com/57884638/216550880-4b67c14d-87b9-49be-96a0-b71b14c26211.png)

后来考虑指定 dubbo线程池也fixed 也不可😭

**Comment by 139xuzhaohui** [comment]
> > > This issue only exists in 3.0.9 and 3.010
> > 
> > 
> > Why dubbo 3.1.1 is the same
> > ![image](https://user-images.githubusercontent.com/57884638/216351486-35b61a68-3159-4559-8b6e-bce00b9d382d.png)
> 
> 可以单独抽一个可以复现的 demo 吗

demo 估计不太行了，现在线上部分项目是正常的，部分项目是不行的，给你看看我们日志里现在找到一些区别，怀疑是 dubbo线程池选择的不一样，线程数被其他的依赖项给覆盖了， 具体信息邮件给你
