### ISSUE TITLE
dubbo3.1.0 kubernetes sample use k8s as registry, consumer fail to startup, due to it  Failed to check the status of the service org.apache.dubbo.samples.api.GreetingService. No provider available for the service...

### ISSUE THREAD

**Issue by szhengli** [apache/dubbo#10507]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.0-SNAPSHOT
* Operating System version: centos7
* Java version: 1.8.0_312

### Steps to reproduce this issue

1. download  git clone  https://github.com/apache/dubbo-samples.git , and cd /data/dubbo-samples/dubbo-samples-kubernetes/
2.  in dubbo-samples-apiserver-consumer,  change  to <image>harbor.cnzhonglunnet.com/zhonglun/dubbo-samples-apiserver-consumer</image>    in pom.xml
3.  in  dubbo-samples-apiserver-consumer, change  to <image>harbor.cnzhonglunnet.com/zhonglun/dubbo-samples-apiserver-provider</image>    in pom.xml

4.   also update the kubernetes API server in properties files in the provider & consumer project
5.  then build and deploy to k8s

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

provider and consumer pod should be able to run normally.

consumer fail to startup . it prompts that it failt o check the provider.

```
Just put your stack trace here!


SEVERE: [DUBBO] Dubbo Application[1.1](dubbo-samples-apiserver-consumer) found failed module: Dubbo Module[1.1.1], dubbo version: 3.1.0-SNAPSHOT, current host: 10.42.1.110
--
java.lang.IllegalStateException: Failed to check the status of the service org.apache.dubbo.samples.api.GreetingService. No provider available for the service org.apache.dubbo.samples.api.GreetingService:1.0.0 from the url consumer://10.42.1.110/org.apache.dubbo.samples.api.GreetingService?application=dubbo-samples-apiserver-consumer&background=false&dubbo=2.0.2&interface=org.apache.dubbo.samples.api.GreetingService&metadata-service-port=20885&methods=sayHello&pid=1&provided-by=dubbo-samples-apiserver-provider&qos.accept.foreign.ip=true&qos.enable=true&register.ip=10.42.1.110&release=3.1.0-SNAPSHOT&revision=1.0.0&side=consumer&sticky=false&timeout=3000&timestamp=1661488063797&version=1.0.0 to the consumer 10.42.1.110 use dubbo version 3.1.0-SNAPSHOT
at org.apache.dubbo.config.ReferenceConfig.checkInvokerAvailable(ReferenceConfig.java:652)
at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:304)
at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:227)
at org.apache.dubbo.config.utils.SimpleReferenceCache.destroyReference(SimpleReferenceCache.java:262)
at org.apache.dubbo.config.utils.SimpleReferenceCache.destroy(SimpleReferenceCache.java:215)
at org.apache.dubbo.config.utils.SimpleReferenceCache.destroy(SimpleReferenceCache.java:239)
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:388)
at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:363)
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:154)
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:111)
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:100)
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:45)
at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
at org.apache.dubbo.samples.ConsumerBootstrap.main(ConsumerBootstrap.java:33)
 
Exception in thread "main" java.lang.IllegalStateException: Failed to check the status of the service org.apache.dubbo.samples.api.GreetingService. No provider available for the service org.apache.dubbo.samples.api.GreetingService:1.0.0 from the url consumer://10.42.1.110/org.apache.dubbo.samples.api.GreetingService?application=dubbo-samples-apiserver-consumer&background=false&dubbo=2.0.2&interface=org.apache.dubbo.samples.api.GreetingService&metadata-service-port=20885&methods=sayHello&pid=1&provided-by=dubbo-samples-apiserver-provider&qos.accept.foreign.ip=true&qos.enable=true&register.ip=10.42.1.110&release=3.1.0-SNAPSHOT&revision=1.0.0&side=consumer&sticky=false&timeout=3000&timestamp=1661488063797&version=1.0.0 to the consumer 10.42.1.110 use dubbo version 3.1.0-SNAPSHOT
at org.apache.dubbo.config.ReferenceConfig.checkInvokerAvailable(ReferenceConfig.java:652)
at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:304)
at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:227)
at org.apache.dubbo.config.utils.SimpleReferenceCache.destroyReference(SimpleReferenceCache.java:262)
at org.apache.dubbo.config.utils.SimpleReferenceCache.destroy(SimpleReferenceCache.java:215)
at org.apache.dubbo.config.utils.SimpleReferenceCache.destroy(SimpleReferenceCache.java:239)
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:388)
at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:363)
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:154)
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:111)
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:100)
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:45)
at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
at org.apache.dubbo.samples.ConsumerBootstrap.main(ConsumerBootstrap.java:33)


```

**Comment by szhengli** [comment]
really sucks! basically I changed nothing , execept docker registry  name  in pom , and kubernetes server  in properties file.  it just DOES NOT WORK!       anybody can run the dubbo-samples/dubbo-samples-kubernetes  successfully?????

**Comment by liufeiyu1002** [comment]
你要看你的提供者有没有正常启动并注册到注册中心去

**Comment by szhengli** [comment]
dubbo-samples-apiserver-provider service, 有提供者endpoints 地址的。 就是消费者，报找不到提供者。。。 你试 https://github.com/apache/dubbo-samples.git  正常吗？

**Comment by AlbumenJ** [comment]
apiserver 直连的我来看下，目前 xds 的是可以跑通的

**Comment by szhengli** [comment]
> apiserver 直连的我来看下，目前 xds 的是可以跑通的

API Server  直连和DNS方式都跑不通。报同样的问题

**Comment by szhengli** [comment]
> apiserver 直连的我来看下，目前 xds 的是可以跑通的
dubbo-samples-mesh-k8s  那个范例（sidecar模式）也跑不通，comsumer报调用失败。 proxyless 模式还没试。

**Comment by AlbumenJ** [comment]
proxyless 模式的文档：https://dubbo.apache.org/zh/overview/tasks/mesh/proxyless/

**Comment by szhengli** [comment]
> apiserver 直连的我来看下，目前 xds 的是可以跑通的

d

> proxyless 模式的文档：https://dubbo.apache.org/zh/overview/tasks/mesh/proxyless/

NOT WORKING NEITHER.

<html>
<body>


[27/08/22 01:03:03:003 UTC] grpc-default-executor-0 ERROR istio.IstioCitadelCertificateSigner: [DUBBO] Receive error message from Istio Citadel grpc stub., dubbo version: 1.0-SNAPSHOT, current host: 10.42.1.200
--
io.grpc.StatusRuntimeException: UNAUTHENTICATED: request authenticate failure
at io.grpc.Status.asRuntimeException(Status.java:535)
at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:479)
at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463)
at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427)
at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:460)
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
[27/08/22 01:03:03:003 UTC] main ERROR xds.XdsServiceDiscovery: Generate Cert Failed. Send csr request failed. Please check log above.
org.apache.dubbo.rpc.RpcException: Generate Cert Failed. Send csr request failed. Please check log above.
at org.apache.dubbo.registry.xds.istio.IstioCitadelCertificateSigner.createCert(IstioCitadelCertificateSigner.java:173)
at org.apache.dubbo.registry.xds.istio.IstioCitadelCertificateSigner.doGenerateCert(IstioCitadelCertificateSigner.java:100)
at org.apache.dubbo.registry.xds.istio.IstioCitadelCertificateSigner.GenerateCert(IstioCitadelCertificateSigner.java:86)
at org.apache.dubbo.registry.xds.util.XdsChannel.<init>(XdsChannel.java:51)
at org.apache.dubbo.registry.xds.util.PilotExchanger.<init>(PilotExchanger.java:56)
at org.apache.dubbo.registry.xds.util.PilotExchanger.initialize(PilotExchanger.java:112)
at org.apache.dubbo.registry.xds.XdsServiceDiscovery.doInitialize(XdsServiceDiscovery.java:50)
at org.apache.dubbo.registry.xds.XdsServiceDiscoveryFactory.createDiscovery(XdsServiceDiscoveryFactory.java:34)
at org.apache.dubbo.registry.client.AbstractServiceDiscoveryFactory.lambda$getServiceDiscovery$0(AbstractServiceDiscoveryFactory.java:53)
at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
at org.apache.dubbo.registry.client.AbstractServiceDiscoveryFactory.getServiceDiscovery(AbstractServiceDiscoveryFactory.java:53)
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.getServiceDiscovery(ServiceDiscoveryRegistry.java:122)
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.createServiceDiscovery(ServiceDiscoveryRegistry.java:109)
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.<init>(ServiceDiscoveryRegistry.java:86)
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryFactory.createRegistry(ServiceDiscoveryRegistryFactory.java:35)
at org.apache.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:94)
at org.apache.dubbo.registry.RegistryFactoryWrapper.getRegistry(RegistryFactoryWrapper.java:33)
at org.apache.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)
at org.apache.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:394)
at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getServiceDiscoveryInvoker(InterfaceCompatibleRegistryProtocol.java:63)
at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshServiceDiscoveryInvoker(MigrationInvoker.java:436)
at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToApplicationFirstInvoker(MigrationInvoker.java:244)
at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.refreshInvoker(MigrationRuleHandler.java:73)
at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:57)
at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:243)
at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:536)
at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:506)
at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:488)
at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:74)
at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:80)
at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:71)
at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:52)
at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
at org.apache.dubbo.config.ReferenceConfig.createInvokerForRemote(ReferenceConfig.java:600)
at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:441)
at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:295)
at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:227)
at org.apache.dubbo.config.utils.SimpleReferenceCache.get(SimpleReferenceCache.java:129)
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:383)
at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:363)
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:154)
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:111)
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:100)
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:45)
at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)


</body>
</html>

**Comment by szhengli** [comment]
> proxyless 模式的文档：https://dubbo.apache.org/zh/overview/tasks/mesh/proxyless/

也不行。
<html>
<body>


[27/08/22 01:03:03:003 UTC] grpc-default-executor-0 ERROR istio.IstioCitadelCertificateSigner: [DUBBO] Receive error message from Istio Citadel grpc stub., dubbo version: 1.0-SNAPSHOT, current host: 10.42.1.200
--
io.grpc.StatusRuntimeException: UNAUTHENTICATED: request authenticate failure
at io.grpc.Status.asRuntimeException(Status.java:535)
at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:479)
at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463)
at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427)
at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:460)
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
[27/08/22 01:03:03:003 UTC] main ERROR xds.XdsServiceDiscovery: Generate Cert Failed. Send csr request failed. Please check log above.
org.apache.dubbo.rpc.RpcException: Generate Cert Failed. Send csr request failed. Please check log above.
at org.apache.dubbo.registry.xds.istio.IstioCitadelCertificateSigner.createCert(IstioCitadelCertificateSigner.java:173)
at org.apache.dubbo.registry.xds.istio.IstioCitadelCertificateSigner.doGenerateCert(IstioCitadelCertificateSigner.java:100)
at org.apache.dubbo.registry.xds.istio.IstioCitadelCertificateSigner.GenerateCert(IstioCitadelCertificateSigner.java:86)
at org.apache.dubbo.registry.xds.util.XdsChannel.<init>(XdsChannel.java:51)
at org.apache.dubbo.registry.xds.util.PilotExchanger.<init>(PilotExchanger.java:56)
at org.apache.dubbo.registry.xds.util.PilotExchanger.initialize(PilotExchanger.java:112)
at org.apache.dubbo.registry.xds.XdsServiceDiscovery.doInitialize(XdsServiceDiscovery.java:50)
at org.apache.dubbo.registry.xds.XdsServiceDiscoveryFactory.createDiscovery(XdsServiceDiscoveryFactory.java:34)
at org.apache.dubbo.registry.client.AbstractServiceDiscoveryFactory.lambda$getServiceDiscovery$0(AbstractServiceDiscoveryFactory.java:53)
at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
at org.apache.dubbo.registry.client.AbstractServiceDiscoveryFactory.getServiceDiscovery(AbstractServiceDiscoveryFactory.java:53)
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.getServiceDiscovery(ServiceDiscoveryRegistry.java:122)
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.createServiceDiscovery(ServiceDiscoveryRegistry.java:109)
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.<init>(ServiceDiscoveryRegistry.java:86)
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryFactory.createRegistry(ServiceDiscoveryRegistryFactory.java:35)
at org.apache.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:94)
at org.apache.dubbo.registry.RegistryFactoryWrapper.getRegistry(RegistryFactoryWrapper.java:33)
at org.apache.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)
at org.apache.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:394)
at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getServiceDiscoveryInvoker(InterfaceCompatibleRegistryProtocol.java:63)
at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshServiceDiscoveryInvoker(MigrationInvoker.java:436)
at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToApplicationFirstInvoker(MigrationInvoker.java:244)
at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.refreshInvoker(MigrationRuleHandler.java:73)
at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:57)
at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:243)
at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:536)
at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:506)
at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:488)
at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:74)
at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:80)
at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:71)
at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:52)
at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
at org.apache.dubbo.config.ReferenceConfig.createInvokerForRemote(ReferenceConfig.java:600)
at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:441)
at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:295)
at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:227)
at org.apache.dubbo.config.utils.SimpleReferenceCache.get(SimpleReferenceCache.java:129)
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:383)
at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:363)
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:154)
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:111)
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:100)
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:45)
at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
at org.apache.dubbo.samples.ConsumerBootstrap.main(ConsumerBootstrap.java:33)


</body>
</html>

**Comment by szhengli** [comment]
> proxyless 模式的文档：https://dubbo.apache.org/zh/overview/tasks/mesh/proxyless/

试到现在.  
1、dubbo-samples/dubbo-samples-xds
2、dubbo-samples-kubernetes
3、dubbo-samples-mesh-k8s
没有一个工作的.
none of the above working.!

**Comment by AlbumenJ** [comment]
![image](https://user-images.githubusercontent.com/9292748/187032185-5128930e-c4ca-4ec2-9493-0f150b363ba5.png)

安装 Istio 的时候需要开启 [first-party-jwt 支持](https://istio.io/latest/docs/ops/best-practices/security/#configure-third-party-service-account-tokens)（使用 istioctl 工具安装的时候加上 --set values.global.jwtPolicy=first-party-jwt 参数），否则将导致客户端认证失败的问题。

**Comment by AlbumenJ** [comment]
k8s apiserver 的是因为 dubbo shade 没有导出相关代码，需要独立依赖，https://github.com/apache/dubbo-samples/pull/504 已经修复了，可以重新拉下代码试下

**Comment by szhengli** [comment]
> k8s apiserver 的是因为 dubbo shade 没有导出相关代码，需要独立依赖，[apache/dubbo-samples#504](https://github.com/apache/dubbo-samples/pull/504) 已经修复了，可以重新拉下代码试下



> ![image](https://user-images.githubusercontent.com/9292748/187032185-5128930e-c4ca-4ec2-9493-0f150b363ba5.png)
> 
> 安装 Istio 的时候需要开启 [first-party-jwt 支持](https://istio.io/latest/docs/ops/best-practices/security/#configure-third-party-service-account-tokens)（使用 istioctl 工具安装的时候加上 --set values.global.jwtPolicy=first-party-jwt 参数），否则将导致客户端认证失败的问题。

istio  first-party-jwt 安装有问题。 网上说 k8s 1.21之后  first-party-jwt with k8s 1.21+ logic is too restrictive #34293
Kubernetes Version: v1.22.11 ，
  istioctl install --set profile=demo --set values.global.jwtPolicy=first-party-jwt -y  部署之后  istiod pod 报错

  error ads Failed to authenticate client from 10.42.0.251:47904: Authenticator ClientCertAuthenticator: no verified chain is found; Authenticator KubeJWTAuthenticator: failed to validate the JWT from cluster "Kubernetes": the service account authentication returns an error: [invalid bearer token, token audiences ["https://kubernetes.default.svc.cluster.local" "rke2"] is invalid for the target audiences ["istio-ca"]]  。
 网上说 k8s 1.21之后  first-party-jwt with k8s 1.21+ logic is too restrictive #34293

**Comment by szhengli** [comment]
> k8s apiserver 的是因为 dubbo shade 没有导出相关代码，需要独立依赖，[apache/dubbo-samples#504](https://github.com/apache/dubbo-samples/pull/504) 已经修复了，可以重新拉下代码试下

解决了。 

dubbo.registry.address=kubernetes://kubernetes.default.svc.cluster.local:443?registry-type=service&duplicate=false&namespace=dubbo-demo&trustCerts=true

之前没有加443端口导致的。加443端口就好了。 

它默认使用了9090端口去连api server。

**Comment by AlbumenJ** [comment]
> 网上说 k8s 1.21之后 first-party-jwt with k8s 1.21+ logic is too restrictive #34293

我用的 Kubernetes Version: v1.22.10 + Istio 1.14.3 是可以正常使用的

**Comment by chickenlj** [comment]
https://github.com/apache/dubbo/pull/10514
