### ISSUE TITLE
3.0.7 Metadata service not found when envoy is opened 

### ISSUE THREAD

**Issue by xlq20080808** [apache/dubbo#10502]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here

dubbo 3.0.7
jdk 1.8

 When I turn on envoy，consumer not found MetadataService,And I can't make Dubbo calls
 When I close envoy, it can be called normally

error log

```
[ERROR 2022-08-25 10:20:15.507] [Dubbo-framework-metadata-retry-thread-1] [] org.apache.dubbo.registry.client.metadata.MetadataUtils.getRemoteMetadata(MetadataUtils.java:160) [ [DUBBO] Failed to get app metadata for revision 83aeeddd661c6ca60f6b833da21ab257 for type local from instance 10.85.40.73:20880, dubbo version: 3.0.7.kk-SNAPSHOT, current host: 10.85.34.82]
org.apache.dubbo.rpc.RpcException: Failed to invoke remote method: getMetadataInfo, provider: dubbo://10.85.40.73:20880/org.apache.dubbo.metadata.MetadataService?connections=1&dubbo=2.0.2&group=hello-service&port=20880&protocol=dubbo&release=3.0.7.kk-SNAPSHOT&retries=0&side=provider&timeout=5000&version=1.0.0, cause: org.apache.dubbo.remoting.RemotingException: Fail to decode request due to: java.lang.IllegalArgumentException: Service not found:org.apache.dubbo.metadata.MetadataService, getMetadataInfo
java.lang.IllegalArgumentException: Service not found:org.apache.dubbo.metadata.MetadataService, getMetadataInfo
        at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:146)
        at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:83)
        at org.apache.dubbo.remoting.transport.DecodeHandler.decode(DecodeHandler.java:57)
        at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:44)
        at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
        at java.lang.Thread.run(Thread.java:748)

        at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:278) ~[dubbo-3.0.7.kk-SNAPSHOT.jar!/:3.0.7.kk-SNAPSHOT]
        at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:185) ~[dubbo-3.0.7.kk-SNAPSHOT.jar!/:3.0.7.kk-SNAPSHOT]
        at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:78) ~[dubbo-3.0.7.kk-SNAPSHOT.jar!/:3.0.7.kk-SNAPSHOT]
        at org.apache.dubbo.rpc.proxy.InvocationUtil.invoke(InvocationUtil.java:57) ~[dubbo-3.0.7.kk-SNAPSHOT.jar!/:3.0.7.kk-SNAPSHOT]
        at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:73) ~[dubbo-3.0.7.kk-SNAPSHOT.jar!/:3.0.7.kk-SNAPSHOT]
        at org.apache.dubbo.metadata.MetadataServiceDubboProxy1.getMetadataInfo(MetadataServiceDubboProxy1.java) ~[dubbo-3.0.7.kk-SNAPSHOT.jar!/:3.0.7.kk-SNAPSHOT]
        at org.apache.dubbo.registry.client.metadata.MetadataUtils.getRemoteMetadata(MetadataUtils.java:152) [dubbo-3.0.7.kk-SNAPSHOT.jar!/:3.0.7.kk-SNAPSHOT]
        at org.apache.dubbo.registry.client.AbstractServiceDiscovery.getRemoteMetadata(AbstractServiceDiscovery.java:164) [dubbo-3.0.7.kk-SNAPSHOT.jar!/:3.0.7.kk-SNAPSHOT]
        at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.doOnEvent(ServiceInstancesChangedListener.java:152) [dubbo-3.0.7.kk-SNAPSHOT.jar!/:3.0.7.kk-SNAPSHOT]
        at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.onEvent(ServiceInstancesChangedListener.java:112) [dubbo-3.0.7.kk-SNAPSHOT.jar!/:3.0.7.kk-SNAPSHOT]
        at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener$AddressRefreshRetryTask.run(ServiceInstancesChangedListener.java:525) [dubbo-3.0.7.kk-SNAPSHOT.jar!/:3.0.7.kk-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.util.concurrent.ExecutionException: org.apache.dubbo.remoting.RemotingException: Fail to decode request due to: java.lang.IllegalArgumentException: Service not found:org.apache.dubbo.metadata.MetadataService, getMetadataInfo
java.lang.IllegalArgumentException: Service not found:org.apache.dubbo.metadata.MetadataService, getMetadataInfo
        at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:146)
        at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:83)
        at org.apache.dubbo.remoting.transport.DecodeHandler.decode(DecodeHandler.java:57)
        at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:44)
        at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
        at java.lang.Thread.run(Thread.java:748)

        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_191]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915) ~[?:1.8.0_191]
        at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:195) ~[dubbo-3.0.7.kk-SNAPSHOT.jar!/:3.0.7.kk-SNAPSHOT]
        at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:264) ~[dubbo-3.0.7.kk-SNAPSHOT.jar!/:3.0.7.kk-SNAPSHOT]
        ... 17 more
Caused by: org.apache.dubbo.remoting.RemotingException: Fail to decode request due to: java.lang.IllegalArgumentException: Service not found:org.apache.dubbo.metadata.MetadataService, getMetadataInfo
java.lang.IllegalArgumentException: Service not found:org.apache.dubbo.metadata.MetadataService, getMetadataInfo
        at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:146)
        at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:83)
        at org.apache.dubbo.remoting.transport.DecodeHandler.decode(DecodeHandler.java:57)
        at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:44)
        at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
        at java.lang.Thread.run(Thread.java:748)

        at org.apache.dubbo.remoting.exchange.support.DefaultFuture.doReceived(DefaultFuture.java:214) ~[dubbo-3.0.7.kk-SNAPSHOT.jar!/:3.0.7.kk-SNAPSHOT]
        at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:176) ~[dubbo-3.0.7.kk-SNAPSHOT.jar!/:3.0.7.kk-SNAPSHOT]
        at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:164) ~[dubbo-3.0.7.kk-SNAPSHOT.jar!/:3.0.7.kk-SNAPSHOT]
        at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleResponse(HeaderExchangeHandler.java:60) ~[dubbo-3.0.7.kk-SNAPSHOT.jar!/:3.0.7.kk-SNAPSHOT]
        at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:181) ~[dubbo-3.0.7.kk-SNAPSHOT.jar!/:3.0.7.kk-SNAPSHOT]
        at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51) ~[dubbo-3.0.7.kk-SNAPSHOT.jar!/:3.0.7.kk-SNAPSHOT]
        at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57) ~[dubbo-3.0.7.kk-SNAPSHOT.jar!/:3.0.7.kk-SNAPSHOT]
        at org.apache.dubbo.common.threadpool.ThreadlessExecutor$RunnableWrapper.run(ThreadlessExecutor.java:184) ~[dubbo-3.0.7.kk-SNAPSHOT.jar!/:3.0.7.kk-SNAPSHOT]
        at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:103) ~[dubbo-3.0.7.kk-SNAPSHOT.jar!/:3.0.7.kk-SNAPSHOT]
        at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:193) ~[dubbo-3.0.7.kk-SNAPSHOT.jar!/:3.0.7.kk-SNAPSHOT]
        at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:264) ~[dubbo-3.0.7.kk-SNAPSHOT.jar!/:3.0.7.kk-SNAPSHOT]
        ... 17 more
```

**Comment by AlbumenJ** [comment]
需要看一下是不是开启了 vs/ds 路由，把 dubbo 自身的请求路由到了错误的机器上

**Comment by xlq20080808** [comment]
感谢大佬回复，目前我们已经定位到原因。存在其他服务创建的service也使用了20880

**Comment by xlq20080808** [comment]
感谢大佬回复，目前我们已经定位到问题。provider端使用了20880作为dubbo端口，k8s集群中存在其他服务开启了sidecar，创建的service也使用了20880端口，但声明为了http协议，造成了这个问题。
