### ISSUE TITLE
Triple真的完美兼容原生grpc吗？

### ISSUE THREAD

**Issue by forbetter100** [apache/dubbo#10600]
I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
根据官网的说法，Triple协议能完美兼容grpc协议，按照我的理解，应该属于"is a"的关系。
为了验证这个说法，我做了两个实验：

1. 将dubbo-samples里的“dubbo-samples-grpc”的经典“Greeter”作为Provider跑起来，Consumer用原生grpc来调用，这时候是能调通的。然后我发现，provider的声明里有这么一个细节，protocol=grpc，而不是tri。
>  <dubbo:service interface="io.grpc.examples.helloworld.DubboGreeterGrpc$IGreeter" ref="greeterImpl" protocol="grpc"/>
2. 于是我做了第二个实验，我将这里的protocol改成tri

> <dubbo:service interface="io.grpc.examples.helloworld.DubboGreeterGrpc$IGreeter" ref="greeterImpl" protocol="tri"/>
这时候，异常发生了，如下
`[10/09/22 11:50:01:001 CST] Dubbo-framework-shared-handler-thread-1 ERROR serial.SerializingExecutor:  [DUBBO] Exception while executing runnable org.apache.dubbo.rpc.protocol.tri.stream.ServerStream$ServerTransportObserver$$Lambda$242/6102697@122e6b4, dubbo version: 3.0.7, current host: 192.168.1.20
java.lang.NullPointerException
	at org.apache.dubbo.rpc.protocol.tri.stream.ServerStream$ServerTransportObserver.doOnData(ServerStream.java:368)
	at org.apache.dubbo.rpc.protocol.tri.stream.ServerStream$ServerTransportObserver.lambda$onData$1(ServerStream.java:364)
	at org.apache.dubbo.rpc.protocol.tri.stream.ServerStream$ServerTransportObserver$$Lambda$242/6102697.run(Unknown Source)
	at org.apache.dubbo.common.threadpool.serial.SerializingExecutor.run(SerializingExecutor.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

我是否可以理解，这本质是一种不兼容？以及，我的核心疑问，既然官网说triple完美兼容grpc，那么protocol=grpc的意义在哪里？

**Comment by AlbumenJ** [comment]
dubbo-samples-grpc 是从 Dubbo 2 开始通过原生 grpc 进行兼容的组件，可以理解为 `protocol=grpc` 是 Dubbo 2 原生通过代理适配兼容的，triple 是 Dubbo 3 重新实现的新协议，对应的用例是 dubbo-samples-triple。
至于那个报错可以升级一下 Dubbo 版本到 3.0.11 看下

**Comment by forbetter100** [comment]
> dubbo-samples-grpc 是从 Dubbo 2 开始通过原生 grpc 进行兼容的组件，可以理解为 `protocol=grpc` 是 Dubbo 2 原生通过代理适配兼容的，triple 是 Dubbo 3 重新实现的新协议，对应的用例是 dubbo-samples-triple。 至于那个报错可以升级一下 Dubbo 版本到 3.0.11 看下

用dubbo-samples-triple实验，跟原生grpc是兼容了。不过dubbo-samples-grpc还是不行（已经按照要求升级到3.0.11）

**Comment by asa3311** [comment]
我测试下看看

**Comment by chickenlj** [comment]
>

直接用 dubbo-samples-triple 就可以了，没必要再用 dubbo-samples-grpc 了（这种模式将逐步停止维护）

**Comment by asa3311** [comment]
triple案例的生成代码工具与grpc案例不一样，导致grpc生成的代码服务名方法名没办法在triple protocol里面找到映射关系，建议使用最新的triple的sample去做原生grpc调用。
