### ISSUE TITLE
使用Dubbo 3.1.0 Proxyless Mesh模式，接口调用时报NPE

### ISSUE THREAD

**Issue by shelltea** [apache/dubbo#10656]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.0
* Java version: 1.8

### Steps to reproduce this issue

1. 在官方示例上稍微修改了一些进行测试，https://dubbo.apache.org/zh/overview/tasks/mesh/proxyless/
2. Consumer调用Provider接口时报错：
```
java.lang.NullPointerException: null
at org.apache.dubbo.registry.xds.XdsServiceDiscovery.getInstances(XdsServiceDiscovery.java:72)
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribeURLs(ServiceDiscoveryRegistry.java:314)
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.doSubscribe(ServiceDiscoveryRegistry.java:216)
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribe(ServiceDiscoveryRegistry.java:184)
at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:111)
at org.apache.dubbo.registry.integration.DynamicDirectory.subscribe(DynamicDirectory.java:180)
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.subscribe(ServiceDiscoveryRegistryDirectory.java:124)
at org.apache.dubbo.registry.integration.RegistryProtocol.doCreateInvoker(RegistryProtocol.java:571)
at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getServiceDiscoveryInvoker(InterfaceCompatibleRegistryProtocol.java:65)
at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshServiceDiscoveryInvoker(MigrationInvoker.java:436)
at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToApplicationFirstInvoker(MigrationInvoker.java:244)
at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.refreshInvoker(MigrationRuleHandler.java:73)
at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:57)
at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:243)
at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:536)
at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:506)
at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:488)
at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:74)
at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:80)
at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:71)
at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:52)
at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
at org.apache.dubbo.config.ReferenceConfig.createInvokerForRemote(ReferenceConfig.java:600)
at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:441)
at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:295)
at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:227)
at org.apache.dubbo.config.utils.SimpleReferenceCache.destroyReference(SimpleReferenceCache.java:262)
at org.apache.dubbo.config.utils.SimpleReferenceCache.destroy(SimpleReferenceCache.java:215)
at org.apache.dubbo.config.utils.SimpleReferenceCache.destroy(SimpleReferenceCache.java:239)
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:388)
at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:363)
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:154)
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:111)
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:100)
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:45)
at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404)
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361)
at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:898)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554)
at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755)
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236)
```

Consumer端和Provider端配置相同，如下：
```
dubbo.consumer.check = false
dubbo.registry.address = xds://istiod.istio-system.svc:15012
dubbo.application.qosEnable = true
dubbo.application.qosAcceptForeignIp = true
dubbo.protocols.triple.name = tri
dubbo.protocols.triple.port = 20881
dubbo.application.metadata-service-port = 20885
```

**Comment by AlbumenJ** [comment]
往前翻下日志，这个一般是 xds client 初始化失败导致的。看下是不是 jwt 配置有问题

**Comment by shelltea** [comment]
已经用以下方法开启了 `first-party-jwt` 的支持

```
istioctl install --set Values.global.jwtPolicy=first-party-jwt
```

**Comment by AlbumenJ** [comment]
> 已经用以下方法开启了 `first-party-jwt` 的支持
> 
> ```
> istioctl install --set Values.global.jwtPolicy=first-party-jwt
> ```

看下完整日志

**Comment by chickenlj** [comment]
Any update?
