### ISSUE TITLE
 Dubbo spring boot start Start-up failure

### ISSUE THREAD

**Issue by TOP-LH** [apache/dubbo#10723]
### Environment

* Dubbo spring boot start version: 3.1.0
* Java version: 1.8
* springboot version: 2.3.7.RELEASE
* springcloud alibaba version: 2.2.2.RELEASE
* guava version: 31.1-jre

### Steps to reproduce this issue

启动失败
Start-up failure

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

启动成功
Successful start

### Actual Behavior

If there is an exception, please attach the exception trace:

```
2022-10-10 14:25:19.670  INFO 8168 --- [           main] o.a.dubbo.registry.nacos.NacosRegistry   :  [DUBBO] Loaded registry cache file C:\Users\lihao3\.dubbo\dubbo-registry-XXX-wpos-XXX.XXX.XXX.XX-8848.cache, dubbo version: 3.1.0, current host: 192.168.137.1
2022-10-10 14:25:19.671  INFO 8168 --- [           main] o.a.dubbo.registry.nacos.NacosRegistry   :  [DUBBO] Register: dubbo://192.168.137.1:20880/com.XXX.wpos.module.oss.api.service.UploadFileDataDubboService?anyhost=true&application=XXX-wpos&background=false&deprecated=false&dispatcher=message&dubbo=2.0.2&dynamic=true&generic=false&interface=com.XXX.wpos.module.oss.api.service.UploadFileDataDubboService&methods=selectFileInfoVOListByObjectId,insertObjectIdByGuid&pid=8168&release=3.1.0&retries=0&service-name-mapping=true&side=provider&threadpool=cached&timeout=30000&timestamp=1665383118540, dubbo version: 3.1.0, current host: 192.168.137.1
2022-10-10 14:25:19.680  INFO 8168 --- [           main] o.a.dubbo.registry.nacos.NacosRegistry   :  [DUBBO] Subscribe: provider://192.168.137.1:20880/com.XXX.wpos.module.oss.api.service.UploadFileDataDubboService?anyhost=true&application=XXX-wpos&background=false&bind.ip=192.168.137.1&bind.port=20880&category=configurators&check=false&deprecated=false&dispatcher=message&dubbo=2.0.2&dynamic=true&generic=false&interface=com.XXX.wpos.module.oss.api.service.UploadFileDataDubboService&methods=selectFileInfoVOListByObjectId,insertObjectIdByGuid&pid=8168&qos.enable=false&release=3.1.0&retries=0&service-name-mapping=true&side=provider&threadpool=cached&timeout=30000&timestamp=1665383118540, dubbo version: 3.1.0, current host: 192.168.137.1
2022-10-10 14:25:19.701 ERROR 8168 --- [           main] o.a.d.c.deploy.DefaultModuleDeployer     :  [DUBBO] Dubbo Module[1.1.1] start failed: java.lang.NoClassDefFoundError: com/alibaba/nacos/shaded/com/google/common/collect/Maps, dubbo version: 3.1.0, current host: 192.168.137.1

java.lang.NoClassDefFoundError: com/alibaba/nacos/shaded/com/google/common/collect/Maps
	at org.apache.dubbo.registry.nacos.util.NacosInstanceManageUtil.<clinit>(NacosInstanceManageUtil.java:40) ~[dubbo-3.1.0.jar:3.1.0]
	at org.apache.dubbo.registry.nacos.NacosRegistry.doSubscribe(NacosRegistry.java:214) ~[dubbo-3.1.0.jar:3.1.0]
	at org.apache.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:298) ~[dubbo-3.1.0.jar:3.1.0]
	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:111) ~[dubbo-3.1.0.jar:3.1.0]
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:261) ~[dubbo-3.1.0.jar:3.1.0]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:64) ~[dubbo-3.1.0.jar:3.1.0]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:74) ~[dubbo-3.1.0.jar:3.1.0]
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:58) ~[dubbo-3.1.0.jar:3.1.0]
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47) ~[dubbo-3.1.0.jar:3.1.0]
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) ~[dubbo-3.1.0.jar:3.1.0]
	at org.apache.dubbo.config.ServiceConfig.doExportUrl(ServiceConfig.java:647) ~[dubbo-3.1.0.jar:3.1.0]
	at org.apache.dubbo.config.ServiceConfig.exportRemote(ServiceConfig.java:625) ~[dubbo-3.1.0.jar:3.1.0]
	at org.apache.dubbo.config.ServiceConfig.exportUrl(ServiceConfig.java:584) ~[dubbo-3.1.0.jar:3.1.0]
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:416) ~[dubbo-3.1.0.jar:3.1.0]
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:400) ~[dubbo-3.1.0.jar:3.1.0]
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:362) ~[dubbo-3.1.0.jar:3.1.0]
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:234) ~[dubbo-3.1.0.jar:3.1.0]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServiceInternal(DefaultModuleDeployer.java:337) ~[dubbo-3.1.0.jar:3.1.0]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServices(DefaultModuleDeployer.java:309) ~[dubbo-3.1.0.jar:3.1.0]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:145) ~[dubbo-3.1.0.jar:3.1.0]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:111) [dubbo-3.1.0.jar:3.1.0]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:100) [dubbo-3.1.0.jar:3.1.0]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:45) [dubbo-3.1.0.jar:3.1.0]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) [spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) [spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404) [spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361) [spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:898) [spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554) [spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) [spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405) [spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.7.RELEASE.jar:2.3.7.RELEASE]
	at com.XXX.wpos.WposWebApplication.main(WposWebApplication.java:18) [classes/:na]
Caused by: java.lang.ClassNotFoundException: com.alibaba.nacos.shaded.com.google.common.collect.Maps
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[na:1.8.0_332]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_332]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[na:1.8.0_332]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_332]
	... 38 common frames omitted

```

**Comment by AlbumenJ** [comment]
添加下 nacos-client 的依赖，默认 dubbo 不会传递这个依赖

**Comment by TOP-LH** [comment]
> 添加下 nacos-client 的依赖，默认 dubbo 不会传递这个依赖

使用了nacos作为注册中心和配置中心, 添加了一下依赖, 已经引入了这个依赖, 是版本过低了吗?
``` xml
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
```
![image](https://user-images.githubusercontent.com/49888630/194984168-ae9a1fa1-559d-4026-8e8c-dc3c8df0cb7a.png)

**Comment by AlbumenJ** [comment]
dubbo 3 需要使用 nacos 2 及以上的版本

**Comment by TOP-LH** [comment]
> dubbo 3 需要使用 nacos 2 及以上的版本

那我能否使用nacos1,X的版本, 但是使用nacos-client2,x的版本吗?

**Comment by AlbumenJ** [comment]
> > dubbo 3 需要使用 nacos 2 及以上的版本
> 
> 那我能否使用nacos1,X的版本, 但是使用nacos-client2,x的版本吗?

按照 nacos 官方的说明，nacos-client 1.x 支持 nacos-server 1.x~2.x ; nacos-client 2.x 只支持 nacos-server 2.x

**Comment by TOP-LH** [comment]
> > > dubbo 3 需要使用 nacos 2 及以上的版本
> > 
> > 
> > 那我能否使用nacos1,X的版本, 但是使用nacos-client2,x的版本吗?
> 
> 按照 nacos 官方的说明，nacos-client 1.x 支持 nacos-server 1.x~2.x ; nacos-client 2.x 只支持 nacos-server 2.x

那就是说非nacos2x暂且不能使用dubbo3吗

**Comment by AlbumenJ** [comment]
> > > > dubbo 3 需要使用 nacos 2 及以上的版本
> > > 
> > > 
> > > 那我能否使用nacos1,X的版本, 但是使用nacos-client2,x的版本吗?
> > 
> > 
> > 按照 nacos 官方的说明，nacos-client 1.x 支持 nacos-server 1.x~2.x ; nacos-client 2.x 只支持 nacos-server 2.x
> 
> 那就是说非nacos2x暂且不能使用dubbo3吗

是的，这个是 Nacos 侧特性的限制，Dubbo 3 所需的能力 Nacos 仅在 2.x 提供。
