### ISSUE TITLE
dubbo 3.1.1 先启动消费者，再启动服务者报错

### ISSUE THREAD

**Issue by pakchoily** [apache/dubbo#10736]
- [X] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
依赖版本如下：

                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>2021.0.4.0</version>

                <artifactId>spring-boot-starter-parent</artifactId>
                <version>2.6.11</version>

                <artifactId>spring-cloud-dependencies</artifactId>
                <version>2021.0.4</version>

                <artifactId>dubbo-bom</artifactId>
                <version>3.1.1</version>

                jdk使用17

服务提供者的yaml文件
~~~yaml
#库存服务端口
server:
  port: 8021

#订单服务名称
spring:
  application:
    name: stock-service
  #配置nacos注册中心地址、用户名、密码
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848/
        username: nacos
        password: nacos
        namespace: test
        #配置为开发环境分组
        group: dev

dubbo:
  application:
    #改为应用级的注册
    register-mode: instance
  #配置使用tri作为RPC协议
  protocol:
    name: tri
    port: 20880
  #配置nacos为注册中心
  registry:
    address: nacos://localhost:8848
    username: nacos
    password: nacos
    parameters:
      namespace: test
    group: dev
    check: false
  consumer:
    check: false

~~~
使用nacos作为注册中心，如果先启动消费者，等消费者完全启动，再启动服务提供者，会报如下错误，不知道有办法解决吗？

~~~java
java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.localAddress()" because "this.channel" is null
	at org.apache.dubbo.remoting.transport.netty4.NettyPortUnificationServer.getLocalAddress(NettyPortUnificationServer.java:221) ~[dubbo-3.1.1.jar:3.1.1]
	at org.apache.dubbo.remoting.transport.AbstractServer.<init>(AbstractServer.java:75) ~[dubbo-3.1.1.jar:3.1.1]
	at org.apache.dubbo.remoting.api.pu.AbstractPortUnificationServer.<init>(AbstractPortUnificationServer.java:46) ~[dubbo-3.1.1.jar:3.1.1]
~~~

**Comment by pakchoily** [comment]
已解决，dubbo的 port 不要配置 20880，要么比nacos端口8848大1000，要么干脆别配。
