### ISSUE TITLE
多实例部署，部分服务启动的时候报错，找不到provider， 服务提供者是正常部署的

### ISSUE THREAD

**Issue by chenxiyuluo** [apache/dubbo#10732]
org.apache.dubbo.rpc.RpcException: No provider available from registry **** for service ***:1.0.0 on consumer *** use dubbo version 2.7.16, please check status of providers(disabled, not registered or in blacklist).
core-sdk-user-002  | 	at org.apache.dubbo.registry.integration.DynamicDirectory.doList(DynamicDirectory.java:169)
core-sdk-user-002  | 	at org.apache.dubbo.rpc.cluster.directory.AbstractDirectory.list(AbstractDirectory.java:99)
core-sdk-user-002  | 	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.list(AbstractClusterInvoker.java:297)
core-sdk-user-002  | 	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:262)
core-sdk-user-002  | 	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)
core-sdk-user-002  | 	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)
core-sdk-user-002  | 	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:98)
core-sdk-user-002  | 	at org.apache.dubbo.registry.client.migration.MigrationInvoker.invoke(MigrationInvoker.java:170)
core-sdk-user-002  | 	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:96)

**Comment by AlbumenJ** [comment]
部署细节贴一下

**Comment by hujun-w-2** [comment]
me too 偶现

**Comment by chenxiyuluo** [comment]
> 部署细节贴一下

就是常规集群部署，这个问题是偶发的，偶尔某一台实例会遇到这个问题

**Comment by AlbumenJ** [comment]
> > 部署细节贴一下
> 
> 就是常规集群部署，这个问题是偶发的，偶尔某一台实例会遇到这个问题

使用的 nacos 注册中心吗

**Comment by tinybyhuang** [comment]
我也有同样的问题，请问有进展吗

**Comment by tinybyhuang** [comment]
`The invoker DefaultServiceInstance{serviceName='distinct-patient-service', host='10.0.18.9', port=21350, enabled=true, healthy=true, metadata={dubbo.metadata-service.url-params={"serialization":"hessian2","prefer.serialization":"hessian2","version":"1.0.0","dubbo":"2.0.2","release":"3.2.9","side":"provider","port":"21350","protocol":"dubbo"}, dubbo.endpoints=[{"port":21350,"protocol":"dubbo"}], dubbo.metadata.revision=1619c6ec1ac88ec96848df730d81c457, dubbo.metadata.storage-type=local, timestamp=1728363217206}}, service{name='com.distinct.patient.api.PatientApi',group='null',version='1.0.0',protocol='dubbo',port='21350',params={side=provider, release=3.2.9, methods=, deprecated=false, dubbo=2.0.2, interface=com.distinct.patient.api.PatientApi, service-name-mapping=true, version=1.0.0, timeout=30000, generic=false, revision=1.0.0, serialize.check.status=WARN, serialization=hessian2, application=distinct-patient-service, prefer.serialization=hessian2, dynamic=true, REGISTRY_CLUSTER=nacos-registry},} has been added to invalidate list due to connectivity problem. Will trying to reconnect to it in the background., dubbo version: 3.2.9, current host: 10.0.18.9`

`No provider available from registry RegistryDirectory(registry: nacos-ans.mse.aliyuncs.com:8848)-Directory(invokers: 0[], validInvokers: 0[], invokersToReconnect: 0[]) for service com.distinct.patient.api.PatientApi:1.0.0 on consumer 10.0.18.9 use dubbo version 3.2.9, please check status of providers(disabled, not registered or in blacklist)`

我这边是提供者实例正常启动后，消费者还是把它标识为blacklist，想问下是什么场景下才能从blacklist清除，后面的日志没有看到reconnect了，给我文档资料也可以
