### ISSUE TITLE
dubbo 2.7.13 升级 dubbo 3.0.7报错

### ISSUE THREAD

**Issue by Vectlin** [apache/dubbo#10762]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.7
* Operating System version: xxx
* Java version: java8

### Steps to reproduce this issue

1. dubbo从2.7.13升级至3.0.7
2.目前代码配置为
![image](https://user-images.githubusercontent.com/44886393/196617838-2905f24f-5b32-448b-9946-e98bc68eb82a.png)
这结果filter spi文件都加上了，还是报错

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

[2022-10-19 13:07:27] [tms-service] [MacBook-Pro.local] [ERROR] [] [main] org.springframework.boot.SpringApplication Application run failed
java.lang.IllegalStateException: No such extension errorcodeExceptionFilter for filter/org.apache.dubbo.rpc.Filter,org.apache.dubbo.rpc.cluster.filter.ClusterFilter
	at org.apache.dubbo.config.utils.ConfigValidationUtils.checkMultiExtension(ConfigValidationUtils.java:653)
	at org.apache.dubbo.config.utils.ConfigValidationUtils.validateAbstractInterfaceConfig(ConfigValidationUtils.java:396)
	at org.apache.dubbo.config.utils.ConfigValidationUtils.validateServiceConfig(ConfigValidationUtils.java:413)
	at org.apache.dubbo.config.ServiceConfig.checkAndUpdateSubConfigs(ServiceConfig.java:340)
	at org.apache.dubbo.config.ServiceConfig.postProcessRefresh(ServiceConfig.java:347)
	at org.apache.dubbo.config.AbstractConfig.refresh(AbstractConfig.java:698)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServiceInternal(DefaultModuleDeployer.java:320)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServices(DefaultModuleDeployer.java:313)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:145)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:111)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:100)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:45)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:896)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:163)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.xx.info.tms.XxServiceApplication.main(XxServiceApplication.java:18)

**Comment by liufeiyu1002** [comment]
java.lang.IllegalStateException: No such extension errorcodeExceptionFilter for filter/org.apache.dubbo.rpc.Filter,org.apache.dubbo.rpc.cluster.filter.ClusterFilter

**Comment by AlbumenJ** [comment]
![image](https://user-images.githubusercontent.com/9292748/196841918-f020ee13-a62d-4a2f-be6f-982c851d594a.png)

这两个名字不一样
