### ISSUE TITLE
调试单个服务启动后控制台一直报 rpc错误

### ISSUE THREAD

**Issue by wcc1433** [apache/dubbo#10824]
有时候我们要调试单个服务，这个服务依赖了其它服务提供的 dubbo接口。因为是本地调试，其它服务没有启动，所以控制台一直报 rpc错误。能不能提供一个开关之类的

---------------------- 下面是异常日志 --------------------------------
org.apache.dubbo.rpc.RpcException: Fail to create remoting client for service(dubbo://172.29.142.18:20881/org.apache.dubbo.metadata.MetadataService?codec=dubbo&connections=1&corethreads=2&dubbo=2.0.2&group=erp-dubbo&heartbeat=60000&port=20881&protocol=dubbo&release=3.0.9&retries=0&side=provider&threadpool=cached&threads=100&timeout=5000&version=1.0.0): client(url: dubbo://172.29.142.18:20881/org.apache.dubbo.metadata.MetadataService?codec=dubbo&connections=1&corethreads=2&dubbo=2.0.2&group=erp-dubbo&heartbeat=60000&port=20881&protocol=dubbo&release=3.0.9&retries=0&side=provider&threadpool=cached&threads=100&timeout=5000&version=1.0.0) failed to connect to server /172.29.142.18:20881 client-side timeout 3000ms (elapsed: 3003ms) from netty client 192.168.2.87 using dubbo version 3.0.9
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.initClient(DubboProtocol.java:632) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getClients(DubboProtocol.java:442) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.protocolBindingRefer(DubboProtocol.java:410) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.refer(DubboProtocol.java:401) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:85) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:77) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:74) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:52) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.registry.client.metadata.MetadataUtils.referProxy(MetadataUtils.java:135) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.registry.client.metadata.MetadataUtils.getRemoteMetadata(MetadataUtils.java:156) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.getRemoteMetadata(AbstractServiceDiscovery.java:169) [dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.doOnEvent(ServiceInstancesChangedListener.java:152) [dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.onEvent(ServiceInstancesChangedListener.java:112) [dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener$AddressRefreshRetryTask.run(ServiceInstancesChangedListener.java:523) [dubbo-3.0.9.jar:3.0.9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
Caused by: org.apache.dubbo.remoting.RemotingException: client(url: dubbo://172.29.142.18:20881/org.apache.dubbo.metadata.MetadataService?codec=dubbo&connections=1&corethreads=2&dubbo=2.0.2&group=erp-dubbo&heartbeat=60000&port=20881&protocol=dubbo&release=3.0.9&retries=0&side=provider&threadpool=cached&threads=100&timeout=5000&version=1.0.0) failed to connect to server /172.29.142.18:20881 client-side timeout 3000ms (elapsed: 3003ms) from netty client 192.168.2.87 using dubbo version 3.0.9
	at org.apache.dubbo.remoting.transport.netty4.NettyClient.doConnect(NettyClient.java:197) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:214) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.remoting.transport.AbstractClient.<init>(AbstractClient.java:74) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.remoting.transport.netty4.NettyClient.<init>(NettyClient.java:89) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.remoting.transport.netty4.NettyTransporter.connect(NettyTransporter.java:40) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.remoting.Transporter$Adaptive.connect(Transporter$Adaptive.java) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.remoting.Transporters.connect(Transporters.java:74) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchanger.connect(HeaderExchanger.java:39) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.remoting.exchange.Exchangers.connect(Exchangers.java:107) ~[dubbo-3.0.9.jar:3.0.9]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.initClient(DubboProtocol.java:628) ~[dubbo-3.0.9.jar:3.0.9]
	... 21 common frames omitted

**Comment by AlbumenJ** [comment]
这个报错是因为网络不通 （192.168.2.87 -> 172.29.142.18) 导致的，如果本地调试没有使用到对应的访问这个日志可以不用管。

**Comment by wcc1433** [comment]
明白了，因为本地没有单独的配置，所以启动之后也是连接测试环境

可是这个日志一直刷，我的控制台全是这个异常。搞得我们没法调试

**Comment by wcc1433** [comment]
> 这个报错是因为网络不通 （192.168.2.87 -> 172.29.142.18) 导致的，如果本地调试没有使用到对应的访问这个日志可以不用管。

明白了，因为本地没有单独的配置，所以启动之后也是连接测试环境，
可是这个日志一直刷，我的控制台全是这个异常。搞得我们没法调试

**Comment by AlbumenJ** [comment]
> > 这个报错是因为网络不通 （192.168.2.87 -> 172.29.142.18) 导致的，如果本地调试没有使用到对应的访问这个日志可以不用管。
> 
> 明白了，因为本地没有单独的配置，所以启动之后也是连接测试环境， 可是这个日志一直刷，我的控制台全是这个异常。搞得我们没法调试

dubbo 的 log level 可以调高

**Comment by wcc1433** [comment]
好的，感谢
