### ISSUE TITLE
dubbo provider set host (Address already in use: bind)

### ISSUE THREAD

**Issue by wpailn** [apache/dubbo#10835]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.12
* Operating System version: windows10
* Java version: 1.8

### Steps to reproduce this issue

1. provider config
```
dubbo:
  application:
    name: producer
    logger: slf4j
  protocol:
    name: dubbo
    host: test-local
    port: -1
  registry:
    id: zk-registry
    address: zookeeper://127.0.0.1:2181
  config-center:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181
```
2. protocol set host: test-local  DubboProtocol method openServer(URL url)  cannot filter ip:port and host:port

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
 Failed to bind NettyServer on /X.X.X.X:20880, cause: Address already in use: bind
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.createServer(DubboProtocol.java:378) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.openServer(DubboProtocol.java:343) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.export(DubboProtocol.java:325) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:72) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:66) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:61) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.registry.integration.RegistryProtocol.lambda$doLocalExport$2(RegistryProtocol.java:294) ~[dubbo-3.0.12.jar:3.0.12]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_341]
	at org.apache.dubbo.registry.integration.RegistryProtocol.doLocalExport(RegistryProtocol.java:292) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:239) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:72) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:64) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:58) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.config.ServiceConfig.doExportUrl(ServiceConfig.java:646) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.config.ServiceConfig.exportRemote(ServiceConfig.java:624) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.config.ServiceConfig.exportUrl(ServiceConfig.java:583) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:415) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:399) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:361) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:233) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.config.metadata.ConfigurableMetadataServiceExporter.export(ConfigurableMetadataServiceExporter.java:71) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.config.metadata.ExporterDeployListener.onModuleStarted(ExporterDeployListener.java:70) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.exportMetadataService(DefaultApplicationDeployer.java:923) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.prepareApplicationInstance(DefaultApplicationDeployer.java:613) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.checkState(DefaultApplicationDeployer.java:824) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.notifyModuleChanged(DefaultApplicationDeployer.java:812) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.onModuleStarted(DefaultModuleDeployer.java:257) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:164) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:132) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:111) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:100) ~[dubbo-3.0.12.jar:3.0.12]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:45) ~[dubbo-3.0.12.jar:3.0.12]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938) ~[spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.20.jar:5.3.20]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.0.jar:2.7.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.0.jar:2.7.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.0.jar:2.7.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.0.jar:2.7.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.0.jar:2.7.0]
	at org.example.ProducerApp.main(ProducerApp.java:11) ~[classes/:?]
Caused by: org.apache.dubbo.remoting.RemotingException: Failed to bind NettyServer on /X.X.X.X:20880, cause: Address already in use: bind


```

**Comment by AlbumenJ** [comment]
Was 20880 port already in used?

**Comment by wpailn** [comment]
> Was 20880 port already in used?
yes  and version 3.0.0 does not have this problem.

**Comment by wpailn** [comment]
> > Was 20880 port already in used?
> > yes  and version 3.0.0 does not have this problem.

first:  dubbo  bind  test-local:20880  and then dubbo bind 192.X.X.X:20880

**Comment by wpailn** [comment]
> > > Was 20880 port already in used?
> > > yes  and version 3.0.0 does not have this problem.
> 
> first: dubbo bind test-local:20880 and then dubbo bind 192.X.X.X:20880

the host "test-local" ip is 127.0.0.1

**Comment by wpailn** [comment]
> > > > Was 20880 port already in used?
> > > > yes  and version 3.0.0 does not have this problem.
> > 
> > 
> > first: dubbo bind test-local:20880 and then dubbo bind 192.X.X.X:20880
> 
> the host "test-local" ip is 127.0.0.1

I find dubbo://X.X.X.X:20880/org.apache.dubbo.metadata.MetadataService  used the default IP instead of the host "test-local"

**Comment by AlbumenJ** [comment]
how about set host as `127.0.0.1` and `192.x.x.x` directly

**Comment by wpailn** [comment]
the business actually needs to provide is the host

**Comment by wpailn** [comment]
By tracing the source code, I found that the findConfiguredHost method and findConfiguredPort method in ServiceConfig, the ProtocolConfig and ProviderConfig of MetadataService did not get my configuration correctly. I found that the DUBBO was set according to the source code_ IP_ TO_ BIND、DUBBO_ IP_ TO_ REGISTRY、DUBBO_ PORT_ TO_ BIND、DUBBO_ PORT_ TO_ REGISTRY can avoid this problem

**Comment by wpailn** [comment]
example：
java -DDUBBO_IP_TO_REGISTRY=test-local -DDUBBO_PORT_TO_REGISTRY=20880 -DDUBBO_IP_TO_BIND=test-local -DDUBBO_PORT_TO_BIND=20880 -jar XXX.jar

**Comment by chickenlj** [comment]
If you have multiple network interfaces available, what Dubbo can do is randomly pick one to register to the registry.

But for `binding`, I remember Dubbo will simply listen on `0.0.0.0:20880`, which means all connection build requests on all interfaces with port 20880 will be accepted. But you need to set the IP or host to be registered to Registry if not all IPs are reachable from the consumer side, use the property you mentioned above: DDUBBO_IP_TO_REGISTRY
