### ISSUE TITLE
Dubbo 升级 2.7.18 后，泛化调用异常

### ISSUE THREAD

**Issue by weii918** [apache/dubbo#10848]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version:  2.7.18
* Operating System version: MacOS
* Java version: 1.8

### Steps to reproduce this issue

1. dubbo 从 2.7.8 升级至 2.7.18
2. 泛化调用异常：Failed to invoke the method $invoke in the service org.apache.dubbo.rpc.service.GenericService. No provider available for the service XXXXX，检查了 zookeeper 服务是注册上去的
3. 泛化调用代码如下：
```
RegistryConfig registry = new RegistryConfig();
ReferenceConfig<GenericService> reference = new ReferenceConfig<>();
HashMap<String,String> map=new HashMap<>(1);
ApplicationConfig application = new ApplicationConfig();
application.setName(this.properties.getApplicationName());
//通过注册器拿到服务信息，不推荐，因为会导致所有的请求压力转向注册中心，建议使用URL，直接发起调用
registry.setAddress(this.properties.getAddress());
reference.setRegistry(registry);
registry.setParameters(map);
reference.setApplication(application);
reference.setInterface(interfaceName);
if (StringUtils.isNotEmpty(group)) {
    reference.setGroup(group);
}
if (StringUtils.isNotEmpty(version)) {
    reference.setVersion(version);
}
reference.setGeneric("true");
reference.setCheck(false);
reference.setTimeout(CONSUMER_TIMEOUT);
genericService = reference.get();
genericService.$invoke(methodName, paramTypes, paramValues)
```

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

 正常调用

If there is an exception, please attach the exception trace:

```
 Failed to invoke the method $invoke in the service org.apache.dubbo.rpc.service.GenericService. No provider available for the service XXXXX from registry 127.0.0.1:2181 on the consumer xxxxxx using the dubbo version 2.7.18. Please check if the providers have been started and registered. 
org.apache.dubbo.rpc.RpcException: Failed to invoke the method $invoke in the service org.apache.dubbo.rpc.service.GenericService. No provider available for the service XXXXX from registry 127.0.0.1:2181 on the consumer xxxxxx using the dubbo version 2.7.18. Please check if the providers have been started and registered.
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.checkInvokers(AbstractClusterInvoker.java:288) ~[dubbo-2.7.18.jar:2.7.18]
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:59) ~[dubbo-2.7.18.jar:2.7.18]
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:265) ~[dubbo-2.7.18.jar:2.7.18]
	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47) ~[dubbo-2.7.18.jar:2.7.18]
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92) ~[dubbo-2.7.18.jar:2.7.18]
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:98) ~[dubbo-2.7.18.jar:2.7.18]
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.invoke(MigrationInvoker.java:170) ~[dubbo-2.7.18.jar:2.7.18]
```

**Comment by wangzihaogithub** [comment]
你是怎么解决的， 我也遇到了和你一模一样
