### ISSUE TITLE
2.7.8版本后，存在Service循环依赖时报错   llegalStateException: <dubbo:service interface="" /> interface not allow null!

### ISSUE THREAD

**Issue by iloveoovo** [apache/dubbo#10857]
- [ ] 有相似问题，但是问题依然存在： [6776](https://github.com/apache/dubbo/issues/6776) 

### Environment

* Dubbo version: 2.7.18
* Operating System version: macOs
* Java version: 1.8

### Steps to reproduce this issue

1. 新建A、B、C三个服务，A服务依赖B、C服务，B服务依赖C服务，C服务依赖B服务
2. 项目启动报错- llegalStateException: <dubbo:service interface="" /> interface not allow null!
3. 2.7.7以前版本都能正常启动，2.7.8及以后启动均报错
4. 通过代码比对，发现服务存在循环依赖+inJvm调用情况下，会出现C获取B的Bean 为 early bean reference，此时属性都为空，进行export 直接报错
5. ReferenceAnnotationBeanPostProcessor的红圈位置为出错位置：

![image](https://user-images.githubusercontent.com/12338948/198962127-96224094-453e-4f23-8e4b-1e3ca2fc6a06.png)
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/12338948/198962408-8ab03871-bb66-49d8-bcf1-048cdcccf731.png">

Pls. provide [GitHub address] to reproduce this issue.
https://github.com/iloveoovo/dubbo-issue

### Expected Behavior

正常启动不报错

### Actual Behavior

启动过程报错

If there is an exception, please attach the exception trace:

```
Caused by: java.lang.IllegalStateException: <dubbo:service interface="" /> interface not allow null!
	at org.apache.dubbo.config.ServiceConfig.checkAndUpdateSubConfigs(ServiceConfig.java:275) ~[classes/:na]
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:217) ~[classes/:na]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.exportServiceBeanIfNecessary(ReferenceAnnotationBeanPostProcessor.java:337) ~[classes/:na]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.prepareReferenceBean(ReferenceAnnotationBeanPostProcessor.java:328) ~[classes/:na]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.doGetInjectedBean(ReferenceAnnotationBeanPostProcessor.java:159) ~[classes/:na]
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.getInjectedObject(AbstractAnnotationBeanPostProcessor.java:409) ~[spring-context-support-1.0.11.jar:na]
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor$AnnotatedFieldElement.inject(AbstractAnnotationBeanPostProcessor.java:626) ~[spring-context-support-1.0.11.jar:na]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.postProcessPropertyValues(AbstractAnnotationBeanPostProcessor.java:179) ~[spring-context-support-1.0.11.jar:na]
```

**Comment by AlbumenJ** [comment]
Please upgrade to `3.1.1` to verify

**Comment by iloveoovo** [comment]
3.1.1 没有问题，能正常启动
