### ISSUE TITLE
在使用基于 IDL 方式，客户端和服务端合并部署在一个应用中使用injvm 协议 ，报java.lang.ClassCastException

### ISSUE THREAD

**Issue by OpenRCS** [apache/dubbo#10910]
报错异常
java.lang.ClassCastException: com.xx.xx.user.facade.LoginBySmsRequest cannot be cast to com.xx.xx.user.facade.LoginReply
	at com.xx.xx.user.facade.UserLoginFacadeDubboProxy1.loginBySms(UserLoginFacadeDubboProxy1.java) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.3.22.jar:5.3.22]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208) ~[spring-aop-5.3.22.jar:5.3.22]
	at com.sun.proxy.$Proxy102.loginBySms(Unknown Source) ~[?:?]

**Comment by lvjing2** [comment]
遇到同样的报错

**Comment by lvjing2** [comment]
发现原因是这里，使用了 requestClass 作为 returnType。这里是低级错误吗？
![image](https://github.com/apache/dubbo/assets/3754074/c1115b0b-b5bb-4404-b874-5f24e44352d3)

**Comment by namelessssssssssss** [comment]
> 发现原因是这里，使用了 requestClass 作为 returnType。这里是低级错误吗？ ![image](https://user-images.githubusercontent.com/3754074/275760908-c1115b0b-b5bb-4404-b874-5f24e44352d3.png)

https://github.com/apache/dubbo/pull/13200

**Comment by namelessssssssssss** [comment]
![image](https://github.com/apache/dubbo/assets/100946116/ad175457-ca3b-4532-a21f-9b11546b901b)
似乎之前也有人发现了这个问题，但是只在`org.apache.dubbo.rpc.stub.StubInvocationUtil`里做了简单修补，所以只有使用Triple协议进行stub调用时不会出错
