### ISSUE TITLE
Tried 1 times of the providers [172.18.1.49:8900] (1/3) from the registry nacos-grpc.qcloud.jcndev.com:8848 on the consumer 172.18.0.209 using the dubbo version 2.7.6. Last error is: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Consumer is shutting down and this call is going to be stopped without receiving any result, usually this is called by a slow provider instance or bad service implementation.

### ISSUE THREAD

**Issue by Jodio-liu** [apache/dubbo#10974]
又一个类似的[issue](https://github.com/apache/dubbo/issues/6294),但是没看到解决方案
服务偶现以下问题，大家有解决方案吗？

java.lang.reflect.InvocationTargetException: null###	
at sun.reflect.GeneratedMethodAccessor1347.invoke(Unknown Source)###	
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)###	
at java.lang.reflect.Method.invoke(Method.java:498)###	
at cn.j.crius.http.netty.NettyBizInvoker.invoke(NettyBizInvoker.java:133)###	
at cn.j.crius.http.netty.NettyBizHandler.handle(NettyBizHandler.java:127)###	
at cn.j.crius.http.netty.NettyHttpServerHandler.lambda$requestHandle$0(NettyHttpServerHandler.java:441)###	
at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)###	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)###	
at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)###	
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)###	
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)###	
at java.lang.Thread.run(Thread.java:748)###Caused by: org.apache.dubbo.rpc.RpcException: Failed to invoke the method fetchUserCoinTotal in the service cn.j.chloe.joint.coin.api.CoinRecordService. Tried 1 times of the providers [172.18.1.49:8900] (1/3) from the registry nacos-grpc.qcloud.jcndev.com:8848 on the consumer 172.18.0.209 using the dubbo version 2.7.6. Last error is: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Consumer is shutting down and this call is going to be stopped without receiving any result, usually this is called by a slow provider instance or bad service implementation.###	
at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:113)###	
at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:259)###	
at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)###	
at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)###	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:82)###	
at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:74)###	
at org.apache.dubbo.common.bytecode.proxy3.fetchUserCoinTotal(proxy3.java)###	
at org.apache.dubbo.common.bytecode.proxy3$$FastClassBySpringCGLIB$$c1976721.invoke(<generated>)###	
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)###	
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721)###	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)###	
at io.seata.spring.tcc.TccActionInterceptor.invoke(TccActionInterceptor.java:84)###	
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)###	
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656)###	at org.apache.dubbo.common.bytecode.proxy3$$EnhancerBySpringCGLIB$$d7edbf8.fetchUserCoinTotal(<generated>)###

**Comment by AlbumenJ** [comment]
Please check why nacos push offline notification of `172.18.1.49:8900`

**Comment by Jodio-liu** [comment]
> 

没明白，能相信说下吗？

**Comment by Jodio-liu** [comment]
> Please check why nacos push offline notification of `172.18.1.49:8900`

没太明白，可以详细说下嘛？

**Comment by AlbumenJ** [comment]
> > Please check why nacos push offline notification of `172.18.1.49:8900`
> 
> 没太明白，可以详细说下嘛？

看一下 `172.18.1.49:8900` 这台机器为什么在那个时间点下线了，是主动下线还是连接抖动导致的

**Comment by AlbumenJ** [comment]
> > 
> 
> 当时是刚上线完没多久，服务正常的，没有主动下线，就出现了两次连接异常

那应该是网络抖动导致的网络重连，如果服务正常可以忽略
