### ISSUE TITLE
Exception caught from Dubbo Admin

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo#11032]
```java
2022-11-25 20:16:56.951 ERROR 32001 --- [-20880-thread-3] o.a.dubbo.rpc.filter.ExceptionFilter     :  [DUBBO] Got unchecked and undeclared exception which called by fd00:1:5:5200:46d0:8a8f:9b6e:92bf. service: org.apache.dubbo.metadata.MetadataService, method: getSubscribedURLs, exception: java.lang.NullPointerException: null, dubbo version: 3.1.2, current host: 30.221.144.114, error code: 5-36. This may be caused by , go to https://dubbo.apache.org/faq/5/36 to find instructions. 

java.lang.NullPointerException: null
	at org.apache.dubbo.registry.client.metadata.MetadataServiceDelegation.getAllUnmodifiableSubscribedURLs(MetadataServiceDelegation.java:117)
	at org.apache.dubbo.registry.client.metadata.MetadataServiceDelegation.getSubscribedURLs(MetadataServiceDelegation.java:88)
	at org.apache.dubbo.registry.client.metadata.MetadataServiceDelegationDubboWrap1.invokeMethod(MetadataServiceDelegationDubboWrap1.java)
	at org.apache.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:73)
	at org.apache.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:100)
	at org.apache.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:55)
```

**Comment by MrJXL** [comment]
您好，请问解决了吗  我也遇到这个问题了。

**Comment by lvguangzeng** [comment]
升级dubbo-admin版本
