### ISSUE TITLE
mvn native compile build failed

### ISSUE THREAD

**Issue by panyox** [apache/dubbo#11048]
### Environment

* Dubbo version: 3.2.0-beta.2
* Operating System version: MacOS 13.0.1
* Java version: Java 17

### Steps to reproduce this issue
create a simple provider then start it.
it will start ok, then I try to compile by command:
```sh
./mvnw -Pnative native:compile
```
build failed throw this exception
```
2022-11-29T10:40:35.228+08:00  INFO 3424 --- [           main] f.a.ReferenceAnnotationBeanPostProcessor : class org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor was destroying!
Exception in thread "main" java.lang.IllegalStateException: No constructor or factory method candidate found for Root bean: class [org.apache.dubbo.config.spring.beans.factory.annotation.ServiceAnnotationPostProcessor]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null and argument types [java.util.Collections$SingletonSet<?>]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorOrFactoryMethod(ConstructorResolver.java:939)
        at org.springframework.beans.factory.support.RegisteredBean.resolveConstructorOrFactoryMethod(RegisteredBean.java:197)
        at org.springframework.beans.factory.aot.BeanDefinitionMethodGenerator.<init>(BeanDefinitionMethodGenerator.java:79)
        at org.springframework.beans.factory.aot.BeanDefinitionMethodGeneratorFactory.getBeanDefinitionMethodGenerator(BeanDefinitionMethodGeneratorFactory.java:102)
        at org.springframework.beans.factory.aot.BeanDefinitionMethodGeneratorFactory.getBeanDefinitionMethodGenerator(BeanDefinitionMethodGeneratorFactory.java:118)
        at org.springframework.beans.factory.aot.BeanRegistrationsAotProcessor.processAheadOfTime(BeanRegistrationsAotProcessor.java:45)
        at org.springframework.beans.factory.aot.BeanRegistrationsAotProcessor.processAheadOfTime(BeanRegistrationsAotProcessor.java:35)
        at org.springframework.context.aot.BeanFactoryInitializationAotContributions.getContributions(BeanFactoryInitializationAotContributions.java:67)
        at org.springframework.context.aot.BeanFactoryInitializationAotContributions.<init>(BeanFactoryInitializationAotContributions.java:49)
        at org.springframework.context.aot.BeanFactoryInitializationAotContributions.<init>(BeanFactoryInitializationAotContributions.java:44)
        at org.springframework.context.aot.ApplicationContextAotGenerator.lambda$processAheadOfTime$0(ApplicationContextAotGenerator.java:58)
        at org.springframework.context.aot.ApplicationContextAotGenerator.withCglibClassHandler(ApplicationContextAotGenerator.java:67)
        at org.springframework.context.aot.ApplicationContextAotGenerator.processAheadOfTime(ApplicationContextAotGenerator.java:53)
        at org.springframework.context.aot.ContextAotProcessor.performAotProcessing(ContextAotProcessor.java:106)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:84)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
        at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
        at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:76)
```
but use mvn package to build a jar, it's build success

**Comment by AlbumenJ** [comment]
```bash
./mvnw -Pnative native:compile -Dmaven.test.skip=true
```
Try use this

**Comment by AlbumenJ** [comment]
```
./mvnw -Pnative native:compile
```
Works fine on my computer.

**Comment by panyox** [comment]
> 

still not working for me, I'll try to upload and compile on a linux server
thank you 🙏

**Comment by yyb1994** [comment]
> > 
> 
> still not working for me, I'll try to upload and compile on a linux server thank you 🙏

I also encountered this error. Have you solved this problem?

**Comment by Nonlone** [comment]
I have some problem，any solution to solve it？

**Comment by Nonlone** [comment]
my  sample address：https://github.com/Nonlone/s2dd/tree/spring3+_native
this project go with SpringBoot3 and Dubbo 3.1.8，But this Dubbo 3.1.8 I have to modify  AbstractAnnotationBeanPostProcessor class, not extend InstantiationAwareBeanPostProcessorAdapter ，implements impSmartInstantiationAwareBeanPostProcessor ;
when I do native compile ,it say error like this
<img width="1442" alt="image" src="https://user-images.githubusercontent.com/5180437/226369138-ac357f2e-64d5-42fb-a251-e439b94c7fc5.png">

**Comment by CrazyHZM** [comment]
@Nonlone 
At present, dubbo has not yet completed the integration with springboot3 in terms of native, but it is already in progress.

**Comment by Nonlone** [comment]
is that possible go with dubbo2？I found that document to show how go with native https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/advanced-features-and-usage/performance/support-graalvm/，is it only for dubbo framework but sb3？

**Comment by CrazyHZM** [comment]
Support native is dubbo3 version, but the configuration method of xml and annotation is not yet supported, they need to be supported after integrating springboot3, and this document needs to be updated, and so on.

**Comment by Nonlone** [comment]
Anything I can help ？

**Comment by AlbumenJ** [comment]
> Anything I can help ？

@CrazyHZM

**Comment by CrazyHZM** [comment]
At present, there are not many native tasks, and the overall plan is still under planning. Welcome to join through https://cn.dubbo.apache.org/zh-cn/contact/. We will release some tasks after the planning is completed. And also create a task issue on github
