### ISSUE TITLE
More information like the address of the server needed on 'zookeeper not connected'.

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo#11057]
```java
        at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.getDynamicConfiguration(DefaultApplicationDeployer.java:720)
        at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.prepareEnvironment(DefaultApplicationDeployer.java:676)
        ... 28 common frames omitted
Caused by: java.lang.IllegalStateException: zookeeper not connected
        at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.<init>(CuratorZookeeperClient.java:105)
        ... 37 common frames omitted

```

**Comment by chickenlj** [comment]
```java
2022-11-30 05:19:07.373 ERROR 8 --- [           main] o.a.d.r.z.c.CuratorZookeeperClient       :  [DUBBO] Failed to connect with zookeeper, dubbo version: 3.1.2, current host: 172.17.0.17, error code: 5-1. This may be caused by Zookeeper server offline, go to https://dubbo.apache.org/faq/5/1 to find instructions. 

java.lang.IllegalStateException: zookeeper not connected
        at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.<init>(CuratorZookeeperClient.java:105)
        at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperTransporter.createZookeeperClient(CuratorZookeeperTransporter.java:26)
        at org.apache.dubbo.remoting.zookeeper.AbstractZookeeperTransporter.connect(AbstractZookeeperTransporter.java:69)
        at org.apache.dubbo.configcenter.support.zookeeper.ZookeeperDynamicConfiguration.<init>(ZookeeperDynamicConfiguration.java:62)
        at org.apache.dubbo.configcenter.support.zookeeper.ZookeeperDynamicConfigurationFactory.createDynamicConfiguration(ZookeeperDynamicConfigurationFactory.java:38)
        at org.apache.dubbo.common.config.configcenter.AbstractDynamicConfigurationFactory.lambd
```

**Comment by Richerlv** [comment]
I want to fix it！
