### ISSUE TITLE
dubbo 2.7.16 NodeExistsException KeeperErrorCode = NodeExists

### ISSUE THREAD

**Issue by itlidaye** [apache/dubbo#11077]
<dubbo.version>2.7.16</dubbo.version>
 <apache.curator.version>4.1.0</apache.curator.version>
<apache.zookeeper.version>3.4.11</apache.zookeeper.version>
<spring-boot.version>2.3.9.RELEASE</spring-boot.version>

WARN     1 [           main] o.a.d.r.z.c.CuratorZookeeperClient       :  [DUBBO] ZNode /dubbo/com。pro.session.service.api.facade.im.Facade/consumers/consumer%3A%2F%2F2.0.0.1%2Fcom.pro.session.service.api.facade.im.ImFacade%3Fapplication%3Dfd-polymeric-msg-service%26category%3Dconsumers%26check%3Dfalse%26dubbo%3D2.0.2%26init%3Dfalse%26interface%3Dcom.pro.session.service.api.facade.im.ImFacade%26metadata-type%3Dremote%26methods%3DqueryConversationList%26pid%3D7720%26qos.enable%3Dfalse%26release%3D2.7.16%26revision%3D2.12.3.1-RELEASE%26shutwait%3D10000%26side%3Dconsumer%26sticky%3Dfalse%26timeout%3D1000%26timestamp%3D1670291604237%26version%3D1.0.0 already exists, since we will only try to recreate a node on a session expiration, this duplication might be caused by a delete delay from the zk server, which means the old expired session may still holds this ZNode and the server just hasn't got time to do the deletion. In this case, we can just try to delete and create again., dubbo version: 2.7.16, current host: 2.0.0.1
org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /dubbo/com.pro.session.service.api.facade.im.ImFacade/consumers/consumer%3A%2F%2F2.0.0.1%2Fcom.pro.session.service.api.facade.im.ImFacade%3Fapplication%3Dfd-polymeric-msg-service%26category%3Dconsumers%26check%3Dfalse%26dubbo%3D2.0.2%26init%3Dfalse%26interface%3Dcom.pro.session.service.api.facade.im.ImFacade%26metadata-type%3Dremote%26methods%3DqueryConversationList%26pid%3D7720%26qos.enable%3Dfalse%26release%3D2.7.16%26revision%3D2.12.3.1-RELEASE%26shutwait%3D10000%26side%3Dconsumer%26sticky%3Dfalse%26timeout%3D1000%26timestamp%3D1670291604237%26version%3D1.0.0
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:119) ~[zookeeper-3.4.7.jar:3.4.7-1713338]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[zookeeper-3.4.7.jar:3.4.7-1713338]
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783) ~[zookeeper-3.4.7.jar:3.4.7-1713338]
	at org.apache.curator.framework.imps.CreateBuilderImpl$17.call(CreateBuilderImpl.java:1179) ~[curator-framework-4.1.0.jar:4.1.0]
	at org.apache.curator.framework.imps.CreateBuilderImpl$17.call(CreateBuilderImpl.java:1160) ~[curator-framework-4.1.0.jar:4.1.0]
	at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:64) ~[curator-client-4.1.0.jar:?]
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100) ~[curator-client-4.1.0.jar:?]
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:1157) ~[curator-framework-4.1.0.jar:4.1.0]
	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:607) ~[curator-framework-4.1.0.jar:4.1.0]
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:597) ~[curator-framework-4.1.0.jar:4.1.0]
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:575) ~[curator-framework-4.1.0.jar:4.1.0]
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:49) ~[curator-framework-4.1.0.jar:4.1.0]
	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.createEphemeral(CuratorZookeeperClient.java:105) ~[dubbo-2.7.16.jar:2.7.16]
	at org.apache.dubbo.remoting.zookeeper.AbstractZookeeperClient.create(AbstractZookeeperClient.java:83) ~[dubbo-2.7.16.jar:2.7.16]
	at org.apache.dubbo.registry.zookeeper.ZookeeperRegistry.doRegister(ZookeeperRegistry.java:125) ~[dubbo-2.7.16.jar:2.7.16]
	at org.apache.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:206) ~[dubbo-2.7.16.jar:2.7.16]
	at org.apache.dubbo.registry.ListenerRegistryWrapper.register(ListenerRegistryWrapper.java:57) ~[dubbo-2.7.16.jar:2.7.16]
	at org.apache.dubbo.registry.integration.RegistryProtocol.doCreateInvoker(RegistryProtocol.java:524) ~[dubbo-2.7.16.jar:2.7.16]
	at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getInvoker(InterfaceCompatibleRegistryProtocol.java:63) ~[dubbo-2.7.16.jar:2.7.16]
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshInterfaceInvoker(MigrationInvoker.java:333) ~[dubbo-2.7.16.jar:2.7.16]
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.fallbackToInterfaceInvoker(MigrationInvoker.java:158) ~[dubbo-2.7.16.jar:2.7.16]
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:65) ~[dubbo-2.7.16.jar:2.7.16]
	at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:103) ~[dubbo-2.7.16.jar:2.7.16]
	at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:500) ~[dubbo-2.7.16.jar:2.7.16]
	at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:485) ~[dubbo-2.7.16.jar:2.7.16]
	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:479) ~[dubbo-2.7.16.jar:2.7.16]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:72) ~[dubbo-2.7.16.jar:2.7.16]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:81) ~[dubbo-2.7.16.jar:2.7.16]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:73) ~[dubbo-2.7.16.jar:2.7.16]
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java) ~[dubbo-2.7.16.jar:2.7.16]
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:385) ~[dubbo-2.7.16.jar:2.7.16]
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:313) ~[dubbo-2.7.16.jar:2.7.16]
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:206) ~[dubbo-2.7.16.jar:2.7.16]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.doGetInjectedBean(ReferenceAnnotationBeanPostProcessor.java:165) ~[dubbo-2.7.16.jar:2.7.16]
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.getInjectedObject(AbstractAnnotationBeanPostProcessor.java:409) ~[spring-context-support-1.0.11.jar:?]
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor$AnnotatedFieldElement.inject(AbstractAnnotationBeanPostProcessor.java:626) ~[spring-context-support-1.0.11.jar:?]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.postProcessPropertyValues(AbstractAnnotationBeanPostProcessor.java:179) ~[spring-context-support-1.0.11.jar:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1430) ~[spring-beans-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) [spring-beans-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) [spring-beans-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) [spring-beans-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) [spring-beans-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) [spring-context-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) [spring-context-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.3.9.RELEASE.jar:2.3.9.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.9.RELEASE.jar:2.3.9.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405) [spring-boot-2.3.9.RELEASE.jar:2.3.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.9.RELEASE.jar:2.3.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.9.RELEASE.jar:2.3.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.9.RELEASE.jar:2.3.9.RELEASE]
	at com.fd.polymeric.Application.main(Application.java:31) [classes/:?]

**Comment by itlidaye** [comment]
> 将在本月发布的 3.1.4 版本中修复。

2.1.x Will it be fixed?

**Comment by AlbumenJ** [comment]
> > 将在本月发布的 3.1.4 版本中修复。
> 
> 2.1.x Will it be fixed?

only fix in 3.1.x and 3.2.x

**Comment by xusheng1987** [comment]
希望在2.7版本也修复下

**Comment by AlbumenJ** [comment]
> 希望在2.7版本也修复下

Dubbo 2.7 is only for security maintain now, and will EOL in 2022.3.

**Comment by AlbumenJ** [comment]
> > 希望在2.7版本也修复下
> 
> Dubbo 2.7 is only for security maintain now, and will EOL in 2022.3.

https://cn.dubbo.apache.org/zh/blog/2022/12/05/%E8%81%9A%E7%84%A6%E7%A8%B3%E5%AE%9A%E6%80%A7dubbo-%E5%8F%91%E7%89%88%E8%A7%84%E5%88%92%E5%85%AC%E5%B8%83/
