### ISSUE TITLE
Failed to start when metadata-report.cycle-report=false is set

### ISSUE THREAD

**Issue by wxbty** [apache/dubbo#11096]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.7+，3.1.0+，3.2.0+
* Operating System version: mac
* Java version: 1.8

### Steps to reproduce this issue

1. The provider and consumer demo use the project of
https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-spring-boot

```java
@SpringBootApplication
@EnableDubbo
public class ProviderApplication {
    public static void main(String[] args) {

        SpringApplication.run(ProviderApplication.class, args);
        System.out.println("dubbo service started");
    }
}
```
2. application.yml setting

```yaml
dubbo:
  metadata-report:
    cycle-report: false
```
3. run main function

### Expected Behavior

Normal start

### Actual Behavior

report error
```txt
2022-12-08 17:56:28.487 ERROR 9666 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalArgumentException: Please specify valid protocol or address for metadata report null
	at org.apache.dubbo.config.utils.ConfigValidationUtils.validateMetadataConfig(ConfigValidationUtils.java:510) ~[dubbo-3.0.13-SNAPSHOT.jar:3.0.13-SNAPSHOT]
	at org.apache.dubbo.config.utils.DefaultConfigValidator.validate(DefaultConfigValidator.java:41) ~[dubbo-3.0.13-SNAPSHOT.jar:3.0.13-SNAPSHOT]
	at org.apache.dubbo.config.context.AbstractConfigManager.checkDefaultAndValidateConfigs(AbstractConfigManager.java:586) ~[dubbo-3.0.13-SNAPSHOT.jar:3.0.13-SNAPSHOT]
	at org.apache.dubbo.config.context.ConfigManager.checkConfigs(ConfigManager.java:281) ~[dubbo-3.0.13-SNAPSHOT.jar:3.0.13-SNAPSHOT]
```

**Comment by AlbumenJ** [comment]
metadata-report.report-definition can disable report

**Comment by AlbumenJ** [comment]
![image](https://user-images.githubusercontent.com/9292748/206665698-6e9ca313-f7e6-4a77-ae40-6795ee0af30a.png)
