### ISSUE TITLE
java.lang.RuntimeException: Can not create registry service-discovery-registry://xxx.xxx.xxx.xxx:2181/,服务启动报这个错

### ISSUE THREAD

**Issue by lamb007** [apache/dubbo#11128]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
使用zookeeper作为注册中心，由于仅仅用作测试，仅使用单机，未做zookeeper集群

在我的电脑上能够正常启动provider和consumer相应的服务
但在另一台电脑上，clone与我完全相同的代码后，却无法启动服务

这是异常信息：
```
java.lang.RuntimeException: Can not create registry service-discovery-registry://xxx.xxx.xxx.xxx:2181/org.apache.dubbo.registry.RegistryService?application=user-provider&dubbo=2.0.2&interface=org.apache.dubbo.registry.RegistryService&pid=8312&qos.enable=false&registry=zookeeper&release=3.0.7
	.................................堆栈信息省略
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-2.6.11.jar:2.6.11]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) [spring-boot-2.6.11.jar:2.6.11]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) [spring-boot-2.6.11.jar:2.6.11]
	at com.qgexam.user.UserProviderApplication.main(UserProviderApplication.java:13) [classes/:na]
```

```
Caused by: java.lang.IllegalStateException: Create zookeeper service discovery failed.
	.....................................堆栈信息省略
	... 35 common frames omitted

Caused by: java.lang.IllegalStateException: failed to connect to zookeeper server
	at org.apache.dubbo.registry.zookeeper.util.CuratorFrameworkUtils.buildCuratorFramework(CuratorFrameworkUtils.java:75) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.registry.zookeeper.ZookeeperServiceDiscovery.<init>(ZookeeperServiceDiscovery.java:72) ~[dubbo-3.0.7.jar:3.0.7]
	... 44 common frames omitted
```

这是zookeeper的日志信息：
```
2022-12-13 23:43:35,391 [myid:] - WARN  [NIOWorkerThread-4:NIOServerCnxn@373] - Close of session 0x10000066bbf003b
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:378)
        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:324)
        at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
        at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```

因为代码在我的电脑上能够正常运行，所以我猜测是不是是zookeeper配置的问题？
这是我的zookeeper配置文件的主要内容
```
initLimit=10

syncLimit=5

dataDir=/root/soft/zookeeper/apache-zookeeper-3.6.1-bin/data
logDir=/root/soft/zookeeper/apache-zookeeper-3.6.1-bin/logs

clientPort=2181

maxClientCnxns=0
```

这个问题已经困扰了我一天，如果能够得到一些有用的建议，我将万分感激，感谢您能在百忙之中抽出的时间

**Comment by AlbumenJ** [comment]
看一下是不是本地开启了网络代理的组件

**Comment by lamb007** [comment]
感谢你的帮助。
我遇到了一个新问题
dubbo版本：2.7.3
在springboot中配置多注册中心：
`dubbo:
  application:
    name: user-provider
  protocol:
    name: dubbo
    # 协议端口
    port: 20880
  provider:
    filter: -exception
  registries:
    beijingRegistry: # 注册中心名称
      address: zookeeper://xxx.xxx.xxx.xxx:2181
      register: true`

启动springboot服务时失败：
`Description:

Configuration property name 'dubbo.registries.beijingRegistry' is not valid:

    Invalid characters: 'R'
    Bean: beijingRegistry
    Reason: Canonical names should be kebab-case ('-' separated), lowercase alpha-numeric characters and must start with a letter

Action:

Modify 'dubbo.registries.beijingRegistry' so that it conforms to the canonical names requirements.`

修改为beijing-registry后仍然失败：
`Description:

A component required a bean named 'registryDefault' that could not be found.


Action:

Consider defining a bean named 'registryDefault' in your configuration.`
请问如何在2.7.3中通过application.yml配置dubbo

**Comment by lihuagang03** [comment]
`dubbo-3.3.1`报错如下，ZooKeeper-server 版本较低，客户端只能使用 `zookeeper-3.4.14`。
若使用`dubbo-3.2.16`和`JDK-8`，运行正常。

`OpenJDK-21`

zookeeper.version=3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf

2024-10-25 17:51:24,920 [WARN] [TID: N/A] [] org.apache.zookeeper.ClientCnxn Session 0x0 for server 172.16.150.60/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect
java.lang.IllegalArgumentException: Unable to canonicalize address 172.16.150.60/<unresolved>:2181 because it's not resolvable

2024-10-25 17:51:24,951 [ERROR] [TID: N/A] [] o.a.d.c.d.DefaultModuleDeployer  [DUBBO] Model start failed: Dubbo Module[1.1.1] start failed: java.lang.RuntimeException: Can not create registry service-discovery-registry://172.16.150.60:2181/org.apache.dubbo.registry.RegistryService?REGISTRY_CLUSTER=default&application=lefit-gateway-admin&check.serializable=false&dubbo=2.0.2&executor-management-mode=isolation&file-cache=true&interface=org.apache.dubbo.registry.RegistryService&logger=slf4j&metadata-service-protocol=dubbo&owner=lefit&pid=21301&qos.port=22222&register=false&registry=zookeeper&release=3.3.1&serialize.check.status=DISABLE, dubbo version: 3.3.1, current host: 172.16.22.50, error code: 5-14. This may be caused by , go to https://dubbo.apache.org/faq/5/14 to find instructions. 
java.lang.RuntimeException: Can not create registry service-discovery-registry://172.16.150.60:2181/org.apache.dubbo.registry.RegistryService?REGISTRY_CLUSTER=default&application=lefit-gateway-admin&check.serializable=false&dubbo=2.0.2&executor-management-mode=isolation&file-cache=true&interface=org.apache.dubbo.registry.RegistryService&logger=slf4j&metadata-service-protocol=dubbo&owner=lefit&pid=21301&qos.port=22222&register=false&registry=zookeeper&release=3.3.1&serialize.check.status=DISABLE

使用ZK本地地址，也不行。(`dubbo.registry.address=zookeeper://localhost:2181`)
没有开启任何代理

org.apache.zookeeper.ClientCnxn Session 0x0 for server localhost/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect
java.lang.IllegalArgumentException: Unable to canonicalize address localhost/<unresolved>:2181 because it's not resolvable
