### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.zookeeper.server.quorum.flexible.QuorumMaj.<init>(Ljava/util/Map;)V

### ISSUE THREAD

**Issue by dousp** [apache/dubbo#11156]
# How to solve this problem, tried for a long time no idea

- In the case of copying the official website, only spring boot uses 2.4
- https://github.com/apache/dubbo-samples/tree/master/1-basic/dubbo-samples-spring-boot

```
java.lang.NoSuchMethodError: org.apache.zookeeper.server.quorum.flexible.QuorumMaj.<init>(Ljava/util/Map;)V
	at org.apache.curator.framework.imps.EnsembleTracker.<init>(EnsembleTracker.java:57)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.<init>(CuratorFrameworkImpl.java:156)
	at org.apache.curator.framework.CuratorFrameworkFactory$Builder.build(CuratorFrameworkFactory.java:161)
	at org.apache.dubbo.remoting.zookeeper.curator5.Curator5ZookeeperClient.<init>(Curator5ZookeeperClient.java:79)
        ...
```

**Comment by AlbumenJ** [comment]
Have you change the dependency of zookeeper? The message shows that you are using curator5 but zookeeper is 3.4.x.

**Comment by dousp** [comment]
dubbo old version is 2.5.3.
now:
```
<dubbo.version>3.0.12</dubbo.version>
<spring.boot.version>2.4.13</spring.boot.version>

<dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo-bom</artifactId>
                <version>${dubbo.version}</version>
                <type>pom</type>
                <scope>import</scope>
</dependency>
 <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo-dependencies-zookeeper</artifactId>
                <version>${dubbo.version}</version>
                <type>pom</type>
</dependency>

<dependency>
       <groupId>org.apache.dubbo</groupId>
       <artifactId>dubbo</artifactId>
</dependency>
<dependency>
      <groupId>org.apache.dubbo</groupId>
      <artifactId>dubbo-dependencies-zookeeper</artifactId>
      <type>pom</type>
</dependency>
```
zookeeper version is 3.4.14

**Comment by dousp** [comment]
i found version in dubbo-dependencies-zookeeper:
```
<zookeeper_version>3.4.14</zookeeper_version>
<curator_version>4.2.0</curator_version>
```
But after actually referencing, curator_versio in the project is 5.1.0.
after modification：
```
<!-- <dependency> -->
        <!--     <groupId>org.apache.dubbo</groupId> -->
        <!--     <artifactId>dubbo-dependencies-zookeeper</artifactId> -->
        <!--     <type>pom</type> -->
        <!--     <exclusions> -->
        <!--         <exclusion> -->
        <!--             <groupId>org.apache.zookeeper</groupId> -->
        <!--             <artifactId>zookeeper</artifactId> -->
        <!--         </exclusion> -->
        <!--     </exclusions> -->
        <!-- </dependency> -->

        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-x-discovery</artifactId>
            <version>4.2.0</version>
        </dependency>
        <!-- <dependency> -->
        <!--     <groupId>org.apache.curator</groupId> -->
        <!--     <artifactId>curator-client</artifactId> -->
        <!--     <version>4.2.0</version> -->
        <!-- </dependency> -->
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-framework</artifactId>
            <version>4.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-recipes</artifactId>
            <version>4.2.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.zookeeper</groupId>
                    <artifactId>zookeeper</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.zookeeper</groupId>
            <artifactId>zookeeper</artifactId>
            <version>3.4.14</version>
        </dependency>
```
The project is finally ready to run。。。。

**Comment by dousp** [comment]
this should be useful
[https://curator.apache.org/zk-compatibility-34.html](url)
