### ISSUE TITLE
Can you set ConfigValidationUtils.MAX_LEGTH longer

### ISSUE THREAD

**Issue by XDanwar** [apache/dubbo#11169]
Exception in thread "thread-finconfig-firstLoad-pool-0" java.lang.IllegalStateException: Invalid file="-authorityFilter,-catconsumerfilter,-catproviderfilter,-dashboardFilter,-fintech_monitor,-fqtracerconsumer,-fqtracerprovider,-frameworkAttachmentCleConfigValidationUtilsanFilter,-ft_monitor,-ft_tracer_consumer,-ft_tracer_provider,-grpcFilter,-healthcheckfilter,-hystrixconsumerfilter,-ratelimiterfilter,-serviceinfofilter,-strace_log_monitor,-tr_monitor,-tracecontextfilter,-ucsProviderFilter" is longer than 200
	at org.apache.dubbo.config.utils.ConfigValidationUtils.checkProperty(ConfigValidationUtils.java:583)
	at org.apache.dubbo.config.utils.ConfigValidationUtils.checkMultiName(ConfigValidationUtils.java:558)
	at org.apache.dubbo.config.utils.ConfigValidationUtils.checkMultiExtension(ConfigValidationUtils.java:520)
	at org.apache.dubbo.config.utils.ConfigValidationUtils.validateAbstractInterfaceConfig(ConfigValidationUtils.java:298)
	at org.apache.dubbo.config.utils.ConfigValidationUtils.validateReferenceConfig(ConfigValidationUtils.java:344)
	at org.apache.dubbo.config.ReferenceConfig.checkAndUpdateSubConfigs(ReferenceConfig.java:420)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:193)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:158)

**Comment by XDanwar** [comment]
case :  The custom filter will be called circularly. The referer parameter can be used to destroy the closed loop, for example, to exclude some filters, but it may exceed the parameter length limit（ConfigValidationUtils.MAX_LEGTH）

**Comment by XDanwar** [comment]
it is not easy to determine the proper length

**Comment by XDanwar** [comment]
Is it more reasonable for filter SPI strength exclusion to provide a prefix matching parameter, for example, according to the package name, other scenarios are similar

**Comment by AlbumenJ** [comment]
> Is it more reasonable for filter SPI strength exclusion to provide a prefix matching parameter, for example, according to the package name, other scenarios are similar

Sounds good. But can we figure out all the cases?

**Comment by XDanwar** [comment]
> > Is it more reasonable for filter SPI strength exclusion to provide a prefix matching parameter, for example, according to the package name, other scenarios are similar
> 
> Sounds good. But can we figure out all the cases?

Well, yes, I feel that we can't take all the scenarios into consideration. However, it seems that there may be a large demand for customization of cluster and filter layer. Can we start with these two?

**Comment by AlbumenJ** [comment]
> > > Is it more reasonable for filter SPI strength exclusion to provide a prefix matching parameter, for example, according to the package name, other scenarios are similar
> > 
> > 
> > Sounds good. But can we figure out all the cases?
> 
> Well, yes, I feel that we can't take all the scenarios into consideration. However, it seems that there may be a large demand for customization of cluster and filter layer. Can we start with these two?

Sure
