### ISSUE TITLE
NullpointExceptioin after upgrade dubbo from 2.7.7 to 2.7.18 

### ISSUE THREAD

**Issue by luluback** [apache/dubbo#11190]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.18
* Operating System version: mac 11.2.3
* Java version: 1.8

### Steps to reproduce this issue

refrence a remote service interface by java config

    @Bean
    public ReferenceBean<UserRoleRpcService> userRoleService() {
        ReferenceBean<UserRoleRpcService> referenceBean = new ReferenceBean();
        referenceBean.setConsumer(consumerConfig);
        referenceBean.setInterface(UserRoleRpcService.class);
        referenceBean.setCheck(false);
        return referenceBean;
    }

then, get NullPointException where RefrenceConfig init, like below :

Caused by: java.lang.NullPointerException
	at org.apache.dubbo.config.utils.ConfigValidationUtils.validateRegistryConfig(ConfigValidationUtils.java:519)
	at org.apache.dubbo.config.utils.ConfigValidationUtils.validateReferenceConfig(ConfigValidationUtils.java:397)
	at org.apache.dubbo.config.ReferenceConfig.checkAndUpdateSubConfigs(ReferenceConfig.java:483)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:247)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:206)
	at org.apache.dubbo.config.spring.ReferenceBean.getObject(ReferenceBean.java:68)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:171)

get into the source code ,must the RegistryConfig is null,

    public static void validateRegistryConfig(RegistryConfig config) {
        checkName(PROTOCOL_KEY, config.getProtocol());
        checkName(USERNAME_KEY, config.getUsername());
        checkLength(PASSWORD_KEY, config.getPassword());
        checkPathLength(FILE_KEY, config.getFile());
        checkName(TRANSPORTER_KEY, config.getTransporter());
        checkName(SERVER_KEY, config.getServer());
        checkName(CLIENT_KEY, config.getClient());
        checkParameterName(config.getParameters());
    }

**Comment by AlbumenJ** [comment]
Try use ReferenceConfig or upgrade to 3.1.4 (2.7.x is no longer bugfix maintain now).
