### ISSUE TITLE
3.1.4使用triple协议时，当provider抛出异常，consumer报npe

### ISSUE THREAD

**Issue by isharpever** [apache/dubbo#11270]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.4
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue

1. provider实现类抛出异常
```
@DubboService
public class DemoProviderImpl implements DemoProvider {
    @Override
    public String sayHello(String name) {
//        return "hello," + name;
        throw new RuntimeException("error");
    }
}
```
2. consumer发起同步调用

Pls. provide [GitHub address] to reproduce this issue.
查看源码发现，在处理[#11075](https://github.com/apache/dubbo/issues/11075)时，在`org.apache.dubbo.rpc.protocol.tri.TripleHeaderEnum`增加了如下代码：
```
static {
    ...

    for (Http2Headers.PseudoHeaderName value : Http2Headers.PseudoHeaderName.values()) {
        excludeAttachmentsSet.add(value.value().toString());
    }
}
```
导致`org.apache.dubbo.rpc.protocol.tri.transport.AbstractH2TransportListener#filterReservedHeaders`里面，
如果第1段if为true，第2段if一定也是true，进而npe。
```
protected Map<String, String> filterReservedHeaders(Http2Headers trailers) {
    ...

    for (Map.Entry<CharSequence, CharSequence> header : trailers) {
        String key = header.getKey().toString();
        if (Http2Headers.PseudoHeaderName.isPseudoHeader(key)) {     // 1
            excludeHeaders.put(key, trailers.getAndRemove(key).toString());
        }
        if (TripleHeaderEnum.containsExcludeAttachments(key)) {   // 若1为true，这里一定也是true
            excludeHeaders.put(key, trailers.getAndRemove(key).toString());  // 第1段if已移除此key, 故npe
        }
    }
    return excludeHeaders;
}
```

### Expected Behavior

consumer不报npe，provider抛异常后立即调用失败。

### Actual Behavior

consumer先报npe，之后一直阻塞至超时。

If there is an exception, please attach the exception trace:

```
2023-01-10 16:22:29.795 ERROR 41760 --- [483647-thread-1] o.a.d.c.t.serial.SerializingExecutor     :  [DUBBO] Exception while executing runnable org.apache.dubbo.rpc.protocol.tri.stream.TripleClientStream$ClientTransportListener$$Lambda$984/0x000000080088a440@24856f9f, dubbo version: 3.1.4, current host: 10.128.100.158, error code: 0-19. This may be caused by , go to https://dubbo.apache.org/faq/0/19 to find instructions. 

java.lang.NullPointerException: null
	at org.apache.dubbo.rpc.protocol.tri.transport.AbstractH2TransportListener.filterReservedHeaders(AbstractH2TransportListener.java:80) ~[dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.rpc.protocol.tri.stream.TripleClientStream$ClientTransportListener.finishProcess(TripleClientStream.java:197) ~[dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.rpc.protocol.tri.stream.TripleClientStream$ClientTransportListener.onTrailersReceived(TripleClientStream.java:299) ~[dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.rpc.protocol.tri.stream.TripleClientStream$ClientTransportListener.lambda$onHeader$1(TripleClientStream.java:344) ~[dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.common.threadpool.serial.SerializingExecutor.run(SerializingExecutor.java:102) ~[dubbo-3.1.4.jar:3.1.4]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41) ~[dubbo-3.1.4.jar:3.1.4]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2023-01-10 16:22:36.091  WARN 41760 --- [nio-8082-exec-2] o.a.d.r.proxy.InvokerInvocationHandler   :  [DUBBO] [Dubbo-Consumer] execute service org.example.DemoProvider#sayHello cost 11036.024000 ms, this invocation almost (maybe already) timeout. Timeout: 3000ms
invocation context:
remote.application=dubbo-consumer;
consumer-application=dubbo-consumer;
interface=org.example.DemoProvider;
request-id=pZi84XouABHiIUja;
request-token=oewiroewfddsfs;
timeout=3000;
thread info: 
Start time: 787862353572000
+-[ Offset: 0.000000ms; Usage: 11036.024000ms, 100% ] Receive request. Client invoke begin. ServiceKey: org.example.DemoProvider MethodName:sayHello
  +-[ Offset: 117.749500ms; Usage: 10918.016900ms, 98% ] Invoker invoke. Target Address: 10.128.100.158:50051, dubbo version: 3.1.4, current host: 10.128.100.158, error code: 3-4. This may be caused by , go to https://dubbo.apache.org/faq/3/4 to find instructions. 
2023-01-10 16:22:36.095 ERROR 41760 --- [nio-8082-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.apache.dubbo.rpc.StatusRpcException: DEADLINE_EXCEEDED : Waiting server-side response timeout by scan timer. start time: 2023-01-10 16:22:28.456, end time: 2023-01-10 16:22:36.088, timeout: 3000 ms, service: org.example.DemoProvider, method: sayHello] with root cause

org.apache.dubbo.rpc.StatusRpcException: DEADLINE_EXCEEDED : Waiting server-side response timeout by scan timer. start time: 2023-01-10 16:22:28.456, end time: 2023-01-10 16:22:36.088, timeout: 3000 ms, service: org.example.DemoProvider, method: sayHello
	at org.apache.dubbo.rpc.TriRpcStatus.asException(TriRpcStatus.java:214) ~[dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.rpc.protocol.tri.DeadlineFuture$TimeoutCheckTask.notifyTimeout(DeadlineFuture.java:183) ~[dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.rpc.protocol.tri.DeadlineFuture$TimeoutCheckTask.lambda$run$0(DeadlineFuture.java:169) ~[dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor$RunnableWrapper.run(ThreadlessExecutor.java:184) ~[dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:103) ~[dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:194) ~[dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:265) ~[dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:186) ~[dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:71) ~[dubbo-3.1.4.jar:3.1.4]
```

**Comment by EarthChen** [comment]
fix by https://github.com/apache/dubbo/pull/11214/files
