### ISSUE TITLE
java.lang.NoSuchFieldError: addr

### ISSUE THREAD

**Issue by fffguo** [apache/dubbo#11428]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.0-beta.4
* Operating System version: mac 13.1
* Java version: jdk17

### Steps to reproduce this issue

java.lang.NoSuchFieldError: addr
	at org.apache.curator.framework.imps.EnsembleTracker.configToConnectionString(EnsembleTracker.java:185) ~[curator-framework-4.3.0.jar:4.3.0]
	at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:206) ~[curator-framework-4.3.0.jar:4.3.0]
	at org.apache.curator.framework.imps.EnsembleTracker.access$300(EnsembleTracker.java:50) ~[curator-framework-4.3.0.jar:4.3.0]
	at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:150) ~[curator-framework-4.3.0.jar:4.3.0]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:883) ~[curator-framework-4.3.0.jar:4.3.0]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:653) ~[curator-framework-4.3.0.jar:4.3.0]
	at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152) ~[curator-framework-4.3.0.jar:4.3.0]
	at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:222) ~[curator-framework-4.3.0.jar:4.3.0]
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:636) ~[zookeeper-3.7.0.jar:3.7.0]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:555) ~[zookeeper-3.7.0.jar:3.7.0]
Pls. provide [GitHub address] to reproduce this issue.

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/27751972/215922293-bfe014f3-76d2-4d89-b53c-2b757f6b5648.png">

**MultipleAddresses does not contain  getAddress()**

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by fffguo** [comment]
我临时升级了版本，暂时解决了问题，
但是这个版本号是 3.2.0-beta.4
应该在 3.2.0-beta.4 上同步升级才对


        <dependency>
            <groupId>org.apache.zookeeper</groupId>
            <artifactId>zookeeper</artifactId>
            <version>3.8.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-framework</artifactId>
            <version>5.4.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-recipes</artifactId>
            <version>5.4.0</version>
        </dependency>

**Comment by AlbumenJ** [comment]
> 应该在 3.2.0-beta.4 上同步升级才对

Dubbo 不会传递 zookeeper / curator 的依赖，这个是用户自己选择的。目前 curator 4.x / 5.x 和 zookeeper > 3.4.x 都是全系列支持的。

**Comment by fffguo** [comment]
> > 应该在 3.2.0-beta.4 上同步升级才对
> 
> Dubbo 不会传递 zookeeper / curator 的依赖，这个是用户自己选择的。目前 curator 4.x / 5.x 和 zookeeper > 3.4.x 都是全系列支持的。


**是我描述的有问题，是该项目所依赖的curator是4.3.0版本：dubbo-dependencies-zookeeper-curator5   3.2.0-beta.4**

<img width="1375" alt="image" src="https://user-images.githubusercontent.com/27751972/216537770-de18fbe0-be77-4e1c-92df-ec9be88bb224.png">

**Comment by fffguo** [comment]
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/27751972/216538519-40fd2527-dddb-4c0e-9246-e44144f0162a.png">

**Comment by AlbumenJ** [comment]
curator 4.3.0 应该是可以用的，主要是 zookeeper 的版本

**Comment by fffguo** [comment]
<img width="1891" alt="image" src="https://user-images.githubusercontent.com/27751972/216539125-5f2040ad-518c-4d02-9fdd-3baf036f2814.png">

我找到了变更记录，从5.1.0 降级到4.3.0了，同时dubbo-dependencies-zookeeper-curator 也从4.2.0 升级到 4.3.0 

看起来像是为了升级 4.2.0 到 4.3.0 ，而误操作，给降级了

**Comment by fffguo** [comment]
dubbo-dependencies-zookeeper-curator5。不是为了适应高版本zookeeper而做的依赖吗？我使用的就是zookeeper较高版本，因此依赖的是 dubbo-dependencies-zookeeper-curator5  而不是 dubbo-dependencies-zookeeper-curator

**Comment by AlbumenJ** [comment]
> dubbo-dependencies-zookeeper-curator5。不是为了适应高版本zookeeper而做的依赖吗？我使用的就是zookeeper较高版本，因此依赖的是 dubbo-dependencies-zookeeper-curator5 而不是 dubbo-dependencies-zookeeper-curator

看了下应该是 dependentbot 升级 curator 依赖的时候错误升级了 curator5 模块的导致的

**Comment by AlbumenJ** [comment]
Will be fixed in https://github.com/apache/dubbo/pull/11492

**Comment by fffguo** [comment]
thank you
