### ISSUE TITLE
调用dubbo接口时如果参数为null则抛出异常调用失败

### ISSUE THREAD

**Issue by ymlisoft** [apache/dubbo#11567]
### Environment

* Dubbo version: 3.1.6
* Operating System version: win10
* Java version: 11

### Steps to reproduce this issue

1. 调用dubbo接口时如果参数为null，则抛出NPE异常，调用失败

```
Service service = consumerManager.getReference(Service.class);
DubboResp dubboResp = service.call(argu1, argu2);
```

如argu1或argu2为null，则抛出异常

org.apache.dubbo.rpc.protocol.tri.ReflectionPackableMethod$WrapRequestPack

![1111](https://user-images.githubusercontent.com/9900158/218735459-8535c6d2-2ff1-4acc-8b15-93a456d2a48c.png)

**Comment by AlbumenJ** [comment]
@EarthChen

**Comment by wangtu** [comment]
v3.1.7 The test problem still exists

**Comment by ilaotan** [comment]
Caused by: java.lang.NullPointerException: null
	at org.apache.dubbo.rpc.protocol.tri.ReflectionPackableMethod$WrapRequestPack.pack(ReflectionPackableMethod.java:393)
	at org.apache.dubbo.rpc.model.PackableMethod.packRequest(PackableMethod.java:58)
	at org.apache.dubbo.rpc.protocol.tri.call.TripleClientCall.sendMessage(TripleClientCall.java:157)

**Comment by pipipapi** [comment]
![图片](https://user-images.githubusercontent.com/29531009/220975146-75bead57-eed6-4cd7-82e3-e41b6aad2dab.png)
CLIENT_STREAM， BI_STREAM这俩rpc方式都用返回类型class赋值？
然后SERVER_STREAM用入参第一个参数类型赋值？
