### ISSUE TITLE
Can not initialized dubbo as a plugin in JetBrains IntelliJ IDEA

### ISSUE THREAD

**Issue by jjwwhmm** [apache/dubbo#11570]
Environment:
    Dubbo version: 2.7.8
    InteliJ IDEA: Ultimate 2020.3
    Operating System version: mac Ventura 13.0
    Java version: openjdk version "1.8.0_292"

The same code could be initialized without plugin support. for example run as a junit test.
But run as a plugin in JetBrains InteliJ IDEA, it throws the following exceptions:
java.lang.ExceptionInInitializerError
	at demo.InvokeDubboServiceJob.call(InvokeDubboServiceJob.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Failed to create adaptive instance: java.lang.IllegalStateException: Can't create adaptive extension interface org.apache.dubbo.common.extension.ExtensionFactory, cause: No adaptive method exist on extension org.apache.dubbo.common.extension.ExtensionFactory, refuse to create the adaptive class!
	at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtension(ExtensionLoader.java:592)
	at org.apache.dubbo.common.extension.ExtensionLoader.<init>(ExtensionLoader.java:145)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtensionLoader(ExtensionLoader.java:167)
	at org.apache.dubbo.config.ReferenceConfig.<clinit>(ReferenceConfig.java:111)
	... 19 more
Caused by: java.lang.IllegalStateException: Can't create adaptive extension interface org.apache.dubbo.common.extension.ExtensionFactory, cause: No adaptive method exist on extension org.apache.dubbo.common.extension.ExtensionFactory, refuse to create the adaptive class!
	at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtension(ExtensionLoader.java:1021)
	at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtension(ExtensionLoader.java:588)
	... 22 more
Caused by: java.lang.IllegalStateException: No adaptive method exist on extension org.apache.dubbo.common.extension.ExtensionFactory, refuse to create the adaptive class!
	at org.apache.dubbo.common.extension.AdaptiveClassCodeGenerator.generate(AdaptiveClassCodeGenerator.java:92)
	at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtensionClass(ExtensionLoader.java:1034)
	at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtensionClass(ExtensionLoader.java:1030)
	at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtension(ExtensionLoader.java:1019)
	... 23 more

build.gradle:
    implementation 'org.apache.dubbo:dubbo:2.7.8'
    implementation 'org.apache.dubbo:dubbo-configcenter-nacos:2.7.8'
    implementation 'org.apache.dubbo:dubbo-registry-nacos:2.7.8'
    implementation 'org.apache.dubbo:dubbo-serialization-fastjson:2.7.8'

code at line 66:
          RegistryConfig registryConfig = new RegistryConfig();
          ......
          ReferenceConfig reference = new ReferenceConfig();
          ......
    64:String address = "ip:port"
    65:ReferenceConfigCache cache = ReferenceConfigCache.getCache(address);
    66:GenericService genericService = (GenericService) cache.get(reference);

Because of the SPI, so I printed the classloader by the snippet code:
        ClassLoader currClassLoader = Thread.currentThread().getContextClassLoader();
        ClassLoader cl = currClassLoader;
        while(true) {
            System.out.println("classloader:" + cl.toString());
            cl = cl.getParent();
            if(null == cl) {
                break;
            }
        }

In JUnit test the classsloaders:
     classloader:sun.misc.Launcher$AppClassLoader@18b4aac2
     classloader:sun.misc.Launcher$ExtClassLoader@66133adc
and, in plugin the classloaders:
    classloader:com.intellij.util.lang.UrlClassLoader@1c72da34 
    classloader:jdk.internal.loader.ClassLoaders$PlatformClassLoader@5ca4f1cb 

Is there any suggestions? thanks a lot.

**Comment by AlbumenJ** [comment]
`Caused by: java.lang.IllegalStateException: No adaptive method exist on extension org.apache.dubbo.common.extension.ExtensionFactory, refuse to create the adaptive class!` may cause by resource load failed.

**Comment by AlbumenJ** [comment]
You can check if the resource file in `resources/META-INF/dubbo/internal/org.apache.dubbo.common.extension.ExtensionInjector` load proper.
