### ISSUE TITLE
Cannot invoke "java.net.InetAddress.getHostAddress()" because the return value of 

### ISSUE THREAD

**Issue by fffguo** [apache/dubbo#11588]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.0-beta.5
* Operating System version: macos 13.1
* Java version: jdk17

### Steps to reproduce this issue

我使用 zookeeper 3.8.0
1. 如下报错不影响正常启动，但是启动时会有报错，目前未发现有其他影响
2. 经过测试，升级curator版本到5.4.0后，问题不再复现。
3. 是否考虑将 curator 5.1.0 升级到 5.4.0 以解决该问题？

升级curator
```
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-framework</artifactId>
            <version>5.4.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-recipes</artifactId>
            <version>5.4.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-x-discovery</artifactId>
            <version>5.4.0</version>
        </dependency>
```

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
java.lang.NullPointerException: Cannot invoke "java.net.InetAddress.getHostAddress()" because the return value of "java.net.InetSocketAddress.getAddress()" is null
	at org.apache.curator.utils.Compatibility.getHostAddress(Compatibility.java:116) ~[curator-client-5.1.0.jar:?]
	at org.apache.curator.framework.imps.EnsembleTracker.configToConnectionString(EnsembleTracker.java:185) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:206) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.EnsembleTracker.access$300(EnsembleTracker.java:50) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:150) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:892) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:649) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:222) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:636) ~[zookeeper-3.7.0.jar:3.7.0]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:555) ~[zookeeper-3.7.0.jar:3.7.0]

2023-02-16 19:21:27.383 ERROR 2278 --- [ain-EventThread] o.a.c.f.i.CuratorFrameworkImpl           : Background exception was not retry-able or retry gave up

java.lang.NullPointerException: Cannot invoke "java.net.InetAddress.getHostAddress()" because the return value of "java.net.InetSocketAddress.getAddress()" is null
	at org.apache.curator.utils.Compatibility.getHostAddress(Compatibility.java:116) ~[curator-client-5.1.0.jar:?]
	at org.apache.curator.framework.imps.EnsembleTracker.configToConnectionString(EnsembleTracker.java:185) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:206) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.EnsembleTracker.access$300(EnsembleTracker.java:50) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:150) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:892) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:649) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:222) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:636) ~[zookeeper-3.7.0.jar:3.7.0]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:555) ~[zookeeper-3.7.0.jar:3.7.0]

2023-02-16 19:21:27.389  INFO 2278 --- [ain-EventThread] o.a.c.f.i.EnsembleTracker                : New config event received: {server.2=zookeeper-cluster-1.zookeeper-cluster-headless.public.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, server.1=zookeeper-cluster-0.zookeeper-cluster-headless.public.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, server.3=zookeeper-cluster-2.zookeeper-cluster-headless.public.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, version=0}
2023-02-16 19:21:27.389  INFO 2278 --- [ain-EventThread] o.a.c.f.i.EnsembleTracker                : New config event received: {server.2=zookeeper-cluster-1.zookeeper-cluster-headless.public.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, server.1=zookeeper-cluster-0.zookeeper-cluster-headless.public.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, server.3=zookeeper-cluster-2.zookeeper-cluster-headless.public.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, version=0}
2023-02-16 19:21:27.390 ERROR 2278 --- [ain-EventThread] o.a.c.f.i.CuratorFrameworkImpl           : Background exception was not retry-able or retry gave up

java.lang.NullPointerException: Cannot invoke "java.net.InetAddress.getHostAddress()" because the return value of "java.net.InetSocketAddress.getAddress()" is null
	at org.apache.curator.utils.Compatibility.getHostAddress(Compatibility.java:116) ~[curator-client-5.1.0.jar:?]
	at org.apache.curator.framework.imps.EnsembleTracker.configToConnectionString(EnsembleTracker.java:185) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:206) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.EnsembleTracker.access$300(EnsembleTracker.java:50) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:150) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:892) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:649) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:222) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:636) ~[zookeeper-3.7.0.jar:3.7.0]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:555) ~[zookeeper-3.7.0.jar:3.7.0]

2023-02-16 19:21:27.390 ERROR 2278 --- [ain-EventThread] o.a.c.f.i.CuratorFrameworkImpl           : Background exception was not retry-able or retry gave up

java.lang.NullPointerException: Cannot invoke "java.net.InetAddress.getHostAddress()" because the return value of "java.net.InetSocketAddress.getAddress()" is null
	at org.apache.curator.utils.Compatibility.getHostAddress(Compatibility.java:116) ~[curator-client-5.1.0.jar:?]
	at org.apache.curator.framework.imps.EnsembleTracker.configToConnectionString(EnsembleTracker.java:185) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:206) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.EnsembleTracker.access$300(EnsembleTracker.java:50) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:150) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:892) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:649) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:222) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:636) ~[zookeeper-3.7.0.jar:3.7.0]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:555) ~[zookeeper-3.7.0.jar:3.7.0]
```

**Comment by aamingaa** [comment]
这个curator版本要跟zk版本匹配的

**Comment by fffguo** [comment]
> 这个curator版本要跟zk版本匹配的，dubbo内置的zk版本是3.4.14，与curator 4.3.0的版本相匹配

我是用的 dubbo-dependencies-zookeeper-curator5 ，内置zookeeper是3.7.0，内置curator 5.1.0
我使用的是zookeeper 3.8

**Comment by fffguo** [comment]
考虑将 dubbo-dependencies-zookeeper-curator5  升级到 zookeeper 3.8   curator 升级到 5.4吗？

**Comment by aamingaa** [comment]
> java.net.InetAddress.getHostAddress()

我这边好像没有复现出这个错误呢，我用的例子来自https://github.com/apache/dubbo-samples/tree/master/1-basic/dubbo-samples-annotation，将dubbo 版本改成了3.2.0-beta.5

**Comment by aamingaa** [comment]
> 考虑将 dubbo-dependencies-zookeeper-curator5 升级到 zookeeper 3.8 curator 升级到 5.4吗？

我这边好像没有复现出这个错误呢，我用的例子来自https://github.com/apache/dubbo-samples/tree/master/1-basic/dubbo-samples-annotation，将dubbo 版本改成了3.2.0-beta.5

**Comment by mujtaba1747** [comment]
I'm facing this issue too.

**Comment by umi-soft** [comment]
> * [x]  I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
> 
> ### Environment
> * Dubbo version: 3.2.0-beta.5
> * Operating System version: macos 13.1
> * Java version: jdk17
> 
> ### Steps to reproduce this issue
> 我使用 zookeeper 3.8.0
> 
> 1. 如下报错不影响正常启动，但是启动时会有报错，目前未发现有其他影响
> 2. 经过测试，升级curator版本到5.4.0后，问题不再复现。
> 3. 是否考虑将 curator 5.1.0 升级到 5.4.0 以解决该问题？
> 
> 升级curator
> 
> ```
>         <dependency>
>             <groupId>org.apache.curator</groupId>
>             <artifactId>curator-framework</artifactId>
>             <version>5.4.0</version>
>         </dependency>
>         <dependency>
>             <groupId>org.apache.curator</groupId>
>             <artifactId>curator-recipes</artifactId>
>             <version>5.4.0</version>
>         </dependency>
>         <dependency>
>             <groupId>org.apache.curator</groupId>
>             <artifactId>curator-x-discovery</artifactId>
>             <version>5.4.0</version>
>         </dependency>
> ```
> 
> Pls. provide [GitHub address] to reproduce this issue.
> 
> ### Expected Behavior
> ### Actual Behavior
> If there is an exception, please attach the exception trace:
> 
> ```
> java.lang.NullPointerException: Cannot invoke "java.net.InetAddress.getHostAddress()" because the return value of "java.net.InetSocketAddress.getAddress()" is null
> 	at org.apache.curator.utils.Compatibility.getHostAddress(Compatibility.java:116) ~[curator-client-5.1.0.jar:?]
> 	at org.apache.curator.framework.imps.EnsembleTracker.configToConnectionString(EnsembleTracker.java:185) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:206) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.EnsembleTracker.access$300(EnsembleTracker.java:50) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:150) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:892) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:649) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:222) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:636) ~[zookeeper-3.7.0.jar:3.7.0]
> 	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:555) ~[zookeeper-3.7.0.jar:3.7.0]
> 
> 2023-02-16 19:21:27.383 ERROR 2278 --- [ain-EventThread] o.a.c.f.i.CuratorFrameworkImpl           : Background exception was not retry-able or retry gave up
> 
> java.lang.NullPointerException: Cannot invoke "java.net.InetAddress.getHostAddress()" because the return value of "java.net.InetSocketAddress.getAddress()" is null
> 	at org.apache.curator.utils.Compatibility.getHostAddress(Compatibility.java:116) ~[curator-client-5.1.0.jar:?]
> 	at org.apache.curator.framework.imps.EnsembleTracker.configToConnectionString(EnsembleTracker.java:185) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:206) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.EnsembleTracker.access$300(EnsembleTracker.java:50) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:150) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:892) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:649) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:222) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:636) ~[zookeeper-3.7.0.jar:3.7.0]
> 	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:555) ~[zookeeper-3.7.0.jar:3.7.0]
> 
> 2023-02-16 19:21:27.389  INFO 2278 --- [ain-EventThread] o.a.c.f.i.EnsembleTracker                : New config event received: {server.2=zookeeper-cluster-1.zookeeper-cluster-headless.public.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, server.1=zookeeper-cluster-0.zookeeper-cluster-headless.public.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, server.3=zookeeper-cluster-2.zookeeper-cluster-headless.public.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, version=0}
> 2023-02-16 19:21:27.389  INFO 2278 --- [ain-EventThread] o.a.c.f.i.EnsembleTracker                : New config event received: {server.2=zookeeper-cluster-1.zookeeper-cluster-headless.public.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, server.1=zookeeper-cluster-0.zookeeper-cluster-headless.public.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, server.3=zookeeper-cluster-2.zookeeper-cluster-headless.public.svc.cluster.local:2888:3888:participant;0.0.0.0:2181, version=0}
> 2023-02-16 19:21:27.390 ERROR 2278 --- [ain-EventThread] o.a.c.f.i.CuratorFrameworkImpl           : Background exception was not retry-able or retry gave up
> 
> java.lang.NullPointerException: Cannot invoke "java.net.InetAddress.getHostAddress()" because the return value of "java.net.InetSocketAddress.getAddress()" is null
> 	at org.apache.curator.utils.Compatibility.getHostAddress(Compatibility.java:116) ~[curator-client-5.1.0.jar:?]
> 	at org.apache.curator.framework.imps.EnsembleTracker.configToConnectionString(EnsembleTracker.java:185) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:206) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.EnsembleTracker.access$300(EnsembleTracker.java:50) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:150) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:892) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:649) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:222) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:636) ~[zookeeper-3.7.0.jar:3.7.0]
> 	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:555) ~[zookeeper-3.7.0.jar:3.7.0]
> 
> 2023-02-16 19:21:27.390 ERROR 2278 --- [ain-EventThread] o.a.c.f.i.CuratorFrameworkImpl           : Background exception was not retry-able or retry gave up
> 
> java.lang.NullPointerException: Cannot invoke "java.net.InetAddress.getHostAddress()" because the return value of "java.net.InetSocketAddress.getAddress()" is null
> 	at org.apache.curator.utils.Compatibility.getHostAddress(Compatibility.java:116) ~[curator-client-5.1.0.jar:?]
> 	at org.apache.curator.framework.imps.EnsembleTracker.configToConnectionString(EnsembleTracker.java:185) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:206) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.EnsembleTracker.access$300(EnsembleTracker.java:50) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:150) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:892) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:649) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:222) ~[curator-framework-5.1.0.jar:5.1.0]
> 	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:636) ~[zookeeper-3.7.0.jar:3.7.0]
> 	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:555) ~[zookeeper-3.7.0.jar:3.7.0]
> ```

I'm facing this issue too. @aamingaa

**Comment by wcy666103** [comment]
In dubbo 3.3 branch, these dependencies have been upgraded 
`<zookeeper_version>3.7.0</zookeeper_version>`
`<curator_version>5.1.0</curator_version>`

In the 3.2 branch, these dependency versions should not be changed, you can try using the 3.3 branch. If this situation occurs again, feedback can be upgraded
