### ISSUE TITLE
java.lang.IllegalStateException: Extension instance (name: rest, class: interface org.apache.dubbo.rpc.Protocol) couldn't be instantiated: null

### ISSUE THREAD

**Issue by jixiaoliang** [apache/dubbo#11631]
java.lang.IllegalStateException: Extension instance (name: rest, class: interface org.apache.dubbo.rpc.Protocol) couldn't be instantiated: null
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:806) ~[dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:561) ~[dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:535) ~[dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.toInvokers(ServiceDiscoveryRegistryDirectory.java:352) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.refreshInvoker(ServiceDiscoveryRegistryDirectory.java:254) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.refreshOverrideAndInvoker(ServiceDiscoveryRegistryDirectory.java:182) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.notify(ServiceDiscoveryRegistryDirectory.java:176) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.addListenerAndNotify(ServiceInstancesChangedListener.java:237) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribeURLs(ServiceDiscoveryRegistry.java:326) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.doSubscribe(ServiceDiscoveryRegistry.java:217) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribe(ServiceDiscoveryRegistry.java:185) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:88) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.registry.integration.DynamicDirectory.subscribe(DynamicDirectory.java:183) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.subscribe(ServiceDiscoveryRegistryDirectory.java:127) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.registry.integration.RegistryProtocol.doCreateInvoker(RegistryProtocol.java:569) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getServiceDiscoveryInvoker(InterfaceCompatibleRegistryProtocol.java:65) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshServiceDiscoveryInvoker(MigrationInvoker.java:437) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToForceApplicationInvoker(MigrationInvoker.java:206) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.refreshInvoker(MigrationRuleHandler.java:79) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:60) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:247) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:534) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:504) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:486) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:83) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:74) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:71) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:52) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.config.ReferenceConfig.createInvokerForRemote(ReferenceConfig.java:614) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:448) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:300) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:232) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.config.utils.SimpleReferenceCache.get(SimpleReferenceCache.java:131) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:396) [dubbo-3.1.4.jar:3.1.4]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) ~[na:1.8.0_261]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:376) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:167) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:139) [dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:113) ~[dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:102) ~[dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:47) ~[dubbo-3.1.4.jar:3.1.4]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:898) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at cn.soulhunter.erp.inventory.InventoryApplication.main(InventoryApplication.java:19) ~[classes/:na]
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_261]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_261]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_261]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_261]
	at org.apache.dubbo.common.beans.support.InstantiationStrategy.instantiate(InstantiationStrategy.java:94) ~[dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtensionInstance(ExtensionLoader.java:811) ~[dubbo-3.1.4.jar:3.1.4]
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:772) ~[dubbo-3.1.4.jar:3.1.4]
	... 57 common frames omitted
Caused by: java.lang.NoClassDefFoundError: javax/ws/rs/ProcessingException
	at org.apache.dubbo.rpc.protocol.rest.RestProtocol.<init>(RestProtocol.java:80) ~[dubbo-3.1.4.jar:3.1.4]
	... 64 common frames omitted

**Comment by jixiaoliang** [comment]
dubbo-3.1.4 有人遇到这个错误不,不影响使用就是看着烦得很

**Comment by pipipapi** [comment]
启动还是调用的时候报这个的？

**Comment by MieAh** [comment]
看这堆栈异常问题是出在RestProtocol中，因为没有具体的场景，我可以给你几个建议，你可以检查一下类路径里面是否包含了这个无法找到的ProcessingException，如果缺少，你可以自己引入包含这个类的jar包。或是可能是不同库导致版本冲突，你可以尝试降版本或者升版本来解决这个问题

**Comment by DiJiaBuHuiFei** [comment]
作者 有解决吗 遇到同样的问题。。。

**Comment by DiJiaBuHuiFei** [comment]
可算是找到原因了。。。。

**Comment by AlbumenJ** [comment]
检查是不是和 Spring Cloud Alibaba 应用共用注册中心了，导致错误订阅到了 Spring Cloud 的应用，使用了 Rest 协议

**Comment by chenglutao** [comment]
> 

是什么原因啊，启动客户端也是报这个错误

**Comment by chenglutao** [comment]
> 可算是找到原因了。。。。

你是怎么解决的这个问题，我也是消费者启动的时候会报rest异常，，dubbo 调用没影响

**Comment by DiJiaBuHuiFei** [comment]
> > 可算是找到原因了。。。。
> 
> 你是怎么解决的这个问题，我也是消费者启动的时候会报rest异常，，dubbo 调用没影响

你把dubbo和spring-cloud的分组分开,不要用一样的分组名

**Comment by chenglutao** [comment]
> > > 可算是找到原因了。。。。
> > 
> > 
> > 你是怎么解决的这个问题，我也是消费者启动的时候会报rest异常，，dubbo 调用没影响
> 
> 你把dubbo和spring-cloud的分组分开,不要用一样的分组名

谢谢您，这个解决方式是有效的
