### ISSUE TITLE
Demo project `dubbo-samples-annotation` start failed. What should I do?

### ISSUE THREAD

**Issue by YunWZ** [apache/dubbo#11645]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here

I try to start `dubbo-samples-annotation` project, but failed.

First, I start `AnnotationProviderBootstrap`, that is ok.
and output log :
```text
[24/02/23 12:38:13:013 CST] main  INFO server.Server:  [DUBBO] qos-server bind localhost:22222, dubbo version: 3.2.0-beta.5-SNAPSHOT, current host: 192.168.31.232
```

And then, I try  to start `AnnotationConsumerBootstrap`, it's failed! The output log below:
```text
[24/02/23 12:51:28:028 CST] DubboShutdownHook  WARN integration.RegistryProtocol:  [DUBBO] null, dubbo version: 3.2.0-beta.5-SNAPSHOT, current host: 192.168.31.232, error code: 99-0. This may be caused by unknown error in registry module, go to https://dubbo.apache.org/faq/99/0 to find instructions. 
java.lang.NullPointerException
	at org.apache.dubbo.registry.integration.RegistryProtocol$ExporterChangeableWrapper.unexport(RegistryProtocol.java:913)
	at org.apache.dubbo.registry.integration.RegistryProtocol$DestroyableExporter.unexport(RegistryProtocol.java:695)
	at org.apache.dubbo.config.ServiceConfig.unexport(ServiceConfig.java:195)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.postDestroy(DefaultModuleDeployer.java:241)
	at org.apache.dubbo.rpc.model.ModuleModel.onDestroy(ModuleModel.java:109)
	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:115)
	at org.apache.dubbo.rpc.model.ApplicationModel.onDestroy(ApplicationModel.java:260)
	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:115)
	at org.apache.dubbo.config.DubboShutdownHook.doDestroy(DubboShutdownHook.java:123)
	at org.apache.dubbo.config.DubboShutdownHook.run(DubboShutdownHook.java:78)
```

**Comment by ShenFeng312** [comment]
You can remore
```java
  System.out.println("greeting : " + annotationAction.doGreeting("world"));
  System.out.println("reply : " + annotationAction.replyGreeting("world"));
```
in `AnnotationConsumerBootstrap`.
it will always time out

**Comment by AlbumenJ** [comment]
```
[24/02/23 12:51:28:028 CST] DubboShutdownHook  WARN integration.RegistryProtocol:  [DUBBO] null, dubbo version: 3.2.0-beta.5-SNAPSHOT, current host: 192.168.31.232, error code: 99-0. This may be caused by unknown error in registry module, go to https://dubbo.apache.org/faq/99/0 to find instructions. 
java.lang.NullPointerException
	at org.apache.dubbo.registry.integration.RegistryProtocol$ExporterChangeableWrapper.unexport(RegistryProtocol.java:913)
	at org.apache.dubbo.registry.integration.RegistryProtocol$DestroyableExporter.unexport(RegistryProtocol.java:695)
	at org.apache.dubbo.config.ServiceConfig.unexport(ServiceConfig.java:195)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.postDestroy(DefaultModuleDeployer.java:241)
	at org.apache.dubbo.rpc.model.ModuleModel.onDestroy(ModuleModel.java:109)
	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:115)
	at org.apache.dubbo.rpc.model.ApplicationModel.onDestroy(ApplicationModel.java:260)
	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:115)
	at org.apache.dubbo.config.DubboShutdownHook.doDestroy(DubboShutdownHook.java:123)
	at org.apache.dubbo.config.DubboShutdownHook.run(DubboShutdownHook.java:78)
```

This is a log when shutting down.
