### ISSUE TITLE
How to use dubbo+consult?Exception is found: Value is too long (limit: 512 characters)')

### ISSUE THREAD

**Issue by imgoby** [apache/dubbo#11684]
<dubbo.version>2.7.21</dubbo.version>
<spring.version>4.3.29.RELEASE</spring.version>

config:

ubbo:
  scan:
    base-packages: com.xxxx.yyyy.demo.dubboconsul.cloud.provider.service
  protocol:
    name: dubbo
    port: -1
    payload: 31457280
  registry:
    address: consul://@consul.host@:@consul.port@
    simplified: true
  cloud:
    subscribed-services: ''
  application:
    qos-enable: false
    id: ${spring.application.name}
  consumer:
    version: 1.0.0
  provider:
    version: 1.0.0
    timeout: 30000
    retries: 1
------------------------------------

java `
package com.xxxx.yyyy.demo.dubboconsul.cloud.provider.service;

import com.xxxx.yyyy.demo.dubboconsul.cloud.api.DubboApi;
import org.apache.dubbo.config.annotation.DubboService;
import org.apache.dubbo.config.annotation.Method;
import org.springframework.beans.factory.annotation.Value;

/**
 * @author ZhangShuzheng
 * @date 2019/5/8
 */
@DubboService(methods = {
@Method(name = "demo", retries = 1),
@Method(name = "demo1", retries = 1),
@Method(name = "demo888888888888df8888888", retries = 1),
@Method(name = "demo888888888xc8888888888", retries = 1),
@Method(name = "demo88888888888fd88888888", retries = 1),
        })
public class DubboApiImpl implements DubboApi {

    @Value("${server.port}")
    private Integer port;

    @Value("${xxx:please_set_in_consul}")
    private String xxx;

    @Value("${spring.elasticsearch.rest.uris:not_set}")
    public String restUris;

    @Override
    public String demo() {
        if(xxx!=null && xxx.equals("please_set_in_consul")){
            System.out.println("please set in consul,path is : config/sail-demo-dubbo-springcloud-provider,default/data ,default means profile");
        }
        return "port= " + port + ",xxx=" + xxx+",restUris="+restUris;
    }

    @Override
    public String demo1() {
        return null;
    }

    @Override
    public String demo2() {
        return null;
    }

    @Override
    public String demo3() {
        return null;
    }

    @Override
    public String demo4() {
        return null;
    }

    @Override
    public String demo5() {
        return null;
    }

    @Override
    public String demo6() {
        return null;
    }

    @Override
    public String demo7() {
        return null;
    }

    @Override
    public String demo888888sdfsd8888888888888() {
        return null;
    }

    @Override
    public String demo8888888s888888888888() {
        return null;
    }

    @Override
    public String demo8888888sf888888888888() {
        return null;
    }

    @Override
    public String demo88888888sdf88888888888() {
        return null;
    }

    @Override
    public String demo88888888dfd88888888888() {
        return null;
    }

    @Override
    public String demo888888888xc8888888888() {
        return null;
    }

    @Override
    public String demo88888sdf888888x88888888() {
        return null;
    }

    @Override
    public String demo888888888888df8888888() {
        return null;
    }

    @Override
    public String demo8888s8888888x88888888() {
        return null;
    }

    @Override
    public String demo888888888888sx8888888() {
        return null;
    }

    @Override
    public String demo88888888888df88888888() {
        return null;
    }

    @Override
    public String demo8888888888df888888888() {
        return null;
    }

    @Override
    public String demo88888888888888888889() {
        return null;
    }

    @Override
    public String demo88888888888888888888() {
        return null;
    }

    @Override
    public String demo88888888888888888886() {
        return null;
    }

    @Override
    public String demo88888888888888888885() {
        return null;
    }

    @Override
    public String demo8888888888888888888x() {
        return null;
    }

    @Override
    public String demo8888888888888888888f() {
        return null;
    }

    @Override
    public String demo8888888888888d888888d() {
        return null;
    }

    @Override
    public String demo8888888888888d88dd8888d() {
        return null;
    }

    @Override
    public String demo8888888888888888s888() {
        return null;
    }

    @Override
    public String demo88888888d88888888888() {
        return null;
    }

    @Override
    public String demo888888888sx8888888888() {
        return null;
    }

    @Override
    public String demo8888888888cd888888888() {
        return null;
    }

    @Override
    public String demo88888888888fd88888888() {
        return null;
    }

}
`

Exception:

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-02-28 16:36:11.731 ERROR 4104 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to register dubbo://192.168.0.111:20881/com.xxxx.yyyy.demo.dubboconsul.cloud.api.DubboApi?application=sail-demo-dubbo-consul-springcloud-provider&demo.retries=1&demo.return=true&demo1.retries=1&demo1.return=true&demo888888888888df8888888.retries=1&demo888888888888df8888888.return=true&demo88888888888fd88888888.retries=1&demo88888888888fd88888888.return=true&demo888888888xc8888888888.retries=1&demo888888888xc8888888888.return=true&deprecated=false&dubbo=2.0.2&release=2.7.21&timeout=30000&timestamp=1677573371178&version=1.0.0 to registry boat-consul.default.svc.cluster.local:8500, cause: OperationException(statusCode=400, statusMessage='Bad Request', statusContent='Invalid Service Meta: Couldn't load metadata pair ('url', 'dubbo://192.168.0.111:20881/com.xxxx.yyyy.demo.dubboconsul.cloud.api.DubboApi?application=sail-demo-dubbo-consul-springcloud-provider&demo.retries=1&demo.return=true&demo1.retries=1&demo1.return=true&demo888888888888df8888888.retries=1&demo888888888888df8888888.return=true&demo88888888888fd88888888.retries=1&demo88888888888fd88888888.return=true&demo888888888xc8888888888.retries=1&demo888888888xc8888888888.return=true&deprecated=false&dubbo=2.0.2&release=2.7.21&timeout=30000&timestamp=1677573371178&version=1.0.0'): Value is too long (limit: 512 characters)')
	at org.apache.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:219) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.registry.consul.ConsulRegistry.register(ConsulRegistry.java:114) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.registry.ListenerRegistryWrapper.register(ListenerRegistryWrapper.java:57) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:222) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:62) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:73) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:64) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:518) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:339) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:314) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:238) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.exportService(DubboBootstrap.java:1100) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.lambda$exportServices$14(DubboBootstrap.java:1087) ~[dubbo-2.7.21.jar:2.7.21]
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065) ~[na:na]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.exportServices(DubboBootstrap.java:1071) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:887) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onContextRefreshedEvent(DubboBootstrapApplicationListener.java:70) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onApplicationContextEvent(DubboBootstrapApplicationListener.java:63) ~[dubbo-2.7.21.jar:2.7.21]
	at com.alibaba.spring.context.OnceApplicationContextEventListener.onApplicationEvent(OnceApplicationContextEventListener.java:52) ~[spring-context-support-1.0.11.jar:na]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.11.jar:2.6.11]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745) ~[spring-boot-2.6.11.jar:2.6.11]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:420) ~[spring-boot-2.6.11.jar:2.6.11]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.6.11.jar:2.6.11]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) ~[spring-boot-2.6.11.jar:2.6.11]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.6.11.jar:2.6.11]
	at com.xxxx.yyyy.demo.dubboconsul.cloud.provider.DemoProviderApplication.main(DemoProviderApplication.java:16) ~[classes/:na]
Caused by: com.ecwid.consul.v1.OperationException: OperationException(statusCode=400, statusMessage='Bad Request', statusContent='Invalid Service Meta: Couldn't load metadata pair ('url', 'dubbo://192.168.0.111:20881/com.xxxx.yyyy.demo.dubboconsul.cloud.api.DubboApi?application=sail-demo-dubbo-consul-springcloud-provider&demo.retries=1&demo.return=true&demo1.retries=1&demo1.return=true&demo888888888888df8888888.retries=1&demo888888888888df8888888.return=true&demo88888888888fd88888888.retries=1&demo88888888888fd88888888.return=true&demo888888888xc8888888888.retries=1&demo888888888xc8888888888.return=true&deprecated=false&dubbo=2.0.2&release=2.7.21&timeout=30000&timestamp=1677573371178&version=1.0.0'): Value is too long (limit: 512 characters)')
	at com.ecwid.consul.v1.agent.AgentConsulClient.agentServiceRegister(AgentConsulClient.java:278) ~[consul-api-1.4.5.jar:na]
	at com.ecwid.consul.v1.agent.AgentConsulClient.agentServiceRegister(AgentConsulClient.java:265) ~[consul-api-1.4.5.jar:na]
	at com.ecwid.consul.v1.ConsulClient.agentServiceRegister(ConsulClient.java:305) ~[consul-api-1.4.5.jar:na]
	at org.apache.dubbo.registry.consul.ConsulRegistry.doRegister(ConsulRegistry.java:120) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:206) ~[dubbo-2.7.21.jar:2.7.21]
	... 33 common frames omitted

2023-02-28 16:36:11.735  INFO 4104 --- [           main] o.apache.dubbo.config.DubboShutdownHook  :  [DUBBO] Run shutdown hook now., dubbo version: 2.7.21, current host: 192.168.0.111
2023-02-28 16:36:11.744  INFO 4104 --- [           main] o.a.d.c.e.listener.LoggingEventListener  :  [DUBBO] Dubbo Service has been destroyed., dubbo version: 2.7.21, current host: 192.168.0.111
2023-02-28 16:36:11.744  INFO 4104 --- [           main] o.a.d.r.support.AbstractRegistryFactory  :  [DUBBO] Close all registries [consul://boat-consul.default.svc.cluster.local:8500/org.apache.dubbo.registry.RegistryService?application=sail-demo-dubbo-consul-springcloud-provider&dubbo=2.0.2&id=org.apache.dubbo.config.RegistryConfig#0&interface=org.apache.dubbo.registry.RegistryService&pid=4104&qos.enable=false&release=2.7.21&simplified=true&timestamp=1677573371173], dubbo version: 2.7.21, current host: 192.168.0.111
2023-02-28 16:36:11.744  INFO 4104 --- [           main] o.a.d.registry.consul.ConsulRegistry     :  [DUBBO] Destroy registry:consul://boat-consul.default.svc.cluster.local:8500/org.apache.dubbo.registry.RegistryService?application=sail-demo-dubbo-consul-springcloud-provider&dubbo=2.0.2&id=org.apache.dubbo.config.RegistryConfig#0&interface=org.apache.dubbo.registry.RegistryService&pid=4104&qos.enable=false&release=2.7.21&simplified=true&timestamp=1677573371173, dubbo version: 2.7.21, current host: 192.168.0.111
2023-02-28 16:36:11.744  INFO 4104 --- [           main] o.a.d.registry.consul.ConsulRegistry     :  [DUBBO] Unregister: dubbo://192.168.0.111:20881/com.xxxx.yyyy.demo.dubboconsul.cloud.api.DubboApi?application=sail-demo-dubbo-consul-springcloud-provider&demo.retries=1&demo.return=true&demo1.retries=1&demo1.return=true&demo888888888888df8888888.retries=1&demo888888888888df8888888.return=true&demo88888888888fd88888888.retries=1&demo88888888888fd88888888.return=true&demo888888888xc8888888888.retries=1&demo888888888xc8888888888.return=true&deprecated=false&dubbo=2.0.2&release=2.7.21&timeout=30000&timestamp=1677573371178&version=1.0.0, dubbo version: 2.7.21, current host: 192.168.0.111
2023-02-28 16:36:11.746  INFO 4104 --- [           main] o.a.d.registry.consul.ConsulRegistry     :  [DUBBO] Destroy unregister url dubbo://192.168.0.111:20881/com.xxxx.yyyy.demo.dubboconsul.cloud.api.DubboApi?application=sail-demo-dubbo-consul-springcloud-provider&demo.retries=1&demo.return=true&demo1.retries=1&demo1.return=true&demo888888888888df8888888.retries=1&demo888888888888df8888888.return=true&demo88888888888fd88888888.retries=1&demo88888888888fd88888888.return=true&demo888888888xc8888888888.retries=1&demo888888888xc8888888888.return=true&deprecated=false&dubbo=2.0.2&release=2.7.21&timeout=30000&timestamp=1677573371178&version=1.0.0, dubbo version: 2.7.21, current host: 192.168.0.111
2023-02-28 16:36:11.747  INFO 4104 --- [           main] o.a.d.rpc.protocol.dubbo.DubboProtocol   :  [DUBBO] Close dubbo server: /192.168.0.111:20881, dubbo version: 2.7.21, current host: 192.168.0.111
2023-02-28 16:36:11.748  INFO 4104 --- [           main] o.a.d.remoting.transport.AbstractServer  :  [DUBBO] Close NettyServer bind /0.0.0.0:20881, export /192.168.0.111:20881, dubbo version: 2.7.21, current host: 192.168.0.111
2023-02-28 16:36:15.929  INFO 4104 --- [           main] o.a.d.rpc.protocol.dubbo.DubboProtocol   :  [DUBBO] Unexport service: dubbo://192.168.0.111:20881/com.xxxx.yyyy.demo.dubboconsul.cloud.api.DubboApi?anyhost=true&application=sail-demo-dubbo-consul-springcloud-provider&bind.ip=192.168.0.111&bind.port=20881&demo.retries=1&demo.return=true&demo1.retries=1&demo1.return=true&demo888888888888df8888888.retries=1&demo888888888888df8888888.return=true&demo88888888888fd88888888.retries=1&demo88888888888fd88888888.return=true&demo888888888xc8888888888.retries=1&demo888888888xc8888888888.return=true&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.xxxx.yyyy.demo.dubboconsul.cloud.api.DubboApi&metadata-type=remote&methods=demo3,demo4,demo5,demo6,demo7,demo8888888888cd888888888,demo88888888sdf88888888888,demo888888888888sx8888888,demo888888sdfsd8888888888888,demo,demo888888888888df8888888,demo8888888sf888888888888,demo8888888888df888888888,demo8888s8888888x88888888,demo8888888888888888888f,demo888888888xc8888888888,demo888888888sx8888888888,demo88888888dfd88888888888,demo8888888s888888888888,demo1,demo2,demo8888888888888888s888,demo88888888d88888888888,demo88888888888df88888888,demo88888888888888888889,demo8888888888888d888888d,demo88888888888888888886,demo88888888888888888885,demo88888888888fd88888888,demo8888888888888888888x,demo88888sdf888888x88888888,demo88888888888888888888,demo8888888888888d88dd8888d&payload=31457280&pid=4104&qos.enable=false&release=2.7.21&retries=1&revision=1.0.0&service.name=ServiceBean:/com.xxxx.yyyy.demo.dubboconsul.cloud.api.DubboApi&side=provider&timeout=30000&timestamp=1677573371178&version=1.0.0, dubbo version: 2.7.21, current host: 192.168.0.111
2023-02-28 16:36:15.931  INFO 4104 --- [           main] org.apache.dubbo.qos.server.Server       :  [DUBBO] qos-server stopped., dubbo version: 2.7.21, current host: 192.168.0.111
2023-02-28 16:36:15.931  INFO 4104 --- [           main] o.a.d.rpc.protocol.injvm.InjvmProtocol   :  [DUBBO] Unexport service: injvm://127.0.0.1/com.xxxx.yyyy.demo.dubboconsul.cloud.api.DubboApi?anyhost=true&application=sail-demo-dubbo-consul-springcloud-provider&bind.ip=192.168.0.111&bind.port=20881&demo.retries=1&demo.return=true&demo1.retries=1&demo1.return=true&demo888888888888df8888888.retries=1&demo888888888888df8888888.return=true&demo88888888888fd88888888.retries=1&demo88888888888fd88888888.return=true&demo888888888xc8888888888.retries=1&demo888888888xc8888888888.return=true&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.xxxx.yyyy.demo.dubboconsul.cloud.api.DubboApi&metadata-type=remote&methods=demo3,demo4,demo5,demo6,demo7,demo8888888888cd888888888,demo88888888sdf88888888888,demo888888888888sx8888888,demo888888sdfsd8888888888888,demo,demo888888888888df8888888,demo8888888sf888888888888,demo8888888888df888888888,demo8888s8888888x88888888,demo8888888888888888888f,demo888888888xc8888888888,demo888888888sx8888888888,demo88888888dfd88888888888,demo8888888s888888888888,demo1,demo2,demo8888888888888888s888,demo88888888d88888888888,demo88888888888df88888888,demo88888888888888888889,demo8888888888888d888888d,demo88888888888888888886,demo88888888888888888885,demo88888888888fd88888888,demo8888888888888888888x,demo88888sdf888888x88888888,demo88888888888888888888,demo8888888888888d88dd8888d&payload=31457280&pid=4104&qos.enable=false&release=2.7.21&retries=1&revision=1.0.0&service.name=ServiceBean:/com.xxxx.yyyy.demo.dubboconsul.cloud.api.DubboApi&side=provider&timeout=30000&timestamp=1677573371178&version=1.0.0, dubbo version: 2.7.21, current host: 192.168.0.111
2023-02-28 16:36:15.934  WARN 4104 --- [           main] o.a.d.r.support.AbstractRegistryFactory  :  [DUBBO] All registry instances have been destroyed, failed to fetch any instance. Usually, this means no need to try to do unnecessary redundant resource clearance, all registries has been taken care of., dubbo version: 2.7.21, current host: 192.168.0.111
2023-02-28 16:36:15.935  WARN 4104 --- [           main] o.a.d.r.integration.RegistryProtocol     :  [DUBBO] Cannot invoke "Object.hashCode()" because "key" is null, dubbo version: 2.7.21, current host: 192.168.0.111

java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
	at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1111) ~[na:na]
	at java.base/java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1102) ~[na:na]
	at org.apache.dubbo.registry.integration.RegistryProtocol$ExporterChangeableWrapper.unexport(RegistryProtocol.java:825) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.registry.integration.RegistryProtocol.destroy(RegistryProtocol.java:572) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.destroy(ProtocolListenerWrapper.java:82) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.destroy(ProtocolFilterWrapper.java:88) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.destroy(QosProtocolWrapper.java:80) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.config.DubboShutdownHook.destroyProtocols(DubboShutdownHook.java:143) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.config.DubboShutdownHook.doDestroy(DubboShutdownHook.java:118) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.config.DubboShutdownHook.destroyAll(DubboShutdownHook.java:131) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.destroy(DubboBootstrap.java:1270) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.common.function.ThrowableAction.execute(ThrowableAction.java:46) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.common.lang.ShutdownHookCallbacks.lambda$callback$0(ShutdownHookCallbacks.java:70) ~[dubbo-2.7.21.jar:2.7.21]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.apache.dubbo.common.lang.ShutdownHookCallbacks.callback(ShutdownHookCallbacks.java:70) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.config.DubboShutdownHook.callback(DubboShutdownHook.java:84) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.config.DubboShutdownHook.run(DubboShutdownHook.java:72) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onContextClosedEvent(DubboBootstrapApplicationListener.java:74) ~[dubbo-2.7.21.jar:2.7.21]
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onApplicationContextEvent(DubboBootstrapApplicationListener.java:65) ~[dubbo-2.7.21.jar:2.7.21]
	at com.alibaba.spring.context.OnceApplicationContextEventListener.onApplicationEvent(OnceApplicationContextEventListener.java:52) ~[spring-context-support-1.0.11.jar:na]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1058) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:172) ~[spring-boot-2.6.11.jar:2.6.11]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:801) ~[spring-boot-2.6.11.jar:2.6.11]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317) ~[spring-boot-2.6.11.jar:2.6.11]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) ~[spring-boot-2.6.11.jar:2.6.11]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.6.11.jar:2.6.11]
	at com.xxxx.yyyy.demo.dubboconsul.cloud.provider.DemoProviderApplication.main(DemoProviderApplication.java:16) ~[classes/:na]

**Comment by imgoby** [comment]
In my business application. set dubbo.registry.simplified=true  could not resolve it. because the package name or method number is so much. is there some idea to resolve?
upgrad to new version?

**Comment by ShenFeng312** [comment]
this error is thorw by consul server
