### ISSUE TITLE
alias wrong type

### ISSUE THREAD

**Issue by zhengkaifor** [apache/dubbo#11688]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.6
* Operating System version: mac os 10.15.7
* Java version: 1.8

### Steps to reproduce this issue

1. one class @DubboReference  fileName A
![image](https://user-images.githubusercontent.com/20293800/221814142-dbb5b55a-29a9-4311-b671-51476ae8791e.png)
2.other class @DubboReference  fileName B
![image](https://user-images.githubusercontent.com/20293800/221814281-5e2299c3-8645-4a7a-8621-41f2c9e1b10c.png)
3. third class @DubboReference  anothor type but fileName also B
![image](https://user-images.githubusercontent.com/20293800/221814533-d1c93933-d51c-4f7f-9d0c-342c08d24307.png)

Pls. provide [GitHub address] to reproduce this issue.

### don't Report an error

If there is an exception, please attach the exception trace:

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'storeProxy': Injection of @DubboReference dependencies is failed; nested exception is java.lang.IllegalArgumentException: Can not set com.pupu.aggregation.facade.api.IPositionConfigAggregationApi field com.pupu.admin.aggregation.proxy.store.StoreProxy.productAggregationEsApi2 to com.sun.proxy.$Proxy159
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.postProcessPropertyValues(ReferenceAnnotationBeanPostProcessor.java:323) ~[dubbo-3.1.7.jar:3.1.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1268) ~[spring-beans-4.3.25.RELEASE.jar:4.3.25.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551) ~[spring-beans-4.3.25.RELEASE.jar:4.3.25.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481) ~[spring-beans-4.3.25.RELEASE.jar:4.3.25.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312) ~[spring-beans-4.3.25.RELEASE.jar:4.3.25.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.25.RELEASE.jar:4.3.25.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308) ~[spring-beans-4.3.25.RELEASE.jar:4.3.25.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.25.RELEASE.jar:4.3.25.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:211) ~[spring-beans-4.3.25.RELEASE.jar:4.3.25.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1131) ~[spring-beans-4.3.25.RELEASE.jar:4.3.25.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1059) ~[spring-beans-4.3.25.RELEASE.jar:4.3.25.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:583) ~[spring-beans-4.3.25.RELEASE.jar:4.3.25.RELEASE]
	... 60 common frames omitted
Caused by: java.lang.IllegalArgumentException: Can not set com.pupu.aggregation.facade.api.IPositionConfigAggregationApi field com.pupu.admin.aggregation.proxy.store.StoreProxy.productAggregationEsApi2 to com.sun.proxy.$Proxy159
	at com.zeroturnaround.jrebelbase.reflection.a.a(SourceFile:278) ~[na:1.8.0_221]
	at com.zeroturnaround.jrebelbase.reflection.a.set(SourceFile:99) ~[na:1.8.0_221]
	at java.lang.reflect.Field.set(Field.java:764) ~[na:1.8.0_221]
	at org.apache.dubbo.config.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor$AnnotatedInjectElement.inject(AbstractAnnotationBeanPostProcessor.java:379) ~[dubbo-3.1.7.jar:3.1.7]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87) ~[spring-beans-4.3.25.RELEASE.jar:4.3.25.RELEASE]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.postProcessPropertyValues(ReferenceAnnotationBeanPostProcessor.java:319) ~[dubbo-3.1.7.jar:3.1.7]
	... 71 common frames omitted


```

**Comment by zhengkaifor** [comment]
the reason is
field not declare ID,the referenceBeanName is filedName
![image](https://user-images.githubusercontent.com/20293800/221815711-30f443af-82f1-40c1-b714-69960d16deb5.png)
when have two same reference,will register alias to spring bean
![image](https://user-images.githubusercontent.com/20293800/221816235-6c31795f-4bee-4ac8-84b0-ee1de5076cbc.png)

when the other class use anothor type but fileName  hit alias ，will return wrong type
![image](https://user-images.githubusercontent.com/20293800/221816517-ca757c8b-76a0-4537-9e1b-54411f593738.png)

**Comment by liufeiyu1002** [comment]
可以提供一个复现的demo么

**Comment by liufeiyu1002** [comment]
问题已复现。晚上提修复代码
