### ISSUE TITLE
Client not connected, current status:SHUTDOWN

### ISSUE THREAD

**Issue by HelloToGithub** [apache/dubbo#11680]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
Dubbo：3.1.7
Nacos：2.0.3
Idea下服务点击重新运行 需要再次点击停止才会重新运行 否则一直出现以下错误
![image](https://user-images.githubusercontent.com/15622677/221743487-816d7a21-356e-4256-8301-3e808e7fc8c4.png)

2023-02-28 11:08:33.271 [SpringApplicationShutdownHook] ERROR com.alibaba.nacos.common.remote.client - Send request fail, request = InstanceRequest{headers={app=unknown}, requestId='null'}, retryTimes = 0, errorMessage = Client not connected, current status:SHUTDOWN
2023-02-28 11:08:33.372 [SpringApplicationShutdownHook] ERROR com.alibaba.nacos.common.remote.client - Send request fail, request = InstanceRequest{headers={app=unknown}, requestId='null'}, retryTimes = 1, errorMessage = Client not connected, current status:SHUTDOWN
2023-02-28 11:08:33.473 [SpringApplicationShutdownHook] ERROR com.alibaba.nacos.common.remote.client - Send request fail, request = InstanceRequest{headers={app=unknown}, requestId='null'}, retryTimes = 2, errorMessage = Client not connected, current status:SHUTDOWN
2023-02-28 11:08:33.473 [SpringApplicationShutdownHook] WARN  org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper -  [DUBBO] Failed to request nacos naming server. Dubbo will try to retry in 1000. Try times: 9, dubbo version: 3.1.7, current host: 192.168.0.128, error code: 1-37. This may be caused by , go to https://dubbo.apache.org/faq/1/37 to find instructions. 
com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:290)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doDeregisterService(NamingGrpcClientProxy.java:153)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.deregisterService(NamingGrpcClientProxy.java:139)
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.deregisterService(NamingClientProxyDelegate.java:99)
	at com.alibaba.nacos.client.naming.NacosNamingService.deregisterInstance(NacosNamingService.java:180)
	at com.alibaba.nacos.client.naming.NacosNamingService.deregisterInstance(NacosNamingService.java:170)
	at com.alibaba.nacos.client.naming.NacosNamingService.deregisterInstance(NacosNamingService.java:155)
	at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.lambda$deregisterInstance$4(NacosNamingServiceWrapper.java:75)
	at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.accept(NacosNamingServiceWrapper.java:146)
	at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.deregisterInstance(NacosNamingServiceWrapper.java:75)
	at org.apache.dubbo.registry.nacos.NacosRegistry.doUnregister(NacosRegistry.java:195)
	at org.apache.dubbo.registry.support.FailbackRegistry.unregister(FailbackRegistry.java:256)
	at org.apache.dubbo.registry.ListenerRegistryWrapper.unregister(ListenerRegistryWrapper.java:75)
	at org.apache.dubbo.registry.integration.DynamicDirectory.destroy(DynamicDirectory.java:301)
	at org.apache.dubbo.registry.integration.RegistryDirectory.destroy(RegistryDirectory.java:142)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.destroy(AbstractClusterInvoker.java:129)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.destroy(MockClusterInvoker.java:88)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.destroy(MigrationInvoker.java:326)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:61)
	at vip.joinsun.service.sms.SmsServiceDubboProxy96.$destroy(SmsServiceDubboProxy96.java)
	at org.apache.dubbo.config.utils.SimpleReferenceCache.destroyReference(SimpleReferenceCache.java:266)
	at org.apache.dubbo.config.utils.SimpleReferenceCache.lambda$destroyAll$4(SimpleReferenceCache.java:255)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.apache.dubbo.config.utils.SimpleReferenceCache.destroyAll(SimpleReferenceCache.java:253)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.unreferServices(DefaultModuleDeployer.java:415)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.postDestroy(DefaultModuleDeployer.java:221)
	at org.apache.dubbo.rpc.model.ModuleModel.onDestroy(ModuleModel.java:108)
	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:115)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextClosedEvent(DubboDeployApplicationListener.java:132)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:104)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:47)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1058)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:174)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021)
	at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:145)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:114)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.alibaba.nacos.api.exception.NacosException: Client not connected, current status:SHUTDOWN
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:650)
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:630)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:280)
	... 42 common frames omitted

**Comment by HelloToGithub** [comment]
补充信息：Dubbo3.1.5版本正常

**Comment by mytang0** [comment]
你设置一下重试次数 nacos.retry 和重试间隔时间 nacos.retry-wait；默认值为重试 10 次，间隔 1 秒

**Comment by mytang0** [comment]
3.1 和 3.2 都可以做一下优化，做一下 NamingService 的健康状态检查

**Comment by HelloToGithub** [comment]
> 跟 3.1.5 的区别就是多了失败重试。你设置一下重试次数 nacos.retry 和重试间隔时间 nacos.retry-wait；默认值为重试 10 次，间隔 1 秒

明白。但是现在的场景是点停止 需要点击两次停止才能停止 否则第一次点停止会一直失败重试 是不是执行顺序有问题 既然停止应用了 是不是就不需要去失败重试
![image](https://user-images.githubusercontent.com/15622677/221779445-fd973638-b215-4636-8b8a-db81b2523e3f.png)

**Comment by HelloToGithub** [comment]
> 3.1 和 3.2 都可以做一下优化，做一下 NamingService 的健康状态检查

您的意思是后续版本优化 还是

**Comment by mytang0** [comment]
是的，通过对 NamingService 的健康状态进行检查去判断是否要执行。你是否可以先通过设置 nacos.retry = 1 达到跟 3.1.5 一样的效果。后续版本会优化。

**Comment by HelloToGithub** [comment]
> 

好的。感谢。另外qos-enable 已经设置为false 但是初始化的时候还是true 请问是什么原因
![image](https://user-images.githubusercontent.com/15622677/221793429-bc4c6cf0-2b31-436e-9603-66927d5439c8.png)

![image](https://user-images.githubusercontent.com/15622677/221793345-df384e24-eb52-4468-b721-38732870088d.png)

**Comment by mytang0** [comment]
你的配置文件名叫啥呢？可以试试 **.defaultProperties

**Comment by mytang0** [comment]
配置文件名加上 defaultProperties  试下

**Comment by HelloToGithub** [comment]
DubboDefaultPropertiesEnvironmentPostProcessor 类中setDubboApplicationQosEnableProperty方法 默认初始化了dubbo.application.qos-enable等于true

    private void setDubboApplicationQosEnableProperty(Map<String, Object> defaultProperties) {
        defaultProperties.put(DUBBO_APPLICATION_QOS_ENABLE_PROPERTY, Boolean.TRUE.toString());
    }

**Comment by AlbumenJ** [comment]
这个应该是关闭的时候的时序问题，应该是先 unregister 然后再 shutdown nacos 的 client 的

**Comment by HelloToGithub** [comment]
> 这个应该是关闭的时候的时序问题，应该是先 unregister 然后再 shutdown nacos 的 client 的

好的 那这个问题是等待后续版本修复 还是

**Comment by AlbumenJ** [comment]
> > 这个应该是关闭的时候的时序问题，应该是先 unregister 然后再 shutdown nacos 的 client 的
> 
> 好的 那这个问题是等待后续版本修复 还是

后续版本会修复，这个不影响正常使用

**Comment by AlbumenJ** [comment]
@HelloToGithub 麻烦看一下日志里面是不是有 `after Spring fails to do in time or doesn't do it completely` 的关键字，可能是 Spring Boot 的 shutdown hook 处理超过 Dubbo 的等待时间（10s）了，然后 Dubbo 的也开始关闭

**Comment by HelloToGithub** [comment]
![image](https://user-images.githubusercontent.com/15622677/223392985-fa636312-23eb-4c15-b252-978a68712cf3.png)
没有搜索到相关关键字信息

**Comment by HelloToGithub** [comment]
[error_info.txt](https://github.com/apache/dubbo/files/10908432/error_info.txt)
具体错误信息在error_info.txt 我是从关闭开始的日志记录

**Comment by AlbumenJ** [comment]
看了下日志，是 Dubbo 的 ShutdownHook 和 Spring 的 Shutdown hook 冲突了，在 #10730 中做了 ShutdownHook 的退让，不过是在 3.2 里面的功能。
另外是 Dubbo 侧可以在有并发 destory 的时候进行适当加锁，避免并发处理。

**Comment by HelloToGithub** [comment]
done
