### ISSUE TITLE
dubbo使用triple协议，消费者无法连接到生产者，消费者调用的时候就报错，而且每次启动会有说找不到metadata

### ISSUE THREAD

**Issue by soiz-tor** [apache/dubbo#11718]
jdk：19
dubbo：3.2.0-beta5
dubbo-spring-boot-starter：3.2.0-beta5
注册中心nacos：3.2.0-beta5

生产者配置文件：
```
server.port=8082

spring.application.name=provider

dubbo.application.name=provider
dubbo.registry.address=nacos://192.168.220.128:8848
dubbo.protocol.port=-1
dubbo.provider.protocol=tri
dubbo.application.metadata-type=remote
```
消费者配置文件：
```
server.port=8081

spring.application.name=consumer

dubbo.application.name=consumer
dubbo.registry.address=nacos://192.168.220.128:8848
dubbo.protocol.port=-1
dubbo.consumer.protocol=tri
```
报错信息：
生产者：
```
[DUBBO] The connection of /192.168.189.1:53173 -> /192.168.189.1:50051 is disconnected., dubbo version: 3.2.0-beta.5, current host: 192.168.189.1
 [DUBBO] The connection of /192.168.189.1:53188 -> /192.168.189.1:50051 is disconnected., dubbo version: 3.2.0-beta.5, current host: 192.168.189.1
[DUBBO] The connection of /192.168.189.1:53191 -> /192.168.189.1:50051 is disconnected., dubbo version: 3.2.0-beta.5, current host: 192.168.189.1
```
消费者：
```
org.apache.dubbo.rpc.StatusRpcException: CANCELLED : Canceled by remote peer, errorCode=8
	at org.apache.dubbo.rpc.TriRpcStatus.asException(TriRpcStatus.java:214) ~[dubbo-3.2.0-beta.5.jar:3.2.0-beta.5]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ HTTP POST "/test?username=123" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at org.apache.dubbo.rpc.TriRpcStatus.asException(TriRpcStatus.java:214) ~[dubbo-3.2.0-beta.5.jar:3.2.0-beta.5]
		at org.apache.dubbo.rpc.protocol.tri.call.UnaryClientCallListener.onClose(UnaryClientCallListener.java:51) ~[dubbo-3.2.0-beta.5.jar:3.2.0-beta.5]
		at org.apache.dubbo.rpc.protocol.tri.call.TripleClientCall.onComplete(TripleClientCall.java:110) ~[dubbo-3.2.0-beta.5.jar:3.2.0-beta.5]
		at org.apache.dubbo.rpc.protocol.tri.stream.TripleClientStream$ClientTransportListener.finishProcess(TripleClientStream.java:256) ~[dubbo-3.2.0-beta.5.jar:3.2.0-beta.5]
		at org.apache.dubbo.rpc.protocol.tri.stream.TripleClientStream$ClientTransportListener.lambda$cancelByRemote$3(TripleClientStream.java:475) ~[dubbo-3.2.0-beta.5.jar:3.2.0-beta.5]
		at org.apache.dubbo.common.threadpool.serial.SerializingExecutor.run(SerializingExecutor.java:102) ~[dubbo-common-3.2.0-beta.5.jar:3.2.0-beta.5]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
		at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41) ~[dubbo-common-3.2.0-beta.5.jar:3.2.0-beta.5]
		at java.base/java.lang.Thread.run(Thread.java:1589) ~[na:na]
```

**Comment by yuchang01** [comment]
provider 设置了 `dubbo.application.metadata-type=remote`，先看一下nacos是否有相关元数据，没有就需要开启nacos作为元数据中心。确保元数据已正常上报至元数据 中心

**Comment by yang19999** [comment]
请问解决了吗？

**Comment by gao05111228** [comment]
解决了么，我也是消费方一直报这个问题，我看nacos上配置和服务都已经注册上去了！

**Comment by dgqypl** [comment]
如果是 JDK17，加一下依赖试试：
```xml
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
        </dependency>
```
