### ISSUE TITLE
dubbo 3.1.7 版本  使用triple 协议 当传的参数为null 时，会报一个序列化空指针异常

### ISSUE THREAD

**Issue by xiehongji** [apache/dubbo#11765]
23-03-08 13:54 TripleClientCall  ERROR (Log4j2Logger.java:101) -  [DUBBO] Serialize triple request failed, service=com.keyword.api.KeywordDbService method=org.apache.dubbo.rpc.model.ReflectionMethodDescriptor@33b2e771, dubbo version: 3.1.7, current host: 192.168.2.1, error code: 4-10. This may be caused by , go to https://dubbo.apache.org/faq/4/10 to find instructions. 
java.lang.NullPointerException: null
	at org.apache.dubbo.rpc.protocol.tri.ReflectionPackableMethod$WrapRequestPack.pack(ReflectionPackableMethod.java:393) ~[dubbo-3.1.7.jar:3.1.7]
	at org.apache.dubbo.rpc.model.PackableMethod.packRequest(PackableMethod.java:58) ~[dubbo-3.1.7.jar:3.1.7]
	at org.apache.dubbo.rpc.protocol.tri.call.TripleClientCall.sendMessage(TripleClientCall.java:157) ~[dubbo-3.1.7.jar:3.1.7]
	at org.apache.dubbo.rpc.protocol.tri.observer.ClientCallToObserverAdapter.onNext(ClientCallToObserverAdapter.java:44) ~[dubbo-3.1.7.jar:3.1.7]
	at org.apache.dubbo.rpc.protocol.tri.TripleInvoker.invokeUnary(TripleInvoker.java:221) ~[dubbo-3.1.7.jar:3.1.7]
	at org.apache.dubbo.rpc.protocol.tri.TripleInvoker.doInvoke(TripleInvoker.java:123) ~[dubbo-3.1.7.jar:3.1.7]
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.doInvokeAndReturn(AbstractInvoker.java:222) ~[dubbo-3.1.7.jar:3.1.7]

**Comment by yuchang01** [comment]
同样的问题，已经被修复 https://github.com/apache/dubbo/issues/11648, 等待`3.1.8`发布
