### ISSUE TITLE
dubbo支持JDK17的问题--add-opens

### ISSUE THREAD

**Issue by Skqing** [apache/dubbo#11807]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here

接口调用时异常
### 版本情况

JDK版本：     Alibaba_Dragonwell_Standard_17.0.6.0.6.9_x64_linux
dubbo-spring-boot-starter：3.1.7
dubbo版本： 3.1.7
spring-boot：2.7.9

### 问题描述

1. 复现代码

```java
OrderShopAppClient.shopEmpTicketMoneySum(dataStatReqDTO.getEmpCode()
                            , dataStatReqDTO.getStartTime(), dataStatReqDTO.getEndTime());
```
调用以上接口时在消费端报出异常

dataStatReqDTO：
```java
    private  Date startTime;
    private Date endTime;
```

JDK已添加配置
```
java  --add-opens java.base/java.lang=ALL-UNNAMED  --add-opens java.base/java.util=ALL-UNNAMED  --add-opens java.base/sun.util=ALL-UNNAMED  -jar  -Dspring.profiles.active=dev   /xxxx.jar
```

2. 堆栈信息
```
cause: org.apache.dubbo.remoting.RemotingException: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Unable to make field private int sun.util.calendar.ZoneInfo.rawOffset accessible: module java.base does not "opens sun.util.calendar" to unnamed module @2b80d80f
 Java field: private java.util.TimeZone cn.hutool.core.date.DateTime.timeZone
io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Unable to make field private int sun.util.calendar.ZoneInfo.rawOffset accessible: module java.base does not "opens sun.util.calendar" to unnamed module @2b80d80f
 Java field: private java.util.TimeZone cn.hutool.core.date.DateTime.timeZone
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
        at io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:304)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
        at org.apache.dubbo.remoting.transport.netty4.NettyClientHandler.write(NettyClientHandler.java:88)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
        at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1247)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Unable to make field private int sun.util.calendar.ZoneInfo.rawOffset accessible: module java.base does not "opens sun.util.calendar" to unnamed module @2b80d80f
 Java field: private java.util.TimeZone cn.hutool.core.date.DateTime.timeZone
```

**Comment by AlbumenJ** [comment]
JDK 17 需要 3.2.0 版本才能原生支持。3.1.x 版本可以配置序列化方式为 fastjson2 支持

**Comment by Skqing** [comment]
好的👌

**Comment by Skqing** [comment]
> JDK 17 需要 3.2.0 版本才能原生支持。3.1.x 版本可以配置序列化方式为 fastjson2 支持

改为3.2.0-beta.5依然报错，并且没有发现间接依赖javaassist
```
Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @6979e8cb, dubbo version: 3.2.0-beta.5, current host: 172.18.0.101, error code: 5-36. This may be caused by , go to https://dubbo.apache.org/faq/5/36 to find instructions. 
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @6979e8cb
```

**Comment by Skqing** [comment]
> > > JDK 17 需要 3.2.0 版本才能原生支持。3.1.x 版本可以配置序列化方式为 fastjson2 支持
> > 
> > 
> > 改为3.2.0-beta.5依然报错，并且没有发现间接依赖javaassist
> > ```
> > Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @6979e8cb, dubbo version: 3.2.0-beta.5, current host: 172.18.0.101, error code: 5-36. This may be caused by , go to https://dubbo.apache.org/faq/5/36 to find instructions. 
> > java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @6979e8cb
> > ```
> 
> mvn dependency:tree 看一下，这个报错一般都是 javassist 版本冲突了导致的

搜了一下就这一个依赖
![image](https://user-images.githubusercontent.com/1713001/224877476-44e78314-3614-42f9-9e38-a8164ee15fc3.png)
![image](https://user-images.githubusercontent.com/1713001/224877531-e0a69b6d-59a2-4991-9576-2611b8a308ac.png)

**Comment by AlbumenJ** [comment]
> > > > JDK 17 需要 3.2.0 版本才能原生支持。3.1.x 版本可以配置序列化方式为 fastjson2 支持
> > > 
> > > 
> > > 改为3.2.0-beta.5依然报错，并且没有发现间接依赖javaassist
> > > ```
> > > Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @6979e8cb, dubbo version: 3.2.0-beta.5, current host: 172.18.0.101, error code: 5-36. This may be caused by , go to https://dubbo.apache.org/faq/5/36 to find instructions. 
> > > java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @6979e8cb
> > > ```
> > 
> > 
> > mvn dependency:tree 看一下，这个报错一般都是 javassist 版本冲突了导致的
> 
> 搜了一下就这一个依赖 ![image](https://user-images.githubusercontent.com/1713001/224877476-44e78314-3614-42f9-9e38-a8164ee15fc3.png) ![image](https://user-images.githubusercontent.com/1713001/224877531-e0a69b6d-59a2-4991-9576-2611b8a308ac.png)

其他地方还有这个依赖吗

**Comment by AlbumenJ** [comment]
启动环境是打包后 java -jar 的还是 idea 直接启动

**Comment by Skqing** [comment]
> java -jar

java -jar

**Comment by Skqing** [comment]
> 启动环境是打包后 java -jar 的还是 idea 直接启动

java -jar 方式启动

**Comment by Skqing** [comment]
这是打包后的jar包打开后里面的依赖
![image](https://user-images.githubusercontent.com/1713001/224887386-cc4fc37b-8b84-482c-907e-37ff117df439.png)

**Comment by Skqing** [comment]
还是要加上--add-opens java.base/java.lang=ALL-UNNAMED这个才能调用成功了

**Comment by Skqing** [comment]
感觉还是没完全支持JDK17啊

**Comment by AlbumenJ** [comment]
`Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass` 
这个的完整堆栈发一下

**Comment by AlbumenJ** [comment]
目前 Dubbo 的所有 UT 已经在 JDK17 不加 add-opens 跑通了，部分集成测试用例（限于spring版本依赖问题）已经改造完在 JDK17 下原生测试通过了

**Comment by Skqing** [comment]
```
 Tried 3 times of the providers [172.18.0.103:20880] (1/1) from the registry 172.18.0.100:8848 on the consumer 172.18.0.101 using the dubbo version 3.2.0-beta.5. Last error is: Failed to invoke remote method: getMoneyAndUserStat, provider: DefaultServiceInstance{serviceName='lot-oto-account', host='172.18.0.103', port=20880, enabled=true, healthy=true, metadata={dubbo.metadata-service.url-params={"cluster":"failfast","connections":"1","loadbalance":"leastactive","timeout":"6000","version":"1.0.0","dubbo":"2.0.2","release":"3.1.7","side":"provider","port":"20880","protocol":"dubbo"}, dubbo.endpoints=[{"port":20880,"protocol":"dubbo"}], dubbo.metadata.revision=a72e5fe40401f7b9f0d302f0dd1cd800, dubbo.metadata.storage-type=local, timestamp=1678759779693}}, service{name='com.xxxt.IAccountShopAppClient',group='null',version='null',protocol='dubbo',port='20880',params={cluster=failfast, side=provider, release=3.1.7, methods=withdrawXXX, logger=log4j2, deprecated=false, dubbo=2.0.2, loadbalance=leastactive, interface=com.xxxx.client.IAccountShopAppClient, service-name-mapping=true, timeout=6000, generic=false, retries=0, environment=test, delay=2000, application=lot-oto-account, background=false, organization=sz-oto, dynamic=true, dump.directory=/home/logs/dubbo, anyhost=true},}, cause: Failed to send message Request [id=1411, version=2.0.2, twoWay=true, event=false, broken=false, data=null] to /172.18.0.103:20880, cause: Unable to make field private int sun.util.calendar.ZoneInfo.rawOffset accessible: module java.base does not "opens sun.util.calendar" to unnamed module @2b80d80f
 Java field: private java.util.TimeZone
```

消费者和生产者的版本都是3.2.0-bate.5为啥调用的异常日志里还是3.1.7，是有缓存吗？我们用的是nacos
![image](https://user-images.githubusercontent.com/1713001/224926644-74eb904c-e6d1-475f-9c7c-d6f0d4ff60dc.png)

**Comment by AlbumenJ** [comment]
172.18.0.103 检查一下这个机器的代码，这个是和 3.1.x 互通，走了 fallback 逻辑了

**Comment by Skqing** [comment]
现在成日志是这样，但还是报错
```
java.util.concurrent.ExecutionException: org.apache.dubbo.rpc.RpcException: Failed to invoke the method queryTicketIncomeAndPay in the service com.san.xxx.shop.client.IShopFeeDetailClient. Tried 3 times of the providers [172.18.0.104:20880] (1/1) from the registry 172.18.0.100:8848 on the consumer 172.18.0.101 using the dubbo version 3.2.0-beta.5. Last error is: Failed to invoke remote method: queryTicketIncomeAndPay, provider: DefaultServiceInstance{serviceName='lot-oto-shop', host='172.18.0.104', port=20880, enabled=true, healthy=true, metadata={dubbo.metadata-service.url-params={"cluster":"failfast","connections":"1","loadbalance":"leastactive","timeout":"6000","version":"1.0.0","dubbo":"2.0.2","release":"3.1.7","side":"provider","port":"20880","protocol":"dubbo"}, dubbo.endpoints=[{"port":20880,"protocol":"dubbo"}], dubbo.metadata.revision=c93040e0956dd2e076a4bffe68020fa6, dubbo.metadata.storage-type=local, timestamp=1678781404845}}, service{name='com.san.xxx.shop.client.IShopFeeDetailClient',group='null',version='null',protocol='dubbo',port='20880',params={cluster=failfast, side=provider, release=3.1.7, methods=queryList,queryShopTicketIncome,queryTicketIncomeAndPay,queryTicketServiceFeeList, logger=log4j2, deprecated=false, dubbo=2.0.2, loadbalance=leastactive, interface=com.san.xxx.shop.client.IShopFeeDetailClient, service-name-mapping=true, timeout=6000, generic=false, retries=0, environment=test, delay=2000, application=lot-oto-shop, background=false, organization=sz-oto, dynamic=true, dump.directory=/home/logs/dubbo, anyhost=true},}, cause: Failed to send message Request [id=204, version=2.0.2, twoWay=true, event=false, broken=false, data=null] to /172.18.0.104:20880, cause: Unable to make field private int sun.util.calendar.ZoneInfo.rawOffset accessible: module java.base does not "opens sun.util.calendar" to unnamed module @2b80d80f
 Java field: private java.util.TimeZone cn.hutool.core.date.DateTime.timeZone
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
        at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
        at com.san.xxx.gateway.controller.shop.SpDataStatController.query(SpDataStatController.java:215) ~[classes!/:?]
        at com.san.xxx.gateway.controller.shop.SpDataStatController$$FastClassBySpringCGLIB$$91e1c0a3.invoke(<generated>) ~[classes!/:?]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.25.jar!/:5.3.25]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.25.jar!/:5.3.25]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.25.jar!/:5.3.25]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.25.jar!/:5.3.25]
        at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:58) ~[spring-aop-5.3.25.jar!/:5.3.25]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.3.25.jar!/:5.3.25]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.25.jar!/:5.3.25]
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) ~[spring-aop-5.3.25.jar!/:5.3.25]
        at com.san.xxx.gateway.aspect.RequestLogAspect.doAround(RequestLogAspect.java:93) ~[classes!/:?]
        at jdk.internal.reflect.GeneratedMethodAccessor278.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634) ~[spring-aop-5.3.25.jar!/:5.3.25]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624) ~[spring-aop-5.3.25.jar!/:5.3.25]
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72) ~[spring-aop-5.3.25.jar!/:5.3.25]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.3.25.jar!/:5.3.25]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.25.jar!/:5.3.25]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.25.jar!/:5.3.25]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.25.jar!/:5.3.25]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.25.jar!/:5.3.25]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.25.jar!/:5.3.25]
        at com.san.xxx.gateway.controller.shop.SpDataStatController$$EnhancerBySpringCGLIB$$a0845d8b.query(<generated>) ~[classes!/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.25.jar!/:5.3.25]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.25.jar!/:5.3.25]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.25.jar!/:5.3.25]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.25.jar!/:5.3.25]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.25.jar!/:5.3.25]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.25.jar!/:5.3.25]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071) ~[spring-webmvc-5.3.25.jar!/:5.3.25]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964) ~[spring-webmvc-5.3.25.jar!/:5.3.25]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.25.jar!/:5.3.25]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.25.jar!/:5.3.25]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:696) ~[tomcat-embed-core-9.0.71.jar!/:4.0.4]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.25.jar!/:5.3.25]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[tomcat-embed-core-9.0.71.jar!/:4.0.4]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at com.san.xxx.gateway.filter.ApiRequestFilter.doFilter(ApiRequestFilter.java:39) ~[classes!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.25.jar!/:5.3.25]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.25.jar!/:5.3.25]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.25.jar!/:5.3.25]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.25.jar!/:5.3.25]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) ~[spring-boot-actuator-2.7.9.jar!/:2.7.9]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.25.jar!/:5.3.25]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.25.jar!/:5.3.25]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.25.jar!/:5.3.25]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.71.jar!/:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
这是104的依赖，好像也没问题
![image](https://user-images.githubusercontent.com/1713001/224942768-9f6f228d-bc21-4740-ba17-ff8c0ebaa079.png)
![image](https://user-images.githubusercontent.com/1713001/224942873-798ba6ee-696d-4a90-9d01-73c761ded2cc.png)

**Comment by Skqing** [comment]
应该是有缓存导致的，现在不加 add-opens可以了。
