### ISSUE TITLE
dubbo从2.7.7 升级到2.7.22 ，no provider

### ISSUE THREAD

**Issue by tang147** [apache/dubbo#11839]
Caused by: org.apache.dubbo.remoting.RemotingException: client(url: dubbo://172.16.0.82:16889/com.qihoo.finance.traffic.facade.TrafficRoleDataAuthFacade?anyhost=true&application=traffic-web&check=false&codec=dubbo&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&heartbeat=60000&init=false&interface=com.qihoo.finance.traffic.facade.TrafficRoleDataAuthFacade&metadata-type=remote&methods=save,getDataAuth,getAppCodeByRoleGroup&pid=24996&qos.enable=false&register.ip=10.93.32.7&release=2.7.7&remote.application=traffic-config-center&revision=1.27.1-SNAPSHOT&service.filter=-dubboTraceProvider&side=consumer&sticky=false&timeout=60000&timestamp=1677225540293) failed to connect to server /172.16.0.82:16889 client-side timeout 3000ms (elapsed: 3003ms) from netty client 10.93.32.7 using dubbo version 2.7.22
	at org.apache.dubbo.remoting.transport.netty4.NettyClient.doConnect(NettyClient.java:182)
	at org.apache.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:198)
	at org.apache.dubbo.remoting.transport.AbstractClient.send(AbstractClient.java:174)
	at org.apache.dubbo.remoting.transport.AbstractPeer.send(AbstractPeer.java:53)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeChannel.request(HeaderExchangeChannel.java:137)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeClient.request(HeaderExchangeClient.java:95)
	at org.apache.dubbo.rpc.protocol.dubbo.ReferenceCountExchangeClient.request(ReferenceCountExchangeClient.java:93)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:108)
	... 57 more

**Comment by tang147** [comment]
问题已经解决,看了源码，dubbo扫描类需要在启动类的时候指定，不能通过apollo配置了
在启动类加上 @EnableDubbo(scanBasePackages = "com.qihoo.finance.traffic.core.provider") 这个即可
