### ISSUE TITLE
graalvm编译产物，无法运行dubbo

### ISSUE THREAD

**Issue by kingsant** [apache/dubbo#11988]
### Environment

* Dubbo version: 3.2.0-beta.6
* Operating System version: linux
* Java version: graalvm jdk 17

### Steps to reproduce this issue

1. graalvm编译的产物报错，
竟然会提示重复bean， 这也太坑了

If there is an exception, please attach the exception trace:

```
46 [main] INFO com.sycloud.aa.basis.base.manager.providerimpl.StartServiceProvider - Starting AOT-processed StartServiceProvider using Java 17.0.6 with PID 31905 (/disk/code/base3/target/spring-native-demo started by root in /disk/code/base3/target)
46 [main] INFO com.sycloud.aa.basis.base.manager.providerimpl.StartServiceProvider - The following 1 profile is active: "@profile.active@"
62 [main] WARN org.springframework.core.io.support.PathMatchingResourcePatternResolver - Failed to search in directory [/com/sycloud/aa/basis/base/core/dao] for files matching pattern [**/*.class]: java.nio.file.NoSuchFileException: /com/sycloud/aa/basis/base/core/dao
62 [main] WARN org.mybatis.spring.mapper.ClassPathMapperScanner - No MyBatis mapper was found in '[com.sycloud.aa.basis.base.core.dao]' package. Please check your configuration.
62 [main] INFO org.apache.dubbo.config.spring.beans.factory.annotation.ServiceAnnotationPostProcessor -  [DUBBO] BeanNameGenerator bean can't be found in BeanFactory with name [org.springframework.context.annotation.internalConfigurationBeanNameGenerator], dubbo version: 3.2.0-beta.6, current host: 10.54.67.140
62 [main] INFO org.apache.dubbo.config.spring.beans.factory.annotation.ServiceAnnotationPostProcessor -  [DUBBO] BeanNameGenerator will be a instance of org.springframework.context.annotation.AnnotationBeanNameGenerator , it maybe a potential problem on bean name generation., dubbo version: 3.2.0-beta.6, current host: 10.54.67.140
65 [main] INFO org.apache.dubbo.config.spring.beans.factory.annotation.ServiceAnnotationPostProcessor -  [DUBBO] Found 7 classes annotated by Dubbo @Service under package [com.sycloud.aa.basis.base.manager.providerimpl.chief]: [com.sycloud.aa.basis.base.manager.providerimpl.chief.common.BaseAdminAreaProviderImpl, com.sycloud.aa.basis.base.manager.providerimpl.chief.common.BaseAttachmentProviderImpl, com.sycloud.aa.basis.base.manager.providerimpl.chief.common.BaseDataDictProviderImpl, com.sycloud.aa.basis.base.manager.providerimpl.chief.common.BaseFeedbackProviderImpl, com.sycloud.aa.basis.base.manager.providerimpl.chief.common.CommonMapPartitionProviderImpl, com.sycloud.aa.basis.base.manager.providerimpl.chief.soldier.BaseSoldierOuterLoginAccountProviderImpl, com.sycloud.aa.basis.base.manager.providerimpl.chief.soldier.BaseSoldierProviderImpl], dubbo version: 3.2.0-beta.6, current host: 10.54.67.140
67 [main] ERROR org.apache.dubbo.config.spring.beans.factory.annotation.ServiceAnnotationPostProcessor -  [DUBBO] Found duplicated BeanDefinition of service interface [com.sycloud.aa.basis.base.infra.provider.api.common.BaseAdminAreaProvider] with bean name [ServiceBean:com.sycloud.aa.basis.base.infra.provider.api.common.BaseAdminAreaProvider::], existing definition [ Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null], new definition [Root bean: class [org.apache.dubbo.config.spring.ServiceBean]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null], dubbo version: 3.2.0-beta.6, current host: 10.54.67.140, error code: 5-30. This may be caused by , go to https://dubbo.apache.org/faq/5/30 to find instructions. 
67 [main] WARN org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'ServiceBean:com.sycloud.aa.basis.base.infra.provider.api.common.BaseAdminAreaProvider::' defined in null: Found duplicated BeanDefinition of service interface [com.sycloud.aa.basis.base.infra.provider.api.common.BaseAdminAreaProvider] with bean name [ServiceBean:com.sycloud.aa.basis.base.infra.provider.api.common.BaseAdminAreaProvider::], existing definition [ Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null], new definition [Root bean: class [org.apache.dubbo.config.spring.ServiceBean]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null]
68 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'ServiceBean:com.sycloud.aa.basis.base.infra.provider.api.common.BaseAdminAreaProvider::' defined in null: Found duplicated BeanDefinition of service interface [com.sycloud.aa.basis.base.infra.provider.api.common.BaseAdminAreaProvider] with bean name [ServiceBean:com.sycloud.aa.basis.base.infra.provider.api.common.BaseAdminAreaProvider::], existing definition [ Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null], new definition [Root bean: class [org.apache.dubbo.config.spring.ServiceBean]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ServiceAnnotationPostProcessor.registerServiceBeanDefinition(ServiceAnnotationPostProcessor.java:597)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ServiceAnnotationPostProcessor.processScannedBeanDefinition(ServiceAnnotationPostProcessor.java:347)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ServiceAnnotationPostProcessor.scanServiceBeans(ServiceAnnotationPostProcessor.java:237)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ServiceAnnotationPostProcessor.postProcessBeanDefinitionRegistry(ServiceAnnotationPostProcessor.java:155)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:344)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:145)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:747)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:565)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293)
	at com.sycloud.aa.basis.base.manager.providerimpl.StartServiceProvider.main(StartServiceProvider.java:30)

```

**Comment by aamingaa** [comment]
按这个文档操作的吗https://dubbo.apache.org/zh-cn/overview/mannual/java-sdk/advanced-features-and-usage/performance/support-graalvm/

**Comment by CrazyHZM** [comment]
@kingsant In the graalvm scenario, support for annotations and xml is already under planning, and is expected to be provided in a certain version of 3.2.x.
@aamingaa The document is a bit old, it will be updated in the near future.

**Comment by kingsant** [comment]
@CrazyHZM  我通过修改dubbo的源码，然后上面bean重复修复后， 还会出现段错误的问题，这可能和netty使用堆外内存有关，到时候看下哈~
