### ISSUE TITLE
引入dubbo3.2.0-beta.的包之后，在进行springboot单元测试时会报错

### ISSUE THREAD

**Issue by wang-laoshi** [apache/dubbo#12025]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.0-beta.6
* Operating System version: macos
* Java version: 17
* SpringBoot version: 3.0.4

### Steps to reproduce this issue

1. 创建一个springboot3的项目，使用junit+springtest进行单元测试，加载了springboot环境
2. 测试内容与dubbo无关
3. 整个工程中除了引入dubbo的包以外，没有任何跟dubbo有关的内容
没有使用EnableDubbo引入dubbo相关依赖，也没有配置dubbo-config.xml
项目代码中没有任何跟dubbo有关的配置

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior
单元测试通过

### Actual Behavior
单元测试通过，但是控制台报错了。
如果去掉的dubbo的包，则没有报错，因此判断仅仅是dubbo引包的问题
引入的三个包分别是
```
<dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-registry-nacos</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-configcenter-nacos</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
        </dependency>
```

If there is an exception, please attach the exception trace:

```
2023-04-06T16:28:56.605+08:00 ERROR 38733 --- [ionShutdownHook] o.a.d.common.deploy.AbstractDeployer     :  [DUBBO] Dubbo Application[1.0](DUBBO_INTERNAL_APPLICATION) an exception occurred when handle stopping event, dubbo version: 3.2.0-beta.6, current host: 10.7.7.2, error code: 0-14. This may be caused by , go to https://dubbo.apache.org/faq/0/14 to find instructions. 

java.lang.NullPointerException: Cannot invoke "org.apache.dubbo.security.cert.DubboCertManager.disConnect()" because "this.dubboCertManager" is null
	at org.apache.dubbo.security.cert.CertDeployerListener.onStopping(CertDeployerListener.java:52) ~[dubbo-3.2.0-beta.6.jar:3.2.0-beta.6]
	at org.apache.dubbo.security.cert.CertDeployerListener.onStopping(CertDeployerListener.java:25) ~[dubbo-3.2.0-beta.6.jar:3.2.0-beta.6]
	at org.apache.dubbo.common.deploy.AbstractDeployer.setStopping(AbstractDeployer.java:132) ~[dubbo-common-3.2.0-beta.6.jar:3.2.0-beta.6]
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.onStopping(DefaultApplicationDeployer.java:1125) ~[dubbo-3.2.0-beta.6.jar:3.2.0-beta.6]
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.preDestroy(DefaultApplicationDeployer.java:902) ~[dubbo-3.2.0-beta.6.jar:3.2.0-beta.6]
	at org.apache.dubbo.rpc.model.ApplicationModel.onDestroy(ApplicationModel.java:150) ~[dubbo-common-3.2.0-beta.6.jar:3.2.0-beta.6]
	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:116) ~[dubbo-common-3.2.0-beta.6.jar:3.2.0-beta.6]
	at org.apache.dubbo.rpc.model.FrameworkModel.onDestroy(FrameworkModel.java:121) ~[dubbo-common-3.2.0-beta.6.jar:3.2.0-beta.6]
	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:116) ~[dubbo-common-3.2.0-beta.6.jar:3.2.0-beta.6]
	at org.apache.dubbo.rpc.model.FrameworkModel.tryDestroy(FrameworkModel.java:280) ~[dubbo-common-3.2.0-beta.6.jar:3.2.0-beta.6]
	at org.apache.dubbo.rpc.model.ApplicationModel.onDestroy(ApplicationModel.java:187) ~[dubbo-common-3.2.0-beta.6.jar:3.2.0-beta.6]
	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:116) ~[dubbo-common-3.2.0-beta.6.jar:3.2.0-beta.6]
	at org.apache.dubbo.rpc.model.ApplicationModel.tryDestroy(ApplicationModel.java:266) ~[dubbo-common-3.2.0-beta.6.jar:3.2.0-beta.6]
	at org.apache.dubbo.rpc.model.ModuleModel.onDestroy(ModuleModel.java:131) ~[dubbo-common-3.2.0-beta.6.jar:3.2.0-beta.6]
	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:116) ~[dubbo-common-3.2.0-beta.6.jar:3.2.0-beta.6]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextClosedEvent(DubboDeployApplicationListener.java:132) ~[dubbo-3.2.0-beta.6.jar:3.2.0-beta.6]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:104) ~[dubbo-3.2.0-beta.6.jar:3.2.0-beta.6]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:47) ~[dubbo-3.2.0-beta.6.jar:3.2.0-beta.6]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-6.0.6.jar:6.0.6]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-6.0.6.jar:6.0.6]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-6.0.6.jar:6.0.6]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413) ~[spring-context-6.0.6.jar:6.0.6]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370) ~[spring-context-6.0.6.jar:6.0.6]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1036) ~[spring-context-6.0.6.jar:6.0.6]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1003) ~[spring-context-6.0.6.jar:6.0.6]
	at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:139) ~[spring-boot-3.0.4.jar:3.0.4]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:108) ~[spring-boot-3.0.4.jar:3.0.4]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

**Comment by MieAh** [comment]
这个问题将在下个版本修复

**Comment by MieAh** [comment]
related to #11800

**Comment by wang-laoshi** [comment]
> related to #11800

环境：springboot3+jdk17
因此需要使用dubbo3.2.0-beta.6版本
