### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "org.apache.dubbo.security.cert.DubboCertManager.disConnect()" because "this.dubboCertManager" is null

### ISSUE THREAD

**Issue by lbhfuture** [apache/dubbo#12090]
- [ x ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.0-beta.6
* Operating System version: k8s
* Java version: OpenJDK 17

### Steps to reproduce this issue
k8s 滚动更新，停止的时候报错，导致 pod 一直无法销毁
```plain
2023-04-14T12:27:35.358+08:00  INFO 1 --- [           main] o.apache.dubbo.rpc.model.FrameworkModel  :  [DUBBO] Destroying default framework model: Dubbo Framework[1], dubbo version: 3.2.0-beta.6, current host: 10.244.4.96
2023-04-14T12:27:35.358+08:00  INFO 1 --- [           main] o.apache.dubbo.rpc.model.FrameworkModel  :  [DUBBO] Dubbo Framework[1] is destroying ..., dubbo version: 3.2.0-beta.6, current host: 10.244.4.96
2023-04-14T12:27:35.358+08:00 ERROR 1 --- [           main] o.a.d.common.deploy.AbstractDeployer     :  [DUBBO] Dubbo Application[1.0](DUBBO_INTERNAL_APPLICATION) an exception occurred when handle stopping event, dubbo version: 3.2.0-beta.6, current host: 10.244.4.96, error code: 0-14. This may be caused by , go to https://dubbo.apache.org/faq/0/14 to find instructions. 

java.lang.NullPointerException: Cannot invoke "org.apache.dubbo.security.cert.DubboCertManager.disConnect()" because "this.dubboCertManager" is null
	at org.apache.dubbo.security.cert.CertDeployerListener.onStopping(CertDeployerListener.java:52) ~[dubbo-3.2.0-beta.6.jar!/:3.2.0-beta.6]
	at org.apache.dubbo.security.cert.CertDeployerListener.onStopping(CertDeployerListener.java:25) ~[dubbo-3.2.0-beta.6.jar!/:3.2.0-beta.6]
	at org.apache.dubbo.common.deploy.AbstractDeployer.setStopping(AbstractDeployer.java:132) ~[dubbo-3.2.0-beta.6.jar!/:3.2.0-beta.6]
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.onStopping(DefaultApplicationDeployer.java:1125) ~[dubbo-3.2.0-beta.6.jar!/:3.2.0-beta.6]
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.preDestroy(DefaultApplicationDeployer.java:902) ~[dubbo-3.2.0-beta.6.jar!/:3.2.0-beta.6]
	at org.apache.dubbo.rpc.model.ApplicationModel.onDestroy(ApplicationModel.java:150) ~[dubbo-3.2.0-beta.6.jar!/:3.2.0-beta.6]
	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:116) ~[dubbo-3.2.0-beta.6.jar!/:3.2.0-beta.6]
	at org.apache.dubbo.rpc.model.FrameworkModel.onDestroy(FrameworkModel.java:121) ~[dubbo-3.2.0-beta.6.jar!/:3.2.0-beta.6]
	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:116) ~[dubbo-3.2.0-beta.6.jar!/:3.2.0-beta.6]
	at org.apache.dubbo.rpc.model.FrameworkModel.tryDestroy(FrameworkModel.java:280) ~[dubbo-3.2.0-beta.6.jar!/:3.2.0-beta.6]
	at org.apache.dubbo.rpc.model.ApplicationModel.onDestroy(ApplicationModel.java:187) ~[dubbo-3.2.0-beta.6.jar!/:3.2.0-beta.6]
	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:116) ~[dubbo-3.2.0-beta.6.jar!/:3.2.0-beta.6]
	at org.apache.dubbo.rpc.model.ApplicationModel.tryDestroy(ApplicationModel.java:266) ~[dubbo-3.2.0-beta.6.jar!/:3.2.0-beta.6]
	at org.apache.dubbo.rpc.model.ModuleModel.onDestroy(ModuleModel.java:131) ~[dubbo-3.2.0-beta.6.jar!/:3.2.0-beta.6]
	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:116) ~[dubbo-3.2.0-beta.6.jar!/:3.2.0-beta.6]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextClosedEvent(DubboDeployApplicationListener.java:132) ~[dubbo-3.2.0-beta.6.jar!/:3.2.0-beta.6]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:104) ~[dubbo-3.2.0-beta.6.jar!/:3.2.0-beta.6]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:47) ~[dubbo-3.2.0-beta.6.jar!/:3.2.0-beta.6]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-6.0.7.jar!/:6.0.7]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-6.0.7.jar!/:6.0.7]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-6.0.7.jar!/:6.0.7]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413) ~[spring-context-6.0.7.jar!/:6.0.7]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370) ~[spring-context-6.0.7.jar!/:6.0.7]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1036) ~[spring-context-6.0.7.jar!/:6.0.7]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:173) ~[spring-boot-3.0.5.jar!/:3.0.5]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1003) ~[spring-context-6.0.7.jar!/:6.0.7]
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:788) ~[spring-boot-3.0.5.jar!/:3.0.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:323) ~[spring-boot-3.0.5.jar!/:3.0.5]
	at com.niudaji.framework.boot.common.NiudajiApplication.run(NiudajiApplication.java:44) ~[niudaji-boot-common-1.0.0-SNAPSHOT.jar!/:na]
	at com.niudaji.collaboration.authority.AuthorityEntryApplication.main(AuthorityEntryApplication.java:23) ~[classes!/:1.0.0-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[authority-entry.jar:1.0.0-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[authority-entry.jar:1.0.0-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[authority-entry.jar:1.0.0-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[authority-entry.jar:1.0.0-SNAPSHOT]

```
查看 https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/faq/0/14/ 的说明说是自定义 MonitorFactory 报错了，事实上我们没有自定义 MonitorFactory。
使用的 k8s 部署，nacos 注册中心，请问是什么原因导致的？
Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by MieAh** [comment]
这个问题在下个最新版本会被修复

**Comment by AlbumenJ** [comment]
Please try 3.2.0
