### ISSUE TITLE
接口可以访问通，返回有异常

### ISSUE THREAD

**Issue by Notailli** [apache/dubbo#12091]
dubbo版本 2.65 

```
@Component
@Service(version = "1.0.0",group = "dev")
public class SayHelloImpl implements SayHelloService {
    @Override
    public String sayHello(String name){
        System.out.println("----------------Hello " + name);
        return "Hello " + name;
    }
}
```
```
2023-04-14 09:35:16.779  WARN 1 --- [ver worker #1-2] c.a.d.remoting.transport.AbstractServer  :  [DUBBO] All clients has discontected from /172.31.67.164:20880. You can graceful shutdown now., dubbo version: 2.6.0, current host: 172.31.67.164
2023-04-14 09:35:16.780  INFO 1 --- [:20880-thread-7] c.a.d.rpc.protocol.dubbo.DubboProtocol   :  [DUBBO] disconected from /172.31.67.161:54208,url:dubbo://172.31.67.164:20880/com.xiaobai.api.service.SayHelloService?anyhost=true&application=provider&bind.ip=172.31.67.164&bind.port=20880&channel.readonly.sent=true&codec=dubbo&dubbo=2.6.0&generic=false&group=dev&heartbeat=60000&interface=com.xiaobai.api.service.SayHelloService&methods=sayHello&pid=1&revision=0.0.1-SNAPSHOT&side=provider&timestamp=1681435335330&version=1.0.0, dubbo version: 2.6.0, current host: 172.31.67.164
2023-04-14 09:35:16.781  WARN 1 --- [:20880-thread-6] c.a.d.r.t.d.ChannelEventRunnable         :  [DUBBO] ChannelEventRunnable handle RECEIVED operation error, channel is NettyChannel [channel=[id: 0x79b1659e, /172.31.67.161:54208 :> /172.31.67.164:20880]], message is Request [id=13, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=$invoke, parameterTypes=[class java.lang.String, class [Ljava.lang.String;, class [Ljava.lang.Object;], arguments=[sayHello, [Ljava.lang.String;@7641b1d1, [Ljava.lang.Object;@727e3bc1], attachments={x-envoy-internal=true, x-request-id=8f75f258-8c5c-4e68-a499-32d354b57283, x-forwarded-proto=http, dubbo=2.7.1, x-forwarded-for=192.168.90.171, version=1.0.0, accept=*/*, path=com.xiaobai.api.service.SayHelloService, input=503, :method=GET, :scheme=http, :path=/dubbo/hello?name=kk, x-envoy-decorator-operation=dubbo-provider-nacos.test.svc.cluster.local:20880/dubbo/*, :authority=test.mcp.cn, group=dev, user-agent=curl/7.29.0}]], dubbo version: 2.6.0, current host: 172.31.67.164

com.alibaba.dubbo.remoting.RemotingException: Failed to send message Response [id=13, version=2.0.0, status=20, event=false, error=null, result=RpcResult [result=Hello kk, exception=null]] to /172.31.67.161:54208, cause: null
        at com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send(NettyChannel.java:106) ~[dubbo-2.6.0.jar!/:2.6.0]
        at com.alibaba.dubbo.remoting.transport.AbstractPeer.send(AbstractPeer.java:52) ~[dubbo-2.6.0.jar!/:2.6.0]
        at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:169) ~[dubbo-2.6.0.jar!/:2.6.0]
        at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:50) ~[dubbo-2.6.0.jar!/:2.6.0]
        at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:79) ~[dubbo-2.6.0.jar!/:2.6.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_301]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_301]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_301]
Caused by: java.nio.channels.ClosedChannelException: null
        at org.jboss.netty.channel.socket.nio.NioWorker.cleanUpWriteBuffer(NioWorker.java:643) ~[netty-3.2.5.Final.jar!/:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.writeFromUserCode(NioWorker.java:370) ~[netty-3.2.5.Final.jar!/:na]
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:137) ~[netty-3.2.5.Final.jar!/:na]
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:76) ~[netty-3.2.5.Final.jar!/:na]
        at org.jboss.netty.channel.Channels.write(Channels.java:632) ~[netty-3.2.5.Final.jar!/:na]
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:70) ~[netty-3.2.5.Final.jar!/:na]
        at com.alibaba.dubbo.remoting.transport.netty.NettyHandler.writeRequested(NettyHandler.java:98) ~[dubbo-2.6.0.jar!/:2.6.0]
        at org.jboss.netty.channel.Channels.write(Channels.java:611) ~[netty-3.2.5.Final.jar!/:na]
        at org.jboss.netty.channel.Channels.write(Channels.java:578) ~[netty-3.2.5.Final.jar!/:na]
        at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:251) ~[netty-3.2.5.Final.jar!/:na]
        at com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send(NettyChannel.java:96) ~[dubbo-2.6.0.jar!/:2.6.0]
        ... 7 common frames omitted

```

**Comment by AlbumenJ** [comment]
Please try upgrade to 3.1.9. 2.6.x is not longer supported now.
