### ISSUE TITLE
dubbo3使用docker部署消费者会找不到生产者

### ISSUE THREAD

**Issue by baozi-2019** [apache/dubbo#12224]
dubbo 2.x使用下列配置可以正常运行，dubbo3使用下列配置注册中心总是找错ip。网络模式改成host，注册中心ip也是现实不对的

dubbo 消费者配置
```yml
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  registry:
    address: nacos://ip:port
    parameters:
      namespace: xxx
      group: xxx
    register: false
    subscribe: true
  protocol:
    name: dubbo
    port: 20881
  consumer:
    timeout: 3000000
    # 不检查提供者是否存在
    check: false
    validation: parameterValidation
    version: 1.0
    group: BAP
```

docker compose 文件
```yml
version: "3.9"
services:
  management-service:
    image: xx:2.0.0
    container_name: management-service
    environment:
      DUBBO_IP_TO_REGISTRY: 192.168.0.155
      DUBBO_PORT_TO_REGISTRY: 20881
      TZ: Asia/Shanghai
    ports:
      - "8081:8081"
      - "20881:20881"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 450M
      # restart_policy:
      #   condition: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "5"
```

服务日志
```log
2023-05-03 19:57:34.228 ERROR --- [main] org.springframework.boot.SpringApplication : Application run failed java.lang.IllegalStateException: Failed to check the status of the service com.baozi.user.api.IUserOuterService. No provider available for the service BAP/com.baozi.user.api.IUserOuterService:1.0 from the url consumer://172.18.0.1/com.baozi.user.api.IUserOuterService?application=BAP-management-service&background=false&check=true&dubbo=2.0.2&executor-management-mode=isolation&file-cache=true&group=BAP&interface=com.baozi.user.api.IUserOuterService&methods=add,checkPassword,delete,getUserAllInfoByUserId,getUserList,getUserRolesAndPermissions,queryUserByAccount,queryUserByUsername,update&pid=1&qos.enable=false&register.ip=172.18.0.1&release=3.2.0&revision=1.0&side=consumer&sticky=false&timeout=3000&timestamp=1683115034289&unloadClusterRelated=false&validation=parameterValidation&version=1.0 to the consumer 172.18.0.1 use dubbo version 3.2.0
        at org.apache.dubbo.config.ReferenceConfig.checkInvokerAvailable(ReferenceConfig.java:640)
        at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:304)
        at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:231)
        at org.apache.dubbo.config.utils.SimpleReferenceCache.destroyReference(SimpleReferenceCache.java:265)
        at org.apache.dubbo.config.utils.SimpleReferenceCache.destroy(SimpleReferenceCache.java:218)
        at org.apache.dubbo.config.utils.SimpleReferenceCache.destroy(SimpleReferenceCache.java:242)
        at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:414)
        at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780)
        at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:389)
        at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:170)
        at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:142)
        at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:113)
        at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:102)
        at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:47)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:587)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291)
        at com.baozi.management.ManagementServiceApp.main(ManagementServiceApp.java:14)
```

**Comment by baozi-2019** [comment]
dubbo3读取ip方式改变了？我的生产者部署网络模式用的是host，之前自己会读取宿主机ip，现在读取的还是docker内的ip，加上环境变量指定ip端口就可以用了

**Comment by AlbumenJ** [comment]
我们建议使用 Docker 部署的应用：
1. 通过环境变量显式指定 IP 去注册
2. 升级到 Kubernetes 等调度平台自动管理网络
