### ISSUE TITLE
springcloud gateway + nacos访问微服务出现invalid version format: UNSUPPORTED！

### ISSUE THREAD

**Issue by sxqem** [apache/dubbo#12253]
* Dubbo version: 3.2.0
* Operating System version: windows 11
* Java version: 17

### Steps to reproduce this issue
```
2023-05-07 19:51:18.986 [ERROR] [o.s.b.a.w.r.error.AbstractErrorWebExceptionHandler : 102]
				- [48396b42-2]  500 Server Error for HTTP GET "/api/v1/xxxx"
java.lang.IllegalArgumentException: invalid version format: UNSUPPORTED
	at io.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:123)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP GET "/api/v1/xxxx" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at io.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:123)
		at io.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:85)
		at io.netty.handler.codec.http.HttpResponseDecoder.createMessage(HttpResponseDecoder.java:155)
		at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:277)
		at io.netty.handler.codec.http.HttpClientCodec$Decoder.decode(HttpClientCodec.java:239)
		at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
		at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:833)
```

我调试了一下，貌似服务返回的是HTTP2.0,导致netty的HttpVersion验证不通过，HttpVersion只支持到1.1，这个有办法解决吗？还是有什么配置可以处理？

**Comment by syltr** [comment]
这个问题有什么解决办法吗?这个校验很频繁，会导致内存空间上涨的速度很快，100G一天就满了

**Comment by syltr** [comment]
参考issues:12145已解决（https://github.com/apache/dubbo/issues/12145）

**Comment by ranLee1** [comment]
已解决偶尔出现标题中问题！存在该报错可能是当前dubbo注册的服务存在其他非dubbo服务注册，请检查nacos中dubbo配置的注册中心命名空间是否存在其他非dubbo服务注册，如果有请在nacos中尝试新建一个`namespace`，然后将新的`namespace`和`group`配置到项目dubbo配置中。修改后配置参考：

```yaml
# dubbo3.2.8
dubbo:
  application:
    qos-enable: false
  registry:
    address: nacos://localhost:8848
    parameters:
      # 修改
      namespace: 31d95bdd-8af7-40fd-80f0-651f233f08de
      # 修改
      group: dubbo
  protocol:
    name: dubbo
    port: 28802
```

**Comment by paxxie2** [comment]
遇到类似问题已解决。关键点在dubbo、spring cloud discovery服务的注册与发现的配置，可以让dubbo和spring cloud discovery用不同的 namespace ，或者让 dubbo.application.name 与 spring.applicaiton.name 不同，比如 test-server-dubbo 和 test-server
