### ISSUE TITLE
请问springboot 引入dubbo后怎么关闭注册？

### ISSUE THREAD

**Issue by huihui-hb** [apache/dubbo#12263]
我在maven中引入了dubbo后项目就必须得正确配置，不然项目压根启动不了，即使我注释了application的enabledubbo注解。
请问这个要怎么玩呢？

**Comment by songxiaosheng** [comment]
> 我在maven中引入了dubbo后项目就必须得正确配置，不然项目压根启动不了，即使我注释了application的enabledubbo注解。
> 请问这个要怎么玩呢？

什么版本，报错信息有不

**Comment by huihui-hb** [comment]
> > 我在maven中引入了dubbo后项目就必须得正确配置，不然项目压根启动不了，即使我注释了application的enabledubbo注解。
> > 请问这个要怎么玩呢？
> 
> 什么版本，报错信息有不

`
java.lang.IllegalStateException: Failed to register dubbo://192.168.10.129:20881/com.zsw.pos.oauth.service.LoginService?anyhost=true&application=ceres-admin-server&application.version=1.1&background=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.zsw.pos.oauth.service.LoginService&logger=slf4j&metadata-type=remote&methods=grant&pid=41216&release=3.0.5&service-name-mapping=true&side=provider&timestamp=1683542498540 to registry 192.168.10.250:8848, cause: Failed to register dubbo://192.168.10.129:20881/com.zsw.pos.oauth.service.LoginService?anyhost=true&application=ceres-admin-server&application.version=1.1&background=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.zsw.pos.oauth.service.LoginService&logger=slf4j&metadata-type=remote&methods=grant&pid=41216&release=3.0.5&service-name-mapping=true&side=provider&timestamp=1683542498540 to nacos nacos://192.168.10.250:8848/org.apache.dubbo.registry.RegistryService?application=ceres-admin-server&application.version=1.1&dubbo=2.0.2&group=dev&interface=org.apache.dubbo.registry.RegistryService&logger=slf4j&namespace=bddff92b-ad56-420d-8aa3-e0d0dc583d70&pid=41216&qos.enable=false&release=3.0.5&timeout=20000, cause: Request nacos server failed: 
	at org.apache.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:218) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.registry.ListenerRegistryWrapper.register(ListenerRegistryWrapper.java:59) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.registry.integration.RegistryProtocol.register(RegistryProtocol.java:209) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:246) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:64) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:74) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:58) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.ServiceConfig.doExportUrl(ServiceConfig.java:638) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.ServiceConfig.exportRemote(ServiceConfig.java:612) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.ServiceConfig.exportUrl(ServiceConfig.java:572) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:402) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:388) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:363) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:237) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServiceInternal(DefaultModuleDeployer.java:338) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServices(DefaultModuleDeployer.java:310) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:142) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:108) [dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:98) [dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:44) [dubbo-3.0.5.jar:3.0.5]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:898) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at com.zsw.pos.AdminApplication.main(AdminApplication.java:46) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_333]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_333]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_333]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_333]
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:64) [idea_rt.jar:na]
Caused by: org.apache.dubbo.rpc.RpcException: Failed to register dubbo://192.168.10.129:20881/com.zsw.pos.oauth.service.LoginService?anyhost=true&application=ceres-admin-server&application.version=1.1&background=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.zsw.pos.oauth.service.LoginService&logger=slf4j&metadata-type=remote&methods=grant&pid=41216&release=3.0.5&service-name-mapping=true&side=provider&timestamp=1683542498540 to nacos nacos://192.168.10.250:8848/org.apache.dubbo.registry.RegistryService?application=ceres-admin-server&application.version=1.1&dubbo=2.0.2&group=dev&interface=org.apache.dubbo.registry.RegistryService&logger=slf4j&namespace=bddff92b-ad56-420d-8aa3-e0d0dc583d70&pid=41216&qos.enable=false&release=3.0.5&timeout=20000, cause: Request nacos server failed: 
	at org.apache.dubbo.registry.nacos.NacosRegistry.doRegister(NacosRegistry.java:180) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:205) ~[dubbo-3.0.5.jar:3.0.5]
	... 41 common frames omitted
Caused by: com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:279) ~[nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:129) ~[nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:115) ~[nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:95) ~[nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:145) ~[nacos-client-2.0.3.jar:na]
	at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.registerInstance(NacosNamingServiceWrapper.java:59) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.registry.nacos.NacosRegistry.doRegister(NacosRegistry.java:177) ~[dubbo-3.0.5.jar:3.0.5]
	... 42 common frames omitted
Caused by: com.alibaba.nacos.api.exception.NacosException: Client not connected,current status:STARTING
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:655) ~[nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:635) ~[nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:269) ~[nacos-client-2.0.3.jar:na]
	... 48 common frames omitted

2023-05-08 18:41:53[ERROR]  [] [main:170478] [o.a.dubbo.config.deploy.DefaultApplicationDeployer.onFailed:1087]  [DUBBO] Dubbo Application[1.1](admin-server) found failed module: Dubbo Module[1.1.1], dubbo version: 3.0.5, current host: 192.168.10.129

`

3.0.5d

**Comment by songxiaosheng** [comment]
尝试移除dubbo相关的开启配置和XML中引入的Dubbo相关的命名空间，避免触发如下初始化代码：
<img width="789" alt="image" src="https://user-images.githubusercontent.com/81170548/236830551-f7b4f580-e11c-476e-8366-34e8458b872e.png">

**Comment by AlbumenJ** [comment]
对于 starter 来说，本身就是一个约定大于配置的模式，因此 Dubbo 默认启用是符合预期的。如果不希望开启，那就把 maven 依赖给排除就行了。

**Comment by huihui-hb** [comment]
> 尝试移除dubbo相关的Java注解配置和XML中引入的Dubbo相关的命名空间，避免触发如下初始化代码： <img alt="image" width="789" src="https://user-images.githubusercontent.com/81170548/236830551-f7b4f580-e11c-476e-8366-34e8458b872e.png">

> 对于 starter 来说，本身就是一个约定大于配置的模式，因此 Dubbo 默认启用是符合预期的。如果不希望开启，那就把 maven 依赖给排除就行了。

@AlbumenJ 好像也是那么肥事。我根据大佬的设定改了后 ，发现我需要移除所有的注解，才可以不让dubbo启动报错。
确实我只能移除dubbo。
感谢你们。
