### ISSUE TITLE
Dubbo3.2.0启动报错

### ISSUE THREAD

**Issue by Ineffable919** [apache/dubbo#12321]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.0
* Operating System version: Windows 10
* Java version: 17

### Steps to reproduce this issue

版本 spring boot 3.0.6 启动报错

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

正常启动

### Actual Behavior

If there is an exception, please attach the exception trace:

java.lang.NoClassDefFoundError: io/prometheus/client/exporter/HttpConnectionFactory
	at org.apache.dubbo.metrics.prometheus.PrometheusMetricsReporterFactory.createMetricsReporter(PrometheusMetricsReporterFactory.java:43)
	at org.apache.dubbo.metrics.report.MetricsReporterFactory$Adaptive.createMetricsReporter(MetricsReporterFactory$Adaptive.java)
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.initMetricsReporter(DefaultApplicationDeployer.java:392)
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.initialize(DefaultApplicationDeployer.java:216)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.prepare(DefaultModuleDeployer.java:488)
	at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.initDubboConfigBeans(DubboConfigApplicationListener.java:73)
	at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.onApplicationEvent(DubboConfigApplicationListener.java:59)
	at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.onApplicationEvent(DubboConfigApplicationListener.java:37)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at org.springframework.context.support.AbstractApplicationContext.registerListeners(AbstractApplicationContext.java:880)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:581)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293)
	at com.crown.amish.user.UserApplication.main(UserApplication.java:17)
Caused by: java.lang.ClassNotFoundException: io.prometheus.client.exporter.HttpConnectionFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 21 common frames omitted
Just put your stack trace here!
```

**Comment by songxiaosheng** [comment]
如果需要引入可观测性的相关功能可以使用starter包方式集成
<img width="451" alt="image" src="https://github.com/apache/dubbo/assets/81170548/0d381cf0-e643-4883-ba17-b00f75a4a627">

**Comment by songxiaosheng** [comment]
缺失的类型在这个依赖中：
  <dependency>
      <groupId>io.prometheus</groupId>
      <artifactId>simpleclient_pushgateway</artifactId>
    </dependency>

**Comment by Ineffable919** [comment]
3.2.1还是会有这个问题   排查发现是如果自身引入了
         <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
        </dependency>
则会报错，之前无该错误

**Comment by Ineffable919** [comment]
3.2.1  启动会报另外一个错误  java.lang.TypeNotPresentException: Type kotlin.reflect.KProperty not present
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at java.base/sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at java.base/sun.reflect.generics.repository.ClassRepository.computeSuperInterfaces(ClassRepository.java:117)
	at java.base/sun.reflect.generics.repository.ClassRepository.getSuperInterfaces(ClassRepository.java:95)
	at java.base/java.lang.Class.getGenericInterfaces(Class.java:1211)
	at org.apache.dubbo.common.utils.SerializeSecurityConfigurator.checkClass(SerializeSecurityConfigurator.java:279)
	at org.apache.dubbo.common.utils.SerializeSecurityConfigurator.registerInterface(SerializeSecurityConfigurator.java:207)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.apache.dubbo.rpc.protocol.ProtocolSecurityWrapper.export(ProtocolSecurityWrapper.java:69)
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:61)
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47)
	at org.apache.dubbo.rpc.protocol.InvokerCountWrapper.export(InvokerCountWrapper.java:42)
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at org.apache.dubbo.registry.integration.RegistryProtocol.lambda$doLocalExport$3(RegistryProtocol.java:311)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doLocalExport(RegistryProtocol.java:309)
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:255)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:80)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:66)
	at org.apache.dubbo.rpc.protocol.ProtocolSecurityWrapper.export(ProtocolSecurityWrapper.java:83)
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:58)
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47)
	at org.apache.dubbo.rpc.protocol.InvokerCountWrapper.export(InvokerCountWrapper.java:42)
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ServiceConfig.doExportUrl(ServiceConfig.java:803)
	at org.apache.dubbo.config.ServiceConfig.exportRemote(ServiceConfig.java:781)
	at org.apache.dubbo.config.ServiceConfig.exportUrl(ServiceConfig.java:722)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:514)
	at org.apache.dubbo.config.ServiceConfig.lambda$doExportUrls$5(ServiceConfig.java:493)
	at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:80)
	at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:62)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:482)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:453)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:305)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServiceInternal(DefaultModuleDeployer.java:393)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServices(DefaultModuleDeployer.java:365)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:164)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:145)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:113)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:102)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:47)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:937)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:587)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293)
	at com.crown.amish.user.UserApplication.main(UserApplication.java:17)
Caused by: java.lang.ClassNotFoundException: kotlin.reflect.KProperty
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	... 58 common frames omitted

**Comment by Ineffable919** [comment]
Spring-security codec ignore error by @jojocodeX in https://github.com/apache/dubbo/pull/12192  
3.2.1  该问题解决了，能正常使用  但是还是会有警告报错

**Comment by ytrlmy521** [comment]
我也是同样的问题
`Caused by: java.lang.ClassNotFoundException: io.prometheus.client.exporter.HttpConnectionFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_172]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_172]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_172]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_172]
	... 19 more
Disconnected from the target VM, address: 'localhost:55179', transport: 'socket'
16:31:07.298 [main] [TraceInfo::] INFO  org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
16:31:07.300 [main] [TraceInfo::] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.NoClassDefFoundError: io/prometheus/client/exporter/HttpConnectionFactory`

**Comment by AlbumenJ** [comment]
> 我也是同样的问题 `Caused by: java.lang.ClassNotFoundException: io.prometheus.client.exporter.HttpConnectionFactory at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_172] at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_172] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_172] at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_172] ... 19 more Disconnected from the target VM, address: 'localhost:55179', transport: 'socket' 16:31:07.298 [main] [TraceInfo::] INFO org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener -
> 
> Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled. 16:31:07.300 [main] [TraceInfo::] ERROR org.springframework.boot.SpringApplication - Application run failed java.lang.NoClassDefFoundError: io/prometheus/client/exporter/HttpConnectionFactory`

这个是 Prometheus Metrics 的问题。
@songxiaosheng PTAL

**Comment by songxiaosheng** [comment]
> 我也是同样的问题
> `Caused by: java.lang.ClassNotFoundException: io.prometheus.client.exporter.HttpConnectionFactory
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_172]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_172]
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_172]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_172]
> 	... 19 more
> Disconnected from the target VM, address: 'localhost:55179', transport: 'socket'
> 16:31:07.298 [main] [TraceInfo::] INFO  org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener - 
> 
> Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
> 16:31:07.300 [main] [TraceInfo::] ERROR org.springframework.boot.SpringApplication - Application run failed
> java.lang.NoClassDefFoundError: io/prometheus/client/exporter/HttpConnectionFactory`

你们也额外引入了micrometer么

**Comment by songxiaosheng** [comment]
> ```
> simpleclient_pushgateway
> ```

@Ineffable919 @ytrlmy521 帮忙看下simpleclient_pushgateway这个依赖的版本号，感谢，案例中3.2.1和3.2.0运行都是正常的目测是这个依赖版本不太兼容导致缺失了一些类型

**Comment by ytrlmy521** [comment]
> > 3.2.1还是会有这个问题   排查发现是如果自身引入了
> > 
> > io.micrometer
> > micrometer-registry-prometheus
> > 
> > 则会报错，之前无该错误
> 
> 我瞅瞅

是的 版本号改成 2.7.7 没问题，改成3.0以上就不兼容了，也是引入了io.micrometer

**Comment by ytrlmy521** [comment]
> > ```
> > simpleclient_pushgateway
> > ```
> 
> @Ineffable919 @ytrlmy521 帮忙看下simpleclient_pushgateway这个依赖的版本号，感谢，案例中3.2.1和3.2.0运行都是正常的，目测是这个依赖版本不太兼容导致缺失了一些类型
![image](https://github.com/apache/dubbo/assets/19338049/910e571c-9263-49cf-aa78-b1b34f85cdbc)

simpleclient_pushgateway这个依赖的版本号 这个没有依赖，只依赖了io.prometheus:simpleclient_common:0.16.0的版本
@songxiaosheng

**Comment by songxiaosheng** [comment]
> simpleclient_pushgateway

你们仅仅引入了Dubbo和micrometer出现了这个问题么
有没有引入如下依赖,simpleclient_pushgateway默认在如下依赖里面是存在的：
```xml
 <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-observability-starter</artifactId>
        </dependency>
```

**Comment by ytrlmy521** [comment]
> > simpleclient_pushgateway
> 
> 你们仅仅引入了Dubbo和micrometer出现了这个问题么 有没有引入如下依赖,simpleclient_pushgateway默认在如下依赖里面是存在的：
> 
> ```
>  <dependency>
>             <groupId>org.apache.dubbo</groupId>
>             <artifactId>dubbo-spring-boot-observability-starter</artifactId>
>         </dependency>
> ```

还没有 我先试试看引入你说的这个 @songxiaosheng

**Comment by songxiaosheng** [comment]
> > > simpleclient_pushgateway
> > 
> > 
> > 你们仅仅引入了Dubbo和micrometer出现了这个问题么 有没有引入如下依赖,simpleclient_pushgateway默认在如下依赖里面是存在的：
> > ```
> >  <dependency>
> >             <groupId>org.apache.dubbo</groupId>
> >             <artifactId>dubbo-spring-boot-observability-starter</artifactId>
> >         </dependency>
> > ```
> 
> 还没有 我先试试看引入你说的这个 @songxiaosheng

那场景应该就是引入dubbo和micrometer 依赖是出现的，我来看下

**Comment by ytrlmy521** [comment]
> dubbo-spring-boot-observability-starter

gradle 构建用哪个版本 仓库里找不到呀

**Comment by songxiaosheng** [comment]
> dubbo-spring-boot-observability-starter

https://mvnrepository.com/artifact/org.apache.dubbo/dubbo-spring-boot-starter/3.2.1

**Comment by songxiaosheng** [comment]
> > dubbo-spring-boot-observability-starter
> 
> gradle 构建用哪个版本 仓库里找不到呀

你们示例代码方便发我邮箱一份么 songxiaosheng@apache.org  我这边测下

**Comment by Sunx6** [comment]
> 3.2.1 启动会报另外一个错误 java.lang.TypeNotPresentException: Type kotlin.reflect.KProperty not present at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117) at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125) at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) at java.base/sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68) at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138) at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) at java.base/sun.reflect.generics.repository.ClassRepository.computeSuperInterfaces(ClassRepository.java:117) at java.base/sun.reflect.generics.repository.ClassRepository.getSuperInterfaces(ClassRepository.java:95) at java.base/java.lang.Class.getGenericInterfaces(Class.java:1211) at org.apache.dubbo.common.utils.SerializeSecurityConfigurator.checkClass(SerializeSecurityConfigurator.java:279) at org.apache.dubbo.common.utils.SerializeSecurityConfigurator.registerInterface(SerializeSecurityConfigurator.java:207) at java.base/java.util.Optional.ifPresent(Optional.java:178) at org.apache.dubbo.rpc.protocol.ProtocolSecurityWrapper.export(ProtocolSecurityWrapper.java:69) at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:61) at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47) at org.apache.dubbo.rpc.protocol.InvokerCountWrapper.export(InvokerCountWrapper.java:42) at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) at org.apache.dubbo.registry.integration.RegistryProtocol.lambda$doLocalExport$3(RegistryProtocol.java:311) at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) at org.apache.dubbo.registry.integration.RegistryProtocol.doLocalExport(RegistryProtocol.java:309) at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:255) at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:80) at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:66) at org.apache.dubbo.rpc.protocol.ProtocolSecurityWrapper.export(ProtocolSecurityWrapper.java:83) at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:58) at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47) at org.apache.dubbo.rpc.protocol.InvokerCountWrapper.export(InvokerCountWrapper.java:42) at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) at org.apache.dubbo.config.ServiceConfig.doExportUrl(ServiceConfig.java:803) at org.apache.dubbo.config.ServiceConfig.exportRemote(ServiceConfig.java:781) at org.apache.dubbo.config.ServiceConfig.exportUrl(ServiceConfig.java:722) at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:514) at org.apache.dubbo.config.ServiceConfig.lambda$doExportUrls$5(ServiceConfig.java:493) at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:80) at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:62) at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:482) at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:453) at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:305) at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServiceInternal(DefaultModuleDeployer.java:393) at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServices(DefaultModuleDeployer.java:365) at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:164) at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:145) at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:113) at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:102) at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:47) at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413) at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370) at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:937) at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:587) at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304) at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293) at com.crown.amish.user.UserApplication.main(UserApplication.java:17) Caused by: java.lang.ClassNotFoundException: kotlin.reflect.KProperty at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) at java.base/java.lang.Class.forName0(Native Method) at java.base/java.lang.Class.forName(Class.java:467) at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114) ... 58 common frames omitted

这个问题解决了吗

**Comment by 2328832188** [comment]
> 财政部的类型在此依赖中：
> 
> ```
>   <dependency>
>       <groupId>io.prometheus</groupId>
>       <artifactId>simpleclient_pushgateway</artifactId>
>     </dependency>
> ```

十分感谢，解决了
