### ISSUE TITLE
dubbo3（consumer）分别调用dubbo2和dubbo3（provider）关于加载扩展协议的问题

### ISSUE THREAD

**Issue by wildeslam** [apache/dubbo#12378]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
consumer版本：3.1.9
provider版本：2.6.5 3.1.9
自定义协议
`public class CustomProtocol extends DubboProtocol {
    @Override
    public int getDefaultPort() {
        return 2222;
    }
}`
org.apache.dubbo.rpc.Protocol文件：
custom2=com.xxx.dubbo2.customprotocol.CustomProtocol
custom3=com.xxx.dubbo3.customprotocol.CustomProtocol

现在的情况是dubbo3调用dubbo3成功，dubbo2调用dubbo2报错
Caused by: java.lang.ClassNotFoundException: com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 82 more

	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:760) ~[dubbo-3.1.9.jar:3.1.9]
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:767) ~[dubbo-3.1.9.jar:3.1.9]
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:561) ~[dubbo-3.1.9.jar:3.1.9]
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:535) ~[dubbo-3.1.9.jar:3.1.9]
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java) ~[dubbo-3.1.9.jar:3.1.9]
	at org.apache.dubbo.config.ReferenceConfig.createInvokerForRemote(ReferenceConfig.java:614) ~[dubbo-3.1.9.jar:3.1.9]
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:448) ~[dubbo-3.1.9.jar:3.1.9]
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:300) ~[dubbo-3.1.9.jar:3.1.9]
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:232) ~[dubbo-3.1.9.jar:3.1.9]

**Comment by songxiaosheng** [comment]
看下扩展文件是不是路径不对

**Comment by wildeslam** [comment]
> 



> 看下扩展文件是不是路径不对

应该不是这个问题，因为consumer这边我换成dubbo2的版本后就可以正确加载custom2协议目前定位的原因是custom2协议extend了com.alibaba的dubboProtocol

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
