### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by java3niu** [apache/dubbo#12398]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.x
* Operating System version: Linux version 4.14.71-1.el7.centos.x86_64
* Java version: 17
java.lang.NullPointerException: Cannot enter synchronized block because the return value of "java.util.concurrent.ConcurrentMap.get(Object)" is null
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getSharedClient(DubboProtocol.java:566) ~[dubbo-4.0.72.jar:4.0.72]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getClients(DubboProtocol.java:534) ~[dubbo-4.0.72.jar:4.0.72]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.protocolBindingRefer(DubboProtocol.java:511) ~[dubbo-4.0.72.jar:4.0.72]
	at org.apache.dubbo.rpc.protocol.AbstractProtocol.refer(AbstractProtocol.java:104) ~[dubbo-4.0.72.jar:4.0.72]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:161) ~[dubbo-4.0.72.jar:4.0.72]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:75) ~[dubbo-4.0.72.jar:4.0.72]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:72) ~[dubbo-4.0.72.jar:4.0.72]
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java) ~[dubbo-4.0.72.jar:4.0.72]
	at org.apache.dubbo.registry.integration.RegistryDirectory$1.apply(RegistryDirectory.java:182) ~[dubbo-4.0.72.jar:4.0.72]
	at org.apache.dubbo.registry.integration.RegistryDirectory$1.apply(RegistryDirectory.java:179) ~[dubbo-4.0.72.jar:4.0.72]
	at org.apache.dubbo.registry.integration.RegistryDirectory.toInvokers(RegistryDirectory.java:648) ~[dubbo-4.0.72.jar:4.0.72]
	at org.apache.dubbo.registry.integration.RegistryDirectory.refreshInvoker(RegistryDirectory.java:437) ~[dubbo-4.0.72.jar:4.0.72]
	at org.apache.dubbo.registry.integration.RegistryDirectory.access$900(RegistryDirectory.java:123) ~[dubbo-4.0.72.jar:4.0.72]
	at org.apache.dubbo.registry.integration.RegistryDirectory$RefreshAction.run$original$WHjVmcmN(RegistryDirectory.java:1227) ~[dubbo-4.0.72.jar:4.0.72]
	at org.apache.dubbo.registry.integration.RegistryDirectory$RefreshAction.run$original$WHjVmcmN$accessor$nek1dtCa(RegistryDirectory.java) ~[dubbo-4.0.72.jar:4.0.72]
	at org.apache.dubbo.registry.integration.RegistryDirectory$RefreshAction$auxiliary$p4eWqJqa.call(Unknown Source) ~[dubbo-4.0.72.jar:4.0.72]
	at premain.qunar.tc.qtracer.agent.common.enhance.InstMethodsInter.intercept(InstMethodsInter.java:43) ~[qtracer-agent-1.0.28.jar:na]
	at org.apache.dubbo.registry.integration.RegistryDirectory$RefreshAction.run(RegistryDirectory.java) ~[dubbo-4.0.72.jar:4.0.72]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

**Comment by AlbumenJ** [comment]
Please try upgrade to 3.2.2
