### ISSUE TITLE
dubbo-demo-native-provider doesn't run successfully.

### ISSUE THREAD

**Issue by imgoby** [apache/dubbo#12400]
There is something wrong while I run dubbo-demo-native-provider.Why

log4j:WARN No appenders could be found for logger (org.apache.dubbo.common.utils.JRE).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.lang.IllegalStateException: Failed to create adaptive instance: java.lang.IllegalStateException: Can't create adaptive extension interface org.apache.dubbo.rpc.Protocol, cause: No adaptive method exist on extension org.apache.dubbo.rpc.Protocol, refuse to create the adaptive class!
	at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtension(ExtensionLoader.java:747)
	at org.apache.dubbo.config.ServiceConfig.postProcessAfterScopeModelChanged(ServiceConfig.java:173)
	at org.apache.dubbo.config.AbstractConfig.setScopeModel(AbstractConfig.java:422)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.service(DubboBootstrap.java:547)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.service(DubboBootstrap.java:542)
	at org.apache.dubbo.demo.graalvm.provider.Application.startWithBootstrap(Application.java:67)
	at org.apache.dubbo.demo.graalvm.provider.Application.main(Application.java:40)
Caused by: java.lang.IllegalStateException: Can't create adaptive extension interface org.apache.dubbo.rpc.Protocol, cause: No adaptive method exist on extension org.apache.dubbo.rpc.Protocol, refuse to create the adaptive class!
	at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtension(ExtensionLoader.java:1396)
	at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtension(ExtensionLoader.java:742)
	... 6 more
Caused by: java.lang.IllegalStateException: No adaptive method exist on extension org.apache.dubbo.rpc.Protocol, refuse to create the adaptive class!
	at org.apache.dubbo.common.extension.AdaptiveClassCodeGenerator.generate(AdaptiveClassCodeGenerator.java:105)
	at org.apache.dubbo.common.extension.AdaptiveClassCodeGenerator.generate(AdaptiveClassCodeGenerator.java:95)
	at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtensionClass(ExtensionLoader.java:1418)
	at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtensionClass(ExtensionLoader.java:1405)
	at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtension(ExtensionLoader.java:1388)
	... 7 more

**Comment by FoghostCn** [comment]
I write a demo and run success, maybe you can take a look.

**Comment by imgoby** [comment]
thank you. I built it successfully in my project too.
