### ISSUE TITLE
[DUBBO] Fail to connect toHeaderExchangeClient

### ISSUE THREAD

**Issue by RupertCui** [apache/dubbo#12412]
### Environment

* Dubbo version: 3.2.0
* Operating System version: linux centos
* Java version: 1.8

### Steps to reproduce this issue
1.启动provider 指定dubbo端口20880
2.启动consumer 服务正常
3.关闭第一个provider 启动第二个provider 端口为20882
4.观察consumer日志 一致在重连第一个已经关掉的provider

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
release 环境脱敏项目 TraceId: null ip: 脱敏 Exception:  [DUBBO] Fail to connect toHeaderExchangeClient [channel=org.apache.dubbo.remoting.transport.netty4.NettyClient [/ip脱敏*:18710 -> /ip脱敏:29378]], dubbo version: 3.2.0, current host: 10.20.152.180, error code: 6-16. This may be caused by , go to https://dubbo.apache.org/faq/6/16 to find instructions. 
at org.apache.dubbo.remoting.transport.netty4.NettyClient.doConnect(NettyClient.java:226)
at org.apache.dubbo.remoting.transport.netty4.NettyClient.doConnect(NettyClient.java:173)
at org.apache.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:219)
at org.apache.dubbo.remoting.transport.AbstractClient.reconnect(AbstractClient.java:273)
at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeClient.reconnect(HeaderExchangeClient.java:183)
at org.apache.dubbo.remoting.exchange.support.header.ReconnectTimerTask.doTask(ReconnectTimerTask.java:53)
at org.apache.dubbo.remoting.exchange.support.header.AbstractTimerTask.run(AbstractTimerTask.java:94)
at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:653)
at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:732)
at org.apache.dubbo.common.timer.HashedWheelTimer$Worker.run(HashedWheelTimer.java:454)
at java.lang.Thread.run(Thread.java:748)
 argsList: null
```

**Comment by AlbumenJ** [comment]
使用的什么注册中心，以及注册中心是否已经推送了下线的信息

**Comment by RupertCui** [comment]
注册中心：zookeeper 3.4.6
Maven 依赖版本：
curator-framework4.3.0
curator-x-discovery4.3.0
curator-recipes4.3.0
zookeeper3.4.14

在重启前已将要下线的服务权重设置为0，观察没有流量进行重启。没有观察到注册中心推送下线信息

**Comment by RupertCui** [comment]
2023-06-01 18:17:32.584 WARN  [ZookeeperDynamicConfiguration-thread-1] [] ?.?:? ->>  [DUBBO] error state, exporter should not be null, dubbo version: 3.2.0, current host: 10.20.152.7, error code: 99-0. This may be caused by unknown error in registry module, go to https://dubbo.apache.org/faq/99/0 to find instructions. 
java.lang.IllegalStateException: error state, exporter should not be null
        at org.apache.dubbo.registry.integration.RegistryProtocol$OverrideListener.doOverrideIfNecessary(RegistryProtocol.java:768)
        at org.apache.dubbo.registry.integration.RegistryProtocol$ProviderConfigurationListener.lambda$notifyOverrides$0(RegistryProtocol.java:879)
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
        at org.apache.dubbo.registry.integration.RegistryProtocol$ProviderConfigurationListener.notifyOverrides(RegistryProtocol.java:877)
        at org.apache.dubbo.registry.integration.AbstractConfiguratorListener.process(AbstractConfiguratorListener.java:102)
        at org.apache.dubbo.configcenter.support.zookeeper.ZookeeperDataListener.lambda$dataChanged$0(ZookeeperDataListener.java:77)
        at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
        at java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:404)
        at org.apache.dubbo.configcenter.support.zookeeper.ZookeeperDataListener.dataChanged(ZookeeperDataListener.java:77)
        at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient$NodeCacheListenerImpl.nodeChanged(CuratorZookeeperClient.java:438)
        at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:326)
        at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:320)
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:100)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

这是服务启动过程中的一个报错

**Comment by RupertCui** [comment]
> 使用的什么注册中心，以及注册中心是否已经推送了下线的信息

您好，此问题已解决，乌龙了，是因为我们启动脚本有问题，没有优雅停机导致的

**Comment by Keanhua** [comment]
@RupertCui 麻烦问下，这个具体您那边具体是怎么解决的啊？我这边也碰到了

**Comment by 2328832188** [comment]
@RupertCui 您好，可以说一下脚本的哪块问题导致的吗? 被这个问题困扰好久了

**Comment by RupertCui** [comment]
不好意思，刚看到，我们问题产生的原因是：

关于启动过程中的报错：[DUBBO] Fail to connect toHeaderExchangeClient&nbsp;

这是由于生产的jenkins脚本在服务重启前没有走代码里的脚本，提前执行了kill-9，导致服务没有优雅停机，服务提供者没来得及注销服务信息就死了，现已修复。

更多信息请参照优雅停机 | Apache Dubbo

如再有问题，可以继续联系，我会关注邮件





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dubbo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月13日(星期一) 晚上6:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dubbo] [DUBBO] Fail to connect toHeaderExchangeClient (Issue #12412)





 
@RupertCui 您好，可以说一下脚本的哪块问题导致的吗? 被这个问题困扰好久了
