### ISSUE TITLE
NPE: unexpected error when unsubscribe service

### ISSUE THREAD

**Issue by chaoyoung** [apache/dubbo#12431]
### Environment

* Dubbo version: 3.1.10
* Operating System version: CentOS 7
* Java version: 1.8.0_201

### Expected Behavior

No NPE

### Actual Behavior

NPE

If there is an exception, please attach the exception trace:

```
2023-05-25 20:53:33.131  WARN 1 --- [bboShutdownHook] .d.registry.integration.DynamicDirectory:? :  [DUBBO] unexpected error when unsubscribe service xxx from registry: nacos://nacos-0.nacos-headless.default.svc.cluster.local:8848,nacos-1.nacos-headless.default.svc.cluster.local:8848,nacos-2.nacos-headless.default.svc.cluster.local:8848/org.apache.dubbo.registry.RegistryService?application=vui-server-dubbo&check=true&dubbo=2.0.2&enable-empty-protection=false&interface=org.apache.dubbo.registry.RegistryService&password=nacos&pid=1&qos.enable=true&register=true&register-mode=all&release=3.1.10&subscribe=true&timeout=5000&username=nacos, dubbo version: 3.1.10, current host: 10.244.3.18, error code: 1-8. This may be caused by , go to https://dubbo.apache.org/faq/1/8 to find instructions.
java.lang.NullPointerException: null
	at org.apache.dubbo.metadata.AbstractServiceNameMapping.stopListen(AbstractServiceNameMapping.java:165)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.doUnsubscribe(ServiceDiscoveryRegistry.java:246)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.unsubscribe(ServiceDiscoveryRegistry.java:229)
	at org.apache.dubbo.registry.ListenerRegistryWrapper.unsubscribe(ListenerRegistryWrapper.java:99)
	at org.apache.dubbo.registry.integration.DynamicDirectory.destroy(DynamicDirectory.java:312)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.destroy(ServiceDiscoveryRegistryDirectory.java:147)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.destroy(AbstractClusterInvoker.java:129)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.destroy(MockClusterInvoker.java:88)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.destroy(MigrationInvoker.java:329)
	at org.apache.dubbo.config.ReferenceConfig.destroy(ReferenceConfig.java:249)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.postDestroy(DefaultModuleDeployer.java:230)
	at org.apache.dubbo.rpc.model.ModuleModel.onDestroy(ModuleModel.java:109)
	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:121)
	at org.apache.dubbo.rpc.model.ApplicationModel.onDestroy(ApplicationModel.java:161)
	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:121)
	at org.apache.dubbo.config.DubboShutdownHook.doDestroy(DubboShutdownHook.java:80)
	at org.apache.dubbo.config.DubboShutdownHook.run(DubboShutdownHook.java:75)
```

**Comment by songxiaosheng** [comment]
升级3.2.2版本试试 这个有优化逻辑
https://github.com/apache/dubbo/commit/7a5d04a16923b2f3fbac943ca9254dc9f9debabd

**Comment by chaoyoung** [comment]
> 升级3.2.2版本试试 这个有优化逻辑 [7a5d04a](https://github.com/apache/dubbo/commit/7a5d04a16923b2f3fbac943ca9254dc9f9debabd)

已升级到3.2.5，目前没有再发现此类问题。
