### ISSUE TITLE
triple协议 + protobuf IDL 进行本地调用时报错

### ISSUE THREAD

**Issue by ai-log** [apache/dubbo#12462]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

**Comment by ai-log** [comment]
`Caused by: java.lang.IllegalStateException: No such extension org.apache.dubbo.common.serialize.Serialization by name protobuf, no related exception was found, please check whether related SPI module is missing.
	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:779)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:786)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:575)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:549)
	at org.apache.dubbo.common.serialize.DefaultMultipleSerialization.serialize(DefaultMultipleSerialization.java:31)
	at org.apache.dubbo.rpc.protocol.tri.ReflectionPackableMethod$WrapRequestPack.pack(ReflectionPackableMethod.java:428)
	at org.apache.dubbo.rpc.model.PackableMethod.packRequest(PackableMethod.java:78)
	at org.apache.dubbo.rpc.protocol.tri.call.TripleClientCall.sendMessage(TripleClientCall.java:177)
	... 28 more`

目前Dubbo 还不支持protobuf IDL的本地调用吗

**Comment by AlbumenJ** [comment]
@icodening PTAL

**Comment by icodening** [comment]
@ai-log 
支持IDL方式调用，但使用`triple`时不需要手动指定protobuf序列化方式，是否使用protobuf序列化方式是根据方法入参class类型判断的，去掉配置中的protobuf序列化即可

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
