### ISSUE TITLE
dubbo 3.1.10 registry NPE

### ISSUE THREAD

**Issue by chaoyoung** [apache/dubbo#12464]
### Environment

* Dubbo version: 3.1.10
* Operating System version: CentOS 7.7
* Java version: 1.8.0_201
* Spring Cloud Alibaba: 2021.0.4.0
* Nacos version: 2.2.0
* grpc version: 1.54.1
* protobuf version: 3.21.12

### Steps to reproduce this issue

1. maven pom.xml
   ```xml
   <dependency>
       <groupId>com.alibaba.cloud</groupId>
       <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
       <exclusions>
           <exclusion>
               <groupId>com.alibaba.nacos</groupId>
               <artifactId>nacos-client</artifactId>
           </exclusion>
       </exclusions>
   </dependency>
   <dependency>
       <groupId>com.alibaba.cloud</groupId>
       <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
       <exclusions>
           <exclusion>
               <groupId>com.alibaba.nacos</groupId>
               <artifactId>nacos-client</artifactId>
           </exclusion>
       </exclusions>
   </dependency>
   <dependency>
       <groupId>com.alibaba.nacos</groupId>
       <artifactId>nacos-client</artifactId>
       <version>${nacos-client.version}</version>
   </dependency>

   <dependency>
       <groupId>org.apache.dubbo</groupId>
       <artifactId>dubbo-spring-boot-starter</artifactId>
   </dependency>
   <dependency>
       <groupId>org.apache.dubbo</groupId>
       <artifactId>dubbo-spring-boot-actuator</artifactId>
   </dependency>
   <dependency>
       <groupId>org.apache.dubbo</groupId>
       <artifactId>dubbo-serialization-hessian2</artifactId>
   </dependency>
   <dependency>
       <groupId>io.grpc</groupId>
       <artifactId>grpc-netty</artifactId>
       <exclusions>
           <exclusion>
               <artifactId>netty-codec-http2</artifactId>
               <groupId>io.netty</groupId>
           </exclusion>
           <exclusion>
               <artifactId>netty-handler-proxy</artifactId>
               <groupId>io.netty</groupId>
           </exclusion>
       </exclusions>
   </dependency>
   <dependency>
       <groupId>io.grpc</groupId>
       <artifactId>grpc-netty-shaded</artifactId>
   </dependency>
   <dependency>
       <groupId>io.grpc</groupId>
       <artifactId>grpc-protobuf</artifactId>
   </dependency>
   <dependency>
       <groupId>io.grpc</groupId>
       <artifactId>grpc-stub</artifactId>
   </dependency>
   <dependency>
       <groupId>com.google.protobuf</groupId>
       <artifactId>protobuf-java-util</artifactId>
   </dependency>
   ```
2. dubbo config
   ```yml
   dubbo:
     application:
       name: xxx
       register-mode: all
       protocol: tri
       enable-empty-protection: false
     scan.base-packages: xxx
     protocols:
       triple:
         name: tri
         port: -1
         serialization: protobuf
       dubbo:
         name: dubbo
         port: -1
         serialization: hessian2
     registry:
       enable-empty-protection: false
       address: nacos://${spring.cloud.nacos.server-addr}?username=${spring.cloud.nacos.username}&password=${spring.cloud.nacos.password}
       use-as-metadata-center: true
       use-as-config-center: true
     provider:
       delay: -1
       timeout: 3000
       retries: 0
     consumer:
       check: false
   ```

### Expected Behavior

No Error

### Actual Behavior

```java
2023-06-05 20:43:10.192  INFO 1 --- [tion-2-thread-1] d.registry.integration.RegistryDirectory:586 :  [DUBBO] New url total size, 1, destroyed total size 1, dubbo version: 3.1.10, current host: 10.244.24.215
2023-06-05 20:43:10.193  INFO 1 --- [tion-2-thread-1] .r.c.m.DefaultMigrationAddressComparator:52 :  [DUBBO] No instance address available, stop compare., dubbo version: 3.1.10, current host: 10.244.24.215
2023-06-05 20:43:10.194  INFO 1 --- [tion-2-thread-1] pache.dubbo.registry.nacos.NacosRegistry:514 :  [DUBBO] Notify urls for subscribe url consumer://10.244.24.215/com.xxxService, url size: 1, dubbo version: 3.1.10, current host: 10.244.24.215
2023-06-05 20:43:10.194  INFO 1 --- [tion-2-thread-1] .r.c.m.DefaultMigrationAddressComparator:52 :  [DUBBO] No instance address available, stop compare., dubbo version: 3.1.10, current host: 10.244.24.215
2023-06-05 20:43:10.195 ERROR 1 --- [tion-2-thread-1] g.apache.dubbo.registry.RegistryNotifier:? :  [DUBBO] Error occurred when notify directory. , dubbo version: 3.1.10, current host: 10.244.24.215, error code: 1-7. This may be caused by , go to https://dubbo.apache.org/faq/1/7 to find instructions.

java.lang.NullPointerException: null
	at java.util.LinkedList.addAll(LinkedList.java:408)
	at java.util.LinkedList.addAll(LinkedList.java:387)
	at java.util.LinkedList.<init>(LinkedList.java:119)
	at org.apache.dubbo.registry.nacos.NacosRegistry.notifySubscriber(NacosRegistry.java:608)
	at org.apache.dubbo.registry.nacos.NacosRegistry.access$000(NacosRegistry.java:88)
	at org.apache.dubbo.registry.nacos.NacosRegistry$RegistryChildListenerImpl$1.doNotify(NacosRegistry.java:706)
	at org.apache.dubbo.registry.RegistryNotifier$NotificationTask.run(RegistryNotifier.java:106)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2023-06-05 20:43:10.202  INFO 1 --- [tion-0-thread-1] .r.c.m.DefaultMigrationAddressComparator:52 :  [DUBBO] No instance address available, stop compare., dubbo version: 3.1.10, current host: 10.244.24.215
```

**Comment by icodening** [comment]
@chaoyoung 
什么场景下会出现呢？目前看起来是短时间内同时出现多个服务变更事件引起的

**Comment by chaoyoung** [comment]
> 

k8s环境重启pod时报的错。因为时开发环境，就只运行了一个实例。
