### ISSUE TITLE
Dubbo 3.2.2 Triple协议并发场景下偶发数组越界异常

### ISSUE THREAD

**Issue by DoctorFung** [apache/dubbo#12512]
具体报错如下：
Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 1086 out of bounds for double
atjava.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2070)
at org.apache.dubbo.rpc.AsyncRpcResult.getAppResponse(AsyncRpcResult.java:161)
89 common frames omitted
Caused by: java.lang.ArrayIndex0utOfBoundsException: arraycopy: last destination index 1086 out of bounds for double[1050]
at java.base/java.lang.System.arraycopy(Native Method)
at com.tdunning.math.stats.MergingDigest.merge(MergingDigest.java:381)
at com.tdunning.math.stats.MergingDigest.mergeNewValues(MergingDigest.java:363)
at com.tdunning.math.stats.MergingDigest.mergeNewValues(MergingDigest.java:353)
at com.tdunning.math.stats.MergingDigest.add(MergingDigest.java:259)
at com.tdunning.math.stats.MergingDigest.add(MergingDigest.java:251)
at com.tdunning.math.stats.AbstractTDigest.add(AbstractTDigest.java:129)
at org.apache.dubbo.metrics.aggregate.TimeWindowQuantile.add(TimeWindowOuantile.iava:51)
at org.apache.dubbo.metrics.collector.AggregateMetricsCollector.onRTEvent(AggregateMetricsCollector.java:92)
atorg.apache.dubbo.metrics.collector.AggregateMetricsCollector.onEvent(AggregateMetricsCollector.java:82)
at org.apache.dubbo.metrics.event.SimpleMetricsEventMulticaster.publishEvent(SimpleMetricsEventMulticaster.iava:48)
atorg.apache.dubbo.metrics.collector.sample.MethodMetricsSampler.lambda$rtConfigure$3(MethodMetricsSampler.java:61)
at org.apache.dubbo.metrics.collector.sample.SimpleMetricsCountSampler.addRT(SimpleMetricsCountSampler.java:120)
at org.apache.dubbo.metrics.filter.MethodMetricsInterceptor.rtTime(MethodMetricsInterceptor.java:97)
at org. apache.dubbo.metrics.filter.MethodMetricsInterceptor.onCompleted(MethodMetricsInterceptor.java:101)
at org.apache.dubbo.metrics.filter.MethodMetricsInterceptor.afterMethod(MethodMetricsInterceptor.java:58)
at org.apache.dubbo.metrics.filter.MetricsFilter.onResponse(MetricsFilter.iava:64)
atorg.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CallbackRegistrationInvoker.lambda$invoke$1(FilterChainBuilder.java:218)
atorg.apache.dubbo.rpc.AsyncRpcResult.lambda$whenCompleteWithContext$0(AsyncRpcResult.java:228)
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2322)
at org.apache.dubbo.rpc.AsyncRpcResult.whenCompleteWithContext(AsyncRpcResult.java:224)
atorg.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CallbackRegistrationInvoker.invoke(FilterChainBuilder.java:195)

**Comment by EarthChen** [comment]
@songxiaosheng PTAL

**Comment by songxiaosheng** [comment]
@DoctorFung 确认下你们dubbo-spring-boot-observability-starter版本号是什么呀

**Comment by wxbty** [comment]
他用的3.2.0，升级3.2.1+即可
