### ISSUE TITLE
dubbo3.2.2 metrics找不到方法报错

### ISSUE THREAD

**Issue by fawks96** [apache/dubbo#12589]
![1687678237154](https://github.com/apache/dubbo/assets/30108187/5d01a08f-2ae6-416a-a678-9b858926979a)

完整堆栈：
`2023-06-25 14:53:43.423|||Failed to apply the value function for the gauge 'dubbo.consumer.rt.milliseconds.p95'. Note that subsequent logs will be logged at debug level.
java.lang.NoSuchMethodError: 'void com.tdunning.math.stats.Sort.stableSort(int[], double[], int)'
	at org.apache.dubbo.metrics.aggregate.DubboMergingDigest.merge(DubboMergingDigest.java:378)
	at org.apache.dubbo.metrics.aggregate.DubboMergingDigest.mergeNewValues(DubboMergingDigest.java:345)
	at org.apache.dubbo.metrics.aggregate.DubboMergingDigest.compress(DubboMergingDigest.java:488)
	at org.apache.dubbo.metrics.aggregate.DubboMergingDigest.centroids(DubboMergingDigest.java:731)
	at org.apache.dubbo.metrics.aggregate.DubboAbstractTDigest.add(DubboAbstractTDigest.java:81)
	at org.apache.dubbo.metrics.aggregate.TimeWindowQuantile.quantile(TimeWindowQuantile.java:43)
	at org.apache.dubbo.metrics.collector.AggregateMetricsCollector.lambda$null$9(AggregateMetricsCollector.java:201)
	at io.micrometer.core.instrument.internal.DefaultGauge.value(DefaultGauge.java:53)
	at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$newGauge$5(PrometheusMeterRegistry.java:334)
	at io.micrometer.prometheus.MicrometerCollector.collect(MicrometerCollector.java:75)
	at io.prometheus.client.Collector.collect(Collector.java:46)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:197)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:212)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:152)
	at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:71)
	at io.prometheus.client.exporter.common.TextFormat.writeFormat(TextFormat.java:53)
	at io.micrometer.prometheus.PrometheusMeterRegistry.scrape(PrometheusMeterRegistry.java:158)
	at io.micrometer.prometheus.PrometheusMeterRegistry.scrape(PrometheusMeterRegistry.java:153)
	at io.micrometer.prometheus.PrometheusMeterRegistry.scrape(PrometheusMeterRegistry.java:124)
	at io.micrometer.prometheus.PrometheusMeterRegistry.scrape(PrometheusMeterRegistry.java:111)
	at org.apache.dubbo.metrics.prometheus.PrometheusMetricsReporter.getResponse(PrometheusMetricsReporter.java:68)
	at org.apache.dubbo.metrics.prometheus.PrometheusMetricsReporterCmd.getResponseByApplication(PrometheusMetricsReporterCmd.java:124)
	at org.apache.dubbo.metrics.prometheus.PrometheusMetricsReporterCmd.useFirst(PrometheusMetricsReporterCmd.java:69)
	at org.apache.dubbo.metrics.prometheus.PrometheusMetricsReporterCmd.execute(PrometheusMetricsReporterCmd.java:56)
	at org.apache.dubbo.qos.command.DefaultCommandExecutor.execute(DefaultCommandExecutor.java:86)
	at org.apache.dubbo.qos.server.handler.HttpProcessHandler.channelRead0(HttpProcessHandler.java:98)
	at org.apache.dubbo.qos.server.handler.HttpProcessHandler.channelRead0(HttpProcessHandler.java:57)
	at org.apache.dubbo.qos.server.handler.HttpProcessHandler.channelRead0(HttpProcessHandler.java:57)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:255)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:517)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)`

### Environment

* Dubbo version: 3.2.2
* Operating System version: xxx
* Java version: JDK17

**Comment by songxiaosheng** [comment]
你们t degist包版本多少

**Comment by fawks96** [comment]
> 你们t degist包版本多少

3.2

**Comment by fawks96** [comment]
> 你们t degist包版本多少

我idea里本地查看依赖，查到的是3.2版本。我没有手工引入过，我看dubbo里带过来它的版本应该3.3 。 不知道为什么我本地实际的是3.2版本。

**Comment by songxiaosheng** [comment]
3.3是没问题的，你执行mvn dependency:tree 查下3.2是哪里来的，或者你单独在最外层引入个3.3版本
<img width="1158" alt="image" src="https://github.com/apache/dubbo/assets/81170548/a31af6d0-f1b9-43bd-ba5e-514dc1ee4431">

**Comment by fawks96** [comment]
> 3.3是没问题的，你执行mvn dependency:tree 查下3.2是哪里来的，或者你单独在最外层引入个3.3版本 <img alt="image" width="1158" src="https://user-images.githubusercontent.com/81170548/248668377-a31af6d0-f1b9-43bd-ba5e-514dc1ee4431.png">

Thanks.  看了下是elastic search 里带过来的。 我手动引入个3.3版本。
