### ISSUE TITLE
Unexpected serialization type:null received from network, please check if the peer send the right id.

### ISSUE THREAD

**Issue by hebrd** [apache/dubbo#12604]
环境：
* 服务端采用tri协议
* 客户端通过gRPC调用
```
[DubboServerHandler-192.168.1.2:9090-thread-2] ERROR org.apache.dubbo.rpc.protocol.tri.call.AbstractServerCall -  [DUBBO] Process request failed. service=com.deo.trading.service.FixTradingService method=cancelOrder, dubbo version: 3.2.2, current host: 192.168.1.2, error code: 4-11. This may be caused by , go to https://dubbo.apache.org/faq/4/11 to find instructions. 
java.io.IOException: Unexpected serialization type:null received from network, please check if the peer send the right id.
	at org.apache.dubbo.remoting.transport.CodecSupport.checkSerialization(CodecSupport.java:174)
	at org.apache.dubbo.rpc.protocol.tri.ReflectionPackableMethod$WrapRequestUnpack.unpack(ReflectionPackableMethod.java:476)
	at org.apache.dubbo.rpc.model.WrapperUnPack.unpack(WrapperUnPack.java:23)
```

另一个异常
```
java.lang.RuntimeException: fieldNum should in (1,2,3)
	at org.apache.dubbo.rpc.protocol.tri.TripleCustomerProtocolWapper$TripleRequestWrapper.parseFrom(TripleCustomerProtocolWapper.java:269)
	at org.apache.dubbo.rpc.protocol.tri.ReflectionPackableMethod$WrapRequestUnpack.unpack(ReflectionPackableMethod.java:472)
```

**Comment by EarthChen** [comment]
你用的是proto 生成的吗，你这调用的是 wrapper 模式

**Comment by hebrd** [comment]
客户端直接用Postman的Grpc请求发送，是不是triple协议不支持异构语言的直接调用？必须使用dubbo插件生成的代码？

**Comment by icodening** [comment]
想要triple支持gRPC模式，需要用proto生成服务端代码，否则会按照传统`java interface`方式发布非gRPC服务

**Comment by soulmz** [comment]
> 想要triple支持gRPC模式，需要用proto生成服务端代码，否则会按照传统`java interface`方式发布非gRPC服务

@icodening 这个具体的方式调用示例有文档吗？

**Comment by tdb11039gg** [comment]
> 想要triple支持gRPC模式，需要用proto生成服务端代码，否则会按照传统`java interface`方式发布非gRPC服务

用proto生成服务端代码的话，那这种方式和dubbo有啥关系，为什么说dubbo兼容grpc
