### ISSUE TITLE
NettyPortUnificationServerHandler.decode 空指针异常

### ISSUE THREAD

**Issue by pbmh92** [apache/dubbo#12621]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.10
* Operating System version: xxx
* Java version: 1.8

### Steps to reproduce this issue
偶发，有个服务报这个错误，调用方超时

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

类名	org.apache.dubbo.remoting.transport.netty4.NettyPortUnificationServerHandler
方法名	NettyServerWorker-7-2
线程名	NettyServerWorker-7-2
内容	
[DUBBO] Unexpected exception from downstream before protocol detected., dubbo version: 3.1.10, current host: 172.17.0.1, error code: 99-0. This may be caused by unknown error in remoting module, go to https://dubbo.apache.org/faq/99/0 to find instructions.
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
　　at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:471)
　　at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
　　at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
　　at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
　　at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
　　at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
　　at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
　　at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
　　at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
　　at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
　　at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
　　at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
　　at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
　　at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
　　at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
　　at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
　　at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
　　at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
　　at org.apache.dubbo.remoting.transport.netty4.NettyPortUnificationServerHandler.decode(NettyPortUnificationServerHandler.java:100)
　　at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
　　at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
　　... 17 more

```
Just put your stack trace here!
```

**Comment by AlbumenJ** [comment]
@EarthChen @icodening PTAL

**Comment by Floweryu** [comment]
I also encountered this problem，my dubbo version is 3.1.2

**Comment by zuomengjun** [comment]
> I also encountered this problem，my dubbo version is 3.1.2

hello, I also encountered this problem，my dubbo version is 3.1.11.

Is there a solution to this problem? @AlbumenJ @CrazyHZM @pbmh92 @Floweryu

**Comment by paradiseidler** [comment]
Can you provide a reproducible demo?    @zuomengjun

**Comment by jockercheng91** [comment]
Dubbo version: 3.3.0 
Java version: 1.8 
 I also encountered this problem.
```
[biz-device-center-service] 2025-11-04 11:10:37.699 [NettyServerWorker-13-1] ERROR o.a.d.r.t.netty4.NettyPortUnificationServerHandler - [DUBBO] Unexpected exception from downstream before protocol detected., dubbo version: 3.3.0, current host: 10.216.13.14, error code: 99-0. This may be caused by unknown error in remoting module, go to https://dubbo.apache.org/faq/99/0 to find instructions. 
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:499)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
        at org.apache.dubbo.remoting.transport.netty4.NettyPortUnificationServerHandler.detectProtocol(NettyPortUnificationServerHandler.java:158)
        at org.apache.dubbo.remoting.transport.netty4.NettyPortUnificationServerHandler.decode(NettyPortUnificationServerHandler.java:124)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
        ... 17 common frames omitted
```
