### ISSUE TITLE
ZookeeperRegistry ->doRegister 方法 faultTolerant参数 设置为false 是不是会存在问题 

### ISSUE THREAD

**Issue by qijun4tian** [apache/dubbo#12646]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
[这个问题中](https://github.com/apache/dubbo/issues/12607)

在provider 恢复zk 链接后
日志如下
```
2023-06-27 19:24:53.473 [main-EventThread] INFO  org.apache.curator.framework.state.ConnectionStateManager [postState:251] - State change: RECONNECTED
```

FailbackRegistry 尝试去恢复链接 会调用  addFailedRegistered 加入到HashedWheelTimer  
HashedWheelTimer 最后尝试去重新注册的时候提示node 已经存在

```
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:119)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783)
	at org.apache.curator.framework.imps.CreateBuilderImpl$17.call(CreateBuilderImpl.java:1176)
	at org.apache.curator.framework.imps.CreateBuilderImpl$17.call(CreateBuilderImpl.java:1156)
	at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:64)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100)
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:1153)
	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:607)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:597)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:575)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:51)
	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.createEphemeral(CuratorZookeeperClient.java:138)
	at org.apache.dubbo.remoting.zookeeper.AbstractZookeeperClient.create(AbstractZookeeperClient.java:87)
	at org.apache.dubbo.registry.zookeeper.ZookeeperRegistry.doRegister(ZookeeperRegistry.java:161)
	at org.apache.dubbo.registry.retry.FailedRegisteredTask.doRetry(FailedRegisteredTask.java:37)
	at org.apache.dubbo.registry.retry.AbstractRetryTask.run(AbstractRetryTask.java:129)
	at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:653)
	at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:732)
	at org.apache.dubbo.common.timer.HashedWheelTimer$Worker.run(HashedWheelTimer.java:454)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

这个问题与 [瓜子遇到的问题类似](https://cn.dubbo.apache.org/zh-cn/blog/2019/01/05/dubbo-%e5%9c%a8%e7%93%9c%e5%ad%90%e4%ba%8c%e6%89%8b%e8%bd%a6%e7%9a%84%e5%ae%9e%e8%b7%b5/)

AbstractZookeeperClient  的 create()只有在 ZookeeperRegistry 调用 doRegister 设置为false。

**Comment by qijun4tian** [comment]
@AlbumenJ  是否存在问题，大佬帮忙看下啊

**Comment by AlbumenJ** [comment]
可以帮提个 PR 把 faultTolerant 改成 false 嘛

**Comment by qijun4tian** [comment]
> 可以帮提个 PR 把 faultTolerant 改成 false 嘛

我试试看

**Comment by iwangjie** [comment]
3.1.11 如何才能优雅的通过补丁解决此问题？
