### ISSUE TITLE
com.alibaba.fastjson2.JSONException: not support none serializable class org.apache.dubbo.rpc.TriRpcStatus

### ISSUE THREAD

**Issue by HelloToGithub** [apache/dubbo#12678]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.3
* fastjson2 version: 2.0.34
* Java version: 8

### Actual Behavior

If there is an exception, please attach the exception trace:
org.apache.dubbo.rpc.StatusRpcException: INTERNAL : Serialize response failed
java.io.IOException: org.apache.dubbo.common.serialize.SerializationException: com.alibaba.fastjson2.JSONException: not support none serializable class org.apache.dubbo.rpc.TriRpcStatus
	at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper.handleToIOException(DefaultSerializationExceptionWrapper.java:358)
	at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper.access$000(DefaultSerializationExceptionWrapper.java:28)
	at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper$ProxyObjectOutput.writeObject(DefaultSerializationExceptionWrapper.java:324)
	at org.apache.dubbo.common.serialize.DefaultMultipleSerialization.serialize(DefaultMultipleSerialization.java:33)
	at org.apache.dubbo.rpc.protocol.tri.ReflectionPackableMethod$WrapResponsePack.pack(ReflectionPackableMethod.java:345)
```
Just put your stack trace here!
```

**Comment by HelloToGithub** [comment]
rresolved due to version inconsistency
