### ISSUE TITLE
dubbo3 应用级服务发现 泛化调用异常

### ISSUE THREAD

**Issue by wangjunjie92** [apache/dubbo#12694]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version:3.1.0
* Operating System version: Windows
* Java version: 1.8

生产者
```
        ServiceConfig<GreetingsService> service = new ServiceConfig<>();
        service.setInterface(GreetingsService.class);
        service.setRef(new GreetingsServiceImpl());
        service.setGeneric("true");

        RegistryConfig registryConfig = new RegistryConfig();
        registryConfig.setAddress("nacos://127.0.0.1:8848");
        Map<String,String> paramMap = new HashMap<String, String>();
        paramMap.put("namespace","test");
        registryConfig.setParameters(paramMap);
        registryConfig.setCheck(false);

        ApplicationConfig applicationConfig = new ApplicationConfig();
        applicationConfig.setName("first-dubbo-provider");
        applicationConfig.setRegisterMode("instance");

        DubboBootstrap.getInstance()
                .application(applicationConfig)
                .registry(registryConfig)
                .protocol(new ProtocolConfig("dubbo", -1))
                .service(service)
                .start()
                .await();
```
消费者

```
        //创建ApplicationConfig
        ApplicationConfig applicationConfig = new ApplicationConfig();
        applicationConfig.setName("generic-call-consumer");
        applicationConfig.setRegisterMode("instance");
        RegistryConfig registryConfig = new RegistryConfig();
        registryConfig.setAddress("nacos://127.0.0.1:8848");
        Map<String,String> paramMap = new HashMap<String, String>();
        paramMap.put("namespace","test");
        registryConfig.setParameters(paramMap);
        registryConfig.setCheck(false);

        ProtocolConfig protocolConfig = new ProtocolConfig();
        protocolConfig.setName("dubbo");
        protocolConfig.setPort(-1);

        ReferenceConfig<GenericService> referenceConfig = new ReferenceConfig<>();
        referenceConfig.setInterface("com.wang.student.student.dubbo.api.GreetingsService");
        applicationConfig.setRegistry(registryConfig);
        applicationConfig.setProtocol("dubbo");
        referenceConfig.setApplication(applicationConfig);
        referenceConfig.setGeneric("true");
        referenceConfig.setAsync(false);
        referenceConfig.setTimeout(7000);
        GenericService genericService = referenceConfig.get();
        Object result = genericService.$invoke("sayHi", new String[]{"java.lang.String"}, new Object[]{"world genericService"});
```
异常信息
```
Exception in thread "main" java.lang.IllegalStateException: Failed to check the status of the service com.wang.student.student.dubbo.api.GreetingsService. No provider available for the service com.wang.student.student.dubbo.api.GreetingsService from the url consumer://192.168.56.1/com.wang.student.student.dubbo.api.GreetingsService?application=generic-call-consumer&async=false&background=false&dubbo=2.0.2&generic=true&interface=com.wang.student.student.dubbo.api.GreetingsService&pid=21052&register-mode=instance&register.ip=192.168.56.1&release=3.1.10&side=consumer&sticky=false&timeout=7000&timestamp=1688720882572&unloadClusterRelated=false to the consumer 192.168.56.1 use dubbo version 3.1.10
	at org.apache.dubbo.config.ReferenceConfig.checkInvokerAvailable(ReferenceConfig.java:668)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:309)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:232)
	at com.wang.student.student.dubbo.GenericServiceTest.main(GenericServiceTest.java:58)
```

**Comment by xieshouyu** [comment]
no provider 是不是 因为 没有version

**Comment by cy1ng** [comment]
@CrazyHZM 当前不支持应用级服务注册的泛化调用吗

**Comment by CrazyHZM** [comment]
Supported, please try the latest version.
@cy1ng
