### ISSUE TITLE
Cannot invoke "org.apache.dubbo.common.URL.getSide(String)" because the return value of "org.apache.dubbo.rpc.RpcServiceContext.getUrl()" is null

### ISSUE THREAD

**Issue by ldcsaa** [apache/dubbo#12778]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.4
* Operating System version: Win10
* Java version: JDK17

### Steps to reproduce this issue

1. start provider
2. start consumer
3. consumer 启动时会调用provider，加载Metadata
4. 进入自定义filter
5. 自定义filter调用 RpcContext.getServiceContext().isConsumerSide()
6. 报告 NPE 异常

```
2023-07-24 00:01:32.568 ERROR [Dubbo-framework-metadata-retry-thread-1] ?#(L:) ->  [DUBBO] Failed to get app metadata for revision b384072965c05583421a94c95d869418 for type local from instance 192.168.59.1:6002, dubbo version: 3.2.4, current host: 192.168.59.1, error code: 1-39. This may be caused by , go to https://dubbo.apache.org/faq/1/39 to find instructions. org.apache.dubbo.rpc.RpcException: Failed to invoke remote method: getMetadataInfo, provider: dubbo://192.168.59.1:6002/org.apache.dubbo.metadata.MetadataService?connections=1&corethreads=2&dubbo=2.0.2&group=hp-demo-infra-service&port=6002&prefer.serialization=fastjson2&protocol=dubbo&release=3.2.4&retries=0&serialization=fastjson2&side=provider&threadpool=cached&threads=100&timeout=5000&version=1.0.0, cause: org.apache.dubbo.remoting.RemotingException: java.lang.NullPointerException: Cannot invoke "org.apache.dubbo.common.URL.getSide(String)" because the return value of "org.apache.dubbo.rpc.RpcServiceContext.getUrl()" is null
java.lang.NullPointerException: Cannot invoke "org.apache.dubbo.common.URL.getSide(String)" because the return value of "org.apache.dubbo.rpc.RpcServiceContext.getUrl()" is null
	at org.apache.dubbo.rpc.RpcServiceContext.isConsumerSide(RpcServiceContext.java:146)
	at com.github.hpsocket.soa.framework.web.dubbo.filter.DubboMdcFilter.invoke(DubboMdcFilter.java:32)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CallbackRegistrationInvoker.invoke(FilterChainBuilder.java:196)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:156)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:110)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:200)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:53)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:62)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
	at java.base/java.lang.Thread.run(Thread.java:833)

	at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:296) ~[dubbo-3.2.4.jar:3.2.4]
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:190) ~[dubbo-3.2.4.jar:3.2.4]
	at org.apache.dubbo.rpc.proxy.InvocationUtil.invoke(InvocationUtil.java:57) ~[dubbo-3.2.4.jar:3.2.4]
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:75) ~[dubbo-3.2.4.jar:3.2.4]
	at org.apache.dubbo.metadata.MetadataServiceDubboProxy1.getMetadataInfo(MetadataServiceDubboProxy1.java) ~[dubbo-3.2.4.jar:3.2.4]
	at org.apache.dubbo.registry.client.metadata.MetadataUtils.getRemoteMetadata(MetadataUtils.java:173) ~[dubbo-3.2.4.jar:3.2.4]
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.lambda$getRemoteMetadata$2(AbstractServiceDiscovery.java:227) ~[dubbo-3.2.4.jar:3.2.4]
	at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:88) ~[dubbo-3.2.4.jar:3.2.4]
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.getRemoteMetadata(AbstractServiceDiscovery.java:226) ~[dubbo-3.2.4.jar:3.2.4]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.lambda$doOnEvent$2(ServiceInstancesChangedListener.java:165) ~[dubbo-3.2.4.jar:3.2.4]
	at java.util.Optional.orElseGet(Optional.java:364) [?:?]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.doOnEvent(ServiceInstancesChangedListener.java:165) [dubbo-3.2.4.jar:3.2.4]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.onEvent(ServiceInstancesChangedListener.java:119) [dubbo-3.2.4.jar:3.2.4]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener$AddressRefreshRetryTask.run(ServiceInstancesChangedListener.java:496) [dubbo-3.2.4.jar:3.2.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.util.concurrent.ExecutionException: org.apache.dubbo.remoting.RemotingException: java.lang.NullPointerException: Cannot invoke "org.apache.dubbo.common.URL.getSide(String)" because the return value of "org.apache.dubbo.rpc.RpcServiceContext.getUrl()" is null
java.lang.NullPointerException: Cannot invoke "org.apache.dubbo.common.URL.getSide(String)" because the return value of "org.apache.dubbo.rpc.RpcServiceContext.getUrl()" is null
	at org.apache.dubbo.rpc.RpcServiceContext.isConsumerSide(RpcServiceContext.java:146)
	at com.github.hpsocket.soa.framework.web.dubbo.filter.DubboMdcFilter.invoke(DubboMdcFilter.java:32)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CallbackRegistrationInvoker.invoke(FilterChainBuilder.java:196)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:156)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:110)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:200)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:53)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:62)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
	at java.base/java.lang.Thread.run(Thread.java:833)

	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096) ~[?:?]
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:218) ~[dubbo-3.2.4.jar:3.2.4]
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:287) ~[dubbo-3.2.4.jar:3.2.4]
	... 19 more
Caused by: org.apache.dubbo.remoting.RemotingException: java.lang.NullPointerException: Cannot invoke "org.apache.dubbo.common.URL.getSide(String)" because the return value of "org.apache.dubbo.rpc.RpcServiceContext.getUrl()" is null
java.lang.NullPointerException: Cannot invoke "org.apache.dubbo.common.URL.getSide(String)" because the return value of "org.apache.dubbo.rpc.RpcServiceContext.getUrl()" is null
	at org.apache.dubbo.rpc.RpcServiceContext.isConsumerSide(RpcServiceContext.java:146)
	at com.github.hpsocket.soa.framework.web.dubbo.filter.DubboMdcFilter.invoke(DubboMdcFilter.java:32)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CallbackRegistrationInvoker.invoke(FilterChainBuilder.java:196)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:156)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:110)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:200)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:53)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:62)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
	at java.base/java.lang.Thread.run(Thread.java:833)

	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.doReceived(DefaultFuture.java:249) ~[dubbo-3.2.4.jar:3.2.4]
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:200) ~[dubbo-3.2.4.jar:3.2.4]
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:188) ~[dubbo-3.2.4.jar:3.2.4]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleResponse(HeaderExchangeHandler.java:65) ~[dubbo-3.2.4.jar:3.2.4]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:206) ~[dubbo-3.2.4.jar:3.2.4]
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:53) ~[dubbo-3.2.4.jar:3.2.4]
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:62) ~[dubbo-3.2.4.jar:3.2.4]
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor$RunnableWrapper.run(ThreadlessExecutor.java:152) ~[dubbo-3.2.4.jar:3.2.4]
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:77) ~[dubbo-3.2.4.jar:3.2.4]
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:205) ~[dubbo-3.2.4.jar:3.2.4]
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:287) ~[dubbo-3.2.4.jar:3.2.4]
	... 19 more

```

**Comment by xixingya** [comment]
没有复现这个问题，我这边是正常获取的，是不是你provider没注册上

**Comment by ldcsaa** [comment]
> 没有复现这个问题，我这边是正常获取的，是不是你provider没注册上

我的现象是：
1、consumer启动时向provider查询Meta信息（getMetadataInfo()）,provider就进入了自定义过滤器，而这时的RpcContext.getServiceContext()..getUrl()为null
2、正常的服务接口调用不会出现上述问题
3、暂时通过以下代码回避这个问题
```
RpcServiceContext ctx = RpcContext.getServiceContext();
if(ctx.getUrl() == null)
    return invoker.invoke(invocation);
```

我的配置文件（只启用dubbo协议）：
```
# Consumer
dubbo.metadata-report.address=nacos://nacos:123456@192.168.56.23:8848
dubbo.registry.simplified=true
dubbo.protocol.name=dubbo
dubbo.protocol.port=5001
dubbo.consumer.filter=mdc
dubbo.provider.filter=mdc

# Provider
dubbo.metadata-report.address=nacos://nacos:123456@192.168.56.23:8848
dubbo.registry.simplified=true
dubbo.protocol.name=dubbo
dubbo.protocol.port=5002
dubbo.consumer.filter=mdc
dubbo.provider.filter=mdc
```

**Comment by AlbumenJ** [comment]
How do you define your Filter? It stands to reason that the current version should not be loaded into the Filter

**Comment by wsandchengxuyuan** [comment]
你好，我这边遇到与你相同的问题，请问你这边已经解决了嘛

**Comment by CrazyHZM** [comment]
@wsandchengxuyuan 
Please provide a demo to reproduce it.

**Comment by wsandchengxuyuan** [comment]
> @wsandchengxuyuan Please provide a demo to reproduce it.
我现在使用的doubbo 3.2.5版本
和上述步骤一样：
Steps to reproduce this issue
start provider
start consumer
consumer 启动时会调用provider，加载Metadata
进入自定义filter
自定义filter调用 RpcContext.getServiceContext().isProviderSide()
消费者这边控制台一直打印报错
` Failed to get app metadata for revision eeda6ca9ea9b15a50ce93efc56bcf5f2 for type local from instance xx.xx.xx.xx:xxxxx, dubbo version: 3.2.5, current host: xx.xx.xx.xx:xxxxx, error code: 1-39. This may be caused by , go to https://dubbo.apache.org/faq/1/39 to find instructions. org.apache.dubbo.rpc.RpcException: Failed to invoke remote method: getMetadataInfo, provider: dubbo://xx.xx.xx.xx:xxxxx/org.apache.dubbo.metadata.MetadataService?connections=1&corethreads=2&dubbo=2.0.2&group=xxxx&port=xxxxx&prefer.serialization=fastjson2,hessian2&protocol=dubbo&release=3.2.5&retries=0&side=consumer&threadpool=cached&threads=100&timeout=5000&version=1.0.0, cause: org.apache.dubbo.remoting.RemotingException: java.lang.NullPointerException
java.lang.NullPointerException

        at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:296)
        at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:190)
        at org.apache.dubbo.rpc.proxy.InvocationUtil.invoke(InvocationUtil.java:61)
        at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:75)
        at org.apache.dubbo.metadata.MetadataServiceDubboProxy21.getMetadataInfo(MetadataServiceDubboProxy21.java)
        at org.apache.dubbo.registry.client.metadata.MetadataUtils.getRemoteMetadata(MetadataUtils.java:173)
        at org.apache.dubbo.registry.client.AbstractServiceDiscovery.lambda$getRemoteMetadata$2(AbstractServiceDiscovery.java:229)
        at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:90)
        at org.apache.dubbo.registry.client.AbstractServiceDiscovery.getRemoteMetadata(AbstractServiceDiscovery.java:228)
        at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.lambda$doOnEvent$2(ServiceInstancesChangedListener.java:162)
        at java.util.Optional.orElseGet(Optional.java:267)
        at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.doOnEvent(ServiceInstancesChangedListener.java:162)
        at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.onEvent(ServiceInstancesChangedListener.java:116)
        at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener$AddressRefreshRetryTask.run(ServiceInstancesChangedListener.java:489)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

`

**Comment by CrazyHZM** [comment]
@wsandchengxuyuan Try it on the latest version.

**Comment by wsandchengxuyuan** [comment]
@CrazyHZM 使用当前版本 可以使用上述代码规避这个问题吗？
`RpcServiceContext ctx = RpcContext.getServiceContext();
if(ctx.getUrl() == null)
    return invoker.invoke(invocation);`

**Comment by CrazyHZM** [comment]
> @CrazyHZM 使用当前版本 可以使用上述代码规避这个问题吗？ `RpcServiceContext ctx = RpcContext.getServiceContext(); if(ctx.getUrl() == null) return invoker.invoke(invocation);`

Sure.
