### ISSUE TITLE
没有任何zookeeper包,为什么会有zookeeper相关的报错

### ISSUE THREAD

**Issue by zwingf** [apache/dubbo#12791]
当我重启服务的时候报错,我确定了依赖包中没有任何zookeeper相关

`20:07:50.670 [SpringApplicationShutdownHook] ERROR o.a.d.c.d.DefaultApplicationDeployer - [error,101] -  [DUBBO] Dubbo Application[1.1](juxing-cp-web-app) an error occurred while stopping application: org/apache/dubbo/common/function/ThrowableAction, dubbo version: 3.2.4, current host: 172.20.54.57, error code: 5-14. This may be caused by , go to https://dubbo.apache.org/faq/5/14 to find instructions. 
java.lang.NoClassDefFoundError: org/apache/dubbo/common/function/ThrowableAction
	at org.apache.dubbo.common.lang.ShutdownHookCallbacks.lambda$callback$0(ShutdownHookCallbacks.java:75)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.apache.dubbo.common.lang.ShutdownHookCallbacks.callback(ShutdownHookCallbacks.java:75)
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.executeShutdownCallbacks(DefaultApplicationDeployer.java:1057)
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.postDestroy(DefaultApplicationDeployer.java:1037)
	at org.apache.dubbo.rpc.model.ApplicationModel.onDestroy(ApplicationModel.java:169)
	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:121)
	at org.apache.dubbo.rpc.model.ApplicationModel.tryDestroy(ApplicationModel.java:272)
	at org.apache.dubbo.rpc.model.ModuleModel.onDestroy(ModuleModel.java:132)
	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:121)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextClosedEvent(DubboDeployApplicationListener.java:169)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:141)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:50)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1034)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:173)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1001)
	at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:139)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:108)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: org.apache.dubbo.common.function.ThrowableAction
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:149)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 25 common frames omitted
20:07:50.672 [SpringApplicationShutdownHook] ERROR o.a.d.r.m.ScopeModel - [error,101] -  [DUBBO] Error happened when destroying ScopeModel., dubbo version: 3.2.4, current host: 172.20.54.57, error code: 5-13. This may be caused by , go to https://dubbo.apache.org/faq/5/13 to find instructions. 
java.lang.AssertionError: Package org.apache.dubbo.remoting.zookeeper has already been defined but it could not be found
	at org.springframework.boot.loader.LaunchedURLClassLoader.definePackageIfNecessary(LaunchedURLClassLoader.java:206)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:138)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.apache.dubbo.remoting.RemotingScopeModelInitializer.lambda$initializeApplicationModel$0(RemotingScopeModelInitializer.java:48)
	at org.apache.dubbo.rpc.model.ScopeModel.notifyDestroy(ScopeModel.java:147)
	at org.apache.dubbo.rpc.model.ApplicationModel.onDestroy(ApplicationModel.java:173)
	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:121)
	at org.apache.dubbo.rpc.model.ApplicationModel.tryDestroy(ApplicationModel.java:272)
	at org.apache.dubbo.rpc.model.ModuleModel.onDestroy(ModuleModel.java:132)
	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:121)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextClosedEvent(DubboDeployApplicationListener.java:169)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:141)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:50)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1034)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:173)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1001)
	at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:139)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:108)
	at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by songxiaosheng** [comment]
java.lang.NoClassDefFoundError: org/apache/dubbo/common/function/ThrowableAction 这个错误原因应该是你进程没关闭就拷贝包导致类被卸载了
Package org.apache.dubbo.remoting.zookeeper has already been defined but it could not be found at  这个zookeeper类型不是zookeeper包里面的是dubbo-remoting-api包里面的一些类型，这些代码可以移动到zookeeper扩展模块
<img width="904" alt="image" src="https://github.com/apache/dubbo/assets/81170548/ffdf7ac5-a5ba-45cb-a114-fa05ebc01dc9">
