### ISSUE TITLE
动态修改rest接口配置，reExport 过程报错

### ISSUE THREAD

**Issue by sick-cat** [apache/dubbo#12802]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.4
* Operating System version:  macOS 13.4.1
* Java version: 8

### Steps to reproduce this issue

1. 通过rest协议暴露dubbo接口
  java代码：
    ```java
    @Path("/testing")
    public class RestProtocolTestingServiceImpl implements RestProtocolTestingService {
        @Override
        @GET
        @Path("/boolean")
        public Boolean getFalse() {
            return Boolean.FALSE;
        }
    }
    ```

    xml配置：
      ```xml
      <bean id="restProtocolTestingService" class="com.mytest.dubbo.protocol.RestProtocolTestingServiceImpl"/>
      <dubbo:service interface="com.mytest.dubbo.protocol.RestProtocolTestingService" ref="restProtocolTestingService" register="false" delay="-1" protocol="rest"/>
      ```
2. 启动服务
3. apollo 中新增配置并发布
  key: dubbo-testing.configurators
  value:
      ```yaml
      configVersion: v3.0
      scope: application
      key: dubbo-testing
      configs:
        - side: provider
          parameters:
            timeout: 2345
            owner: apollo-provider
      ```

### Expected Behavior

apollo配置生效，接口元数据中有timeout和owner参数

### Actual Behavior

exception trace:

```

[Apollo-Config-3]  c.c.f.apollo.internals.AbstractConfig    : Failed to invoke config change listener org.apache.dubbo.configcenter.support.apollo.ApolloDynamicConfiguration$ApolloListener

org.apache.dubbo.rpc.protocol.rest.exception.DoublePathCheckException: dubbo rest double path check error, current path is: PathMatcher{path='/testing/boolean', version='null', group='null', port=null, hasPathVariable=false, contextPath='null', httpMethod='GET'} ,and service method
 is: public java.lang.Boolean com.mytest.dubbo.protocol.RestProtocolTestingServiceImpl.getFalse()before service  method is: public java.lang.Boolean com.mytest.dubbo.protocol.RestProtocolTestingServiceImpl.getFalse()
        at org.apache.dubbo.rpc.protocol.rest.PathAndInvokerMapper.addPathMatcherToPathMap(PathAndInvokerMapper.java:108)
        at org.apache.dubbo.rpc.protocol.rest.PathAndInvokerMapper.lambda$addPathAndInvoker$0(PathAndInvokerMapper.java:53)
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at org.apache.dubbo.rpc.protocol.rest.PathAndInvokerMapper.addPathAndInvoker(PathAndInvokerMapper.java:48)
        at org.apache.dubbo.rpc.protocol.rest.deploy.ServiceDeployer.deploy(ServiceDeployer.java:61)
        at org.apache.dubbo.rpc.protocol.rest.NettyHttpRestServer.deploy(NettyHttpRestServer.java:177)
        at org.apache.dubbo.rpc.protocol.rest.RestProtocol.export(RestProtocol.java:105)
        at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:80)
        at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:73)
        at org.apache.dubbo.rpc.protocol.ProtocolSecurityWrapper.export(ProtocolSecurityWrapper.java:83)
        at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:61)
        at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47)
        at org.apache.dubbo.rpc.protocol.InvokerCountWrapper.export(InvokerCountWrapper.java:42)
        at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
        at org.apache.dubbo.registry.integration.RegistryProtocol.reExport(RegistryProtocol.java:363)
        at org.apache.dubbo.registry.integration.RegistryProtocol$OverrideListener.doOverrideIfNecessary(RegistryProtocol.java:831)
        at org.apache.dubbo.registry.integration.RegistryProtocol$ProviderConfigurationListener.lambda$notifyOverrides$0(RegistryProtocol.java:929)
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
        at org.apache.dubbo.registry.integration.RegistryProtocol$ProviderConfigurationListener.notifyOverrides(RegistryProtocol.java:927)
        at org.apache.dubbo.registry.integration.AbstractConfiguratorListener.process(AbstractConfiguratorListener.java:102)
        at org.apache.dubbo.configcenter.support.apollo.ApolloDynamicConfiguration$ApolloListener.lambda$onChange$0(ApolloDynamicConfiguration.java:255)
        at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
        at java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:404)
        at org.apache.dubbo.configcenter.support.apollo.ApolloDynamicConfiguration$ApolloListener.onChange(ApolloDynamicConfiguration.java:255)
        at com.ctrip.framework.apollo.internals.AbstractConfig$2.run(AbstractConfig.java:470)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by suncairong163** [comment]
rest 服务发布的时候，会对path进行重复校验，类似mvc 那种，不能有重复的path,动态配置会重新解析服务接口，这个时候会抛校验错误，我这边适配一下
