### ISSUE TITLE
dubbo3.2.0 rest请求Dubbo-thread-1 线程泄漏

### ISSUE THREAD

**Issue by mnshun** [apache/dubbo#12803]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.0
* Operating System version: Linux  4.19.91-685c634.al7.x86_64
* Java version: 17.0.3

JVM parameters
[-javaagent:/home/admin/.opt/ArmsAgent/arms-bootstrap-1.7.0-SNAPSHOT.jar, -Darms.licenseKey=[******], -Darms.appId=0a3e7725-91be-4ea7-872c-7fc95a2319da, -Darms.agent.env=Serverless, -Darms.agent.args=, -Dprofiler.micro.service.canary.enable=true, -Dprofiler.micro.service.metadata.report.enable=true, -Dprofiler.micro.service.http.server.enable=true, -Dmsc.appName=cn-beijing-002-lucas-team-start-test-0a3e77, -Dmsc.licenseKey=[******], -Darms.host.tags=namespace:002, -XX:+UseG1GC, -Dnacos.use.endpoint.parsing.rule=false, -Dnacos.use.cloud.namespace.parsing=false, --add-opens=java.base/java.lang.reflect=ALL-UNNAMED, --add-opens=java.base/java.util=ALL-UNNAMED, --add-opens=java.base/java.lang=ALL-UNNAMED, --add-opens=java.base/java.math=ALL-UNNAMED]

### Steps to reproduce this issue

1. JVM memory leak, the troubleshooting indicates a thread leak. Below is the jstack:
2. cat 1.jstack |grep 'Dubbo-thread-1' |wc -l  ，result: 4015
3. thread dump analyze：https://fastthread.io/my-thread-report.jsp?p=c2hhcmVkLzIwMjMvMDcvMjcvMS5qc3RhY2stLTgtMjctOQ==&

[ft-report-1.pdf](https://github.com/apache/dubbo/files/12181234/ft-report-1.pdf)

"Dubbo-thread-1" #500373 daemon prio=5 os_prio=0 cpu=0.88ms elapsed=2029.18s tid=0x00007ffb06cb1360 nid=0x8d24f waiting on condition  [0x00007ff9ed5e4000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.3/Native Method)
	- parking to wait for  <0x00000000f1219128> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.3/LockSupport.java:341)
	at java.util.concurrent.SynchronousQueue$TransferStack$SNode.block(java.base@17.0.3/SynchronousQueue.java:288)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.3/ForkJoinPool.java:3463)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.3/ForkJoinPool.java:3434)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(java.base@17.0.3/SynchronousQueue.java:397)
	at java.util.concurrent.SynchronousQueue.take(java.base@17.0.3/SynchronousQueue.java:886)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@17.0.3/ThreadPoolExecutor.java:1062)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.3/ThreadPoolExecutor.java:1122)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.3/ThreadPoolExecutor.java:635)
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(Unknown Source)
	at java.lang.Thread.run(java.base@17.0.3/Thread.java:833)

"Dubbo-thread-1" #500374 daemon prio=5 os_prio=0 cpu=3.31ms elapsed=2029.17s tid=0x00007ffb2858fc20 nid=0x8d250 waiting on condition  [0x00007ff9ecbda000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.3/Native Method)
	- parking to wait for  <0x00000000f1219390> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.3/LockSupport.java:341)
	at java.util.concurrent.SynchronousQueue$TransferStack$SNode.block(java.base@17.0.3/SynchronousQueue.java:288)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.3/ForkJoinPool.java:3463)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.3/ForkJoinPool.java:3434)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(java.base@17.0.3/SynchronousQueue.java:397)
	at java.util.concurrent.SynchronousQueue.take(java.base@17.0.3/SynchronousQueue.java:886)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@17.0.3/ThreadPoolExecutor.java:1062)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.3/ThreadPoolExecutor.java:1122)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.3/ThreadPoolExecutor.java:635)
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(Unknown Source)
	at java.lang.Thread.run(java.base@17.0.3/Thread.java:833)

![image](https://github.com/apache/dubbo/assets/12005228/be8cd88c-536f-441c-9643-6510dbed6dc5)
![image](https://github.com/apache/dubbo/assets/12005228/d1d769f4-af77-409f-85f6-cb7ea482c431)

dubbo:
  protocols:
    rest:
      name: rest
      port: 9080
      server: netty

本地访问 localhost:9080/xxx/xxx，必现

**Comment by AlbumenJ** [comment]
有内存 Dump 吗，jmap -dump:format=b,file=dump.bin pid

**Comment by mnshun** [comment]
![image](https://github.com/apache/dubbo/assets/12005228/e05545e2-4cf4-4fa7-8236-edeaebb104b5)
![image](https://github.com/apache/dubbo/assets/12005228/6caceb18-fa9f-44ab-868a-66d6b50e1643)

这两个分析可以么，还是需要把整个文件上传一下啊？

**Comment by AlbumenJ** [comment]
> ![image](https://user-images.githubusercontent.com/12005228/257126202-e05545e2-4cf4-4fa7-8236-edeaebb104b5.png) ![image](https://user-images.githubusercontent.com/12005228/257126341-0a28ad63-c4f1-4342-a4c6-a84fec45c2d2.png)
> 
> 这两个分析可以么，还是需要把整个文件上传一下啊？

单加下我钉钉吧，albumenj

**Comment by AlbumenJ** [comment]
@suncairong163 PTAL

**Comment by flybh521** [comment]
你好   这个问题解决了吗

**Comment by flybh521** [comment]
我现在也是卡住调用线程 
"Thread-52-EventThread" #165 daemon prio=5 os_prio=0 tid=0x00007fc7403c6800 nid=0x478c waiting on condition [0x00007fc5b13aa000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000679795478> (a org.apache.dubbo.common.threadpool.ThreadlessExecutor)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:62)
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:202)
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:286)
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:189)
	at org.apache.dubbo.rpc.proxy.InvocationUtil.invoke(InvocationUtil.java:57)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:75)
	at org.apache.dubbo.metadata.MetadataServiceDubboProxy0.getMetadataInfo(MetadataServiceDubboProxy0.java)
	at org.apache.dubbo.registry.client.metadata.MetadataUtils.getRemoteMetadata(MetadataUtils.java:173)
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.lambda$getRemoteMetadata$2(AbstractServiceDiscovery.java:227)
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery$$Lambda$854/469064277.get(Unknown Source)
	at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:104)
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.getRemoteMetadata(AbstractServiceDiscovery.java:226)
	- locked <0x000000066ecbe7e0> (a org.apache.dubbo.registry.client.metadata.store.MetaCacheManager)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.lambda$doOnEvent$2(ServiceInstancesChangedListener.java:165)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener$$Lambda$853/1898979814.get(Unknown Source)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.doOnEvent(ServiceInstancesChangedListener.java:165)
	- locked <0x00000006791fe9a0> (a org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.onEvent(ServiceInstancesChangedListener.java:119)
	at org.apache.dubbo.registry.zookeeper.ZookeeperServiceDiscovery.registerServiceWatcher(ZookeeperServiceDiscovery.java:211)
	at org.apache.dubbo.registry.zookeeper.ZookeeperServiceDiscovery.lambda$addServiceInstancesChangedListener$3(ZookeeperServiceDiscovery.java:157)
	at org.apache.dubbo.registry.zookeeper.ZookeeperServiceDiscovery$$Lambda$881/534704249.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.apache.dubbo.registry.zookeeper.ZookeeperServiceDiscovery.addServiceInstancesChangedListener(ZookeeperServiceDiscovery.java:157)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.lambda$subscribeURLs$0(ServiceDiscoveryRegistry.java:334)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry$$Lambda$880/597598000.get(Unknown Source)
	at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:95)
	at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:62)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribeURLs(ServiceDiscoveryRegistry.java:332)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry$DefaultMappingListener.onEvent(ServiceDiscoveryRegistry.java:422)
	- locked <0x000000066ff6a610> (a org.apache.dubbo.registry.client.ServiceDiscoveryRegistry$DefaultMappingListener)
	at org.apache.dubbo.metadata.store.zookeeper.ZookeeperMetadataReport$MappingDataListener.lambda$dataChanged$0(ZookeeperMetadataReport.java:268)
	at org.apache.dubbo.metadata.store.zookeeper.ZookeeperMetadataReport$MappingDataListener$$Lambda$847/675272494.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.apache.dubbo.metadata.store.zookeeper.ZookeeperMetadataReport$MappingDataListener.dataChanged(ZookeeperMetadataReport.java:268)
	at org.apache.dubbo.remoting.zookeeper.curator5.Curator5ZookeeperClient$NodeCacheListenerImpl.nodeChanged(Curator5ZookeeperClient.java:430)
	at org.apache.curator.framework.recipes.cache.NodeCache.lambda$setNewData$0(NodeCache.java:323)
	at org.apache.curator.framework.recipes.cache.NodeCache$$Lambda$846/383337552.accept(Unknown Source)
	at org.apache.curator.framework.listen.MappingListenerManager.lambda$forEach$0(MappingListenerManager.java:92)
	at org.apache.curator.framework.listen.MappingListenerManager$$Lambda$560/521862646.run(Unknown Source)
	at org.apache.curator.framework.listen.MappingListenerManager$$Lambda$556/1666438914.execute(Unknown Source)
	at org.apache.curator.framework.listen.MappingListenerManager.forEach(MappingListenerManager.java:89)
	at org.apache.curator.framework.listen.StandardListenerManager.forEach(StandardListenerManager.java:89)
	at org.apache.curator.framework.recipes.cache.NodeCache.setNewData(NodeCache.java:320)
	at org.apache.curator.framework.recipes.cache.NodeCache.processBackgroundResult(NodeCache.java:288)
	at org.apache.curator.framework.recipes.cache.NodeCache.access$300(NodeCache.java:60)
	at org.apache.curator.framework.recipes.cache.NodeCache$3.processResult(NodeCache.java:126)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:892)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:649)
	at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152)
	at org.apache.curator.framework.imps.GetDataBuilderImpl$3.processResult(GetDataBuilderImpl.java:272)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:634)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:553)

**Comment by AlbumenJ** [comment]
> 我现在也是卡住调用线程 "Thread-52-EventThread" #165 daemon prio=5 os_prio=0 tid=0x00007fc7403c6800 nid=0x478c waiting on condition [0x00007fc5b13aa000] java.lang.Thread.State: WAITING (parking) at sun.misc.Unsafe.park(Native Method) - parking to wait for <0x0000000679795478> (a org.apache.dubbo.common.threadpool.ThreadlessExecutor) at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175) at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:62) at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:202) at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:286) at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:189) at org.apache.dubbo.rpc.proxy.InvocationUtil.invoke(InvocationUtil.java:57) at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:75) at org.apache.dubbo.metadata.MetadataServiceDubboProxy0.getMetadataInfo(MetadataServiceDubboProxy0.java) at org.apache.dubbo.registry.client.metadata.MetadataUtils.getRemoteMetadata(MetadataUtils.java:173) at org.apache.dubbo.registry.client.AbstractServiceDiscovery.lambda$getRemoteMetadata$2(AbstractServiceDiscovery.java:227) at org.apache.dubbo.registry.client.AbstractServiceDiscovery$$Lambda$854/469064277.get(Unknown Source) at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:104) at org.apache.dubbo.registry.client.AbstractServiceDiscovery.getRemoteMetadata(AbstractServiceDiscovery.java:226) - locked <0x000000066ecbe7e0> (a org.apache.dubbo.registry.client.metadata.store.MetaCacheManager) at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.lambda$doOnEvent$2(ServiceInstancesChangedListener.java:165) at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener$$Lambda$853/1898979814.get(Unknown Source) at java.util.Optional.orElseGet(Optional.java:267) at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.doOnEvent(ServiceInstancesChangedListener.java:165) - locked <0x00000006791fe9a0> (a org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener) at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.onEvent(ServiceInstancesChangedListener.java:119) at org.apache.dubbo.registry.zookeeper.ZookeeperServiceDiscovery.registerServiceWatcher(ZookeeperServiceDiscovery.java:211) at org.apache.dubbo.registry.zookeeper.ZookeeperServiceDiscovery.lambda$addServiceInstancesChangedListener$3(ZookeeperServiceDiscovery.java:157) at org.apache.dubbo.registry.zookeeper.ZookeeperServiceDiscovery$$Lambda$881/534704249.accept(Unknown Source) at java.lang.Iterable.forEach(Iterable.java:75) at org.apache.dubbo.registry.zookeeper.ZookeeperServiceDiscovery.addServiceInstancesChangedListener(ZookeeperServiceDiscovery.java:157) at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.lambda$subscribeURLs$0(ServiceDiscoveryRegistry.java:334) at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry$$Lambda$880/597598000.get(Unknown Source) at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:95) at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:62) at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribeURLs(ServiceDiscoveryRegistry.java:332) at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry$DefaultMappingListener.onEvent(ServiceDiscoveryRegistry.java:422) - locked <0x000000066ff6a610> (a org.apache.dubbo.registry.client.ServiceDiscoveryRegistry$DefaultMappingListener) at org.apache.dubbo.metadata.store.zookeeper.ZookeeperMetadataReport$MappingDataListener.lambda$dataChanged$0(ZookeeperMetadataReport.java:268) at org.apache.dubbo.metadata.store.zookeeper.ZookeeperMetadataReport$MappingDataListener$$Lambda$847/675272494.accept(Unknown Source) at java.lang.Iterable.forEach(Iterable.java:75) at org.apache.dubbo.metadata.store.zookeeper.ZookeeperMetadataReport$MappingDataListener.dataChanged(ZookeeperMetadataReport.java:268) at org.apache.dubbo.remoting.zookeeper.curator5.Curator5ZookeeperClient$NodeCacheListenerImpl.nodeChanged(Curator5ZookeeperClient.java:430) at org.apache.curator.framework.recipes.cache.NodeCache.lambda$setNewData$0(NodeCache.java:323) at org.apache.curator.framework.recipes.cache.NodeCache$$Lambda$846/383337552.accept(Unknown Source) at org.apache.curator.framework.listen.MappingListenerManager.lambda$forEach$0(MappingListenerManager.java:92) at org.apache.curator.framework.listen.MappingListenerManager$$Lambda$560/521862646.run(Unknown Source) at org.apache.curator.framework.listen.MappingListenerManager$$Lambda$556/1666438914.execute(Unknown Source) at org.apache.curator.framework.listen.MappingListenerManager.forEach(MappingListenerManager.java:89) at org.apache.curator.framework.listen.StandardListenerManager.forEach(StandardListenerManager.java:89) at org.apache.curator.framework.recipes.cache.NodeCache.setNewData(NodeCache.java:320) at org.apache.curator.framework.recipes.cache.NodeCache.processBackgroundResult(NodeCache.java:288) at org.apache.curator.framework.recipes.cache.NodeCache.access$300(NodeCache.java:60) at org.apache.curator.framework.recipes.cache.NodeCache$3.processResult(NodeCache.java:126) at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:892) at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:649) at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152) at org.apache.curator.framework.imps.GetDataBuilderImpl$3.processResult(GetDataBuilderImpl.java:272) at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:634) at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:553)

这个堆栈请检查和 Provider 的网络连接情况，这个是 Metadata 请求超时了，这个 PR 对应的问题已经在 3.2.6 解决
