### ISSUE TITLE
KeeperErrorCode = NoNode for /dubbo/metadata

### ISSUE THREAD

**Issue by WangXiaoJin** [apache/dubbo#12843]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.3
* Operating System version: CentOS
* Java version: 8

### Steps to reproduce this issue

启用ZK远程元数据中心：
  ```yaml
  dubbo:
    application:
      # metadata 信息从远端元数据中心获取
      metadata-type: remote
  ```
应用启动后ZK元数据中心有metadata 数据，但第二天发现metadata 数据被删除了，并报以下异常：

```
[DUBBO] Failed to put provider metadata org.apache.dubbo.metadata.report.identifier.MetadataIdentifier@142ad493 in  FullServiceDefinition{parameters={anyhost=true, release=3.2.3, interface=com.xxx, dubbo=2.0.2, application=xxx, metadata-type=remote, pid=1, side=provider, check.serializable=false, executor-management-mode=isolation, file-cache=true, methods=jySendSms,sendSms,sendSms,sendSmsWithSign,sendWithReply, logger=slf4j, deprecated=false, qos.port=22222, service-name-mapping=true, qos.enable=true, timeout=10000, bind.port=23001, generic=false, serialize.check.status=DISABLE, retries=0, delay=-1, bind.ip=10.90.15.20, prefer.serialization=hessian2, background=false, dynamic=true, timestamp=1691051364338}} ServiceDefinition [canonicalName=com.xxx, codeSource=jar:file:/xxx.jar!/BOOT-INF/lib/xxx.jar!/, methods=[MethodDefinition [name=sendSmsWithSign, parameterTypes=[java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String], returnType=java.lang.String], MethodDefinition [name=sendSms, parameterTypes=[java.lang.String, java.lang.String, java.lang.String, java.lang.String], returnType=java.lang.String], MethodDefinition [name=sendSms, parameterTypes=[java.util.List<java.lang.String>, java.lang.String, java.lang.String, java.lang.String, java.lang.String], returnType=java.lang.String], MethodDefinition [name=sendWithReply, parameterTypes=[java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String], returnType=com.xxx], MethodDefinition [name=jySendSms, parameterTypes=[java.lang.String, java.lang.String, java.lang.String, java.lang.String], returnType=java.lang.String]]], cause: KeeperErrorCode = NoNode for /dubbo/metadata/com.xxxe/provider/xxx, dubbo version: 3.2.3, current host: 10.90.15.20, error code: 3-2. This may be caused by , go to https://dubbo.apache.org/faq/3/2 to find instructions. 

o.a.z.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /dubbo/metadata/com.xxx/provider/xxx
	at o.a.z.KeeperException.create(KeeperException.java:114)
	at o.a.z.KeeperException.create(KeeperException.java:54)
	at o.a.z.ZooKeeper.create(ZooKeeper.java:792)
	at o.a.c.f.i.CreateBuilderImpl$17.call(CreateBuilderImpl.java:1176)
	at o.a.c.f.i.CreateBuilderImpl$17.call(CreateBuilderImpl.java:1156)
	at o.a.c.c.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:67)
	at o.a.c.RetryLoop.callWithRetry(RetryLoop.java:81)
	at o.a.c.f.i.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:1153)
	at o.a.c.f.i.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:607)
	at o.a.c.f.i.CreateBuilderImpl.forPath(CreateBuilderImpl.java:597)
	at o.a.c.f.i.CreateBuilderImpl.forPath(CreateBuilderImpl.java:51)
	at o.a.d.r.z.c.CuratorZookeeperClient.createPersistent(CuratorZookeeperClient.java:160)
	... 11 common frames omitted
Wrapped by: j.l.IllegalStateException: KeeperErrorCode = NoNode for /dubbo/metadata/com.xxx/provider/xxx
	at o.a.d.r.z.c.CuratorZookeeperClient.createPersistent(CuratorZookeeperClient.java:174)
	at o.a.d.r.z.c.CuratorZookeeperClient.createOrUpdatePersistent(CuratorZookeeperClient.java:226)
	... 10 common frames omitted
Wrapped by: j.l.IllegalStateException: KeeperErrorCode = NoNode for /dubbo/metadata/com.xxx/provider/xxxx
	at o.a.d.r.z.c.CuratorZookeeperClient.createOrUpdatePersistent(CuratorZookeeperClient.java:229)
	at o.a.d.r.z.AbstractZookeeperClient.createOrUpdate(AbstractZookeeperClient.java:177)
	at o.a.d.m.s.z.ZookeeperMetadataReport.storeMetadata(ZookeeperMetadataReport.java:135)
	at o.a.d.m.s.z.ZookeeperMetadataReport.doStoreProviderMetadata(ZookeeperMetadataReport.java:92)
	at o.a.d.m.r.s.AbstractMetadataReport.lambda$storeProviderMetadataTask$1(AbstractMetadataReport.java:293)
	at o.a.d.m.e.MetricsEventBus.post(MetricsEventBus.java:88)
	at o.a.d.m.r.s.AbstractMetadataReport.storeProviderMetadataTask(AbstractMetadataReport.java:283)
	at o.a.d.m.r.s.AbstractMetadataReport.lambda$storeProviderMetadata$0(AbstractMetadataReport.java:276)
	at j.u.c.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at j.u.c.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at j.l.Thread.run(Thread.java:748)
```

### Expected Behavior

应用还在运行时不应该删除metadata数据

**Comment by songxiaosheng** [comment]
zookeeper是否开启了debug日志看下，日志中这个path的节点被删除的时刻观测下日志发生移除时候的原因

**Comment by WangXiaoJin** [comment]
问题已定位，和Dubbo无关，打扰了

**Comment by 780664893** [comment]
> 问题已定位，和Dubbo无关，打扰了

请问是什么原因啊，遇到同样的问题了

**Comment by WangXiaoJin** [comment]
> > 问题已定位，和Dubbo无关，打扰了
> 
> 请问是什么原因啊，遇到同样的问题了

我们有个定时任务误删了metadata数据
