### ISSUE TITLE
自定义异常fastjson2反序列化失败

### ISSUE THREAD

**Issue by may-fly** [apache/dubbo#12853]
Caused by: org.apache.dubbo.remoting.RemotingException: java.io.IOException: org.apache.dubbo.common.serialize.SerializationException: com.alibaba.fastjson2.JSONException: auotype not support : mayfly.common.core.exception.BizException
java.io.IOException: org.apache.dubbo.common.serialize.SerializationException: com.alibaba.fastjson2.JSONException: auotype not support : mayfly.common.core.exception.BizException

**Comment by AlbumenJ** [comment]
Please refer https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/advanced-features-and-usage/security/class-check/

**Comment by may-fly** [comment]
可以了，3q

**Comment by chihche** [comment]
@may-fly 您好 请问是怎么解决的呢？可否分享一下

**Comment by xiaopangfire** [comment]
怎么解决的

**Comment by xiaopangfire** [comment]
> 
怎么解决的

**Comment by may-fly** [comment]
<img width="767" alt="image" src="https://github.com/apache/dubbo/assets/38199635/9a66ef60-0252-4b35-8518-2efc947f64ca">

**Comment by xiaopangfire** [comment]
> <img alt="image" width="767" src="https://user-images.githubusercontent.com/38199635/263911434-9a66ef60-0252-4b35-8518-2efc947f64ca.png">
这个我加了 而且断点确认加进去了 结果还是不行

**Comment by may-fly** [comment]
同样的错吗，默认构造器啥的有加吗

**Comment by xiaopangfire** [comment]
> 同样的错吗，默认构造器啥的有加吗

感谢 我找到了 手抖用了泛型 尴尬了

**Comment by lichangan18356288293** [comment]
Caused by: com.alibaba.fastjson2.JSONException: auoType not support : com.jabqus.oas.project.project.exception.U9ProjectInvokeException, offset 173
	at com.alibaba.fastjson2.reader.ObjectReaderException.readJSONBObject(ObjectReaderException.java:368)
	at com.alibaba.fastjson2.JSONReaderJSONB.read(JSONReaderJSONB.java:266)
	at com.alibaba.fastjson2.reader.ObjectReaderException.readObject(ObjectReaderException.java:180)
	at com.alibaba.fastjson2.reader.ObjectReaderException.readJSONBObject(ObjectReaderException.java:375)
	at com.alibaba.fastjson2.reader.ObjectReaderException.readJSONBObject(ObjectReaderException.java:371)
	at com.alibaba.fastjson2.JSONReaderJSONB.read(JSONReaderJSONB.java:266)
	at com.alibaba.fastjson2.reader.ObjectReaderException.readObject(ObjectReaderException.java:180)
	at com.alibaba.fastjson2.reader.ObjectReaderException.readJSONBObject(ObjectReaderException.java:375)
	at com.alibaba.fastjson2.JSONReaderJSONB.readAnyObject(JSONReaderJSONB.java:1243)
	at com.alibaba.fastjson2.JSONB.parseObject(JSONB.java:536)
	at org.apache.dubbo.common.serialize.fastjson2.FastJson2ObjectInput.readObject(FastJson2ObjectInput.java:125)
	at org.apache.dubbo.common.serialize.fastjson2.FastJson2ObjectInput.readObject(FastJson2ObjectInput.java:103)
	at org.apache.dubbo.common.serialize.ObjectInput.readThrowable(ObjectInput.java:74)
	at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper$ProxyObjectInput.readThrowable(DefaultSerializationExceptionWrapper.java:184)
	... 10 more

	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.doReceived(DefaultFuture.java:249)
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:200)
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:188)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleResponse(HeaderExchangeHandler.java:65)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:206)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:53)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:62)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
	... 1 common frames omitted

同样的报错dubbo异常设置只是警告还是报错
# dubbo 配置
dubbo:
  application:
    # 关闭qos端口避免单机多生产者端口冲突 如需使用自行开启
    qos-enable: false
    # 取消序列化检查
    serialize-check-status: WARN

但是这个我抛这个异常的父类(也是自定义的异常)就不会触发这个反序列化异常
