### ISSUE TITLE
kill命令无法正常关闭服务

### ISSUE THREAD

**Issue by zwingf** [apache/dubbo#12867]
### 关闭服务时刻的日志(包含info,warn,error)
``` 
19:31:19.296 [nacos-grpc-client-executor-127.0.0.1-70546] INFO  c.a.n.client.naming - [processServiceInfo,169] - current ips:(0) service: DEFAULT_GROUP@@providers:com.tianyincp.juxing.userservice.rpc.admin.UserAdminRpc:: -> []
19:31:19.296 [nacos-grpc-client-executor-127.0.0.1-70546] INFO  c.a.n.c.r.client - [printIfInfoEnabled,63] - [201a15b7-fcd8-4932-bdc1-3f85295a3ba6] Ack server push request, request = NotifySubscriberRequest, requestId = 14635
19:31:19.309 [NettyServerWorker-7-6] INFO  o.a.d.r.t.n.NettyServerHandler - [info,61] -  [DUBBO] The connection of /172.20.54.57:59734 -> /172.20.54.57:20883 is disconnected., dubbo version: 3.2.4, current host: 172.20.54.57
19:31:19.326 [NettyServerWorker-7-7] INFO  o.a.d.r.t.n.NettyServerHandler - [info,61] -  [DUBBO] The connection of /172.20.54.57:59862 -> /172.20.54.57:20883 is disconnected., dubbo version: 3.2.4, current host: 172.20.54.57
19:31:19.343 [SpringApplicationShutdownHook] INFO  o.a.d.r.t.AbstractServer - [info,61] -  [DUBBO] Close NettyServer bind /0.0.0.0:20883, export /172.20.54.57:20883, dubbo version: 3.2.4, current host: 172.20.54.57
19:31:19.410 [com.alibaba.nacos.client.naming.grpc.redo.0] INFO  c.a.n.client.naming - [redoForInstance,73] - Redo instance operation REMOVE for DEFAULT_GROUP@@juxing-user
19:31:19.953 [com.alibaba.nacos.client.naming.grpc.redo.0] INFO  c.a.n.client.naming - [redoForInstance,73] - Redo instance operation REMOVE for DEFAULT_GROUP@@providers:com.tianyincp.juxing.userservice.rpc.teenager.TeenagerRpc::
19:31:42.027 [Dubbo-framework-cache-refreshing-scheduler-thread-1] INFO  o.a.d.m.AbstractCacheManager$CacheRefreshTask - [info,61] -  [DUBBO] Dumping mapping caches, latest entries 10, dubbo version: 3.2.4, current host: 172.20.54.57


19:31:18.746 [SpringApplicationShutdownHook] WARN  o.a.d.r.i.DynamicDirectory - [warn,86] -  [DUBBO] unexpected error when unsubscribe service com.tianyincp.juxing.imservice.rpc.p2p.ImFriendRpc from registry: nacos://127.0.0.1:8848/org.apache.dubbo.registry.RegistryService?application=juxing-user&dubbo=2.0.2&executor-management-mode=isolation&file-cache=true&interface=org.apache.dubbo.registry.RegistryService&password=0PtsWi39&pid=21766&qos.enable=true&qos.port=22225&register=false&release=3.2.4&serialize.check.status=WARN&simplified=true&username=nacos, dubbo version: 3.2.4, current host: 172.20.54.57, error code: 1-8. This may be caused by , go to https://dubbo.apache.org/faq/1/8 to find instructions. 
java.lang.NoClassDefFoundError: org/apache/dubbo/registry/client/NopServiceDiscovery
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.isAvailable(ServiceDiscoveryRegistry.java:281)
	at org.apache.dubbo.registry.ListenerRegistryWrapper.isAvailable(ListenerRegistryWrapper.java:50)
	at org.apache.dubbo.registry.integration.DynamicDirectory.destroy(DynamicDirectory.java:319)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.destroy(ServiceDiscoveryRegistryDirectory.java:154)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.destroy(AbstractClusterInvoker.java:130)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.destroy(MockClusterInvoker.java:88)
	at org.apache.dubbo.rpc.cluster.support.wrapper.ScopeClusterInvoker.destroy(ScopeClusterInvoker.java:126)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.destroy(MigrationInvoker.java:332)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:61)
	at com.tianyincp.juxing.imservice.rpc.p2p.ImFriendRpcDubboProxy5.$destroy(ImFriendRpcDubboProxy5.java)
	at org.apache.dubbo.config.utils.SimpleReferenceCache.destroyReference(SimpleReferenceCache.java:290)
	at org.apache.dubbo.config.utils.SimpleReferenceCache.lambda$destroyAll$4(SimpleReferenceCache.java:279)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at org.apache.dubbo.config.utils.SimpleReferenceCache.destroyAll(SimpleReferenceCache.java:277)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.unreferServices(DefaultModuleDeployer.java:507)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.postDestroy(DefaultModuleDeployer.java:280)
	at org.apache.dubbo.rpc.model.ModuleModel.onDestroy(ModuleModel.java:110)
	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:121)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextClosedEvent(DubboDeployApplicationListener.java:169)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:141)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:50)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1034)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:173)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1001)
	at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:139)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:108)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: org.apache.dubbo.registry.client.NopServiceDiscovery
	... 33 common frames omitted
19:31:19.268 [Dubbo-framework-registry-notification-2-thread-1] WARN  o.a.d.r.n.NacosRegistry - [warn,76] -  [DUBBO] Received empty url address list and empty protection is disabled, will clear current available addresses, dubbo version: 3.2.4, current host: 172.20.54.57, error code: 1-37. This may be caused by , go to https://dubbo.apache.org/faq/1/37 to find instructions. 
19:31:19.326 [NettyServerWorker-7-7] WARN  o.a.d.r.t.AbstractServer - [warn,76] -  [DUBBO] All clients has disconnected from /172.20.54.57:20883. You can graceful shutdown now., dubbo version: 3.2.4, current host: 172.20.54.57, error code: 99-0. This may be caused by unknown error in remoting module, go to https://dubbo.apache.org/faq/99/0 to find instructions. 

19:31:19.345 [NettyServerWorker-7-4] ERROR i.n.u.c.D.rejectedExecution - [safeExecute,864] - Failed to submit a listener notification task. Event loop shut down?
java.lang.NoClassDefFoundError: io/netty/util/concurrent/GlobalEventExecutor$2
	at io.netty.util.concurrent.GlobalEventExecutor.startThread(GlobalEventExecutor.java:228)
	at io.netty.util.concurrent.GlobalEventExecutor.execute0(GlobalEventExecutor.java:216)
	at io.netty.util.concurrent.GlobalEventExecutor.execute(GlobalEventExecutor.java:210)
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:862)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:97)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1059)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: io.netty.util.concurrent.GlobalEventExecutor$2
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:440)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:149)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 12 common frames omitted

```

**Comment by zwingf** [comment]
### 使用restart重启
```
function start() {
    PID=$(ps -ef | grep java | grep $AppName | grep -v grep | awk '{print $2}')

    if [ "x$PID" != "x" ]; then
        echo "$AppName is running..."
    else
        nohup java $JVM_OPTS -jar ./$AppName > /dev/null 2>nohuoerror.log &
        echo "Start $AppName success..."
    fi
}


function stop() {
    echo "Stop $AppName"

    PID=""
    query() {
        PID=$(ps -ef | grep java | grep $AppName | grep -v grep | awk '{print $2}')
    }

    query
    if [ "x$PID" != "x" ]; then
        kill -TERM $PID
        echo "$AppName (pid:$PID) exiting..."
        while [ "x$PID" != "x" ]; do
            sleep 1
            query
        done
        echo "$AppName exited."
    else
        echo "$AppName already stopped."
    fi
}

function restart()
{
    stop
    sleep 10
    start
}
```

**Comment by songxiaosheng** [comment]
这个NoClassDefFoundError 应该是你们进程还未停止拷贝应用包导致了类卸载，尝试先关闭进程再拷贝应用的包试试。

**Comment by zwingf** [comment]
> > 这个NoClassDefFoundError 应该是你们进程还未停止拷贝应用包导致了类卸载，尝试先关闭进程再拷贝应用的包试试。
> 
> 我是用Alibaba Cloud Toolkit上传jar包的,是不是每次上传了新包已经覆盖掉老的jar包后,我才关闭服务,跟启动时候的jar包不一样?

正常更新服务是不是应该先关闭原来服务,然后再上传新jar包,再启动?

**Comment by songxiaosheng** [comment]
> > > 这个NoClassDefFoundError 应该是你们进程还未停止拷贝应用包导致了类卸载，尝试先关闭进程再拷贝应用的包试试。
> > 
> > 我是用Alibaba Cloud Toolkit上传jar包的,是不是每次上传了新包已经覆盖掉老的jar包后,我才关闭服务,跟启动时候的jar包不一样?
> 
> 正常更新服务是不是应该先关闭原来服务,然后再上传新jar包,再启动?

对，进程在启动过程拷贝包就会导致类被卸载报刚刚那个错误。正常的顺序应该是先关闭进程，再拷贝。

**Comment by zwingf** [comment]
先关闭服务,再更新新jar包,再重新启动;

**Comment by songxiaosheng** [comment]
> ①先关闭服务,再更新新jar包,再重新启动; ②服务正常运行,上传新jar包覆盖原来的jar包,然后kill关闭服务,再重新启动. 这两种操作会有问题么?
① 没有问题
② 有问题
你那边可以测试下同时观察日志，应该是可以看到第② 中方案kill之前会有大量NoClassDef报错
