### ISSUE TITLE
系统调用时候报错了原2.8.0升级到现3.2.4

### ISSUE THREAD

**Issue by tts2** [apache/dubbo#12877]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
Dubbo版本:
dubbo-3.2.4
调用方法:
public void saveWFUrlInfo(String strPath,String userId,String strListTask,Map mapInfo) 
传入参数
strPath:""
userId:"SU_201411170001"
strListTask:""{"inid":"","taskid":"","businesskey":"BK_2023081017570002","formkey":"","taskdefinitionKey":"","code":"WFC_2023081017570001","name":"删除"}]"
mapInfo:{head.upgrade-insecure-requests=[Ljava.lang.Object;@4ec97c96, head.sec-fetch-site=[Ljava.lang.Object;@19c0e9de, head.referer=[Ljava.lang.Object;@15b7087a, head.sec-fetch-user=[Ljava.lang.Object;@6107aa7b, attr._authority=[Ljava.lang.Object;@642f4701, head.content-length=[Ljava.lang.Object;@7a3fdc43, head.user-agent=[Ljava.lang.Object;@5766efa6, map.FIID=[Ljava.lang.String;@b6ec343, attr._encode=[Ljava.lang.Object;@15679a60, map.fileId=[Ljava.lang.String;@11be814b, map.stufiledId=[Ljava.lang.String;@71c54705, head.accept=[Ljava.lang.Object;@ccce6a5, attr.org.springframework.web.servlet.HandlerMapping.pathWithinHandlerMapping=[Ljava.lang.Object;@2551c9c6, head.sec-fetch-mode=[Ljava.lang.Object;@4000a0fe, map.multiFile=[Ljava.lang.String;@1ba62a94, attr._jspPage=[Ljava.lang.Object;@70340e8b, head.connection=[Ljava.lang.Object;@5b80f6b2, head.sec-fetch-dest=[Ljava.lang.Object;@1e42aa6c, map.name=[Ljava.lang.String;@341ac1ba, attr.org.springframework.web.servlet.HandlerMapping.bestMatchingPattern=[Ljava.lang.Object;@640ad1e4, attr._lastmodifiedtime=[Ljava.lang.Object;@38638eb1, head.cache-control=[Ljava.lang.Object;@33f9521b, attr._teacherId_show=[Ljava.lang.Object;@510c42cf, attr._btntest_show=[Ljava.lang.Object;@63bb3cfb, attr._currDate=[Ljava.lang.Object;@4789203b, attr.shiroFilter.FILTERED=[Ljava.lang.Object;@3e99cb5b, attr._FI_btnKey_show=[Ljava.lang.Object;@db0ec7d, head.sec-ch-ua-mobile=[Ljava.lang.Object;@375655d4, attr.invalidRequest.FILTERED=[Ljava.lang.Object;@39d033fd, attr._btn_data_show=[Ljava.lang.Object;@49e3f48f, attr._user=[Ljava.lang.Object;@43ba2aca, attr._stufiledId_show=[Ljava.lang.Object;@1c33eefb, map.file=[Ljava.lang.String;@32cbb06f, attr.encodingFilter.FILTERED=[Ljava.lang.Object;@567964e6, attr.viewpath=[Ljava.lang.Object;@45b6c502, head.accept-encoding=[Ljava.lang.Object;@4671bf79, attr.org.apache.shiro.web.servlet.ShiroHttpServletRequest_SESSION_ID_URL_REWRITING_ENABLED=[Ljava.lang.Object;@29d62710, map.teacherId=[Ljava.lang.String;@34152898, map.FI_btnId=[Ljava.lang.String;@477875cd, attr._viewpath=[Ljava.lang.Object;@cb9802c, head.sec-ch-ua=[Ljava.lang.Object;@14cfc80c, head.accept-language=[Ljava.lang.Object;@98363e5, head.host=[Ljava.lang.Object;@dd1b905, attr._blIsUpdate=[Ljava.lang.Object;@4da9e073, attr.org.apache.shiro.web.servlet.ShiroHttpServletRequest_REQUESTED_SESSION_ID=[Ljava.lang.Object;@27ccde62, map.FI_btnKey=[Ljava.lang.String;@35c20d35, map._idvalue=[Ljava.lang.String;@355b9319, map.moneyInfo=[Ljava.lang.String;@377347b9, attr._name_show=[Ljava.lang.Object;@760da0fb, attr._userInfo=[Ljava.lang.Object;@5303b0aa, head.cookie=[Ljava.lang.Object;@3a292288, attr._FI_ID_show=[Ljava.lang.Object;@174af4fb, map.stulist=[Ljava.lang.String;@cdb9491, attr.org.springframework.web.servlet.HandlerMapping.uriTemplateVariables=[Ljava.lang.Object;@4213f340, attr._stulist_show=[Ljava.lang.Object;@71f07304, head.sec-ch-ua-platform=[Ljava.lang.Object;@215f1eb7, attr.org.springframework.web.servlet.DispatcherServlet.OUTPUT_FLASH_MAP=[Ljava.lang.Object;@7c0b702f, attr.user.FILTERED=[Ljava.lang.Object;@52375ee0, map.id=[Ljava.lang.String;@bc448b7, head.x-real-ip=[Ljava.lang.Object;@2c69dbe8, attr._id_show=[Ljava.lang.Object;@67821fb6, head.content-type=[Ljava.lang.Object;@f2a9df8, attr.org.apache.shiro.web.servlet.ShiroHttpServletRequestREFERENCED_SESSION_ID_SOURCE=[Ljava.lang.Object;@2602fd5a, attr._fileId_show=[Ljava.lang.Object;@4456d4e9, attr._urlInfo=[Ljava.lang.Object;@33de1c7a, head.origin=[Ljava.lang.Object;@68c082a4, attr.org.springframework.session.web.http.SessionRepositoryFilter.FILTERED=[Ljava.lang.Object;@59195acb, attr._btnsave_show=[Ljava.lang.Object;@2b9a2c9d, attr._FI_btnId_show=[Ljava.lang.Object;@6864c858, attr.org.springframework.web.servlet.View.pathVariables=[Ljava.lang.Object;@45db252, attr._money_show=[Ljava.lang.Object;@6d0547b9, attr.HttpMethodFilter.FILTERED=[Ljava.lang.Object;@236d7449, attr.org.apache.shiro.web.servlet.ShiroHttpServletRequest_REQUESTED_SESSION_ID_VALID=[Ljava.lang.Object;@4acb8d54}
Customer报错如下:
`Caused by: org.apache.dubbo.rpc.RpcException: Failed to invoke the method saveWFUrlInfo in the service com.common.service.WorkflowService. Tried 3 times of the providers [192.168.56.1:20880] (1/1) from the registry 127.0.0.1:2181 on the consumer 192.168.56.1 using the dubbo version 3.2.4. Last error is: Failed to invoke remote method: saveWFUrlInfo, provider: DefaultServiceInstance{serviceName='platform_provider', host='192.168.56.1', port=20880, enabled=true, healthy=true, metadata={dubbo.endpoints=[{"port":20880,"protocol":"dubbo"}], dubbo.metadata-service.url-params={"prefer.serialization":"fastjson2,hessian2","version":"1.0.0","dubbo":"2.0.2","release":"3.2.4","side":"provider","port":"20880","protocol":"dubbo"}, dubbo.metadata.revision=813c22ae7755a97320a51154c580f7e1, dubbo.metadata.storage-type=local, timestamp=1691660447684}}, service{name='com.common.service.WorkflowService',group='null',version='null',protocol='dubbo',port='20880',params={side=provider, release=3.2.4, methods=activateProcessInstanceById,completeTaskWithCommentCmd,createBussinKey,delAllDeployment,delDeployment,delDeploymentByMap,delRunWF,delegateTaskUsers,deleteModel,deleteModelByMap,deleteProcessInstanceById,deployWFModel,deployWFModelByRedisKey,expreeString,getControlTaskInfo,getCurrTask,getDeploymentIdByProcesskey,getDeploymentIdByTaskId,getDeptPostUser,getDeptUser,getFormKeyByTaskID,getJsonInfoByDeployId,getMultipleUser,getNextUserTaskInfo,getPostUser,getProcessInstanceByInid,getRoleUser,getRunVariablesByProcess,getUserTaskDefinition,getUsersIdBySql,getWFFormInfoData,openWFModel,openWFRunData,saveBusinessKey,saveDeployWFByRedisKey,saveDeployWFData,saveSuggestion,saveWFModel,saveWFModelByMap,saveWFUrlInfo,startProcess,startWorkflow,suspendProcessInstanceById,taskClaim,taskMoveBack,taskMoveChange,taskMoveChangeInfo,updateFirstUserLink, deprecated=false, dubbo=2.0.2, interface=com.common.service.WorkflowService, service-name-mapping=true, timeout=5000, generic=false, revision=CommonService, qos.anonymous.access.permission.level=PUBLIC, retries=0, application=platform_provider, prefer.serialization=fastjson2,hessian2, dynamic=true, qos.accept.foreign.ip.whitelist=123.12.10.13, 132.12.10.13/24},}, cause: org.apache.dubbo.remoting.RemotingException: Fail to decode request due to: RpcInvocation [methodName=saveWFUrlInfo, parameterTypes=null]
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:114)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:344)
	at org.apache.dubbo.rpc.cluster.router.RouterSnapshotFilter.invoke(RouterSnapshotFilter.java:46)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:108)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.rpc.cluster.filter.support.MetricsClusterFilter.invoke(MetricsClusterFilter.java:50)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:52)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.spring.security.filter.ContextHolderParametersSelectedTransferFilter.invoke(ContextHolderParametersSelectedTransferFilter.java:41)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.rpc.cluster.filter.support.ConsumerClassLoaderFilter.invoke(ConsumerClassLoaderFilter.java:40)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.rpc.cluster.filter.support.ConsumerContextFilter.invoke(ConsumerContextFilter.java:118)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CallbackRegistrationInvoker.invoke(FilterChainBuilder.java:196)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$ClusterFilterInvoker.invoke(AbstractCluster.java:91)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:103)
	at org.apache.dubbo.rpc.cluster.support.wrapper.ScopeClusterInvoker.invoke(ScopeClusterInvoker.java:169)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.invoke(MigrationInvoker.java:284)
	at org.apache.dubbo.rpc.proxy.InvocationUtil.invoke(InvocationUtil.java:57)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:75)
	at com.common.service.WorkflowServiceDubboProxy5.saveWFUrlInfo(WorkflowServiceDubboProxy5.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.dubbo.config.spring.util.LazyTargetInvocationHandler.invoke(LazyTargetInvocationHandler.java:58)
	at com.common.service.WorkflowServiceDubboProxy5.saveWFUrlInfo(WorkflowServiceDubboProxy5.java)
	... 75 more
Caused by: java.util.concurrent.ExecutionException: org.apache.dubbo.remoting.RemotingException: Fail to decode request due to: RpcInvocation [methodName=saveWFUrlInfo, parameterTypes=null]
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:218)
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:287)
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:190)
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:71)
	at org.apache.dubbo.metrics.filter.MetricsFilter.invoke(MetricsFilter.java:63)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CallbackRegistrationInvoker.invoke(FilterChainBuilder.java:196)
	at org.apache.dubbo.rpc.protocol.ReferenceCountInvokerWrapper.invoke(ReferenceCountInvokerWrapper.java:78)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invokeWithContext(AbstractClusterInvoker.java:383)
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:80)
	... 104 more
Caused by: org.apache.dubbo.remoting.RemotingException: Fail to decode request due to: RpcInvocation [methodName=saveWFUrlInfo, parameterTypes=null]
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.doReceived(DefaultFuture.java:249)
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:200)
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:188)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleResponse(HeaderExchangeHandler.java:65)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:206)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:53)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:62)
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor$RunnableWrapper.run(ThreadlessExecutor.java:152)
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:77)
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:205)
	... 113 more`
Provider报错如下:
`2023-08-10 18:42:23 ? WARN  [DUBBO] Decode rpc invocation failed: org.apache.dubbo.common.serialize.SerializationException: com.alibaba.fastjson2.JSONException: not support type : REFERENCE -109, offset 14178/15287, dubbo version: 3.2.4, current host: 192.168.56.1, error code: 4-20. This may be caused by , go to https://dubbo.apache.org/faq/4/20 to find instructions. 
java.io.IOException: org.apache.dubbo.common.serialize.SerializationException: com.alibaba.fastjson2.JSONException: not support type : REFERENCE -109, offset 14178/15287
	at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper.handleToIOException(DefaultSerializationExceptionWrapper.java:358)
	at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper.access$000(DefaultSerializationExceptionWrapper.java:28)
	at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper$ProxyObjectInput.readObject(DefaultSerializationExceptionWrapper.java:168)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.drawArgs(DecodeableRpcInvocation.java:265)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:166)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:103)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboCodec.decodeBody(DubboCodec.java:180)
	at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:138)
	at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:92)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboCountCodec.decode(DubboCountCodec.java:60)
	at org.apache.dubbo.remoting.transport.netty4.NettyCodecAdapter$InternalDecoder.decode(NettyCodecAdapter.java:103)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.dubbo.common.serialize.SerializationException: com.alibaba.fastjson2.JSONException: not support type : REFERENCE -109, offset 14178/15287
	... 30 more
Caused by: com.alibaba.fastjson2.JSONException: not support type : REFERENCE -109, offset 14178/15287
	at com.alibaba.fastjson2.JSONReaderJSONB.readAny(JSONReaderJSONB.java:975)
	at com.alibaba.fastjson2.reader.ObjectArrayReader.readJSONBObject(ObjectArrayReader.java:141)
	at com.alibaba.fastjson2.reader.ObjectReaderImplMap.readJSONBObject(ObjectReaderImplMap.java:366)
	at com.alibaba.fastjson2.JSONB.parseObject(JSONB.java:540)
	at org.apache.dubbo.common.serialize.fastjson2.FastJson2ObjectInput.readObject(FastJson2ObjectInput.java:118)
	at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper$ProxyObjectInput.readObject(DefaultSerializationExceptionWrapper.java:166)
	... 27 more`

**Comment by AlbumenJ** [comment]
这个应该是 fastjson2 的问题，可以提供一个可以复现的 demo吗

**Comment by tts2** [comment]
找到问题了，是map里的变量并不是所有都是继承自序列化接口的，好绕😂
