### ISSUE TITLE
dubbo 3.2.4多线程环境下导致服务消费者获取的ClassLoader不对，消费者反序列化pojo失败，返回值被转为HashMap

### ISSUE THREAD

**Issue by lucky-xin** [apache/dubbo#12885]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.4
* Operating System version: k8s v1.27
* Java version: 17

### Steps to reproduce this issue

1. 多线程执行服务消费者
2. 使用stream().parallel().forEach()遍历并调用服务提供者

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

支持服务消费者多线程调用服务提供者

### Actual Behavior

服务消费端返回值被转为HashMap
If there is an exception, please attach the exception trace:
```
com.alibaba.com.caucho.hessian.io.java8.LocalDateTimeHandle"}
{"@timestamp":"2023-08-12T09:09:34.881328+08:00","thread":"ForkJoinPool.commonPool-worker-2","thread_id":15,"level":"WARN","message":"Hessian/Burlap: 'com.alibaba.com.caucho.hessian.io.java8.LocalTimeHandle' is an unknown class in jdk.internal.loader.ClassLoaders$AppClassLoader@531d72ca:\njava.lang.ClassNotFoundException: com.alibaba.com.caucho.hessian.io.java8.LocalTimeHandle"}
{"@timestamp":"2023-08-12T09:09:34.881663+08:00","thread":"ForkJoinPool.commonPool-worker-2","thread_id":15,"level":"WARN","message":"Hessian/Burlap: 'com.alibaba.com.caucho.hessian.io.java8.LocalDateHandle' is an unknown class in jdk.internal.loader.ClassLoaders$AppClassLoader@531d72ca:\njava.lang.ClassNotFoundException: 
java.util.concurrent.CompletionException: java.lang.ClassCastException: class java.util.HashMap cannot be cast to class com.x.x.x.UserInfo (java.util.HashMap is in module java.base of loader 'bootstrap';com.x.x.x.UserInfo is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader@573f2bb1)
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165
```

跟踪代码发现问题出现在com.alibaba.com.caucho.hessian.io.SerializerFactory#getDeserializer(java.lang.String)中，加载业务class失败导致获取Deserializer为null，最后返回MapDeserializer
```
public Deserializer getObjectDeserializer(String type)
            throws HessianProtocolException {

        Deserializer deserializer = getDeserializer(type);
       // deserializer为null，返回MapDeserializer
        if (deserializer != null)
            return deserializer;
        else if (_hashMapDeserializer != null)
            return _hashMapDeserializer;
        else {
            _hashMapDeserializer = new MapDeserializer(HashMap.class);

            return _hashMapDeserializer;
        }
    }
```
```
public Deserializer getDeserializer(String type)
            throws HessianProtocolException {
        if (type == null || type.equals("") || _typeNotFoundDeserializerMap.containsKey(type))
            return null;

        Deserializer deserializer;

        if (_cachedTypeDeserializerMap != null) {
            deserializer = (Deserializer) _cachedTypeDeserializerMap.get(type);

            if (deserializer != null)
                return deserializer;
        }


        deserializer = (Deserializer) _staticTypeMap.get(type);
        if (deserializer != null)
            return deserializer;

        if (type.startsWith("[")) {
            Deserializer subDeserializer = getDeserializer(type.substring(1));

            if (subDeserializer != null)
                deserializer = new ArrayDeserializer(subDeserializer.getType());
            else
                deserializer = new ArrayDeserializer(Object.class);
        } else if (_unrecognizedTypeCache.get(type) == null) {
            try {
                // 问题在这出现
               //                Class cl = Class.forName(type, false, _loader);
                Class cl = loadSerializedClass(type);
                deserializer = getDeserializer(cl);
            } catch (Exception e) {
                log.warning("Hessian/Burlap: '" + type + "' is an unknown class in " + _loader + ":\n" + e);
                _typeNotFoundDeserializerMap.put(type, PRESENT);
                log.log(Level.FINER, e.toString(), e);
                _unrecognizedTypeCache.put(type, new AtomicLong(1L));
            }
        } else {
            ((AtomicLong) _unrecognizedTypeCache.get(type)).incrementAndGet();
            if (((AtomicLong) _unrecognizedTypeCache.get(type)).get() % 2000L == 0L)
                ((AtomicLong) _unrecognizedTypeCache.get(type)).getAndSet(1L);
        }

        if (deserializer != null) {
            if (_cachedTypeDeserializerMap == null)
                _cachedTypeDeserializerMap = new ConcurrentHashMap(8);

            _cachedTypeDeserializerMap.put(type, deserializer);
        }

        return deserializer;
    }
```
loadSerializedClass时会获取ClassFactory加载class
```
public Class<?> loadSerializedClass(String className)
            throws ClassNotFoundException
    {
        return getClassFactory().load(className);
    }

    public ClassFactory getClassFactory()
    {
        synchronized (this) {
            if (_classFactory == null) {
             // 获取当前SerializerFactory的ClassLoader
                _classFactory = new ClassFactory(getClassLoader());
            }

            return _classFactory;
        }
    }
```
而SerializerFactory的ClassLoader是通过当前执行线程获取的，单线程环境下没有问题，多线程环境下很可能就会有问题
```
public class Hessian2ObjectInput implements ObjectInput, Cleanable {
    private final Hessian2Input mH2i;
    private final Hessian2FactoryManager hessian2FactoryManager;

    @Deprecated
    public Hessian2ObjectInput(InputStream is) {
        mH2i = new Hessian2Input(is);
        this.hessian2FactoryManager = FrameworkModel.defaultModel().getBeanFactory().getOrRegisterBean(Hessian2FactoryManager.class);
        mH2i.setSerializerFactory(hessian2FactoryManager.getSerializerFactory(Thread.currentThread().getContextClassLoader()));
    }

    public Hessian2ObjectInput(InputStream is, Hessian2FactoryManager hessian2FactoryManager) {
        mH2i = new Hessian2Input(is);
        this.hessian2FactoryManager = hessian2FactoryManager;
        // 反序列化时创建SerializerFactory，并把当前线程的ClassLoader给SerializerFactory
       mH2i.setSerializerFactory(hessian2FactoryManager.getSerializerFactory(Thread.currentThread().getContextClassLoader()));
    }
//...
}
```

**Comment by AlbumenJ** [comment]
![image](https://github.com/apache/dubbo/assets/9292748/11953ea3-c248-45e8-805b-200df0adf421)

在具体获取的地方还有再检查一次 ClassLoader 的

**Comment by lucky-xin** [comment]
> ![image](https://user-images.githubusercontent.com/9292748/260370471-11953ea3-c248-45e8-805b-200df0adf421.png)
> 
> 在具体获取的地方还有再检查一次 ClassLoader 的

某些情况下readObject是在子线程里边，如使用Caffeine缓存异步加载数据，子线程的ClassLoader和父线程的ClassLoader不一致
![image](https://github.com/apache/dubbo/assets/13815910/ac9ac7a3-27ec-491b-b490-01aac8c90c15)

我是在开启子线程时设置了父线程的ClassLoader解决了该问题，如下：
![image](https://github.com/apache/dubbo/assets/13815910/24744a30-d15f-41c1-a806-07f8cfd9b2c5)

**Comment by AlbumenJ** [comment]
> > ![image](https://user-images.githubusercontent.com/9292748/260370471-11953ea3-c248-45e8-805b-200df0adf421.png)
> > 在具体获取的地方还有再检查一次 ClassLoader 的
> 
> 某些情况下readObject是在子线程里边，如使用Caffeine缓存异步加载数据，子线程的ClassLoader和父线程的ClassLoader不一致 ![image](https://user-images.githubusercontent.com/13815910/260898846-ac9ac7a3-27ec-491b-b490-01aac8c90c15.png)
> 
> 我是在开启子线程时设置了父线程的ClassLoader解决了该问题，如下： ![image](https://user-images.githubusercontent.com/13815910/260898968-24744a30-d15f-41c1-a806-07f8cfd9b2c5.png)

按照双亲委派机制，子 classloader 应该可以加载到父 classloader 的类吧

**Comment by CLOUDERHEM** [comment]
是不是有什么操作导致com.x.x.x.UserInfo被其他自定义的类加载器重新加载了(例如热加载的场景)? 或者所说的"父子线程"实际上不是父子线程? 子线程的ContextClassLoader默认是父线程的loader, 还有双亲委派的机制存在

**Comment by xlq20080808** [comment]
也有遇到类似问题，目前排查点是使用了ForkJoinPool，JDK11时修改了类加载器的获取方式
https://stackoverflow.com/questions/56967408/classes-with-default-access-result-in-noclassdeffound-error-at-runtime-in-spring

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.

**Comment by zhouxufu** [comment]
这个问题在较新的版本组合中仍然可以复现，申请重新打开。

### 环境

- Dubbo：3.3.5
- Spring Boot：4.1.0（可执行 fat jar）
- Reactor Core：3.8.6
- JDK：21
- 序列化：Hessian2

### 现象

Dubbo 消费者在 Reactor 的 `boundedElastic` 线程中发起 RPC 调用时，服务端已经正常返回 DTO，但消费者反序列化阶段出现类似日志：

```text
Hessian/Burlap: 'xxx.ResponseDTO' is an unknown class in
jdk.internal.loader.ClassLoaders$AppClassLoader
```

随后 DTO 和枚举被降级反序列化为 `HashMap`，最终发生：

```text
ClassCastException: java.util.HashMap cannot be cast to xxx.ResponseDTO
```

已经确认：

1. RPC 接口、DTO 和枚举都存在于 Spring Boot 可执行 jar 的嵌套依赖中；
2. 消费端与提供端使用的 RPC API 版本一致；
3. 两个服务运行在不同 JVM 中，因此不是同 JVM 类冲突；
4. 本地 IDE 直接启动正常，打成 Spring Boot fat jar 后在异步线程中复现；
5. 出错线程的 TCCL 是 `AppClassLoader`，无法加载 Spring Boot fat jar 中由应用 ClassLoader 管理的 RPC DTO。

### 临时解决方案

在异步线程真正发起 Dubbo 调用前，将当前线程的 Context ClassLoader 临时切换为 RPC 契约类的 ClassLoader，并在调用结束后恢复：

```java
Thread thread = Thread.currentThread();
ClassLoader original = thread.getContextClassLoader();
ClassLoader rpcClassLoader = RpcService.class.getClassLoader();
try {
    thread.setContextClassLoader(rpcClassLoader);
    return rpcService.invoke(request);
} finally {
    thread.setContextClassLoader(original);
}
```

应用此处理后，Hessian2 可以正确加载 DTO，返回值不再变成 `HashMap`。

### 希望确认

Dubbo 3.3.5 中的 `ConsumerClassLoaderFilter` 是否应该覆盖这种 Reactor 异步线程场景？目前实际反序列化时仍然取到了 `AppClassLoader`。是否可以在 Dubbo/Hessian2 内部优先使用 ServiceModel 或 RPC 契约所属的 ClassLoader，而不是直接依赖调用线程的 TCCL？

该现象与本 Issue 描述一致，并且在 3.3.5 上仍然存在，麻烦重新打开并继续确认，谢谢。
