### ISSUE TITLE
dubbo 3.2.5 下消费者请求调用使用 tri 协议和使用kyro序列化时，不能序列化tri 请求,使用fastjson2则正常

### ISSUE THREAD

**Issue by rickyhuangdev** [apache/dubbo#12901]
2023-08-15T14:53:26.586+08:00 ERROR 55830 --- [nio-9094-exec-1] o.a.d.r.p.t.c.TripleClientCall           :  [DUBBO] Serialize triple request failed, service=com.ensign.nexusnet.api.service.client.organization.ProfileServiceApi method=org.apache.dubbo.rpc.model.ReflectionMethodDescriptor@3658947c, dubbo version: 3.2.5, current host: 10.10.10.135, error code: 4-10. This may be caused by , go to https://dubbo.apache.org/faq/4/10 to find instructions. 

java.lang.RuntimeException: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.Object[] java.util.Arrays$ArrayList.a accessible: module java.base does not "opens java.util" to unnamed module @604ed9f0
	at de.javakaffee.kryoserializers.ArraysAsListSerializer.<init>(ArraysAsListSerializer.java:47) ~[kryo-serializers-0.45.jar:?]
	at org.apache.dubbo.common.serialize.kryo.utils.AbstractKryoFactory.create(AbstractKryoFactory.java:97) ~[dubbo-serialization-kryo-1.0.1.jar:1.0.1]
	at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:361) ~[?:?]
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:226) ~[?:?]
	at java.lang.ThreadLocal.get(ThreadLocal.java:195) ~[?:?]
	at java.lang.ThreadLocal.get(ThreadLocal.java:169) ~[?:?]
	at org.apache.dubbo.common.serialize.kryo.utils.ThreadLocalKryoFactory.getKryo(ThreadLocalKryoFactory.java:32) ~[dubbo-serialization-kryo-1.0.1.jar:1.0.1]
	at org.apache.dubbo.common.serialize.kryo.utils.KryoUtils.get(KryoUtils.java:30) ~[dubbo-serialization-kryo-1.0.1.jar:1.0.1]
	at org.apache.dubbo.common.serialize.kryo.KryoObjectOutput.<init>(KryoObjectOutput.java:39) ~[dubbo-serialization-kryo-1.0.1.jar:1.0.1]
	at org.apache.dubbo.common.serialize.kryo.KryoSerialization.serialize(KryoSerialization.java:51) ~[dubbo-serialization-kryo-1.0.1.jar:1.0.1]
	at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper.serialize(DefaultSerializationExceptionWrapper.java:51) ~[dubbo-serialization-api-3.2.5.jar:3.2.5]
	at org.apache.dubbo.common.serialize.DefaultMultipleSerialization.serialize(DefaultMultipleSerialization.java:32) ~[dubbo-serialization-api-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.protocol.tri.ReflectionPackableMethod$WrapRequestPack.pack(ReflectionPackableMethod.java:431) ~[dubbo-rpc-triple-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.model.PackableMethod.packRequest(PackableMethod.java:43) ~[dubbo-common-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.protocol.tri.call.TripleClientCall.sendMessage(TripleClientCall.java:177) ~[dubbo-rpc-triple-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.protocol.tri.observer.ClientCallToObserverAdapter.onNext(ClientCallToObserverAdapter.java:44) ~[dubbo-rpc-triple-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.protocol.tri.TripleInvoker.invokeUnary(TripleInvoker.java:253) ~[dubbo-rpc-triple-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.protocol.tri.TripleInvoker.doInvoke(TripleInvoker.java:144) ~[dubbo-rpc-triple-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.doInvokeAndReturn(AbstractInvoker.java:243) ~[dubbo-rpc-api-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:187) ~[dubbo-rpc-api-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:71) ~[dubbo-rpc-api-3.2.5.jar:3.2.5]
	at com.ensign.commons.rpc.filters.RpcRequestFilter.invoke(RpcRequestFilter.java:32) ~[classes/:?]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.filter.RpcExceptionFilter.invoke(RpcExceptionFilter.java:41) ~[dubbo-rpc-api-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CallbackRegistrationInvoker.invoke(FilterChainBuilder.java:196) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.protocol.ReferenceCountInvokerWrapper.invoke(ReferenceCountInvokerWrapper.java:88) ~[dubbo-rpc-api-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invokeWithContext(AbstractClusterInvoker.java:383) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:80) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:344) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.cluster.router.RouterSnapshotFilter.invoke(RouterSnapshotFilter.java:46) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:108) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.cluster.filter.support.MetricsClusterFilter.invoke(MetricsClusterFilter.java:56) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:52) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.cluster.filter.support.ObservationSenderFilter.invoke(ObservationSenderFilter.java:61) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.spring.security.filter.ContextHolderParametersSelectedTransferFilter.invoke(ContextHolderParametersSelectedTransferFilter.java:41) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.metrics.filter.MetricsFilter.invoke(MetricsFilter.java:73) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.cluster.filter.support.MetricsConsumerFilter.invoke(MetricsConsumerFilter.java:37) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.cluster.filter.support.ConsumerClassLoaderFilter.invoke(ConsumerClassLoaderFilter.java:40) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.cluster.filter.support.ConsumerContextFilter.invoke(ConsumerContextFilter.java:116) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CallbackRegistrationInvoker.invoke(FilterChainBuilder.java:196) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$ClusterFilterInvoker.invoke(AbstractCluster.java:91) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:103) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.cluster.support.wrapper.ScopeClusterInvoker.invoke(ScopeClusterInvoker.java:169) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.invoke(MigrationInvoker.java:284) ~[dubbo-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.proxy.InvocationUtil.invoke(InvocationUtil.java:61) ~[dubbo-rpc-api-3.2.5.jar:3.2.5]
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:75) ~[dubbo-rpc-api-3.2.5.jar:3.2.5]
	at com.ensign.nexusnet.api.service.client.organization.ProfileServiceApiDubboProxy4.getProfile(ProfileServiceApiDubboProxy4.java) ~[classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.apache.dubbo.config.spring.util.LazyTargetInvocationHandler.invoke(LazyTargetInvocationHandler.java:58) ~[dubbo-3.2.5.jar:3.2.5]
	at com.ensign.nexusnet.api.service.client.organization.ProfileServiceApiDubboProxy4.getProfile(ProfileServiceApiDubboProxy4.java) ~[classes/:?]
	at com.ensign.internal.app.interfaces.facade.organization.ProfileApi.getProfile(ProfileApi.java:32) ~[classes/:?]
	at com.ensign.internal.app.domain.service.organization.ProfileDomainService.getProfile(ProfileDomainService.java:37) ~[classes/:?]
	at com.ensign.internal.app.application.service.organization.ProfileApplicationService.getProfile(ProfileApplicationService.java:34) ~[classes/:?]
	at com.ensign.internal.app.controller.organization.ProfileController.getProfile(ProfileController.java:45) ~[classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-6.0.11.jar:6.0.11]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-6.0.11.jar:6.0.11]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.0.11.jar:6.0.11]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.11.jar:6.0.11]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.11.jar:6.0.11]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.11.jar:6.0.11]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[spring-webmvc-6.0.11.jar:6.0.11]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[spring-webmvc-6.0.11.jar:6.0.11]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[spring-webmvc-6.0.11.jar:6.0.11]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-webmvc-6.0.11.jar:6.0.11]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564) ~[tomcat-embed-core-10.1.11.jar:6.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.0.11.jar:6.0.11]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.11.jar:6.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.0.11.jar:6.0.11]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar:6.0.11]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.0.11.jar:6.0.11]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar:6.0.11]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109) ~[spring-web-6.0.11.jar:6.0.11]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar:6.0.11]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.0.11.jar:6.0.11]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar:6.0.11]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1740) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at java.lang.Thread.run(Thread.java:1623) [?:?]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.Object[] java.util.Arrays$ArrayList.a accessible: module java.base does not "opens java.util" to unnamed module @604ed9f0
	at java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311) ~[?:?]
	at java.lang.reflect.Field.checkCanSetAccessible(Field.java:181) ~[?:?]
	at java.lang.reflect.Field.setAccessible(Field.java:175) ~[?:?]
	at de.javakaffee.kryoserializers.ArraysAsListSerializer.<init>(ArraysAsListSerializer.java:45) ~[kryo-serializers-0.45.jar:?]
	... 116 more

2023-08-15T14:53:26.589+08:00  INFO 55830 --- [nio-9094-exec-1] c.e.c.r.f.RpcRequestFilter               : Rpc - 服务响应: Client[consumer], InterfaceName=[ProfileServiceApi],MethodName=[getProfile],SpendTime=[35ms, Response=[null]]
**配置**
boostrap 文件
dubbo:
  application:
    name: internal-web-application
    metadata-type: remote
    check-serializable: true
    auto-trust-serialize-class: true
    trust-serialize-class-level: 3
  metadata-report:
    address: nacos://${spring.cloud.nacos.config.server-addr}?username=${spring.cloud.nacos.config.username}&password=${spring.cloud.nacos.config.password}
    protocol: nacos
    group: SEATA_GROUP
  protocol:
    name: tri
    port: 20888
    serialization: kryo
    optimizer: com.ensign.internal.app.config.SerializationOptimizerImpl
  registry:
    address: nacos://${spring.cloud.nacos.config.server-addr}?username=${spring.cloud.nacos.config.username}&password=${spring.cloud.nacos.config.password}
    group: SEATA_GROUP
    check: false
    protocol: nacos
    parameters:
      register-consumer-url: true
  consumer:
    check: false
    filter: -exception,rpcRequestFilter
    timeout: 5000
  provider:
    filter: -exception,rpcRequestFilter
    timeout: 5000
  **SerializationOptimizer**
package com.ensign.internal.app.config;

import com.ensign.nexusnet.api.domain.client.organization.profile.ProfileApiDTO;
import org.apache.dubbo.common.serialize.support.SerializationOptimizer;

import java.util.Collection;
import java.util.LinkedList;
import java.util.List;

public class SerializationOptimizerImpl implements SerializationOptimizer {
    public Collection<Class<?>> getSerializableClasses() {
        List<Class<?>> classes = new LinkedList<Class<?>>();
        classes.add(ProfileApiDTO.class);
        return classes;
    }
}
**pom**
   <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-metadata-report-nacos</artifactId>
            <version>3.2.5</version>
        </dependency>
     <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-rpc-triple</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo.extensions</groupId>
            <artifactId>dubbo-serialization-kryo</artifactId>
            <version>1.0.1</version>
        </dependency>

**Comment by AlbumenJ** [comment]
java.lang.RuntimeException: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.Object[] java.util.Arrays$ArrayList.a accessible: module java.base does not "opens java.util" to unnamed module @604ed9f0


JDK 17 限制了模块的访问，请降级到 JDK11 或者添加 add-open 参数才能使用 kryo

**Comment by JavaLionLi** [comment]
升级到 dubbo-serialization-kryo 1.0.3 kryo升级到5.5.0 适配了jdk17 
你用的插件版本太低了

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
