### ISSUE TITLE
在rest协议接口内调用dubbo协议接口，报序列化异常

### ISSUE THREAD

**Issue by sick-cat** [apache/dubbo#12974]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.5
* Java version: 1.8

### Steps to reproduce this issue

1. 起一个dubbo服务，rest协议暴露A接口，dubbo协议暴露B接口。在A接口中调用B
2. 服务启动后，发起http请求调用A接口会报异常：
```
Caused by: java.io.IOException: org.apache.dubbo.common.serialize.SerializationException: java.lang.IllegalArgumentException: [Serialization Security] Serialized class org.jboss.resteasy.plugins.server.netty.NettyHttpRequest is in disallow list. Current mode is `WARN`, will disallow to deserialize it by default. Please add it into security/serialize.allowlist or follow FAQ to configure it.
        at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper.handleToIOException(DefaultSerializationExceptionWrapper.java:358)
        at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper.access$000(DefaultSerializationExceptionWrapper.java:28)
        at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper$ProxyObjectOutput.writeAttachments(DefaultSerializationExceptionWrapper.java:351)
        at org.apache.dubbo.rpc.protocol.dubbo.DubboCodec.encodeRequestData(DubboCodec.java:292)
        at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.encodeRequest(ExchangeCodec.java:273)
        at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.encode(ExchangeCodec.java:79)
        at org.apache.dubbo.rpc.protocol.dubbo.DubboCountCodec.encode(DubboCountCodec.java:51)
        at org.apache.dubbo.remoting.transport.netty4.NettyChannel.send(NettyChannel.java:192)
```

-----
DEBUG发现，在 ConsumerContextFilter 中，把rest请求的ServerAttachment加入到了invocation的attachments中，导致序列化失败。
```java
((RpcInvocation) invocation).addObjectAttachments(RpcContext.getServerAttachment().getObjectAttachments());
```

**Comment by AlbumenJ** [comment]
@suncairong163 PTAL

NettyHttpRequest should not be added into `attachments`. Can only be added into `attributes`.
