### ISSUE TITLE
rest : dubbo rest metadata resolve double path error,and do not  contain path variable  

### ISSUE THREAD

**Issue by zdtjss** [apache/dubbo#13235]
故障版本：3.2.6、3.2.7
故障位置：AbstractServiceRestMetadataResolver.java  203行  代码（break）在2023年8月3号被注释，以致方法在serviceMethodsMap被重复添加
问题：使用rest注册接口时报错：
Caused by: java.lang.IllegalArgumentException: dubbo rest metadata resolve double path error,and do not  contain path variable  is: PathMatcher{path='/workflow-api/workflow/getNextVars', version='1.0.0', group='null', port=null, hasPathVariable=false, contextPath='null', httpMethod='GET'}, rest method metadata is: RestMethodMetadata{method=MethodDefinition [name=getNextVars, parameterTypes=[java.lang.String], returnType=java.util.Map<java.lang.String,java.lang.String>], request=RequestMetadata{method='GET', path='/workflow-api/workflow/getNextVars', params={bizId=[{0}]}, headers={}, consumes=[application/json; charset=UTF-8], produces=[application/json; charset=UTF-8]}, urlIndex=null, bodyIndex=null, headerMapIndex=null, bodyType='null', indexToName=null, formParams=null, indexToEncoded=null, argInfos=[ArgInfo{index=0, annotationNameAttribute='bizId', paramAnnotationType=interface javax.ws.rs.QueryParam, paramType=class java.lang.String, paramName='arg0', urlSplitIndex=0, defaultValue={0}, formContentType=false}], reflectMethod=public abstract java.util.Map com.zdtjss.workflow.client.api.WorkflowService.getNextVars(java.lang.String), codeStyle=class org.apache.dubbo.metadata.rest.jaxrs.JAXRSServiceRestMetadataResolver}
	at org.apache.dubbo.metadata.rest.ServiceRestMetadata.doublePathCheck(ServiceRestMetadata.java:149)
	at org.apache.dubbo.metadata.rest.ServiceRestMetadata.addPathToServiceMap(ServiceRestMetadata.java:134)
	at org.apache.dubbo.metadata.rest.ServiceRestMetadata.addRestMethodMetadata(ServiceRestMetadata.java:115)
	at org.apache.dubbo.metadata.rest.AbstractServiceRestMetadataResolver.processRestMethodMetadata(AbstractServiceRestMetadataResolver.java:302)
	at org.apache.dubbo.metadata.rest.AbstractServiceRestMetadataResolver.processAllRestMethodMetadata(AbstractServiceRestMetadataResolver.java:159)
	at org.apache.dubbo.metadata.rest.AbstractServiceRestMetadataResolver.resolve(AbstractServiceRestMetadataResolver.java:121)
	at org.apache.dubbo.rpc.protocol.rest.annotation.metadata.MetadataResolver.resolveProviderServiceMetadata(MetadataResolver.java:63)

**Comment by Stellar1999** [comment]
II can't reproduce this issue. Could you provide a code snippet as an example?
