### ISSUE TITLE
从3.1.7升级到3.2.6版本后，getMetadataInfo timeout 

### ISSUE THREAD

**Issue by Liu-YanP** [apache/dubbo#13245]
### Environment

* Dubbo version: 3.2.6
* Java version: jdk11

升级3.2.6版本后 一直报getMetadataInfo超时错误。可以确定网络是没问题的。

```
 [DUBBO] Failed to get app metadata for revision bbc7548be1e77bec95618bdfc77a950a for type local from instance host:port, dubbo version: 3.2.6, current host: XXXXXXX, error code: 1-39. This may be caused by , go to https://dubbo.apache.org/faq/1/39 to find instructions. org.apache.dubbo.rpc.RpcException: Invoke remote method timeout. method: getMetadataInfo, provider: tri://(host:port)/org.apache.dubbo.metadata.MetadataService?connections=200&corethreads=2&dubbo=2.0.2&group=xxxxx&port=xxxxx&prefer.serialization=fastjson2,hessian2&protocol=tri&release=3.2.6&retries=0&side=consumer&threadpool=cached&threads=100&timeout=5000&token=************************************&version=1.0.0, cause: Timeout after 5000ms waiting for result.
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:304)
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:190)
	at org.apache.dubbo.rpc.proxy.InvocationUtil.invoke(InvocationUtil.java:61)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:75)
	at org.apache.dubbo.metadata.MetadataServiceDubboProxy1.getMetadataInfo(MetadataServiceDubboProxy1.java)
	at org.apache.dubbo.registry.client.metadata.MetadataUtils.getRemoteMetadata(MetadataUtils.java:173)
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.lambda$getRemoteMetadata$2(AbstractServiceDiscovery.java:229)
	at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:86)
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.getRemoteMetadata(AbstractServiceDiscovery.java:228)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.lambda$doOnEvent$2(ServiceInstancesChangedListener.java:162)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.doOnEvent(ServiceInstancesChangedListener.java:162)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.onEvent(ServiceInstancesChangedListener.java:116)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener$AddressRefreshRetryTask.run(ServiceInstancesChangedListener.java:489)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.TimeoutException: Timeout after 5000ms waiting for result.
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:207)
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:287)
	... 20 more

```

**Comment by AlbumenJ** [comment]
Check if there is any exception on the provider side.

**Comment by Liu-YanP** [comment]
已经解决了。升级dubbo版本后需要同步升级protibuf-Java版本到3.22.0
```
private DebugInfo() {
    stackEntries_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    detail_ = "";
  }
```
这里调用了protibuf-Java 中emptyList()方法，在3.22.0版本之前该方法是非public方法。会报错
3.22.0版本LazyStringArrayList 类之前的 emptyList()方法
```
static LazyStringArrayList emptyList() {
    return EMPTY_LIST;
  }
```
