### ISSUE TITLE
Is there an example of a spring cloud Alibaba 2022+dubbo 3.2+native image that can compile and run successfully

### ISSUE THREAD

**Issue by imgoby** [apache/dubbo#13241]
Spring cloud Alibaba+dubbo+native-image cannot run successfully under native image.
Is there an example of a spring cloud Alibaba 2022+dubbo 3.2+native image that can compile and run successfully

**Comment by imgoby** [comment]
I save the code here:
https://github.com/imgoby/spring-cloud-alibaba-graalvm
This code is a test example of spring cloud Alibaba+grailvm.
[spring cloud alibaba examples]（ https://github.com/imgoby/spring-cloud-alibaba-graalvm/tree/main/spring-cloud-alibaba-examples ）Testing is possible.
But [spring cloud alibaba dubbo]（ https://github.com/imgoby/spring-cloud-alibaba-graalvm/tree/main/spring-cloud-alibaba-dubbo ）Previously, there was a build error, but later it was set to:

<dubbo. version>3.3.0 beta. 1</dubbo. version>

**Can be successfully built. But there were errors during operation**

How to Resolve it.

 :: Dubbo (v3.3.0-beta.1) : https://github.com/apache/dubbo
 :: Discuss group : dev@dubbo.apache.org
2023-10-23T11:01:22.843+08:00  WARN 21249 --- [           main] c.a.nacos.client.logging.NacosLogging    : Load Logback Configuration of Nacos fail, message: Could not initialize Logback Nacos logging from classpath:nacos-logback.xml

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.0.2)

2023-10-23T11:01:22.847+08:00  WARN 21249 --- [           main] c.a.nacos.client.logging.NacosLogging    : Load Logback Configuration of Nacos fail, message: Could not initialize Logback Nacos logging from classpath:nacos-logback.xml
2023-10-23T11:01:22.848+08:00  INFO 21249 --- [           main] o.a.d.s.d.provider.ProviderApplication   : Starting AOT-processed ProviderApplication using Java 17.0.5 with PID 21249 (/root/spring-cloud-alibaba-graalvm/spring-cloud-alibaba-dubbo/spring-cloud-alibaba-dubbo-producer/target/spring-cloud-alibaba-dubbo-producer started by root in /root/spring-cloud-alibaba-graalvm/spring-cloud-alibaba-dubbo/spring-cloud-alibaba-dubbo-producer/target)
2023-10-23T11:01:22.848+08:00  INFO 21249 --- [           main] o.a.d.s.d.provider.ProviderApplication   : No active profile set, falling back to 1 default profile: "default"
2023-10-23T11:01:22.940+08:00  INFO 21249 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=b85fb125-2d6c-3e29-b9fb-7d7fde260925
2023-10-23T11:01:22.974+08:00  INFO 21249 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2023-10-23T11:01:22.974+08:00  INFO 21249 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-10-23T11:01:22.974+08:00  INFO 21249 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.5]
2023-10-23T11:01:22.979+08:00  INFO 21249 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-10-23T11:01:22.979+08:00  INFO 21249 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 130 ms
2023-10-23T11:01:23.054+08:00  WARN 21249 --- [           main] i.m.c.i.binder.jvm.JvmGcMetrics          : GC notifications will not be available because MemoryPoolMXBeans are not provided by the JVM
2023-10-23T11:01:23.068+08:00  INFO 21249 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2023-10-23T11:01:23.069+08:00  WARN 21249 --- [           main] w.s.c.ServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ServiceBean:org.apache.dubbo.springboot.demo.DemoService::': Instantiation of supplied bean failed
2023-10-23T11:01:23.069+08:00  WARN 21249 --- [           main] o.s.b.f.support.DisposableBeanAdapter    : Failed to invoke custom destroy method 'close' on bean with name 'nacosServiceRegistry'

com.oracle.svm.core.jdk.UnsupportedFeatureError: Runtime reflection is not supported for public abstract void org.springframework.cloud.client.serviceregistry.ServiceRegistry.close()
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89) ~[na:na]
	at java.base@17.0.5/java.lang.reflect.Method.acquireMethodAccessor(Method.java:71) ~[spring-cloud-alibaba-dubbo-producer:na]
	at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:566) ~[spring-cloud-alibaba-dubbo-producer:na]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:283) ~[na:na]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:232) ~[na:na]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587) ~[spring-cloud-alibaba-dubbo-producer:6.0.4]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559) ~[spring-cloud-alibaba-dubbo-producer:6.0.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1177) ~[spring-cloud-alibaba-dubbo-producer:6.0.4]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520) ~[spring-cloud-alibaba-dubbo-producer:6.0.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1170) ~[spring-cloud-alibaba-dubbo-producer:6.0.4]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1082) ~[spring-cloud-alibaba-dubbo-producer:6.0.4]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:597) ~[spring-cloud-alibaba-dubbo-producer:6.0.4]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-cloud-alibaba-dubbo-producer:3.0.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-cloud-alibaba-dubbo-producer:3.0.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[spring-cloud-alibaba-dubbo-producer:3.0.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-cloud-alibaba-dubbo-producer:3.0.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[spring-cloud-alibaba-dubbo-producer:3.0.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[spring-cloud-alibaba-dubbo-producer:3.0.2]
	at org.apache.dubbo.springboot.demo.provider.ProviderApplication.main(ProviderApplication.java:29) ~[spring-cloud-alibaba-dubbo-producer:na]

2023-10-23T11:01:23.070+08:00  INFO 21249 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2023-10-23T11:01:23.071+08:00 ERROR 21249 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ServiceBean:org.apache.dubbo.springboot.demo.DemoService::': Instantiation of supplied bean failed
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainInstanceFromSupplier(AbstractAutowireCapableBeanFactory.java:1236) ~[spring-cloud-alibaba-dubbo-producer:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1210) ~[spring-cloud-alibaba-dubbo-producer:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1157) ~[spring-cloud-alibaba-dubbo-producer:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[spring-cloud-alibaba-dubbo-producer:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-cloud-alibaba-dubbo-producer:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-cloud-alibaba-dubbo-producer:6.0.4]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-cloud-alibaba-dubbo-producer:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-cloud-alibaba-dubbo-producer:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-cloud-alibaba-dubbo-producer:6.0.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:961) ~[spring-cloud-alibaba-dubbo-producer:6.0.4]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:915) ~[spring-cloud-alibaba-dubbo-producer:6.0.4]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[spring-cloud-alibaba-dubbo-producer:6.0.4]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-cloud-alibaba-dubbo-producer:3.0.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-cloud-alibaba-dubbo-producer:3.0.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[spring-cloud-alibaba-dubbo-producer:3.0.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-cloud-alibaba-dubbo-producer:3.0.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[spring-cloud-alibaba-dubbo-producer:3.0.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[spring-cloud-alibaba-dubbo-producer:3.0.2]
	at org.apache.dubbo.springboot.demo.provider.ProviderApplication.main(ProviderApplication.java:29) ~[spring-cloud-alibaba-dubbo-producer:na]
Caused by: java.lang.IllegalStateException: Failed to create adaptive instance: java.lang.IllegalStateException: Can't create adaptive extension interface org.apache.dubbo.rpc.Protocol, cause: No adaptive method exist on extension org.apache.dubbo.rpc.Protocol, refuse to create the adaptive class!
	at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtension(ExtensionLoader.java:750) ~[spring-cloud-alibaba-dubbo-producer:3.3.0-beta.1]
	at org.apache.dubbo.config.ServiceConfig.postProcessAfterScopeModelChanged(ServiceConfig.java:183) ~[spring-cloud-alibaba-dubbo-producer:3.3.0-beta.1]
	at org.apache.dubbo.config.AbstractConfig.setScopeModel(AbstractConfig.java:428) ~[spring-cloud-alibaba-dubbo-producer:3.3.0-beta.1]
	at org.apache.dubbo.config.AbstractConfig.<init>(AbstractConfig.java:129) ~[spring-cloud-alibaba-dubbo-producer:3.3.0-beta.1]
	at org.apache.dubbo.config.AbstractMethodConfig.<init>(AbstractMethodConfig.java:110) ~[spring-cloud-alibaba-dubbo-producer:3.3.0-beta.1]
	at org.apache.dubbo.config.AbstractInterfaceConfig.<init>(AbstractInterfaceConfig.java:207) ~[spring-cloud-alibaba-dubbo-producer:3.3.0-beta.1]
	at org.apache.dubbo.config.AbstractServiceConfig.<init>(AbstractServiceConfig.java:162) ~[spring-cloud-alibaba-dubbo-producer:3.3.0-beta.1]
	at org.apache.dubbo.config.ServiceConfigBase.<init>(ServiceConfigBase.java:92) ~[spring-cloud-alibaba-dubbo-producer:3.3.0-beta.1]
	at org.apache.dubbo.config.ServiceConfig.<init>(ServiceConfig.java:169) ~[spring-cloud-alibaba-dubbo-producer:3.3.0-beta.1]
	at org.apache.dubbo.config.spring.ServiceBean.<init>(ServiceBean.java:58) ~[spring-cloud-alibaba-dubbo-producer:na]
	at org.apache.dubbo.config.spring.ServiceBean__BeanDefinitions.lambda$getDemoServiceInstanceSupplier$0(ServiceBean__BeanDefinitions.java:20) ~[na:na]
	at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:68) ~[spring-cloud-alibaba-dubbo-producer:6.0.4]
	at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:54) ~[spring-cloud-alibaba-dubbo-producer:6.0.4]
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.lambda$get$2(BeanInstanceSupplier.java:208) ~[na:na]
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:59) ~[spring-cloud-alibaba-dubbo-producer:6.0.4]
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:47) ~[spring-cloud-alibaba-dubbo-producer:6.0.4]
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.invokeBeanSupplier(BeanInstanceSupplier.java:216) ~[na:na]
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:208) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainInstanceFromSupplier(AbstractAutowireCapableBeanFactory.java:1225) ~[spring-cloud-alibaba-dubbo-producer:6.0.4]
	... 18 common frames omitted
Caused by: java.lang.IllegalStateException: Can't create adaptive extension interface org.apache.dubbo.rpc.Protocol, cause: No adaptive method exist on extension org.apache.dubbo.rpc.Protocol, refuse to create the adaptive class!
	at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtension(ExtensionLoader.java:1399) ~[spring-cloud-alibaba-dubbo-producer:3.3.0-beta.1]
	at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtension(ExtensionLoader.java:745) ~[spring-cloud-alibaba-dubbo-producer:3.3.0-beta.1]
	... 36 common frames omitted
Caused by: java.lang.IllegalStateException: No adaptive method exist on extension org.apache.dubbo.rpc.Protocol, refuse to create the adaptive class!
	at org.apache.dubbo.common.extension.AdaptiveClassCodeGenerator.generate(AdaptiveClassCodeGenerator.java:105) ~[na:na]
	at org.apache.dubbo.common.extension.AdaptiveClassCodeGenerator.generate(AdaptiveClassCodeGenerator.java:95) ~[na:na]
	at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtensionClass(ExtensionLoader.java:1421) ~[spring-cloud-alibaba-dubbo-producer:3.3.0-beta.1]
	at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtensionClass(ExtensionLoader.java:1408) ~[spring-cloud-alibaba-dubbo-producer:3.3.0-beta.1]
	at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtension(ExtensionLoader.java:1391) ~[spring-cloud-alibaba-dubbo-producer:3.3.0-beta.1]
	... 37 common frames omitted

**Comment by imgoby** [comment]
How to support native-image build for the demo project:  https://github.com/dubbo/dubbo/tree/3.2/dubbo-demo/dubbo-demo-spring-boot ?

**Comment by CrazyHZM** [comment]
@imgoby 
You can refer to the configuration on the samples:
https://github.com/apache/dubbo-samples/tree/master/1-basic/dubbo-samples-native-image

**Comment by imgoby** [comment]
@CrazyHZM  I run the demo https://github.com/apache/dubbo-samples/tree/master/1-basic/dubbo-samples-native-image
but failed. Step is:
In project's root, run :  mvn install -DskipTests
go to 1-basic/dubbo-samples-native-image/dubbo-samples-native-image-provider run:  mvn -Pnative native:compile
It is OK

but run the bin file. It is failed.

![image](https://github.com/apache/dubbo/assets/27885492/ea9530bc-6d77-495a-b3c2-7b34bfb44dc8)



How to resolve it???

**Comment by imgoby** [comment]
Resolve it . My project is here:
https://github.com/imgoby/spring-cloud-alibaba-graalvm
