### ISSUE TITLE
jdk21 + springboot3.1.4 + dubbo3.2.7搭建grpc服务provider报错

### ISSUE THREAD

**Issue by tf2021go** [apache/dubbo#13338]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.7
* Operating System version: windows 11
* Java version: 21

### Steps to reproduce this issue
1. 搭建dubbo-jdk21-test工程，包括interface  consumer  provider3个模块。其中interface里面有grpc proto文件，consumer和provider依赖interface模块；

2.编译各模块，运行provider  consumer

3.provider报错

### Expected Behavior

服务端接收消费端请求，打印request
消费端收到响应，打印response

### Actual Behavior

服务端报错，Server error  java.lang.RuntimeException: fieldNum should in (1,2,3)

Pls. provide [GitHub address] to reproduce this issue.

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```
服务端报错
 ```
[09/11/23 10:22:13:506 CST] DubboServerHandler-10.104.32.105:20889-thread-2 ERROR call.AbstractServerCall:  [DUBBO] Process request failed. service=org.example.protogen.DubboPredictServiceGrpc$IPredictService method=predict, dubbo version: 3.2.7, current host: 10.104.32.105, error code: 4-11. This may be caused by , go to https://dubbo.apache.org/faq/4/11 to find instructions. 
java.lang.RuntimeException: fieldNum should in (1,2,3)
	at org.apache.dubbo.rpc.protocol.tri.TripleCustomerProtocolWapper$TripleRequestWrapper.parseFrom(TripleCustomerProtocolWapper.java:269)
	at org.apache.dubbo.rpc.protocol.tri.call.ReflectionAbstractServerCall.trySetMethodDescriptor(ReflectionAbstractServerCall.java:175)
	at org.apache.dubbo.rpc.protocol.tri.call.ReflectionAbstractServerCall.parseSingleMessage(ReflectionAbstractServerCall.java:159)
	at org.apache.dubbo.rpc.protocol.tri.call.AbstractServerCall.onMessage(AbstractServerCall.java:214)
	at org.apache.dubbo.rpc.protocol.tri.stream.TripleServerStream$ServerDecoderListener.onRawMessage(TripleServerStream.java:475)
	at org.apache.dubbo.rpc.protocol.tri.frame.TriDecoder.processBody(TriDecoder.java:139)
	at org.apache.dubbo.rpc.protocol.tri.frame.TriDecoder.deliver(TriDecoder.java:86)
	at org.apache.dubbo.rpc.protocol.tri.frame.TriDecoder.deframe(TriDecoder.java:56)
	at org.apache.dubbo.rpc.protocol.tri.stream.TripleServerStream$ServerTransportObserver.doOnData(TripleServerStream.java:441)
	at org.apache.dubbo.rpc.protocol.tri.stream.TripleServerStream$ServerTransportObserver.lambda$onData$2(TripleServerStream.java:434)
	at org.apache.dubbo.common.threadpool.serial.SerializingExecutor.run(SerializingExecutor.java:102)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

客户端报错

```
[09/11/23 10:22:13:597 CST] main ERROR rpc.AsyncRpcResult:  [DUBBO] Got exception when trying to fetch the underlying result from AsyncRpcResult., dubbo version: 3.2.7, current host: **********, error code: 3-5. This may be caused by , go to https://dubbo.apache.org/faq/3/5 to find instructions. 
Exception in thread "main" org.apache.dubbo.rpc.RpcException: java.util.concurrent.ExecutionException: org.apache.dubbo.rpc.StatusRpcException: UNKNOWN : Server error
java.lang.RuntimeException: fieldNum should in (1,2,3)
	at org.apache.dubbo.rpc.protocol.tri.TripleCustomerProtocolWapper$TripleRequestWrapper.parseFrom(TripleCustomerProtocolWapper.java:269)
	at org.apache.dubbo.rpc.protocol.tri.call.ReflectionAbstractServerCall.trySetMethodDescriptor(ReflectionAbstractServerCall.java:175)
	at org.apache.dubbo.rpc.protocol.tri.call.ReflectionAbstractServerCall.parseSingleMessage(ReflectionAbstractServerCall.java:159)
	at org.apache.dubbo.rpc.protocol.tri.call.AbstractServerCall.onMessage(AbstractServerCall.java:214)
	at org.apache.dubbo.rpc.protocol.tri.stream.TripleServerStream$ServerDecoderListener.onRawMessage(TripleServerStream.java:475)

	at org.apache.dubbo.rpc.AsyncRpcResult.getAppResponse(AsyncRpcResult.java:166)
	at org.apache.dubbo.rpc.AsyncRpcResult.recreate(AsyncRpcResult.java:230)
	at org.apache.dubbo.rpc.proxy.InvocationUtil.invoke(InvocationUtil.java:61)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:75)
	at org.example.protogen.DubboPredictServiceGrpc$IPredictServiceDubboProxy0.predict(DubboPredictServiceGrpc$IPredictServiceDubboProxy0.java)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.apache.dubbo.config.spring.util.LazyTargetInvocationHandler.invoke(LazyTargetInvocationHandler.java:58)
	at org.example.protogen.DubboPredictServiceGrpc$IPredictServiceDubboProxy0.predict(DubboPredictServiceGrpc$IPredictServiceDubboProxy0.java)
	at org.example.ConsumerApplication.predict(ConsumerApplication.java:34)
	at org.example.ConsumerApplication.main(ConsumerApplication.java:29)
Caused by: java.util.concurrent.ExecutionException: org.apache.dubbo.rpc.StatusRpcException: UNKNOWN : Server error
java.lang.RuntimeException: fieldNum should in (1,2,3)
	at org.apache.dubbo.rpc.protocol.tri.TripleCustomerProtocolWapper$TripleRequestWrapper.parseFrom(TripleCustomerProtocolWapper.java:269)
	at org.apache.dubbo.rpc.protocol.tri.call.ReflectionAbstractServerCall.trySetMethodDescriptor(ReflectionAbstractServerCall.java:175)
	at org.apache.dubbo.rpc.protocol.tri.call.ReflectionAbstractServerCall.parseSingleMessage(ReflectionAbstractServerCall.java:159)
	at org.apache.dubbo.rpc.protocol.tri.call.AbstractServerCall.onMessage(AbstractServerCall.java:214)
	at org.apache.dubbo.rpc.protocol.tri.stream.TripleServerStream$ServerDecoderListener.onRawMessage(TripleServerStream.java:475)

	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at org.apache.dubbo.rpc.AsyncRpcResult.getAppResponse(AsyncRpcResult.java:161)
	... 10 more
Caused by: org.apache.dubbo.rpc.StatusRpcException: UNKNOWN : Server error
java.lang.RuntimeException: fieldNum should in (1,2,3)
	at org.apache.dubbo.rpc.protocol.tri.TripleCustomerProtocolWapper$TripleRequestWrapper.parseFrom(TripleCustomerProtocolWapper.java:269)
	at org.apache.dubbo.rpc.protocol.tri.call.ReflectionAbstractServerCall.trySetMethodDescriptor(ReflectionAbstractServerCall.java:175)
	at org.apache.dubbo.rpc.protocol.tri.call.ReflectionAbstractServerCall.parseSingleMessage(ReflectionAbstractServerCall.java:159)
	at org.apache.dubbo.rpc.protocol.tri.call.AbstractServerCall.onMessage(AbstractServerCall.java:214)
	at org.apache.dubbo.rpc.protocol.tri.stream.TripleServerStream$ServerDecoderListener.onRawMessage(TripleServerStream.java:475)

	at org.apache.dubbo.rpc.TriRpcStatus.asException(TriRpcStatus.java:214)
	at org.apache.dubbo.rpc.protocol.tri.call.UnaryClientCallListener.onClose(UnaryClientCallListener.java:54)
	at org.apache.dubbo.rpc.protocol.tri.call.TripleClientCall.onComplete(TripleClientCall.java:112)
	at org.apache.dubbo.rpc.protocol.tri.stream.TripleClientStream$ClientTransportListener.finishProcess(TripleClientStream.java:250)
	at org.apache.dubbo.rpc.protocol.tri.stream.TripleClientStream$ClientTransportListener.onTrailersReceived(TripleClientStream.java:336)
	at org.apache.dubbo.rpc.protocol.tri.stream.TripleClientStream$ClientTransportListener.lambda$onHeader$1(TripleClientStream.java:442)
	at org.apache.dubbo.common.threadpool.serial.SerializingExecutor.run(SerializingExecutor.java:102)
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor$RunnableWrapper.run(ThreadlessExecutor.java:152)
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:77)
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:205)
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:287)
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:190)
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:71)
	at org.apache.dubbo.rpc.filter.RpcExceptionFilter.invoke(RpcExceptionFilter.java:41)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CallbackRegistrationInvoker.invoke(FilterChainBuilder.java:196)
	at org.apache.dubbo.rpc.protocol.ReferenceCountInvokerWrapper.invoke(ReferenceCountInvokerWrapper.java:95)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invokeWithContext(AbstractClusterInvoker.java:383)
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:80)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:344)
	at org.apache.dubbo.rpc.cluster.router.RouterSnapshotFilter.invoke(RouterSnapshotFilter.java:46)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:108)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.rpc.cluster.filter.support.MetricsClusterFilter.invoke(MetricsClusterFilter.java:59)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:52)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.spring.security.filter.ContextHolderParametersSelectedTransferFilter.invoke(ContextHolderParametersSelectedTransferFilter.java:41)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.metrics.filter.MetricsFilter.invoke(MetricsFilter.java:76)
	at org.apache.dubbo.rpc.cluster.filter.support.MetricsConsumerFilter.invoke(MetricsConsumerFilter.java:37)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at [org.apache.dubbo.rpc.cluster.filter.support.ConsumerClassLoaderFilter.invoke(ConsumerClassLoaderFilter.java:40)]([DubboTestJdk21.zip](https://github.com/apache/dubbo/files/13303087/DubboTestJdk21.zip))
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.rpc.cluster.filter.support.ConsumerContextFilter.invoke(ConsumerContextFilter.java:116)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:334)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CallbackRegistrationInvoker.invoke(FilterChainBuilder.java:196)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$ClusterFilterInvoker.invoke(AbstractCluster.java:91)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:103)
	at org.apache.dubbo.rpc.cluster.support.wrapper.ScopeClusterInvoker.invoke(ScopeClusterInvoker.java:169)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.invoke(MigrationInvoker.java:284)
	... 9 more
```

**Comment by tf2021go** [comment]
[DubboTestJdk21.zip](https://github.com/apache/dubbo/files/13303115/DubboTestJdk21.zip)

**Comment by AlbumenJ** [comment]
@icodening @EarthChen PTAL

**Comment by xiaoyuuuuuupeng** [comment]
use dubbo version 3.1.7,
will be ok 
![Uploading WechatIMG24553.png…]()

**Comment by tf2021go** [comment]
多谢关注！
直接降级dubbo的版本，我本地会报错，找不到这个类 InstantiationAwareBeanPostProcessorAdapter。
报错的原因是，dubbo3.1.4里面引用的是spring版本是5.2.20（这个版本的spring beans里面有上面这个类），我在Provider和Consumer工程里面把这个依赖排除掉了，单独引用的6.0.12（这个版本里面没有上面这个类）。实际上这个工程把spring和dubbo的版本都降下来（dubbo2），是不报错的。
之所以要单独在Provider和Consumer里面引用spring 6.0.12，对应的spring boot版本是3.1.14，主要是这个版本开始支持jdk21。并且dubbo 3.2.7开始支持jdk21。我的目的是让spring和dubbo同时支持jdk21，保证整个项目能升级到jdk21。

> use dubbo version 3.1.7, will be ok ![WechatIMG24553](https://user-images.githubusercontent.com/30964063/283025557-342fd647-c29e-443d-8350-e7ab98f1f63b.png)

**Comment by xiaoyuuuuuupeng** [comment]
> 多谢关注！ 直接降级dubbo的版本，我本地会报错，找不到这个类 InstantiationAwareBeanPostProcessorAdapter。 报错的原因是，dubbo3.1.4里面引用的是spring版本是5.2.20（这个版本的spring beans里面有上面这个类），我在Provider和Consumer工程里面把这个依赖排除掉了，单独引用的6.0.12（这个版本里面没有上面这个类）。实际上这个工程把spring和dubbo的版本都降下来（dubbo2），是不报错的。 之所以要单独在Provider和Consumer里面引用spring 6.0.12，对应的spring boot版本是3.1.14，主要是这个版本开始支持jdk21。并且dubbo 3.2.7开始支持jdk21。我的目的是让spring和dubbo同时支持jdk21，保证整个项目能升级到jdk21。
> 
> > use dubbo version 3.1.7, will be ok ![WechatIMG24553](https://user-images.githubusercontent.com/30964063/283025557-342fd647-c29e-443d-8350-e7ab98f1f63b.png)

可以在不改动版本的情况下 使用tri协议 tri协议 支持grpc的原生调用 后续应该是不支持纯grpc协议的 dubbo.protocal.name=grpc => dubbo.protocal.name=tri 并使用Dubbo3TripleGenerator生成proto代码

**Comment by xiaoyuuuuuupeng** [comment]
debug下来看到原因可能是：客户端传递数据的时候没有用Wrapper的方式对request进行编码 是直接pb.pack的 但是服务端那里解码的时候有个函数trySetMethodDescriptor() 这里面会把字节解码成TripleRequestWrapper 所以解码出来的数据对不上导致找不到methodDescriptor 产生报错

**Comment by tf2021go** [comment]
> > 多谢关注！ 直接降级dubbo的版本，我本地会报错，找不到这个类 InstantiationAwareBeanPostProcessorAdapter。 报错的原因是，dubbo3.1.4里面引用的是spring版本是5.2.20（这个版本的spring beans里面有上面这个类），我在Provider和Consumer工程里面把这个依赖排除掉了，单独引用的6.0.12（这个版本里面没有上面这个类）。实际上这个工程把spring和dubbo的版本都降下来（dubbo2），是不报错的。 之所以要单独在Provider和Consumer里面引用spring 6.0.12，对应的spring boot版本是3.1.14，主要是这个版本开始支持jdk21。并且dubbo 3.2.7开始支持jdk21。我的目的是让spring和dubbo同时支持jdk21，保证整个项目能升级到jdk21。
> > > use dubbo version 3.1.7, will be ok ![WechatIMG24553](https://user-images.githubusercontent.com/30964063/283025557-342fd647-c29e-443d-8350-e7ab98f1f63b.png)
> 
> 可以在不改动版本的情况下 使用tri协议 tri协议 支持grpc的原生调用 后续应该是不支持纯grpc协议的 dubbo.protocal.name=grpc => dubbo.protocal.name=tri 并使用Dubbo3TripleGenerator生成proto代码

我尝试将协议改成tri，同时proto插件改成Dubbo3TripleGenerator，仍然报相同的错误：
java.lang.RuntimeException: fieldNum should in (1,2,3)
	at org.apache.dubbo.rpc.protocol.tri.TripleCustomerProtocolWapper$TripleRequestWrapper.parseFrom(TripleCustomerProtocolWapper.java:269)
	at org.apache.dubbo.rpc.protocol.tri.call.ReflectionAbstractServerCall.trySetMethodDescriptor(ReflectionAbstractServerCall.java:175)
	at org.apache.dubbo.rpc.protocol.tri.call.ReflectionAbstractServerCall.parseSingleMessage(ReflectionAbstractServerCall.java:159)
	at org.apache.dubbo.rpc.protocol.tri.call.AbstractServerCall.onMessage(AbstractServerCall.java:214)
	at org.apache.dubbo.rpc.protocol.tri.stream.TripleServerStream$ServerDecoderListener.onRawMessage(TripleServerStream.java:475)
	at org.apache.dubbo.rpc.protocol.tri.frame.TriDecoder.processBody(TriDecoder.java:139)
	at org.apache.dubbo.rpc.protocol.tri.frame.TriDecoder.deliver(TriDecoder.java:86)
	at org.apache.dubbo.rpc.protocol.tri.frame.TriDecoder.deframe(TriDecoder.java:56)
	at org.apache.dubbo.rpc.protocol.tri.stream.TripleServerStream$ServerTransportObserver.doOnData(TripleServerStream.java:441)
	at org.apache.dubbo.rpc.protocol.tri.stream.TripleServerStream$ServerTransportObserver.lambda$onData$2(TripleServerStream.java:434)
	at org.apache.dubbo.common.threadpool.serial.SerializingExecutor.run(SerializingExecutor.java:102)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by xiaoyuuuuuupeng** [comment]
> > > 多谢关注！ 直接降级dubbo的版本，我本地会报错，找不到这个类 InstantiationAwareBeanPostProcessorAdapter。 报错的原因是，dubbo3.1.4里面引用的是spring版本是5.2.20（这个版本的spring beans里面有上面这个类），我在Provider和Consumer工程里面把这个依赖排除掉了，单独引用的6.0.12（这个版本里面没有上面这个类）。实际上这个工程把spring和dubbo的版本都降下来（dubbo2），是不报错的。 之所以要单独在Provider和Consumer里面引用spring 6.0.12，对应的spring boot版本是3.1.14，主要是这个版本开始支持jdk21。并且dubbo 3.2.7开始支持jdk21。我的目的是让spring和dubbo同时支持jdk21，保证整个项目能升级到jdk21。
> > > > use dubbo version 3.1.7, will be ok ![WechatIMG24553](https://user-images.githubusercontent.com/30964063/283025557-342fd647-c29e-443d-8350-e7ab98f1f63b.png)
> > 
> > 
> > 可以在不改动版本的情况下 使用tri协议 tri协议 支持grpc的原生调用 后续应该是不支持纯grpc协议的 dubbo.protocal.name=grpc => dubbo.protocal.name=tri 并使用Dubbo3TripleGenerator生成proto代码
> 
> 我尝试将协议改成tri，同时proto插件改成Dubbo3TripleGenerator，仍然报相同的错误： java.lang.RuntimeException: fieldNum should in (1,2,3) at org.apache.dubbo.rpc.protocol.tri.TripleCustomerProtocolWapper$TripleRequestWrapper.parseFrom(TripleCustomerProtocolWapper.java:269) at org.apache.dubbo.rpc.protocol.tri.call.ReflectionAbstractServerCall.trySetMethodDescriptor(ReflectionAbstractServerCall.java:175) at org.apache.dubbo.rpc.protocol.tri.call.ReflectionAbstractServerCall.parseSingleMessage(ReflectionAbstractServerCall.java:159) at org.apache.dubbo.rpc.protocol.tri.call.AbstractServerCall.onMessage(AbstractServerCall.java:214) at org.apache.dubbo.rpc.protocol.tri.stream.TripleServerStream$ServerDecoderListener.onRawMessage(TripleServerStream.java:475) at org.apache.dubbo.rpc.protocol.tri.frame.TriDecoder.processBody(TriDecoder.java:139) at org.apache.dubbo.rpc.protocol.tri.frame.TriDecoder.deliver(TriDecoder.java:86) at org.apache.dubbo.rpc.protocol.tri.frame.TriDecoder.deframe(TriDecoder.java:56) at org.apache.dubbo.rpc.protocol.tri.stream.TripleServerStream$ServerTransportObserver.doOnData(TripleServerStream.java:441) at org.apache.dubbo.rpc.protocol.tri.stream.TripleServerStream$ServerTransportObserver.lambda$onData$2(TripleServerStream.java:434) at org.apache.dubbo.common.threadpool.serial.SerializingExecutor.run(SerializingExecutor.java:102) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41) at java.base/java.lang.Thread.run(Thread.java:1583)

[DubboTestJdk21 2.zip](https://github.com/apache/dubbo/files/13373250/DubboTestJdk21.2.zip)
需要改动的地方：
1、proto增加option java_multiple_files = true;
2、proto-plugin改为trip的
```xml
  <protocPlugins>
                        <protocPlugin>
                            <id>dubbo-grpc</id>
                            <groupId>org.apache.dubbo</groupId>
                            <artifactId>dubbo-compiler</artifactId>
                            <version>3.2.7</version>
                            <mainClass>org.apache.dubbo.gen.tri.Dubbo3TripleGenerator</mainClass>
                        </protocPlugin>
                    </protocPlugins>
```
3、修改Server和client代码 
我已经改好了 你可以下载看下 已经测过OK了

**Comment by tf2021go** [comment]
@xiaoyuuuuuupeng 多谢！我的代码按照你的修改方法改动后也运行成功了！
总结一下改动：
一、interface里面proto的编译插件改成Dubbo3TripleGenerator，同时版本升级到3.2.7；
二、interface里面proto文件option java_multiple_files = true;（这是上面proto插件升级后要求的）
三、provider和consumer里面grpc的接口类，改成triple插件编译后的新的接口类（我之前没有清除老的grpc插件编译出来的文件，仍然引用的是老的grpc接口类）
修改后：
public class PredictServer extends DubboPredictServiceTriple.PredictServiceImplBase
修改前：
public class PredictServer extends DubboPredictServiceGrpc.PredictServiceImplBase implements DubboPredictServiceGrpc.IPredictService
