### ISSUE TITLE
mesh环境序列化方式怎么修改？

### ISSUE THREAD

**Issue by yyi** [apache/dubbo#13333]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here

* Dubbo version: 3.2.7
* Operating System version: k8s 1.27.6 + istio 1.19.3 sidecar
* Java version: 17.08

设置序列化方式为fastjson2未生效，默认还是hessian2，服务端配置为：
dubbo:
  application:
    serialize-check-status: WARN
    metadata-service-port: 20885
    metadata-service-protocol: tri
    qos-enable: true
    qos-accept-foreign-ip: true
  registry:
    address: N/A
  protocol:
    name: tri
    port: 50052
    serialization: fastjson2
  provider:
    prefer-serialization: fastjson2
    serialization: fastjson2

客户端配置为：
dubbo:
  application:
    serialize-check-status: WARN
    metadata-service-port: 20885
    metadata-service-protocol: tri
    qos-enable: true
    qos-accept-foreign-ip: true
  registry:
    address: N/A
  protocol:
    name: tri
    port: 50052
    serialization: fastjson2
  consumer:
    mesh-enable: true
    serialization: fastjson2

服务端异常堆栈：
08:28:07.085 [DubboServerHandler-10.244.166.186:50052-thread-4] ERROR org.apache.dubbo.rpc.protocol.tri.call.AbstractServerCall -  [DUBBO] Process request failed. service=com.ads.baidu.api.service.BaiduService method=getGroup, dubbo version: 3.2.7, current host: 10.244.166.186, error code: 4-11. This may be caused by , go to https://dubbo.apache.org/faq/4/11 to find instructions. 
java.io.IOException: org.apache.dubbo.common.serialize.SerializationException: java.lang.UnsupportedOperationException: CollectionDeserializer[interface java.util.List]
        at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper.handleToIOException(DefaultSerializationExceptionWrapper.java:358) ~[dubbo-3.2.7.jar!/:3.2.7]
        at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper.access$000(DefaultSerializationExceptionWrapper.java:28) ~[dubbo-3.2.7.jar!/:3.2.7]
        at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper$ProxyObjectInput.readObject(DefaultSerializationExceptionWrapper.java:168) ~[dubbo-3.2.7.jar!/:3.2.7]
        at org.apache.dubbo.common.serialize.DefaultMultipleSerialization.deserialize(DefaultMultipleSerialization.java:42) ~[dubbo-3.2.7.jar!/:3.2.7]
        at org.apache.dubbo.rpc.protocol.tri.ReflectionPackableMethod$WrapRequestUnpack.unpack(ReflectionPackableMethod.java:483) ~[dubbo-3.2.7.jar!/:3.2.7]
        at org.apache.dubbo.rpc.model.WrapperUnPack.unpack(WrapperUnPack.java:23) ~[dubbo-3.2.7.jar!/:3.2.7]
        at org.apache.dubbo.rpc.protocol.tri.call.ReflectionAbstractServerCall.parseSingleMessage(ReflectionAbstractServerCall.java:166) ~[dubbo-3.2.7.jar!/:3.2.7]
        at org.apache.dubbo.rpc.protocol.tri.call.AbstractServerCall.onMessage(AbstractServerCall.java:214) ~[dubbo-3.2.7.jar!/:3.2.7]
        at org.apache.dubbo.rpc.protocol.tri.stream.TripleServerStream$ServerDecoderListener.onRawMessage(TripleServerStream.java:475) ~[dubbo-3.2.7.jar!/:3.2.7]
        at org.apache.dubbo.rpc.protocol.tri.frame.TriDecoder.processBody(TriDecoder.java:139) ~[dubbo-3.2.7.jar!/:3.2.7]
        at org.apache.dubbo.rpc.protocol.tri.frame.TriDecoder.deliver(TriDecoder.java:86) ~[dubbo-3.2.7.jar!/:3.2.7]
        at org.apache.dubbo.rpc.protocol.tri.frame.TriDecoder.deframe(TriDecoder.java:56) ~[dubbo-3.2.7.jar!/:3.2.7]
        at org.apache.dubbo.rpc.protocol.tri.stream.TripleServerStream$ServerTransportObserver.doOnData(TripleServerStream.java:441) ~[dubbo-3.2.7.jar!/:3.2.7]
        at org.apache.dubbo.rpc.protocol.tri.stream.TripleServerStream$ServerTransportObserver.lambda$onData$2(TripleServerStream.java:434) ~[dubbo-3.2.7.jar!/:3.2.7]
        at org.apache.dubbo.common.threadpool.serial.SerializingExecutor.run(SerializingExecutor.java:102) [dubbo-3.2.7.jar!/:3.2.7]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41) [dubbo-3.2.7.jar!/:3.2.7]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.apache.dubbo.common.serialize.SerializationException: java.lang.UnsupportedOperationException: CollectionDeserializer[interface java.util.List]
        ... 19 more
Caused by: java.lang.UnsupportedOperationException: CollectionDeserializer[interface java.util.List]
        at com.alibaba.com.caucho.hessian.io.AbstractDeserializer.readObject(AbstractDeserializer.java:127) ~[hessian-lite-3.2.13.jar!/:?]
        at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObjectInstance(Hessian2Input.java:2848) ~[hessian-lite-3.2.13.jar!/:?]
        at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2175) ~[hessian-lite-3.2.13.jar!/:?]
        at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2104) ~[hessian-lite-3.2.13.jar!/:?]
        at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2148) ~[hessian-lite-3.2.13.jar!/:?]
        at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2104) ~[hessian-lite-3.2.13.jar!/:?]
        at org.apache.dubbo.common.serialize.hessian2.Hessian2ObjectInput.readObject(Hessian2ObjectInput.java:109) ~[dubbo-3.2.7.jar!/:3.2.7]
        at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper$ProxyObjectInput.readObject(DefaultSerializationExceptionWrapper.java:166) ~[dubbo-3.2.7.jar!/:3.2.7]

**Comment by AlbumenJ** [comment]
dubbo.comsumer.parameter.serialization=fastjson2

**Comment by yyi** [comment]
it works! thx,how about make it default when dubbo running in mesh?

**Comment by liang2h** [comment]
I also encountered this issue, and I was able to resolve it by following the solutions mentioned above. However, I would like to correct one thing: it should be “dubbo.consumer.parameters.serialization=fastjson2”
