### ISSUE TITLE
Exception happened when delete pod

### ISSUE THREAD

**Issue by huanyang001** [apache/dubbo#13364]
报错信息如下

2023-11-15 13:32:38.220 [nacos.publisher-com.alibaba.nacos.client.naming.event.InstancesChangeEvent] ERROR c.a.nacos.common.notify.NotifyCenter -Event callback exception: 
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@186267c0 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@64e12515[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 349]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
        at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
        at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:632)
        at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:678)
        at org.apache.dubbo.registry.RegistryNotifier.notify(RegistryNotifier.java:77)
        at org.apache.dubbo.registry.nacos.NacosRegistry$RegistryChildListenerImpl.onEvent(NacosRegistry.java:665)
        at com.alibaba.nacos.client.naming.event.InstancesChangeNotifier.onEvent(InstancesChangeNotifier.java:124)
        at com.alibaba.nacos.client.naming.event.InstancesChangeNotifier.onEvent(InstancesChangeNotifier.java:40)
        at com.alibaba.nacos.common.notify.DefaultPublisher.lambda$notifySubscriber$0(DefaultPublisher.java:201)
        at com.alibaba.nacos.common.notify.DefaultPublisher.notifySubscriber(DefaultPublisher.java:208)
        at com.alibaba.nacos.common.notify.DefaultPublisher.receiveEvent(DefaultPublisher.java:192)
        at com.alibaba.nacos.common.notify.DefaultPublisher.openEventHandler(DefaultPublisher.java:118)
        at com.alibaba.nacos.common.notify.DefaultPublisher.run(DefaultPublisher.java:95)

**Comment by AlbumenJ** [comment]
Are these logs in on pod which kubernetes deleted?

**Comment by huanyang001** [comment]
> Are these logs in on pod which kubernetes deleted?

是的

**Comment by huanyang001** [comment]
> Are these logs in on pod which kubernetes deleted?



> > > Are these logs in on pod which kubernetes deleted?
> > 
> > 
> > 是的
> 
> So these logs are happened when shutdown?

是的，旧的pod被停掉的时候就会报错，有这样的log

**Comment by AlbumenJ** [comment]
Fixed in #13273

**Comment by huanyang001** [comment]
> Fixed in #13273

thanks
