### ISSUE TITLE
org.apache.dubbo.remoting.RemotingException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by zczhzy** [apache/dubbo#13411]
springboot集成dubbo，使用nacos作为注册中，dubbo版本：3.2.6，nacos-client版本：2.2.4，jdk17。

服务提供者正常注册：
![1700813587406](https://github.com/apache/dubbo/assets/4607069/49f0d000-3338-4760-a551-f0ae3ff08223)

调用方启动后，会报上面系统的错误，主要日志：

org.apache.dubbo.registry.client.metadata.MetadataUtils, [DUBBO] Failed to get app metadata for revision 90037953236eb9f5fa855ae0f241794a for type local from instance 172.20.1.2:20880, dubbo version: 3.2.6, current host: 172.20.1.22, error code: 1-39. This may be caused by , go to https://dubbo.apache.org/faq/1/39 to find instructions.
org.apache.dubbo.rpc.RpcException: Failed to invoke remote method: getMetadataInfo, provider: dubbo://172.20.1.2:20881/org.apache.dubbo.metadata.MetadataService?connections=1&corethreads=2&dubbo=2.0.2&group=xxxxxxxxxxxxxx&port=20881&prefer.serialization=fastjson2,hessian2&protocol=dubbo&release=3.2.6&retries=0&side=consumer&threadpool=cached&threads=100&timeout=5000&version=1.0.0, cause: org.apache.dubbo.remoting.RemotingException: java.lang.NullPointerException
java.lang.NullPointerException
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:296) ~[dubbo-3.2.6.jar!/:3.2.6]
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:190) ~[dubbo-3.2.6.jar!/:3.2.6]
	at org.apache.dubbo.rpc.proxy.InvocationUtil.invoke(InvocationUtil.java:61) ~[dubbo-3.2.6.jar!/:3.2.6]
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:75) ~[dubbo-3.2.6.jar!/:3.2.6]
	at org.apache.dubbo.metadata.MetadataServiceDubboProxy51.getMetadataInfo(MetadataServiceDubboProxy51.java) ~[dubbo-3.2.6.jar!/:3.2.6]
	at org.apache.dubbo.registry.client.metadata.MetadataUtils.getRemoteMetadata(MetadataUtils.java:173) ~[dubbo-3.2.6.jar!/:3.2.6]
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.lambda$getRemoteMetadata$2(AbstractServiceDiscovery.java:229) ~[dubbo-3.2.6.jar!/:3.2.6]
	at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:86) ~[dubbo-3.2.6.jar!/:3.2.6]
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.getRemoteMetadata(AbstractServiceDiscovery.java:228) ~[dubbo-3.2.6.jar!/:3.2.6]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.lambda$doOnEvent$2(ServiceInstancesChangedListener.java:162) ~[dubbo-3.2.6.jar!/:3.2.6]
	at java.util.Optional.orElseGet(Optional.java:364) [?:?]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.doOnEvent(ServiceInstancesChangedListener.java:162) [dubbo-3.2.6.jar!/:3.2.6]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.onEvent(ServiceInstancesChangedListener.java:116) [dubbo-3.2.6.jar!/:3.2.6]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener$AddressRefreshRetryTask.run(ServiceInstancesChangedListener.java:489) [dubbo-3.2.6.jar!/:3.2.6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

Caused by: java.util.concurrent.ExecutionException: org.apache.dubbo.remoting.RemotingException: java.lang.NullPointerException
java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096) ~[?:?]
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:218) ~[dubbo-3.2.6.jar!/:3.2.6]
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:287) ~[dubbo-3.2.6.jar!/:3.2.6]
	... 19 more

Caused by: org.apache.dubbo.remoting.RemotingException: java.lang.NullPointerException
java.lang.NullPointerException
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.doReceived(DefaultFuture.java:249) ~[dubbo-3.2.6.jar!/:3.2.6]
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:200) ~[dubbo-3.2.6.jar!/:3.2.6]
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:188) ~[dubbo-3.2.6.jar!/:3.2.6]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleResponse(HeaderExchangeHandler.java:65) ~[dubbo-3.2.6.jar!/:3.2.6]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:206) ~[dubbo-3.2.6.jar!/:3.2.6]
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:53) ~[dubbo-3.2.6.jar!/:3.2.6]
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:62) ~[dubbo-3.2.6.jar!/:3.2.6]
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor$RunnableWrapper.run(ThreadlessExecutor.java:152) ~[dubbo-3.2.6.jar!/:3.2.6]
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:77) ~[dubbo-3.2.6.jar!/:3.2.6]
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:205) ~[dubbo-3.2.6.jar!/:3.2.6]
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:287) ~[dubbo-3.2.6.jar!/:3.2.6]
	... 19 more

调用方在调其他系统dubbo接口时没问题，唯独其中一个服务提供者系统有这样的问题，对比了相关配置，暂时没发现问题，请问可能是什么原因造成这样的问题？

**Comment by your-boy** [comment]
巧了，我也碰到了这个问题

**Comment by lizf2014** [comment]
我也碰到了这个问题，请问解决了吗？
