### ISSUE TITLE
project with dubbo 3.3.0-beta.1 built in native-image has exception "Caused by: javassist.NotFoundException: org.apache.dubbo.common.bytecode.ClassGenerator$DC"

### ISSUE THREAD

**Issue by imgoby** [apache/dubbo#13455]
<dubbo.version>3.3.0-beta.1</dubbo.version>
project demo:
https://github.com/imgoby/spring-cloud-alibaba-dubbo-native/tree/main/dubbo-samples-native-image-registry-consumer

built with native-image
```

2023-12-04T14:23:08.341+08:00 ERROR 2480 --- [           main] o.a.dubbo.config.spring.ReferenceBean    :  [DUBBO] Failed to generate proxy by Javassist failed. Fallback to use JDK proxy success. Interfaces: [interface com.yuhoutian.demo.api.DemoService, interface org.apache.dubbo.rpc.service.EchoService, interface org.apache.dubbo.rpc.service.Destroyable], dubbo version: 3.3.0-beta.1, current host: 192.168.0.219, error code: 3-8. This may be caused by , go to https://dubbo.apache.org/faq/3/8 to find instructions. 

java.lang.RuntimeException: org.apache.dubbo.common.bytecode.ClassGenerator$DC
	at org.apache.dubbo.common.bytecode.ClassGenerator.toClass(ClassGenerator.java:362)
	at org.apache.dubbo.common.bytecode.Proxy.buildProxyClass(Proxy.java:171)
	at org.apache.dubbo.common.bytecode.Proxy.getProxy(Proxy.java:87)
	at org.apache.dubbo.config.spring.ReferenceBean.generateFromJavassistFirst(ReferenceBean.java:372)
	at org.apache.dubbo.config.spring.ReferenceBean.createLazyProxy(ReferenceBean.java:362)
	at org.apache.dubbo.config.spring.ReferenceBean.getObject(ReferenceBean.java:206)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:148)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:90)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1823)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1273)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:259)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.apache.dubbo.config.spring6.beans.factory.aot.ReferencedFieldValueResolver.resolveValue(ReferencedFieldValueResolver.java:195)
	at org.apache.dubbo.config.spring6.beans.factory.aot.ReferencedFieldValueResolver.resolveAndSet(ReferencedFieldValueResolver.java:172)
	at com.yuhoutian.demo.consumer.Task__DubboReference.apply(Task__DubboReference.java:14)
	at org.springframework.beans.factory.support.InstanceSupplier$1.get(InstanceSupplier.java:83)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.obtainInstanceFromSupplier(DefaultListableBeanFactory.java:947)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1158)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293)
	at com.yuhoutian.demo.consumer.ConsumerApplication.main(ConsumerApplication.java:31)
Caused by: javassist.NotFoundException: org.apache.dubbo.common.bytecode.ClassGenerator$DC
	at javassist.ClassPool.get(ClassPool.java:430)
	at org.apache.dubbo.common.bytecode.ClassGenerator.toClass(ClassGenerator.java:314)
	... 34 common frames omitted

```

**Comment by imgoby** [comment]
Do you mean it doesn't support native-image?how to config?

**Comment by CrazyHZM** [comment]
This does not affect the normal execution; let's see how to eliminate this prompt.
@imgoby
