### ISSUE TITLE
Dubbo judges two different RegistryConfigs by equals

### ISSUE THREAD

**Issue by alcoveWander** [apache/dubbo#13462]
### Environment

* Dubbo version: 3.2.8
* Operating System version: mac
* Java version: JDK17

### Steps to reproduce this issue

1. in my project , I have two registryConfigs in SpringBoot Framework like these:

```
    @Bean
    public RegistryConfig registryConfig() {
        RegistryConfig registryConfig = new RegistryConfig();
        registryConfig.setId("r1");
        registryConfig.setProtocol("zookeeper");
        registryConfig.setAddress(dubboRegistryAddress);
        registryConfig.setTimeout(60000);
        return registryConfig;
    }

    @Bean
    public RegistryConfig registryConfig2() {
        RegistryConfig registryConfig = new RegistryConfig();
        registryConfig.setId("configReg");
        registryConfig.setProtocol("zookeeper");
        registryConfig.setAddress(dubboConfigRegistryAddress);
        registryConfig.setTimeout(60000);
        return registryConfig;
    }
```

    When in different environments (product,test and etc...), the 'dubboRegistryAddress'  and  'dubboConfigRegistryAddress' may be different. but in test env, the 'dubboRegistryAddress'  and  'dubboConfigRegistryAddress'  is the same.

2. Then when I upgrade the dubbo version from 2.7.9 to 3.2.8 and startup the project, it turns to be error:

```
    Caused by: java.lang.IllegalStateException: Registry not found: configReg
	at org.apache.dubbo.config.AbstractInterfaceConfig.lambda$convertRegistryIdsToRegistries$5(AbstractInterfaceConfig.java:505) ~[dubbo-3.2.8.jar:3.2.8]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at org.apache.dubbo.config.AbstractInterfaceConfig.convertRegistryIdsToRegistries(AbstractInterfaceConfig.java:499) ~[dubbo-3.2.8.jar:3.2.8]
	at org.apache.dubbo.config.AbstractInterfaceConfig.checkRegistry(AbstractInterfaceConfig.java:253) ~[dubbo-3.2.8.jar:3.2.8]
	at org.apache.dubbo.config.ReferenceConfig.checkAndUpdateSubConfigs(ReferenceConfig.java:750) ~[dubbo-3.2.8.jar:3.2.8]
	at org.apache.dubbo.config.ReferenceConfig.postProcessRefresh(ReferenceConfig.java:761) ~[dubbo-3.2.8.jar:3.2.8]
	at org.apache.dubbo.config.AbstractConfig.refresh(AbstractConfig.java:697) ~[dubbo-3.2.8.jar:3.2.8]
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:317) ~[dubbo-3.2.8.jar:3.2.8]
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:238) ~[dubbo-3.2.8.jar:3.2.8]
	at org.apache.dubbo.config.ReferenceConfigBase.get(ReferenceConfigBase.java:381) ~[dubbo-3.2.8.jar:3.2.8]
	at org.apache.dubbo.config.spring.ReferenceBean.getCallProxy(ReferenceBean.java:407) ~[dubbo-3.2.8.jar:3.2.8]
    ```

    Then I look into the source code of dubbo, I found when register the RegistryConfig bean into cache, it judges the difference by equals method of it . So if first registryConfig bean was registered to the cache , the second won't be add to the configsMap below:

![image](https://github.com/apache/dubbo/assets/87684149/3fe37b3e-38fb-4e67-9ffd-9402a1d62a42)
  
    But in test env , I do need both the two registryConfigs to be registered to String.

   And then I looked back to old source code of 2.7.9 of dubbo, I found it was judged by the id of registryConfig:
  
 
![image](https://github.com/apache/dubbo/assets/87684149/56cf9431-15aa-482a-ad60-80e3ced2aa13)

  so it is not a problem in version of 2.7.9.

  I understand you want to avoid to register two same registryConfigs , but when in differrent envs ,the registry address can be same of different by spring injected value.it is a real existed requirement.(In product environment , the two address is different and both can be registered, but in test environment, the second cannot be registered.)

### Expected Behavior

Maybe you can recover the judging difference of config by id like the way in old versions.

### Actual Behavior

If there is an exception, please attach the exception trace:
```
Caused by: java.lang.IllegalStateException: Registry not found: configReg
	at org.apache.dubbo.config.AbstractInterfaceConfig.lambda$convertRegistryIdsToRegistries$5(AbstractInterfaceConfig.java:505) ~[dubbo-3.2.8.jar:3.2.8]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at org.apache.dubbo.config.AbstractInterfaceConfig.convertRegistryIdsToRegistries(AbstractInterfaceConfig.java:499) ~[dubbo-3.2.8.jar:3.2.8]
	at org.apache.dubbo.config.AbstractInterfaceConfig.checkRegistry(AbstractInterfaceConfig.java:253) ~[dubbo-3.2.8.jar:3.2.8]
	at org.apache.dubbo.config.ReferenceConfig.checkAndUpdateSubConfigs(ReferenceConfig.java:750) ~[dubbo-3.2.8.jar:3.2.8]
	at org.apache.dubbo.config.ReferenceConfig.postProcessRefresh(ReferenceConfig.java:761) ~[dubbo-3.2.8.jar:3.2.8]
	at org.apache.dubbo.config.AbstractConfig.refresh(AbstractConfig.java:697) ~[dubbo-3.2.8.jar:3.2.8]
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:317) ~[dubbo-3.2.8.jar:3.2.8]
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:238) ~[dubbo-3.2.8.jar:3.2.8]
	at org.apache.dubbo.config.ReferenceConfigBase.get(ReferenceConfigBase.java:381) ~[dubbo-3.2.8.jar:3.2.8]
	at org.apache.dubbo.config.spring.ReferenceBean.getCallProxy(ReferenceBean.java:407) ~[dubbo-3.2.8.jar:3.2.8]
```

**Comment by XIACYBING** [comment]
i don't understand why the comparison of id value is ignored in AbstractConfig...

isn't id a unique identifier for a config?

![image](https://github.com/apache/dubbo/assets/39894036/577609c9-9971-464a-a60b-7a6a34d116b9)

**Comment by AlbumenJ** [comment]
Because id can be automatically generated by spring configure.

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
