### ISSUE TITLE
Got exception with triple protocol when `package` and `java_package` are different in .proto

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo#13496]
**Dubbo version:** 3.3.0-beta.1, 3.2.9
**Protocol:** triple with protobuf
**JDK:** 17

When `package` and `java_package` are different in .proto 

```protobuf
syntax = "proto3";

option java_multiple_files = true;
option java_package = "org.apache.dubbo.springboot.demo.idl";

package greet;

message GreeterRequest {
  string name = 1;
}

message GreeterReply {
  string message = 1;
}

service Greeter{

  rpc greet(GreeterRequest) returns (GreeterReply);

}

```

Got the following 

```java
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.getGenericReturnType()" because the return value of "org.apache.dubbo.rpc.model.MethodDescriptor.getMethod()" is null
	at org.apache.dubbo.rpc.protocol.tri.ReflectionPackableMethod.needWrap(ReflectionPackableMethod.java:247) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.apache.dubbo.rpc.protocol.tri.h12.http2.GenericHttp2ServerTransportListener.startListener(GenericHttp2ServerTransportListener.java:93) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.apache.dubbo.rpc.protocol.tri.h12.http2.GenericHttp2ServerTransportListener.initializeServerCallListener(GenericHttp2ServerTransportListener.java:202) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.apache.dubbo.rpc.protocol.tri.h12.http2.GenericHttp2ServerTransportListener.newHttpMessageListener(GenericHttp2ServerTransportListener.java:150) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.apache.dubbo.rpc.protocol.tri.h12.grpc.GrpcHttp2ServerTransportListener.access$1001(GrpcHttp2ServerTransportListener.java:54) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.apache.dubbo.rpc.protocol.tri.h12.grpc.GrpcHttp2ServerTransportListener$DetermineMethodDescriptorListener.onFragmentMessage(GrpcHttp2ServerTransportListener.java:202) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.apache.dubbo.remoting.http12.message.LengthFieldStreamingDecoder.invokeListener(LengthFieldStreamingDecoder.java:171) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.apache.dubbo.remoting.http12.message.LengthFieldStreamingDecoder.processBody(LengthFieldStreamingDecoder.java:163) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.apache.dubbo.remoting.http12.message.LengthFieldStreamingDecoder.deliver(LengthFieldStreamingDecoder.java:108) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.apache.dubbo.remoting.http12.message.LengthFieldStreamingDecoder.decode(LengthFieldStreamingDecoder.java:72) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.apache.dubbo.rpc.protocol.tri.h12.grpc.GrpcHttp2ServerTransportListener$LazyFindMethodListener.onMessage(GrpcHttp2ServerTransportListener.java:149) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.apache.dubbo.rpc.protocol.tri.h12.AbstractServerTransportListener.doOnData(AbstractServerTransportListener.java:190) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.apache.dubbo.rpc.protocol.tri.h12.AbstractServerTransportListener.lambda$onData$1(AbstractServerTransportListener.java:178) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.apache.dubbo.common.threadpool.serial.SerializingExecutor.run(SerializingExecutor.java:102) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

**Comment by chickenlj** [comment]
Use the following example to reproduce

https://github.com/chickenlj/dubbo-samples/tree/add-spring-boot-idl-sample/1-basic/dubbo-samples-spring-boot-idl
