### ISSUE TITLE
Class cast exception running triple with injvm mode, dubbo 3.3.0-beta.1, jdk 17

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo#13498]
**Dubbo Version:** 3.3.0-beta.1
**Protocol:** triple protocol with injvm mode, which means consumer and provider run in the same process
**JDK:** 17

```java
2023-12-14 10:45:14.067  INFO 36752 --- [resh-0-thread-1] o.a.d.r.m.ModuleModel                    :  [DUBBO] Dynamically registering consumer model dubbo-springboot-demo-idl-provider/org.apache.dubbo.metadata.MetadataService:1.0.0 into model Dubbo Module[1.1.0], dubbo version: 3.3.0-beta.1, current host: 30.221.148.148
2023-12-14 10:45:14.071 ERROR 36752 --- [           main] o.s.b.SpringApplication                  : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-2.7.8.jar:2.7.8]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752) ~[spring-boot-2.7.8.jar:2.7.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.7.8.jar:2.7.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.7.8.jar:2.7.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.7.8.jar:2.7.8]
	at org.apache.dubbo.springboot.demo.provider.ProviderApplication.main(ProviderApplication.java:29) ~[classes/:?]
Caused by: java.lang.ClassCastException: class org.apache.dubbo.springboot.demo.idl.GreeterRequest cannot be cast to class org.apache.dubbo.springboot.demo.idl.GreeterReply (org.apache.dubbo.springboot.demo.idl.GreeterRequest and org.apache.dubbo.springboot.demo.idl.GreeterReply are in unnamed module of loader 'app')
	at org.apache.dubbo.springboot.demo.idl.DubboGreeterTriple$GreeterStub.greet(DubboGreeterTriple.java:93) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.apache.dubbo.config.spring.util.LazyTargetInvocationHandler.invoke(LazyTargetInvocationHandler.java:58) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.apache.dubbo.springboot.demo.idl.GreeterDubboProxy0.greet(GreeterDubboProxy0.java) ~[classes/:?]
	at org.apache.dubbo.springboot.demo.provider.dubbo.consumer.Consumer.run(Consumer.java:20) ~[classes/:?]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:768) ~[spring-boot-2.7.8.jar:2.7.8]
	... 5 more

```

**Comment by chickenlj** [comment]
Sample to reproduce: https://github.com/chickenlj/dubbo-samples/tree/add-spring-boot-idl-sample2/1-basic/dubbo-samples-spring-boot-idl3
