### ISSUE TITLE
Help：Failed to check the status of the service 

### ISSUE THREAD

**Issue by mayunSaicmotor** [apache/dubbo#13517]
Dear，

I  use dubbo ReferenceConfig to invoke a remote dubbo service,but ,failed. 

my code is below:
<img width="1082" alt="image" src="https://github.com/apache/dubbo/assets/22955377/d03a0f8d-3b45-43f0-b970-4235822ae531">

the error is below:
<img width="1702" alt="image" src="https://github.com/apache/dubbo/assets/22955377/8b7bbb0f-5b48-4284-ac1f-678229f21016">

I checked the nacos web console, the service is already there
<img width="1479" alt="image" src="https://github.com/apache/dubbo/assets/22955377/df0c77a4-6976-43e7-aebb-e5b9ea16ccd9">

Is anybody can help me?

**Comment by mayunSaicmotor** [comment]
error  log:
Exception in thread "main" java.lang.IllegalStateException: Failed to check the status of the service com.rrht.common.service.sys.SysUserService. No provider available for the service parking/com.rrht.common.service.sys.SysUserService:1.2 from the url nacos://127.0.0.1:8848/org.apache.dubbo.registry.RegistryService?application=test-consumer&dubbo=2.0.2&generic=true&group=parking&interface=com.rrht.common.service.sys.SysUserService&pid=68207&register.ip=10.31.200.128&release=2.7.8&side=consumer&sticky=false&timeout=3000&timestamp=1702875356959&version=1.2 to the consumer 10.31.200.128 use dubbo version 2.7.8
	at org.apache.dubbo.config.ReferenceConfig.checkInvokerAvailable(ReferenceConfig.java:420)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:315)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:205)
	at com.rrht.gateway.GateWayApplication.main(GateWayApplication.java:48)

**Comment by kazetyan** [comment]
see`https://github.com/apache/dubbo-samples/blob/master/1-basic/dubbo-samples-api/src/main/java/org/apache/dubbo/samples/client/Application.java` 
i think dubbo app maybe not started,add`DubboBootstrap.getInstance().reference(reference).start();` and tries again,please.

**Comment by mayunSaicmotor** [comment]
<img width="1709" alt="image" src="https://github.com/apache/dubbo/assets/22955377/257772dc-8a5a-4426-a1c4-814f3ba310ee">

Still have the same issue, please give me more help, thanks

**Comment by kazetyan** [comment]
i found it.
see #5349 
nacos's groupName is not dubbo's group.
you must register provider to `DEFAULT_GROUP` group.

**Comment by kazetyan** [comment]
and see #5978 
dubbo supported it after 2.7.7
nacos's groupName can be set by `dubbo.registry.group`.
so,you can call `RegistryConfig#setGroup` to set nacos's groupName.
just like this:
```java
    RegistryConfig registryConfig = new RegistryConfig("nacos://127.0.0.1:8848");
    registryConfig.setGroup("parking");
```

**Comment by mayunSaicmotor** [comment]
@kazetyan  , thank you  very much, it works.
<img width="1062" alt="image" src="https://github.com/apache/dubbo/assets/22955377/771ab766-0980-4cec-9ed7-0448b29e41a2">
