### ISSUE TITLE
fastjson2 unable to backward compatibility

### ISSUE THREAD

**Issue by owen200008** [apache/dubbo#13519]
when the provider response add some member（like Integer） 

the consumer no update，then call the provider will be error。like following:

cause: org.apache.dubbo.remoting.RemotingException: java.io.IOException: org.apache.dubbo.common.serialize.SerializationException: com.alibaba.fastjson2.JSONException: skip not support type INT32 68

**Comment by owen200008** [comment]
https://github.com/alibaba/fastjson2/issues/2078

**Comment by zhaoyunxing92** [comment]
看下是不是跟这个问题类似：https://github.com/apache/dubbo/issues/13518

**Comment by owen200008** [comment]
不是 定义父类实际返回子类 这个问题建议是不要这样用 req和rsp用final

**Comment by zhaoyunxing92** [comment]
可以提供下简单的 demo 吗

**Comment by lihuagang03** [comment]
温少，我们升级到`dubbo-3.2.10`、`fastjson2-2.0.43`，还有遇到这个问题。
麻烦帮忙再看下，感谢  @wenshao 

我们排查到的一些信息与线索，消费者和提供者使用的响应结构有一些差异，JSONB协议通过字段类型和顺序进行了数据空间压缩，丢失字段名称，会带来对象字段签名问题(与方法参数列表签名类似)，不能随意在中间随意增加新的字段。新的字段，需要添加在对象末尾。
不知道我这样理解，对不对？

```
java.io.IOException: org.apache.dubbo.common.serialize.SerializationException: com.alibaba.fastjson2.JSONException: skip not support type INT32 68
  at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper.handleToIOException(DefaultSerializationExceptionWrapper.java:353)
  at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper.access$000(DefaultSerializationExceptionWrapper.java:27)
  at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper$ProxyObjectInput.readObject(DefaultSerializationExceptionWrapper.java:172)
  at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.handleValue(DecodeableRpcResult.java:176)
  at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:110)
  at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:153)
  at org.apache.dubbo.remoting.transport.DecodeHandler.decode(DecodeHandler.java:61)
  at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:49)
  at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:64)
  at org.apache.dubbo.common.threadpool.ThreadlessExecutor$RunnableWrapper.run(ThreadlessExecutor.java:151)
  at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:77)
  at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:219)
  at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:292)
  at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:194)
  at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:71)
  at org.apache.dubbo.rpc.filter.RpcExceptionFilter.invoke(RpcExceptionFilter.java:40)
  at com.leoao.starter.dubbo.generic.GenericFilterWrapper.invoke(GenericFilterWrapper.java:67)
  at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:349)
  at com.lefit.conf.DubboFilter.invoke(DubboFilter.java:61)
  at com.leoao.starter.dubbo.generic.GenericFilterWrapper.invoke(GenericFilterWrapper.java:67)
  at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:349)
  at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CallbackRegistrationInvoker.invoke(FilterChainBuilder.java:197)
  at org.apache.dubbo.rpc.protocol.ReferenceCountInvokerWrapper.invoke(ReferenceCountInvokerWrapper.java:106)
  at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invokeWithContext(AbstractClusterInvoker.java:412)
  at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:82)
  at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:366)
  at org.apache.dubbo.rpc.cluster.router.RouterSnapshotFilter.invoke(RouterSnapshotFilter.java:46)
  at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:349)
  at ...
Caused by: org.apache.dubbo.common.serialize.SerializationException: com.alibaba.fastjson2.JSONException: skip not support type INT32 68
  ... 130 common frames omitted
Caused by: com.alibaba.fastjson2.JSONException: skip not support type INT32 68
  at com.alibaba.fastjson2.JSONReaderJSONB.skipValue(JSONReaderJSONB.java:2461)
  at com.alibaba.fastjson2.reader.ObjectReaderBean.processExtra(ObjectReaderBean.java:129)
  at com.alibaba.fastjson2.reader.ORG_20_2_StoreGroundThemeDTO.readJSONBObject(Unknown Source)
  at com.alibaba.fastjson2.reader.ORG_18_7_StoreBaseInfoResponseDTO.readJSONBObject(Unknown Source)
  at com.alibaba.fastjson2.reader.ObjectReaderImplObject.readJSONBObject(ObjectReaderImplObject.java:319)
  at com.alibaba.fastjson2.reader.ORG_17_4_CommonResponse.readJSONBObject(Unknown Source)
  at com.alibaba.fastjson2.JSONB.parseObject(JSONB.java:540)
  at org.apache.dubbo.common.serialize.fastjson2.FastJson2ObjectInput.readObject(FastJson2ObjectInput.java:171)
  at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper$ProxyObjectInput.readObject(DefaultSerializationExceptionWrapper.java:170)
  ... 127 common frames omitted

```

**Comment by lihuagang03** [comment]
温少，我的理解，`skip not support type INT32 69` 也是类似的  @wenshao 

```
org.apache.dubbo.common.serialize.SerializationException: com.alibaba.fastjson2.JSONException: skip not support type INT32 69
    ... 153 more
Caused by: com.alibaba.fastjson2.JSONException: skip not support type INT32 69
    at com.alibaba.fastjson2.JSONReaderJSONB.skipValue(JSONReaderJSONB.java:2461)
    at com.alibaba.fastjson2.reader.ObjectReaderBean.processExtra(ObjectReaderBean.java:129)
    at com.alibaba.fastjson2.reader.ORG_6_31_StoreFrontSimpleResponse.readJSONBObject(Unknown Source)
    at com.alibaba.fastjson2.reader.ObjectReaderImplObject.readJSONBObject(ObjectReaderImplObject.java:319)
    at com.alibaba.fastjson2.reader.ORG_5_4_CommonResponse.readJSONBObject(Unknown Source)
    at com.alibaba.fastjson2.JSONB.parseObject(JSONB.java:540)
    at org.apache.dubbo.common.serialize.fastjson2.FastJson2ObjectInput.readObject(FastJson2ObjectInput.java:171)
    at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper$ProxyObjectInput.readObject(DefaultSerializationExceptionWrapper.java:170
```

**Comment by AlbumenJ** [comment]
Track in fastjson2
