### ISSUE TITLE
program built with native-image runs failed.Could you give me some advice?

### ISSUE THREAD

**Issue by imgoby** [apache/dubbo#13550]
my demo project ( https://github.com/imgoby/spring-cloud-alibaba-dubbo-native/tree/main/spring-cloud-alibaba-consul-dubbo-provider )  is OK.but My production project has Exception:

       <spring.cloud.version>2022.0.0</spring.cloud.version>
        <spring-boot.version>3.0.9</spring-boot.version>
<dubbo.version>3.3.0-beta.1</dubbo.version>

My production project has more dependency. I don't know what affects it.
Could you give me some advice?

```

Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
11:27:42,035 |-WARN in ch.qos.logback.classic.model.processor.ConfigurationModelHandler - Due to missing top level configuration file, reconfiguration on change (configuration file scanning) cannot be done.
11:27:42,035 |-INFO in ch.qos.logback.classic.model.processor.ContextNameModelHandler - Setting logger context name as [logback]
11:27:42,035 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [console]
11:27:42,035 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
11:27:42,036 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:27:42,036 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [file]
11:27:42,036 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
11:27:42,037 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1099455902 - Archive files will be limited to [500 MB] each.
11:27:42,037 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1099455902 - Will use zip compression
11:27:42,037 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1099455902 - Will use the pattern ./logs/sail-message-provider.log.%d{yyyy-MM-dd}.%i for the active file
11:27:42,037 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@45941acf - The date pattern is 'yyyy-MM-dd' from file name pattern './logs/sail-message-provider.log.%d{yyyy-MM-dd}.%i.zip'.
11:27:42,037 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@45941acf - Roll-over at midnight.
11:27:42,038 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@45941acf - Setting initial period to 2023-12-21T03:27:42.038Z
11:27:42,038 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:27:42,038 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[file] - Active log file name: ./logs/sail-message-provider.log
11:27:42,038 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[file] - File property is set to [./logs/sail-message-provider.log]
11:27:42,038 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to INFO
11:27:42,038 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@a22ecf8 - Propagating INFO level on Logger[ROOT] onto the JUL framework
11:27:42,038 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [console] to Logger[ROOT]
11:27:42,038 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [file] to Logger[ROOT]
11:27:42,038 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@6953086a - End of configuration.

11:27:42.041 logback [main] INFO  o.a.d.s.b.c.e.WelcomeLogoApplicationListener -  [DUBBO] 

 :: Dubbo (v3.3.0-beta.1) : https://github.com/apache/dubbo
 :: Discuss group : dev@dubbo.apache.org
, dubbo version: 3.3.0-beta.1, current host: 192.168.0.219

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.0.9)

11:27:42.053 logback [main] INFO  c.h.sail.MessageProviderApplication - Starting AOT-processed MessageProviderApplication using Java 17.0.5 with PID 13057 (/root/sail-native/sail-message/sail-message-provider/target/sail-message-provider started by root in /root/sail-native/sail-message/sail-message-provider/target)
11:27:42.053 logback [main] INFO  c.h.sail.MessageProviderApplication - The following 1 profile is active: "prod"
11:27:42.094 logback [main] WARN  o.a.d.c.s.r.ReferenceBeanManager -  [DUBBO] Early initialize reference bean before DubboConfigBeanInitializer, the BeanPostProcessor has not been loaded at this time, which may cause abnormalities in some components (such as seata): dubboAlarmLogService = ReferenceBean:com.hcll.sail.foundation.api.service.DubboAlarmLogService(), dubbo version: 3.3.0-beta.1, current host: 192.168.0.219, error code: 5-39. This may be caused by , go to https://dubbo.apache.org/faq/5/39 to find instructions. 
11:27:42.094 logback [main] WARN  o.a.d.c.s.r.ReferenceBeanManager -  [DUBBO] Early initialize reference bean before DubboConfigBeanInitializer, the BeanPostProcessor has not been loaded at this time, which may cause abnormalities in some components (such as seata): dubboSubmitExportService = ReferenceBean:com.hcll.sail.foundation.api.service.DubboSubmitExportService(), dubbo version: 3.3.0-beta.1, current host: 192.168.0.219, error code: 5-39. This may be caused by , go to https://dubbo.apache.org/faq/5/39 to find instructions. 
11:27:42.094 logback [main] WARN  o.a.d.c.s.r.ReferenceBeanManager -  [DUBBO] Early initialize reference bean before DubboConfigBeanInitializer, the BeanPostProcessor has not been loaded at this time, which may cause abnormalities in some components (such as seata): dubboClientService = ReferenceBean:com.hcll.sail.foundation.api.service.DubboClientService(), dubbo version: 3.3.0-beta.1, current host: 192.168.0.219, error code: 5-39. This may be caused by , go to https://dubbo.apache.org/faq/5/39 to find instructions. 
11:27:42.094 logback [main] WARN  o.a.d.c.s.r.ReferenceBeanManager -  [DUBBO] Early initialize reference bean before DubboConfigBeanInitializer, the BeanPostProcessor has not been loaded at this time, which may cause abnormalities in some components (such as seata): dubboLinkStatisService = ReferenceBean:com.hcll.sail.foundation.api.service.DubboLinkStatisService(), dubbo version: 3.3.0-beta.1, current host: 192.168.0.219, error code: 5-39. This may be caused by , go to https://dubbo.apache.org/faq/5/39 to find instructions. 
11:27:42.094 logback [main] WARN  o.a.d.c.s.r.ReferenceBeanManager -  [DUBBO] Early initialize reference bean before DubboConfigBeanInitializer, the BeanPostProcessor has not been loaded at this time, which may cause abnormalities in some components (such as seata): dubboSettingService = ReferenceBean:com.hcll.sail.foundation.api.service.DubboSettingService(), dubbo version: 3.3.0-beta.1, current host: 192.168.0.219, error code: 5-39. This may be caused by , go to https://dubbo.apache.org/faq/5/39 to find instructions. 
11:27:42.094 logback [main] WARN  o.a.d.c.s.r.ReferenceBeanManager -  [DUBBO] Early initialize reference bean before DubboConfigBeanInitializer, the BeanPostProcessor has not been loaded at this time, which may cause abnormalities in some components (such as seata): dubboHttpMessageStatisService = ReferenceBean:com.hcll.sail.foundation.api.service.DubboHttpMessageStatisService(), dubbo version: 3.3.0-beta.1, current host: 192.168.0.219, error code: 5-39. This may be caused by , go to https://dubbo.apache.org/faq/5/39 to find instructions. 
11:27:42.094 logback [main] WARN  o.a.d.c.s.r.ReferenceBeanManager -  [DUBBO] Early initialize reference bean before DubboConfigBeanInitializer, the BeanPostProcessor has not been loaded at this time, which may cause abnormalities in some components (such as seata): dubboMessageStatisSummaryService = ReferenceBean:com.hcll.sail.foundation.api.service.DubboMessageStatisSummaryService(), dubbo version: 3.3.0-beta.1, current host: 192.168.0.219, error code: 5-39. This may be caused by , go to https://dubbo.apache.org/faq/5/39 to find instructions. 
11:27:42.094 logback [main] WARN  o.a.d.c.s.r.ReferenceBeanManager -  [DUBBO] Early initialize reference bean before DubboConfigBeanInitializer, the BeanPostProcessor has not been loaded at this time, which may cause abnormalities in some components (such as seata): dubboMessageStatisService = ReferenceBean:com.hcll.sail.foundation.api.service.DubboMessageSourceStatisService(), dubbo version: 3.3.0-beta.1, current host: 192.168.0.219, error code: 5-39. This may be caused by , go to https://dubbo.apache.org/faq/5/39 to find instructions. 
11:27:42.094 logback [main] WARN  o.a.d.c.s.r.ReferenceBeanManager -  [DUBBO] Early initialize reference bean before DubboConfigBeanInitializer, the BeanPostProcessor has not been loaded at this time, which may cause abnormalities in some components (such as seata): dubboMessageDurationStatisService = ReferenceBean:com.hcll.sail.foundation.api.service.DubboMessageDurationStatisService(), dubbo version: 3.3.0-beta.1, current host: 192.168.0.219, error code: 5-39. This may be caused by , go to https://dubbo.apache.org/faq/5/39 to find instructions. 
11:27:42.095 logback [main] WARN  o.a.d.c.s.r.ReferenceBeanManager -  [DUBBO] Early initialize reference bean before DubboConfigBeanInitializer, the BeanPostProcessor has not been loaded at this time, which may cause abnormalities in some components (such as seata): dubboMessageCountryStatisService = ReferenceBean:com.hcll.sail.foundation.api.service.DubboMessageCountryStatisService(), dubbo version: 3.3.0-beta.1, current host: 192.168.0.219, error code: 5-39. This may be caused by , go to https://dubbo.apache.org/faq/5/39 to find instructions. 
11:27:42.104 logback [main] WARN  o.a.d.c.s.r.ReferenceBeanManager -  [DUBBO] Early initialize reference bean before DubboConfigBeanInitializer, the BeanPostProcessor has not been loaded at this time, which may cause abnormalities in some components (such as seata): dubboMessageProvinceStatisService = ReferenceBean:com.hcll.sail.foundation.api.service.DubboMessageProvinceStatisService(), dubbo version: 3.3.0-beta.1, current host: 192.168.0.219, error code: 5-39. This may be caused by , go to https://dubbo.apache.org/faq/5/39 to find instructions. 
11:27:42.104 logback [main] WARN  o.a.d.c.s.r.ReferenceBeanManager -  [DUBBO] Early initialize reference bean before DubboConfigBeanInitializer, the BeanPostProcessor has not been loaded at this time, which may cause abnormalities in some components (such as seata): dubboMessageSinkStatisService = ReferenceBean:com.hcll.sail.foundation.api.service.DubboMessageSinkStatisService(), dubbo version: 3.3.0-beta.1, current host: 192.168.0.219, error code: 5-39. This may be caused by , go to https://dubbo.apache.org/faq/5/39 to find instructions. 
11:27:42.104 logback [main] WARN  o.a.d.c.s.r.ReferenceBeanManager -  [DUBBO] Early initialize reference bean before DubboConfigBeanInitializer, the BeanPostProcessor has not been loaded at this time, which may cause abnormalities in some components (such as seata): dubboMessageTagStatisService = ReferenceBean:com.hcll.sail.foundation.api.service.DubboMessageTagStatisService(), dubbo version: 3.3.0-beta.1, current host: 192.168.0.219, error code: 5-39. This may be caused by , go to https://dubbo.apache.org/faq/5/39 to find instructions. 
11:27:42.105 logback [main] WARN  o.a.d.c.s.r.ReferenceBeanManager -  [DUBBO] Early initialize reference bean before DubboConfigBeanInitializer, the BeanPostProcessor has not been loaded at this time, which may cause abnormalities in some components (such as seata): dubboMessageOperatorsStatisService = ReferenceBean:com.hcll.sail.foundation.api.service.DubboMessageOperatorsStatisService(), dubbo version: 3.3.0-beta.1, current host: 192.168.0.219, error code: 5-39. This may be caused by , go to https://dubbo.apache.org/faq/5/39 to find instructions. 
11:27:42.105 logback [main] WARN  o.a.d.c.s.r.ReferenceBeanManager -  [DUBBO] Early initialize reference bean before DubboConfigBeanInitializer, the BeanPostProcessor has not been loaded at this time, which may cause abnormalities in some components (such as seata): dubboMessageStatStatisService = ReferenceBean:com.hcll.sail.foundation.api.service.DubboMessageStatStatisService(), dubbo version: 3.3.0-beta.1, current host: 192.168.0.219, error code: 5-39. This may be caused by , go to https://dubbo.apache.org/faq/5/39 to find instructions. 
11:27:42.105 logback [main] WARN  o.a.d.c.s.r.ReferenceBeanManager -  [DUBBO] Early initialize reference bean before DubboConfigBeanInitializer, the BeanPostProcessor has not been loaded at this time, which may cause abnormalities in some components (such as seata): dubboServiceProviderService = ReferenceBean:com.hcll.sail.foundation.api.service.DubboServiceProviderService(), dubbo version: 3.3.0-beta.1, current host: 192.168.0.219, error code: 5-39. This may be caused by , go to https://dubbo.apache.org/faq/5/39 to find instructions. 
11:27:42.105 logback [main] WARN  o.a.d.c.s.r.ReferenceBeanManager -  [DUBBO] Early initialize reference bean before DubboConfigBeanInitializer, the BeanPostProcessor has not been loaded at this time, which may cause abnormalities in some components (such as seata): dubboSubServiceProviderService = ReferenceBean:com.hcll.sail.foundation.api.service.DubboSubServiceProviderService(), dubbo version: 3.3.0-beta.1, current host: 192.168.0.219, error code: 5-39. This may be caused by , go to https://dubbo.apache.org/faq/5/39 to find instructions. 
11:27:42.105 logback [main] WARN  o.a.d.c.s.r.ReferenceBeanManager -  [DUBBO] Early initialize reference bean before DubboConfigBeanInitializer, the BeanPostProcessor has not been loaded at this time, which may cause abnormalities in some components (such as seata): dubboSinkService = ReferenceBean:com.hcll.sail.foundation.api.service.DubboSinkService(), dubbo version: 3.3.0-beta.1, current host: 192.168.0.219, error code: 5-39. This may be caused by , go to https://dubbo.apache.org/faq/5/39 to find instructions. 
11:27:42.107 logback [main] WARN  o.s.b.w.s.c.ServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serviceAnnotationBeanProcessor': Instantiation of supplied bean failed
11:27:42.110 logback [main] ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serviceAnnotationBeanProcessor': Instantiation of supplied bean failed
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1220)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1158)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:138)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:771)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:589)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:150)
	at com.hcll.sail.MessageProviderApplication.main(MessageProviderApplication.java:95)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: org.apache.dubbo.config.spring.beans.factory.annotation.ServiceAnnotationPostProcessor.<init>(java.util.Collection)
	at org.apache.dubbo.spring.boot.autoconfigure.DubboAutoConfiguration.serviceAnnotationBeanProcessor(DubboAutoConfiguration.java:72)
	at org.apache.dubbo.spring.boot.autoconfigure.DubboAutoConfiguration__BeanDefinitions.lambda$getServiceAnnotationBeanProcessorInstanceSupplier$0(DubboAutoConfiguration__BeanDefinitions.java:30)
	at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:68)
	at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:54)
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.lambda$get$2(BeanInstanceSupplier.java:202)
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:58)
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:46)
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.invokeBeanSupplier(BeanInstanceSupplier.java:214)
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.obtainInstanceFromSupplier(DefaultListableBeanFactory.java:947)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1214)
	... 16 common frames omitted
Caused by: java.lang.NoSuchMethodException: org.apache.dubbo.config.spring.beans.factory.annotation.ServiceAnnotationPostProcessor.<init>(java.util.Collection)
	at java.base@17.0.5/java.lang.Class.getConstructor0(DynamicHub.java:3585)
	at java.base@17.0.5/java.lang.Class.getDeclaredConstructor(DynamicHub.java:2754)
	at org.apache.dubbo.spring.boot.autoconfigure.DubboAutoConfiguration.serviceAnnotationBeanProcessor(DubboAutoConfiguration.java:70)
	... 26 common frames omitted

```
I see this method named "org.apache.dubbo.config.spring.beans.factory.annotation.ServiceAnnotationPostProcessor.<init>(java.util.Collection)"
![image](https://github.com/apache/dubbo/assets/27885492/f117c7c6-a766-4b8e-ab44-c10ca33129cb)

**Comment by imgoby** [comment]
add reflect-config.json to src/main/resources/META-INF/native-image to  resolve:

```
[
  {
    "name": "org.apache.dubbo.config.spring.beans.factory.annotation.ServiceAnnotationPostProcessor",
    "allDeclaredFields": true,
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true,
    "methods": [
      {
        "name": "<init>",
        "parameterTypes": [ "java.util.Collection" ]
      }
    ]
  },
  {
    "name": "org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertySource",
    "allDeclaredFields": true,
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true,
    "methods": [
      {
        "name": "<init>",
        "parameterTypes": [ ]
      }
    ]
  }
]
```

**Comment by CrazyHZM** [comment]
@imgoby 
I noticed that you have started to validate the production application. If you need to, you can contact the community through the following ways or through my Github page email to contact me. We can talk about the use of scenarios.
 https://cn.dubbo.apache.org/zh-cn/contact/
