### ISSUE TITLE
deadlock when starting by springboot web

### ISSUE THREAD

**Issue by tobizhang** [apache/dubbo#13560]
### Environment

* Dubbo version: 3.2.10
* Operating System version: mac
* Java version: jdk8

### Steps to reproduce this issue

1. 使用dubbo-spring-boot-starter和nacos通过springboot web应用拉起dubbo提供者服务时，会deadlock，日志如下：
"main" Id=1 BLOCKED on org.apache.dubbo.config.spring.ServiceBean@4840dee0 owned by "Dubbo-ots-service-export-thread-1" Id=300
    at org.apache.dubbo.config.ServiceConfig.register(ServiceConfig.java:353)
    -  blocked on org.apache.dubbo.config.spring.ServiceBean@4840dee0
    at org.apache.dubbo.config.deploy.DefaultModuleDeployer.registerServiceInternal(DefaultModuleDeployer.java:491)
    at org.apache.dubbo.config.deploy.DefaultModuleDeployer.registerServices(DefaultModuleDeployer.java:431)
    at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:191)
    -  locked org.apache.dubbo.config.deploy.DefaultModuleDeployer@19d1ac5
    at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:156)
    at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:153)
    -  locked java.util.concurrent.ConcurrentHashMap@381ae39 <---- but blocks 6 other threads!
    at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:138)
    at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:47)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:355)
    at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:882)
    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:163)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
    -  locked java.lang.Object@3775b7f2
    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
    at com.xxx.cpods.xxx.rpc.api.RpcApplication.main(RpcApplication.java:83)

通过去除DubboDeployApplicationListener.onContextRefreshedEvent中的synchronized代码可以解决这个死锁问题。但不知是否有其他影响

**Comment by AlbumenJ** [comment]
Can you pls provide the whole jstack file?

**Comment by tobizhang** [comment]
[31520.txt](https://github.com/apache/dubbo/files/13770905/31520.txt)
jstack file 已上传

**Comment by AlbumenJ** [comment]
Are you using delay publish?

**Comment by AlbumenJ** [comment]
BTW, which version of version do you use?

**Comment by tobizhang** [comment]
是使用了delay publish

**Comment by AlbumenJ** [comment]
> 是使用了delay publish

Which spring version do you use?

**Comment by tobizhang** [comment]
springboot 2.1.1 
spring 5.1.3

**Comment by AlbumenJ** [comment]
> springboot 2.1.1 spring 5.1.3

I found this might depend on what spring version do you use for. When I try to reproduce it with the latest spring version, everything is ok.
The following several ways you can try:
1. Disable delay publish
2. Upgrade spring version
3. Wait for #13583 being merged

**Comment by tobizhang** [comment]
目前是通过去除DubboDeployApplicationListener.onContextRefreshedEvent中的synchronized代码投产的，后续等新版本解决这个问题，感谢！
