### ISSUE TITLE
native image run failed on consumer and should add config to proxy-config.json application

### ISSUE THREAD

**Issue by imgoby** [apache/dubbo#13613]
version: <dubbo.version>3.3.0-beta.1</dubbo.version>

```
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Proxy class defined by interfaces [interface com.xxx.api.service.DubboSettingService, interface org.apache.dubbo.rpc.service.EchoService, interface org.apache.dubbo.rpc.service.Destroyable] not found. Generating proxy classes at runtime is not supported. Proxy classes need to be defined at image build time by specifying the list of interfaces that they implement. To define proxy classes use -H:DynamicProxyConfigurationFiles=<comma-separated-config-files> and -H:DynamicProxyConfigurationResources=<comma-separated-config-resources> options.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.proxy.DynamicProxySupport.getProxyClass(DynamicProxySupport.java:171)
	at java.base@17.0.5/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:47)
	at java.base@17.0.5/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1037)
	at org.apache.dubbo.config.spring.ReferenceBean.generateFromJdk(ReferenceBean.java:396)
	at org.apache.dubbo.config.spring.ReferenceBean.createLazyProxy(ReferenceBean.java:362)
	at org.apache.dubbo.config.spring.ReferenceBean.getObject(ReferenceBean.java:206)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:148)
	... 17 common frames omitted

```

if I add this setting to file proxy-config.json ,It can be resolved.

```
  {
    "interfaces": [
      "com.xxx.api.service.DubboSettingService",
      "org.apache.dubbo.rpc.service.EchoService",
      "org.apache.dubbo.rpc.service.Destroyable"
    ]
  }
```
com.xxx.api.service.DubboSettingService is my business api. also,there are another apis.

```
  {
    "interfaces": [
      "com.xxx.api.service.DubboApi1",
      "org.apache.dubbo.rpc.service.EchoService",
      "org.apache.dubbo.rpc.service.Destroyable"
    ]
  },
  {
    "interfaces": [
      "com.xxx.api.service.DubboApi2",
      "org.apache.dubbo.rpc.service.EchoService",
      "org.apache.dubbo.rpc.service.Destroyable"
    ]
  },
  {
    "interfaces": [
      "com.xxx.api.service.DubboApi3",
      "org.apache.dubbo.rpc.service.EchoService",
      "org.apache.dubbo.rpc.service.Destroyable"
    ]
  }
```
 too many apis should be added.

how to resolve?

**Comment by CrazyHZM** [comment]
If you use annotation or XML config， it will generate it automatically. Please provide a demo to reproduce it.
@imgoby

**Comment by imgoby** [comment]
There is currently no demo available.

other information:

`13:53:45.335 logback [main] ERROR o.a.d.config.spring.ReferenceBean -  [DUBBO] Failed to generate proxy by Javassist failed. Fallback to use JDK proxy is also failed. Interfaces: [interface com.hcll.sail.foundation.api.service.DubboBalanceThresholdService, interface org.apache.dubbo.rpc.service.EchoService, interface org.apache.dubbo.rpc.service.Destroyable] JDK Error., dubbo version: 3.3.0-beta.1, current host: 192.168.0.219, error code: 3-8. This may be caused by , go to https://dubbo.apache.org/faq/3/8 to find instructions. 
`

**Comment by imgoby** [comment]
Maybe because I merged code to org.apache.dubbo.config.spring.ReferenceBean,but it is not latest.

**Comment by imgoby** [comment]
My Demo project is OK.  https://github.com/imgoby/spring-cloud-alibaba-dubbo-native/tree/main/spring-cloud-alibaba-consul-dubbo-consumer
But my production project has this issue.

**Comment by imgoby** [comment]
I see

**Comment by imgoby** [comment]
I know something. 
Lack of dependencies and writing dependency like this can lead to errors:
What is the standard dependency  writing method? Ha ha~~

```
 <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-native</artifactId>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>org.apache.dubbo</groupId>-->
<!--            <artifactId>dubbo-remoting-netty4</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.apache.dubbo</groupId>-->
<!--            <artifactId>dubbo-serialization-fastjson2</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.apache.dubbo</groupId>-->
<!--            <artifactId>dubbo-rpc-triple</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.apache.dubbo</groupId>-->
<!--            <artifactId>dubbo-registry-zookeeper</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.apache.dubbo</groupId>-->
<!--            <artifactId>dubbo-config-spring6</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.apache.dubbo</groupId>-->
<!--            <artifactId>dubbo-rpc-dubbo</artifactId>-->
<!--        </dependency>-->
```
