### ISSUE TITLE
Low version of consumer reports error when dubbo3.3provider uses virtual threading

### ISSUE THREAD

**Issue by funky-eyes** [apache/dubbo#13635]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.3 provider  3.2consumer
* Operating System version: xxx
* Java version: jdk21

### Steps to reproduce this issue

1.  provider of dubbo 3.3 uses'dubbo.protocol.threadpool = virtual 'and start
2. dubbo3.2 consumer start
3. The exception log will be output directly

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
2024-01-10 09:35:40.709 ERROR 59497 --- [           main] o.a.d.r.integration.RegistryDirectory    :  [DUBBO] urls to invokers error, dubbo version: 3.2.10, current host: 10.57.240.121, error code: 3-1. This may be caused by inconsistency between the client protocol and the protocol of the server, go to https://dubbo.apache.org/faq/3/1 to find instructions. 

java.lang.IllegalStateException: urls to invokers error. invokerUrls.size :1, invoker.size :0. urls :[dubbo://10.57.17.39:20880/cn.tongdun.app.service.TestService?application=java-demo-002169&background=false&category=providers,configurators,routers&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&executor-management-mode=isolation&file-cache=true&generic=false&interface=cn.tongdun.app.service.TestService&methods=test&pid=59497&prefer.serialization=fastjson2,hessian2&register-mode=all&release=3.2.10&revision=1.0.1&service-name-mapping=true&side=provider&sticky=false&threadpool=virtual&unloadClusterRelated=false&version=1.0.0]
	at org.apache.dubbo.registry.integration.RegistryDirectory.refreshInvoker(RegistryDirectory.java:341)
	at org.apache.dubbo.registry.integration.RegistryDirectory.refreshOverrideAndInvoker(RegistryDirectory.java:254)
	at org.apache.dubbo.registry.integration.RegistryDirectory.notify(RegistryDirectory.java:230)
	at org.apache.dubbo.registry.support.AbstractRegistry.notify(AbstractRegistry.java:574)
	at org.apache.dubbo.registry.support.FailbackRegistry.doNotify(FailbackRegistry.java:421)
	at org.apache.dubbo.registry.support.FailbackRegistry.notify(FailbackRegistry.java:408)
	at org.apache.dubbo.registry.zookeeper.ZookeeperRegistry.doSubscribe(ZookeeperRegistry.java:268)
	at org.apache.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:324)
	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:87)
	at org.apache.dubbo.registry.integration.DynamicDirectory.subscribe(DynamicDirectory.java:186)
	at org.apache.dubbo.registry.integration.RegistryDirectory.lambda$subscribe$0(RegistryDirectory.java:147)
	at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:76)
	at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:59)
	at org.apache.dubbo.registry.integration.RegistryDirectory.subscribe(RegistryDirectory.java:146)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doCreateInvoker(RegistryProtocol.java:695)
	at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getInvoker(InterfaceCompatibleRegistryProtocol.java:58)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshInterfaceInvoker(MigrationInvoker.java:482)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToApplicationFirstInvoker(MigrationInvoker.java:255)
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.refreshInvoker(MigrationRuleHandler.java:78)
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:62)
	at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:285)
	at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:658)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:622)
	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:603)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:85)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:84)
	at org.apache.dubbo.rpc.protocol.ProtocolSecurityWrapper.refer(ProtocolSecurityWrapper.java:112)
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:72)
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:55)
	at org.apache.dubbo.rpc.protocol.InvokerCountWrapper.refer(InvokerCountWrapper.java:48)
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ReferenceConfig.createInvoker(ReferenceConfig.java:656)
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:486)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:369)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:238)
	at org.apache.dubbo.config.utils.SimpleReferenceCache.get(SimpleReferenceCache.java:140)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:542)
	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4783)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:514)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:183)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:156)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:157)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:143)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:52)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:429)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:386)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:949)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:594)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at cn.tongdun.app.AppMain.main(AppMain.java:133)
```

**Comment by AlbumenJ** [comment]
We need to add `threadpool` into `org.apache.dubbo.registry.support.DefaultProviderFirstParams`

**Comment by funky-eyes** [comment]
> We need to add `threadpool` into `org.apache.dubbo.registry.support.DefaultProviderFirstParams`

Please leave it to me to fix it.
