### ISSUE TITLE
NPE if return com.qiniu.http.Response

### ISSUE THREAD

**Issue by lxf-lxf** [apache/dubbo#13689]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.7
* Operating System version: windows11
* Java version: 17

### Steps to reproduce this issue

![image](https://github.com/apache/dubbo/assets/61101384/54bd2877-75cf-4eae-9f6a-e015e324ee21)
![image](https://github.com/apache/dubbo/assets/61101384/047b3c59-ef47-408b-8ac0-33e6c1ee59d6)
![image](https://github.com/apache/dubbo/assets/61101384/a261b518-3e3d-4640-ac77-a33c03a2337d)
![image](https://github.com/apache/dubbo/assets/61101384/a585a5d0-f407-4965-81f4-5ab8c24b47c6)

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
  2024-01-25 15:18:28  [DUBBO] publish service definition metadata error., dubbo version: 3.2.7, current host: 172.17.2.10, error code: 1-11. This may be caused by , go to https://dubbo.apache.org/faq/1/11 to find instructions. 
  java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "type" is null
	at org.apache.dubbo.metadata.definition.model.TypeDefinition.isGenericType(TypeDefinition.java:111)
	at org.apache.dubbo.metadata.definition.model.TypeDefinition.formatType(TypeDefinition.java:92)
	at org.apache.dubbo.metadata.definition.model.TypeDefinition.setType(TypeDefinition.java:152)
	at org.apache.dubbo.metadata.definition.model.TypeDefinition.<init>(TypeDefinition.java:66)
	at org.apache.dubbo.metadata.definition.builder.DefaultTypeBuilder.build(DefaultTypeBuilder.java:42)
	at org.apache.dubbo.metadata.definition.TypeDefinitionBuilder.build(TypeDefinitionBuilder.java:57)
	at org.apache.dubbo.metadata.definition.builder.DefaultTypeBuilder.build(DefaultTypeBuilder.java:56)
	at org.apache.dubbo.metadata.definition.TypeDefinitionBuilder.build(TypeDefinitionBuilder.java:57)
	at org.apache.dubbo.metadata.definition.builder.DefaultTypeBuilder.build(DefaultTypeBuilder.java:56)
	at org.apache.dubbo.metadata.definition.TypeDefinitionBuilder.build(TypeDefinitionBuilder.java:57)
	at org.apache.dubbo.metadata.definition.builder.DefaultTypeBuilder.build(DefaultTypeBuilder.java:56)
	at org.apache.dubbo.metadata.definition.TypeDefinitionBuilder.build(TypeDefinitionBuilder.java:57)
	at org.apache.dubbo.metadata.definition.builder.DefaultTypeBuilder.build(DefaultTypeBuilder.java:56)
	at org.apache.dubbo.metadata.definition.TypeDefinitionBuilder.build(TypeDefinitionBuilder.java:57)
	at org.apache.dubbo.metadata.definition.builder.DefaultTypeBuilder.build(DefaultTypeBuilder.java:56)
	at org.apache.dubbo.metadata.definition.TypeDefinitionBuilder.build(TypeDefinitionBuilder.java:57)
	at org.apache.dubbo.metadata.definition.builder.DefaultTypeBuilder.build(DefaultTypeBuilder.java:56)
	at org.apache.dubbo.metadata.definition.TypeDefinitionBuilder.build(TypeDefinitionBuilder.java:57)
	at org.apache.dubbo.metadata.definition.builder.DefaultTypeBuilder.build(DefaultTypeBuilder.java:56)
	at org.apache.dubbo.metadata.definition.TypeDefinitionBuilder.build(TypeDefinitionBuilder.java:57)
	at org.apache.dubbo.metadata.definition.TypeDefinitionBuilder.build(TypeDefinitionBuilder.java:79)
	at org.apache.dubbo.metadata.definition.ServiceDefinitionBuilder.build(ServiceDefinitionBuilder.java:90)
	at org.apache.dubbo.metadata.definition.ServiceDefinitionBuilder.buildFullDefinition(ServiceDefinitionBuilder.java:58)
	at org.apache.dubbo.rpc.model.ReflectionServiceDescriptor.lambda$getFullServiceDefinition$0(ReflectionServiceDescriptor.java:62)
	at java.base/java.util.concurrent.ConcurrentSkipListMap.computeIfAbsent(ConcurrentSkipListMap.java:1462)
	at org.apache.dubbo.rpc.model.ReflectionServiceDescriptor.getFullServiceDefinition(ReflectionServiceDescriptor.java:61)
	at org.apache.dubbo.registry.client.metadata.MetadataUtils.publishServiceDefinition(MetadataUtils.java:70)
	at org.apache.dubbo.config.ServiceConfig.exportUrl(ServiceConfig.java:773)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:554)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:536)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:498)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:327)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServiceInternal(DefaultModuleDeployer.java:438)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServices(DefaultModuleDeployer.java:393)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:167)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:148)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:155)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:141)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:52)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:174)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:445)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:969)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:619)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:738)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:440)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
```

**Comment by iwangjie** [comment]
已经解决，原因：
org.apache.dubbo.rpc.protocol.tri.stream.TripleServerStream#complete 抛出异常
Method threw 'java.lang.NoSuchMethodError' exception.
com.google.protobuf.GeneratedMessageV3.isStringEmpty(Ljava/lang/Object;)Z

因为 mysql8 驱动引入了 protobuf 依赖，和 Dubbo 这块代码冲突，没有使用 protobuf 需求，去掉即可。

**Comment by lxf-lxf** [comment]
> 已经解决，原因： org.apache.dubbo.rpc.protocol.tri.stream.TripleServerStream#complete 抛出异常 Method threw 'java.lang.NoSuchMethodError' exception. com.google.protobuf.GeneratedMessageV3.isStringEmpty(Ljava/lang/Object;)Z
> 
> 因为 mysql8 驱动引入了 protobuf 依赖，和 Dubbo 这块代码冲突，没有使用 protobuf 需求，去掉即可。

我试了下好像没有，和报错的原因应该没关系。

**Comment by AlbumenJ** [comment]
Can you please submit a reproducble demo?

**Comment by iwangjie** [comment]
> > 已经解决，原因： org.apache.dubbo.rpc.protocol.tri.stream.TripleServerStream#complete 抛出异常 Method threw 'java.lang.NoSuchMethodError' exception. com.google.protobuf.GeneratedMessageV3.isStringEmpty(Ljava/lang/Object;)Z
> > 因为 mysql8 驱动引入了 protobuf 依赖，和 Dubbo 这块代码冲突，没有使用 protobuf 需求，去掉即可。
> 
> 我试了下好像没有，和报错的原因应该没关系。

实在抱歉，回复错issue了，请忽略

**Comment by lxf-lxf** [comment]
> DefaultTypeBuilder

https://github.com/lxf-lxf/dubboIssues-13689.git

**Comment by AlbumenJ** [comment]
Will be fixed in https://github.com/apache/dubbo/pull/13732
