### ISSUE TITLE
java.lang.IllegalArgumentException: Metrics port cannot be null

### ISSUE THREAD

**Issue by bitgorust** [apache/dubbo#13684]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.9
* Operating System version: CentOS 8
* Java version: Oracle JDK 8u221

### Steps to reproduce this issue

1. set system property `dubbo.metrics.enabled=false`
2. define dubbo references by exporting `ReferenceConfig.get()` as `Bean`s 
3. start

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

Project starts successfully. References created without metrics configuration.

### Actual Behavior

References created with metrics enabled, but port is null.

Exception trace:

```
2024-01-22 17:55:47.207 |-ERROR [main] org.apache.dubbo.config.deploy.DefaultApplicationDeployer []-[traceId:] -|  [DUBBO] Dubbo Application[1.1](qijian-rec-service-41-prod) an exception occurred when handle starting event, dubbo version: 3.2.9, current host: 10.5.139.33, error code: 5-14. This may be caused by , go to https://dubbo.apache.org/faq/5/14 to find instructions. 
java.lang.IllegalArgumentException: Metrics port cannot be null
	at org.apache.dubbo.common.utils.Assert.notEmptyString(Assert.java:33) ~[dubbo-3.2.9.jar:3.2.9]
	at org.apache.dubbo.config.AbstractInterfaceConfig.appendMetricsCompatible(AbstractInterfaceConfig.java:280) ~[dubbo-3.2.9.jar:3.2.9]
	at org.apache.dubbo.config.ServiceConfig.buildAttributes(ServiceConfig.java:662) ~[dubbo-3.2.9.jar:3.2.9]
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:587) ~[dubbo-3.2.9.jar:3.2.9]
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:579) ~[dubbo-3.2.9.jar:3.2.9]
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:540) ~[dubbo-3.2.9.jar:3.2.9]
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:340) ~[dubbo-3.2.9.jar:3.2.9]
	at org.apache.dubbo.config.ServiceConfigBase.export(ServiceConfigBase.java:422) ~[dubbo-3.2.9.jar:3.2.9]
	at org.apache.dubbo.config.metadata.ConfigurableMetadataServiceExporter.export(ConfigurableMetadataServiceExporter.java:76) ~[dubbo-3.2.9.jar:3.2.9]
	at org.apache.dubbo.config.metadata.ExporterDeployListener.onModuleStarted(ExporterDeployListener.java:85) ~[dubbo-3.2.9.jar:3.2.9]
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.exportMetadataService(DefaultApplicationDeployer.java:1263) ~[dubbo-3.2.9.jar:3.2.9]
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.prepareApplicationInstance(DefaultApplicationDeployer.java:764) ~[dubbo-3.2.9.jar:3.2.9]
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.checkState(DefaultApplicationDeployer.java:1149) ~[dubbo-3.2.9.jar:3.2.9]
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.notifyModuleChanged(DefaultApplicationDeployer.java:1137) ~[dubbo-3.2.9.jar:3.2.9]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.onModuleStarted(DefaultModuleDeployer.java:363) ~[dubbo-3.2.9.jar:3.2.9]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:188) ~[dubbo-3.2.9.jar:3.2.9]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:156) ~[dubbo-3.2.9.jar:3.2.9]
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:235) ~[dubbo-3.2.9.jar:3.2.9]
	at org.apache.dubbo.config.ReferenceConfigBase.get(ReferenceConfigBase.java:395) ~[dubbo-3.2.9.jar:3.2.9]
```

### Analysis

In https://github.com/apache/dubbo/blob/2cf54f7947596abbf92f907853a2df7cbfc8b7fb/dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java#L274-L277 (though it is marked as deprecated but is still used now), `MetricsConfig` is got by `getConfigManager().getMetrics().orElse(null)`. Dive in we can know that the instance actually comes from https://github.com/apache/dubbo/blob/2cf54f7947596abbf92f907853a2df7cbfc8b7fb/dubbo-common/src/main/java/org/apache/dubbo/config/context/AbstractConfigManager.java#L294-L296. It is added here https://github.com/apache/dubbo/blob/2cf54f7947596abbf92f907853a2df7cbfc8b7fb/dubbo-common/src/main/java/org/apache/dubbo/config/context/AbstractConfigManager.java#L554-L566 because the statement `ConfigurationUtils.hasSubProperties(configurationMaps, AbstractConfig.getTypePrefix(cls))` is `true` here, which I think it should do more than just looking for properties with `dubbo.metrics` prefix.

### Workaround

Now we work it around by adding `org.apache.dubbo:dubbo-spring-boot-observability-starter` to avoid null port exceptions.

### Solution

One reasonable solution I think is to add one more condition after https://github.com/apache/dubbo/blob/2cf54f7947596abbf92f907853a2df7cbfc8b7fb/dubbo-common/src/main/java/org/apache/dubbo/config/context/AbstractConfigManager.java#L554 to check if contains `${prefix}.enabled=false` configuration. Or maybe some solutions are on the way as `appendMetricsCompatible` is deprecated.

**Comment by yuluo-yx** [comment]
If need to fix it, please assign to me.

**Comment by bitgorust** [comment]
@songxiaosheng @yuluo-yx 

Since I've read [Configuration Item Reference Manual](https://dubbo.apache.org/zh-cn/overview/mannual/java-sdk/reference-manual/config/properties/) (BTW, [English version](https://dubbo.apache.org/en/docs3-v2/java-sdk/reference-manual/config/properties/) seems not up-to-date neither well typeset) and code relative to `MetricsConfig` / `AggregationConfig` / `PrometheusConfig`, I think L280 and L282 are no longer necessary here. https://github.com/apache/dubbo/blob/2cf54f7947596abbf92f907853a2df7cbfc8b7fb/dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java#L279-L283

1. [MetricsFilter](https://github.com/apache/dubbo/blob/3.2/dubbo-monitor/dubbo-monitor-default/src/main/java/org/apache/dubbo/monitor/dubbo/MetricsFilter.java) is marked `deprecated`. And even it is useful now, `metrics.protocol` and `metrics.port` have their own default values respectively.
2. `port` in [MetricsConfig](https://github.com/apache/dubbo/blob/3.2/dubbo-common/src/main/java/org/apache/dubbo/config/MetricsConfig.java) is also marked `deprecated`. Nor used in nested [PrometheusConfig](https://github.com/apache/dubbo/blob/3.2/dubbo-common/src/main/java/org/apache/dubbo/config/nested/PrometheusConfig.java) and [AggregationConfig](https://github.com/apache/dubbo/blob/3.2/dubbo-common/src/main/java/org/apache/dubbo/config/nested/AggregationConfig.java)
3. `enabled` flag only appears in `MetricsConfig` and `TracingConfig` according to [Configuration Item Reference Manual](https://dubbo.apache.org/zh-cn/overview/mannual/java-sdk/reference-manual/config/properties/). In `MetricsConfig`, `enabled` is actually for `AggregationConfig`. In `TracingConfig`, `enabled` has its default value. So now I think maybe checking `enabled` flag when adding config in `AbstractConfigManager` is not a good choice.

Hope this helps.

**Comment by songxiaosheng** [comment]
@bitgorust The ports related to indicators have been migrated to the QOS service, and outdated configurations will gradually be removed in the future

**Comment by bitgorust** [comment]
> @bitgorust The ports related to indicators have been migrated to the QOS service, and outdated configurations will gradually be removed in the future

@songxiaosheng Thanks for telling your plan. So maybe we can simply drop L280 and L282 here instead of kind of breaking changes like #13687?

https://github.com/apache/dubbo/blob/5c0b1deb1c2fae2e37b4add093b7122da73f971e/dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java#L279-L283

**Comment by songxiaosheng** [comment]
> .c

you can try it

**Comment by songxiaosheng** [comment]
> > @bitgorust The ports related to indicators have been migrated to the QOS service, and outdated configurations will gradually be removed in the future
> 
> @songxiaosheng Thanks for telling your plan. So maybe we can simply drop L280 and L282 here instead of kind of breaking changes like #13687?
> 
> https://github.com/apache/dubbo/blob/5c0b1deb1c2fae2e37b4add093b7122da73f971e/dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java#L279-L283

you can try it

**Comment by bitgorust** [comment]
> > > @bitgorust The ports related to indicators have been migrated to the QOS service, and outdated configurations will gradually be removed in the future
> > 
> > 
> > @songxiaosheng Thanks for telling your plan. So maybe we can simply drop L280 and L282 here instead of kind of breaking changes like #13687?
> > https://github.com/apache/dubbo/blob/5c0b1deb1c2fae2e37b4add093b7122da73f971e/dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java#L279-L283
> 
> you can try it

Pull request is subbmited: https://github.com/apache/dubbo/pull/13705

**Comment by songxiaosheng** [comment]
How about deleting the outdated methods and testing them out

**Comment by bitgorust** [comment]
> How about deleting the outdated methods and testing them out

Glad to be part of the future. I think following code can be deleted. There will be another PR  later.

https://github.com/apache/dubbo/blob/29b0c7298d06fb401498b809d1a19fa6396f2cb5/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java#L666

https://github.com/apache/dubbo/blob/29b0c7298d06fb401498b809d1a19fa6396f2cb5/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java#L445

https://github.com/apache/dubbo/blob/29b0c7298d06fb401498b809d1a19fa6396f2cb5/dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java#L270-L286

**Comment by bitgorust** [comment]
> > How about deleting the outdated methods and testing them out
> 
> Glad to be part of the future. I think following code can be deleted. There will be another PR later.
> 
> https://github.com/apache/dubbo/blob/29b0c7298d06fb401498b809d1a19fa6396f2cb5/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java#L666
> 
> https://github.com/apache/dubbo/blob/29b0c7298d06fb401498b809d1a19fa6396f2cb5/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java#L445
> 
> https://github.com/apache/dubbo/blob/29b0c7298d06fb401498b809d1a19fa6396f2cb5/dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java#L270-L286

@songxiaosheng Here is the new one: https://github.com/apache/dubbo/pull/13717
