### ISSUE TITLE
 TLS negotiation failed when trying to accept new connection

### ISSUE THREAD

**Issue by lizf2014** [apache/dubbo#13707]
服务启动后，一直报以下错误，1s 出现一次，不影响接口调用，大家有人遇到过吗？
### Environment
* Dubbo version: 3.2.7
* Java version: 17
* dubbo.protocol.name=dubbo

`[DUBBO] TLS negotiation failed when trying to accept new connection., dubbo version: 3.2.7, current host: 192.168.48.92, error code: 99-0. This may be caused by unknown error in remoting module, go to https://dubbo.apache.org/faq/99/0 to find instructions. 
java.net.SocketException: Connection reset
	at sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426) ~[?:?]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:259) ~[netty-buffer-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by AlbumenJ** [comment]
Did you enable the TLS mode?

**Comment by lizf2014** [comment]
I didn't enable the TLS mode, just use default config. @AlbumenJ

**Comment by AlbumenJ** [comment]
Can you please submit a demo?

**Comment by lizf2014** [comment]
@AlbumenJ 不太好复现，目前只有部分服务会出现这个 error，其他服务是正常的，配置和代码是一致的。

这个场景下，如果我改为使用 triple 协议，又会一直报下边这个错，也是 1s 一次：
```
[DUBBO] Unexpected exception from downstream before protocol detected., dubbo version: 3.2.7, current host: 192.168.48.247, error code: 99-0. This may be caused by unknown error in remoting module, go to https://dubbo.apache.org/faq/99/0 to find instructions. 
java.net.SocketException: Connection reset
	at sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426) ~[?:?]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:259) ~[netty-buffer-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by lizf2014** [comment]
@AlbumenJ 经过 debug 后，是下图中代码会抛出 Connection reset：
<img width="1060" alt="image" src="https://github.com/apache/dubbo/assets/35981577/47f700c8-5bf6-4530-ae3d-41f072076f73">

**Comment by AlbumenJ** [comment]
> @AlbumenJ 不太好复现，目前只有部分服务会出现这个 error，其他服务是正常的，配置和代码是一致的。
> 
> 这个场景下，如果我改为使用 triple 协议，又会一直报下边这个错，也是 1s 一次：
> 
> ```
> [DUBBO] Unexpected exception from downstream before protocol detected., dubbo version: 3.2.7, current host: 192.168.48.247, error code: 99-0. This may be caused by unknown error in remoting module, go to https://dubbo.apache.org/faq/99/0 to find instructions. 
> java.net.SocketException: Connection reset
> 	at sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394) ~[?:?]
> 	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426) ~[?:?]
> 	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:259) ~[netty-buffer-4.1.87.Final.jar!/:4.1.87.Final]
> 	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.87.Final.jar!/:4.1.87.Final]
> 	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.87.Final.jar!/:4.1.87.Final]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> ```

Add a breakpoint and get the config of remote address.

**Comment by Quison** [comment]
这个问题我遇到了，我们的情况是这样的：
1. 我们之前由于网络原因，使用了直连方式调用，后面因为负载原因，使用了阿里云的负载均衡（SLB）；
2. SLB有个存活检测，导致一秒钟调用一次20880接口，dubbo2.x的时候没有报错，dubbo升级到3.x的时候，这个就会报，原因应该是数据协议不兼容导致的
3. 解决方法：使用正常的注册中心调度即可，也可以关闭存活检测、或者存活检测22222端口，甚至可以单独开发一个接口专门用于存活检测。
