### ISSUE TITLE
Dubbo AOT or spring AOT did not fully recognize the classes that fastjson needs to handle and generated them into a file reflect-config.json

### ISSUE THREAD

**Issue by imgoby** [apache/dubbo#13785]
version:  <dubbo.version>3.3.0-beta.1</dubbo.version>

for example:There is a  failure while running under native-image.
 JSON.parseObject(str, Xxx.class)

I think : Dubbo AOT or spring AOT did not fully recognize the classes that fastjson needs to handle and generated them into a file reflect-config.json

I have to add this model one by one.It is so difficult.

**Comment by AlbumenJ** [comment]
@CrazyHZM

**Comment by imgoby** [comment]
while run:
mvn  package native:compile -P native
some information is as bellow:

```
java.lang.reflect.InaccessibleObjectException: Unable to make field private byte java.lang.StackTraceElement.format accessible: module java.base does not "opens java.lang" to unnamed module @5890e879
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.alibaba.com.caucho.hessian.io.JavaDeserializer.getFieldMap(JavaDeserializer.java:340)
	at com.alibaba.com.caucho.hessian.io.JavaDeserializer.<init>(JavaDeserializer.java:80)
	at com.alibaba.com.caucho.hessian.io.StackTraceElementDeserializer.<init>(StackTraceElementDeserializer.java:56)
	at com.alibaba.com.caucho.hessian.io.SerializerFactory.<clinit>(SerializerFactory.java:189)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at org.apache.dubbo.aot.generate.JarScanner.lambda$forNames$0(JarScanner.java:63)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
	at org.apache.dubbo.aot.generate.JarScanner.forNames(JarScanner.java:61)
	at org.apache.dubbo.aot.generate.JarScanner.getClasses(JarScanner.java:48)
	at org.apache.dubbo.aot.generate.ClassSourceScanner.spiClassesWithAdaptive(ClassSourceScanner.java:57)
	at org.apache.dubbo.aot.generate.AotProcessor.main(AotProcessor.java:37)

```

**Comment by CrazyHZM** [comment]
Is `JSON.parseObject` your business code or code within a framework?
@imgoby

**Comment by imgoby** [comment]
business code.

**Comment by CrazyHZM** [comment]
You can consider using metadata collection with tracing agent (https://www.graalvm.org/latest/reference-manual/native-image/metadata/AutomaticMetadataCollection/).
It is not an issue that  Dubbo and Spring should solve.
@imgoby

**Comment by imgoby** [comment]
thank you.
