### ISSUE TITLE
CodeStyleNotSupportException，only support [jax-rs, spring-webmvc] annotation

### ISSUE THREAD

**Issue by xfyang1988** [apache/dubbo#13780]
dubbo:3.2.11

以下报错信息：
org.apache.dubbo.rpc.protocol.rest.exception.CodeStyleNotSupportException: service is: interface xxx.DemoDubboFacade, only support [jax-rs, spring-webmvc] annotation
	at org.apache.dubbo.rpc.protocol.rest.annotation.metadata.MetadataResolver.resolveConsumerServiceMetadata(MetadataResolver.java:54) ~[dubbo-3.2.11.jar:3.2.11]
	at org.apache.dubbo.rpc.protocol.rest.RestProtocol.protocolBindingRefer(RestProtocol.java:134) ~[dubbo-3.2.11.jar:3.2.11]
	at org.apache.dubbo.rpc.protocol.AbstractProtocol.refer(AbstractProtocol.java:137) ~[dubbo-3.2.11.jar:3.2.11]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:87) ~[dubbo-3.2.11.jar:3.2.11]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:85) ~[dubbo-3.2.11.jar:3.2.11]
	at org.apache.dubbo.rpc.protocol.ProtocolSecurityWrapper.refer(ProtocolSecurityWrapper.java:112) ~[dubbo-3.2.11.jar:3.2.11]
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:75) ~[dubbo-3.2.11.jar:3.2.11]
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:55) ~[dubbo-3.2.11.jar:3.2.11]
	at org.apache.dubbo.rpc.protocol.InvokerCountWrapper.refer(InvokerCountWrapper.java:50) ~[dubbo-3.2.11.jar:3.2.11]
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java) ~[dubbo-3.2.11.jar:3.2.11]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.toInvokers(ServiceDiscoveryRegistryDirectory.java:490) [dubbo-3.2.11.jar:3.2.11]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.refreshInvoker(ServiceDiscoveryRegistryDirectory.java:356) [dubbo-3.2.11.jar:3.2.11]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.refreshOverrideAndInvoker(ServiceDiscoveryRegistryDirectory.java:219) [dubbo-3.2.11.jar:3.2.11]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.notify(ServiceDiscoveryRegistryDirectory.java:211) [dubbo-3.2.11.jar:3.2.11]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.lambda$null$10(ServiceInstancesChangedListener.java:467) [dubbo-3.2.11.jar:3.2.11]
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597) ~[na:1.8.0_333]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.lambda$notifyAddressChanged$11(ServiceInstancesChangedListener.java:458) [dubbo-3.2.11.jar:3.2.11]
	at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:76) ~[dubbo-3.2.11.jar:3.2.11]
	at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:59) ~[dubbo-3.2.11.jar:3.2.11]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.notifyAddressChanged(ServiceInstancesChangedListener.java:455) [dubbo-3.2.11.jar:3.2.11]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.doOnEvent(ServiceInstancesChangedListener.java:243) [dubbo-3.2.11.jar:3.2.11]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.onEvent(ServiceInstancesChangedListener.java:125) [dubbo-3.2.11.jar:3.2.11]
	at org.apache.dubbo.registry.nacos.NacosServiceDiscovery.handleEvent(NacosServiceDiscovery.java:245) ~[dubbo-3.2.11.jar:3.2.11]
	at org.apache.dubbo.registry.nacos.NacosServiceDiscovery.access$000(NacosServiceDiscovery.java:65) ~[dubbo-3.2.11.jar:3.2.11]
	at org.apache.dubbo.registry.nacos.NacosServiceDiscovery$NacosEventListener.onEvent(NacosServiceDiscovery.java:217) ~[dubbo-3.2.11.jar:3.2.11]
	at com.alibaba.nacos.client.naming.event.InstancesChangeNotifier.onEvent(InstancesChangeNotifier.java:126) ~[nacos-client-2.2.0.jar:na]
	at com.alibaba.nacos.client.naming.event.InstancesChangeNotifier.onEvent(InstancesChangeNotifier.java:42) ~[nacos-client-2.2.0.jar:na]
	at com.alibaba.nacos.common.notify.DefaultPublisher.lambda$notifySubscriber$0(DefaultPublisher.java:199) ~[nacos-client-2.2.0.jar:na]
	at com.alibaba.nacos.common.notify.DefaultPublisher.notifySubscriber(DefaultPublisher.java:206) ~[nacos-client-2.2.0.jar:na]
	at com.alibaba.nacos.common.notify.DefaultPublisher.receiveEvent(DefaultPublisher.java:190) ~[nacos-client-2.2.0.jar:na]
	at com.alibaba.nacos.common.notify.DefaultPublisher.openEventHandler(DefaultPublisher.java:112) ~[nacos-client-2.2.0.jar:na]
	at com.alibaba.nacos.common.notify.DefaultPublisher.run(DefaultPublisher.java:95) ~[nacos-client-2.2.0.jar:na]

是不支持在RestController直接用@DubboReference注解么？
![image](https://github.com/apache/dubbo/assets/19721648/0ee20bda-d169-4191-ae5c-ec313f153025)
我看源码里面TO DO，是打算后续版本支持么？

**Comment by AlbumenJ** [comment]
> Is it not supported to use @DubboReference annotation directly in RestController?

Can you please provide your code?

**Comment by suncairong163** [comment]
> dubbo:3.2.11
> 
> 以下报错信息： org.apache.dubbo.rpc.protocol.rest.exception.CodeStyleNotSupportException: service is: interface xxx.DemoDubboFacade, only support [jax-rs, spring-webmvc] annotation at org.apache.dubbo.rpc.protocol.rest.annotation.metadata.MetadataResolver.resolveConsumerServiceMetadata(MetadataResolver.java:54) ~[dubbo-3.2.11.jar:3.2.11] at org.apache.dubbo.rpc.protocol.rest.RestProtocol.protocolBindingRefer(RestProtocol.java:134) ~[dubbo-3.2.11.jar:3.2.11] at org.apache.dubbo.rpc.protocol.AbstractProtocol.refer(AbstractProtocol.java:137) ~[dubbo-3.2.11.jar:3.2.11] at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:87) ~[dubbo-3.2.11.jar:3.2.11] at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:85) ~[dubbo-3.2.11.jar:3.2.11] at org.apache.dubbo.rpc.protocol.ProtocolSecurityWrapper.refer(ProtocolSecurityWrapper.java:112) ~[dubbo-3.2.11.jar:3.2.11] at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:75) ~[dubbo-3.2.11.jar:3.2.11] at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:55) ~[dubbo-3.2.11.jar:3.2.11] at org.apache.dubbo.rpc.protocol.InvokerCountWrapper.refer(InvokerCountWrapper.java:50) ~[dubbo-3.2.11.jar:3.2.11] at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java) ~[dubbo-3.2.11.jar:3.2.11] at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.toInvokers(ServiceDiscoveryRegistryDirectory.java:490) [dubbo-3.2.11.jar:3.2.11] at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.refreshInvoker(ServiceDiscoveryRegistryDirectory.java:356) [dubbo-3.2.11.jar:3.2.11] at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.refreshOverrideAndInvoker(ServiceDiscoveryRegistryDirectory.java:219) [dubbo-3.2.11.jar:3.2.11] at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.notify(ServiceDiscoveryRegistryDirectory.java:211) [dubbo-3.2.11.jar:3.2.11] at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.lambda$null$10(ServiceInstancesChangedListener.java:467) [dubbo-3.2.11.jar:3.2.11] at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597) ~[na:1.8.0_333] at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.lambda$notifyAddressChanged$11(ServiceInstancesChangedListener.java:458) [dubbo-3.2.11.jar:3.2.11] at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:76) ~[dubbo-3.2.11.jar:3.2.11] at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:59) ~[dubbo-3.2.11.jar:3.2.11] at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.notifyAddressChanged(ServiceInstancesChangedListener.java:455) [dubbo-3.2.11.jar:3.2.11] at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.doOnEvent(ServiceInstancesChangedListener.java:243) [dubbo-3.2.11.jar:3.2.11] at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.onEvent(ServiceInstancesChangedListener.java:125) [dubbo-3.2.11.jar:3.2.11] at org.apache.dubbo.registry.nacos.NacosServiceDiscovery.handleEvent(NacosServiceDiscovery.java:245) ~[dubbo-3.2.11.jar:3.2.11] at org.apache.dubbo.registry.nacos.NacosServiceDiscovery.access$000(NacosServiceDiscovery.java:65) ~[dubbo-3.2.11.jar:3.2.11] at org.apache.dubbo.registry.nacos.NacosServiceDiscovery$NacosEventListener.onEvent(NacosServiceDiscovery.java:217) ~[dubbo-3.2.11.jar:3.2.11] at com.alibaba.nacos.client.naming.event.InstancesChangeNotifier.onEvent(InstancesChangeNotifier.java:126) ~[nacos-client-2.2.0.jar:na] at com.alibaba.nacos.client.naming.event.InstancesChangeNotifier.onEvent(InstancesChangeNotifier.java:42) ~[nacos-client-2.2.0.jar:na] at com.alibaba.nacos.common.notify.DefaultPublisher.lambda$notifySubscriber$0(DefaultPublisher.java:199) ~[nacos-client-2.2.0.jar:na] at com.alibaba.nacos.common.notify.DefaultPublisher.notifySubscriber(DefaultPublisher.java:206) ~[nacos-client-2.2.0.jar:na] at com.alibaba.nacos.common.notify.DefaultPublisher.receiveEvent(DefaultPublisher.java:190) ~[nacos-client-2.2.0.jar:na] at com.alibaba.nacos.common.notify.DefaultPublisher.openEventHandler(DefaultPublisher.java:112) ~[nacos-client-2.2.0.jar:na] at com.alibaba.nacos.common.notify.DefaultPublisher.run(DefaultPublisher.java:95) ~[nacos-client-2.2.0.jar:na]
> 
> 是不支持在RestController直接用@DubboReference注解么？ ![image](https://private-user-images.githubusercontent.com/19721648/306926619-0ee20bda-d169-4191-ae5c-ec313f153025.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NzQ0NjUsIm5iZiI6MTcwOTQ3NDE2NSwicGF0aCI6Ii8xOTcyMTY0OC8zMDY5MjY2MTktMGVlMjBiZGEtZDE2OS00MTkxLWFlNWMtZWMzMTNmMTUzMDI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDEzNTYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5MzQxMjg2ZDliMzA2MDA4OTJiYTJmZTMzM2ExYTk4MDI2M2IyNmM5YWUzOTkwM2FjMjIxNWZjMzFhMjJiZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1ivRqhTZhM8t-dam30PR3jcx2KoTisb818zcRJgp1ZA) 我看源码里面TO DO，是打算后续版本支持么？

Dubbo code style is not support at 3.2
