### ISSUE TITLE
Invoke error

### ISSUE THREAD

**Issue by libq25** [apache/dubbo#13805]
我的服务升级到了dubbo3.2，同时注册到了nacos中。服务消费端在调用接口时。在服务端收到请求后，返回结果时会报错
换了好几个版本的fasterxml-jackson都一样
`2024/02/28-17:11:09.200 [DubboServerHandler-10.2.21.42:20883-thread-20] ERROR o.a.dubbo.rpc.filter.ExceptionFilter -  [DUBBO] Got unchecked and undeclared exception which called by 10.1.1.197. service: com.test.Facade, method: orderSearchList, exception: java.lang.NoSuchMethodError: com.fasterxml.jackson.dataformat.smile.SmileGenerator.getOutputContext()Lcom/fasterxml/jackson/core/json/JsonWriteContext;, dubbo version: 3.2.0, current host: 10.2.21.42, error code: 5-36. This may be caused by , go to https://dubbo.apache.org/faq/5/36 to find instructions. 
java.lang.NoSuchMethodError: com.fasterxml.jackson.dataformat.smile.SmileGenerator.getOutputContext()Lcom/fasterxml/jackson/core/json/JsonWriteContext;
	at com.fasterxml.jackson.dataformat.smile.SmileGenerator.close(SmileGenerator.java:1516)
	at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.close(JsonXContentGenerator.java:445)
	at org.elasticsearch.common.xcontent.XContentBuilder.close(XContentBuilder.java:1174)
	at org.elasticsearch.common.xcontent.XContentBuilder.bytes(XContentBuilder.java:1186)
	at org.elasticsearch.action.support.ToXContentToBytes.buildAsBytes(ToXContentToBytes.java:64)
	at org.elasticsearch.action.search.SearchRequest.source(SearchRequest.java:250)`

**Comment by AlbumenJ** [comment]
This is the exception from your biz code. Please fix your biz code first.

**Comment by AlbumenJ** [comment]
BTW, arthas can help you.

**Comment by libq25** [comment]
It's a version issue with the spring-data-elasticsearch package，is done
