### ISSUE TITLE
ClassNotFoundException  when upgrade from 2.5.5 to 2.7.5

### ISSUE THREAD

**Issue by nulinuli-nuli** [apache/dubbo#13806]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.5
* Operating System version: centos
* Java version: 1.8

### Steps to reproduce this issue

将dubbo版本由2.5.5升级到2.7.5的时候启动报错，错误日志在下面
配置为
	<dubbo:reference
            id="xxx"
            interface="xxx"
            version="1.0.0"
            cluster="failfast"
            lazy="true"
            timeout="50000"
            check="false"
            registry="xxx">
    </dubbo:reference>

CGLIB生成代理的时候报错，没有找到类org.apache.dubbo.common.bytecode.proxy4

### Actual Behavior

If there is an exception, please attach the exception trace:

Caused by: java.lang.ClassNotFoundException: org.apache.dubbo.common.bytecode.proxy4
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151) ~[spiderAdapterApplication.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_131]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_131]
	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:535) ~[spring-core-5.2.11.RELEASE.jar!/:5.2.11.RELEASE]
	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:363) ~[spring-core-5.2.11.RELEASE.jar!/:5.2.11.RELEASE]
	at org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:585) ~[spring-core-5.2.11.RELEASE.jar!/:5.2.11.RELEASE]
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:110) ~[spring-core-5.2.11.RELEASE.jar!/:5.2.11.RELEASE]
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:108) ~[spring-core-5.2.11.RELEASE.jar!/:5.2.11.RELEASE]
	at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54) ~[spring-core-5.2.11.RELEASE.jar!/:5.2.11.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61) ~[spring-core-5.2.11.RELEASE.jar!/:5.2.11.RELEASE]
	at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34) ~[spring-core-5.2.11.RELEASE.jar!/:5.2.11.RELEASE]
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:134) ~[spring-core-5.2.11.RELEASE.jar!/:5.2.11.RELEASE]
	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:319) ~[spring-core-5.2.11.RELEASE.jar!/:5.2.11.RELEASE]
	at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:572) ~[spring-core-5.2.11.RELEASE.jar!/:5.2.11.RELEASE]
	at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:419) ~[spring-core-5.2.11.RELEASE.jar!/:5.2.11.RELEASE]
	at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:57) ~[spring-aop-5.2.11.RELEASE.jar!/:5.2.11.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:205) ~[spring-aop-5.2.11.RELEASE.jar!/:5.2.11.RELEASE]
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:110) ~[spring-aop-5.2.11.RELEASE.jar!/:5.2.11.RELEASE]
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.createProxy(AbstractAutoProxyCreator.java:471) ~[spring-aop-5.2.11.RELEASE.jar!/:5.2.11.RELEASE]
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:350) ~[spring-aop-5.2.11.RELEASE.jar!/:5.2.11.RELEASE]
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:299) ~[spring-aop-5.2.11.RELEASE.jar!/:5.2.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:430) ~[spring-beans-5.2.11.RELEASE.jar!/:5.2.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.postProcessObjectFromFactoryBean(AbstractAutowireCapableBeanFactory.java:1937) ~[spring-beans-5.2.11.RELEASE.jar!/:5.2.11.RELEASE]

```
Just put your stack trace here!
```

**Comment by nulinuli-nuli** [comment]
org.apache.dubbo.common.bytecode.proxy4  dubbo生成代理对象 加载这个类用的是URlClassLoader
在springboot生成aop代理对象是用的确是LaunchedURLClassLoader导致ClassNotFound启动失败

**Comment by AlbumenJ** [comment]
Please check in the latest version (3.2.11)

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
