### ISSUE TITLE
when meshEnable=true，dubbo.consumer.check=false dubbo.consumer.lazy=true notwork

### ISSUE THREAD

**Issue by yuanzhibang-tool** [apache/dubbo#13815]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.11
* Operating System version: openjdk:21-jdk-slim-bullseye
* Java version: 21

### Steps to reproduce this issue

1. config content
```
spring.application.name=biz-api-gateway
dubbo.application.name=biz-api-gateway
dubbo.application.qosEnable=true
dubbo.application.qosAcceptForeignIp=true

# istio架构
dubbo.application.metadataServicePort=20885
# dubbo.registry.address=N/A
dubbo.protocol.name=tri
dubbo.protocol.serialization=fastjson2
dubbo.protocol.port=50052
dubbo.consumer.timeout=30000
# enable mesh
dubbo.consumer.meshEnable=true

dubbo.consumer.check=false
dubbo.consumer.lazy=true
```
2. consumer reference
```
@DubboReference(check = false, lazy = true, providedBy = "test-service", providerPort = 50052)
TestService testService;
```
3. RUN with exception
```
java.net.UnknownHostException: test-service.default.svc.cluster.local
        at java.base/java.net.InetAddress$CachedLookup.get(InetAddress.java:988) ~[na:na]
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1818) ~[na:na]
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1688) ~[na:na]
        at java.base/java.net.InetAddress.getByName(InetAddress.java:1568) ~[na:na]
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156) ~[netty-common-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153) ~[netty-common-4.1.107.Final.jar:4.1.107.Final]
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:571) ~[na:na]
        at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153) ~[netty-common-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41) ~[netty-resolver-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61) ~[netty-resolver-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53) ~[netty-resolver-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55) ~[netty-resolver-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31) ~[netty-resolver-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106) ~[netty-resolver-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:220) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:47) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:189) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:175) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[netty-common-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557) ~[netty-common-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[netty-common-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) ~[netty-common-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625) ~[netty-common-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105) ~[netty-common-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[netty-common-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[netty-common-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.107.Final.jar:4.1.107.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.107.Final.jar:4.1.107.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
```
Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior
like the `lazy` and `check` document description.

### Actual Behavior
the netty client try to connect the service address, and if the address not found it throw an exception above.

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by AlbumenJ** [comment]
1. Triple protocol not supports lazy now
2. `Check=false` is work as expected

**Comment by yuanzhibang-tool** [comment]
@AlbumenJ Ok,Thanks for your reply.
