### ISSUE TITLE
how to cancel the injection of Hessian2FactoryManager ? (AOT)

### ISSUE THREAD

**Issue by StupidManYI** [apache/dubbo#13816]
### Environment

* Dubbo version: 3.3.0-beta.1
* Operating System version: linux-x64 or window-x64 or macOs
* Java version: graalvm-ce-17.0.9

### Steps to reproduce this issue

1. git clone https://github.com/StupidManYI/dubbo-graalvm17-native-build-demo/
2. you need to deploy nacos 2.2.3 
3. modify application.yml

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

cancel the injection of Hessian2FactoryManager  and run application Succesful

(as much as possible AOT ``` mvn native:compile -Pnative  ```  Succesful)

### Actual Behavior

I don't need hessian2, I just want to use fastjson2, I have removed all hessian2 dependencies,
but why dubbo still inject Hessian2FactoryManager

```at class org.apache.dubbo.common.beans.factory.ScopeBeanFactory =>line 87 => T instance = getBean(name, clazz);```

<img width="1439" alt="image" src="https://github.com/apache/dubbo/assets/50037510/980c5a78-d474-4cc4-b69a-14c158b669c0">

**If there is an exception, please attach the exception trace:**

core problem

```
org.apache.dubbo.common.beans.ScopeBeanException: create bean instance failed, type=org.apache.dubbo.common.serialize.hessian2.Hessian2FactoryManager
```
all
```
org.apache.dubbo.common.beans.ScopeBeanException: create bean instance failed, type=org.apache.dubbo.common.serialize.hessian2.Hessian2FactoryManager
	at org.apache.dubbo.common.beans.factory.ScopeBeanFactory.createAndRegisterBean(ScopeBeanFactory.java:94) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.apache.dubbo.common.beans.factory.ScopeBeanFactory.getOrRegisterBean(ScopeBeanFactory.java:131) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.apache.dubbo.common.beans.factory.ScopeBeanFactory.registerBean(ScopeBeanFactory.java:78) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.apache.dubbo.common.serialize.hessian2.Hessian2ScopeModelInitializer.initializeFrameworkModel(Hessian2ScopeModelInitializer.java:29) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.apache.dubbo.rpc.model.FrameworkModel.<init>(FrameworkModel.java:97) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.apache.dubbo.rpc.model.FrameworkModel.defaultModel(FrameworkModel.java:181) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.apache.dubbo.config.spring.context.DubboSpringInitializer.customize(DubboSpringInitializer.java:198) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.apache.dubbo.config.spring.context.DubboSpringInitializer.initContext(DubboSpringInitializer.java:108) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.apache.dubbo.config.spring.context.DubboSpringInitializer.initialize(DubboSpringInitializer.java:65) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.apache.dubbo.config.spring.context.annotation.DubboConfigConfigurationRegistrar.registerBeanDefinitions(DubboConfigConfigurationRegistrar.java:40) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.springframework.context.annotation.ImportBeanDefinitionRegistrar.registerBeanDefinitions(ImportBeanDefinitionRegistrar.java:86) ~[spring-context-6.1.2.jar:6.1.2]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:376) ~[spring-context-6.1.2.jar:6.1.2]
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[na:na]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:375) ~[spring-context-6.1.2.jar:6.1.2]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:148) ~[spring-context-6.1.2.jar:6.1.2]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:120) ~[spring-context-6.1.2.jar:6.1.2]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:428) ~[spring-context-6.1.2.jar:6.1.2]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:289) ~[spring-context-6.1.2.jar:6.1.2]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:349) ~[spring-context-6.1.2.jar:6.1.2]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:118) ~[spring-context-6.1.2.jar:6.1.2]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:789) ~[spring-context-6.1.2.jar:6.1.2]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:606) ~[spring-context-6.1.2.jar:6.1.2]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.1.jar:3.2.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762) ~[spring-boot-3.2.1.jar:3.2.1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:464) ~[spring-boot-3.2.1.jar:3.2.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.1.jar:3.2.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1358) ~[spring-boot-3.2.1.jar:3.2.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1347) ~[spring-boot-3.2.1.jar:3.2.1]
	at com.ingsha.nativeDemo.Application.main(Application.java:24) ~[classes/:na]
Caused by: java.lang.NoClassDefFoundError: com/alibaba/com/caucho/hessian/io/SerializerFactory
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[na:na]
	at java.base/java.lang.Class.getConstructor0(Class.java:3578) ~[na:na]
	at java.base/java.lang.Class.getConstructor(Class.java:2271) ~[na:na]
	at org.apache.dubbo.common.beans.support.InstantiationStrategy.instantiate(InstantiationStrategy.java:53) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	at org.apache.dubbo.common.beans.factory.ScopeBeanFactory.createAndRegisterBean(ScopeBeanFactory.java:92) ~[dubbo-3.3.0-beta.1.jar:3.3.0-beta.1]
	... 28 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.alibaba.com.caucho.hessian.io.SerializerFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[na:na]
	... 34 common frames omitted

```

**Comment by StupidManYI** [comment]
After reading the repository (https://github.com/imgoby/spring-cloud-alibaba-dubbo-native/tree/main) , I modified the dependencies and successfully packaged , 

but there are still some nacos bugs , wait for nacos to hear back
https://github.com/alibaba/nacos/issues/11790)

**Comment by StupidManYI** [comment]
nacos is not currently supported native:compile, so I replaced nacos to zookeeper(new branch zookeeper),

I met a new bug when `mvn clean package native:compile -Pnative`
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/PropertyNamingStrategies
        at org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$JacksonAutoConfigurationRuntimeHints.registerPropertyNamingStrategyHints(JacksonAutoConfiguration.java:360)
        at org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$JacksonAutoConfigurationRuntimeHints.registerHints(JacksonAutoConfiguration.java:350)
        at org.springframework.context.aot.RuntimeHintsBeanFactoryInitializationAotProcessor$RuntimeHintsRegistrarContribution.lambda$applyTo$0(RuntimeHintsBeanFactoryInitializationAotProcessor.java:116)
        at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647)
        at org.springframework.context.aot.RuntimeHintsBeanFactoryInitializationAotProcessor$RuntimeHintsRegistrarContribution.applyTo(RuntimeHintsBeanFactoryInitializationAotProcessor.java:110)
        at org.springframework.context.aot.BeanFactoryInitializationAotContributions.applyTo(BeanFactoryInitializationAotContributions.java:78)
        at org.springframework.context.aot.ApplicationContextAotGenerator.lambda$processAheadOfTime$0(ApplicationContextAotGenerator.java:58)
        at org.springframework.context.aot.ApplicationContextAotGenerator.withCglibClassHandler(ApplicationContextAotGenerator.java:67)
        at org.springframework.context.aot.ApplicationContextAotGenerator.processAheadOfTime(ApplicationContextAotGenerator.java:53)
        at org.springframework.context.aot.ContextAotProcessor.performAotProcessing(ContextAotProcessor.java:106)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:84)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
        at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
        at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:80)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.PropertyNamingStrategies
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 14 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.494 s
[INFO] Finished at: 2024-03-05T02:22:21+08:00



```

**Comment by CrazyHZM** [comment]
@StupidManYI 
Please refer to https://github.com/apache/dubbo-samples/tree/master/2-advanced/dubbo-samples-native-image-registry

**Comment by StupidManYI** [comment]
thanks
