### ISSUE TITLE
[Bug] actual protocal 【tri】，but  dubbo://xxxxxxxxx:50051/org.apache.dubbo.metadata.MetadataService  request ues 【dubbo】protocal，and then timeout，we do not know why？

### ISSUE THREAD

**Issue by vhypnus** [apache/dubbo#14054]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

3.2.5

### Steps to reproduce this issue

以下是配置信息
nacos:
  config:
    server-addr: xxxxx
    namespace: xxxxxxx-f1459f0956d0
    data-ids: xx,xx
    group: xxxxxxx
    type: yaml
    auto-refresh: true
    bootstrap:
      enable: true
      log:
        enable: true
    username: xxxx
    password: xxxxx
dubbo:
  registries:
    idRegistry:
      address: nacos://1xxxxxx:8848,xxxxxxxx:8848?username=xxx&password=xxxxx
      register-mode: instance
      group: xxxx-xxxxx
      parameters.namespace: xxxxx
  protocol:
    name: tri
    port: -1
  consumer:
    check: false
    retries: 0
    timeout: 30000
  metrics:
    protocol: prometheus
    enable-jvm: true
    enable-metadata: true
    enable-registry: true
    enable-rpc: true
    enable-threadpool: true
    aggregation:
      enabled: true
    prometheus:
      exporter:
        enabled: true

以下是异常信息
2024-03-27 16:19:35.745 ERROR 2515 --- [Dubbo-framework-metadata-retry-thread-1] o.a.d.r.client.metadata.MetadataUtils    :  [DUBBO] Failed to get app metadata for revision d53353ed39151ea19ab50bff2f9dc0b5 for type local from instance 10.184.0.42:50051, dubbo version: 3.2.5, current host: 10.184.0.48, error code: 1-39. This may be caused by , go to https://dubbo.apache.org/faq/1/39 to find instructions. 

org.apache.dubbo.rpc.RpcException: Invoke remote method timeout. method: getMetadataInfo, provider: dubbo://xxxxxxxxx:50051/org.apache.dubbo.metadata.MetadataService?getAndListenInstanceMetadata.1.callback=true&group=pay-api-trade&reconnect=false&retries=0&side=consumer&timeout=5000&version=1.0.0, cause: Timeout after 5000ms waiting for result.
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:304) ~[dubbo-3.2.5.jar!/:3.2.5]
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:190) ~[dubbo-3.2.5.jar!/:3.2.5]
	at org.apache.dubbo.rpc.proxy.InvocationUtil.invoke(InvocationUtil.java:61) ~[dubbo-3.2.5.jar!/:3.2.5]
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:75) ~[dubbo-3.2.5.jar!/:3.2.5]
	at org.apache.dubbo.metadata.MetadataServiceDubboProxy31.getMetadataInfo(MetadataServiceDubboProxy31.java) ~[dubbo-3.2.5.jar!/:3.2.5]
	at org.apache.dubbo.registry.client.metadata.MetadataUtils.getRemoteMetadata(MetadataUtils.java:173) ~[dubbo-3.2.5.jar!/:3.2.5]
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.lambda$getRemoteMetadata$2(AbstractServiceDiscovery.java:229) [dubbo-3.2.5.jar!/:3.2.5]
	at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:90) ~[dubbo-3.2.5.jar!/:3.2.5]
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.getRemoteMetadata(AbstractServiceDiscovery.java:228) [dubbo-3.2.5.jar!/:3.2.5]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.lambda$doOnEvent$2(ServiceInstancesChangedListener.java:162) ~[dubbo-3.2.5.jar!/:3.2.5]
	at java.util.Optional.orElseGet(Optional.java:267) ~[na:1.8.0_181]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.doOnEvent(ServiceInstancesChangedListener.java:162) ~[dubbo-3.2.5.jar!/:3.2.5]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.onEvent(ServiceInstancesChangedListener.java:116) ~[dubbo-3.2.5.jar!/:3.2.5]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener$AddressRefreshRetryTask.run(ServiceInstancesChangedListener.java:489) ~[dubbo-3.2.5.jar!/:3.2.5]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
Caused by: java.util.concurrent.TimeoutException: Timeout after 5000ms waiting for result.
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:207) ~[dubbo-3.2.5.jar!/:3.2.5]
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:287) ~[dubbo-3.2.5.jar!/:3.2.5]
	... 20 common frames omitted

### What you expected to happen

这个(dubbo://xxxxxxxx:50051)是否是导致问题的根本原因

### Are you willing to submit a pull request to fix on your own?

- [x] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vhypnus** [comment]
already fix
