### ISSUE TITLE
Dubbo 3.2 throws an error directly upon startup

### ISSUE THREAD

**Issue by nikbobo** [apache/dubbo#14178]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo Java 3.2.11, Zulu JDK 11

### Steps to reproduce this issue

```pom.xml```
```
        <dubbo.version>3.2.11</dubbo.version>
        <dubbo-extension.version>3.2.0</dubbo-extension.version>
        <nacos.version>2.3.2</nacos.version>
        <nacos-client.version>2.3.2</nacos-client.version>
        <nacos-spring-context.version>1.1.2</nacos-spring-context.version>
        <nacos-spring-boot.version>0.2.12</nacos-spring-boot.version>
```
```
        <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-registry-nacos</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-rpc-triple</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo.extensions</groupId>
            <artifactId>dubbo-serialization-fst</artifactId>
        </dependency>
```
```application.properties```
```
nacos.config.auto-refresh = true
nacos.config.bootstrap.enable = true
nacos.config.bootstrap.log-enable = true
nacos.config.enable-remote-sync-config = true
nacos.config.remote-first = true
dubbo.protocol.name = tri
dubbo.protocol.prefer-serialization = fst
dubbo.protocol.serialization = fst
dubbo.provider.prefer-serialization = fst
dubbo.registry.protocol = nacos
dubbo.provider.serialization = fst
dubbo.registry.register-mode = instance
```
These are what I consider special configurations; the rest are standard configurations.

### What you expected to happen

The application fails to start directly, displaying the error ```Application run failed```.

```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
-2024-05-13 10:43:59 -ERROR 16040  --- [main] org.springframework.boot.SpringApplication[818] : Application run failed
-
java.lang.NullPointerException: null
	at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.initDubboConfigBeans(DubboConfigApplicationListener.java:85) ~
	at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.init(DubboConfigApplicationListener.java:68) ~
	at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.onApplicationEvent(DubboConfigApplicationListener.java:59) ~
	at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.onApplicationEvent(DubboConfigApplicationListener.java:38) ~
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178) ~
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171) ~
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145) ~
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:133) ~
	at org.springframework.context.support.AbstractApplicationContext.registerListeners(AbstractApplicationContext.java:892) ~
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588) ~
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409) ~
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) ~
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289) ~
	at Application.main(Application.java:13) ~

2024-05-13 10:43:59 - WARN 16040  --- [main] o.s.c.a.AnnotationConfigApplicationContext[1072] : Exception thrown from ApplicationListener handling ContextClosedEvent
-
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.apache.dubbo.config.spring.context.DubboDeployApplicationListener': Initialization of bean failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:628) ~
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213) ~
	at org.springframework.context.event.AbstractApplicationEventMulticaster.retrieveApplicationListeners(AbstractApplicationEventMulticaster.java:264) ~
	at org.springframework.context.event.AbstractApplicationEventMulticaster.getApplicationListeners(AbstractApplicationEventMulticaster.java:221) ~
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:140) ~
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:429) ~
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:386) ~
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1069) ~
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1032) ~
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:784) ~
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:318) ~
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) ~
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289) ~
	at Application.main(Application.java:13) ~
Caused by: java.lang.NullPointerException: null
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.setApplicationContext(DubboDeployApplicationListener.java:69) ~
	at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:128) ~
	at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:102) ~
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440) ~
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~
	... 17 common frames omitted
```

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by nikbobo** [comment]
Debugging the Jar file revealed that ```moduleModel.getDeployer()``` being ```null``` caused the issue.

**Comment by nikbobo** [comment]
I found the cause to be the use of the maven-shade-plugin. If I switch to the spring-boot-maven-plugin, there are no issues. Here are my configurations for these two plugins. Did I miss something?
```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>${maven-shade-plugin.version}</version>
                <configuration>
                    <keepDependenciesWithProvidedScope>true</keepDependenciesWithProvidedScope>
                    <createDependencyReducedPom>true</createDependencyReducedPom>
                    <artifactSet>
                        <excludes>
                            <exclude>org.springframework.boot:spring-boot-devtools</exclude>
                            <exclude>org.springframework.boot:spring-boot-docker-compose</exclude>
                            <exclude>org.projectlombok:lombok</exclude>
                        </excludes>
                    </artifactSet>
                    <filters>
                        <filter>
                            <artifact>*:*</artifact>
                            <excludes>
                                <exclude>module-info.class</exclude>
                                <exclude>META-INF/*.SF</exclude>
                                <exclude>META-INF/*.DSA</exclude>
                                <exclude>META-INF/*.RSA</exclude>
                                <exclude>META-INF/DEPENDENCIES</exclude>
                                <exclude>META-INF/LICENSE*</exclude>
                                <exclude>META-INF/license/**</exclude>
                                <exclude>META-INF/licenses/**</exclude>
                                <exclude>META-INF/NOTICE*</exclude>
                                <exclude>META-INF/MANIFEST*</exclude>
                                <exclude>META-INF/maven/**</exclude>
                            </excludes>
                        </filter>
                    </filters>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <version>${spring-boot.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/spring.handlers</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/spring.schemas</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/spring.tooling</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/spring.provides</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/spring/org.springframework.boot.actuate.autoconfigure.web.ManagementContextConfiguration.imports</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/dubbo/org.apache.dubbo.rpc.Filter</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/dubbo/org.apache.dubbo.rpc.cluster.filter.ClusterFilter</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/druid-driver.properties</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/druid-filter.properties</resource>
                                </transformer>
                                <transformer
                                        implementation="org.springframework.boot.maven.PropertiesMergingResourceTransformer">
                                    <resource>META-INF/spring.factories</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ApacheNoticeResourceTransformer">
                                    <addHeader>false</addHeader>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <manifestEntries>
                                        <Main-Class>${spring-boot.application.class}</Main-Class>
                                    </manifestEntries>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ApacheLicenseResourceTransformer" />
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
```
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>${spring-boot.application.class}</mainClass>
                    <layout>JAR</layout>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                        <exclude>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-configuration-processor</artifactId>
                        </exclude>
                    </excludes>
                    <excludeDevtools>true</excludeDevtools>
                    <executable>true</executable>
                </configuration>
            </plugin>
```

**Comment by AlbumenJ** [comment]
Please submit the issue in English :)

**Comment by nikbobo** [comment]
> Please submit the issue in English :)

Already remove all Chinese, and debug to fix it, thanks!
