### ISSUE TITLE
[Bug] java.lang.IllegalArgumentException: interface org.apache.dubbo.rpc.service.EchoService is not visible from class loader

### ISSUE THREAD

**Issue by cloudarts** [apache/dubbo#14197]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo 3.2.12 jdk 17 nacos 2021.0.4.0

### Steps to reproduce this issue

Starting the springboot program classloader did not load the class

### What you expected to happen

java.lang.IllegalArgumentException: interface org.apache.dubbo.rpc.service.EchoService is not visible from class loader
	at org.apache.dubbo.common.bytecode.Proxy.buildInterfacesKey(Proxy.java:110) ~[dubbo-3.2.12.jar:3.2.12]
	at org.apache.dubbo.common.bytecode.Proxy.getProxy(Proxy.java:73) ~[dubbo-3.2.12.jar:3.2.12]
	at org.apache.dubbo.rpc.proxy.javassist.JavassistProxyFactory.getProxy(JavassistProxyFactory.java:46) ~[dubbo-3.2.12.jar:3.2.12]
	at org.apache.dubbo.rpc.proxy.AbstractProxyFactory.getProxy(AbstractProxyFactory.java:102) ~[dubbo-3.2.12.jar:3.2.12]
	at org.apache.dubbo.rpc.proxy.wrapper.StubProxyFactoryWrapper.getProxy(StubProxyFactoryWrapper.java:68) ~[dubbo-3.2.12.jar:3.2.12]
	at org.apache.dubbo.rpc.ProxyFactory$Adaptive.getProxy(ProxyFactory$Adaptive.java) ~[dubbo-3.2.12.jar:3.2.12]
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:505) ~[dubbo-3.2.12.jar:3.2.12]
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:369) ~[dubbo-3.2.12.jar:3.2.12]
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:238) ~[dubbo-3.2.12.jar:3.2.12]
	at org.apache.dubbo.config.ReferenceConfigBase.get(ReferenceConfigBase.java:395) ~[dubbo-3.2.12.jar:3.2.12]
	at org.apache.dubbo.config.utils.SimpleReferenceCache.destroyReference(SimpleReferenceCache.java:294) ~[dubbo-3.2.12.jar:3.2.12]
	at org.apache.dubbo.config.utils.SimpleReferenceCache.destroy(SimpleReferenceCache.java:248) ~[dubbo-3.2.12.jar:3.2.12]
	at org.apache.dubbo.config.utils.SimpleReferenceCache.destroy(SimpleReferenceCache.java:271) ~[dubbo-3.2.12.jar:3.2.12]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:555) ~[dubbo-3.2.12.jar:3.2.12]
	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780) ~[na:na]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:517) ~[dubbo-3.2.12.jar:3.2.12]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:183) ~[dubbo-3.2.12.jar:3.2.12]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:156) ~[dubbo-3.2.12.jar:3.2.12]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:157) ~[dubbo-3.2.12.jar:3.2.12]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:143) ~[dubbo-3.2.12.jar:3.2.12]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:52) ~[dubbo-3.2.12.jar:3.2.12]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:587) ~[spring-context-6.0.2.jar:6.0.2]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[spring-boot-3.0.0.jar:3.0.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[spring-boot-3.0.0.jar:3.0.0]
	at com.cloudart.author.UserAuthorzationApplication.main(UserAuthorzationApplication.java:13) ~[classes/:na]

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cloudarts** [comment]
<img width="820" alt="Snipaste_2024-05-16_14-19-44" src="https://github.com/apache/dubbo/assets/60880086/f8106b0d-69ad-43ec-b203-306a37793462">
