### ISSUE TITLE
[Bug]  通过网关将 http 流量接入 Dubbo 后端服务报错

### ISSUE THREAD

**Issue by kangzhaok** [apache/dubbo#14288]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

3.3.0-beta.3

### Steps to reproduce this issue

use 3.3.0-beta.3 both publish dubbo and tri protocol, use http call dubbo interface has a error.
java.lang.NoClassDefFoundError: io/netty/handler/codec/http/HttpDecoderConfig
	at org.apache.dubbo.rpc.protocol.tri.TripleHttp2Protocol.configurerHttp1Handlers(TripleHttp2Protocol.java:133) ~[dubbo-3.3.0-beta.3.jar:3.3.0-beta.3]
	at org.apache.dubbo.rpc.protocol.tri.TripleHttp2Protocol.configServerProtocolHandler(TripleHttp2Protocol.java:118) ~[dubbo-3.3.0-beta.3.jar:3.3.0-beta.3]
	at org.apache.dubbo.remoting.transport.netty4.NettyPortUnificationServerHandler.detectProtocol(NettyPortUnificationServerHandler.java:176) ~[dubbo-3.3.0-beta.3.jar:3.3.0-beta.3]
	at org.apache.dubbo.remoting.transport.netty4.NettyPortUnificationServerHandler.decode(NettyPortUnificationServerHandler.java:124) ~[dubbo-3.3.0-beta.3.jar:3.3.0-beta.3]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.87.Final.jar:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_401]
Caused by: java.lang.ClassNotFoundException: io.netty.handler.codec.http.HttpDecoderConfig
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[na:1.8.0_401]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_401]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:359) ~[na:1.8.0_401]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_401]
	... 23 common frames omitted

### What you expected to happen

use http call dubbo interface no error。 try use 3.3.0-beta.2 is right。
need upgrade netty-codec-http version to 4.1.107.Final

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by finefuture** [comment]
Please upgrade to the latest netty version.

**Comment by kangzhaok** [comment]
ok，i see latest code already upgrade to 4.1.109.Final ，i will close this issus
