### ISSUE TITLE
[Bug] tri protocol does not work properly in dubbo 3.3.0-beta.4-snapshot version

### ISSUE THREAD

**Issue by wcy666103** [apache/dubbo#14293]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

3.3.0-beta.4-snapshot 
jdk17
nacos 2.2.x

### Steps to reproduce this issue

run the dubbo-samples-sentinel in samples with dubbo 3.3.0-beta.4-snapshot 

and it can work in dubbo 3.3.0-beta.3

### What you expected to happen

work properly 

### Anything else

**by the way, the revision number is correct**

`
14:39:52.659 |-ERROR [main] o.registry.client.metadata.MetadataUtils:    -|  [DUBBO] Failed to get app metadata for revision 1d53f6fe82d9c731efd1e4cda6660570 for type local from instance 10.12.36.58:50052, dubbo version: 3.3.0-beta.4-SNAPSHOT, current host: 10.12.36.58, error code: 1-39. This may be caused by , go to https://dubbo.apache.org/faq/1/39 to find instructions. 
org.apache.dubbo.rpc.StatusRpcException: UNAVAILABLE : upstream 10.12.36.58:50052 is unavailable
	at org.apache.dubbo.rpc.TriRpcStatus.asException(TriRpcStatus.java:213) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.rpc.protocol.tri.TripleInvoker.doInvoke(TripleInvoker.java:139) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.doInvokeAndReturn(AbstractInvoker.java:249) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:192) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	... 60 more
Wrapped by: java.util.concurrent.ExecutionException: org.apache.dubbo.rpc.StatusRpcException: UNAVAILABLE : upstream 10.12.36.58:50052 is unavailable
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096) ~[?:?]
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:234) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:293) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	... 61 more
Wrapped by: org.apache.dubbo.rpc.RpcException: Fail to invoke remote method: getMetadataInfo, provider: tri://10.12.36.58:50052/org.apache.dubbo.metadata.MetadataService?connections=1&corethreads=2&dubbo=2.0.2&group=dubbo-springboot-demo-provider&ipv6=2001:250:480c:2717:67c:16ff:feb8:fb58&port=50052&prefer.serialization=hessian2,fastjson2&protocol=tri&release=3.3.0-beta.4-SNAPSHOT&retries=0&side=consumer&threadpool=cached&threads=100&timeout=5000&version=1.0.0, cause: org.apache.dubbo.rpc.StatusRpcException: UNAVAILABLE : upstream 10.12.36.58:50052 is unavailable
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:324) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:195) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.rpc.proxy.InvocationUtil.invoke(InvocationUtil.java:64) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:81) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.metadata.MetadataServiceDubboProxy1.getMetadataInfo(MetadataServiceDubboProxy1.java) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.registry.client.metadata.MetadataUtils.getRemoteMetadata(MetadataUtils.java:187) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.lambda$getRemoteMetadata$2(AbstractServiceDiscovery.java:249) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:84) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.getRemoteMetadata(AbstractServiceDiscovery.java:247) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.lambda$doOnEvent$2(ServiceInstancesChangedListener.java:172) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at java.base/java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.doOnEvent(ServiceInstancesChangedListener.java:172) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.onEvent(ServiceInstancesChangedListener.java:125) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribeURLs(ServiceDiscoveryRegistry.java:354) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.doSubscribe(ServiceDiscoveryRegistry.java:244) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribe(ServiceDiscoveryRegistry.java:195) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:87) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.registry.integration.DynamicDirectory.subscribe(DynamicDirectory.java:186) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.subscribe(ServiceDiscoveryRegistryDirectory.java:153) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.registry.integration.RegistryProtocol.doCreateInvoker(RegistryProtocol.java:640) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getServiceDiscoveryInvoker(InterfaceCompatibleRegistryProtocol.java:66) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshServiceDiscoveryInvoker(MigrationInvoker.java:458) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToApplicationFirstInvoker(MigrationInvoker.java:256) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.refreshInvoker(MigrationRuleHandler.java:90) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:71) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:285) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:603) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:567) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:548) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:83) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.rpc.protocol.ProtocolSecurityWrapper.refer(ProtocolSecurityWrapper.java:112) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:85) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:72) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:55) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.rpc.protocol.InvokerCountWrapper.refer(InvokerCountWrapper.java:48) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.config.ReferenceConfig.createInvoker(ReferenceConfig.java:672) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:502) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:383) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:244) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.config.utils.SimpleReferenceCache.get(SimpleReferenceCache.java:140) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:567) ~[dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780) [?:?]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:539) [dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:186) [dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:159) [dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:167) [dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:153) [dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:52) [dubbo-3.3.0-beta.4-20240531.125502-4.jar:3.3.0-beta.4-SNAPSHOT]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185) [spring-context-6.1.4.jar:6.1.4]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178) [spring-context-6.1.4.jar:6.1.4]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156) [spring-context-6.1.4.jar:6.1.4]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:451) [spring-context-6.1.4.jar:6.1.4]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:384) [spring-context-6.1.4.jar:6.1.4]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:981) [spring-context-6.1.4.jar:6.1.4]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:627) [spring-context-6.1.4.jar:6.1.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) [spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) [spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) [spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) [spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) [spring-boot-3.2.3.jar:3.2.3]
	at org.apache.dubbo.springboot.demo.consumer.ConsumerApplication.main(ConsumerApplication.java:29) [classes/:?]
`

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wcy666103** [comment]
dubbo-samples-sentinel、dubbo-samples-spring-boot、dubbo-samples-environment-keys、dubbo-samples-triple-rest-springmvc、dubbo-samples-nacos-registry、dubbo-samples-triple-rest-jaxrs **All modules failed to pass ci because of this problem**

**Comment by wcy666103** [comment]
`This was caused by an issue with netty's new api, and a fallback has been made to resolve the issue `
 https://github.com/apache/dubbo/pull/14294
