### ISSUE TITLE
[Bug] version 3.2.13 and version 2.6.7 gray release failed

### ISSUE THREAD

**Issue by xm101** [apache/dubbo#14386]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo 3.2.13 JDK8
Dubbo 2.6.7 JDK8

### Steps to reproduce this issue

Originally, there were 3 A services deployed in the cluster, with Dubbo version 2.6.7. Recently, an additional new version was restored and deployed, upgrading Dubbo to version 3.2.13

### What you expected to happen

start succ

### Anything else

start failed
msg：
2024.07.01 - 13:21:22 A 1.0.1 ERROR ?   traceId: tokenId: sessionId: -  [DUBBO] Failed to get app metadata for revision b37111c1dfaefc571822fffa5a69b267 for type local from instance [IP]:[PORT], dubbo version: 3
.2.13, current host: [IP], error code: 1-39. This may be caused by , go to https://dubbo.apache.org/faq/1/39 to find instructions. org.apache.dubbo.rpc.RpcException: Failed to invoke remote method: getMetadataInfo, provider: du
bbo://[IP]:[PORT]/org.apache.dubbo.metadata.MetadataService?connections=1&corethreads=2&dubbo=2.0.2&group=ztjy-family-server&port=[PORT]&prefer.serialization=fastjson2,hessian2&protocol=dubbo&release=3.2.13&retries=0&side=consume
r&threadpool=cached&threads=100&timeout=5000&version=1.0.0, cause: org.apache.dubbo.remoting.RemotingException: Fail to decode request due to: RpcInvocation [methodName=getMetadataInfo, parameterTypes=null]
        at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:311) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:194) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.rpc.proxy.InvocationUtil.invoke(InvocationUtil.java:64) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:81) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.metadata.MetadataServiceDubboProxy17.getMetadataInfo(MetadataServiceDubboProxy17.java) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.registry.client.metadata.MetadataUtils.getRemoteMetadata(MetadataUtils.java:182) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.registry.client.AbstractServiceDiscovery.lambda$getRemoteMetadata$2(AbstractServiceDiscovery.java:249) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:84) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.registry.client.AbstractServiceDiscovery.getRemoteMetadata(AbstractServiceDiscovery.java:247) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.lambda$doOnEvent$2(ServiceInstancesChangedListener.java:172) ~[dubbo-3.2.13.jar!/:3.2.13]
        at java.util.Optional.orElseGet(Optional.java:267) ~[?:1.8.0_202]
        at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.doOnEvent(ServiceInstancesChangedListener.java:172) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.onEvent(ServiceInstancesChangedListener.java:125) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribeURLs(ServiceDiscoveryRegistry.java:353) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.doSubscribe(ServiceDiscoveryRegistry.java:243) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribe(ServiceDiscoveryRegistry.java:194) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:87) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.registry.integration.DynamicDirectory.subscribe(DynamicDirectory.java:186) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.subscribe(ServiceDiscoveryRegistryDirectory.java:151) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.registry.integration.RegistryProtocol.doCreateInvoker(RegistryProtocol.java:639) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getServiceDiscoveryInvoker(InterfaceCompatibleRegistryProtocol.java:66) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshServiceDiscoveryInvoker(MigrationInvoker.java:458) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToApplicationFirstInvoker(MigrationInvoker.java:256) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.refreshInvoker(MigrationRuleHandler.java:78) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:62) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:285) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:602) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:566) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:547) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:85) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:83) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.rpc.protocol.ProtocolSecurityWrapper.refer(ProtocolSecurityWrapper.java:112) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:72) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:55) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.rpc.protocol.InvokerCountWrapper.refer(InvokerCountWrapper.java:48) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.config.ReferenceConfig.createInvoker(ReferenceConfig.java:656) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:486) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:370) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:238) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.config.utils.SimpleReferenceCache.get(SimpleReferenceCache.java:140) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:545) ~[dubbo-3.2.13.jar!/:3.2.13]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) ~[?:1.8.0_202]
        at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:517) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:183) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:156) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:157) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:143) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:52) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.27.jar!/:5.3.27]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.27.jar!/:5.3.27]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.27.jar!/:5.3.27]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.27.jar!/:5.3.27]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.27.jar!/:5.3.27]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:940) ~[spring-context-5.3.27.jar!/:5.3.27]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.27.jar!/:5.3.27]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.11.jar!/:2.7.11]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731) ~[spring-boot-2.7.11.jar!/:2.7.11]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.11.jar!/:2.7.11]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.7.11.jar!/:2.7.11]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.7.11.jar!/:2.7.11]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.7.11.jar!/:2.7.11]
        at com.ztjy.familyserver.MyApplication.main(MyApplication.java:24) ~[classes!/:1.6.0-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[app.jar:1.6.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[app.jar:1.6.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[app.jar:1.6.0-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[app.jar:1.6.0-SNAPSHOT]
Caused by: java.util.concurrent.ExecutionException: org.apache.dubbo.remoting.RemotingException: Fail to decode request due to: RpcInvocation [methodName=getMetadataInfo, parameterTypes=null]
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_202]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915) ~[?:1.8.0_202]
        at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:233) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:292) ~[dubbo-3.2.13.jar!/:3.2.13]
        ... 70 more
Caused by: org.apache.dubbo.remoting.RemotingException: Fail to decode request due to: RpcInvocation [methodName=getMetadataInfo, parameterTypes=null]
        at org.apache.dubbo.remoting.exchange.support.DefaultFuture.doReceived(DefaultFuture.java:265) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:208) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:196) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleResponse(HeaderExchangeHandler.java:65) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:211) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:64) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.common.threadpool.ThreadlessExecutor$RunnableWrapper.run(ThreadlessExecutor.java:151) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:77) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:219) ~[dubbo-3.2.13.jar!/:3.2.13]
        at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:292) ~[dubbo-3.2.13.jar!/:3.2.13]
        ... 70 more

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wcy666103** [comment]
Please redescribe in English and submit error messages whenever possible.

**Comment by xm101** [comment]
会报错，但不影响启动，启动是我们自己配置的问题

**Comment by AlbumenJ** [comment]
Please submit the issue in ENGLISH **only** :)
