### ISSUE TITLE
Based on the CRAC backup dubbo program fail

### ISSUE THREAD

**Issue by yangzehan** [apache/dubbo#14447]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

3.3.0-beta.4

### Steps to reproduce this issue

Use CRAC to back up the Dubbo application
 jcmd demo-0.0.1-SNAPSHOT.jar 

### What you expected to happen

Normal backup

### Anything else

jdk.crac.CheckpointException
        Suppressed: java.nio.channels.IllegalSelectorException
                at java.base/sun.nio.ch.EPollSelectorImpl.beforeCheckpoint(EPollSelectorImpl.java:401)
                at java.base/jdk.crac.impl.AbstractContext.invokeBeforeCheckpoint(AbstractContext.java:44)
                at java.base/jdk.crac.impl.AbstractContext.beforeCheckpoint(AbstractContext.java:59)
                at java.base/jdk.crac.impl.BlockingOrderedContext.beforeCheckpoint(BlockingOrderedContext.java:40)
                at java.base/jdk.crac.impl.AbstractContext.invokeBeforeCheckpoint(AbstractContext.java:44)
                at java.base/jdk.crac.impl.AbstractContext.beforeCheckpoint(AbstractContext.java:59)
                at java.base/jdk.crac.Core.checkpointRestore1(Core.java:158)
                at java.base/jdk.crac.Core.checkpointRestore(Core.java:299)
                at java.base/jdk.crac.Core.checkpointRestoreInternal(Core.java:312)
        Suppressed: java.nio.channels.IllegalSelectorException
                at java.base/sun.nio.ch.EPollSelectorImpl.beforeCheckpoint(EPollSelectorImpl.java:401)
                at java.base/jdk.crac.impl.AbstractContext.invokeBeforeCheckpoint(AbstractContext.java:44)
                at java.base/jdk.crac.impl.AbstractContext.beforeCheckpoint(AbstractContext.java:59)
                at java.base/jdk.crac.impl.BlockingOrderedContext.beforeCheckpoint(BlockingOrderedContext.java:40)
                at java.base/jdk.crac.impl.AbstractContext.invokeBeforeCheckpoint(AbstractContext.java:44)
                at java.base/jdk.crac.impl.AbstractContext.beforeCheckpoint(AbstractContext.java:59)
                at java.base/jdk.crac.Core.checkpointRestore1(Core.java:158)
                at java.base/jdk.crac.Core.checkpointRestore(Core.java:299)
                at java.base/jdk.crac.Core.checkpointRestoreInternal(Core.java:312)
        Suppressed: java.nio.channels.IllegalSelectorException
                at java.base/sun.nio.ch.EPollSelectorImpl.beforeCheckpoint(EPollSelectorImpl.java:401)
                at java.base/jdk.crac.impl.AbstractContext.invokeBeforeCheckpoint(AbstractContext.java:44)
                at java.base/jdk.crac.impl.AbstractContext.beforeCheckpoint(AbstractContext.java:59)
                at java.base/jdk.crac.impl.BlockingOrderedContext.beforeCheckpoint(BlockingOrderedContext.java:40)
                at java.base/jdk.crac.impl.AbstractContext.invokeBeforeCheckpoint(AbstractContext.java:44)
                at java.base/jdk.crac.impl.AbstractContext.beforeCheckpoint(AbstractContext.java:59)
                at java.base/jdk.crac.Core.checkpointRestore1(Core.java:158)
                at java.base/jdk.crac.Core.checkpointRestore(Core.java:299)
                at java.base/jdk.crac.Core.checkpointRestoreInternal(Core.java:312)
        Suppressed: jdk.crac.impl.CheckpointOpenSocketException: java.nio.channels.SocketChannel[connected local=/172.17.0.2:54590 remote=/192.168.10.10:9848]
                at java.base/jdk.internal.crac.JDKSocketResourceBase.lambda$beforeCheckpoint$0(JDKSocketResourceBase.java:44)
                at java.base/jdk.crac.Core.checkpointRestore1(Core.java:174)
                at java.base/jdk.crac.Core.checkpointRestore(Core.java:299)
                at java.base/jdk.crac.Core.checkpointRestoreInternal(Core.java:312)
        Suppressed: jdk.crac.impl.CheckpointOpenSocketException: sun.nio.ch.ServerSocketChannelImpl[/[0:0:0:0:0:0:0:0]:8080]
                at java.base/jdk.internal.crac.JDKSocketResourceBase.lambda$beforeCheckpoint$0(JDKSocketResourceBase.java:44)
                at java.base/jdk.crac.Core.checkpointRestore1(Core.java:174)
                at java.base/jdk.crac.Core.checkpointRestore(Core.java:299)
                at java.base/jdk.crac.Core.checkpointRestoreInternal(Core.java:312)
        Suppressed: jdk.crac.impl.CheckpointOpenSocketException: java.nio.channels.SocketChannel[connected local=/172.17.0.2:54594 remote=/192.168.10.10:9848]
                at java.base/jdk.internal.crac.JDKSocketResourceBase.lambda$beforeCheckpoint$0(JDKSocketResourceBase.java:44)
                at java.base/jdk.crac.Core.checkpointRestore1(Core.java:174)
                at java.base/jdk.crac.Core.checkpointRestore(Core.java:299)
                at java.base/jdk.crac.Core.checkpointRestoreInternal(Core.java:312)
        Suppressed: jdk.crac.impl.CheckpointOpenSocketException: sun.nio.ch.ServerSocketChannelImpl[/[0:0:0:0:0:0:0:0]:22222]
                at java.base/jdk.internal.crac.JDKSocketResourceBase.lambda$beforeCheckpoint$0(JDKSocketResourceBase.java:44)
                at java.base/jdk.crac.Core.checkpointRestore1(Core.java:174)
                at java.base/jdk.crac.Core.checkpointRestore(Core.java:299)
                at java.base/jdk.crac.Core.checkpointRestoreInternal(Core.java:312)
        Suppressed: jdk.crac.impl.CheckpointOpenFileException: /root/.dubbo/.metadata.DemoApplication.nacos.192.168.10.10%003a8848.dubbo.cache.lock
                at java.base/jdk.internal.crac.JDKFileResource.lambda$beforeCheckpoint$1(JDKFileResource.java:89)
                at java.base/jdk.crac.Core.checkpointRestore1(Core.java:174)
                at java.base/jdk.crac.Core.checkpointRestore(Core.java:299)
                at java.base/jdk.crac.Core.checkpointRestoreInternal(Core.java:312)
        Suppressed: jdk.crac.impl.CheckpointOpenSocketException: java.nio.channels.SocketChannel[connected local=/172.17.0.2:54598 remote=/192.168.10.10:9848]
                at java.base/jdk.internal.crac.JDKSocketResourceBase.lambda$beforeCheckpoint$0(JDKSocketResourceBase.java:44)
                at java.base/jdk.crac.Core.checkpointRestore1(Core.java:174)
                at java.base/jdk.crac.Core.checkpointRestore(Core.java:299)
                at java.base/jdk.crac.Core.checkpointRestoreInternal(Core.java:312)
        Suppressed: jdk.crac.impl.CheckpointOpenSocketException: sun.nio.ch.ServerSocketChannelImpl[/[0:0:0:0:0:0:0:0]:50051]
                at java.base/jdk.internal.crac.JDKSocketResourceBase.lambda$beforeCheckpoint$0(JDKSocketResourceBase.java:44)
                at java.base/jdk.crac.Core.checkpointRestore1(Core.java:174)
                at java.base/jdk.crac.Core.checkpointRestore(Core.java:299)
                at java.base/jdk.crac.Core.checkpointRestoreInternal(Core.java:312)
        Suppressed: jdk.crac.impl.CheckpointOpenFileException: /root/.dubbo/.mapping.DemoApplication.dubbo.cache.lock
                at java.base/jdk.internal.crac.JDKFileResource.lambda$beforeCheckpoint$1(JDKFileResource.java:89)
                at java.base/jdk.crac.Core.checkpointRestore1(Core.java:174)
                at java.base/jdk.crac.Core.checkpointRestore(Core.java:299)
                at java.base/jdk.crac.Core.checkpointRestoreInternal(Core.java:312)
        Suppressed: jdk.crac.impl.CheckpointOpenSocketException: java.nio.channels.SocketChannel[connected local=/172.17.0.2:54602 remote=/192.168.10.10:9848]
                at java.base/jdk.internal.crac.JDKSocketResourceBase.lambda$beforeCheckpoint$0(JDKSocketResourceBase.java:44)
                at java.base/jdk.crac.Core.checkpointRestore1(Core.java:174)
                at java.base/jdk.crac.Core.checkpointRestore(Core.java:299)
                at java.base/jdk.crac.Core.checkpointRestoreInternal(Core.java:312)
        Suppressed: jdk.crac.impl.CheckpointOpenResourceException: FD fd=10 type=unknown path=anon_inode:[eventpoll]
                at java.base/jdk.crac.Core.translateJVMExceptions(Core.java:122)
                at java.base/jdk.crac.Core.checkpointRestore1(Core.java:192)
                at java.base/jdk.crac.Core.checkpointRestore(Core.java:299)
                at java.base/jdk.crac.Core.checkpointRestoreInternal(Core.java:312)
        Suppressed: jdk.crac.impl.CheckpointOpenResourceException: FD fd=11 type=unknown path=anon_inode:[eventfd]
                at java.base/jdk.crac.Core.translateJVMExceptions(Core.java:122)
                at java.base/jdk.crac.Core.checkpointRestore1(Core.java:192)
                at java.base/jdk.crac.Core.checkpointRestore(Core.java:299)
                at java.base/jdk.crac.Core.checkpointRestoreInternal(Core.java:312)
        Suppressed: jdk.crac.impl.CheckpointOpenResourceException: FD fd=19 type=unknown path=anon_inode:[eventpoll]
                at java.base/jdk.crac.Core.translateJVMExceptions(Core.java:122)
                at java.base/jdk.crac.Core.checkpointRestore1(Core.java:192)
                at java.base/jdk.crac.Core.checkpointRestore(Core.java:299)
                at java.base/jdk.crac.Core.checkpointRestoreInternal(Core.java:312)
        Suppressed: jdk.crac.impl.CheckpointOpenResourceException: FD fd=20 type=unknown path=anon_inode:[eventfd]
                at java.base/jdk.crac.Core.translateJVMExceptions(Core.java:122)
                at java.base/jdk.crac.Core.checkpointRestore1(Core.java:192)
                at java.base/jdk.crac.Core.checkpointRestore(Core.java:299)
                at java.base/jdk.crac.Core.checkpointRestoreInternal(Core.java:312)
        Suppressed: jdk.crac.impl.CheckpointOpenResourceException: FD fd=30 type=unknown path=anon_inode:[eventpoll]
                at java.base/jdk.crac.Core.translateJVMExceptions(Core.java:122)
                at java.base/jdk.crac.Core.checkpointRestore1(Core.java:192)
                at java.base/jdk.crac.Core.checkpointRestore(Core.java:299)
                at java.base/jdk.crac.Core.checkpointRestoreInternal(Core.java:312)
        Suppressed: jdk.crac.impl.CheckpointOpenResourceException: FD fd=31 type=unknown path=anon_inode:[eventfd]
                at java.base/jdk.crac.Core.translateJVMExceptions(Core.java:122)
                at java.base/jdk.crac.Core.checkpointRestore1(Core.java:192)
                at java.base/jdk.crac.Core.checkpointRestore(Core.java:299)
                at java.base/jdk.crac.Core.checkpointRestoreInternal(Core.java:312)

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
Dubbo can't work with CRAC now. Dubbo should have the ability to save the status of network I/O and filesystem I/O to support it
