### ISSUE TITLE
[Bug]  When I use @DubboReference to make a call it starts with an error log, but it doesn't affect the use of the

### ISSUE THREAD

**Issue by Ineffable919** [apache/dubbo#14542]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

dubbo 3.2 any version of jdk8 17 exists macos 14.5

### Steps to reproduce this issue

When I make an rpc call using @DubboReference at the consumer, the consumer starts with the following error log, but the service runs normally
```
2024-08-15 15:45:33.564 ERROR 12777 --- [ main] o.a.d.r.p.ProtocolSecurityWrapper : [DUBBO] Failed to register interface for security check, dubbo version: 3.2.15, current host: 192.168.2.52, error code: 99-0. This may be caused by , go to https://dubbo.apache.org/faq/99/0 to find instructions.

java.lang.TypeNotPresentException: Type kotlin.reflect.KProperty1 not present
at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117) ~[na:na]
at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125) ~[na:na]
at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[na:na]
at java.base/sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68) ~[na:na]
at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138) ~[na:na]
at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[na:na]
at java.base/sun.reflect.generics.repository.ClassRepository.computeSuperInterfaces(ClassRepository.java:117) ~[na:na]
at java.base/sun.reflect.generics.repository.ClassRepository.getSuperInterfaces(ClassRepository.java:95) ~[na:na]
at java.base/java.lang.Class.getGenericInterfaces(Class.java:1211) ~[na:na]
at org.apache.dubbo.common.utils.SerializeSecurityConfigurator.checkClass(SerializeSecurityConfigurator.java:312) ~[dubbo-3.2.15.jar:3.2.15]
at org.apache.dubbo.common.utils.SerializeSecurityConfigurator.registerInterface(SerializeSecurityConfigurator.java:228) ~[dubbo-3.2.15.jar:3.2.15]
at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[na:na]
at org.apache.dubbo.rpc.protocol.ProtocolSecurityWrapper.refer(ProtocolSecurityWrapper.java:101) ~[dubbo-3.2.15.jar:3.2.15]
at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:83) ~[dubbo-3.2.15.jar:3.2.15]
at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:85) ~[dubbo-3.2.15.jar:3.2.15]
at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:72) ~[dubbo-3.2.15.jar:3.2.15]
at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:55) ~[dubbo-3.2.15.jar:3.2.15]
at org.apache.dubbo.rpc.protocol.InvokerCountWrapper.refer(InvokerCountWrapper.java:48) ~[dubbo-3.2.15.jar:3.2.15]
at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java) ~[dubbo-3.2.15.jar:3.2.15]
at org.apache.dubbo.config.ReferenceConfig.createInvoker(ReferenceConfig.java:656) ~[dubbo-3.2.15.jar:3.2.15]
at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:486) ~[dubbo-3.2.15.jar:3.2.15]
at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:370) ~[dubbo-3.2.15.jar:3.2.15]
at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:238) ~[dubbo-3.2.15.jar:3.2.15]
at org.apache.dubbo.config.utils.SimpleReferenceCache.get(SimpleReferenceCache.java:140) ~[dubbo-3.2.15.jar:3.2.15]
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:545) ~[dubbo-3.2.15.jar:3.2.15]
at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780) ~[na:na]
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:517) ~[dubbo-3.2.15.jar:3.2.15]
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:183) ~[dubbo-3.2.15.jar:3.2.15]
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:156) ~[dubbo-3.2.15.jar:3.2.15]
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:157) ~[dubbo-3.2.15.jar:3.2.15]
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:143) ~[dubbo-3.2.15.jar:3.2.15]
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:52) ~[dubbo-3.2.15.jar:3.2.15]
at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178) ~[spring-context-5.3.31.jar:5.3.31]
at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171) ~[spring-context-5.3.31.jar:5.3.31]
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145) ~[spring-context-5.3.31.jar:5.3.31]
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:429) ~[spring-context-5.3.31.jar:5.3.31]
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:386) ~[spring-context-5.3.31.jar:5.3.31]
at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:949) ~[spring-context-5.3.31.jar:5.3.31]
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:594) ~[spring-context-5.3.31.jar:5.3.31]
at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.18.jar:2.7.18]
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[spring-boot-2.7.18.jar:2.7.18]
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409) ~[spring-boot-2.7.18.jar:2.7.18]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.18.jar:2.7.18]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) ~[spring-boot-2.7.18.jar:2.7.18]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289) ~[spring-boot-2.7.18.jar:2.7.18]
at com.crown.shadow.msg.ShadowMsgApplication.main(ShadowMsgApplication.java:17) ~[classes/:na]
Caused by: java.lang.ClassNotFoundException: kotlin.reflect.KProperty1
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[na:na]
at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
at java.base/java.lang.Class.forName(Class.java:467) ~[na:na]
at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114) ~[na:na]
... 45 common frames omitted
```
Just remove the @DubboReference annotation and it will be normal

### What you expected to happen

Consumers start without error logs

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
![image](https://github.com/user-attachments/assets/4edf35cd-3751-42c4-a42f-a5ae02c6c304)

**Comment by Ineffable919** [comment]
> ![image](https://private-user-images.githubusercontent.com/9292748/359718459-4edf35cd-3751-42c4-a42f-a5ae02c6c304.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMjk3NzMsIm5iZiI6MTcyNDIyOTQ3MywicGF0aCI6Ii85MjkyNzQ4LzM1OTcxODQ1OS00ZWRmMzVjZC0zNzUxLTQyYzQtYTQyZi1hNWFlMDJjNmMzMDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjFUMDgzNzUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTkxMjE0MzM3NzI1YTI4ODEwNDg2YzJhMDBiN2VkYTA4NzRjM2UyZjFiYzNkNmY2YjA3YzA2ZTAwM2YwODg5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1zMZfRb7tSap6UBN3NhacpLxm1XfW7yIB1kL1CdD0Xs)

What should I do?

**Comment by xiohuchi** [comment]
同问
