### ISSUE TITLE
[Bug] java.lang.IllegalStateException: Duplicate extension org.apache.dubbo.common.extension.ExtensionInjector name spi

### ISSUE THREAD

**Issue by hexinwei1** [apache/dubbo#14620]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

dubbo java: 3.2.15  dubbo-serialization-protobuf:2.7.20  JDK: 17 

### Steps to reproduce this issue

Caused by: java.lang.IllegalStateException: Duplicate extension org.apache.dubbo.common.extension.ExtensionInjector name spi on org.apache.dubbo.common.extension.inject.SpiExtensionInjector and org.apache.dubbo.common.extension.factory.SpiExtensionFactory
	at org.apache.dubbo.common.extension.ExtensionLoader.saveInExtensionClass(ExtensionLoader.java:1351)
	at org.apache.dubbo.common.extension.ExtensionLoader.loadClass(ExtensionLoader.java:1296)
	at org.apache.dubbo.common.extension.ExtensionLoader.loadResource(ExtensionLoader.java:1158)
	... 27 more

	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:766)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:773)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:573)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:547)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:3064)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.apache.dubbo.common.extension.inject.AdaptiveExtensionInjector.initialize(AdaptiveExtensionInjector.java:51)
	at org.apache.dubbo.common.extension.ExtensionLoader.initExtension(ExtensionLoader.java:910)
	at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtension(ExtensionLoader.java:1434)
	... 17 more

### What you expected to happen

serialization: protobuf, Duplicate extension org.apache.dubbo.common.extension.ExtensionInjector name spi
spi=org.apache.dubbo.common.extension.factory.SpiExtensionFactory
spi=org.apache.dubbo.common.extension.inject.SpiExtensionInjector

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
You should use `org.apache.dubbo.extensions:dubbo-serialization-protobuf` instead

```xml
<dependency>
    <groupId>org.apache.dubbo.extensions</groupId>
    <artifactId>dubbo-serialization-protobuf</artifactId>
    <version>3.2.0</version>
</dependency>
```

**Comment by hexinwei1** [comment]
邮件已收到！

**Comment by wcy666103** [comment]
Some extension has been unified moved to the rep: https://github.com/apache/dubbo-spi-extensions

You can find the extension you want here.

Please close this issue.

**Comment by hexinwei1** [comment]
邮件已收到！
