### ISSUE TITLE
[Bug] Demo dubbo-demo-triple  consumer run with timeout exception.

### ISSUE THREAD

**Issue by zhangcunli** [apache/dubbo#14788]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo Java 3.3

### Steps to reproduce this issue

1. dubbo version: 3.3;  mac: Darwin zzzMacBook-Pro-M1.local 23.0.0
2. Step 1: `cd dubbo-demo` and `mvn clean package -Dmaven.test.skip=true` 
3. Step 2: In demo dubbo-demo-triple, I use run IDEA run the ApiProvider.main。
4. Step 3: Then I use run IDEA run the ApiConsumer.main.
Look the following screenshot:
<img width="1390" alt="image" src="https://github.com/user-attachments/assets/0ed313f2-81a7-44dd-8278-8fb4b0c4647a">

5.Exception stack:
```
14:15:28.668 |-INFO  [main] ient.metadata.MetadataServiceNameMapping:105 -|  [DUBBO] Local cache mapping is empty, dubbo version: , current host: 10.251.1.1
14:15:28.674 |-INFO  [main] registry.client.ServiceDiscoveryRegistry:341 -|  [DUBBO] Trying to subscribe from apps dubbo-demo-triple-api-provider for service key org.apache.dubbo.demo.GreeterService, , dubbo version: , current host: 10.251.1.1
14:15:28.675 |-INFO  [main-EventThread] DiscoveryRegistry$DefaultMappingListener:414 -|  [DUBBO] Received mapping notification from meta server, {serviceKey: org.apache.dubbo.demo.GreeterService, apps: [dubbo-demo-triple-api-provider]}, dubbo version: , current host: 10.251.1.1
14:15:28.675 |-INFO  [main-EventThread] DiscoveryRegistry$DefaultMappingListener:431 -|  [DUBBO] Mapping of service org.apache.dubbo.demo.GreeterServicechanged from null to [dubbo-demo-triple-api-provider], dubbo version: , current host: 10.251.1.1
14:15:28.675 |-INFO  [main-EventThread] registry.client.ServiceDiscoveryRegistry:341 -|  [DUBBO] Trying to subscribe from apps dubbo-demo-triple-api-provider for service key org.apache.dubbo.demo.GreeterService, , dubbo version: , current host: 10.251.1.1
14:15:28.721 |-INFO  [main] listener.ServiceInstancesChangedListener:349 -|  [DUBBO] Received instance notification, serviceName: dubbo-demo-triple-api-provider, instances: 1, dubbo version: , current host: 10.251.1.1
14:15:28.872 |-INFO  [main]   org.apache.dubbo.rpc.model.ModuleModel:212 -|  [DUBBO] Dynamically registering consumer model dubbo-demo-triple-api-provider/org.apache.dubbo.metadata.MetadataServiceV2:2.0.0 into model Dubbo Module[1.1.0], dubbo version: , current host: 10.251.1.1
14:15:33.919 |-WARN  [main] dubbo.rpc.proxy.InvokerInvocationHandler:    -|  [DUBBO] [Dubbo-Consumer] execute service dubbo-demo-triple-api-provider/org.apache.dubbo.metadata.MetadataServiceV2:2.0.0:tri#GetMetadataInfo cost 5033.162542 ms, this invocation almost (maybe already) timeout. Timeout: 5000ms
invocation context:
timeout=5000;
group=dubbo-demo-triple-api-provider;
thread info: 
Start time: 2219890168094333
+-[ Offset: 0.000000ms; Usage: 5033.162542ms, 100% ] Receive request. Client invoke begin. ServiceKey: dubbo-demo-triple-api-provider/org.apache.dubbo.metadata.MetadataServiceV2:2.0.0 MethodName:GetMetadataInfo, dubbo version: , current host: 10.251.1.1, error code: 3-4. This may be caused by , go to https://dubbo.apache.org/faq/3/4 to find instructions. 
14:15:33.920 |-ERROR [main] o.registry.client.metadata.MetadataUtils:    -|  [DUBBO] Failed to get app metadata for revision 6e283032d615a7f6f3fe4be6dcfb23c6 for type local from instance 10.251.1.1:50051, dubbo version: , current host: 10.251.1.1, error code: 1-39. This may be caused by , go to https://dubbo.apache.org/faq/1/39 to find instructions. 
org.apache.dubbo.rpc.StatusRpcException: DEADLINE_EXCEEDED : Waiting server-side response timeout by scan timer. start time: 2024-10-17 14:15:28.887, end time: 2024-10-17 14:15:33.912, timeout: 5000 ms, service: org.apache.dubbo.metadata.MetadataServiceV2, method: GetMetadataInfo
    at org.apache.dubbo.rpc.TriRpcStatus.asException(TriRpcStatus.java:260) ~[classes/:?]
    at org.apache.dubbo.rpc.protocol.tri.DeadlineFuture$TimeoutCheckTask.notifyTimeout(DeadlineFuture.java:162) ~[classes/:?]
    at org.apache.dubbo.rpc.protocol.tri.DeadlineFuture$TimeoutCheckTask.lambda$run$0(DeadlineFuture.java:149) ~[classes/:?]
    at org.apache.dubbo.common.threadpool.ThreadlessExecutor$RunnableWrapper.run(ThreadlessExecutor.java:151) ~[classes/:?]
    at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:77) ~[classes/:?]
    at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:220) ~[classes/:?]
    at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:293) ~[classes/:?]
    at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:195) ~[classes/:?]
    at org.apache.dubbo.rpc.proxy.InvocationUtil.invoke(InvocationUtil.java:64) ~[classes/:?]
    at org.apache.dubbo.rpc.stub.StubInvocationUtil.call(StubInvocationUtil.java:64) ~[classes/:?]
    at org.apache.dubbo.rpc.stub.StubInvocationUtil.unaryCall(StubInvocationUtil.java:29) ~[classes/:?]
    at org.apache.dubbo.metadata.DubboMetadataServiceV2Triple$MetadataServiceV2Stub.getMetadataInfo(DubboMetadataServiceV2Triple.java:114) ~[classes/:?]
    at org.apache.dubbo.registry.client.metadata.MetadataUtils$RemoteMetadataService.getRemoteMetadata(MetadataUtils.java:370) ~[classes/:?]
    at org.apache.dubbo.registry.client.metadata.MetadataUtils.getRemoteMetadata(MetadataUtils.java:258) ~[classes/:?]
    at org.apache.dubbo.registry.client.AbstractServiceDiscovery.lambda$getRemoteMetadata$2(AbstractServiceDiscovery.java:254) ~[classes/:?]
    at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:84) ~[classes/:?]
    at org.apache.dubbo.registry.client.AbstractServiceDiscovery.getRemoteMetadata(AbstractServiceDiscovery.java:252) ~[classes/:?]
    at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.lambda$doOnEvent$2(ServiceInstancesChangedListener.java:172) ~[classes/:?]
    at java.base/java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
    at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.doOnEvent(ServiceInstancesChangedListener.java:172) ~[classes/:?]
    at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.onEvent(ServiceInstancesChangedListener.java:125) ~[classes/:?]
    at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribeURLs(ServiceDiscoveryRegistry.java:354) ~[classes/:?]
    at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.doSubscribe(ServiceDiscoveryRegistry.java:244) ~[classes/:?]
    at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribe(ServiceDiscoveryRegistry.java:195) ~[classes/:?]
    at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:87) ~[classes/:?]
    at org.apache.dubbo.registry.integration.DynamicDirectory.subscribe(DynamicDirectory.java:186) ~[classes/:?]
    at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.subscribe(ServiceDiscoveryRegistryDirectory.java:153) ~[classes/:?]
    at org.apache.dubbo.registry.integration.RegistryProtocol.doCreateInvoker(RegistryProtocol.java:666) ~[classes/:?]
    at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getServiceDiscoveryInvoker(InterfaceCompatibleRegistryProtocol.java:66) ~[classes/:?]
    at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshServiceDiscoveryInvoker(MigrationInvoker.java:458) ~[classes/:?]
    at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToApplicationFirstInvoker(MigrationInvoker.java:256) ~[classes/:?]
    at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.refreshInvoker(MigrationRuleHandler.java:90) ~[classes/:?]
    at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:71) ~[classes/:?]
    at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:285) ~[classes/:?]
    at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:629) ~[classes/:?]
    at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:593) ~[classes/:?]
    at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:574) ~[classes/:?]
    at org.apache.dubbo.rpc.protocol.ProtocolSecurityWrapper.refer(ProtocolSecurityWrapper.java:112) ~[classes/:?]
    at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:83) ~[classes/:?]
    at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:72) ~[classes/:?]
    at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:55) ~[classes/:?]
    at org.apache.dubbo.rpc.protocol.InvokerCountWrapper.refer(InvokerCountWrapper.java:48) ~[classes/:?]
    at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java) ~[classes/:?]
    at org.apache.dubbo.config.ReferenceConfig.createInvoker(ReferenceConfig.java:672) ~[classes/:?]
    at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:502) ~[classes/:?]
    at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:383) ~[classes/:?]
    at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:244) ~[classes/:?]
    at org.apache.dubbo.config.utils.SimpleReferenceCache.get(SimpleReferenceCache.java:140) ~[classes/:?]
    at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:567) ~[classes/:?]
    at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780) [?:?]
    at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:539) [classes/:?]
    at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:186) [classes/:?]
    at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:159) [classes/:?]
    at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.startModules(DefaultApplicationDeployer.java:771) [classes/:?]
    at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.doStart(DefaultApplicationDeployer.java:735) [classes/:?]
    at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.start(DefaultApplicationDeployer.java:708) [classes/:?]
    at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:230) [classes/:?]
    at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:219) [classes/:?]
    at org.apache.dubbo.demo.consumer.ApiConsumer.main(ApiConsumer.java:53) [classes/:?]
14:15:34.935 |-INFO  [main]   org.apache.dubbo.rpc.model.ModuleModel:212 -|  [DUBBO] Dynamically registering consumer model dubbo-demo-triple-api-provider/org.apache.dubbo.metadata.MetadataServiceV2:2.0.0 into model Dubbo Module[1.1.0], dubbo version: , current host: 10.251.1.1
14:15:39.946 |-WARN  [main] dubbo.rpc.proxy.InvokerInvocationHandler:    -|  [DUBBO] [Dubbo-Consumer] execute service dubbo-demo-triple-api-provider/org.apache.dubbo.metadata.MetadataServiceV2:2.0.0:tri#GetMetadataInfo cost 5007.212208 ms, this invocation almost (maybe already) timeout. Timeout: 5000ms
invocation context:
timeout=5000;
group=dubbo-demo-triple-api-provider;
thread info: 
Start time: 2219896222520750
+-[ Offset: 0.000000ms; Usage: 5007.212208ms, 100% ] Receive request. Client invoke begin. ServiceKey: dubbo-demo-triple-api-provider/org.apache.dubbo.metadata.MetadataServiceV2:2.0.0 MethodName:GetMetadataInfo, dubbo version: , current host: 10.251.1.1, error code: 3-4. This may be caused by , go to https://dubbo.apache.org/faq/3/4 to find instructions. 
14:15:39.947 |-ERROR [main] o.registry.client.metadata.MetadataUtils:    -|  [DUBBO] Failed to get app metadata for revision 6e283032d615a7f6f3fe4be6dcfb23c6 for type local from instance 10.251.1.1:50051, dubbo version: , current host: 10.251.1.1, error code: 1-39. This may be caused by , go to https://dubbo.apache.org/faq/1/39 to find instructions. 
java.util.concurrent.TimeoutException: Timeout after 5000ms waiting for result.
    at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:223) ~[classes/:?]
    at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:293) ~[classes/:?]
    ... 52 more
Wrapped by: org.apache.dubbo.rpc.RpcException: Invoke remote method timeout. method: GetMetadataInfo, provider: tri://10.251.1.1:50051/org.apache.dubbo.metadata.MetadataServiceV2?check=false&connections=1&corethreads=2&dubbo=2.0.2&group=dubbo-demo-triple-api-provider&port=50051&prefer.serialization=hessian2,fastjson2&protocol=tri&proxy=nativestub&retries=0&side=consumer&threadpool=cached&threads=100&timeout=5000&version=2.0.0, cause: Timeout after 5000ms waiting for result.
    at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:331) ~[classes/:?]
    at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:195) ~[classes/:?]
    at org.apache.dubbo.rpc.proxy.InvocationUtil.invoke(InvocationUtil.java:64) ~[classes/:?]
    at org.apache.dubbo.rpc.stub.StubInvocationUtil.call(StubInvocationUtil.java:64) ~[classes/:?]
    at org.apache.dubbo.rpc.stub.StubInvocationUtil.unaryCall(StubInvocationUtil.java:29) ~[classes/:?]
    at org.apache.dubbo.metadata.DubboMetadataServiceV2Triple$MetadataServiceV2Stub.getMetadataInfo(DubboMetadataServiceV2Triple.java:114) ~[classes/:?]
    at org.apache.dubbo.registry.client.metadata.MetadataUtils$RemoteMetadataService.getRemoteMetadata(MetadataUtils.java:370) ~[classes/:?]
    at org.apache.dubbo.registry.client.metadata.MetadataUtils.getRemoteMetadata(MetadataUtils.java:258) ~[classes/:?]
    at org.apache.dubbo.registry.client.AbstractServiceDiscovery.lambda$getRemoteMetadata$2(AbstractServiceDiscovery.java:254) ~[classes/:?]
    at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:84) ~[classes/:?]
    at org.apache.dubbo.registry.client.AbstractServiceDiscovery.getRemoteMetadata(AbstractServiceDiscovery.java:252) ~[classes/:?]
    at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.lambda$doOnEvent$2(ServiceInstancesChangedListener.java:172) ~[classes/:?]
    at java.base/java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
    at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.doOnEvent(ServiceInstancesChangedListener.java:172) ~[classes/:?]
    at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.onEvent(ServiceInstancesChangedListener.java:125) ~[classes/:?]
    at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribeURLs(ServiceDiscoveryRegistry.java:354) ~[classes/:?]
    at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.doSubscribe(ServiceDiscoveryRegistry.java:244) ~[classes/:?]
    at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribe(ServiceDiscoveryRegistry.java:195) ~[classes/:?]
    at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:87) ~[classes/:?]
    at org.apache.dubbo.registry.integration.DynamicDirectory.subscribe(DynamicDirectory.java:186) ~[classes/:?]
    at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.subscribe(ServiceDiscoveryRegistryDirectory.java:153) ~[classes/:?]
    at org.apache.dubbo.registry.integration.RegistryProtocol.doCreateInvoker(RegistryProtocol.java:666) ~[classes/:?]
    at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getServiceDiscoveryInvoker(InterfaceCompatibleRegistryProtocol.java:66) ~[classes/:?]
    at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshServiceDiscoveryInvoker(MigrationInvoker.java:458) ~[classes/:?]
    at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToApplicationFirstInvoker(MigrationInvoker.java:256) ~[classes/:?]
    at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.refreshInvoker(MigrationRuleHandler.java:90) ~[classes/:?]
    at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:71) ~[classes/:?]
    at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:285) ~[classes/:?]
    at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:629) ~[classes/:?]
    at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:593) ~[classes/:?]
    at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:574) ~[classes/:?]
    at org.apache.dubbo.rpc.protocol.ProtocolSecurityWrapper.refer(ProtocolSecurityWrapper.java:112) ~[classes/:?]
    at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:83) ~[classes/:?]
    at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:72) ~[classes/:?]
    at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:55) ~[classes/:?]
    at org.apache.dubbo.rpc.protocol.InvokerCountWrapper.refer(InvokerCountWrapper.java:48) ~[classes/:?]
    at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java) ~[classes/:?]
    at org.apache.dubbo.config.ReferenceConfig.createInvoker(ReferenceConfig.java:672) ~[classes/:?]
    at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:502) ~[classes/:?]
    at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:383) ~[classes/:?]
    at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:244) ~[classes/:?]
    at org.apache.dubbo.config.utils.SimpleReferenceCache.get(SimpleReferenceCache.java:140) ~[classes/:?]
    at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:567) ~[classes/:?]
    at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780) [?:?]
    at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:539) [classes/:?]
    at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:186) [classes/:?]
    at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:159) [classes/:?]
    at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.startModules(DefaultApplicationDeployer.java:771) [classes/:?]
    at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.doStart(DefaultApplicationDeployer.java:735) [classes/:?]
    at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.start(DefaultApplicationDeployer.java:708) [classes/:?]
    at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:230) [classes/:?]
    at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:219) [classes/:?]
    at org.apache.dubbo.demo.consumer.ApiConsumer.main(ApiConsumer.java:53) [classes/:?]
14:15:40.956 |-INFO  [main]   org.apache.dubbo.rpc.model.ModuleModel:212 -|  [DUBBO] Dynamically registering consumer model dubbo-demo-triple-api-provider/org.apache.dubbo.metadata.MetadataServiceV2:2.0.0 into model Dubbo Module[1.1.0], dubbo version: , current host: 10.251.1.1
```
6. This the zk:
<img width="713" alt="image" src="https://github.com/user-attachments/assets/5c8a85b4-943c-4d53-9709-a9339fbe4bfa">

### What you expected to happen

1. I want to run the demo `dubbo-demo-triple` with IDEA;

### Anything else

Is there an online discussion group? Please add me, thank you.

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangcunli** [comment]
utun5 is a virtual network interface typically created by VPN:
<img width="751" alt="image" src="https://github.com/user-attachments/assets/c6ccc12d-3e6f-4807-bdde-2e32ed615b3a">

I have resolve the issue:
```
ProtocolConfig protocol = new ProtocolConfig(CommonConstants.TRIPLE, -1);
protocol.setHost("xxx.xxx.xxx.xxx"); //uses the specified IP address
```

**Comment by wcy666103** [comment]
> utun5 is a virtual network interface typically created by VPN: <img alt="image" width="751" src="https://private-user-images.githubusercontent.com/5989340/377412707-c6ccc12d-3e6f-4807-bdde-2e32ed615b3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjY4NDYsIm5iZiI6MTcyOTE2NjU0NiwicGF0aCI6Ii81OTg5MzQwLzM3NzQxMjcwNy1jNmNjYzEyZC0zZTZmLTQ4MDctYmRkZS0yZTMyZWQ2MTViM2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTdUMTIwMjI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDY2ODMzZTA4NmRkN2UwNWU1ZDM3ZWQ3OTA5MDYyY2Q3ZWI5Zjk4YjlkODY0YmQ1ODBkYTRhODI1OWJjYTVlZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0aaTPn0nHJtoxF99lfMwJ1I5EhInRJqBgBzndjss5uA">
> 
> I have resolve the issue:
> 
> ```
> ProtocolConfig protocol = new ProtocolConfig(CommonConstants.TRIPLE, -1);
> protocol.setHost("xxx.xxx.xxx.xxx"); //uses the specified IP address
> ```

https://dubbo.apache.org/  There are several solutions to this problem in the official documentation, and you can choose the one that is most elegant to you

**Comment by heliang666s** [comment]
> utun5 is a virtual network interface typically created by VPN: <img alt="image" width="751" src="https://private-user-images.githubusercontent.com/5989340/377412707-c6ccc12d-3e6f-4807-bdde-2e32ed615b3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjg2MTQsIm5iZiI6MTcyOTE2ODMxNCwicGF0aCI6Ii81OTg5MzQwLzM3NzQxMjcwNy1jNmNjYzEyZC0zZTZmLTQ4MDctYmRkZS0yZTMyZWQ2MTViM2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTdUMTIzMTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTIyYzBmMmI1YjE5OGE4NDUxYWI4MGFmYWMzNTFhMTA5NWRmMDBjOTU2MGRlMWVhOWM2ZjFmNzNmYzQ3ZmIwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lqvCpS-7C8pSGXDQUl6IIPjIjLbLNGDCAIk6HhtS2lU">
> 
> I have resolve the issue:
> 
> ```
> ProtocolConfig protocol = new ProtocolConfig(CommonConstants.TRIPLE, -1);
> protocol.setHost("xxx.xxx.xxx.xxx"); //uses the specified IP address
> ```

If you solve it，you can close the issue,thanks~

**Comment by Yuuu97** [comment]
The key is to use reflection to change the HOST_ADDRESS in NetUtils to 127.0.0.1 before Spring Boot runs. Then upgrade the protobuf - java version to 3.22.0 or above.
