### ISSUE TITLE
[Bug] "dubbo-samples-triple-streaming" run with exception "Unable to make field final int java.math.BigInteger.signum accessible"

### ISSUE THREAD

**Issue by zhangcunli** [apache/dubbo#14791]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

1.<dubbo.version>3.3.0-beta.1</dubbo.version>
2.Darwin zzzMacBook-Pro-M1.local 23.0.0 Darwin Kernel Version 23.0.0

### Steps to reproduce this issue

I run the demo "dubbo-samples-triple-streaming" with IDEA
But the client failed:
Exception stack:
```
15:27:46.083 |-INFO  [main] .remoting.zookeeper.ZookeeperTransporter:59  -|  [DUBBO] find valid zookeeper client from the cache for address: zookeeper://127.0.0.1:2181/org.apache.dubbo.registry.RegistryService?application=tri-stub-consumer&dubbo=2.0.2&executor-management-mode=isolation&file-cache=true&interface=org.apache.dubbo.registry.RegistryService&pid=79502&qos.enable=false&release=3.3.0-beta.1, dubbo version: 3.3.0-beta.1, current host: 10.251.1.1
15:27:46.093 |-INFO  [main] y.client.migration.MigrationRuleListener:103 -|  [DUBBO] Listening for migration rules on dataId tri-stub-consumer.migration, group DUBBO_SERVICEDISCOVERY_MIGRATION, dubbo version: 3.3.0-beta.1, current host: 10.251.1.1
15:27:46.143 |-INFO  [main] bbo.registry.zookeeper.ZookeeperRegistry:415 -|  [DUBBO] Subscribe: tri://10.251.1.1/org.apache.dubbo.samples.tri.streaming.Greeter?application=tri-stub-consumer&background=false&category=providers,configurators,routers&dubbo=2.0.2&executor-management-mode=isolation&file-cache=true&interface=org.apache.dubbo.samples.tri.streaming.Greeter&methods=biStream,serverStream&pid=79502&protocol=tri&proxy=nativestub&qos.enable=false&release=3.3.0-beta.1&side=consumer&sticky=false&timeout=3000&timestamp=1729150066018&unloadClusterRelated=false, dubbo version: 3.3.0-beta.1, current host: 10.251.1.1
15:27:46.157 |-INFO  [main] bbo.registry.zookeeper.ZookeeperRegistry:514 -|  [DUBBO] Notify urls for subscribe url tri://10.251.1.1/org.apache.dubbo.samples.tri.streaming.Greeter?application=tri-stub-consumer&background=false&category=providers,configurators,routers&dubbo=2.0.2&executor-management-mode=isolation&file-cache=true&interface=org.apache.dubbo.samples.tri.streaming.Greeter&methods=biStream,serverStream&pid=79502&protocol=tri&proxy=nativestub&qos.enable=false&release=3.3.0-beta.1&side=consumer&sticky=false&timeout=3000&timestamp=1729150066018&unloadClusterRelated=false, url size: 3, dubbo version: 3.3.0-beta.1, current host: 10.251.1.1
15:27:46.172 |-INFO  [main] he.dubbo.qos.protocol.QosProtocolWrapper:109 -|  [DUBBO] qos won't be started because it is disabled. Please check dubbo.application.qos.enable is configured either in system property, dubbo.properties or XML/spring-boot configuration., dubbo version: 3.3.0-beta.1, current host: 10.251.1.1
15:27:46.286 |-INFO  [NettyClientWorker-2-1] .transport.netty4.NettyConnectionHandler:100 -|  [DUBBO] The connection of /10.251.1.1:62624 -> /10.251.1.1:50052 is established., dubbo version: 3.3.0-beta.1, current host: 10.251.1.1
15:27:46.289 |-INFO  [main] .dubbo.remoting.transport.AbstractClient:228 -|  [DUBBO] Successfully connect to server /10.251.1.1:50052 from NettyConnectionClient 10.251.1.1 using dubbo version 3.3.0-beta.1, channel is NettyChannel [channel=[id: 0x32798ea5, L:/10.251.1.1:62624 - R:/10.251.1.1:50052]], dubbo version: 3.3.0-beta.1, current host: 10.251.1.1
15:27:46.289 |-INFO  [main] .dubbo.remoting.transport.AbstractClient:79  -|  [DUBBO] Start NettyConnectionClient /10.251.1.1 connect to the server /10.251.1.1:50052, dubbo version: 3.3.0-beta.1, current host: 10.251.1.1
15:27:46.314 |-INFO  [main] o.registry.integration.RegistryDirectory:334 -|  [DUBBO] Received invokers changed event from registry. Registry type: interface. Service Key: org.apache.dubbo.samples.tri.streaming.Greeter. Urls Size : 1. Invokers Size : 1. Available Size: 1. Available Invokers : 10.251.1.1:50052, dubbo version: 3.3.0-beta.1, current host: 10.251.1.1
15:27:46.329 |-INFO  [main] registry.client.ServiceDiscoveryRegistry:315 -|  [DUBBO] Loaded registry cache file /Users/zhangcunli/.dubbo/dubbo-registry-tri-stub-consumer-127.0.0.1-2181.cache, dubbo version: 3.3.0-beta.1, current host: 10.251.1.1
15:27:46.336 |-INFO  [main] y.client.metadata.store.MetaCacheManager:54  -|  [DUBBO] Successfully loaded meta cache from file .metadata.tri-stub-consumer.zookeeper.127.0.0.1:2181, entries 0, dubbo version: 3.3.0-beta.1, current host: 10.251.1.1
15:27:46.338 |-INFO  [main] ator.framework.imps.CuratorFrameworkImpl:304 -| Starting
15:27:46.339 |-INFO  [main]           org.apache.zookeeper.ZooKeeper:637 -| Initiating client connection, connectString=127.0.0.1:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@53b7ce6
15:27:46.339 |-INFO  [main]    org.apache.zookeeper.ClientCnxnSocket:239 -| jute.maxbuffer value is 1048575 Bytes
15:27:46.339 |-INFO  [main]          org.apache.zookeeper.ClientCnxn:1741 -| zookeeper.request.timeout value is 0. feature enabled=false
15:27:46.339 |-INFO  [main] ator.framework.imps.CuratorFrameworkImpl:352 -| Default schema
15:27:46.340 |-INFO  [main-SendThread(127.0.0.1:2181)]          org.apache.zookeeper.ClientCnxn:1177 -| Opening socket connection to server localhost/127.0.0.1:2181.
15:27:46.340 |-INFO  [main-SendThread(127.0.0.1:2181)]          org.apache.zookeeper.ClientCnxn:1179 -| SASL config status: Will not attempt to authenticate using SASL (unknown error)
15:27:46.340 |-INFO  [main-SendThread(127.0.0.1:2181)]          org.apache.zookeeper.ClientCnxn:1011 -| Socket connection established, initiating session, client: /127.0.0.1:62626, server: localhost/127.0.0.1:2181
15:27:46.344 |-INFO  [main-SendThread(127.0.0.1:2181)]          org.apache.zookeeper.ClientCnxn:1452 -| Session establishment complete on server localhost/127.0.0.1:2181, session id = 0x1008492a29e0003, negotiated timeout = 60000
15:27:46.345 |-INFO  [main-EventThread] r.framework.state.ConnectionStateManager:250 -| State change: CONNECTED
15:27:46.346 |-INFO  [main-EventThread] e.curator.framework.imps.EnsembleTracker:201 -| New config event received: {}
15:27:46.346 |-INFO  [main-EventThread] e.curator.framework.imps.EnsembleTracker:201 -| New config event received: {}
15:27:46.399 |-INFO  [main] pache.dubbo.metadata.MappingCacheManager:54  -|  [DUBBO] Successfully loaded mapping cache from file .mapping.tri-stub-consumer, entries 0, dubbo version: 3.3.0-beta.1, current host: 10.251.1.1
15:27:46.403 |-INFO  [main] ient.metadata.MetadataServiceNameMapping:100 -|  [DUBBO] Local cache mapping is empty, dubbo version: 3.3.0-beta.1, current host: 10.251.1.1
15:27:46.406 |-INFO  [main] registry.client.ServiceDiscoveryRegistry:309 -|  [DUBBO] Trying to subscribe from apps tri-stub-server for service key org.apache.dubbo.samples.tri.streaming.Greeter, , dubbo version: 3.3.0-beta.1, current host: 10.251.1.1
15:27:46.407 |-INFO  [main-EventThread] DiscoveryRegistry$DefaultMappingListener:378 -|  [DUBBO] Received mapping notification from meta server, {serviceKey: org.apache.dubbo.samples.tri.streaming.Greeter, apps: [tri-stub-server]}, dubbo version: 3.3.0-beta.1, current host: 10.251.1.1
15:27:46.407 |-INFO  [main-EventThread] DiscoveryRegistry$DefaultMappingListener:391 -|  [DUBBO] Mapping of service org.apache.dubbo.samples.tri.streaming.Greeterchanged from null to [tri-stub-server], dubbo version: 3.3.0-beta.1, current host: 10.251.1.1
15:27:46.407 |-INFO  [main-EventThread] registry.client.ServiceDiscoveryRegistry:309 -|  [DUBBO] Trying to subscribe from apps tri-stub-server for service key org.apache.dubbo.samples.tri.streaming.Greeter, , dubbo version: 3.3.0-beta.1, current host: 10.251.1.1
15:27:46.435 |-INFO  [main] listener.ServiceInstancesChangedListener:301 -|  [DUBBO] Received instance notification, serviceName: tri-stub-server, instances: 1, dubbo version: 3.3.0-beta.1, current host: 10.251.1.1
15:27:46.487 |-INFO  [main]   org.apache.dubbo.rpc.model.ModuleModel:203 -|  [DUBBO] Dynamically registering consumer model tri-stub-server/org.apache.dubbo.metadata.MetadataService:1.0.0 into model Dubbo Module[1.1.0], dubbo version: 3.3.0-beta.1, current host: 10.251.1.1
15:27:46.509 |-INFO  [main] .dubbo.remoting.transport.AbstractClient:228 -|  [DUBBO] Successfully connect to server /10.251.1.1:20880 from NettyClient 10.251.1.1 using dubbo version 3.3.0-beta.1, channel is NettyChannel [channel=[id: 0xc6b6607c, L:/10.251.1.1:62629 - R:/10.251.1.1:20880]], dubbo version: 3.3.0-beta.1, current host: 10.251.1.1
15:27:46.509 |-INFO  [main] .dubbo.remoting.transport.AbstractClient:79  -|  [DUBBO] Start NettyClient /10.251.1.1 connect to the server /10.251.1.1:20880, dubbo version: 3.3.0-beta.1, current host: 10.251.1.1
15:27:46.511 |-INFO  [NettyClientWorker-3-1] ting.transport.netty4.NettyClientHandler:60  -|  [DUBBO] The connection of /10.251.1.1:62629 -> /10.251.1.1:20880 is established., dubbo version: 3.3.0-beta.1, current host: 10.251.1.1
java.lang.reflect.InaccessibleObjectException: Unable to make field final int java.math.BigInteger.signum accessible: module java.base does not "opens java.math" to unnamed module @35fc6dc4
    at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
    at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
    at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
    at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
    at com.alibaba.com.caucho.hessian.io.JavaDeserializer.getFieldMap(JavaDeserializer.java:340)
    at com.alibaba.com.caucho.hessian.io.JavaDeserializer.<init>(JavaDeserializer.java:80)
    at com.alibaba.com.caucho.hessian.io.BigIntegerDeserializer.<init>(BigIntegerDeserializer.java:25)
    at com.alibaba.com.caucho.hessian.io.SerializerFactory.<clinit>(SerializerFactory.java:142)
    at org.apache.dubbo.common.serialize.hessian2.Hessian2FactoryManager.createDefaultSerializerFactory(Hessian2FactoryManager.java:91)
    at org.apache.dubbo.common.serialize.hessian2.Hessian2FactoryManager.createSerializerFactory(Hessian2FactoryManager.java:87)
    at org.apache.dubbo.common.serialize.hessian2.Hessian2FactoryManager.getSerializerFactory(Hessian2FactoryManager.java:70)
    at org.apache.dubbo.common.serialize.hessian2.Hessian2ObjectOutput.<init>(Hessian2ObjectOutput.java:44)
    at org.apache.dubbo.common.serialize.hessian2.Hessian2Serialization.serialize(Hessian2Serialization.java:57)
    at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper.serialize(DefaultSerializationExceptionWrapper.java:51)
    at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.encodeRequest(ExchangeCodec.java:269)
    at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.encode(ExchangeCodec.java:79)
    at org.apache.dubbo.rpc.protocol.dubbo.DubboCountCodec.encode(DubboCountCodec.java:51)
    at org.apache.dubbo.remoting.transport.netty4.NettyChannel.send(NettyChannel.java:192)
    at org.apache.dubbo.remoting.transport.AbstractClient.send(AbstractClient.java:202)
    at org.apache.dubbo.remoting.transport.AbstractPeer.send(AbstractPeer.java:53)
    at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeChannel.request(HeaderExchangeChannel.java:149)
    at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeClient.request(HeaderExchangeClient.java:105)
    at org.apache.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:131)
    at org.apache.dubbo.rpc.protocol.AbstractInvoker.doInvokeAndReturn(AbstractInvoker.java:243)
    at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:187)
    at org.apache.dubbo.rpc.proxy.InvocationUtil.invoke(InvocationUtil.java:61)
    at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:75)
    at org.apache.dubbo.metadata.MetadataServiceDubboProxy0.getMetadataInfo(MetadataServiceDubboProxy0.java)
    at org.apache.dubbo.registry.client.metadata.MetadataUtils.getRemoteMetadata(MetadataUtils.java:178)
    at org.apache.dubbo.registry.client.AbstractServiceDiscovery.lambda$getRemoteMetadata$2(AbstractServiceDiscovery.java:229)
    at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:86)
    at org.apache.dubbo.registry.client.AbstractServiceDiscovery.getRemoteMetadata(AbstractServiceDiscovery.java:228)
    at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.lambda$doOnEvent$2(ServiceInstancesChangedListener.java:162)
    at java.base/java.util.Optional.orElseGet(Optional.java:364)
    at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.doOnEvent(ServiceInstancesChangedListener.java:162)
    at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.onEvent(ServiceInstancesChangedListener.java:116)
    at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribeURLs(ServiceDiscoveryRegistry.java:321)
    at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.doSubscribe(ServiceDiscoveryRegistry.java:226)
    at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribe(ServiceDiscoveryRegistry.java:188)
    at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:88)
    at org.apache.dubbo.registry.integration.DynamicDirectory.subscribe(DynamicDirectory.java:184)
    at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.subscribe(ServiceDiscoveryRegistryDirectory.java:142)
    at org.apache.dubbo.registry.integration.RegistryProtocol.doCreateInvoker(RegistryProtocol.java:629)
    at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getServiceDiscoveryInvoker(InterfaceCompatibleRegistryProtocol.java:65)
    at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshServiceDiscoveryInvoker(MigrationInvoker.java:440)
    at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToApplicationFirstInvoker(MigrationInvoker.java:246)
    at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.refreshInvoker(MigrationRuleHandler.java:76)
    at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:60)
    at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:249)
    at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:594)
    at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:564)
    at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:546)
    at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:85)
    at org.apache.dubbo.rpc.protocol.ProtocolSecurityWrapper.refer(ProtocolSecurityWrapper.java:110)
    at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:80)
    at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:71)
    at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:52)
    at org.apache.dubbo.rpc.protocol.InvokerCountWrapper.refer(InvokerCountWrapper.java:48)
    at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
    at org.apache.dubbo.config.ReferenceConfig.createInvoker(ReferenceConfig.java:621)
    at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:467)
    at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:354)
    at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:239)
    at org.apache.dubbo.config.utils.SimpleReferenceCache.get(SimpleReferenceCache.java:132)
    at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:502)
    at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780)
    at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:482)
    at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:179)
    at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:151)
    at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.startModules(DefaultApplicationDeployer.java:744)
    at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.doStart(DefaultApplicationDeployer.java:708)
    at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.start(DefaultApplicationDeployer.java:681)
    at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:227)
    at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:216)
    at org.apache.dubbo.samples.tri.streaming.TriStreamClient.main(TriStreamClient.java:45)
java.lang.reflect.InaccessibleObjectException: Unable to make field final int[] java.math.BigInteger.mag accessible: module java.base does not "opens java.math" to unnamed module @35fc6dc4
    at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
    at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
    at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
    at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
    at com.alibaba.com.caucho.hessian.io.JavaDeserializer.getFieldMap(JavaDeserializer.java:340)
    at com.alibaba.com.caucho.hessian.io.JavaDeserializer.<init>(JavaDeserializer.java:80)
    at com.alibaba.com.caucho.hessian.io.BigIntegerDeserializer.<init>(BigIntegerDeserializer.java:25)
    at com.alibaba.com.caucho.hessian.io.SerializerFactory.<clinit>(SerializerFactory.java:142)
    at org.apache.dubbo.common.serialize.hessian2.Hessian2FactoryManager.createDefaultSerializerFactory(Hessian2FactoryManager.java:91)
    at org.apache.dubbo.common.serialize.hessian2.Hessian2FactoryManager.createSerializerFactory(Hessian2FactoryManager.java:87)
    at org.apache.dubbo.common.serialize.hessian2.Hessian2FactoryManager.getSerializerFactory(Hessian2FactoryManager.java:70)
    at org.apache.dubbo.common.serialize.hessian2.Hessian2ObjectOutput.<init>(Hessian2ObjectOutput.java:44)
    at org.apache.dubbo.common.serialize.hessian2.Hessian2Serialization.serialize(Hessian2Serialization.java:57)
    at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper.serialize(DefaultSerializationExceptionWrapper.java:51)
    at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.encodeRequest(ExchangeCodec.java:269)
    at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.encode(ExchangeCodec.java:79)
    at org.apache.dubbo.rpc.protocol.dubbo.DubboCountCodec.encode(DubboCountCodec.java:51)
    at org.apache.dubbo.remoting.transport.netty4.NettyChannel.send(NettyChannel.java:192)
    at org.apache.dubbo.remoting.transport.AbstractClient.send(AbstractClient.java:202)
    at org.apache.dubbo.remoting.transport.AbstractPeer.send(AbstractPeer.java:53)
    at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeChannel.request(HeaderExchangeChannel.java:149)
    at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeClient.request(HeaderExchangeClient.java:105)
    at org.apache.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:131)
    at org.apache.dubbo.rpc.protocol.AbstractInvoker.doInvokeAndReturn(AbstractInvoker.java:243)
    at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:187)
    at org.apache.dubbo.rpc.proxy.InvocationUtil.invoke(InvocationUtil.java:61)
    at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:75)
    at org.apache.dubbo.metadata.MetadataServiceDubboProxy0.getMetadataInfo(MetadataServiceDubboProxy0.java)
    at org.apache.dubbo.registry.client.metadata.MetadataUtils.getRemoteMetadata(MetadataUtils.java:178)
    at org.apache.dubbo.registry.client.AbstractServiceDiscovery.lambda$getRemoteMetadata$2(AbstractServiceDiscovery.java:229)
```

### What you expected to happen

I want to run the demo "dubbo-samples-triple-streaming" with IDEA.

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangcunli** [comment]
Demo: dubbo-samples/tree/master/2-advanced/dubbo-samples-triple-streaming

**Comment by wcy666103** [comment]
This seems to be a bug in analyzing the entity's properties. I try different serialization methods and this error occurs, but the results are normal and can communicate  PTAL @oxsean

**Comment by oxsean** [comment]
Please try  <dubbo.version>3.3.1</dubbo.version>

**Comment by zhangcunli** [comment]
> Please try <dubbo.version>3.3.1</dubbo.version>

@oxsean I modified the dubbo.version to 3.3.1, and the program runs normally now. thanks, I close the issue.

**Comment by lihuagang03** [comment]
> > Please try <dubbo.version>3.3.1</dubbo.version>
> 
> [@oxsean](https://github.com/oxsean) I modified the dubbo.version to 3.3.1, and the program runs normally now. thanks, I close the issue.

What is the JDK version?
This error maybe caused by use the JDK-9 later。
```
InaccessibleObjectException: Unable to make field final int[] java.math.BigInteger.mag accessible: module java.base does not "opens java.math" to unnamed module @35fc6dc4
```
