### ISSUE TITLE
[Bug] 3.2.0-beta.4.jar  No such extension ls for telnet/org.apache.dubbo.remoting.telnet.TelnetHandler

### ISSUE THREAD

**Issue by ddfeiyu** [apache/dubbo#14919]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

3.2.0-beta.4

### Steps to reproduce this issue

3.2.0-beta.4.jar

### What you expected to happen

  main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: No such extension ls for telnet/org.apache.dubbo.remoting.telnet.TelnetHandler
	at org.apache.dubbo.config.utils.ConfigValidationUtils.checkMultiExtension(ConfigValidationUtils.java:680) ~[dubbo-3.2.0-beta.4.jar!/:3.2.0-beta.4]
	at org.apache.dubbo.config.utils.ConfigValidationUtils.checkMultiExtension(ConfigValidationUtils.java:658) ~[dubbo-3.2.0-beta.4.jar!/:3.2.0-beta.4]
	at org.apache.dubbo.config.utils.ConfigValidationUtils.validateProviderConfig(ConfigValidationUtils.java:592) ~[dubbo-3.2.0-beta.4.jar!/:3.2.0-beta.4]
	at org.apache.dubbo.config.utils.DefaultConfigValidator.validate(DefaultConfigValidator.java:43) ~[dubbo-3.2.0-beta.4.jar!/:3.2.0-beta.4]
	at org.apache.dubbo.config.context.AbstractConfigManager.checkDefaultAndValidateConfigs(AbstractConfigManager.java:588) ~[dubbo-3.2.0-beta.4.jar!/:3.2.0-beta.4]
	at org.apache.dubbo.config.context.ModuleConfigManager.loadConfigs(ModuleConfigManager.java:292) ~[dubbo-3.2.0-beta.4.jar!/:3.2.0-beta.4]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.loadConfigs(DefaultModuleDeployer.java:316) ~[dubbo-3.2.0-beta.4.jar!/:3.2.0-beta.4]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.initialize(DefaultModuleDeployer.java:113) ~[dubbo-3.2.0-beta.4.jar!/:3.2.0-beta.4]
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.initModuleDeployers(DefaultApplicationDeployer.java:235) ~[dubbo-3.2.0-beta.4.jar!/:3.2.0-beta.4]
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.initialize(DefaultApplicationDeployer.java:207) ~[dubbo-3.2.0-beta.4.jar!/:3.2.0-beta.4]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.prepare(DefaultModuleDeployer.java:479) ~[dubbo-3.2.0-beta.4.jar!/:3.2.0-beta.4]
	at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.initDubboConfigBeans(DubboConfigApplicationListener.java:73) ~[dubbo-3.2.0-beta.4.jar!/:3.2.0-beta.4]
	at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.onApplicationEvent(DubboConfigApplicationListener.java:59) ~[dubbo-3.2.0-beta.4.jar!/:3.2.0-beta.4]
	at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.onApplicationEvent(DubboConfigApplicationListener.java:37) ~[dubbo-3.2.0-beta.4.jar!/:3.2.0-beta.4]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178) ~[spring-context-6.1.1.jar!/:6.1.1]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171) ~[spring-context-6.1.1.jar!/:6.1.1]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:149) ~[spring-context-6.1.1.jar!/:6.1.1]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:137) ~[spring-context-6.1.1.jar!/:6.1.1]
	at org.springframework.context.support.AbstractApplicationContext.registerListeners(AbstractApplicationContext.java:909) ~[spring-context-6.1.1.jar!/:6.1.1]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:613) ~[spring-context-6.1.1.jar!/:6.1.1]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.0.jar!/:3.2.0]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:753) ~[spring-boot-3.2.0.jar!/:3.2.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:455) ~[spring-boot-3.2.0.jar!/:3.2.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:323) ~[spring-boot-3.2.0.jar!/:3.2.0]
	at com.tem.platform.App.main(App.java:41) ~[!/:3.33.68-SNAPSHOT]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:102) ~[java.jar:3.33.68-SNAPSHOT]
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:64) ~[java.jar:3.33.68-SNAPSHOT]
	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:40) ~[java.jar:3.33.68-SNAPSHOT]

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
Please remove this config. We have already remove these commands in Dubbo 3
