### ISSUE TITLE
[Bug] org.apache.dubbo.rpc.protocol.tri.rest.mapping.DefaultRequestMappingRegistry restConfig may be null

### ISSUE THREAD

**Issue by niuone-cloud** [apache/dubbo#14923]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

dubbo java 3.3.2
spring boot 3.x
jdk 21

### Steps to reproduce this issue

restconfig is not initialized until tomcat is started, when the system is ready to receive requests. If there is a request before restconfig is initialized, the exception restconfig is null.
Can you add initialization logic when determining whether to use the triple-rest protocol, or reject the request before the initialization is complete

### What you expected to happen

no exception

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by oxsean** [comment]
Could you please provide the exception stack?

**Comment by niuone-cloud** [comment]
`
    Tomcat started on port 20110 (http) with context path '/support/monitor'
    Cannot determine local hostname
    Cannot determine local hostname
    Initializing Spring DispatcherServlet 'dispatcherServlet'
    Initializing Servlet 'dispatcherServlet'
    Completed initialization in 1 ms
    Servlet.service() for servlet [dispatcherServlet] in context with path [/support/monitor] threw exception

    java.lang.NullPointerException: Cannot invoke "org.apache.dubbo.config.nested.RestConfig.getCaseSensitiveMatchOrDefault()" because "this.restConfig" is null
	    at org.apache.dubbo.rpc.protocol.tri.rest.mapping.DefaultRequestMappingRegistry.exists(DefaultRequestMappingRegistry.java:368)
	    at org.apache.dubbo.rpc.protocol.tri.servlet.jakarta.TripleFilter.doFilter(TripleFilter.java:89)
	    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	    at niuone.framework.component.web.filter.security.encrypt.EncryptParamFilter.doFilter(EncryptParamFilter.java:32)
	    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	    at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	    at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	    at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:113)
	    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
	    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
	    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:384)
	    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
	    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
	    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	    at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
	    at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	    at java.base/java.lang.Thread.run(Thread.java:1583)
`
