### ISSUE TITLE
[Bug] The error is disconnect, but the telnet [provider:port] is available

### ISSUE THREAD

**Issue by glynnwei** [apache/dubbo#14946]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo:3.2.11
Nacos: 2.3.2
JDK: 1.8
SpringBoot: 2.6.4

### Steps to reproduce this issue

background:
- The provider is the go project, which does not use the dubbo-go framework, and refers to the java way to register nacos, interface level mode
![image](https://github.com/user-attachments/assets/df90ffbd-e3d1-48b9-891f-df06d5467482)
- The consumer is a Java project, framework for dubbo3, normal subscription
![image](https://github.com/user-attachments/assets/4d375bc3-6303-4555-84c1-21806021e1cb)

The consumer is a Java project, error ：
```
2024-11-25 02:42:40.692|||-|||ERROR|||-|||-|||-|||-|||[NettyClientWorker-10-2] - [org.apache.dubbo.remoting.transport.netty4.NettyConnectionClient:?] -  [DUBBO] Client-side timeout., dubbo version: 3.2.11, current host: 10.183.20.160, error code: 6-2. This may be caused by provider crash, go to https://dubbo.apache.org/faq/6/2 to find instructions. 
org.apache.dubbo.remoting.RemotingException: client(url: grpc://10.183.19.125:8082/proto.user.UserApi?application=rpc.discover.test/k8s/user&background=false&category=providers,configurators,routers&check=false&dubbo=2.0.2&dubbo-services=proto.user.UserApi,proto.session.SessionApi&env=test&executor-management-mode=isolation&file-cache=true&interface=proto.user.UserApi&logger=slf4j&path=proto.user.UserApi&pid=11&protocol=grpc&proxy=nativestub&qos.enable=false&release=3.2.11&retries=0&side=provider&sticky=false&timeout=6000&unloadClusterRelated=false) failed to connect to server /10.183.19.125:8082 client-side timeout 3000ms (elapsed: 3001ms) from netty client 10.183.20.160 using dubbo version 3.2.11
        at org.apache.dubbo.remoting.transport.netty4.NettyConnectionClient.doConnect(NettyConnectionClient.java:205)
        at org.apache.dubbo.remoting.transport.netty4.NettyConnectionHandler.lambda$reconnect$0(NettyConnectionHandler.java:87)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
2024-11-25 02:42:40.692|||-|||ERROR|||-|||-|||-|||-|||[NettyClientWorker-10-2] - [org.apache.dubbo.remoting.transport.netty4.NettyConnectionHandler:?] -  [DUBBO] Fail to connect to null, dubbo version: 3.2.11, current host: 10.183.20.160, error code: 6-16. This may be caused by , go to https://dubbo.apache.org/faq/6/16 to find instructions. 
org.apache.dubbo.remoting.RemotingException: client(url: grpc://10.183.19.125:8082/proto.user.UserApi?application=rpc.discover.test/k8s/user&background=false&category=providers,configurators,routers&check=false&dubbo=2.0.2&dubbo-services=proto.user.UserApi,proto.session.SessionApi&env=test&executor-management-mode=isolation&file-cache=true&interface=proto.user.UserApi&logger=slf4j&path=proto.user.UserApi&pid=11&protocol=grpc&proxy=nativestub&qos.enable=false&release=3.2.11&retries=0&side=provider&sticky=false&timeout=6000&unloadClusterRelated=false) failed to connect to server /10.183.19.125:8082 client-side timeout 3000ms (elapsed: 3001ms) from netty client 10.183.20.160 using dubbo version 3.2.11
        at org.apache.dubbo.remoting.transport.netty4.NettyConnectionClient.doConnect(NettyConnectionClient.java:205)
        at org.apache.dubbo.remoting.transport.netty4.NettyConnectionHandler.lambda$reconnect$0(NettyConnectionHandler.java:87)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```
- Consumer command line test
```
telnet 10.183.19.125 8082
The results are available
```
- Also used etcd register, the same problem

### What you expected to happen

1, go project does not implement all according to dubbo3 specification
2. go project metadata data is insufficient
3. The java project dubbo check mechanism has bugs

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wcy666103** [comment]
Would you be willing to submit a pr to help fix this?
