### ISSUE TITLE
ThriftProtocol BUG

### ISSUE THREAD

**Issue by zhaobingss** [apache/dubbo#2061]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/wiki/FAQ) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.2
* Operating System version: win10
* Java version: 1.8

### Step to reproduce this issue
1、the code in **ThriftProtocol**
String serviceKey = serviceKey(channel.getLocalAddress().getPort(), serviceName, null, null);
DubboExporter<?> exporter = (DubboExporter<?>) exporterMap.get(serviceKey);
2、why set the serviceVersion and serviceGroup null ? I do not understand

```
com.alibaba.dubbo.remoting.RemotingException: Not found exported service: com.zbss.common.api.config.service.ConfigService$Iface:20080 in [service-config/com.zbss.common.api.config.service.ConfigService$Iface:20080], may be version or group mismatch , channel: consumer: /192.168.3.63:61251 --> provider: /192.168.3.63:20080, message:RpcInvocation [methodName=getVendorConfig, parameterTypes=[class java.lang.String], arguments=[123], attachments={interface=com.zbss.common.api.config.service.ConfigService$Iface}]
	at com.alibaba.dubbo.rpc.protocol.thrift.ThriftProtocol$1.reply(ThriftProtocol.java:67)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:96)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:172)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by lovepoem** [comment]
What kind of thrift  is used in your project?

I guess is native thrift

**Comment by zhaobingss** [comment]
no i do not use native thrift
@lovepoem
