### ISSUE TITLE
Dubbo 2.6.2 version do not support specify the protocol type on consumer side

### ISSUE THREAD

**Issue by jiangzzwy** [apache/dubbo#2311]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### 问题描述

使用注解开发dubbo的服务端和消费端。当服务端暴露多个协议的时候，dubbo客户端@Reference无法指定协议去消费。但是在dubbo的消费XML配置方式是支持的
```   
 <dubbo:reference id="userService" interface="com.jiangzz.service.IUserService" protocol="dubbo"/>
```
但是@Refernece目前没有注解支持改配置信息，希望官方有时间修正该问题！   

### 环境

* Dubbo version: 2.6.2
* Operating System version: win7
* Java version: 1.8.0_161

### 创建服务端，同时支持三种协议
服务端：
```java
@Service(protocol = {"dubbo","rmi","rest"})
@Path(value = "users")
public class UserService implements IUserService {
    @GET
    @Path(value = "queryUserById")
    @Produces(value = {"application/json;charset=utf-8"})
    public User queryUser(@QueryParam(value = "id") Integer id) {
        User user=new User();
        user.setId(id+"");
        user.setBirthDay(new Date());
        user.setName("张三");
        return user;
    }
}
```
```
@Configuration
@DubboComponentScan(basePackages = {"com.jiangzz.service.impl"})
public class DubboConfig {
    @Bean
    public ApplicationConfig applicationConfig() {
        ApplicationConfig applicationConfig = new ApplicationConfig();
        applicationConfig.setName("provider-test");
        return applicationConfig;
    }

    @Bean("dubbo")
    public ProtocolConfig protocolConfig0(){
        ProtocolConfig protocolConfig=new ProtocolConfig("dubbo");
        protocolConfig.setPort(20880);
        protocolConfig.setServer("netty4");
        return protocolConfig;
    }
    @Bean("rmi")
    public ProtocolConfig protocolConfig1(){
        ProtocolConfig protocolConfig=new ProtocolConfig("rmi");
        protocolConfig.setPort(20881);
        protocolConfig.setServer("netty4");
        return protocolConfig;
    }
    @Bean("rest")
    public ProtocolConfig protocolConfig2(){
        ProtocolConfig protocolConfig=new ProtocolConfig("rest");
        protocolConfig.setPort(8080);
        protocolConfig.setServer("netty4");
        protocolConfig.setContextpath("/services");
        protocolConfig.setServer("netty");
        return protocolConfig;
    }
    @Bean
    public RegistryConfig registryConfig() {
        RegistryConfig registryConfig = new RegistryConfig();
        registryConfig.setAddress("zookeeper://192.168.65.135:2181");
        registryConfig.setClient("curator");
        return registryConfig;
    }
}

```
**客户端：**
```
@Configuration
@DubboComponentScan(basePackages = "com.jiangzz.service")
public class DubboConfig {
    @Reference
    private IUserService userService;
   @Bean
    public IUserService userService(){
        return userService;
   }
    @Bean
    public ApplicationConfig applicationConfig() {
        ApplicationConfig applicationConfig = new ApplicationConfig();
        applicationConfig.setName("consumer-test");
        return applicationConfig;
    }
    @Bean
    public ConsumerConfig consumerConfig() {
        ConsumerConfig consumerConfig = new ConsumerConfig();
        consumerConfig.setTimeout(3000);
        consumerConfig.setClient("netty4");

        return consumerConfig;
    }
    @Bean
    public RegistryConfig registryConfig() {
        RegistryConfig registryConfig = new RegistryConfig();
        registryConfig.setAddress("zookeeper://192.168.65.135:2181");
        registryConfig.setClient("curator");
        return registryConfig;
    }
}
```
调用：
```
  AnnotationConfigApplicationContext acc=new AnnotationConfigApplicationContext(DubboConfig.class);
        IUserService bean = acc.getBean(IUserService.class);
        for(int i=0;i<1000;i++){
            User user = bean.queryUser(1);
            System.out.println(user);

        }
```
###异常信息

```
Exception in thread "main" java.lang.RuntimeException: RESTEASY004530: Could not find a method for: public abstract com.jiangzz.entities.User com.jiangzz.service.IUserService.queryUser(java.lang.Integer)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:74)
	at com.sun.proxy.$Proxy31.queryUser(Unknown Source)
	at com.alibaba.dubbo.common.bytecode.Wrapper0.invokeMethod(Wrapper0.java)
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47)
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:76)
	at com.alibaba.dubbo.rpc.protocol.AbstractProxyProtocol$2.doInvoke(AbstractProxyProtocol.java:97)
	at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:148)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:54)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:77)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:78)
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:238)
	at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:75)
	at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52)
	at com.alibaba.dubbo.common.bytecode.proxy0.queryUser(proxy0.java)
	at com.jiangzz.StartClientDemo.main(StartClientDemo.java:18)

```

**Comment by panyi5202** [comment]
我按照上面的配置，启动就报错：
```
Exception in thread "main" java.lang.IllegalStateException: No such extension org.apache.dubbo.rpc.Protocol by name rest
	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:494)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:501)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:321)
	at org.apache.dubbo.config.ServiceConfig.findConfigedPorts(ServiceConfig.java:648)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:471)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:358)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:317)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:216)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:123)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:49)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
	at com.apache.dubbo.demo.provider.annotation.AppProvider.main(AppProvider.java:12)
```

**Comment by kevin-wang001** [comment]
我觉得，在 loadbalance 里面是不是应该有个协议选择的优先级？优先选择速度快的协议去 invoke
比如：在待选的 invokers 里面同时有 rest 和 dubbo 协议的，优先选择调用 dubbo 协议的

**Comment by lthaoshao** [comment]
我这两天也遇到了这个问题，看你代码问题应该差不多。
我这边的解决方式是因为 dubbo 看到是接口，使用rest形式时，如果你的@Path等注解是在实现类上，则在用dubbo consumer形式调用时，会找不到对应的方法，但是有postman等形式应该是可以调用的。
解决dubbo consumer 调用rest的办法就是将注解提到接口上就可以了。
