### ISSUE TITLE
调用dubbo 泛化 rest协议问题

### ISSUE THREAD

**Issue by zyh1218** [apache/dubbo#2612]
当我在setUrl 是rest协议的时候报错，请问这是什么原因的 代码如下
![image](https://user-images.githubusercontent.com/5111738/46642961-68ed5d80-cbac-11e8-8db1-a3cf5cfdc8ae.png)
错误如下：
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.RuntimeException: RESTEASY004530: Could not find a method for: public abstract java.lang.Object com.alibaba.dubbo.rpc.service.GenericService.$invoke(java.lang.String,java.lang.String[],java.lang.Object[]) throws com.alibaba.dubbo.rpc.service.GenericException
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:336)
	at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:124)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:334)
	at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:141)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:334)
	at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:270)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:334)
	at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:73)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:334)
	at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:40)

**Comment by gudegg** [comment]
I think the rest protocol is not supported. `GenericService` is not annotated with `@Path`.So throw an exception:
```xml
Could not find a method for: public abstract java.lang.Object com.alibaba.dubbo.rpc.service.GenericService.$invoke(java.lang.String,java.lang.String[],java.lang.Object[]) throws com.alibaba.dubbo.rpc.service.GenericException
```

**Comment by zyh1218** [comment]
hi,我想在dubbo泛化的时候在GenericService 想拿到dubbo的提供者的服务ip和端口，需要怎么拿。thks

**Comment by gudegg** [comment]
@zyh1218  ` RpcContext.getContext().getLocalAddress()`

**Comment by wanhuhou** [comment]
dubbo rest发布 path 路径信息不会发到 zookeeper，非dubbo消费端就无法知道发布了什么服务。这个怎么解决的？
