### ISSUE TITLE
user Kryo,reporting error in high concurrency environment

### ISSUE THREAD

**Issue by zengqiyan** [apache/dubbo#2942]
java.lang.NullPointerException: null
	at reflectasm.java.lang.NullPointerExceptionConstructorAccess.newInstance(Unknown Source) ~[na:na]
	at com.esotericsoftware.kryo.Kryo$DefaultInstantiatorStrategy$1.newInstance(Kryo.java:1275) ~[kryo-4.0.0.jar!/:na]
	at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1139) ~[kryo-4.0.0.jar!/:na]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.create(FieldSerializer.java:559) ~[kryo-4.0.0.jar!/:na]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:535) ~[kryo-4.0.0.jar!/:na]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813) ~[kryo-4.0.0.jar!/:na]
	at com.alibaba.dubbo.common.serialize.support.kryo.KryoObjectInput.readObject(KryoObjectInput.java:123) ~[dubbo-2.6.0.jar!/:2.6.0]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:90) ~[dubbo-2.6.0.jar!/:2.6.0]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:110) ~[dubbo-2.6.0.jar!/:2.6.0]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCodec.decodeBody(DubboCodec.java:88) ~[dubbo-2.6.0.jar!/:2.6.0]
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:121) ~[dubbo-2.6.0.jar!/:2.6.0]
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:82) ~[dubbo-2.6.0.jar!/:2.6.0]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCountCodec.decode(DubboCountCodec.java:44) ~[dubbo-2.6.0.jar!/:2.6.0]
	at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalDecoder.messageReceived(NettyCodecAdapter.java:133) ~[dubbo-2.6.0.jar!/:2.6.0]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80) ~[netty-3.2.5.Final.jar!/:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.2.5.Final.jar!/:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) ~[netty-3.2.5.Final.jar!/:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274) ~[netty-3.2.5.Final.jar!/:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261) ~[netty-3.2.5.Final.jar!/:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:349) ~[netty-3.2.5.Final.jar!/:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280) ~[netty-3.2.5.Final.jar!/:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200) ~[netty-3.2.5.Final.jar!/:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.2.5.Final.jar!/:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:44) ~[netty-3.2.5.Final.jar!/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_172]

**Comment by Bricks-Man** [comment]
Could you please upload a demo project on github?

**Comment by hqhe-nj** [comment]
I encounted the same issue. Dont know the reason for this exception.

**Comment by hesy007** [comment]
I encountered the same issue too

**Comment by AlbumenJ** [comment]
This might be an issue of kryo.

Close for long time no response. Please feel free to reopen if you have any question.
