### ISSUE TITLE
请大神帮忙！dubbo 启动警告 warn [DUBBO] Failed to start NettyClient 'xxx'connect to the server 'yyy' (check == false, ignore and retry later!)

### ISSUE THREAD

**Issue by hanchao-c** [apache/dubbo#3911]
### 环境

* Dubbo version: 2.7.1
* Operating System version: windows
* Java version: 1.8
* zookeeper version : 3.4.12 一台

### 引用

```
         <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-framework</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-recipes</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.zookeeper</groupId>
            <artifactId>zookeeper</artifactId>
        </dependency>
```

### 问题描述

```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:dubbo="http://dubbo.apache.org/schema/dubbo" 
	xmlns="http://www.springframework.org/schema/beans"
	xsi:schemaLocation="http://www.springframework.org/schema/beans
		http://www.springframework.org/schema/beans/spring-beans-4.2.xsd
		http://dubbo.apache.org/schema/dubbo 
		http://dubbo.apache.org/schema/dubbo/dubbo.xsd">
		
	<dubbo:application name="${spring.application.name}" logger="slf4j">
		<dubbo:parameter key="qos.enable" value="false"/>
	</dubbo:application>
  	
	<dubbo:registry protocol="zookeeper" address="${dubbo.registry.zookeeper.address}" 
	file="${user.home}/dubbo-cache/${spring.application.name}.dubbo.cache" check="false" />
	
	<dubbo:protocol name="dubbo" port="${dubbo.protocol.port}" />
	
	    <!-- consumer -->
    <dubbo:consumer id="default_consumer" check="false" mock="false" />
    <dubbo:reference consumer="default_consumer" id="payRecordProvider" interface="org.tinker.payment.provider.PayRecordProvider" />
    
</beans>
```
设置了 check="false" 但是项目启动是时候 还是 有如下日志!
在非首次连接生产者的情况下，如果生产者没有启动就会出现这种warn，警告生产者没有启动，虽然这不是error，但是项目启动的时候可能会误导开发者。在清空了zookeeper下的dubbo/org.tinker.payment.provider.PayRecordProvider的情况下就不会出现这样的日志。

除了从日志上过滤的方法之外。
请问如何从配置上解决日志输出当前warn的问题？

通过断点跟踪发现
org.apache.dubbo.remoting.transport.netty4.doConnect() 异常抛出
org.apache.dubbo.registry.zookeeper.ZookeeperRegistry.doSubscribe()具体的解析过程

```
20190423-113606-493  WARN  AbstractClient:74-  [DUBBO] Failed to start NettyClient PC-201803021701/10.3.0.146 connect to the server /10.3.0.146:20882 (check == false, ignore and retry later!), cause: client(url: dubbo://10.3.0.146:20882/org.tinker.payment.provider.PayRecordProvider?anyhost=true&application=tinker-order&bean.name=org.tinker.payment.provider.PayRecordProvider&check=false&codec=dubbo&default.check=false&default.deprecated=false&default.dynamic=false&default.lazy=false&default.mock=false&default.register=true&default.retries=2&default.sticky=false&default.timeout=5000&deprecated=false&dubbo=2.0.2&dynamic=false&generic=false&heartbeat=60000&interface=org.tinker.payment.provider.PayRecordProvider&lazy=false&logger=slf4j&methods=notice&pid=9068&qos.enable=false&register=true&register.ip=10.3.0.146&release=2.7.1&remote.application=tinker-payment&remote.timestamp=1555913582220&side=consumer&sticky=false&timestamp=1555990564828) failed to connect to server /10.3.0.146:20882, error message is:Connection refused: no further information: /10.3.0.146:20882, dubbo version: 2.7.1, current host: 10.3.0.146
org.apache.dubbo.remoting.RemotingException: client(url: dubbo://10.3.0.146:20882/org.tinker.payment.provider.PayRecordProvider?anyhost=true&application=tinker-order&bean.name=org.tinker.payment.provider.PayRecordProvider&check=false&codec=dubbo&default.check=false&default.deprecated=false&default.dynamic=false&default.lazy=false&default.mock=false&default.register=true&default.retries=2&default.sticky=false&default.timeout=5000&deprecated=false&dubbo=2.0.2&dynamic=false&generic=false&heartbeat=60000&interface=org.tinker.payment.provider.PayRecordProvider&lazy=false&logger=slf4j&methods=notice&pid=9068&qos.enable=false&register=true&register.ip=10.3.0.146&release=2.7.1&remote.application=tinker-payment&remote.timestamp=1555913582220&side=consumer&sticky=false&timestamp=1555990564828) failed to connect to server /10.3.0.146:20882, error message is:Connection refused: no further information: /10.3.0.146:20882
	at org.apache.dubbo.remoting.transport.netty4.NettyClient.doConnect(NettyClient.java:131)
	at org.apache.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:186)
	at org.apache.dubbo.remoting.transport.AbstractClient.<init>(AbstractClient.java:65)
	at org.apache.dubbo.remoting.transport.netty4.NettyClient.<init>(NettyClient.java:57)
	at org.apache.dubbo.remoting.transport.netty4.NettyTransporter.connect(NettyTransporter.java:37)
	at org.apache.dubbo.remoting.Transporter$Adaptive.connect(Transporter$Adaptive.java)
	at org.apache.dubbo.remoting.Transporters.connect(Transporters.java:75)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchanger.connect(HeaderExchanger.java:39)
	at org.apache.dubbo.remoting.exchange.Exchangers.connect(Exchangers.java:109)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.initClient(DubboProtocol.java:577)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.buildReferenceCountExchangeClient(DubboProtocol.java:545)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.buildReferenceCountExchangeClientList(DubboProtocol.java:532)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getSharedClient(DubboProtocol.java:457)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getClients(DubboProtocol.java:412)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.refer(DubboProtocol.java:389)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:67)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:72)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:116)
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at org.apache.dubbo.registry.integration.RegistryDirectory.toInvokers(RegistryDirectory.java:408)
	at org.apache.dubbo.registry.integration.RegistryDirectory.refreshInvoker(RegistryDirectory.java:265)
	at org.apache.dubbo.registry.integration.RegistryDirectory.refreshOverrideAndInvoker(RegistryDirectory.java:224)
	at org.apache.dubbo.registry.integration.RegistryDirectory.notify(RegistryDirectory.java:218)
	at org.apache.dubbo.registry.support.AbstractRegistry.notify(AbstractRegistry.java:399)
	at org.apache.dubbo.registry.support.FailbackRegistry.doNotify(FailbackRegistry.java:364)
	at org.apache.dubbo.registry.support.FailbackRegistry.notify(FailbackRegistry.java:355)
	at org.apache.dubbo.registry.zookeeper.ZookeeperRegistry.doSubscribe(ZookeeperRegistry.java:169)
	at org.apache.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:290)
	at org.apache.dubbo.registry.integration.RegistryDirectory.subscribe(RegistryDirectory.java:157)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:386)
	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:367)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:65)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:70)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:114)
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:366)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:305)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:231)
	at org.apache.dubbo.config.spring.ReferenceBean.getObject(ReferenceBean.java:71)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:171)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:101)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1674)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1249)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:257)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1470)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1427)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1210)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1411)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1411)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at org.tinker.order.server.Application.main(Application.java:14)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /10.3.0.146:20882
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:665)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused: no further information
	... 11 common frames omitted
```

### 请大神帮忙 多谢！！！

**Comment by luoning810** [comment]
provider 发布时，@Service#dynamic() 设置为true

**Comment by cwtree** [comment]
同样的问题，求解
