### ISSUE TITLE
UT failure for EtcdMetadataReport

### ISSUE THREAD

**Issue by ralf0131** [apache/dubbo#4008]
```
[INFO] Running org.apache.dubbo.metadata.store.etcd.EtcdMetadataReportTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
        â„¹ï¸Ž Checking the system...
        âœ” Docker version should be at least 1.6.0
        âœ” Docker environment should have more than 2GB free disk space
```

**Comment by Moriadry** [comment]
Do you mean the fail of loading slf4j StaticLoggerBinder? I found this ut works well.

**Comment by biyuhao** [comment]
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.dubbo.metadata.store.etcd.EtcdMetadataReportTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 10.492 s <<< FAILURE! - in org.apache.dubbo.metadata.store.etcd.EtcdMetadataReportTest
[ERROR] testStoreProvider  Time elapsed: 0.009 s  <<< ERROR!
java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
	at org.apache.dubbo.metadata.store.etcd.EtcdMetadataReportTest.<init>(EtcdMetadataReportTest.java:54)

[ERROR] testStoreConsumer  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
	at org.apache.dubbo.metadata.store.etcd.EtcdMetadataReportTest.<init>(EtcdMetadataReportTest.java:54)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   EtcdMetadataReportTest.<init>:54 » IllegalState Previous attempts to find a Do...
[ERROR]   EtcdMetadataReportTest.<init>:54 » IllegalState Could not find a valid Docker ...
[INFO] 
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
```
Appropriate docker environment is required for UT now.

**Comment by ralf0131** [comment]
@biyuhao Yes, the UT for Etcd requires a docker environment. So local UT make fail unless you have installed docker. Travis machines do have docker installed, so most of the cases it should pass. The issue I reported looks like some edge case, maybe one of the machines does not meet the requirement.

p.s. Whether or not using docker to test Etcd is another question, that can be discussed.

**Comment by ralf0131** [comment]
According to this [doc](https://www.testcontainers.org/features/configuration), I think we should disable the startup check.

Add `testcontainers.properties` on classpath,  and add `checks.disable = true`


Before running any containers Testcontainers will perform a set of startup checks to ensure that your environment is configured correctly. Usually they look like this:


        ℹ︎ Checking the system...
        ✔ Docker version should be at least 1.6.0
        ✔ Docker environment should have more than 2GB free disk space
        ✔ File should be mountable
        ✔ A port exposed by a docker container should be accessible

**Comment by liketic** [comment]
hi @ralf0131 I opened #4803
