### ISSUE TITLE
没有找到LoadBalance的错误

### ISSUE THREAD

**Issue by cossbow** [apache/dubbo#4089]
服务器上遇到一个错误出现在消费者方，以下是具体的异常信息：

```
java.lang.IllegalStateException: No such extension org.apache.dubbo.rpc.cluster.LoadBalance by name random
        at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:516) ~[dubbo-2.7.1.jar!/:2.7.1]
        at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:523) ~[dubbo-2.7.1.jar!/:2.7.1]
        at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:347) ~[dubbo-2.7.1.jar!/:2.7.1]
        at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.initLoadBalance(AbstractClusterInvoker.java:290) ~[dubbo-2.7.1.jar!/:2.7.1]
        at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:240) ~[dubbo-2.7.1.jar!/:2.7.1]
        at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:76) ~[dubbo-2.7.1.jar!/:2.7.1]
        at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:57) ~[dubbo-2.7.1.jar!/:2.7.1]
        at org.apache.dubbo.common.bytecode.proxy2.saveProviderRateStatus(proxy2.java) ~[dubbo-2.7.1.jar!/:2.7.1]
        at jdk.internal.reflect.GeneratedMethodAccessor266.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor$ReferenceBeanInvocationHandler.invoke(ReferenceAnnotationBeanPostProcessor.java:165) ~[dubbo-2.7.1.jar!/:2.7.1]
        at com.sun.proxy.$Proxy111.saveProviderRateStatus(Unknown Source) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor266.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88) ~[spring-aop-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
        at com.fmrt.trade.aop.RpcExceptionAspectHandler.exception(RpcExceptionAspectHandler.java:26) ~[rpc-client-aop-0.1.1.jar!/:0.1.1]
        at jdk.internal.reflect.GeneratedMethodAccessor224.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644) ~[spring-aop-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633) ~[spring-aop-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
```

**Comment by Leishunyu** [comment]
Can you provide more detailed configuration information?

**Comment by cossbow** [comment]
almost default, see below:
dubbo:
  application:
    name: trade-admin
    qos-enable: false
  registry:
    address: zookeeper://172.26.9.168:2181
  consumer:
    init: true
    timeout: 180000

**Comment by Leishunyu** [comment]
The exception information you gave shows that it is a problem with spi loading the load balancing strategy. It may be that some dependencies are missing, but you don't appear locally.

**Comment by cossbow** [comment]
是的，本地没出现，奇怪的是在服务器上间歇性出现，直到我手动指定loadbalance = RoundRobinLoadBalance.NAME 才正常的

**Comment by Leishunyu** [comment]
> 是的，本地没出现，奇怪的是在服务器上间歇性出现，直到我手动指定loadbalance = RoundRobinLoadBalance.NAME 才正常的
Can you check if the source package of dubbo on the server contains RandomLoadBalance?

**Comment by SimpleLym** [comment]
我这边也出现这个问题了，打包之后在服务器上跑起来基本是必现的，我debug跟踪了一下，发现是org.apache.dubbo.common.extension.ExtensionLoader中的findClassLoader 获取的classLoader getResources为空，使用ExtensionLoader.class.getClassLoader() 获得的classLoader是可以获取资源的，麻烦阿里的同学看下是不是ClassUtils.getClassLoader(ExtensionLoader.class)的问题？

**Comment by kiss-yu** [comment]
这个问题解决了？2.7.12版本依然有这个问题，指定leastactive也找不到，本地可以

**Comment by AlbumenJ** [comment]
> 这个问题解决了？2.7.12版本依然有这个问题，指定leastactive也找不到，本地可以

排查下线上的 classloader 是不是没有找到对应的 class，如果使用 dubbo-all 方式导入的应该在 dubbo.jar 里面会有的

**Comment by guoxianxian** [comment]
> > 这个问题解决了？2.7.12版本依然有这个问题，指定leastactive也找不到，本地可以
> 
> 排查下线上的 classloader 是不是没有找到对应的 class，如果使用 dubbo-all 方式导入的应该在 dubbo.jar 里面会有的

我也是这个问题，用的特殊的打包方式，没法看源码

**Comment by kiss-yu** [comment]
> > > 这个问题解决了？2.7.12版本依然有这个问题，指定leastactive也找不到，本地可以
> > 
> > 
> > 排查下线上的 classloader 是不是没有找到对应的 class，如果使用 dubbo-all 方式导入的应该在 dubbo.jar 里面会有的
> 
> 我也是这个问题，用的特殊的打包方式，没法看源码

现在直接自定义了LoadBalance，没用自带的。没出现这个错误了。

**Comment by qixiaobo** [comment]
Maybe some problems with classloader?
