### ISSUE TITLE
2.7.2 启动服务报错

### ISSUE THREAD

**Issue by spiritme1984** [apache/dubbo#4271]
### Environment
* Dubbo version: 2.7.2
* Operating System version: window10
* Java version: 1.8

### Steps to reproduce this issue
把项目从2.5.3升级到2.7.2, 修改引用版本后启动服务，系统提示如下错误：

2019-06-10 14:14:25.977 [crm7] [ERROR] [,] [localhost-startStop-1] org.apache.dubbo.config.AbstractConfig.refresh(AbstractConfig.java:577)  [DUBBO] Failed to override , dubbo version: 2.7.2, current host: 192.168.14.179

java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor357.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.dubbo.config.AbstractConfig.refresh(AbstractConfig.java:567)
	at org.apache.dubbo.config.ServiceConfig.checkAndUpdateSubConfigs(ServiceConfig.java:304)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:369)
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:336)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:114)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:60)
	at 
...

Caused by: java.lang.IllegalArgumentException: Unsupported generic type false
	at org.apache.dubbo.config.ServiceConfig.setGeneric(ServiceConfig.java:1015)
	... 34 more

在配置文件中并没有配置generic，请问如何避免这个错误提示，是否需要增加一些设置？

**Comment by web1992** [comment]
Did you use XML to config Dubbo?
If yes, please check you XML config:

```xml
<dubbo:service generic="false" />
```
You can delee `generic="false"` in you XML config

**Comment by spiritme1984** [comment]
> Did you use XML to config Dubbo?
> If yes, please check you XML config:
> 
> ```
> <dubbo:service generic="false" />
> ```
> 
> You can delete `generic="false"` in you XML config and try again.

I did use XML to config Dubbo. But I didn't have 'generic="false"' in provider XML files.
Whether the default value is false? 
Here is my XML:
<dubbo:service
interface="cn.com.xxx.dubbo.baseservice.DubboDefaultAlipayCompanyService"
		ref="dubboDefaultAlipayCompanyServiceImpl" />
....

**Comment by chickenlj** [comment]
>Caused by: java.lang.IllegalArgumentException: Unsupported generic type false
at org.apache.dubbo.config.ServiceConfig.setGeneric(ServiceConfig.java:1015)
... 34 more

1. 你能否定位到generic的"false"是从哪个配置源来的？
2. "false"是一个合理的配置值，check条件应该将true和false考虑在内。

**Comment by chickenlj** [comment]
```java
public static boolean isGeneric(String generic) {
        return generic != null
                && !"".equals(generic)
                && (GENERIC_SERIALIZATION_DEFAULT.equalsIgnoreCase(generic)  /* Normal generalization cal */
                || GENERIC_SERIALIZATION_NATIVE_JAVA.equalsIgnoreCase(generic) /* Streaming generalization call supporting jdk serialization */
                || GENERIC_SERIALIZATION_BEAN.equalsIgnoreCase(generic)
                || GENERIC_SERIALIZATION_PROTOBUF.equalsIgnoreCase(generic));
    }
```

一直以来，框架都是不允许显示设置generic=false。另外，你这里收到的error报错是一个告警日志，并不影响程序正常启动。

**Comment by spiritme1984** [comment]
...今天重启又好了，什么都没改，感谢提供意见的同学，关闭了
