### ISSUE TITLE
demo run with zookeeper registery exception

### ISSUE THREAD

**Issue by zhenxianyimeng** [apache/dubbo#4350]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: master
* Operating System version: macos  10.14.3
* Java version: 1.8.0_201-b09

### Steps to reproduce this issue

1. demo-xml model，use zookeeper registery  just  change:
       <dubbo:registry address="multicast://224.5.6.7:1234" />
    to 
   <dubbo:registry protocol="zookeeper" address="127.0.0.1:2181" />

2.Exception：
java.lang.IllegalStateException: No such extension org.apache.dubbo.registry.RegistryFactory by name zookeeper

3.solution:
add maven dependency in demo pom as:
```
 <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-registry-zookeeper</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-configcenter-zookeeper</artifactId>
        </dependency>
```
maybe it's not useful in multicast registry, so may be some lines in readme can help

### Expected Result
can run without Exception

### Actual Result
Exception：
java.lang.IllegalStateException: No such extension org.apache.dubbo.registry.RegistryFactory by name zookeeper

```
java.lang.IllegalStateException: No such extension org.apache.dubbo.registry.RegistryFactory by name zookeeper
	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:520)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:527)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:351)
	at org.apache.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)
	at org.apache.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:298)
	at org.apache.dubbo.registry.integration.RegistryProtocol.access$1100(RegistryProtocol.java:111)
	at org.apache.dubbo.registry.integration.RegistryProtocol$ExporterChangeableWrapper.unexport(RegistryProtocol.java:669)
	at org.apache.dubbo.registry.integration.RegistryProtocol.destroy(RegistryProtocol.java:442)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.destroy(ProtocolFilterWrapper.java:135)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.destroy(ProtocolListenerWrapper.java:79)
	at org.apache.dubbo.config.DubboShutdownHook.destroyProtocols(DubboShutdownHook.java:103)
	at org.apache.dubbo.config.DubboShutdownHook.doDestroy(DubboShutdownHook.java:91)
	at org.apache.dubbo.config.spring.extension.SpringExtensionFactory$ShutdownHookListener.onApplicationEvent(SpringExtensionFactory.java:114)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:991)
	at org.springframework.context.support.AbstractApplicationContext$2.run(AbstractApplicationContext.java:929)```

**Comment by kexianjun** [comment]
pls add dubbo-registry-zookeeper dependency in your project
