### ISSUE TITLE
[ISSUE] In dubbo-2.7.2, Dubbo + Nacos throw 404 error

### ISSUE THREAD

**Issue by cvictory** [apache/dubbo#4353]
```
ErrCode:500,ErrMsg:failed to req API:http://127.0.0.1:8848/nacos/v1/ns/instance/list. code:404 msg: service not found: DEFAULT_GROUP@@configurators:org.apache.dubbo.samples.basic.api.DemoService::
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:340)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273)
	at com.alibaba.nacos.client.naming.core.HostReactor.getServiceInfo(HostReactor.java:232)
	at com.alibaba.nacos.client.naming.NacosNamingService.getAllInstances(NacosNamingService.java:373)
	at com.alibaba.nacos.client.naming.NacosNamingService.getAllInstances(NacosNamingService.java:365)
	at com.alibaba.nacos.client.naming.NacosNamingService.getAllInstances(NacosNamingService.java:354)
	at com.alibaba.nacos.client.naming.NacosNamingService.getAllInstances(NacosNamingService.java:334)
	at org.apache.dubbo.registry.nacos.NacosRegistry.lambda$doSubscribe$3(NacosRegistry.java:173)
	at org.apache.dubbo.registry.nacos.NacosRegistry.execute(NacosRegistry.java:454)
	at org.apache.dubbo.registry.nacos.NacosRegistry.doSubscribe(NacosRegistry.java:171)
	at org.apache.dubbo.registry.nacos.NacosRegistry.doSubscribe(NacosRegistry.java:167)
	at org.apache.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:295)
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:224)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:59)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:120)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:61)
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:607)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:457)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:415)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:378)
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:336)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:114)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:60)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at org.apache.dubbo.samples.basic.BasicProvider.main(BasicProvider.java:30)
[20/06/19 10:29:36:036 CST] main ERROR client.naming: [NA] failed to update serviceName: DEFAULT_GROUP@@configurators:org.apache.dubbo.samples.basic.api.DemoService::
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/list after all servers([127.0.0.1:8848]) tried: failed to req API:http://127.0.0.1:8848/nacos/v1/ns/instance/list. code:404 msg: service not found: DEFAULT_GROUP@@configurators:org.apache.dubbo.samples.basic.api.DemoService::
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:380)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273)
	at com.alibaba.nacos.client.naming.core.HostReactor.getServiceInfo(HostReactor.java:232)
	at com.alibaba.nacos.client.naming.NacosNamingService.getAllInstances(NacosNamingService.java:373)
	at com.alibaba.nacos.client.naming.NacosNamingService.getAllInstances(NacosNamingService.java:365)
	at com.alibaba.nacos.client.naming.NacosNamingService.getAllInstances(NacosNamingService.java:354)
	at com.alibaba.nacos.client.naming.NacosNamingService.getAllInstances(NacosNamingService.java:334)
	at org.apache.dubbo.registry.nacos.NacosRegistry.lambda$doSubscribe$3(NacosRegistry.java:173)
	at org.apache.dubbo.registry.nacos.NacosRegistry.execute(NacosRegistry.java:454)
	at org.apache.dubbo.registry.nacos.NacosRegistry.doSubscribe(NacosRegistry.java:171)
	at org.apache.dubbo.registry.nacos.NacosRegistry.doSubscribe(NacosRegistry.java:167)
	at org.apache.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:295)
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:224)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:59)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:120)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:61)
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:607)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:457)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:415)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:378)
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:336)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:114)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:60)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
```

**Comment by htynkn** [comment]
maybe also consider upgrade nacos client version to latest one

**Comment by 502085563** [comment]
i was try it ,but it also report bug like this ,may be there are some bugs in nacos or dubbo

**Comment by sunbufu** [comment]
Can you provide the relevant code and configuration? I cannot reproduce this issue.
