### ISSUE TITLE
UT failure for RedisMetadataReportTest

### ISSUE THREAD

**Issue by htynkn** [apache/dubbo#4373]
https://api.travis-ci.org/v3/job/548777690/log.txt

```
[INFO] Running org.apache.dubbo.metadata.store.redis.RedisMetadataReportTest
log4j:WARN No appenders could be found for logger (org.apache.dubbo.common.logger.LoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.565 s <<< FAILURE! - in org.apache.dubbo.metadata.store.redis.RedisMetadataReportTest
[ERROR] testAuthRedisMetadata  Time elapsed: 0.091 s  <<< ERROR!
redis.embedded.exceptions.EmbeddedRedisException: Failed to start Redis instance
	at org.apache.dubbo.metadata.store.redis.RedisMetadataReportTest.constructor(RedisMetadataReportTest.java:67)
Caused by: java.io.IOException: Cannot run program "/tmp/1561140977100-0/redis-server-2.8.19" (in directory "/tmp/1561140977100-0"): error=26, Text file busy
	at org.apache.dubbo.metadata.store.redis.RedisMetadataReportTest.constructor(RedisMetadataReportTest.java:67)
Caused by: java.io.IOException: error=26, Text file busy
	at org.apache.dubbo.metadata.store.redis.RedisMetadataReportTest.constructor(RedisMetadataReportTest.java:67)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   RedisMetadataReportTest.constructor:67 Â» EmbeddedRedis Failed to start Redis i...
[INFO] 
[ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by cvictory** [comment]
I find it work well.
