### ISSUE TITLE
The Dubbo registration center uses nacos, the service display is normal, and the log keeps reporting errors.

### ISSUE THREAD

**Issue by nkorange** [apache/dubbo#4423]
Copied from [nacos#1396](https://github.com/alibaba/nacos/issues/1396), @mercyblitz has confirmed this is a bug of Dubbo.

服务列表里可以查询到，但是日志报错。

报错内容如下：

```
[19/06/19 04:21:36:036 CST] com.alibaba.nacos.client.naming.updater ERROR client.naming: [NA] failed to update serviceName: DEFAULT_GROUP@@configurators:org.apache.dubbo.samples.basic.api.DemoService::
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/list after all servers([127.0.0.1:8848]) tried: failed to req API:http://127.0.0.1:8848/nacos/v1/ns/instance/list. code:404 msg: service not found: DEFAULT_GROUP@@configurators:org.apache.dubbo.samples.basic.api.DemoService::
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:380)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:318)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by zk123456** [comment]
有什么方法可以在启动的时候不校验引用的提供者吗

**Comment by cvictory** [comment]
It will be fixed in dubbo 2.7.3.  @mercyblitz

**Comment by cvictory** [comment]
duplicate https://github.com/apache/dubbo/issues/4353

**Comment by tonypig** [comment]
这个问题很困扰啊，2.7.3 计划啥时候发布

**Comment by htynkn** [comment]
@tonypig 2.7.3已经发布
https://mvnrepository.com/artifact/org.apache.dubbo/dubbo/2.7.3
