### ISSUE TITLE
dubbo can not find provider or consumer   for nacos ,but the provider status is running on nacos 

### ISSUE THREAD

**Issue by vikenlove** [apache/dubbo#4450]
```
org.apache.dubbo.remoting.RemotingException: Not found exported service: simple-tax-client-consumer/org.springframework.cloud.alibaba.dubbo.service.DubboMetadataService:1.0.0:20880 in [com.cloud.zxt.js.simple.tax.service.NavigationService:1.0.0:20880, com.cloud.zxt.js.simple.tax.service.ActionRecordService:1.0.0:20880, simple-tax-server-provider/org.springframework.cloud.alibaba.dubbo.service.DubboMetadataService:1.0.0:20880, com.cloud.zxt.js.simple.tax.service.InformationService:1.0.0:20880, com.cloud.zxt.js.simple.tax.service.NoticeService:1.0.0:20880, com.cloud.zxt.js.simple.tax.service.PsystemService:1.0.0:20880, com.cloud.zxt.js.simple.tax.service.AdService:1.0.0:20880, com.cloud.zxt.js.simple.tax.service.FloatWindowService:1.0.0:20880, com.cloud.zxt.js.simple.tax.service.DmAreaService:1.0.0:20880], may be version or group mismatch , channel: consumer: /127.0.0.1:45296 --> provider: /127.0.0.1:20880, message:RpcInvocation [methodName=$invoke, parameterTypes=[class java.lang.String, class [Ljava.lang.String;, class [Ljava.lang.Object;], arguments=[getExportedURLs, [Ljava.lang.String;@3f624c02, [Ljava.lang.Object;@3376fdf8], attachments={path=org.springframework.cloud.alibaba.dubbo.service.DubboMetadataService, input=532, dubbo=2.0.2, interface=org.springframework.cloud.alibaba.dubbo.service.DubboMetadataService, version=1.0.0, generic=true, group=simple-tax-client-consumer}]
        at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:248)
        at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:102)
        at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:103)
        at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:200)
        at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
        at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
        at org.apache.dubbo.remoting.exchange.support.DefaultFuture.returnFromResponse(DefaultFuture.java:297) ~[dubbo-2.7.1.jar!/:2.7.1]
        at org.apache.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:191) ~[dubbo-2.7.1.jar!/:2.7.1]
        at org.apache.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:164) ~[dubbo-2.7.1.jar!/:2.7.1]
        at org.apache.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:108) ~[dubbo-2.7.1.jar!/:2.7.1]
        at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:157) ~[dubbo-2.7.1.jar!/:2.7.1]
        at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:78) ~[dubbo-2.7.1.jar!/:2.7.1]
        at org.apache.dubbo.rpc.filter.GenericImplFilter.invoke(GenericImplFilter.java:172) ~[dubbo-2.7.1.jar!/:2.7.1]
        at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73) ~[dubbo-2.7.1.jar!/:2.7.1]
        at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:88) ~[dubbo-2.7.1.jar!/:2.7.1]
        at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73) ~[dubbo-2.7.1.jar!/:2.7.1]
        at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:49) ~[dubbo-2.7.1.jar!/:2.7.1]
        at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73) ~[dubbo-2.7.1.jar!/:2.7.1]
        at org.apache.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:54) ~[dubbo-2.7.1.jar!/:2.7.1]
        at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73) ~[dubbo-2.7.1.jar!/:2.7.1]
        at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56) ~[dubbo-2.7.1.jar!/:2.7.1]
        at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:80) ~[dubbo-2.7.1.jar!/:2.7.1]
```

**Comment by ralf0131** [comment]
Please provide steps to reproduce this issue.

**Comment by vikenlove** [comment]
@ralf0131 please call me for dingding ok?

**Comment by cvictory** [comment]
Please provide steps to reproduce this issue， or you can upload a demo.

**Comment by beiwei30** [comment]
cannot reproduce, pls. provide the app to demo the issue on github. Feel free to repopen once you provide the demo app.

**Comment by cens7** [comment]
I'm also
