### ISSUE TITLE
优化下no provider提示

### ISSUE THREAD

**Issue by dcqyzb** [apache/dubbo#4457]
dubbo服务调用失败原因不是很清楚，查找问题不放便，报错的时候把consumer端使用的protocol也顺便输出出来

**Comment by cvictory** [comment]
日志输出是：
```
Exception in thread "main" com.alibaba.dubbo.rpc.RpcException: No provider available from registry 127.0.0.1:2181 for service org.apache.dubbo.samples.api.GreetingService on consumer 169.254.238.147 use dubbo version 2.6.6, please check status of providers(disabled, not registered or in blacklist).
	at com.alibaba.dubbo.registry.integration.RegistryDirectory.doList(RegistryDirectory.java:588)
	at com.alibaba.dubbo.rpc.cluster.directory.AbstractDirectory.list(AbstractDirectory.java:75)
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.list(AbstractClusterInvoker.java:277)
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:238)
	at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:75)
	at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52)
	at com.alibaba.dubbo.common.bytecode.proxy0.greeting(proxy0.java)
	at org.apache.dubbo.samples.client.Application.main(Application.java:32)
```

基本还是很清晰，不知道你还需要什么信息？ 提issue的时候，最好给下上下文，不然很难理解。

**Comment by beiwei30** [comment]
> dubbo服务调用失败原因不是很清楚，查找问题不放便，报错的时候把consumer端使用的protocol也顺便输出出来

In this case, when provider doesn't exist in the registry server, there's no way to judge the protocol the consumer is to use. The reason is, the protocol to be used on the consumer side is in fact decided by the URL registered by the provider.
