### ISSUE TITLE
No such extension org.apache.dubbo.metadata.store.MetadataReportFactory by name zookeeper

### ISSUE THREAD

**Issue by zpLiuHH** [apache/dubbo#4507]
### Environment

* Dubbo version: 2.7.3
* Java version: 1.8

在clone了最新代码后修改了org.apache.dubbo.demo.provider.Application中的main方法，具体如下：
 @Bean
        public RegistryConfig registryConfig() {
            RegistryConfig registryConfig = new RegistryConfig();
//            registryConfig.setAddress("multicast://224.5.6.7:1234");
            registryConfig.setAddress("zookeeper://127.0.0.1:2181");
            return registryConfig;
        }
然后执行main方法后一直报错，目前dubbo-demo下实例都无法正常运行，请大家指教一下这个是什么原因造成的，报错信息如下：
Exception in thread "main" java.lang.IllegalStateException: No such extension org.apache.dubbo.metadata.store.MetadataReportFactory by name zookeeper
	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:520)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:527)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:351)
	at org.apache.dubbo.metadata.store.MetadataReportFactory$Adaptive.getMetadataReport(MetadataReportFactory$Adaptive.java)
	at org.apache.dubbo.metadata.integration.MetadataReportService.<init>(MetadataReportService.java:69)
	at org.apache.dubbo.metadata.integration.MetadataReportService.instance(MetadataReportService.java:82)
	at org.apache.dubbo.config.AbstractInterfaceConfig.getMetadataReportService(AbstractInterfaceConfig.java:433)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:622)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:457)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:415)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:378)
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:336)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:114)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:60)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at org.apache.dubbo.demo.provider.Application.main(Application.java:28)

**Comment by web1992** [comment]
应该是依赖没有正确的添加，检查下 maven 依赖，看下的这个依赖是否存在。
```xml
<groupId>org.apache.dubbo</groupId>
<artifactId>dubbo-metadata-report-zookeeper</artifactId>
```

**Comment by zpLiuHH** [comment]
@web1992 pom中有加这个依赖。

**Comment by chickenlj** [comment]
尝试重新build demo，可能还是依赖问题。你添加了metadata report配置了吗？

**Comment by zpLiuHH** [comment]
@chickenlj 重新build了demo，在dubbo-provider.xml中也有加如下配置：
<dubbo:config-center address="zookeeper://127.0.0.1:2181"/>
<dubbo:metadata-report  address="zookeeper://127.0.0.1:2181"/>
还是会报那个错。

**Comment by zpLiuHH** [comment]
@web1992@chickenlj 感谢二位，重新把最新的代码clone到本地，然后在dubbo-demo-xml和dubbo-demo-annotation的pom文件中加入了
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-metadata-report-zookeeper</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
在dubbo-provider.xml和dubbo-provider.properties中分别加入了如下配置：dubbo.configcenter=zookeeper://127.0.0.1:2181
dubbo.metadata-report.address=zookeeper://127.0.0.1:2181
然后成功运行，并在dubbo-admin的管理界面及服务的详细页面元数据部分能正常显示。
总结来说应该还是配置和pom的原因。
