### ISSUE TITLE
2.7.1 java.lang.IllegalStateException: No such extension org.apache.dubbo.rpc.Protocol by name dubbo

### ISSUE THREAD

**Issue by wecloud2008** [apache/dubbo#4532]
java.lang.IllegalStateException: No such extension org.apache.dubbo.rpc.Protocol by name dubbo
	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:516) ~[dubbo-common-2.7.1.jar:2.7.1]
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:523) ~[dubbo-common-2.7.1.jar:2.7.1]
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:347) ~[dubbo-common-2.7.1.jar:2.7.1]
	at org.apache.dubbo.config.ServiceConfig.findConfigedPorts(ServiceConfig.java:696) ~[dubbo-config-api-2.7.1.jar:2.7.1]
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:517) ~[dubbo-config-api-2.7.1.jar:2.7.1]
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:417) ~[dubbo-config-api-2.7.1.jar:2.7.1]
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:375) ~[dubbo-config-api-2.7.1.jar:2.7.1]
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:337) ~[dubbo-config-api-2.7.1.jar:2.7.1]
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:319) ~[dubbo-config-spring-2.7.1.jar:2.7.1]
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:113) ~[dubbo-config-spring-2.7.1.jar:2.7.1]
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:59) ~[dubbo-config-spring-2.7.1.jar:2.7.1]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:896) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at com.fahuo123.fh.FhApplication.main(FhApplication.java:24) [classes/:na]

2019-07-10 23:10:49.406  INFO 4716 --- [           main] .b.c.e.AwaitingNonWebApplicationListener :  [Dubbo] Current Spring Boot Application is about to shutdown...
2019-07-10 23:10:49.415  INFO 4716 --- [           main] f.a.ReferenceAnnotationBeanPostProcessor : class org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor was destroying!

Process finished with exit code 1

**Comment by wecloud2008** [comment]
解决

       <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo</artifactId>
            <version>2.7.1</version>
        </dependency>
