### ISSUE TITLE
random token causes Invalid Token Exception when retry another provider

### ISSUE THREAD

**Issue by LeoLiangJin** [apache/dubbo#4550]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.2
* Operating System version: linux
* Java version: 1.8

### Steps to reproduce this issue

1. dubbo.provider.token=${random.uuid}
2. launch two providers
3. invoke failed and retry the other provider

### Expected Result

token should be valid

### Actual Result
token is invalid
```
com.alibaba.dubbo.rpc.RpcException: Invalid token! Forbid invoke remote service interface com.darcytech.hera.api.service.SmsService method sendSms() from consumer 192.168.24.81 to provider 192.168.24.82
        at com.alibaba.dubbo.rpc.filter.TokenFilter.invoke(TokenFilter.java:46)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
        at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
        at com.darcytech.hera.server.dubbo.ErrorHandleFilter.invoke(ErrorHandleFilter.java:28)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
        at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:72)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
        at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:131)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
        at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
        at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
```

**Comment by LeoLiangJin** [comment]
If use fixed token, I think it won't be a problem.

**Comment by LeoLiangJin** [comment]
dubbo 2.7.2 has fixed this problem.
```code
Map<String, String> contextAttachments = RpcContext.getContext().getAttachments();
        if (CollectionUtils.isNotEmptyMap(contextAttachments)) {
            /**
             * invocation.addAttachmentsIfAbsent(context){@link RpcInvocation#addAttachmentsIfAbsent(Map)}should not be used here,
             * because the {@link RpcContext#setAttachment(String, String)} is passed in the Filter when the call is triggered
             * by the built-in retry mechanism of the Dubbo. The attachment to update RpcContext will no longer work, which is
             * a mistake in most cases (for example, through Filter to RpcContext output traceId and spanId and other information).
             */
            invocation.addAttachments(contextAttachments);
        }


```

**Comment by beiwei30** [comment]
@LeoLiangJin are you saying this issue has been fixed on 2.7 branch but still exists on 2.6?

**Comment by tonydzt** [comment]
在2.7.8版本又出现了这个问题，复现方式跟这个issue步骤是一样的，问题现象也是一样的。
