### ISSUE TITLE
同时用注解和xml配置系统报异常

### ISSUE THREAD

**Issue by jimiyi** [apache/dubbo#4561]
### Environment

* Dubbo version: 2.7.2
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue

1. 在xml文件中增加一些dubbo配置，比如dubbo:application, dubbo:protocol
2. 在接口实现类上增加@service注解
3. 在主启动程序类(spring boot的) 上添加注解@EnableDubbo

### Expected Result
What do you expected from the above steps？
正常启动
### Actual Result
What actually happens?

Caused by: java.lang.IllegalStateException: Invalid name="org.apache.dubbo.config.ProtocolConfig#0" contains illegal character, only digit, letter, '-', '_' or '.' is legal.

If there is an exception, please attach the exception trace:

```
Caused by: java.lang.IllegalStateException: Invalid name="org.apache.dubbo.config.ProtocolConfig#0" contains illegal character, only digit, letter, '-', '_' or '.' is legal.
	at org.apache.dubbo.config.AbstractConfig.checkProperty(AbstractConfig.java:384)
	at org.apache.dubbo.config.AbstractConfig.checkName(AbstractConfig.java:342)
	at org.apache.dubbo.config.ProtocolConfig.setName(ProtocolConfig.java:228)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
	at org.apache.dubbo.config.spring.context.config.NamePropertyDefaultValueDubboConfigBeanCustomizer.customize(NamePropertyDefaultValueDubboConfigBeanCustomizer.java:73)
	at org.apache.dubbo.config.spring.beans.factory.annotation.DubboConfigBindingBeanPostProcessor.customize(DubboConfigBindingBeanPostProcessor.java:117)
	at org.apache.dubbo.config.spring.beans.factory.annotation.DubboConfigBindingBeanPostProcessor.postProcessBeforeInitialization(DubboConfigBindingBeanPostProcessor.java:96)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1686)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573)
	... 15 common frames omitted
```

**Comment by tswstarplanet** [comment]
Can you provide a demo to reproduce the problem ? I have tried using @ImportSource to import xml configuration to an annotation configuration. And it works.

**Comment by cvictory** [comment]
duplicate https://github.com/apache/dubbo/issues/4657
