### ISSUE TITLE
i try to use  Event Notify with Annotation, but it not work 

### ISSUE THREAD

**Issue by GitBaronYang** [apache/dubbo#4599]
### Environment

* Dubbo version: 2.7.2
* Operating System version: windows
* Java version: 1.8

### Steps to reproduce this issue

1.   
 ```java
  @Reference(lazy = true, methods = {@Method(name = "sayHello", async = true,
            oninvoke = "notifyServiceImpl.oninvoke",
            onreturn = "notifyServiceImpl.onreturn",
            onthrow = "notifyServiceImpl.onthrow")})
         DemoService demoService;
```
2. notifyServiceImpl use  @Component to injection
```java
 @Component
  public class NotifyServiceImpl implements NotifyService{
    @Override
    public void oninvoke(String name) {
        try {
            Thread.sleep(3000L);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.println("onInvoke: " + name);
    }
    
    @Override
    public void onreturn(String retName, String name) {
        System.out.println("onReturn: " + name);
    }
    
    @Override
    public void onthrow(Throwable ex, String name) {
        System.out.println("onThrow: " + name);
    }
}
```
3
```java
    public static void main(String[] args) throws InterruptedException {
        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(ConsumerConfiguration.class);
        context.start();
        DemoServiceComponent service = context.getBean("demoServiceComponent", DemoServiceComponent.class);
        String hello = service.sayHello("world");
        System.out.println("result :" + hello);

    }
```
but not work

```
Caused by: java.lang.IllegalStateException: service:org.apache.dubbo.demo.DemoService has a oninvoke callback config , but no such method found. url:dubbo://192.168.140.82:20880/org.apache.dubbo.demo.DemoService?anyhost=true&application=dubbo-demo-annotation-consumer&bean.name=ServiceBean:org.apache.dubbo.demo.DemoService&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=org.apache.dubbo.demo.DemoService&lazy=true&methods=sayYes,sayHello&pid=16500&register=true&register.ip=192.168.140.82&remote.application=dubbo-demo-annotation-provider&sayHello.async=true&sayHello.return=true&side=consumer&sticky=false&timestamp=1563422037125
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.fireInvokeCallback(FutureFilter.java:69)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:51)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:58)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$CallbackRegistrationInvoker.invoke(ProtocolFilterWrapper.java:150)
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:82)
	... 12 more
```

**Comment by zddgit** [comment]
我也是！调试代码发现没有地方去设置那个onreturnmethod

**Comment by beiwei30** [comment]
dup issue: #4580

**Comment by beiwei30** [comment]
https://github.com/apache/dubbo/issues/4580#issuecomment-517190714

**Comment by cybbeta** [comment]
i use Event Notify with Annotation in dubbo2.7.7 version, still can't work
`    @Reference(interfaceClass = HelloService.class, 
            methods = {
                    @Method(
                            name = "sayHello",
                            oninvoke = "notify.oninvoke",
                            onreturn = "notify.onreturn",
                            onthrow = "notify.onthrow")
            }
    )
    private HelloService helloService;`

**Comment by CarlaX** [comment]
i use dubbo-starter 2.7.8 ， still can‘t work, is there a annotation property to assign the notify interface?
```
@DubboReference(methods = {@Method(name = "exchangeUserInfo", async = false,
                                       oninvoke = "notify.beforeCall",
                                       onreturn = "notify.afterCall",
                                       onthrow = "notify.onThrow")})
private UserServiceForDubbo userServiceForDubbo;
```
