### ISSUE TITLE
cannot throw GenericException

### ISSUE THREAD

**Issue by beiwei30** [apache/dubbo#4630]
Pls. check org.apache.dubbo.samples.generic.call.HelloServiceIT#testNotImplementedHello in dubbo-samples, GenericException is expected, but ExecutionException is thrown:

```
java.util.concurrent.ExecutionException: org.apache.dubbo.rpc.RpcException: Can not deserialize exception null, message: method does not exist.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at org.apache.dubbo.rpc.AsyncRpcResult.getAppResponse(AsyncRpcResult.java:130)
	at org.apache.dubbo.rpc.AsyncRpcResult.recreate(AsyncRpcResult.java:148)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:55)
	at org.apache.dubbo.common.bytecode.proxy0.notImplementedHello(proxy0.java)
	at org.apache.dubbo.samples.generic.call.HelloServiceIT.testNotImplementedHello(HelloServiceIT.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
```

**Comment by lkj41110** [comment]
```
String className = exception.getExceptionClass();
                        Class<?> clazz = ReflectUtils.forName(className);
                        Throwable targetException = null;
                        Throwable lastException = null;
                        try {
                            targetException = (Throwable) clazz.newInstance();
                        } catch (Throwable e) {
                            lastException = e;
                            for (Constructor<?> constructor : clazz.getConstructors()) {
                                try {
                                    targetException = (Throwable) constructor.newInstance(new Object[constructor.getParameterTypes().length]);
                                    break;
                                } catch (Throwable e1) {
                                    lastException = e1;
                                }
                            }
                        }
```
The design seems to be like this, is this a bug?

**Comment by chickenlj** [comment]
I checked the sample and it works fine.
