### ISSUE TITLE
No such any registry to reference Exception happends When Consumer using ConfigCenterConfig

### ISSUE THREAD

**Issue by slankka** [apache/dubbo#4652]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3 and 2.7.2
* Operating System version: Windows 10
* Java version: 1.8.0_151

### Steps to reproduce this issue

0. pom:
```
<dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-alibaba-dependencies</artifactId>
        <exclusions>
          <exclusion>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo</artifactId></exclusion>
        </exclusions>
        <version>0.9.0.RELEASE</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <dependency>
        <groupId>org.apache.dubbo</groupId>
        <artifactId>dubbo</artifactId>
        <version>2.7.3</version>
        <exclusions>
          <exclusion>
            <groupId>org.springframework</groupId>
            <artifactId>spring</artifactId>
          </exclusion>
          <exclusion>
            <groupId>javax.servlet</groupId>
            <artifactId>servlet-api</artifactId>
          </exclusion>
          <exclusion>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
          </exclusion>
        </exclusions>
      </dependency>
```

1. create a configuration class, **without any dubbo properties in local file**.

```
@EnableDubbo(scanBasePackages = {"com.xxxx.rpc"})
@Configuration
public class DubboConfig {

    @Bean
    public ConfigCenterConfig configCenterConfig() {
        ConfigCenterConfig configCenterConfig = new ConfigCenterConfig();
        configCenterConfig.setAddress("apollo.xxxx.com");
        configCenterConfig.setProtocol("apollo");
        configCenterConfig.setNamespace("dubbo");
        configCenterConfig.setGroup(null);
        return configCenterConfig;
    }
}
```
2. The RegistryAddress provided in Apollo namespace: dubbo:
```
dubbo.application.name=Consumer
dubbo.application.qos-enable=false
dubbo.registry.address=zookeeper://zk.xxxxx.com?backup=zk2.xxxxx.com
dubbo.registry.simplified=true
```
when add `dubbo.registry.address=N/A` to local properties file，the apollo config is truely resolved. but the problem exception still remain.

3. The consumer code:
```
@Reference(version = "${xxxx.service.version}", retries = 0, lazy=true)
private IRExecutionService executionService;
```

I will provide full code to reproduce this issue if it's necessary.

### Expected Result

The [document ](http://dubbo.apache.org/zh-cn/docs/user/configuration/config-center.html)shows ConfigCenterConfig support RegistryConfig.

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Caused by: java.lang.IllegalStateException: No such any registry to reference com.sohu.rc.ir.jobDesign.IRExecutionService on the consumer a.b.c.d use dubbo version 2.7.3, please config <dubbo:registry address="..." /> to your spring config.
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:390) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:329) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:250) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor$ReferenceBeanInvocationHandler.init(ReferenceAnnotationBeanPostProcessor.java:269) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor$ReferenceBeanInvocationHandler.access$100(ReferenceAnnotationBeanPostProcessor.java:242) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.buildInvocationHandler(ReferenceAnnotationBeanPostProcessor.java:236) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.buildProxy(ReferenceAnnotationBeanPostProcessor.java:219) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.doGetInjectedBean(ReferenceAnnotationBeanPostProcessor.java:134) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.config.spring.beans.factory.annotation.AnnotationInjectedBeanPostProcessor.getInjectedObject(AnnotationInjectedBeanPostProcessor.java:360) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.config.spring.beans.factory.annotation.AnnotationInjectedBeanPostProcessor$AnnotatedFieldElement.inject(AnnotationInjectedBeanPostProcessor.java:540) ~[dubbo-2.7.3.jar:2.7.3]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.apache.dubbo.config.spring.beans.factory.annotation.AnnotationInjectedBeanPostProcessor.postProcessPropertyValues(AnnotationInjectedBeanPostProcessor.java:147) ~[dubbo-2.7.3.jar:2.7.3]
```

**Comment by CrazyHZM** [comment]
add registry address port

**Comment by slankka** [comment]
The problem has been sovled. My variables in Apollo namespace dubbo should be expanded, but not as a property key `dubbo.properties`.

The document is not explicitly point out that Dubbo 2.7.2 and above has changed the storage model to adapt to Apollo.  

BTW the `Enhancement` part of release note in `apache-dubbo-2.7.2`  mentioned #3266
