### ISSUE TITLE
2.7.1升级2.7.2+后的bug

### ISSUE THREAD

**Issue by zhangx66** [apache/dubbo#4665]
### Environment

* Dubbo version: 2.7.3
* Java version: 1.8

### Steps to reproduce this issue

2.7.1升级到2.7.2+后
启动后MetadataReport无法写入zk

```
[2019-07-25 16:45:47.187][ERROR][AbstractMetadataReport]-- [DUBBO] Failed to put consumer metadata org.apache.dubbo.metadata.identifier.MetadataIdentifier@1f3923f1;  {side=consumer, release=2.7.3, methods=decryptForJdbc,decryptFields,decrypt, lazy=false, dubbo=2.0.2, check=false, interface=com.pingpongx.secret.api.IDecryptService, version=1.0.0, qos.enable=false, timeout=6000, revision=1.0.3, application=fx-tx-service, sticky=false}, cause: KeeperErrorCode = Directory not empty for /dubbo/metadata/com.pingpongx.secret.api.IDecryptService/1.0.0/consumer/fx-tx-service, dubbo version: 2.7.3, current host: 172.16.12.18
java.lang.IllegalStateException: KeeperErrorCode = Directory not empty for /dubbo/metadata/com.pingpongx.secret.api.IDecryptService/1.0.0/consumer/fx-tx-service
	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.delete(CuratorZookeeperClient.java:150) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.remoting.zookeeper.support.AbstractZookeeperClient.create(AbstractZookeeperClient.java:168) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.metadata.store.zookeeper.ZookeeperMetadataReport.storeMetadata(ZookeeperMetadataReport.java:72) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.metadata.store.zookeeper.ZookeeperMetadataReport.doStoreConsumerMetadata(ZookeeperMetadataReport.java:68) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.metadata.support.AbstractMetadataReport.storeConsumerMetadataTask(AbstractMetadataReport.java:274) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.metadata.support.AbstractMetadataReport.lambda$storeConsumerMetadata$1(AbstractMetadataReport.java:260) ~[dubbo-2.7.3.jar:2.7.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by zhangx66** [comment]
因为2.7.1还有子节点service.data

**Comment by cvictory** [comment]
@zhangx66  You can login the zookeeper client, and delete the path manually. 
Then it will work well.
