### ISSUE TITLE
org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeChannel#getExchangeHandler

### ISSUE THREAD

**Issue by beiwei30** [apache/dubbo#4701]
org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeChannel#getExchangeHandler will cause class cast exception when run with netty:

```
java.lang.ClassCastException: class org.apache.dubbo.remoting.transport.netty4.NettyClient cannot be cast to class org.apache.dubbo.remoting.exchange.ExchangeHandler (org.apache.dubbo.remoting.transport.netty4.NettyClient and org.apache.dubbo.remoting.exchange.ExchangeHandler are in unnamed module of loader 'app')
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeChannel.getExchangeHandler(HeaderExchangeChannel.java:193)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeClient.getExchangeHandler(HeaderExchangeClient.java:106)
	at org.apache.dubbo.rpc.protocol.dubbo.ReferenceCountExchangeClient.replaceWithLazyClient(ReferenceCountExchangeClient.java:186)
	at org.apache.dubbo.rpc.protocol.dubbo.ReferenceCountExchangeClient.close(ReferenceCountExchangeClient.java:156)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboInvoker.destroy(DubboInvoker.java:144)
	at org.apache.dubbo.rpc.protocol.AbstractProtocol.destroy(AbstractProtocol.java:68)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.destroy(DubboProtocol.java:639)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.destroy(ProtocolListenerWrapper.java:79)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.destroy(ProtocolFilterWrapper.java:135)
	at org.apache.dubbo.config.DubboShutdownHook.destroyProtocols(DubboShutdownHook.java:103)
	at org.apache.dubbo.config.DubboShutdownHook.doDestroy(DubboShutdownHook.java:91)
	at org.apache.dubbo.config.spring.extension.SpringExtensionFactory$ShutdownHookListener.onApplicationEvent(SpringExtensionFactory.java:114)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:991)
	at org.springframework.context.support.AbstractApplicationContext$2.run(AbstractApplicationContext.java:929)
[30/07/19 15:47:14:520 CST] Thread-0  INFO annotation.ReferenceAnnotationBeanPostProcessor: org.apache.dubbo.common.bytecode.proxy0@4ce62c0c was destroying!
[30/07/19 15:47:14:521 CST] Thread-0  INFO annotation.ReferenceAnnotationBeanPostProcessor: class org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor was destroying!
```

**Comment by beiwei30** [comment]
invalid.
