### ISSUE TITLE
Address already in use: bind

### ISSUE THREAD

**Issue by huangyangcong** [apache/dubbo#4749]
Environment
Dubbo version: 2.7.3
Operating System version: centos7
Java version: jdk8
Steps to reproduce this issue
多个服务在同一台机器同时启动getAvailablePort(defaultPort)获取到的端口一致抛出异常
```
Caused by: org.apache.dubbo.remoting.RemotingException: Failed to bind NettyServer on /192.168.20.155:20883, cause: Address already in use: bind
	at org.apache.dubbo.remoting.transport.AbstractServer.<init>(AbstractServer.java:77) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.remoting.transport.netty4.NettyServer.<init>(NettyServer.java:79) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.remoting.transport.netty4.NettyTransporter.bind(NettyTransporter.java:35) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.remoting.Transporter$Adaptive.bind(Transporter$Adaptive.java) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.remoting.Transporters.bind(Transporters.java:56) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchanger.bind(HeaderExchanger.java:44) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.remoting.exchange.Exchangers.bind(Exchangers.java:70) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.createServer(DubboProtocol.java:349) ~[dubbo-2.7.3.jar:2.7.3]
	... 36 common frames omitted
```

**Comment by zzkyeee** [comment]
增加随机端口配置：
<dubbo:protocol name="dubbo" port="-1" />

**Comment by huangyangcong** [comment]
@zzkyeee 这个运用了端口自增
```
 public static int getAvailablePort(int port) {
        if (port <= 0) {
            return getAvailablePort();
        }
        for (int i = port; i < MAX_PORT; i++) {
            try (ServerSocket ss = new ServerSocket(i)) {
                return i;
            } catch (IOException e) {
                // continue
            }
        }
        return port;
    }
```
第一个获取比如20880获取后另外一个随后获取也是20880，此时第一个还没有真正的绑定

**Comment by CrazyHZM** [comment]
@huangyangcong  你所说的`第一个获取比如20880获取后另外一个随后获取也是20880`指的是随机端口配置还是你直接指定端口。如果配置了随机端口，并不会第一次获得到20880，之后又获取到20880。
另外你这种情况我觉得应该是多个服务都没有配置端口吗，默认使用了20880，如果是这种情况的话，的确会出现端口占用的情况。所以还是需要配置一下端口，或者指定随机端口配置

**Comment by huangyangcong** [comment]
```
    private Integer findConfigedPorts(ProtocolConfig protocolConfig, String name, Map<String, String> map) {
        Integer portToBind = null;

        // parse bind port from environment
        String port = getValueFromConfig(protocolConfig, DUBBO_PORT_TO_BIND);
        portToBind = parsePort(port);

        // if there's no bind port found from environment, keep looking up.
        if (portToBind == null) {
            portToBind = protocolConfig.getPort();
            if (provider != null && (portToBind == null || portToBind == 0)) {
                portToBind = provider.getPort();
            }
            final int defaultPort = ExtensionLoader.getExtensionLoader(Protocol.class).getExtension(name).getDefaultPort();
            if (portToBind == null || portToBind == 0) {
                portToBind = defaultPort;
            }
            if (portToBind == null || portToBind <= 0) {
                portToBind = getRandomPort(name);
                if (portToBind == null || portToBind < 0) {
                    portToBind = getAvailablePort(defaultPort);
                    putRandomPort(name, portToBind);
                }
            }
        }


 public static int getAvailablePort(int port) {
        if (port <= 0) {
            return getAvailablePort();
        }
        for (int i = port; i < MAX_PORT; i++) {
            try (ServerSocket ss = new ServerSocket(i)) {
                return i;
            } catch (IOException e) {
                // continue
            }
        }
        return port;
    }
```

这边配置了```port="-1"```，这个地方获取```portToBind = protocolConfig.getPort();``` portToBind = -1，然后进入```portToBind = getAvailablePort(defaultPort);``` 多个服务同一机器台启动

**Comment by CrazyHZM** [comment]
我理解你的意思了，多个服务一起启动的时候`ServerSocket ss = new ServerSocket(i)`这个一直都能成功对吧，所以导致一起启动的服务都没有获得自增的port。这的确是个问题。

**Comment by WhaleCloud-platform** [comment]
检查下是不是多网卡引起的，导致端口被占用。-Ddubbo.protocol.host=

**Comment by medusar** [comment]
恩，随机端口的话最好dubbo能够保证启动成功。可能这部分逻辑还是需要强化一下

**Comment by lichunheng1024** [comment]
让用户配置一个负数，去触发走默认值+主动bind校验的逻辑，增加了用户的使用成本。
用户也会疑惑，端口号还能配负数嘛。



下面这种优化思路-尽力避免 "Address already in use"  的出现，请指正


#### com.alibaba.dubbo.config.ServiceConfig#findConfigedPorts
```java
private Integer findConfigedPorts(ProtocolConfig protocolConfig, String name, Map<String, String> map) {
        Integer portToBind = null;

        // parse bind port from environment
        String port = getValueFromConfig(protocolConfig, Constants.DUBBO_PORT_TO_BIND);
        portToBind = parsePort(port);

        // if there's no bind port found from environment, keep looking up.
        if (portToBind == null) {
            portToBind = protocolConfig.getPort();
            if (provider != null && (portToBind == null || portToBind == 0)) {
                portToBind = provider.getPort();
            }
        }
        if(portToBind <= 0){
            portToBind = ExtensionLoader.getExtensionLoader(Protocol.class).getExtension(name).getDefaultPort();
        }
        portToBind=getAvailablePort(portToBind);
        // save bind port, used as url's key later
        map.put(Constants.BIND_PORT_KEY, String.valueOf(portToBind));
       
        // registry port, not used as bind port by default
        String portToRegistryStr = getValueFromConfig(protocolConfig, Constants.DUBBO_PORT_TO_REGISTRY);
        Integer portToRegistry = parsePort(portToRegistryStr);
        if (portToRegistry == null) {
            portToRegistry = portToBind;
        }
        return portToRegistry;
    }


```
####  com.alibaba.dubbo.common.utils.NetUtils#getAvailablePort
```

   public static int getAvailablePort(int port) {
        for (int i = port; i < MAX_PORT; i++) {
            ServerSocket ss = null;
            try {
                ss = new ServerSocket(i);
                return i;
            } catch (IOException e) {
                // continue
            } finally {
                if (ss != null) {
                    try {
                        ss.close();
                    } catch (IOException e) {
                    }
                }
            }
        }
        return getAvailablePort();
    }

```

**Comment by lichunheng1024** [comment]
让用户配置一个负数，触发`getRandomPort(String protocol) `,该方法第一次返回Integer.MIN_VALUE; 
从而进入`getAvailablePort(int port)` ，该方法被`findConfigedPorts`调用时传入的是默认值 20880，从而执行主动探测port是否可用的。并不会执行到无参的`getAvailablePort() `

若用户没配置负数，则触发不了主动探测的`getAvailablePort`逻辑。需要做一系列修改配置，打包发布的工作。

与其让用户主动配置一个负数来触发随机逻辑，程序自身主动试探并解决这个错误会更好点。


另外没懂 `getRandomPort(name)` 和 `putRandomPort()` 的用途。


尽力避免 "Address already in use"  的出现修改，请指正


#### com.alibaba.dubbo.config.ServiceConfig#findConfigedPorts
```java
private Integer findConfigedPorts(ProtocolConfig protocolConfig, String name, Map<String, String> map) {
        Integer portToBind = null;

        // parse bind port from environment
        String port = getValueFromConfig(protocolConfig, Constants.DUBBO_PORT_TO_BIND);
        portToBind = parsePort(port);

        // if there's no bind port found from environment, keep looking up.
        if (portToBind == null) {
            portToBind = protocolConfig.getPort();
            if (provider != null && (portToBind == null || portToBind == 0)) {
                portToBind = provider.getPort();
            }
        }
        if(portToBind <= 0){
            portToBind = ExtensionLoader.getExtensionLoader(Protocol.class).getExtension(name).getDefaultPort();
        }
        portToBind=getAvailablePort(portToBind);
        // save bind port, used as url's key later
        map.put(Constants.BIND_PORT_KEY, String.valueOf(portToBind));
       
        // registry port, not used as bind port by default
        String portToRegistryStr = getValueFromConfig(protocolConfig, Constants.DUBBO_PORT_TO_REGISTRY);
        Integer portToRegistry = parsePort(portToRegistryStr);
        if (portToRegistry == null) {
            portToRegistry = portToBind;
        }
        return portToRegistry;
    }


```
####  com.alibaba.dubbo.common.utils.NetUtils#getAvailablePort
```java

   public static int getAvailablePort(int port) {
        for (int i = port; i < MAX_PORT; i++) {
            ServerSocket ss = null;
            try {
                ss = new ServerSocket(i);
                return i;
            } catch (IOException e) {
                // continue
            } finally {
                if (ss != null) {
                    try {
                        ss.close();
                    } catch (IOException e) {
                    }
                }
            }
        }
        return getAvailablePort();
    }

```
