### ISSUE TITLE
dubbo version: 2.6.6 java.lang.NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by alformd** [apache/dubbo#4754]
2019-08-06 16:26:08.383 [NettyServerWorker-6-13] WARN  com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec |  [DUBBO] Fail to encode response: Response [id=5235576, version=stormjar, status=20, event=false, error=null, result=RpcResult [result=null, exception=null]], send bad_response info instead, cause: For input string: "", dubbo version: 2.6.6, current host: 10.0.1.45
java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_60]
        at java.lang.Integer.parseInt(Integer.java:592) ~[na:1.8.0_60]
        at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_60]
        at com.alibaba.dubbo.common.Version.parseInt(Version.java:92) ~[dubbo-2.6.6.jar:2.6.6]
        at com.alibaba.dubbo.common.Version.getIntVersion(Version.java:81) ~[dubbo-2.6.6.jar:2.6.6]
        at com.alibaba.dubbo.common.Version.isSupportResponseAttatchment(Version.java:70) ~[dubbo-2.6.6.jar:2.6.6]
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCodec.encodeResponseData(DubboCodec.java:192) ~[dubbo-2.6.6.jar:2.6.6]
        at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.encodeResponse(ExchangeCodec.java:278) [dubbo-2.6.6.jar:2.6.6]
        at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.encode(ExchangeCodec.java:74) [dubbo-2.6.6.jar:2.6.6]
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCountCodec.encode(DubboCountCodec.java:38) [dubbo-2.6.6.jar:2.6.6]
        at com.alibaba.dubbo.remoting.transport.netty4.NettyCodecAdapter$InternalEncoder.encode(NettyCodecAdapter.java:70) [dubbo-2.6.6.jar:2.6.6]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) [netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:743) [netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:735) [netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:820) [netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:728) [netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) [netty-all-4.0.42.Final.jar:4.0.42.Final]
        at com.alibaba.dubbo.remoting.transport.netty4.NettyServerHandler.write(NettyServerHandler.java:105) [dubbo-2.6.6.jar:2.6.6]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:743) [netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:735) [netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:36) [netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1072) [netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1126) [netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1061) [netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:408) [netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:455) [netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140) [netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [netty-all-4.0.42.Final.jar:4.0.42.Final]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]

**Comment by cvictory** [comment]
In dubbo 2.7， https://github.com/apache/dubbo/issues/3069 has been fixed.

But in dubbo 2.6, the issue is still exist.  

Can you commit a pr for this issue?
