### ISSUE TITLE
run dubbo-demo-api error

### ISSUE THREAD

**Issue by SparkandScala** [apache/dubbo#4765]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4
* Operating System version: Mac
* Java version: 1.8

### Steps to reproduce this issue

1. import the source code of dubbo.
2. at root of the dubbo, execute mvn install
3. run zookeeper at localhost:2181
4. cd to dubbo-demo/dubbo-demo-api/dubbo-demo-api-provide/src/......  run main()
5. has error No such extension org.apache.dubbo.configcenter.DynamicConfigurationFactory by name zookeeper

i want to run this demo at local.

**Comment by tswstarplanet** [comment]
You should add the maven dependency related to ZookeeperDynamicConfigurationFactory

**Comment by SparkandScala** [comment]
can you show me the dependency, thank you,

**Comment by SparkandScala** [comment]
<dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-remoting-zookeeper</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
is it this?

**Comment by SparkandScala** [comment]
<dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-remoting-zookeeper</artifactId>
            <version>${project.parent.version}</version>
        </dependency>

**Comment by SparkandScala** [comment]
Exception in thread "main" java.lang.IllegalStateException: No such extension org.apache.dubbo.configcenter.DynamicConfigurationFactory by name zookeeper
	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:517)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:524)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:348)
	at org.apache.dubbo.config.AbstractInterfaceConfig.getDynamicConfiguration(AbstractInterfaceConfig.java:313)
	at org.apache.dubbo.config.AbstractInterfaceConfig.prepareEnvironment(AbstractInterfaceConfig.java:289)
	at org.apache.dubbo.config.AbstractInterfaceConfig.startConfigCenter(AbstractInterfaceConfig.java:279)
	at org.apache.dubbo.config.AbstractInterfaceConfig.lambda$null$7(AbstractInterfaceConfig.java:628)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.apache.dubbo.config.AbstractInterfaceConfig.lambda$useRegistryForConfigIfNecessary$8(AbstractInterfaceConfig.java:619)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.apache.dubbo.config.AbstractInterfaceConfig.useRegistryForConfigIfNecessary(AbstractInterfaceConfig.java:617)
	at org.apache.dubbo.config.AbstractInterfaceConfig.checkRegistry(AbstractInterfaceConfig.java:207)
	at org.apache.dubbo.config.ServiceConfig.checkAndUpdateSubConfigs(ServiceConfig.java:302)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:369)
	at org.apache.dubbo.demo.provider.Application.main(Application.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
