### ISSUE TITLE
spirng context中存在匿名bean时，dubbo初始化抛npe

### ISSUE THREAD

**Issue by 54hechuan** [apache/dubbo#4772]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.4
* Operating System version: linux 
* Java version: 1.8

### Steps to reproduce this issue

1. 可重现bug的最小环境：spirng boot 2.0.4  + quartz 2.3.0 + dubbo 2.6.4

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
系统启动时抛空指针异常，堆栈如下：
2019-08-08 10:26:40,310 [quartzScheduler_QuartzSchedulerThread] ERROR org.quartz.core.ErrorLogger:2401 schedulerError     - An error occured instantiating job to be executed. job= 'DEFAULT.DemoJob' org.quartz.SchedulerException: Job instantiation failed
	at org.springframework.scheduling.quartz.AdaptableJobFactory.newJob(AdaptableJobFactory.java:47) ~[spring-context-support-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.quartz.core.JobRunShell.initialize(JobRunShell.java:127) [quartz-2.3.0.jar:?]
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:392) [quartz-2.3.0.jar:?]
Caused by: java.lang.NullPointerException
	at com.alibaba.dubbo.config.spring.beans.factory.annotation.DubboConfigBindingBeanPostProcessor.postProcessBeforeInitialization(DubboConfigBindingBeanPostProcessor.java:78) ~[dubbo-2.6.2.jar:2.6.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1691) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:407) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.boot.autoconfigure.quartz.AutowireCapableBeanJobFactory.createJobInstance(AutowireCapableBeanJobFactory.java:45) ~[spring-boot-autoconfigure-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.scheduling.quartz.AdaptableJobFactory.newJob(AdaptableJobFactory.java:43) ~[spring-context-support-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	... 2 more

```

### 问题可能原因
引起此 bug可能的原因是，在集成 quartz 的过程中，spring boot 中的 quartz配置组件向spring context 注入了匿名bean，而且 dubbo组件(DubboConfigBindingBeanPostProcessor.java:78) 这个类中没考虑到 beanName可能为null，重然异致npe。
quartz配置组件向spring context 注入了匿名bean的相关代码，在(org.springframework.boot.autoconfigure.quartz.AutowireCapableBeanJobFactory.java:45)，如下图：
![dubbo1](https://user-images.githubusercontent.com/43158596/62671146-38db3a80-b9c8-11e9-8cd2-4f5c2e61531c.jpg)

dubbo组件(DubboConfigBindingBeanPostProcessor.java:78) 空指针异常的代码如下图：
![dubbo2](https://user-images.githubusercontent.com/43158596/62671208-7dff6c80-b9c8-11e9-8c6b-11ff30b1d653.jpg)

### bug修复建议：
建议在 DubboConfigBindingBeanPostProcessor 类的条件判断语句中先判断 beanName是否为null

**Comment by tswstarplanet** [comment]
can you send a pr to fix it ?

**Comment by AnthonyKot** [comment]
I think reverting `beanName.equals(this.beanName)` to `this.beanName.equals(beanName)` should help. Should I make PR?

**Comment by tswstarplanet** [comment]
> I think reverting `beanName.equals(this.beanName)` to `this.beanName.equals(beanName)` should help. Should I make PR?

I think we should check if the beanName is null first

**Comment by 54hechuan** [comment]
Ok,I while send a pr

**Comment by lixiaojiee** [comment]
+1 to @tswstarplanet 我看了下，这里是最好做一下非空检查的，那个pr我已经合并了，你可以另行提交一个添加非空检查的pr。

**Comment by tswstarplanet** [comment]
@lixiaojie
这个类的beanName属性可能为null吗？

**Comment by lixiaojiee** [comment]
不可能，这个类在初始化的时候对beanName做了校验，他这个pr没问题
