### ISSUE TITLE
dubbo版本2.5.3在jdk1.7下稳定运行,升级到jdk1.8后运行几分钟后线程池就爆掉了,改回1.7又恢复到稳定运行

### ISSUE THREAD

**Issue by dongdongzld** [apache/dubbo#4972]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.5.3
* Operating System version: centos7
* Java version: 1.8

### Steps to reproduce this issue

1. 所有配置都不调整，仅升级环境的jdk版本从1.7升级至1.8
2.qps压力为200左右，service rt 2ms
3. 运行一段时间
Caused by: java.util.concurrent.RejectedExecutionException: Thread pool is EXHAUSTED! Thread Name: DubboServerHandler-10.27.70.208:18707, Pool Size: 200 (active: 200, core: 200, max: 200, largest: 200), Task: 323413 (completed: 323213), Executor status:(isShutdown:false, isTerminated:false, isTerminating:false), in dubbo://10.27.70.208:18707!
调整  threads="1000" dispatcher="message" 依然是运行一段时间会爆掉

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

稳定运行

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
2019-08-30 10:16:59,071 WARN  [org.jboss.netty.channel.DefaultChannelPipeline]  [DUBBO] An exception was thrown by a user handler while handling an exception event ([id: 0xdea80c4e, /10.31.120.115:50188 :> /10.27.70.208:18707] EXCEPTION: com.alibaba.dubbo.remoting.ExecutionException: class com.alibaba.dubbo.remoting.transport.dispatcher.all.AllChannelHandler error when process disconnected event .), dubbo version: 2.5.3, current host: 127.0.0.1
com.alibaba.dubbo.remoting.ExecutionException: class com.alibaba.dubbo.remoting.transport.dispatcher.all.AllChannelHandler error when process caught event .
	at com.alibaba.dubbo.remoting.transport.dispatcher.all.AllChannelHandler.caught(AllChannelHandler.java:67)
	at com.alibaba.dubbo.remoting.transport.AbstractChannelHandlerDelegate.caught(AbstractChannelHandlerDelegate.java:44)
	at com.alibaba.dubbo.remoting.transport.AbstractChannelHandlerDelegate.caught(AbstractChannelHandlerDelegate.java:44)
	at com.alibaba.dubbo.remoting.transport.AbstractPeer.caught(AbstractPeer.java:127)
	at com.alibaba.dubbo.remoting.transport.netty.NettyHandler.exceptionCaught(NettyHandler.java:112)
	at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalDecoder.exceptionCaught(NettyCodecAdapter.java:165)
	at org.jboss.netty.channel.Channels.fireExceptionCaught(Channels.java:525)
	at org.jboss.netty.channel.AbstractChannelSink.exceptionCaught(AbstractChannelSink.java:48)
	at org.jboss.netty.channel.Channels.fireChannelDisconnected(Channels.java:396)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:361)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:93)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.RejectedExecutionException: Thread pool is EXHAUSTED! Thread Name: DubboServerHandler-10.27.70.208:18707, Pool Size: 200 (active: 200, core: 200, max: 200, largest: 200), Task: 323413 (completed: 323213), Executor status:(isShutdown:false, isTerminated:false, isTerminating:false), in dubbo://10.27.70.208:18707!
	at com.alibaba.dubbo.common.threadpool.support.AbortPolicyWithReport.rejectedExecution(AbortPolicyWithReport.java:53)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at com.alibaba.dubbo.remoting.transport.dispatcher.all.AllChannelHandler.caught(AllChannelHandler.java:65)
	... 17 more
```

**Comment by dongdongzld** [comment]
已解決

**Comment by Anlyjia** [comment]
遇到相同的问题，请问您是如何解决的？
