### ISSUE TITLE
2.5.x script route can't work

### ISSUE THREAD

**Issue by wkcaeser** [apache/dubbo#4979]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.5.3
* Operating System version: MacOS Mojave 10.14.4 (18E226)
* Java version: 1.8

### Steps to reproduce this issue

1.  register script route 
```java
URL registryUrl = URL.valueOf("zookeeper://127.0.0.1:2181");
        ZookeeperRegistryFactory zookeeperRegistryFactory = new
                ZookeeperRegistryFactory();
        zookeeperRegistryFactory.setZookeeperTransporter(new
                CuratorZookeeperTransporter());
        Registry zookeeperRegistry = zookeeperRegistryFactory.createRegistry(registryUrl);
        URL routerURL =
//                URL.valueOf("script://0.0.0.0/com.wk.dubbotest.IDubboTest?category=routers&dynamic=false&enabled=true&force=false&priority=0&runtime=true&rule="
                URL.valueOf("script://0.0.0.0/com.wk.dubbotest.IDubboTest?type=javascript&rule="
                + URL.encode(get_demoService_createUser_router()));

//        routerURL = routerURL.addParameter("rule", URL.encode(get_demoService_createUser_router()));
//        zookeeperRegistry.register(routerURL);     // 注册
         zookeeperRegistry.unregister(routerURL); // 取消注册
```
2. consumer print error

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

I hope that consumer can work correctly and the script route can take effect

### Actual Result

Consumer  print error when I registered the script route 

If there is an exception, please attach the exception trace:

```
2019-09-02 11:39:59.302 ERROR 5026 --- [-127.0.0.1:2181] c.a.d.r.integration.RegistryDirectory    : Unsupported protocol script in notified url: script://0.0.0.0/com.wk.dubbotest.IDubboTest?rule=function+route%28invokers%29+%7B++++var+result+%3D+new+java.util.ArrayList%28invokers.size%28%29%29%3B++++result.add%28invokers.get%280%29%29%3B++++return+result%3B%7Droute%28invokers%29%3B&type=javascript from registry 127.0.0.1:2181 to consumer 10.38.1.51, supported protocol: [dubbo, injvm, mock, redis, registry, rmi, thrift]

java.lang.IllegalStateException: Unsupported protocol script in notified url: script://0.0.0.0/com.wk.dubbotest.IDubboTest?rule=function+route%28invokers%29+%7B++++var+result+%3D+new+java.util.ArrayList%28invokers.size%28%29%29%3B++++result.add%28invokers.get%280%29%29%3B++++return+result%3B%7Droute%28invokers%29%3B&type=javascript from registry 127.0.0.1:2181 to consumer 10.38.1.51, supported protocol: [dubbo, injvm, mock, redis, registry, rmi, thrift]
	at com.alibaba.dubbo.registry.integration.RegistryDirectory.toInvokers(RegistryDirectory.java:372) [dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.registry.integration.RegistryDirectory.refreshInvoker(RegistryDirectory.java:224) [dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.registry.integration.RegistryDirectory.notify(RegistryDirectory.java:195) [dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.registry.support.AbstractRegistry.notify(AbstractRegistry.java:449) [dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.registry.support.FailbackRegistry.doNotify(FailbackRegistry.java:273) [dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.registry.support.FailbackRegistry.notify(FailbackRegistry.java:259) [dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry.access$400(ZookeeperRegistry.java:45) [dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry$3.childChanged(ZookeeperRegistry.java:159) [dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.remoting.zookeeper.zkclient.ZkclientZookeeperClient$2.handleChildChange(ZkclientZookeeperClient.java:82) [dubbo-2.5.3.jar:2.5.3]
	at org.I0Itec.zkclient.ZkClient$10.run(ZkClient.java:843) [zkclient-0.9.jar:na]
	at org.I0Itec.zkclient.ZkEventThread.run(ZkEventThread.java:71) [zkclient-0.9.jar:na]
```

**Comment by wkcaeser** [comment]
this url can work
```java
URL.valueOf("script://0.0.0.0/com.wk.dubbotest.IDubboTest?type=javascript&category=routers&dynamic=false&enabled=true&force=false&priority=0&runtime=true&rule="
//                URL.valueOf("script://0.0.0.0/com.wk.dubbotest.IDubboTest?type=javascript&rule="
                + URL.encode(get_demoService_createUser_router()));
```

**Comment by 13567436138** [comment]
我试了下，不报错，但是路由好像不起作用

**Comment by 13567436138** [comment]
get_demoService_createUser_router  这个代码能贴下么

**Comment by wkcaeser** [comment]
```java
public static String get_demoService_createUser_router() throws IOException {
        java.net.URL url = App.class.getClassLoader().getResource("js/dubboRoute1.js");
        StringBuilder js = new StringBuilder();
        BufferedReader reader = new BufferedReader(new FileReader(url.getFile()));
        String line;
        while ((line =reader.readLine()) != null) {
            js.append(line);
        }
        return js.toString();
    }
```
dubboRoute1.js
```javascript
function route(invokers) {
    var result = new java.util.ArrayList(invokers.size());
    result.add(invokers.get(0));
    return result;
}
route(invokers);
```

**Comment by wkcaeser** [comment]
参考这个  https://blog.csdn.net/prestigeding/article/details/83057273     我还遇到一个类型转化出错的问题，测试的结果貌似每次返回的类型是js函数的最后一个参数类型
