### ISSUE TITLE
RpcUtils.getReturnTypes(Invocation) 性能问题

### ISSUE THREAD

**Issue by LinShunKang** [apache/dubbo#5004]
- [] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.5.10
* Operating System version: 3.10.0-514.26.2.el7.x86_64 GNU/Linux
* Java version: 1.8

### Steps to reproduce this issue

1. benchmark

### Description
在对 Dubbo 应用进行压测时，通过 top -Hp {pid} 和 jstack {pid} 进行查看后，发现 Dubbo 客户端有 4 个线程的 CPU 占用比较高，并且线程均在执行 `sun.reflect.generics.parser.SignatureParser.current(SignatureParser.java:95)`

### Suggestion
把 `RpcUtils.getReturnTypes(Invocation)` 执行结果的 `Method` 对象缓存下来，避免每次都调用反射 Api：
例如，用 `Map<service, Map<methodName, A>>` 来缓存，其中  `A` 中包含 `parameterTypes` 和 `Method` 的对应关系

具体线程堆栈如下：

```
"New I/O client worker #1-5" #63 daemon prio=5 os_prio=0 tid=0x00007fc730003000 nid=0x49db runnable [0x00007fc790c13000]
   java.lang.Thread.State: RUNNABLE
        at sun.reflect.generics.parser.SignatureParser.current(SignatureParser.java:95)
        at sun.reflect.generics.parser.SignatureParser.parseZeroOrMoreThrowsSignatures(SignatureParser.java:633)
        at sun.reflect.generics.parser.SignatureParser.parseMethodTypeSignature(SignatureParser.java:578)
        at sun.reflect.generics.parser.SignatureParser.parseMethodSig(SignatureParser.java:171)
        at sun.reflect.generics.repository.ConstructorRepository.parse(ConstructorRepository.java:55)
        at sun.reflect.generics.repository.ConstructorRepository.parse(ConstructorRepository.java:43)
        at sun.reflect.generics.repository.AbstractRepository.<init>(AbstractRepository.java:74)
        at sun.reflect.generics.repository.GenericDeclRepository.<init>(GenericDeclRepository.java:49)
        at sun.reflect.generics.repository.ConstructorRepository.<init>(ConstructorRepository.java:51)
        at sun.reflect.generics.repository.MethodRepository.<init>(MethodRepository.java:46)
        at sun.reflect.generics.repository.MethodRepository.make(MethodRepository.java:59)
        at java.lang.reflect.Method.getGenericInfo(Method.java:102)
        at java.lang.reflect.Method.getGenericReturnType(Method.java:255)
        at com.alibaba.dubbo.rpc.support.RpcUtils.getReturnTypes(RpcUtils.java:72)
        at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:79)
        at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:106)
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCodec.decodeBody(DubboCodec.java:88)
        at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:120)
        at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:81)
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCountCodec.decode(DubboCountCodec.java:44)
        at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalDecoder.messageReceived(NettyCodecAdapter.java:133)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:349)
        at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:44)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

"New I/O client worker #1-4" #62 daemon prio=5 os_prio=0 tid=0x00007fc730001000 nid=0x49da runnable [0x00007fc790c94000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
        at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
        at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
        at sun.reflect.generics.repository.MethodRepository.getReturnType(MethodRepository.java:68)
        at java.lang.reflect.Method.getGenericReturnType(Method.java:255)
        at com.alibaba.dubbo.rpc.support.RpcUtils.getReturnTypes(RpcUtils.java:72)
        at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:79)
        at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:106)
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCodec.decodeBody(DubboCodec.java:88)
        at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:120)
        at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:81)
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCountCodec.decode(DubboCountCodec.java:44)
        at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalDecoder.messageReceived(NettyCodecAdapter.java:133)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:349)
        at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:44)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

"New I/O client worker #1-3" #61 daemon prio=5 os_prio=0 tid=0x00007fc73005b800 nid=0x49d9 runnable [0x00007fc790d15000]
   java.lang.Thread.State: RUNNABLE
        at sun.reflect.generics.parser.SignatureParser.current(SignatureParser.java:95)
        at sun.reflect.generics.parser.SignatureParser.parseZeroOrMoreThrowsSignatures(SignatureParser.java:633)
        at sun.reflect.generics.parser.SignatureParser.parseMethodTypeSignature(SignatureParser.java:578)
        at sun.reflect.generics.parser.SignatureParser.parseMethodSig(SignatureParser.java:171)
        at sun.reflect.generics.repository.ConstructorRepository.parse(ConstructorRepository.java:55)
        at sun.reflect.generics.repository.ConstructorRepository.parse(ConstructorRepository.java:43)
        at sun.reflect.generics.repository.AbstractRepository.<init>(AbstractRepository.java:74)
        at sun.reflect.generics.repository.GenericDeclRepository.<init>(GenericDeclRepository.java:49)
        at sun.reflect.generics.repository.ConstructorRepository.<init>(ConstructorRepository.java:51)
        at sun.reflect.generics.repository.MethodRepository.<init>(MethodRepository.java:46)
        at sun.reflect.generics.repository.MethodRepository.make(MethodRepository.java:59)
        at java.lang.reflect.Method.getGenericInfo(Method.java:102)
        at java.lang.reflect.Method.getGenericReturnType(Method.java:255)
        at com.alibaba.dubbo.rpc.support.RpcUtils.getReturnTypes(RpcUtils.java:72)
        at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:79)
        at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:106)
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCodec.decodeBody(DubboCodec.java:88)
        at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:120)
        at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:81)
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCountCodec.decode(DubboCountCodec.java:44)
        at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalDecoder.messageReceived(NettyCodecAdapter.java:133)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:349)
        at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:44)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

"New I/O client worker #1-2" #59 daemon prio=5 os_prio=0 tid=0x00007fc730041000 nid=0x49d7 runnable [0x00007fc790e17000]
   java.lang.Thread.State: RUNNABLE
        at sun.reflect.generics.parser.SignatureParser.current(SignatureParser.java:95)
        at sun.reflect.generics.parser.SignatureParser.parseZeroOrMoreThrowsSignatures(SignatureParser.java:633)
        at sun.reflect.generics.parser.SignatureParser.parseMethodTypeSignature(SignatureParser.java:578)
        at sun.reflect.generics.parser.SignatureParser.parseMethodSig(SignatureParser.java:171)
        at sun.reflect.generics.repository.ConstructorRepository.parse(ConstructorRepository.java:55)
        at sun.reflect.generics.repository.ConstructorRepository.parse(ConstructorRepository.java:43)
        at sun.reflect.generics.repository.AbstractRepository.<init>(AbstractRepository.java:74)
        at sun.reflect.generics.repository.GenericDeclRepository.<init>(GenericDeclRepository.java:49)
        at sun.reflect.generics.repository.ConstructorRepository.<init>(ConstructorRepository.java:51)
        at sun.reflect.generics.repository.MethodRepository.<init>(MethodRepository.java:46)
        at sun.reflect.generics.repository.MethodRepository.make(MethodRepository.java:59)
        at java.lang.reflect.Method.getGenericInfo(Method.java:102)
        at java.lang.reflect.Method.getGenericReturnType(Method.java:255)
        at com.alibaba.dubbo.rpc.support.RpcUtils.getReturnTypes(RpcUtils.java:72)
        at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:79)
        at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:106)
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCodec.decodeBody(DubboCodec.java:88)
        at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:120)
        at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:81)
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCountCodec.decode(DubboCountCodec.java:44)
        at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalDecoder.messageReceived(NettyCodecAdapter.java:133)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:349)
        at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:44)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by chickenlj** [comment]
Thanks for pointing this out, this has been fixed in branch performance-tuning-2.7.x. Please help to review and reopen this issue if any problem with the new implementation.

**Comment by LinShunKang** [comment]
@chickenlj 你好，我看了 `performance-tuning-2.7.x` 分支上相关代码，整体思路和我的差不多，但是，实现方式不太一样：
* Dubbo 的实现方式是在生成每一个 `RpcInvocation` 对象的时候从缓存中获取 `returnTypes` 并放到 `RpcInvocation` 对象中保存起来
* 我的实现方式是直接修改 `RpcUtils.getReturnTypes(Invocation)` 的实现，从缓存中获 `returnTypes`并返回

个人观点：
Dubbo 的实现方式会导致每一个 RpcInvocation 对象的占用空间变大，如果 Consumer 对外的请求量比较高，会对 GC 有一些影响，虽然不大。

**Comment by LinShunKang** [comment]
@chickenlj 另外，不建议用 Set<MethodModel> 来存储 MethodModel，否则每次遍历都会生成一个 Iterator 对象，浪费内存。
[ServiceModel.java#L87](https://github.com/apache/dubbo/blob/c48c5cfa1d9fe05fb6c3f5198638eb260759a8a2/dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ServiceModel.java#L87)

**Comment by LinShunKang** [comment]
关于我的实现方式 与 Dubbo现有的实现方式的 微基准测试，我已经放到 [dubbo-benchmark](https://github.com/LinShunKang/dubbo-benchmark) 项目中了，如果微基准测试代码有问题，还请指正。
