### ISSUE TITLE
Flaky EtcdMetadataReportTest.testStoreConsumer:NoClassDefFoundError

### ISSUE THREAD

**Issue by sonymoon** [apache/dubbo#5080]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4-SNAPSHOT
* Operating System version: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"
* Java version: 1.8.0_131

### Steps to reproduce this issue

1. just run UT `EtcdMetadataReportTest.testStoreConsumer` in IDEA
or `mvn clean install -DskipTests=false` from cmd.

### Expected Result
UT succeeds

### Actual Result
Ex:
#### IDEA
```
java.lang.NoClassDefFoundError: com/google/common/base/Preconditions

	at io.etcd.jetcd.ClientBuilder.endpoints(ClientBuilder.java:82)
	at org.apache.dubbo.metadata.store.etcd.EtcdMetadataReportTest.setUp(EtcdMetadataReportTest.java:64
```

#### mvn build with clean install
```
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 4.798 s <<< FAILURE! - in org.apache.dubbo.metadata.store.etcd.EtcdMetadataReportTest
[ERROR] testStoreConsumer  Time elapsed: 2.127 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/common/base/Preconditions
        at org.apache.dubbo.metadata.store.etcd.EtcdMetadataReportTest.setUp(EtcdMetadataReportTest.java:64)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Preconditions
        at org.apache.dubbo.metadata.store.etcd.EtcdMetadataReportTest.setUp(EtcdMetadataReportTest.java:64)

**Comment by sonymoon** [comment]
`jetcd-core` needs `guava` dependency which is absent in test classpath
