### ISSUE TITLE
按照Demo写的代码运行Cunsummer时 Failed to check the status of the service com.alibaba.dubbo.demo.DemoService

### ISSUE THREAD

**Issue by 83909339** [apache/dubbo#51]
按照例子配置：
provider.xml
![image](https://cloud.githubusercontent.com/assets/5762264/3201406/7cf4f282-ed87-11e3-86a2-ac0723200ad4.png)
consummer.xml
![image](https://cloud.githubusercontent.com/assets/5762264/3201411/8d40dbec-ed87-11e3-902d-f735637c85ee.png)

telnet可以看到服务：

![image](https://cloud.githubusercontent.com/assets/5762264/3201392/5f384172-ed87-11e3-896d-9c6c2ecf3094.png)

但是运行Cunsummer时,getBean报错,：
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoService': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: Failed to check the status of the service com.alibaba.dubbo.demo.DemoService. No provider available for the service com.alibaba.dubbo.demo.DemoService from the url multicast://225.0.0.0:1234/com.alibaba.dubbo.registry.RegistryService?anyhost=true&application=consumer-of-helloworld-app&check=false&connected=true&dubbo=2.4.9&interface=com.alibaba.dubbo.demo.DemoService&methods=sayHello&pid=12256&revision=service&side=consumer&timestamp=1402064250263 to the consumer 192.168.1.6 use dubbo version 2.4.9
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport$1.run(FactoryBeanRegistrySupport.java:127)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:116)
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:91)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1285)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:217)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:185)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:164)
    at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:881)
    at Consumer.main(Consumer.java:11)
Caused by: java.lang.IllegalStateException: Failed to check the status of the service com.alibaba.dubbo.demo.DemoService. No provider available for the service com.alibaba.dubbo.demo.DemoService from the url multicast://225.0.0.0:1234/com.alibaba.dubbo.registry.RegistryService?anyhost=true&application=consumer-of-helloworld-app&check=false&connected=true&dubbo=2.4.9&interface=com.alibaba.dubbo.demo.DemoService&methods=sayHello&pid=12256&revision=service&side=consumer&timestamp=1402064250263 to the consumer 192.168.1.6 use dubbo version 2.4.9
    at com.alibaba.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:422)
    at com.alibaba.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:303)
    at com.alibaba.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:138)
    at com.alibaba.dubbo.config.spring.ReferenceBean.getObject(ReferenceBean.java:65)
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport$1.run(FactoryBeanRegistrySupport.java:121)
    ... 9 more

**Comment by fengbiaoshan** [comment]
应该是多网卡多IP引起的问题，可以参考https://www.jianshu.com/p/3646263199a1文章底部的问题分析

**Comment by YouthLin** [comment]
> 应该是多网卡多IP引起的问题，可以参考[https://www.jianshu.com/p/3646263199a1文章底部的问题分析](https://www.jianshu.com/p/3646263199a1%E6%96%87%E7%AB%A0%E5%BA%95%E9%83%A8%E7%9A%84%E9%97%AE%E9%A2%98%E5%88%86%E6%9E%90)
赞👍，这里也提到了这个的解决方法：
https://github.com/apache/dubbo/issues/3561#issuecomment-498574806
