### ISSUE TITLE
configToConnectionString  NullPointerException

### ISSUE THREAD

**Issue by fxqy** [apache/dubbo#5173]
java.lang.NullPointerException: null
	at org.apache.curator.framework.imps.EnsembleTracker.configToConnectionString(EnsembleTracker.java:179) ~[curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:200) ~[curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.EnsembleTracker.access$300(EnsembleTracker.java:50) ~[curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:144) ~[curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:865) [curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:635) [curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152) [curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:222) [curator-framework-4.0.1.jar:4.0.1]
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:598) [zookeeper-3.5.5.jar:3.5.5]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:510) [zookeeper-3.5.5.jar:3.5.5]

**Comment by CrazyHZM** [comment]
Is this all the error message?

**Comment by fxqy** [comment]
Project start printed two identical exceptions, I only posted one

**Comment by fxqy** [comment]
The complete error message is as follows

`2019-10-22 14:36:02.003  INFO 2788 --- [           main] o.a.c.f.imps.CuratorFrameworkImpl        : Starting
2019-10-22 14:36:02.008  INFO 2788 --- [           main] org.apache.zookeeper.ZooKeeper           : Initiating client connection, connectString=longsun_host1:2181,longsun_host2:2182,longsun_host3:2183 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@1d3e0e96
2019-10-22 14:36:02.016  INFO 2788 --- [           main] org.apache.zookeeper.common.X509Util     : Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
2019-10-22 14:36:02.023  INFO 2788 --- [           main] org.apache.zookeeper.ClientCnxnSocket    : jute.maxbuffer value is 4194304 Bytes
2019-10-22 14:36:02.034  INFO 2788 --- [           main] org.apache.zookeeper.ClientCnxn          : zookeeper.request.timeout value is 0. feature enabled=
2019-10-22 14:36:02.043  INFO 2788 --- [sun_host1:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server longsun_host1/192.168.1.154:2181. Will not attempt to authenticate using SASL (unknown error)
2019-10-22 14:36:02.045  INFO 2788 --- [sun_host1:2181)] org.apache.zookeeper.ClientCnxn          : Socket connection established, initiating session, client: /192.168.1.118:51963, server: longsun_host1/192.168.1.154:2181
2019-10-22 14:36:02.050  INFO 2788 --- [sun_host1:2181)] org.apache.zookeeper.ClientCnxn          : Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect
2019-10-22 14:36:02.052  INFO 2788 --- [           main] o.a.c.f.imps.CuratorFrameworkImpl        : Default schema
[22/10/19 14:36:02:052 CST] main  INFO zookeeper.ZookeeperTransporter:  [DUBBO] No valid zookeeper client found from cache, therefore create a new client for url. zookeeper://longsun_host1:2181/ConfigCenterConfig?backup=longsun_host2:2182,longsun_host3:2183&config.check=true&config.config-file=dubbo.properties&config.group=dubbo&config.highest-priority=false&config.namespace=dubbo&config.timeout=3000, dubbo version: 2.7.3, current host: 192.168.1.118
2019-10-22 14:36:02.637  INFO 2788 --- [sun_host2:2182)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server longsun_host2/192.168.1.155:2182. Will not attempt to authenticate using SASL (unknown error)
2019-10-22 14:36:02.638  INFO 2788 --- [sun_host2:2182)] org.apache.zookeeper.ClientCnxn          : Socket connection established, initiating session, client: /192.168.1.118:51964, server: longsun_host2/192.168.1.155:2182
2019-10-22 14:36:02.648  INFO 2788 --- [sun_host2:2182)] org.apache.zookeeper.ClientCnxn          : Session establishment complete on server longsun_host2/192.168.1.155:2182, sessionid = 0x200007697c40008, negotiated timeout = 40000
2019-10-22 14:36:02.657  INFO 2788 --- [ain-EventThread] o.a.c.f.state.ConnectionStateManager     : State change: CONNECTED
2019-10-22 14:36:02.672  INFO 2788 --- [ain-EventThread] o.a.c.framework.imps.EnsembleTracker     : New config event received: {server.1=zoo1:2888:3888:participant;0.0.0.0:2181, version=0, server.3=zoo3:2888:3888:participant;0.0.0.0:2181, server.2=0.0.0.0:2888:3888:participant;0.0.0.0:2181}
2019-10-22 14:36:07.186 ERROR 2788 --- [ain-EventThread] o.a.c.f.imps.CuratorFrameworkImpl        : Background exception was not retry-able or retry gave up

java.lang.NullPointerException: null
	at org.apache.curator.framework.imps.EnsembleTracker.configToConnectionString(EnsembleTracker.java:179) ~[curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:200) ~[curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.EnsembleTracker.access$300(EnsembleTracker.java:50) ~[curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:144) ~[curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:865) [curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:635) [curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152) [curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:222) [curator-framework-4.0.1.jar:4.0.1]
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:598) [zookeeper-3.5.5.jar:3.5.5]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:510) [zookeeper-3.5.5.jar:3.5.5]

2019-10-22 14:36:07.187  INFO 2788 --- [ain-EventThread] o.a.c.framework.imps.EnsembleTracker     : New config event received: {server.1=zoo1:2888:3888:participant;0.0.0.0:2181, version=0, server.3=zoo3:2888:3888:participant;0.0.0.0:2181, server.2=0.0.0.0:2888:3888:participant;0.0.0.0:2181}
2019-10-22 14:36:07.187 ERROR 2788 --- [ain-EventThread] o.a.c.f.imps.CuratorFrameworkImpl        : Background exception was not retry-able or retry gave up

java.lang.NullPointerException: null
	at org.apache.curator.framework.imps.EnsembleTracker.configToConnectionString(EnsembleTracker.java:179) ~[curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:200) ~[curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.EnsembleTracker.access$300(EnsembleTracker.java:50) ~[curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:144) ~[curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:865) [curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:635) [curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152) [curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:222) [curator-framework-4.0.1.jar:4.0.1]
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:598) [zookeeper-3.5.5.jar:3.5.5]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:510) [zookeeper-3.5.5.jar:3.5.5]

[22/10/19 14:36:07:207 CST] main  WARN config.ConfigurationUtils:  [DUBBO] You specified the config centre, but there's not even one single config item in it., dubbo version: 2.7.3, current host: 192.168.1.118
[22/10/19 14:36:07:208 CST] main  WARN config.ConfigurationUtils:  [DUBBO] You specified the config centre, but there's not even one single config item in it., dubbo version: 2.7.3, current host: 192.168.1.118
[22/10/19 14:36:07:217 CST] main  WARN config.AbstractConfig:  [DUBBO] There's no valid metadata config found, if you are using the simplified mode of registry url, please make sure you have a metadata address configured properly., dubbo version: 2.7.3, current host: 192.168.1.118`

**Comment by fxqy** [comment]
The complete error message is as follows

---------------------------------------------------------------------------------------------------------------

2019-10-22 14:36:02.003  INFO 2788 --- [           main] o.a.c.f.imps.CuratorFrameworkImpl        : Starting
2019-10-22 14:36:02.008  INFO 2788 --- [           main] org.apache.zookeeper.ZooKeeper           : Initiating client connection, connectString=zookeeper_host1:2181,zookeeper_host2:2182,zookeeper_host3:2183 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@1d3e0e96
2019-10-22 14:36:02.016  INFO 2788 --- [           main] org.apache.zookeeper.common.X509Util     : Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
2019-10-22 14:36:02.023  INFO 2788 --- [           main] org.apache.zookeeper.ClientCnxnSocket    : jute.maxbuffer value is 4194304 Bytes
2019-10-22 14:36:02.034  INFO 2788 --- [           main] org.apache.zookeeper.ClientCnxn          : zookeeper.request.timeout value is 0. feature enabled=
2019-10-22 14:36:02.043  INFO 2788 --- [sun_host1:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server zookeeper_host1/192.168.1.154:2181. Will not attempt to authenticate using SASL (unknown error)
2019-10-22 14:36:02.045  INFO 2788 --- [sun_host1:2181)] org.apache.zookeeper.ClientCnxn          : Socket connection established, initiating session, client: /192.168.1.118:51963, server: zookeeper_host1/192.168.1.154:2181
2019-10-22 14:36:02.050  INFO 2788 --- [sun_host1:2181)] org.apache.zookeeper.ClientCnxn          : Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect
2019-10-22 14:36:02.052  INFO 2788 --- [           main] o.a.c.f.imps.CuratorFrameworkImpl        : Default schema
[22/10/19 14:36:02:052 CST] main  INFO zookeeper.ZookeeperTransporter:  [DUBBO] No valid zookeeper client found from cache, therefore create a new client for url. zookeeper://zookeeper_host1:2181/ConfigCenterConfig?backup=zookeeper_host2:2182,zookeeper_host3:2183&config.check=true&config.config-file=dubbo.properties&config.group=dubbo&config.highest-priority=false&config.namespace=dubbo&config.timeout=3000, dubbo version: 2.7.3, current host: 192.168.1.118
2019-10-22 14:36:02.637  INFO 2788 --- [sun_host2:2182)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server zookeeper_host2/192.168.1.155:2182. Will not attempt to authenticate using SASL (unknown error)
2019-10-22 14:36:02.638  INFO 2788 --- [sun_host2:2182)] org.apache.zookeeper.ClientCnxn          : Socket connection established, initiating session, client: /192.168.1.118:51964, server: zookeeper_host2/192.168.1.155:2182
2019-10-22 14:36:02.648  INFO 2788 --- [sun_host2:2182)] org.apache.zookeeper.ClientCnxn          : Session establishment complete on server zookeeper_host2/192.168.1.155:2182, sessionid = 0x200007697c40008, negotiated timeout = 40000
2019-10-22 14:36:02.657  INFO 2788 --- [ain-EventThread] o.a.c.f.state.ConnectionStateManager     : State change: CONNECTED
2019-10-22 14:36:02.672  INFO 2788 --- [ain-EventThread] o.a.c.framework.imps.EnsembleTracker     : New config event received: {server.1=zoo1:2888:3888:participant;0.0.0.0:2181, version=0, server.3=zoo3:2888:3888:participant;0.0.0.0:2181, server.2=0.0.0.0:2888:3888:participant;0.0.0.0:2181}
2019-10-22 14:36:07.186 ERROR 2788 --- [ain-EventThread] o.a.c.f.imps.CuratorFrameworkImpl        : Background exception was not retry-able or retry gave up

java.lang.NullPointerException: null
	at org.apache.curator.framework.imps.EnsembleTracker.configToConnectionString(EnsembleTracker.java:179) ~[curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:200) ~[curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.EnsembleTracker.access$300(EnsembleTracker.java:50) ~[curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:144) ~[curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:865) [curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:635) [curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152) [curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:222) [curator-framework-4.0.1.jar:4.0.1]
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:598) [zookeeper-3.5.5.jar:3.5.5]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:510) [zookeeper-3.5.5.jar:3.5.5]

2019-10-22 14:36:07.187  INFO 2788 --- [ain-EventThread] o.a.c.framework.imps.EnsembleTracker     : New config event received: {server.1=zoo1:2888:3888:participant;0.0.0.0:2181, version=0, server.3=zoo3:2888:3888:participant;0.0.0.0:2181, server.2=0.0.0.0:2888:3888:participant;0.0.0.0:2181}
2019-10-22 14:36:07.187 ERROR 2788 --- [ain-EventThread] o.a.c.f.imps.CuratorFrameworkImpl        : Background exception was not retry-able or retry gave up

java.lang.NullPointerException: null
	at org.apache.curator.framework.imps.EnsembleTracker.configToConnectionString(EnsembleTracker.java:179) ~[curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:200) ~[curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.EnsembleTracker.access$300(EnsembleTracker.java:50) ~[curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:144) ~[curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:865) [curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:635) [curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152) [curator-framework-4.0.1.jar:4.0.1]
	at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:222) [curator-framework-4.0.1.jar:4.0.1]
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:598) [zookeeper-3.5.5.jar:3.5.5]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:510) [zookeeper-3.5.5.jar:3.5.5]

[22/10/19 14:36:07:207 CST] main  WARN config.ConfigurationUtils:  [DUBBO] You specified the config centre, but there's not even one single config item in it., dubbo version: 2.7.3, current host: 192.168.1.118
[22/10/19 14:36:07:208 CST] main  WARN config.ConfigurationUtils:  [DUBBO] You specified the config centre, but there's not even one single config item in it., dubbo version: 2.7.3, current host: 192.168.1.118
[22/10/19 14:36:07:217 CST] main  WARN config.AbstractConfig:  [DUBBO] There's no valid metadata config found, if you are using the simplified mode of registry url, please make sure you have a metadata address configured properly., dubbo version: 2.7.3, current host: 192.168.1.118

**Comment by CrazyHZM** [comment]
I found that the server in your zk cluster configuration has a version in the log, please check your configuration.
server.1=zoo1:2888:3888:participant;0.0.0.0:2181, version=0, server.3=zoo3:2888:3888:participant;0.0.0.0:2181, server.2=0.0.0.0:2888:3888:participant;0.0.0.0:2181

**Comment by samz406** [comment]
Is curator4.0.1 incompatible zookeeper-3.5.5?
