### ISSUE TITLE
dubbo 2.7.3 @Reference group参数不生效

### ISSUE THREAD

**Issue by hyberbin** [apache/dubbo#5190]
### Environment

* Dubbo version: 2.7.3
* Operating System version: *
* Java version: 1.8

### Steps to reproduce this issue

1. 在Consumer端以注解方式配置

```java
 @Reference(group = "aaaa")
 private XXXService service1;
 @Reference(group = "bbbb")
 private XXXService service2;
```

2. 调用时候报错

  找不到服务

3. consumer和privider同时去掉group能通

```java
 @Reference
 private XXXService service1;
```

4.我自己的解决方案,手动带上Attachment也能通
```java
 try {
                RpcContext.getContext().setAttachment("group", "aaa");
                return service1.xxx();
        } finally {
            RpcContext.getContext().removeAttachment("group");
        }
```

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

理论上说group配置后应该能调通，不应该手动setAttachment

### Actual Result
分析问题：
org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol 第261行  inv.getAttachments().get(GROUP_KEY) is null

```java
String serviceKey = serviceKey(port, path, inv.getAttachments().get(VERSION_KEY), inv.getAttachments().get(GROUP_KEY));
        DubboExporter<?> exporter = (DubboExporter<?>) exporterMap.get(serviceKey);

        if (exporter == null) {
            throw new RemotingException(channel, "Not found exported service: " + serviceKey + " in " + exporterMap.keySet() + ", may be version or group mismatch " +
                    ", channel: consumer: " + channel.getRemoteAddress() + " --> provider: " + channel.getLocalAddress() + ", message:" + inv);
        }



```

```
12:02:42.983  [http-nio-8080-exec-2] ERROR o.p.h.license.LicenseController - Failed to invoke remote method: xxx, provider: dubbo://localhost:12345/xxxx?application=xxx&check=false&interface=xxxx.common.service.LicenseService&lazy=false&pid=18076&qos.enable=false&register.ip=192.168.31.118&remote.application=&retries=0&side=consumer&sticky=false&timeout=5000&url=dubbo://localhost:12345, cause: org.apache.dubbo.remoting.RemotingException: org.apache.dubbo.remoting.RemotingException: Not found exported service: xxxx.common.service.LicenseService:12345 in [ ... aaa/xxxx.common.service.LicenseService:12345, ...], may be version or group mismatch , channel: consumer: /192.168.31.118:52787 --> provider: /192.168.31.118:12345, message:RpcInvocation [methodName=getLicenseInfo, parameterTypes=[], arguments=[], attachments={path=xxxx.common.service.LicenseService, input=271, dubbo=2.0.2, interface=xxxx.common.service.LicenseService, version=0.0.0, lang_locale=zh_CN, timeout=5000}]
org.apache.dubbo.remoting.RemotingException: Not found exported service: xxxx.common.service.LicenseService:12345 in [... aaa/xxxx.common.service.LicenseService:12345,...], may be version or group mismatch , channel: consumer: /192.168.31.118:52787 --> provider: /192.168.31.118:12345, message:RpcInvocation [methodName=getLicenseInfo, parameterTypes=[], arguments=[], attachments={path=xxxx.common.service.LicenseService, input=271, dubbo=2.0.2, interface=xxxx.common.service.LicenseService, version=0.0.0, lang_locale=zh_CN, timeout=5000}]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:266)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:127)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:102)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:193)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

```

**Comment by lkj41110** [comment]
按照你的描述`去掉group能通`说明提供者的group是没有生效的，说明消费者没有问题。
```
                RpcContext.getContext().setAttachment("group", "aaa");
```
隐式传参是在调用的时候拦截器的时候生效的，而获取提供者根据group获取提供者在调用之前，可以调用通是因为 你调用的还是没有group的提供者。

能不能提供一下你的提供者的篇日志。

**Comment by lkj41110** [comment]
可以看下你的zk的providers 里有没有group属性

**Comment by hyberbin** [comment]
我描述有问题，第二步是同时去掉了消费端和服务端的group参数。
zk中的内容如下：
[zk: 192.168.10.98(CONNECTED) 5] ls /dubbo/xxx.common.service.LicenseService/providers
[dubbo://0:0:0:0:0:0:0:1:12345/xxxx.common.service.LicenseService?anyhost=true&application=hyperone-dubbo-provider&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&group=cloud&interface=xxxx.common.service.LicenseService&methods=getLicenseInfo,refresh,updateLicense&pid=7&register=true&release=2.7.3&revision=1.0-SNAPSHOT&side=provider&timestamp=1571386775604]

**Comment by lkj41110** [comment]
本地试了下，好像没有办法重现你说的问题。
```
/dubbo/xxx.common.service.LicenseService/providers
/dubbo/xxx.common.service.LicenseService/consumers
```
当加group属性后,提供者和消费者的都会增加对应的group节点。
且消费者调用过程中，会在ConsumerContextFilter.invoke中放入group属性。

看你的描述很有可能是调用过程group丢失了。

**Comment by hyberbin** [comment]
我从源码中并没有看到ConsumerContextFilter.invoke中放入group属性

下面是我重写了ConsumerContextFilter，会调用super.invoke(invoker, invocation)
```
@Activate(group = CommonConstants.CONSUMER)
@Configuration
@Slf4j
public class DubboContextFilter extends ConsumerContextFilter {

    @Override
    public Result invoke(Invoker<?> invoker, Invocation invocation) throws RpcException {
        String langLocale = LocaleContextHolder.getLocale().toString();
        if (langLocale != null) {
            RpcContext.getContext().setAttachment("lang_locale", langLocale);
        }
        String requestId = MDC.get("requestId");
        if(requestId!=null){
            RpcContext.getContext().setAttachment("requestId", requestId);
        }
        Result invoke = super.invoke(invoker, invocation);
        String serverIp = invoke.getAttachment("serverIp");
        if(StringUtils.isNotEmpty(serverIp)){
            log.info("serverIp:{},method:{}.{}",serverIp,invoker.getInterface().getName(),invocation.getMethodName());
        }
        
        return invoke;
    }
}
```

**Comment by lkj41110** [comment]
sorry，应该是AbstractInvoker.invoke
```
if (CollectionUtils.isNotEmptyMap(attachment)) {
            //理论上，会把interface,group,token ,timeout 放进去
            invocation.addAttachmentsIfAbsent(attachment);
        }
        Map<String, String> contextAttachments = RpcContext.getContext().getAttachments();
        if (CollectionUtils.isNotEmptyMap(contextAttachments)) {
            invocation.addAttachments(contextAttachments);
        }
```

**Comment by hyberbin** [comment]
我的锅，，，sorry
