### ISSUE TITLE
NullPointerException when start provider

### ISSUE THREAD

**Issue by luyuanwan** [apache/dubbo#5216]
- [*] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [*] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.5-SNAPSHOT
* Dubbo branch: master
* Operating System version: macOS Catalina
* Java version: jdk-11.0.5

### Steps to reproduce this issue

1. start zookeeper in localhost and port is 2181
2. write provider-side code
3. start provider, the provider-side code looks like this

```java
public class Application {

	private static String zookeeperHost = System.getProperty("zookeeper.address", "127.0.0.1");

	public static void main(String[] args) throws Exception {
		ServiceConfig<DemoService> service = new ServiceConfig<DemoService>();
		service.setApplication(new ApplicationConfig("first-dubbo-provider"));
		service.setRegistry(new RegistryConfig("zookeeper://" + zookeeperHost + ":2181"));
		service.setInterface(DemoService.class);
		service.setRef(new DemoServiceImpl());
		service.export();

		System.out.println("dubbo service started");
		new CountDownLatch(1).await();
	}
}
```

### Actual Result

But I got an exception.

```
Exception in thread "main" java.lang.NullPointerException
	at org.apache.dubbo.config.AbstractInterfaceConfig.lambda$useRegistryForConfigIfNecessary$7(AbstractInterfaceConfig.java:628)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at org.apache.dubbo.config.AbstractInterfaceConfig.lambda$useRegistryForConfigIfNecessary$8(AbstractInterfaceConfig.java:620)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.apache.dubbo.config.AbstractInterfaceConfig.useRegistryForConfigIfNecessary(AbstractInterfaceConfig.java:618)
	at org.apache.dubbo.config.AbstractInterfaceConfig.checkRegistry(AbstractInterfaceConfig.java:208)
	at org.apache.dubbo.config.ServiceConfig.checkAndUpdateSubConfigs(ServiceConfig.java:303)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:370)
	at com.example.studydubboProvider.Application.main(Application.java:22)
```

Is this an issue?

**Comment by lkj41110** [comment]
#5186

**Comment by luyuanwan** [comment]
@lkj41110  NO , I found it is  client is null, not Parameters

**Comment by lkj41110** [comment]
Map.put(key,null) dont throw an NullPointerException

**Comment by luyuanwan** [comment]
@lkj41110   OK ,I will recheck. You dubbo version is 2.7.4.1, mine is 2.7.5-SNAPSHOT(branch master).Thanks anyway.

**Comment by chickenlj** [comment]
Please follow the release progress posted in this issue: https://github.com/apache/dubbo/issues/5219
