### ISSUE TITLE
java.lang.IllegalStateException: zookeeper not connected

### ISSUE THREAD

**Issue by gaoxianggithub** [apache/dubbo#5230]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.5-SNAPSHOT
* Operating System version: windows10
* Java version: 1.8
* zookeeper version: 3.4.12

### Steps to reproduce this issue

1.最近学习dubbo， 自己在用vm搭建了zookeeper 集群，系统是centos7。
2. 自己的系统是win10，在idea中下载了官网的dubbo-demo，运行其中的/dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-provider时，抛出异常：Exception in thread "main" java.lang.IllegalStateException: zookeeper not connected
3. 只修改/dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-provider/src/main/resources/spring/dubbo-provider.xml的<dubbo:registry timeout="100000" address="zookeeper://192.168.71.101:2181?backup=192.168.71.102:2181,192.168.71.103:2181,192.168.71.104:2181"/>
地址为运行在vmare的zookeeper集群地址，联网方式是NAT

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Exception in thread "main" java.lang.IllegalStateException: zookeeper not connected
	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.<init>(CuratorZookeeperClient.java:93)
	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperTransporter.createZookeeperClient(CuratorZookeeperTransporter.java:26)
	at org.apache.dubbo.remoting.zookeeper.support.AbstractZookeeperTransporter.connect(AbstractZookeeperTransporter.java:68)
	at org.apache.dubbo.remoting.zookeeper.ZookeeperTransporter$Adaptive.connect(ZookeeperTransporter$Adaptive.java)
	at org.apache.dubbo.configcenter.support.zookeeper.ZookeeperDynamicConfiguration.<init>(ZookeeperDynamicConfiguration.java:62)
	at org.apache.dubbo.configcenter.support.zookeeper.ZookeeperDynamicConfigurationFactory.createDynamicConfiguration(ZookeeperDynamicConfigurationFactory.java:37)
	at org.apache.dubbo.configcenter.AbstractDynamicConfigurationFactory.getDynamicConfiguration(AbstractDynamicConfigurationFactory.java:33)
	at org.apache.dubbo.config.AbstractInterfaceConfig.getDynamicConfiguration(AbstractInterfaceConfig.java:315)
	at org.apache.dubbo.config.AbstractInterfaceConfig.prepareEnvironment(AbstractInterfaceConfig.java:290)
	at org.apache.dubbo.config.AbstractInterfaceConfig.startConfigCenter(AbstractInterfaceConfig.java:280)
	at org.apache.dubbo.config.AbstractInterfaceConfig.lambda$null$7(AbstractInterfaceConfig.java:631)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.apache.dubbo.config.AbstractInterfaceConfig.lambda$useRegistryForConfigIfNecessary$8(AbstractInterfaceConfig.java:620)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.apache.dubbo.config.AbstractInterfaceConfig.useRegistryForConfigIfNecessary(AbstractInterfaceConfig.java:618)
	at org.apache.dubbo.config.AbstractInterfaceConfig.checkRegistry(AbstractInterfaceConfig.java:208)
	at org.apache.dubbo.config.ServiceConfig.checkAndUpdateSubConfigs(ServiceConfig.java:303)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:370)
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:336)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:114)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:60)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at org.apache.dubbo.demo.provider.Application.main(Application.java:23)
Caused by: java.lang.IllegalStateException: zookeeper not connected
	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.<init>(CuratorZookeeperClient.java:90)
	... 30 more

```

**Comment by happyrambo** [comment]
Use the default config-center, the timeout period is 3 seconds, this 3 seconds is used on the zk connection. When starting, the above exception occurs when connect zk exceeds 3 seconds.
see the class org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient, line 78.
can customize the config-center, set timeout property value equal 60s to resolve the problem.

**Comment by gaoxianggithub** [comment]
首先，非常感谢您在百忙之中抽空回复我。我想就我的情况详细说明下，我的网络是应该是通畅的，我是用xshell操作的虚拟机的，其次，我下载的dubbo-admin是可以跑起来的，并且可以查看我自己写的一个测试接口，可是用了git上dubbo的代码就总是连不上zk，所以不免有点疑惑，希望您能抽空帮忙看下。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"大雁小鱼"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月24日(星期四) 晚上10:21
收件人:&nbsp;"apache/dubbo"<dubbo@noreply.github.com&gt;;
抄送:&nbsp;"gaoxiang"<624545217@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/dubbo] java.lang.IllegalStateException: zookeeper not connected (#5230)




@gaoxianggithub  我建议，首先确定网络是否是通顺的，你先通过命令连接VMWARE里的ZK试试，看是否能连上

**Comment by ningyu1** [comment]
当没有使用config center时根据registry参数生成一个默认的config center时无法将timeout和group透传下去，位置：AbstractInterfaceConfig.useRegistryForConfigIfNecessary
问题同：#5276

**Comment by gaoxianggithub** [comment]
> @gaoxianggithub 我建议，首先确定网络是否是通顺的，你先通过命令连接VMWARE里的ZK试试，看是否能连上
> 
> 我在测试的时候是使用docker启动一个ZK，然后本机启动provider和consumer的，暂时没遇到过连不上ZK的情况

**Comment by handsome-fstar** [comment]
我也遇到了同样的问题，我虚拟机起了一个zookeeper，telnet是通的。我的同事同样的代码，可以注册进去，我的启动也是报zookeeper not connected

**Comment by pugwoo** [comment]
我也碰到这个问题，2.7.1则没有这个问题。已经检查zk是没有问题的，也不是超时的问题，dubbo设置到60秒超时依然有这个问题。

**Comment by GrowUp-hzy** [comment]
同样的问题`zkCli.sh -server host:port`可以连接,`-e ZOO_TICK_TIME=6000`
但是我的springboot应用还是无法连接

**Comment by GrowUp-hzy** [comment]
```xml
  <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>0.2.0</version>
        </dependency>
```
换成阿里的老版本居然就可以

**Comment by MiltonLai** [comment]
I got the same problem under Dubbo 2.7.4.1, this can be solved by adding config-center:timeout in your application.yml like this:
```
dubbo:
  registry:
    protocol: zookeeper 
    address: @dubbo.registry@

  config-center:
    timeout: 20000
```

**Comment by halleycomet** [comment]
@MiltonLai
fixed just add

  config-center:
    timeout: 20000

**Comment by oneslideicywater** [comment]
dubbo.registry.use-as-config-center:false

**Comment by 1859197812** [comment]
设置config-center的超时可以解决。默认3秒，大概率连接失败。
