### ISSUE TITLE
Dubbo 2.7.4.1 Use zookeeper registry, generic call throws error: 'zookeeper not connected '.

### ISSUE THREAD

**Issue by ningyu1** [apache/dubbo#5276]
### Environment

* Dubbo version: 2.7.4.1
* Operating System version: Win7
* Java version: jdk8

### Steps to reproduce this issue

1. Dubbo 2.7.4.1 Use zookeeper registry, generic call reports an error: 'zookeeper not connected '.
2. Dubbo 2.7.3 no such problem

### Expected Result

Interface accessed successfully

### Actual Result

java.lang.IllegalStateException: zookeeper not connected

If there is an exception, please attach the exception trace:

```
java.lang.IllegalStateException: zookeeper not connected

	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.<init>(CuratorZookeeperClient.java:83)
	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperTransporter.createZookeeperClient(CuratorZookeeperTransporter.java:26)
	at org.apache.dubbo.remoting.zookeeper.support.AbstractZookeeperTransporter.connect(AbstractZookeeperTransporter.java:68)
	at org.apache.dubbo.remoting.zookeeper.ZookeeperTransporter$Adaptive.connect(ZookeeperTransporter$Adaptive.java)
	at org.apache.dubbo.configcenter.support.zookeeper.ZookeeperDynamicConfiguration.<init>(ZookeeperDynamicConfiguration.java:62)
	at org.apache.dubbo.configcenter.support.zookeeper.ZookeeperDynamicConfigurationFactory.createDynamicConfiguration(ZookeeperDynamicConfigurationFactory.java:37)
	at org.apache.dubbo.configcenter.AbstractDynamicConfigurationFactory.getDynamicConfiguration(AbstractDynamicConfigurationFactory.java:33)
	at org.apache.dubbo.config.AbstractInterfaceConfig.getDynamicConfiguration(AbstractInterfaceConfig.java:315)
	at org.apache.dubbo.config.AbstractInterfaceConfig.prepareEnvironment(AbstractInterfaceConfig.java:290)
	at org.apache.dubbo.config.AbstractInterfaceConfig.startConfigCenter(AbstractInterfaceConfig.java:280)
	at org.apache.dubbo.config.AbstractInterfaceConfig.lambda$null$7(AbstractInterfaceConfig.java:636)
	at org.apache.dubbo.config.AbstractInterfaceConfig$$Lambda$38/1374066265.get(Unknown Source)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.apache.dubbo.config.AbstractInterfaceConfig.lambda$useRegistryForConfigIfNecessary$8(AbstractInterfaceConfig.java:620)
	at org.apache.dubbo.config.AbstractInterfaceConfig$$Lambda$37/1704237553.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.apache.dubbo.config.AbstractInterfaceConfig.useRegistryForConfigIfNecessary(AbstractInterfaceConfig.java:618)
	at org.apache.dubbo.config.AbstractInterfaceConfig.checkRegistry(AbstractInterfaceConfig.java:208)
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:378)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:329)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:250)
```

### Sample code

```
ApplicationConfig application = new ApplicationConfig();
application.setName("api-generic-consumer");
ReferenceConfig<GenericService> reference = new ReferenceConfig<>();
reference.setVersion("1.0.0");
RegistryConfig registry = new RegistryConfig();
registry.setProtocol(Constants.REGISTRY_ZOOKEEPER);
registry.setAddress("192.168.0.58:2181,192.168.0.59:2181,192.168.0.60:2181");
reference.setRegistry(registry);
reference.setTimeout(2000);
reference.setGeneric(true);
reference.setApplication(application);
reference.setInterface("com.xxxxx.api.IXxxService");
GenericService genericService = reference.get();
Object obj = genericService.$invoke("getXxx", new String[]{Long.class.getName()}, new Long[]{1L});
String json = JsonUtils.toJson(obj);
System.out.println(json);
```

**Comment by chickenlj** [comment]
How does that URL difference affect the zookeeper connection?

**Comment by ningyu1** [comment]
@chickenlj 
I'm not sure

**Comment by ningyu1** [comment]
Configcenter timeout problem, default is 3000, increase to 4000 can solve the problem

**Comment by ningyu1** [comment]
当没有使用config center时，dubbo会根据registry参数生成一个默认的config center，但是在生成的时候没有考虑到将timeout和group透传下去，因此默认的ConfigCenterConfig中的timeout为3000毫秒，在网络不好的情况下会有'zookeeper not connected'

代码位置：AbstractInterfaceConfig.useRegistryForConfigIfNecessary
问题同

**Comment by ningyu1** [comment]
#5230

**Comment by ningyu1** [comment]
Why is the code of `master`, `3.x-dev`, `cloud-native`, `performance-tuning 2.7.x` branch and released 2.7.4.1 inconsistent?

I want to send a PR based on the released 2.7.4.1, but I don't know how to start？

@chickenlj

**Comment by handsome-fstar** [comment]
我也在2.7.4.1遇到了这个问题，我确保我的zookeeper的通讯是正常的，最奇怪的是，我win10环境下无法启动，同样的代码，我同事的Mac竟然可以正常启动。
而且为什么我配置了超时到60s了，也是无法启动？
<dubbo:registry address="zookeeper://192.168.2.245:2181" timeout="60000"/>
请问我这样配置有问题吗？

**Comment by handsome-fstar** [comment]
```
@Configuration
public class dubboConfiguration {

    @Bean
    public ConfigCenterConfig configCenterConfig() {
        ConfigCenterConfig configCenterConfig = new ConfigCenterConfig();
        configCenterConfig.setTimeout(60000L);
        return configCenterConfig;
    }

}
```
我尝试手动配置，貌似也不行

**Comment by wallfacers** [comment]
[#5378](https://github.com/apache/dubbo/issues/5378)

**Comment by ningyu1** [comment]
@handsome-fstar 
`<dubbo:registry address="zookeeper://192.168.2.245:2181" timeout="60000"/>`
这样配置不行的，2.7.4.1在没有配置ConfigCenter的时候会根据Registry生成一个默认的ConfigCenter，dubbo这个版本没有把Registry的timeout透传给ConfigCenter，所以registry上的timeout是无法控制元数据中心的连接超时

**Comment by shifefiei** [comment]
> @handsome-fstar
> `<dubbo:registry address="zookeeper://192.168.2.245:2181" timeout="60000"/>`
> 这样配置不行的，2.7.4.1在没有配置ConfigCenter的时候会根据Registry生成一个默认的ConfigCenter，dubbo这个版本没有把Registry的timeout透传给ConfigCenter，所以registry上的timeout是无法控制元数据中心的连接超时

请问怎么配置

**Comment by shifefiei** [comment]
> @handsome-fstar
> `<dubbo:registry address="zookeeper://192.168.2.245:2181" timeout="60000"/>`
> 这样配置不行的，2.7.4.1在没有配置ConfigCenter的时候会根据Registry生成一个默认的ConfigCenter，dubbo这个版本没有把Registry的timeout透传给ConfigCenter，所以registry上的timeout是无法控制元数据中心的连接超时

请问正确的配置方式是？

**Comment by gollon** [comment]
在win10上复现此问题，具体现象是：时好时坏，大约1/3的概率能连接上zk。当出现zookeeper not connected时，在应用机器和zk机器上均抓不到tcp包，也就是说此时dubbo应用在3s内根本就没有发送SYN给zk服务器。
延长timeout为10s时，不会出现此问题。
在win7上没有发现此问题。

**Comment by pugwoo** [comment]
我也碰到这个问题，2.7.1则没有这个问题。已经检查zk是没有问题的，也不是超时的问题，dubbo设置到60秒超时依然有这个问题。

**Comment by pugwoo** [comment]
> 我也碰到这个问题，2.7.1则没有这个问题。已经检查zk是没有问题的，也不是超时的问题，dubbo设置到60秒超时依然有这个问题。

在zk链接后面加上timeout属性之后就好了：
```
dubbo:
  registry:
    address: zookeeper://192.168.0.11:2181?timeout=30000
  metadata-report:
    address: zookeeper://192.168.0.11:2181?timeout=30000
```
