### ISSUE TITLE
添加“-Djava.net.preferIPv4Stack=true”参数之后，NetUtils.getLocalAddress0()错误的获取到Hyper-V虚拟网卡的地址

### ISSUE THREAD

**Issue by makingtime** [apache/dubbo#5283]
- [√] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [√] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4.1
* Operating System version: Windows 10 1809 64位专业版
* Java version: 1.8.0.191
* Nacos version: 1.1.3

### Steps to reproduce this issue
前提：
1，Windows 10 专业版启用Hyper-v，安装Docker for windows，但是Docker服务没启动
2，`C:\Windows\System32\drivers\etc\hosts` 中已设置了: `正确IP 主机名`

网卡环境：
![image](https://user-images.githubusercontent.com/53243647/68201797-6bafc180-fffd-11e9-8c1d-8a7fdea5d79d.png)

添加JVM参数“-Djava.net.preferIPv4Stack=true”，然后运行以下代码(从dubbo-2.7.4.1-sources.jar中复制的NetUtils.getLocalAddress()相关的代码)：

```
import java.io.IOException;
import java.net.Inet6Address;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.UnknownHostException;
import java.util.Enumeration;
import java.util.Optional;
import java.util.regex.Pattern;

public class Test {

    private static final Pattern IP_PATTERN = Pattern.compile("\\d{1,3}(\\.\\d{1,3}){3,5}$");

    private static final String ANYHOST_VALUE = "0.0.0.0";

    private static final String LOCALHOST_VALUE = "127.0.0.1";

    public static void main(String[] args) throws UnknownHostException {
        
        System.out.println(getIpByHost(getLocalAddress().getHostName()));
        
    }

    public static String getIpByHost(String hostName) {
        try {
            return InetAddress.getByName(hostName).getHostAddress();
        } catch (UnknownHostException e) {
            return hostName;
        }
    }

    public static InetAddress getLocalAddress() {

        InetAddress localAddress = getLocalAddress0();
        return localAddress;
    }

    private static InetAddress getLocalAddress0() {
        InetAddress localAddress = null;
        try {
            localAddress = InetAddress.getLocalHost();
            Optional<InetAddress> addressOp = toValidAddress(localAddress);
            if (addressOp.isPresent()) {
                return addressOp.get();
            }
        } catch (Throwable e) {
            e.printStackTrace();
        }

        try {
            Enumeration<NetworkInterface> interfaces = NetworkInterface.getNetworkInterfaces();
            if (null == interfaces) {
                return localAddress;
            }
            while (interfaces.hasMoreElements()) {
                try {
                    NetworkInterface network = interfaces.nextElement();
                    if (network.isLoopback() || network.isVirtual() || !network.isUp()) {
                        continue;
                    }
                    Enumeration<InetAddress> addresses = network.getInetAddresses();
                    while (addresses.hasMoreElements()) {
                        try {
                            Optional<InetAddress> addressOp = toValidAddress(addresses.nextElement());
                            if (addressOp.isPresent()) {
                                try {
                                    if(addressOp.get().isReachable(100)){
                                        return addressOp.get();
                                    }
                                } catch (IOException e) {
                                    // ignore
                                }
                            }
                        } catch (Throwable e) {
                            e.printStackTrace();
                        }
                    }
                } catch (Throwable e) {
                    e.printStackTrace();
                }
            }
        } catch (Throwable e) {
            e.printStackTrace();
        }
        return localAddress;
    }

    private static Optional<InetAddress> toValidAddress(InetAddress address) {
        if (address instanceof Inet6Address) {
            Inet6Address v6Address = (Inet6Address) address;
            if (isPreferIPV6Address()) {
                return Optional.ofNullable(normalizeV6Address(v6Address));
            }
        }
        if (isValidV4Address(address)) {
            return Optional.of(address);
        }
        return Optional.empty();
    }

    static boolean isPreferIPV6Address() {
        boolean preferIpv6 = Boolean.getBoolean("java.net.preferIPv6Addresses");
        if (!preferIpv6) {
            return false;
        }
        return false;
    }

    static InetAddress normalizeV6Address(Inet6Address address) {
        String addr = address.getHostAddress();
        int i = addr.lastIndexOf('%');
        if (i > 0) {
            try {
                return InetAddress.getByName(addr.substring(0, i) + '%' + address.getScopeId());
            } catch (UnknownHostException e) {
                // ignore
                e.printStackTrace();
            }
        }
        return address;
    }

    static boolean isValidV4Address(InetAddress address) {
        if (address == null || address.isLoopbackAddress()) {
            return false;
        }
        String name = address.getHostAddress();
        boolean result = (name != null
                && IP_PATTERN.matcher(name).matches()
                && !ANYHOST_VALUE.equals(name)
                && !LOCALHOST_VALUE.equals(name));
        return result;
    }
}
```

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

获取的IP应该是在`C:\Windows\System32\drivers\etc\hosts` 中已设置的正确IP

### Actual Result

添加“-Djava.net.preferIPv4Stack=true”参数之后，输出的IP是Hyper-V的虚拟网卡`vEthernet (Default Switch)`的IP，注册到Nacos的也是这个IP

去掉“-Djava.net.preferIPv4Stack=true”参数之后，输出的IP才是在`C:\Windows\System32\drivers\etc\hosts` 中已设置的正确IP

调试过程中发现，如果添加“-Djava.net.preferIPv4Stack=true”参数，则调用链是:
```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.net.Inet4AddressImpl.lookupAllHostAddr(Inet4AddressImpl.java:-1)
	  at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	  at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	  at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
```
最后获取到的IP是Hyper-V的虚拟网卡的IP

如果去掉“-Djava.net.preferIPv4Stack=true”参数，则调用链是:
```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:-1)
	  at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	  at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	  at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
```
最后获取到的IP是在`C:\Windows\System32\drivers\etc\hosts` 中已设置的正确IP

**Comment by makingtime** [comment]
网卡信息：

```
ipconfig /all

Windows IP 配置

   主机名  . . . . . . . . . . . . . : DESKTOP-xxxx
   主 DNS 后缀 . . . . . . . . . . . :
   节点类型  . . . . . . . . . . . . : 混合
   IP 路由已启用 . . . . . . . . . . : 否
   WINS 代理已启用 . . . . . . . . . : 否


无线局域网适配器 WLAN:

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Intel(R) Dual Band Wireless-AC 3165
   物理地址. . . . . . . . . . . . . : xx-xx-xx-xx-xx-xx
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是
   本地链接 IPv6 地址. . . . . . . . : fe80::49d2:xxx:xxx:xxxx%14(首选)
   IPv4 地址 . . . . . . . . . . . . : 172.16.20.100(首选)
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 172.16.20.1
   DHCPv6 客户端 DUID  . . . . . . . : 00-01-00-01-55-9C-63-7B-AB-TY-5B-3D-89-7D
   DNS 服务器  . . . . . . . . . . . : 172.16.22.100
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用


以太网适配器 vEthernet (Default Switch):

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter
   物理地址. . . . . . . . . . . . . : XX-XX-XX-XX-XX-XX
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是
   本地链接 IPv6 地址. . . . . . . . : fe80::41a:xxx:XXX:56f7%26(首选)
   IPv4 地址 . . . . . . . . . . . . : 172.17.159.67(首选)
   子网掩码  . . . . . . . . . . . . : 255.255.255.240
   默认网关. . . . . . . . . . . . . :
   DHCPv6 客户端 DUID  . . . . . . . : 00-01-00-01-23-9C-66-3B-80-AF-B7-23-67-3F
   DNS 服务器  . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用
```

**Comment by wangkezun** [comment]
看起来应该与dubbo无关，而是java提供的InetAddress在ipv4与ipv6两种impl获取地址列表不同导致的。

**Comment by makingtime** [comment]
`InetAddress[] InetAddress.getAddressesFromNameService()` 1324行：`addresses = nameService.lookupAllHostAddr(host);` 是可以拿到所有地址的，

但是`InetAddress.getLocalHost()` 1512行 只返回第一个地址，
```
  cachedLocalHost = localAddrs[0];
  cacheTime = now;
  ret = localAddrs[0];
```

而带有“-Djava.net.preferIPv4Stack=true”参数时，拿到的是2个地址：
1：Hyper-V网卡地址
2：无线网卡地址（也是hosts中配置的地址）

不带“-Djava.net.preferIPv4Stack=true”参数时，拿到的是4个地址：
1：无线网卡地址（也是hosts中配置的地址）
2：Hyper-V网卡地址
3：无线网卡IPV6地址
4：Hyper-V网卡IPV6地址

带有“-Djava.net.preferIPv4Stack=true”参数时，Hyper-V网卡地址在前面，所以。。。

**Comment by wangkezun** [comment]
> `InetAddress[] InetAddress.getAddressesFromNameService()` 1324行：`addresses = nameService.lookupAllHostAddr(host);` 是可以拿到所有地址的，
> 
> 但是`InetAddress.getLocalHost()` 1512行 只返回第一个地址，
> 
> ```
>   cachedLocalHost = localAddrs[0];
>   cacheTime = now;
>   ret = localAddrs[0];
> ```
> 
> 而带有“-Djava.net.preferIPv4Stack=true”参数时，拿到的是2个地址：
> 1：Hyper-V网卡地址
> 2：无线网卡地址（也是hosts中配置的地址）
> 
> 不带“-Djava.net.preferIPv4Stack=true”参数时，拿到的是4个地址：
> 1：无线网卡地址（也是hosts中配置的地址）
> 2：Hyper-V网卡地址
> 3：无线网卡IPV6地址
> 4：Hyper-V网卡IPV6地址
> 
> 带有“-Djava.net.preferIPv4Stack=true”参数时，Hyper-V网卡地址在前面，所以。。。

看现在openjdk的master分支的两个impl的获取逻辑改成一致的了 没深究是哪个版本引入的 我测试11是已经好了。

**Comment by makingtime** [comment]
确实11获取的地址数组顺序对了
