### ISSUE TITLE
 2.7.4-release demo工程抛异常

### ISSUE THREAD

**Issue by lebron374** [apache/dubbo#5284]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4-release
* Operating System version: windows 7
* Java version: 1.8.0_101

### Steps to reproduce this issue

1、运行org.apache.dubbo.demo.provider.Application
2、直接抛异常

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
[06/11/19 08:52:38:145 CST] main  INFO logger.LoggerFactory: using logger: org.apache.dubbo.common.logger.log4j.Log4jLoggerAdapter
Exception in thread "main" java.lang.NullPointerException
	at org.apache.dubbo.config.AbstractInterfaceConfig.lambda$null$7(AbstractInterfaceConfig.java:628)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.apache.dubbo.config.AbstractInterfaceConfig.lambda$useRegistryForConfigIfNecessary$8(AbstractInterfaceConfig.java:620)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.apache.dubbo.config.AbstractInterfaceConfig.useRegistryForConfigIfNecessary(AbstractInterfaceConfig.java:618)
	at org.apache.dubbo.config.AbstractInterfaceConfig.checkRegistry(AbstractInterfaceConfig.java:208)
	at org.apache.dubbo.config.ServiceConfig.checkAndUpdateSubConfigs(ServiceConfig.java:303)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:370)
	at org.apache.dubbo.demo.provider.Application.main(Application.java:33)
[06/11/19 08:52:38:730 CST] DubboShutdownHook  INFO config.DubboShutdownHook:  [DUBBO] Run shutdown hook now., dubbo version: , current host: 172.17.32.176
[06/11/19 08:52:38:732 CST] DubboShutdownHook  INFO support.AbstractRegistryFactory:  [DUBBO] Close all registries [], dubbo version: , current host: 172.17.32.176
```

**Comment by lebron374** [comment]
![image](https://user-images.githubusercontent.com/5032169/68259654-6e4dfd80-0075-11ea-82f5-e00eda27fe31.png)

**Comment by htynkn** [comment]
具体是哪个demo，另外能够试试2.7.4.1版本吗？
有一个可能有关的紧急修复：https://github.com/apache/dubbo/pull/5205

**Comment by jasonjoo2010** [comment]
That's why an instant bug fixed version is filed. So you may try the branch `master`.

For details please refer to https://github.com/apache/dubbo/commit/87547793e0530aabdf429218629def9001347252

**Comment by lebron374** [comment]
@jasonjoo2010 谢谢，应该就是这个问题

**Comment by lebron374** [comment]
> 具体是哪个demo，另外能够试试2.7.4.1版本吗？
> 有一个可能有关的紧急修复：#5205

看到其他人已经修复了呢。

**Comment by lebron374** [comment]
> 具体是哪个demo，另外能够试试2.7.4.1版本吗？
> 有一个可能有关的紧急修复：#5205

请问如何拉取2.7.4.1的分支，我在本地branch和tag里都没有找到2.7.4.1

**Comment by htynkn** [comment]
建议fetch一下，应该是没有拉最新的。

https://github.com/apache/dubbo/tree/dubbo-2.7.4.1
