### ISSUE TITLE
report metadata to nacos cause npe

### ISSUE THREAD

**Issue by steveguoshao** [apache/dubbo#5286]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: centos 7.3
* Java version: jdk1.8.0_221

### Steps to reproduce this issue

1. dubbo.metadata-report.address = nacos://127.0.0.1:8848
dubbo.registry.address = nacos://127.0.0.1:8848
dubbo.registry.simplified = false

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
org.apache.dubbo.rpc.RpcException: Failed to put org.apache.dubbo.metadata.identifier.MetadataIdentifier@e4a8091 to nacos {"side":"consumer","release":"2.7.3","methods":"xxx,"lazy":"false","logger":"slf4j","dubbo":"2.0.2","check":"false","interface":"xxxx","version":"1.0.0","qos.enable":"false","generic":"false","timeout":"3000","revision":"1.0.0","retries":"0","application":"xxx","sticky":"false","validation":"true"}, cause: null
        at org.apache.dubbo.metadata.store.nacos.NacosMetadataReport.storeMetadata(NacosMetadataReport.java:132) ~[dubbo-2.7.3.jar!/:2.7.3]
        at org.apache.dubbo.metadata.store.nacos.NacosMetadataReport.doStoreConsumerMetadata(NacosMetadataReport.java:121) ~[dubbo-2.7.3.jar!/:2.7.3]
        at org.apache.dubbo.metadata.support.AbstractMetadataReport.storeConsumerMetadataTask(AbstractMetadataReport.java:274) ~[dubbo-2.7.3.jar!/:2.7.3]
        at org.apache.dubbo.metadata.support.AbstractMetadataReport.lambda$storeConsumerMetadata$1(AbstractMetadataReport.java:260) ~[dubbo-2.7.3.jar!/:2.7.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_221]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78) ~[?:1.8.0_221]
        at java.io.InputStreamReader.<init>(InputStreamReader.java:97) ~[?:1.8.0_221]
        at com.alibaba.nacos.client.config.utils.IOUtils.toString(IOUtils.java:33) ~[nacos-client-1.1.1.jar!/:?]
        at com.alibaba.nacos.client.config.impl.HttpSimpleClient.httpPost(HttpSimpleClient.java:129) ~[nacos-client-1.1.1.jar!/:?]
        at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:135) ~[nacos-client-1.1.1.jar!/:?]
        at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64) ~[nacos-client-1.1.1.jar!/:?]
        at com.alibaba.nacos.client.config.NacosConfigService.publishConfigInner(NacosConfigService.java:283) ~[nacos-client-1.1.1.jar!/:?]
        at com.alibaba.nacos.client.config.NacosConfigService.publishConfig(NacosConfigService.java:139) ~[nacos-client-1.1.1.jar!/:?]
        at org.apache.dubbo.metadata.store.nacos.NacosMetadataReport.storeMetadata(NacosMetadataReport.java:126) ~[dubbo-2.7.3.jar!/:2.7.3]
        ... 6 more
```

**Comment by chickenlj** [comment]
It seems like the NPE was thrown from Nacos sdk, we need to contact the Nacos team to see if it's a bug from them.
