### ISSUE TITLE
[DUBBO] Invalid value for MonthOfYear (valid values 1 - 12): 0

### ISSUE THREAD

**Issue by ym2008** [apache/dubbo#5301]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4.1
* Operating System version: CentOS 7.6
* Java version: 1.8

### Steps to reproduce this issue

1. kill the process
2. see the following exception in the logs

If there is an exception, please attach the exception trace:

```
2019-11-11 10:12:30.809 ERROR 5810 --- [NettyServerWorker-9-2] i.n.u.c.D.rejectedExecution              : Failed to submit a listener notification task. Event loop shut down?

java.lang.NoClassDefFoundError: io/netty/util/concurrent/GlobalEventExecutor$2
        at io.netty.util.concurrent.GlobalEventExecutor.startThread(GlobalEventExecutor.java:227) ~[netty-all-4.1.42.Final.jar!/:4.1.42.Final]
        at io.netty.util.concurrent.GlobalEventExecutor.execute(GlobalEventExecutor.java:215) ~[netty-all-4.1.42.Final.jar!/:4.1.42.Final]
        at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:841) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:498) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
        at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:96) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1089) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
Caused by: java.lang.ClassNotFoundException: io.netty.util.concurrent.GlobalEventExecutor$2
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_201]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_201]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93) ~[data-service.jar:0.0.1]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_201]
        ... 11 common frames omitted

2019-11-11 10:12:30.810  WARN 5810 --- [Thread-6] o.apache.dubbo.config.DubboShutdownHook  :  [DUBBO] Invalid value for MonthOfYear (valid values 1 - 12): 0, dubbo version: 2.7.4.1, current host: 10.31.120.92

java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0
        at java.time.temporal.ValueRange.checkValidValue(ValueRange.java:311) ~[na:1.8.0_201]
        at java.time.temporal.ChronoField.checkValidValue(ChronoField.java:703) ~[na:1.8.0_201]
        at java.time.LocalDate.of(LocalDate.java:267) ~[na:1.8.0_201]
        at java.time.LocalDateTime.of(LocalDateTime.java:336) ~[na:1.8.0_201]
        at org.springframework.boot.loader.jar.CentralDirectoryFileHeader.decodeMsDosFormatDateTime(CentralDirectoryFileHeader.java:127) ~[data-service.jar:0.0.1]
        at org.springframework.boot.loader.jar.CentralDirectoryFileHeader.getTime(CentralDirectoryFileHeader.java:116) ~[data-service.jar:0.0.1]
        at org.springframework.boot.loader.jar.JarEntry.<init>(JarEntry.java:58) ~[data-service.jar:0.0.1]
        at org.springframework.boot.loader.jar.JarFileEntries.getEntry(JarFileEntries.java:316) ~[data-service.jar:0.0.1]
        at org.springframework.boot.loader.jar.JarFileEntries.getEntry(JarFileEntries.java:300) ~[data-service.jar:0.0.1]
        at org.springframework.boot.loader.jar.JarFileEntries.doGetEntry(JarFileEntries.java:288) ~[data-service.jar:0.0.1]
        at org.springframework.boot.loader.jar.JarFileEntries.getEntry(JarFileEntries.java:243) ~[data-service.jar:0.0.1]
        at org.springframework.boot.loader.jar.JarFileEntries.getEntry(JarFileEntries.java:203) ~[data-service.jar:0.0.1]
        at org.springframework.boot.loader.jar.JarFile.getEntry(JarFile.java:225) ~[data-service.jar:0.0.1]
        at org.springframework.boot.loader.LaunchedURLClassLoader.lambda$definePackage$0(LaunchedURLClassLoader.java:138) ~[data-service.jar:0.0.1]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_201]
        at org.springframework.boot.loader.LaunchedURLClassLoader.definePackage(LaunchedURLClassLoader.java:130) ~[data-service.jar:0.0.1]
        at org.springframework.boot.loader.LaunchedURLClassLoader.definePackageIfNecessary(LaunchedURLClassLoader.java:112) ~[data-service.jar:0.0.1]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:81) ~[data-service.jar:0.0.1]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_201]
        at org.apache.dubbo.qos.protocol.QosProtocolWrapper.stopServer(QosProtocolWrapper.java:112) ~[dubbo-2.7.4.1.jar!/:2.7.4.1]
        at org.apache.dubbo.qos.protocol.QosProtocolWrapper.destroy(QosProtocolWrapper.java:79) ~[dubbo-2.7.4.1.jar!/:2.7.4.1]
        at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.destroy(ProtocolFilterWrapper.java:135) ~[dubbo-2.7.4.1.jar!/:2.7.4.1]
        at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.destroy(ProtocolListenerWrapper.java:79) ~[dubbo-2.7.4.1.jar!/:2.7.4.1]
        at org.apache.dubbo.config.DubboShutdownHook.destroyProtocols(DubboShutdownHook.java:103) [dubbo-2.7.4.1.jar!/:2.7.4.1]
        at org.apache.dubbo.config.DubboShutdownHook.doDestroy(DubboShutdownHook.java:91) [dubbo-2.7.4.1.jar!/:2.7.4.1]
        at org.apache.dubbo.config.spring.extension.SpringExtensionFactory$ShutdownHookListener.onApplicationEvent(SpringExtensionFactory.java:114) [dubbo-2.7.4.1.jar!/:2.7.4.1]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) [spring-context-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) [spring-context-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [spring-context-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402) [spring-context-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359) [spring-context-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1009) [spring-context-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:945) [spring-context-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
```

**Comment by qinliujie** [comment]
jvm enter class unload process,so it may happen some exception like that
