### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.validator.engine.ConfigurationImpl

### ISSUE THREAD

**Issue by chenshun00** [apache/dubbo#5372]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.2
* Operating System version: docker
* Java version: 18

### Steps to reproduce this issue

服务端开启了validate=true , 依赖也加入了，但是`org.hibernate.validator.engine.ConfigurationImpl` 都没有这个类，服务调用都时候弄了这个类。

已经查阅过的链接
https://blog.csdn.net/hengyunabc/article/details/71513509

1. validate=true

```
Failed to invoke remote method: stopNotifyJob, provider: dubbo://10.4.3.136:30001/com.raycloud.notify.api.service.NotifyJobRequest?application=demo-docker&application.version=1.0.0ValidationAutoConfiguration&check=false&dubbo=2.6.2&interface=com.xxxxx.xxxx.xxx.service.xxxxx&methods=xxxx,xxx,xxx&pid=56&register.ip=10.0.0.72&revision=2.0.1&side=consumer&timeout=20000&timestamp=1574320167228&version=2.0.1-vpc, cause: com.alibaba.dubbo.rpc.RpcException: Could not initialize class org.hibernate.validator.engine.ConfigurationImpl
com.alibaba.dubbo.rpc.RpcException: Could not initialize class org.hibernate.validator.engine.ConfigurationImpl
	at com.alibaba.dubbo.validation.filter.ValidationFilter.invoke(ValidationFilter.java:54)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:64)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.raycloud.dubbo.rpc.filter.DubboConcurrentMonitor.invoke(DubboConcurrentMonitor.java:58)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.raycloud.eagle.trace.dubbo.DubboInvokeMonitorFilter.invoke(DubboInvokeMonitorFilter.java:78)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:60)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:112)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:108)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:84)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:170)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
	at com.alibaba.dubbo.remoting.transport.dispather.ChannelEventRunnable.run(ChannelEventRunnable.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.validator.engine.ConfigurationImpl
	at org.hibernate.validator.HibernateValidator.createGenericConfiguration(HibernateValidator.java:41)
	at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:269)
	at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:111)
	at com.alibaba.dubbo.validation.support.jvalidation.JValidator.<init>(JValidator.java:86)
	at com.alibaba.dubbo.validation.support.jvalidation.JValidation.createValidator(JValidation.java:31)
	at com.alibaba.dubbo.validation.support.AbstractValidation.getValidator(AbstractValidation.java:38)
	at com.alibaba.dubbo.validation.Validation$Adpative.getValidator(Validation$Adpative.java)
	at com.alibaba.dubbo.validation.filter.ValidationFilter.invoke(ValidationFilter.java:47)
	... 29 more
```

**Comment by chenshun00** [comment]
慎重使用validation功能，建议还是应用上做一次参数的校验. :(
