### ISSUE TITLE
use ZookeeperMetadataReportFactory,  no extension

### ISSUE THREAD

**Issue by coderlongren** [apache/dubbo#5405]
#Environment

* Dubbo version: 2.7.5-SNAPSHOT
* Operating System version: Mac OS
* Java version: 1.8

### Steps to reproduce this issue

1.  can't use Zookeeper metadatacenter,  my redis metadate is good, and I make sure the ZookeeperMetadataReportFactory extension exists.
```java
Exception in thread "main" java.lang.IllegalStateException: No such extension org.apache.dubbo.metadata.store.MetadataReportFactory by name zookeeper
	at org.apache.dubbo.common.extension.ExtensionLoader.noExtensionException(ExtensionLoader.java:520)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:529)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:346)
	at org.apache.dubbo.metadata.store.MetadataReportFactory$Adaptive.getMetadataReport(MetadataReportFactory$Adaptive.java)
	at org.apache.dubbo.metadata.integration.MetadataReportService.<init>(MetadataReportService.java:70)
	at org.apache.dubbo.metadata.integration.MetadataReportService.instance(MetadataReportService.java:83)
	at org.apache.dubbo.config.AbstractInterfaceConfig.getMetadataReportService(AbstractInterfaceConfig.java:434)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:629)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:458)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:416)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:379)
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:336)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:114)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:60)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at org.apache.dubbo.demo.provider.Application.main(Application.java:23)
```

**Comment by lkj41110** [comment]
Can you provide your config or a demo ？

**Comment by chickenlj** [comment]
Do you have dubbo-metadata-zookeeper in your classpath?

**Comment by chickenlj** [comment]
Please check and reopen if necessary.
