### ISSUE TITLE
2.7.4.1 版本的dubbo服务在docker容器内启动，无法连接容器外部的zookeeper

### ISSUE THREAD

**Issue by msdemt** [apache/dubbo#5474]
- [ √] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ √] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4.1
* Operating System version: linux
* Java version: 1.8.0_231

### Steps to reproduce this issue

1. 使用springboot写一个dubbo demo，在本地环境IDEA中运行成功
2. 启动一个jdk镜像，将dubbo demo 的jar包使用docker cp命令拷贝到jdk镜像生成的容器中（或者将dubbo demo构建为docker镜像，该镜像的容器无法运行，报错：连不上zookeeper）
3. 使用java -jar 命令运行jar包，提示连不上zookeeper（使用dubbo版本2.7.3正常！！）

### Expected Result

期望dubbo应用能够在docker容器中正常运行

### Actual Result

dubbo应用无法在docker容器中运行，提示连不上zookeeper

```
2019-12-12 09:12:26.462 ERROR 7 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: zookeeper not connected
	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.<init>(CuratorZookeeperClient.java:83) ~[dubbo-2.7.4.1.jar!/:2.7.4.1]
	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperTransporter.createZookeeperClient(CuratorZookeeperTransporter.java:26) ~[dubbo-2.7.4.1.jar!/:2.7.4.1]
	at org.apache.dubbo.remoting.zookeeper.support.AbstractZookeeperTransporter.connect(AbstractZookeeperTransporter.java:68) ~[dubbo-2.7.4.1.jar!/:2.7.4.1]
	at org.apache.dubbo.remoting.zookeeper.ZookeeperTransporter$Adaptive.connect(ZookeeperTransporter$Adaptive.java) ~[dubbo-2.7.4.1.jar!/:2.7.4.1]
	at org.apache.dubbo.configcenter.support.zookeeper.ZookeeperDynamicConfiguration.<init>(ZookeeperDynamicConfiguration.java:62) ~[dubbo-2.7.4.1.jar!/:2.7.4.1]
	at org.apache.dubbo.configcenter.support.zookeeper.ZookeeperDynamicConfigurationFactory.createDynamicConfiguration(ZookeeperDynamicConfigurationFactory.java:37) ~[dubbo-2.7.4.1.jar!/:2.7.4.1]
	at org.apache.dubbo.configcenter.AbstractDynamicConfigurationFactory.getDynamicConfiguration(AbstractDynamicConfigurationFactory.java:33) ~[dubbo-2.7.4.1.jar!/:2.7.4.1]
	at org.apache.dubbo.config.AbstractInterfaceConfig.getDynamicConfiguration(AbstractInterfaceConfig.java:315) ~[dubbo-2.7.4.1.jar!/:2.7.4.1]
	at org.apache.dubbo.config.AbstractInterfaceConfig.prepareEnvironment(AbstractInterfaceConfig.java:290) ~[dubbo-2.7.4.1.jar!/:2.7.4.1]
	at org.apache.dubbo.config.AbstractInterfaceConfig.startConfigCenter(AbstractInterfaceConfig.java:280) ~[dubbo-2.7.4.1.jar!/:2.7.4.1]
	at org.apache.dubbo.config.AbstractInterfaceConfig.lambda$null$7(AbstractInterfaceConfig.java:636) ~[dubbo-2.7.4.1.jar!/:2.7.4.1]
	at java.util.Optional.orElseGet(Optional.java:267) ~[na:1.8.0_232]
	at org.apache.dubbo.config.AbstractInterfaceConfig.lambda$useRegistryForConfigIfNecessary$8(AbstractInterfaceConfig.java:620) ~[dubbo-2.7.4.1.jar!/:2.7.4.1]
	at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_232]
	at org.apache.dubbo.config.AbstractInterfaceConfig.useRegistryForConfigIfNecessary(AbstractInterfaceConfig.java:618) ~[dubbo-2.7.4.1.jar!/:2.7.4.1]
	at org.apache.dubbo.config.AbstractInterfaceConfig.checkRegistry(AbstractInterfaceConfig.java:208) ~[dubbo-2.7.4.1.jar!/:2.7.4.1]
	at org.apache.dubbo.config.ServiceConfig.checkAndUpdateSubConfigs(ServiceConfig.java:303) ~[dubbo-2.7.4.1.jar!/:2.7.4.1]
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:370) ~[dubbo-2.7.4.1.jar!/:2.7.4.1]
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:336) ~[dubbo-2.7.4.1.jar!/:2.7.4.1]
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:114) ~[dubbo-2.7.4.1.jar!/:2.7.4.1]
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:60) ~[dubbo-2.7.4.1.jar!/:2.7.4.1]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:897) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140) [spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
	at com.example.demo.App.main(App.java:15) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_232]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_232]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_232]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [message-service-1.0.0.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [message-service-1.0.0.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [message-service-1.0.0.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [message-service-1.0.0.jar:na]
Caused by: java.lang.IllegalStateException: zookeeper not connected
	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.<init>(CuratorZookeeperClient.java:80) ~[dubbo-2.7.4.1.jar!/:2.7.4.1]
	... 40 common frames omitted
```

**Comment by chickenlj** [comment]
没理解到为什么会在两个版本间有不同的连接状态，请问你的 ip 都是用的什么方案？

**Comment by msdemt** [comment]
@chickenlj 没有其他的网络组件，就是docker自带的网络

**Comment by YZCSZHIWJ** [comment]
貌似也遇到过，把启动时检查关闭试下呢

**Comment by sstg** [comment]
默认网络配置当然不能连接外部的 zk, 要么 --network=host，要么把 zk 跑在容器里并且确保应用能访问到

**Comment by wormone11** [comment]
暂时可将zookeeper得docker容器切换到3.4.13版本下

**Comment by wormone11** [comment]
配置 <dubbo:config-center timeout="7000"/> 信息

**Comment by wormone11** [comment]
配置 <dubbo:config-center timeout="7000"/> 信息，根据实际的情况设置时间长度

**Comment by beiwei30** [comment]
pls. try `2.7.5`. I can run https://github.com/apache/dubbo-samples/tree/master/java/dubbo-samples-api in https://github.com/apache/dubbo-samples without any problem. I believe you may need to consider to specify zookeeper's address like this: https://github.com/apache/dubbo-samples/blob/master/java/dubbo-samples-api/pom.xml#L106

**Comment by beiwei30** [comment]
ps, you may need to consider to configure docker hub mirror like this: https://yq.aliyun.com/articles/29941
