### ISSUE TITLE
Start null pointer problem in dubbo 2.7.4

### ISSUE THREAD

**Issue by liujianbigboss** [apache/dubbo#5520]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue
![image](https://user-images.githubusercontent.com/57934445/71306583-316b7980-241d-11ea-9316-6f713b3d898d.png)
Spring boot version 2.2.2.release integration Dubbo version 2.7.4 is started by XML configuration, as shown in the figure above, if the configuration commented out is turned on, it will start normally, if the configuration commented out is turned off, the position shown in the figure below will have a null pointer problem:
![image](https://user-images.githubusercontent.com/57934445/71306605-77c0d880-241d-11ea-8b1b-70d6411acbfb.png)

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

Startup success

### Actual Result

Start failed with null pointer

Just put your stack trace here!

java.lang.NullPointerException: null
	at org.apache.dubbo.config.AbstractInterfaceConfig.lambda$null$7(AbstractInterfaceConfig.java:628) ~[dubbo-2.7.4.jar:2.7.4]
	at java.util.Optional.orElseGet(Optional.java:267) ~[na:1.8.0_211]
	at org.apache.dubbo.config.AbstractInterfaceConfig.lambda$useRegistryForConfigIfNecessary$8(AbstractInterfaceConfig.java:620) ~[dubbo-2.7.4.jar:2.7.4]
	at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_211]
	at org.apache.dubbo.config.AbstractInterfaceConfig.useRegistryForConfigIfNecessary(AbstractInterfaceConfig.java:618) ~[dubbo-2.7.4.jar:2.7.4]
	at org.apache.dubbo.config.AbstractInterfaceConfig.checkRegistry(AbstractInterfaceConfig.java:208) ~[dubbo-2.7.4.jar:2.7.4]
	at org.apache.dubbo.config.ServiceConfig.checkAndUpdateSubConfigs(ServiceConfig.java:303) ~[dubbo-2.7.4.jar:2.7.4]
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:370) ~[dubbo-2.7.4.jar:2.7.4]
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:336) ~[dubbo-2.7.4.jar:2.7.4]
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:114) ~[dubbo-2.7.4.jar:2.7.4]
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:60) ~[dubbo-2.7.4.jar:2.7.4]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403) ~[spring-context-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360) ~[spring-context-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:897) ~[spring-context-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162) ~[spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) ~[spring-context-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at com.bigboss.provider.AplicationRunner.main(AplicationRunner.java:22) [classes/:na]

**Comment by ZhiQinIsZhen** [comment]
升级到2.7.4.1，这个bug已经修复了，cc之前没有判断
if(cc.getParameters() == null) {
                    cc.setParameters(new HashMap());
                }
现在已经做了判断了

**Comment by canglang1973** [comment]
I have a doubt. I have reviewed the code and github commit log.
![image](https://user-images.githubusercontent.com/17998341/71430206-6883a880-2705-11ea-95ab-fe9daedcf9fb.png)
![image](https://user-images.githubusercontent.com/17998341/71430211-746f6a80-2705-11ea-8a0a-d57b91a83b77.png)
These two commit are next to each other.but I do not find the code had being move.Can you tell me why? @chickenlj

**Comment by htynkn** [comment]
Closing this issue since fixed in 2.7.4.1

by the way @canglang1973, your question is not related to this issue right?
For my personal view, those two commits are not next to each other, there are in different branch until one merge into master branch

**Comment by canglang1973** [comment]
Oh ,Thanks your answer.
