### ISSUE TITLE
dubbo 注册中心没有加protocol会失败，并且报错有问题

### ISSUE THREAD

**Issue by chenshun00** [apache/dubbo#5522]
### Environment

* Dubbo version: 2.6.2
* Operating System version: macos
* Java version: 1.8

### Steps to reproduce this issue

```xml
 <dubbo:registry id="defaultRegister" address="127.0.0.1:2181"/>
```

### Expected Result
希望报错配置注册中心错误。或者是优先使用zk

### Actual Result

```txt
java.lang.IllegalStateException: Failed to subscribe consumer://192.168.1.7/com.alibaba.dubbo.registry.RegistryService?application=chen&callbacks=10000&connect.timeout=10000&dubbo=2.6.2&interface=com.alibaba.dubbo.registry.RegistryService&lazy=true&methods=lookup,subscribe,unsubscribe,unregister,register&pid=84642&reconnect=false&sticky=true&subscribe.1.callback=true&timeout=10000&timestamp=1576949750389&unsubscribe.1.callback=false, cause: Failed to invoke the method subscribe in the service com.alibaba.dubbo.registry.RegistryService. Tried 3 times of the providers [127.0.0.1:2181] (1/1) from the registry 127.0.0.1:2181 on the consumer 192.168.1.7 using the dubbo version 2.6.2. Last error is: Invoke remote method timeout. method: subscribe, provider: dubbo://127.0.0.1:2181/com.alibaba.dubbo.registry.RegistryService?application=chen&callbacks=10000&check=false&connect.timeout=10000&dubbo=2.6.2&interface=com.alibaba.dubbo.registry.RegistryService&lazy=true&methods=lookup,subscribe,unsubscribe,unregister,register&pid=84642&reconnect=false&remote.timestamp=1576949750389&sticky=true&subscribe.1.callback=true&timeout=10000&timestamp=1576949750389&unsubscribe.1.callback=false, cause: Waiting server-side response timeout by scan timer. start time: 2019-12-22 01:36:10.773, end time: 2019-12-22 01:36:20.774, client elapsed: 1 ms, server elapsed: 10000 ms, timeout: 10000 ms, request: Request [id=4, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=subscribe, parameterTypes=[class com.alibaba.dubbo.common.URL, interface com.alibaba.dubbo.registry.NotifyListener], arguments=[consumer://192.168.1.7/com.alibaba.dubbo.registry.RegistryService?application=chen&callbacks=10000&connect.timeout=10000&dubbo=2.6.2&interface=com.alibaba.dubbo.registry.RegistryService&lazy=true&methods=lookup,subscribe,unsubscribe,unregister,register&pid=84642&reconnect=false&sticky=true&subscribe.1.callback=true&timeout=10000&timestamp=1576949750389&unsubscribe.1.callback=false, com.alibaba.dubbo.registry.integration.RegistryDirectory@32843980], attachments={path=com.alibaba.dubbo.registry.RegistryService, sys_callback_arg-1=847526272, interface=com.alibaba.dubbo.registry.RegistryService, version=0.0.0, timeout=10000}]], channel: 192.168.1.7:0 -> /127.0.0.1:2181
	at com.alibaba.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:207)
	at com.alibaba.dubbo.registry.integration.RegistryDirectory.subscribe(RegistryDirectory.java:159)
	at com.alibaba.dubbo.registry.dubbo.DubboRegistryFactory.createRegistry(DubboRegistryFactory.java:97)
	at com.alibaba.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:96)
	at com.alibaba.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:202)
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:136)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:98)
	at com.alibaba.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:55)
	at com.alibaba.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:54)
	at com.alibaba.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at com.alibaba.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:506)
	at com.alibaba.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:358)
	at com.alibaba.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:317)
	at com.alibaba.dubbo.config.ServiceConfig.export(ServiceConfig.java:216)
	at com.alibaba.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:123)
	at com.alibaba.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:49)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener
```

原因是注册中心的地址从 zookeeper://127.0.0.1:2181 ===> dubbo//127.0.0.1:2181
[代码地址](https://github.com/apache/dubbo/blob/e1beaf2f8ec65c317830f7e5ffbe5a4106a9b822/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java#L186-L188)

**Comment by zhuliangcai** [comment]
```java
org.apache.dubbo.registry.integration.AbstractConfiguratorListener#initWith
    protected final void initWith(String key) {
        DynamicConfiguration dynamicConfiguration = DynamicConfiguration.getDynamicConfiguration();
        dynamicConfiguration.addListener(key, this);
        String rawConfig = dynamicConfiguration.getRule(key, DynamicConfiguration.DEFAULT_GROUP);
        if (!StringUtils.isEmpty(rawConfig)) {
            genConfiguratorsFromRawRule(rawConfig);
        }
    }    

org.apache.dubbo.configcenter.DynamicConfiguration#getDynamicConfiguration
static DynamicConfiguration getDynamicConfiguration() {
        Optional<Configuration> optional = Environment.getInstance().getDynamicConfiguration();
        return (DynamicConfiguration) optional.orElseGet(() -> getExtensionLoader(DynamicConfigurationFactory.class)
                .getDefaultExtension()
                .getDynamicConfiguration(null));
    }
```
在方法配置registry 时，没有协议名称就不会在 Environment.getInstance()中添加DynamicConfiguration，从而在上述的initWith方法中调用了获取getDynamicConfiguration的方法，由于获取不到对象，不得不执行lambda表达式中的获取方式，主要问题在此处传递了null，经测试此处必然报空指针异常，从源码中也能看出异常来自org.apache.dubbo.configcenter.support.zookeeper.ZookeeperDynamicConfiguration#ZookeeperDynamicConfiguration构造方法中根据url获取参数。
这里之所以会报错主要原因在于下面的类被修改了
```java 
//@SPI("nop")
@SPI("zookeeper")
public interface DynamicConfigurationFactory {
    DynamicConfiguration getDynamicConfiguration(URL url);
}
```
默认值改为了 zookeeper ,而 nop对应的类NopDynamicConfiguration在构造是不会报错的

**Comment by htynkn** [comment]
试了一下，2.7.5版本也是一样的报错信息，报错信息是否可以优化这个可以评估下

如果不加地址中加protocol也可以单独指定，比如
``` xml
<dubbo:registry id="defaultRegister" address="127.0.0.1:2181" protocol="zookeeper"/>
```

**Comment by chenshun00** [comment]
@htynkn  我觉得严格一点会好一些，直接要求必须指定protocol，越严格简单的错误就会在一开始就规避
