### ISSUE TITLE
Dubbo 2.7.5 has just been released

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo#5552]
Please check [2.7.5 Release Notes](https://github.com/apache/dubbo/releases/tag/dubbo-2.7.5) for details, more detailed docs will be published later at [the official website](dubbo.apache.org).

**Comment by RojerAlone** [comment]
Is it compatible with 2.7.3? And can I use dubbo 2.7.5 and use dubbo-spring-boot 2.7.3?

Beside these, I think dubbo can do better on these:

- [release notes](https://github.com/apache/dubbo/blob/master/CHANGES.md) should show if there are something compatible with previous version
- show roadmap and release notes on officical website

**Comment by htynkn** [comment]
Another stuff is for ```Refactoring of config module```, 
what user should do for jdk11 env and what user should do with manual config instantiation should list in website.

for example how new config works with below code:
``` java
 @Configuration
    @EnableDubbo(scanBasePackages = "org.apache.dubbo.samples.metadatareport.configcenter.impl")
    @PropertySource("classpath:/spring/dubbo-provider.properties")
    static public class ProviderConfiguration {
        @Bean
        public ProviderConfig providerConfig() {
            ProviderConfig providerConfig = new ProviderConfig();
            providerConfig.setTimeout(1000);
            return providerConfig;
        }
    }
```

**Comment by RojerAlone** [comment]
> Is it compatible with 2.7.3? And can I use dubbo 2.7.5 and use dubbo-spring-boot 2.7.3?
> 
> Beside these, I think dubbo can do better on these:
> 
> * [release notes](https://github.com/apache/dubbo/blob/master/CHANGES.md) should show if there are something compatible with previous version
> * show roadmap and release notes on officical website

I found there are some compatibility since 2.7.5:
- the constructor of `AbstractRouter` remove `DynamicConfiguration` param
- constant "dubbo.tag" was removed from `org.apache.dubbo.rpc.cluster.Constants` to `CommonConstants`

**Comment by RojerAlone** [comment]
Another compatibility problem, method `org.apache.dubbo.rpc.Filter.Listener.onResponse` was renamed to `onMessage`, I think create a new `onMessage` method and annotation `@Deprecated` on `onResponse` is better than renaming directly.

Besides this, I start my service failed because of NPE:
```
java.lang.NullPointerException: null
	at org.apache.dubbo.registry.integration.RegistryProtocol.register(RegistryProtocol.java:178) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:209) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:60) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:143) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:64) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:470) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:315) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:287) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:205) ~[dubbo-2.7.5.jar:2.7.5]
```
I read the code and found that dubbo would add a `RegisterStatedURL` to `ProviderModel` when register self, but can't find an exist model. The related compont is refactored, and is there some docs?

And more, it seems 2.7.5 has some compatibility question, should we create a special issue to collect them?

**Comment by haozi000005** [comment]
> Another compatibility problem, method `org.apache.dubbo.rpc.Filter.Listener.onResponse` was renamed to `onMessage`, I think create a new `onMessage` method and annotation `@Deprecated` on `onResponse` is better than renaming directly.
> 
> Besides this, I start my service failed because of NPE:
> 
> ```
> java.lang.NullPointerException: null
> 	at org.apache.dubbo.registry.integration.RegistryProtocol.register(RegistryProtocol.java:178) ~[dubbo-2.7.5.jar:2.7.5]
> 	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:209) ~[dubbo-2.7.5.jar:2.7.5]
> 	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:60) ~[dubbo-2.7.5.jar:2.7.5]
> 	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:143) ~[dubbo-2.7.5.jar:2.7.5]
> 	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:64) ~[dubbo-2.7.5.jar:2.7.5]
> 	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) ~[dubbo-2.7.5.jar:2.7.5]
> 	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:470) ~[dubbo-2.7.5.jar:2.7.5]
> 	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:315) ~[dubbo-2.7.5.jar:2.7.5]
> 	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:287) ~[dubbo-2.7.5.jar:2.7.5]
> 	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:205) ~[dubbo-2.7.5.jar:2.7.5]
> ```
> 
> I read the code and found that dubbo would add a `RegisterStatedURL` to `ProviderModel` when register self, but can't find an exist model. The related compont is refactored, and is there some docs?
> 
> And more, it seems 2.7.5 has some compatibility question, should we create a special issue to collect them?

I got this Exception too!

**Comment by haozi000005** [comment]
我实现org.apache.dubbo.rpc.cluster.loadbalance.AbstractLoadBalance来写拓展，但是现在getWeight方法吧protected 修饰去掉了。我又需要自己在实现类里面重新写一遍getWeight的实现，请问是基于什么考虑，建议还是加上protected修饰

**Comment by mail6562** [comment]
I use dubbo 2.7.5 and use dubbo-spring-boot 2.7.5 , I start my service failed ;
 nested exception is java.lang.IllegalStateException: zookeeper not connected
 on package: org.apache.dubbo.remoting.zookeeper.curator; 
`Caused by: java.lang.IllegalStateException: zookeeper not connected
	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.<init>(CuratorZookeeperClient.java:83) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperTransporter.createZookeeperClient(CuratorZookeeperTransporter.java:26) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.remoting.zookeeper.support.AbstractZookeeperTransporter.connect(AbstractZookeeperTransporter.java:68) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.remoting.zookeeper.ZookeeperTransporter$Adaptive.connect(ZookeeperTransporter$Adaptive.java) ~[dubbo-2.7.5.jar:2.7.5]
`  .
CuratorZookeeperClient start twice , first is failed. application is exit.

when CuratorZookeeperClient start first,  wait 30 seconds . application  is running.

**Comment by chickenlj** [comment]
Thanks you all for the feedbacks, I am working on these possible issues.

**Comment by RojerAlone** [comment]
> Thanks you all for the feedbacks, I am working on these possible issues.

will u fix it by release a new version 2.7.5.1 like 2.7.4.1? I saw some commits about compatibility has been merged into master.

**Comment by chickenlj** [comment]
> will u fix it by release a new version 2.7.5.1 like 2.7.4.1? I saw some commits about compatibility has been merged into master.

Yes, we are considering doing this.

**Comment by chickenlj** [comment]
https://github.com/apache/dubbo/issues/5669
