### ISSUE TITLE
Dubbo2.6.5 + log4j 1.2.15 Dubbo_JStack一直报BLOCKED

### ISSUE THREAD

**Issue by TuJianwei** [apache/dubbo#5604]
dubbo设置3000个线程，当并发量很高的时候会有多个线程被同一个线程阻塞
log4j日志配置如下
`<appender name="file" class="org.apache.log4j.DailyRollingFileAppender">
		<param name="File" value="./logs/log.log" />
		<param name="Encoding" value="utf-8" />
		<param name="DatePattern" value="'.'yyyy-MM-dd-HH" />
		<layout class="org.apache.log4j.PatternLayout">
			<param name="ConversionPattern"
				   value="%d{yyyy-MM-dd HH:mm:ss,SSS} %5p (%F:%L) - %m%n" />
		</layout>
	</appender>

	<appender name="ASYNCOUT" class="org.apache.log4j.AsyncAppender">
		<param name="BufferSize" value="8192" />
		<appender-ref ref="file" />
	</appender>`
Dubbo_JStack日志：
`"DubboServerHandler-10.200.130.59:20992-thread-2298" Id=2769 BLOCKED on org.apache.log4j.spi.RootLogger@13344c34 owned by "DubboServerHandler-10.200.130.59:20992-thread-1433" Id=1900
        at org.apache.log4j.Category.callAppenders(Category.java:204)
        -  blocked on org.apache.log4j.spi.RootLogger@13344c34
        at org.apache.log4j.Category.forcedLog(Category.java:391)
        at org.apache.log4j.Category.log(Category.java:856)
        at org.slf4j.impl.Log4jLoggerAdapter.error(Log4jLoggerAdapter.java:576)
        at com.alibaba.dubbo.common.bytecode.Wrapper5.invokeMethod(Wrapper5.java)
        at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47)
        at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:76)
        at com.alibaba.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:52)
        at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
        at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:62)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
        at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
        at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
        at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
        at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:73)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
        at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:138)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
        at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
        at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke$sentryProxy(EchoFilter.java:38)
        at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:104)
        at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:96)
        at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:173)
        ...

        Number of locked synchronizers = 1
        - java.util.concurrent.ThreadPoolExecutor$Worker@63508aab
`

**Comment by mercyblitz** [comment]
It's a legacy issue about log4j 1.x, please upgrade the logback or log4j 2.x
