### ISSUE TITLE
在局域网中使用multicast注册中心出现异常

### ISSUE THREAD

**Issue by startjava** [apache/dubbo#5647]
-----------------------------------------服务器端代码-----------------------------------
package com.class09.www.run;

import com.class09.www.service.IService;
import com.class09.www.service.Service;
import org.apache.dubbo.config.ApplicationConfig;
import org.apache.dubbo.config.RegistryConfig;
import org.apache.dubbo.config.ServiceConfig;
import org.apache.dubbo.config.bootstrap.DubboBootstrap;

import java.io.IOException;

public class Run {
    public static void main(String[] args) throws IOException {
        Service service = new Service();
        // 服务配置
        ServiceConfig<IService> serviceConfig = new ServiceConfig<IService>();
        // 设置业务接口
        serviceConfig.setInterface(IService.class);
        // 设置业务实现类
        serviceConfig.setRef(service);
        // 使用广播地址做为注册中心
        serviceConfig.setRegistry(new RegistryConfig("multicast://224.5.6.7:1234"));

        DubboBootstrap bootstrap = DubboBootstrap.getInstance();
        bootstrap
                .application(new ApplicationConfig("dubbo2-server"))
                .registry(new RegistryConfig("multicast://224.5.6.7:1234"))
                .service(serviceConfig)
                .start()
                .await();
    }
}

-----------------------------------------客户端代码---------------------------------------------------
package com.class09.www.run;

import com.class09.www.service.IService;
import org.apache.dubbo.config.ApplicationConfig;
import org.apache.dubbo.config.ReferenceConfig;
import org.apache.dubbo.config.RegistryConfig;
import org.apache.dubbo.config.bootstrap.DubboBootstrap;
import org.apache.dubbo.config.utils.ReferenceConfigCache;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

public class Run {
    public static void main(String[] args) throws IOException {
        ReferenceConfig<IService> reference = new ReferenceConfig<>();
        reference.setInterface(IService.class);
        reference.setRegistry(new RegistryConfig("multicast://224.5.6.7:1234?unicast=false"));

        ApplicationConfig applicationConfig = new ApplicationConfig("dubbo1-client");
        DubboBootstrap bootstrap = DubboBootstrap.getInstance();
        bootstrap
                .application(applicationConfig)
                .registry(new RegistryConfig("multicast://224.5.6.7:1234?unicast=false"))
                .reference(reference)
                .start();
        String message = ReferenceConfigCache.getCache().get(reference).sayHello("来自客户端！");
        System.out.println("客户端打印：" + message);
    }
}
-------------------------------异常信息----------------------------
C:\jdk1.8\bin\java.exe -Djava.net.preferIPv4Stack=true -javaagent:C:\ideaIU-2019.3.1.win\lib\idea_rt.jar=53028:C:\ideaIU-2019.3.1.win\bin -Dfile.encoding=UTF-8 -classpath C:\jdk1.8\jre\lib\charsets.jar;C:\jdk1.8\jre\lib\deploy.jar;C:\jdk1.8\jre\lib\ext\access-bridge-64.jar;C:\jdk1.8\jre\lib\ext\cldrdata.jar;C:\jdk1.8\jre\lib\ext\dnsns.jar;C:\jdk1.8\jre\lib\ext\jaccess.jar;C:\jdk1.8\jre\lib\ext\jfxrt.jar;C:\jdk1.8\jre\lib\ext\localedata.jar;C:\jdk1.8\jre\lib\ext\nashorn.jar;C:\jdk1.8\jre\lib\ext\sunec.jar;C:\jdk1.8\jre\lib\ext\sunjce_provider.jar;C:\jdk1.8\jre\lib\ext\sunmscapi.jar;C:\jdk1.8\jre\lib\ext\sunpkcs11.jar;C:\jdk1.8\jre\lib\ext\zipfs.jar;C:\jdk1.8\jre\lib\javaws.jar;C:\jdk1.8\jre\lib\jce.jar;C:\jdk1.8\jre\lib\jfr.jar;C:\jdk1.8\jre\lib\jfxswt.jar;C:\jdk1.8\jre\lib\jsse.jar;C:\jdk1.8\jre\lib\management-agent.jar;C:\jdk1.8\jre\lib\plugin.jar;C:\jdk1.8\jre\lib\resources.jar;C:\jdk1.8\jre\lib\rt.jar;C:\Users\Administrator\Desktop\Dubbo\test2\client\target\classes;C:\mvnrepository\org\apache\dubbo\dubbo\2.7.5\dubbo-2.7.5.jar;C:\mvnrepository\org\springframework\spring-context\4.3.16.RELEASE\spring-context-4.3.16.RELEASE.jar;C:\mvnrepository\org\springframework\spring-aop\4.3.16.RELEASE\spring-aop-4.3.16.RELEASE.jar;C:\mvnrepository\org\springframework\spring-beans\4.3.16.RELEASE\spring-beans-4.3.16.RELEASE.jar;C:\mvnrepository\org\springframework\spring-core\4.3.16.RELEASE\spring-core-4.3.16.RELEASE.jar;C:\mvnrepository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;C:\mvnrepository\org\springframework\spring-expression\4.3.16.RELEASE\spring-expression-4.3.16.RELEASE.jar;C:\mvnrepository\com\alibaba\spring\spring-context-support\1.0.5\spring-context-support-1.0.5.jar;C:\mvnrepository\org\javassist\javassist\3.20.0-GA\javassist-3.20.0-GA.jar;C:\mvnrepository\io\netty\netty-all\4.1.25.Final\netty-all-4.1.25.Final.jar;C:\mvnrepository\com\google\code\gson\gson\2.8.5\gson-2.8.5.jar;C:\mvnrepository\org\yaml\snakeyaml\1.20\snakeyaml-1.20.jar;C:\mvnrepository\org\apache\curator\curator-recipes\4.0.1\curator-recipes-4.0.1.jar;C:\mvnrepository\org\apache\curator\curator-framework\4.0.1\curator-framework-4.0.1.jar;C:\mvnrepository\org\apache\curator\curator-client\4.0.1\curator-client-4.0.1.jar;C:\mvnrepository\com\google\guava\guava\20.0\guava-20.0.jar;C:\mvnrepository\org\apache\zookeeper\zookeeper\3.4.13\zookeeper-3.4.13.jar;C:\mvnrepository\org\slf4j\slf4j-api\1.7.25\slf4j-api-1.7.25.jar;C:\mvnrepository\org\slf4j\slf4j-log4j12\1.7.25\slf4j-log4j12-1.7.25.jar;C:\mvnrepository\log4j\log4j\1.2.17\log4j-1.2.17.jar;C:\mvnrepository\jline\jline\0.9.94\jline-0.9.94.jar;C:\mvnrepository\org\apache\yetus\audience-annotations\0.5.0\audience-annotations-0.5.0.jar com.class09.www.run.Run
main  INFO logger.LoggerFactory: using logger: org.apache.dubbo.common.logger.log4j.Log4jLoggerAdapter
main  WARN extension.SpringExtensionFactory:  [DUBBO] No spring extension (bean) named:module, try to find an extension (bean) of type org.apache.dubbo.config.ModuleConfig, dubbo version: 2.7.5, current host: 192.168.59.18
main  WARN extension.SpringExtensionFactory:  [DUBBO] No spring extension (bean) named:monitor, try to find an extension (bean) of type org.apache.dubbo.config.MonitorConfig, dubbo version: 2.7.5, current host: 192.168.59.18
main  WARN extension.SpringExtensionFactory:  [DUBBO] No spring extension (bean) named:application, try to find an extension (bean) of type org.apache.dubbo.config.ApplicationConfig, dubbo version: 2.7.5, current host: 192.168.59.18
main  WARN extension.SpringExtensionFactory:  [DUBBO] No spring extension (bean) named:metrics, try to find an extension (bean) of type org.apache.dubbo.config.MetricsConfig, dubbo version: 2.7.5, current host: 192.168.59.18
main  WARN extension.SpringExtensionFactory:  [DUBBO] No spring extension (bean) named:ssl, try to find an extension (bean) of type org.apache.dubbo.config.SslConfig, dubbo version: 2.7.5, current host: 192.168.59.18
main  WARN config.ConfigurationUtils:  [DUBBO] You specified the config center, but there's not even one single config item in it., dubbo version: 2.7.5, current host: 192.168.59.18
main  WARN config.ConfigurationUtils:  [DUBBO] You specified the config center, but there's not even one single config item in it., dubbo version: 2.7.5, current host: 192.168.59.18
main  INFO utils.ConfigValidationUtils:  [DUBBO] There's no valid monitor config found, if you want to open monitor statistics for Dubbo, please make sure your monitor is configured properly., dubbo version: 2.7.5, current host: 192.168.59.18
main  INFO bootstrap.DubboBootstrap:  [DUBBO] DubboBootstrap has been initialized!, dubbo version: 2.7.5, current host: 192.168.59.18
main  INFO bootstrap.DubboBootstrap:  [DUBBO] DubboBootstrap is starting..., dubbo version: 2.7.5, current host: 192.168.59.18
main  INFO server.Server:  [DUBBO] qos-server bind localhost:33333, dubbo version: 2.7.5, current host: 192.168.59.18
main  INFO multicast.MulticastRegistry:  [DUBBO] Load registry cache file C:\Users\Administrator\.dubbo\dubbo-registry-dubbo1-client-224.5.6.7-1234.cache, data: {com.class09.www.service.IService=dubbo://192.168.59.18:20880/com.class09.www.service.IService?anyhost=true&application=dubbo1-server&default=true&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.class09.www.service.IService&methods=sayHello&pid=10556&release=2.7.5&side=provider&timestamp=1578984874892}, dubbo version: 2.7.5, current host: 192.168.59.18
main  INFO multicast.MulticastRegistry:  [DUBBO] Register: consumer://192.168.59.18/com.class09.www.service.IService?application=dubbo1-client&category=consumers&check=false&dubbo=2.0.2&interface=com.class09.www.service.IService&methods=sayHello&pid=7328&qos.port=33333&release=2.7.5&side=consumer&sticky=false&timestamp=1578993594190, dubbo version: 2.7.5, current host: 192.168.59.18
main  INFO multicast.MulticastRegistry:  [DUBBO] Send multicast message: register consumer://192.168.59.18/com.class09.www.service.IService?application=dubbo1-client&category=consumers&check=false&dubbo=2.0.2&interface=com.class09.www.service.IService&methods=sayHello&pid=7328&qos.port=33333&release=2.7.5&side=consumer&sticky=false&timestamp=1578993594190 to /224.5.6.7:1234, dubbo version: 2.7.5, current host: 192.168.59.18
DubboMulticastRegistryReceiver  INFO multicast.MulticastRegistry:  [DUBBO] Receive multicast message: register consumer://192.168.59.18/com.class09.www.service.IService?application=dubbo1-client&category=consumers&check=false&dubbo=2.0.2&interface=com.class09.www.service.IService&methods=sayHello&pid=7328&qos.port=33333&release=2.7.5&side=consumer&sticky=false&timestamp=1578993594190 from /127.0.0.1:1234, dubbo version: 2.7.5, current host: 192.168.59.18
main  INFO multicast.MulticastRegistry:  [DUBBO] Subscribe: consumer://192.168.59.18/com.class09.www.service.IService?application=dubbo1-client&category=providers,configurators,routers&dubbo=2.0.2&interface=com.class09.www.service.IService&methods=sayHello&pid=7328&qos.port=33333&release=2.7.5&side=consumer&sticky=false&timestamp=1578993594190, dubbo version: 2.7.5, current host: 192.168.59.18
main  INFO multicast.MulticastRegistry:  [DUBBO] Send multicast message: subscribe consumer://192.168.59.18/com.class09.www.service.IService?application=dubbo1-client&category=providers,configurators,routers&dubbo=2.0.2&interface=com.class09.www.service.IService&methods=sayHello&pid=7328&qos.port=33333&release=2.7.5&side=consumer&sticky=false&timestamp=1578993594190 to /224.5.6.7:1234, dubbo version: 2.7.5, current host: 192.168.59.18
DubboMulticastRegistryReceiver  INFO multicast.MulticastRegistry:  [DUBBO] Receive multicast message: subscribe consumer://192.168.59.18/com.class09.www.service.IService?application=dubbo1-client&category=providers,configurators,routers&dubbo=2.0.2&interface=com.class09.www.service.IService&methods=sayHello&pid=7328&qos.port=33333&release=2.7.5&side=consumer&sticky=false&timestamp=1578993594190 from /127.0.0.1:1234, dubbo version: 2.7.5, current host: 192.168.59.18
main  INFO multicast.MulticastRegistry:  [DUBBO] Notify urls for subscribe url consumer://192.168.59.18/com.class09.www.service.IService?application=dubbo1-client&category=providers,configurators,routers&dubbo=2.0.2&interface=com.class09.www.service.IService&methods=sayHello&pid=7328&qos.port=33333&release=2.7.5&side=consumer&sticky=false&timestamp=1578993594190, urls: [dubbo://192.168.59.18:20880/com.class09.www.service.IService?anyhost=true&application=dubbo1-server&default=true&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.class09.www.service.IService&methods=sayHello&pid=10556&release=2.7.5&side=provider&timestamp=1578984874892], dubbo version: 2.7.5, current host: 192.168.59.18
main  WARN transport.AbstractClient:  [DUBBO] Failed to start NettyClient DESKTOP-92NCRPC/192.168.59.18 connect to the server /192.168.59.18:20880 (check == false, ignore and retry later!), cause: client(url: dubbo://192.168.59.18:20880/com.class09.www.service.IService?anyhost=true&application=dubbo1-client&check=false&codec=dubbo&default=true&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&heartbeat=60000&interface=com.class09.www.service.IService&methods=sayHello&pid=7328&qos.port=33333&register.ip=192.168.59.18&release=2.7.5&remote.application=dubbo1-server&side=consumer&sticky=false&timestamp=1578984874892) failed to connect to server /192.168.59.18:20880, error message is:Connection refused: no further information: /192.168.59.18:20880, dubbo version: 2.7.5, current host: 192.168.59.18
org.apache.dubbo.remoting.RemotingException: client(url: dubbo://192.168.59.18:20880/com.class09.www.service.IService?anyhost=true&application=dubbo1-client&check=false&codec=dubbo&default=true&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&heartbeat=60000&interface=com.class09.www.service.IService&methods=sayHello&pid=7328&qos.port=33333&register.ip=192.168.59.18&release=2.7.5&remote.application=dubbo1-server&side=consumer&sticky=false&timestamp=1578984874892) failed to connect to server /192.168.59.18:20880, error message is:Connection refused: no further information: /192.168.59.18:20880
	at org.apache.dubbo.remoting.transport.netty4.NettyClient.doConnect(NettyClient.java:168)
	at org.apache.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:191)
	at org.apache.dubbo.remoting.transport.AbstractClient.<init>(AbstractClient.java:71)
	at org.apache.dubbo.remoting.transport.netty4.NettyClient.<init>(NettyClient.java:81)
	at org.apache.dubbo.remoting.transport.netty4.NettyTransporter.connect(NettyTransporter.java:40)
	at org.apache.dubbo.remoting.Transporter$Adaptive.connect(Transporter$Adaptive.java)
	at org.apache.dubbo.remoting.Transporters.connect(Transporters.java:75)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchanger.connect(HeaderExchanger.java:39)
	at org.apache.dubbo.remoting.exchange.Exchangers.connect(Exchangers.java:109)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.initClient(DubboProtocol.java:594)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.buildReferenceCountExchangeClient(DubboProtocol.java:562)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.buildReferenceCountExchangeClientList(DubboProtocol.java:549)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getSharedClient(DubboProtocol.java:474)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getClients(DubboProtocol.java:429)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.protocolBindingRefer(DubboProtocol.java:406)
	at org.apache.dubbo.rpc.protocol.AbstractProtocol.refer(AbstractProtocol.java:104)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:72)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:75)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:153)
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at org.apache.dubbo.registry.integration.RegistryDirectory.toInvokers(RegistryDirectory.java:435)
	at org.apache.dubbo.registry.integration.RegistryDirectory.refreshInvoker(RegistryDirectory.java:292)
	at org.apache.dubbo.registry.integration.RegistryDirectory.refreshOverrideAndInvoker(RegistryDirectory.java:251)
	at org.apache.dubbo.registry.integration.RegistryDirectory.notify(RegistryDirectory.java:245)
	at org.apache.dubbo.registry.support.AbstractRegistry.notify(AbstractRegistry.java:423)
	at org.apache.dubbo.registry.support.FailbackRegistry.doNotify(FailbackRegistry.java:373)
	at org.apache.dubbo.registry.support.FailbackRegistry.notify(FailbackRegistry.java:364)
	at org.apache.dubbo.registry.multicast.MulticastRegistry.subscribed(MulticastRegistry.java:362)
	at org.apache.dubbo.registry.multicast.MulticastRegistry.subscribe(MulticastRegistry.java:390)
	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:105)
	at org.apache.dubbo.registry.integration.RegistryDirectory.subscribe(RegistryDirectory.java:174)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:415)
	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:396)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:70)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:73)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:151)
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:324)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:266)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:151)
	at org.apache.dubbo.config.utils.ReferenceConfigCache.lambda$get$2(ReferenceConfigCache.java:119)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.apache.dubbo.config.utils.ReferenceConfigCache.get(ReferenceConfigCache.java:118)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.lambda$referServices$17(DubboBootstrap.java:912)
	at java.util.HashMap$Values.forEach(HashMap.java:981)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.referServices(DubboBootstrap.java:899)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:713)
	at com.class09.www.run.Run.main(Run.java:26)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.59.18:20880
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:325)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused: no further information
	... 11 more
Exception in thread "main" java.lang.IllegalStateException: Failed to check the status of the service com.class09.www.service.IService. No provider available for the service com.class09.www.service.IService from the url multicast://224.5.6.7:1234/org.apache.dubbo.registry.RegistryService?anyhost=true&application=dubbo1-client&check=false&default=true&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.class09.www.service.IService&methods=sayHello&pid=7328&qos.port=33333&register.ip=192.168.59.18&release=2.7.5&remote.application=dubbo1-server&side=consumer&sticky=false&timestamp=1578993594190 to the consumer 192.168.59.18 use dubbo version 2.7.5
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:355)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:266)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:151)
	at org.apache.dubbo.config.utils.ReferenceConfigCache.lambda$get$2(ReferenceConfigCache.java:119)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.apache.dubbo.config.utils.ReferenceConfigCache.get(ReferenceConfigCache.java:118)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.lambda$referServices$17(DubboBootstrap.java:912)
	at java.util.HashMap$Values.forEach(HashMap.java:981)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.referServices(DubboBootstrap.java:899)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:713)
	at com.class09.www.run.Run.main(Run.java:26)
DubboShutdownHook  INFO config.DubboShutdownHook:  [DUBBO] Run shutdown hook now., dubbo version: 2.7.5, current host: 192.168.59.18
DubboShutdownHook  INFO support.AbstractRegistryFactory:  [DUBBO] Close all registries [multicast://224.5.6.7:1234/org.apache.dubbo.registry.RegistryService?application=dubbo1-client&dubbo=2.0.2&interface=org.apache.dubbo.registry.RegistryService&pid=7328&qos.port=33333&release=2.7.5&timestamp=1578993594211&unicast=false], dubbo version: 2.7.5, current host: 192.168.59.18
DubboShutdownHook  INFO multicast.MulticastRegistry:  [DUBBO] Destroy registry:multicast://224.5.6.7:1234/org.apache.dubbo.registry.RegistryService?application=dubbo1-client&dubbo=2.0.2&interface=org.apache.dubbo.registry.RegistryService&pid=7328&qos.port=33333&release=2.7.5&timestamp=1578993594211&unicast=false, dubbo version: 2.7.5, current host: 192.168.59.18
DubboShutdownHook  INFO multicast.MulticastRegistry:  [DUBBO] Unregister: consumer://192.168.59.18/com.class09.www.service.IService?application=dubbo1-client&category=consumers&check=false&dubbo=2.0.2&interface=com.class09.www.service.IService&methods=sayHello&pid=7328&qos.port=33333&release=2.7.5&side=consumer&sticky=false&timestamp=1578993594190, dubbo version: 2.7.5, current host: 192.168.59.18
DubboShutdownHook  INFO multicast.MulticastRegistry:  [DUBBO] Send multicast message: unregister consumer://192.168.59.18/com.class09.www.service.IService?application=dubbo1-client&category=consumers&check=false&dubbo=2.0.2&interface=com.class09.www.service.IService&methods=sayHello&pid=7328&qos.port=33333&release=2.7.5&side=consumer&sticky=false&timestamp=1578993594190 to /224.5.6.7:1234, dubbo version: 2.7.5, current host: 192.168.59.18
DubboMulticastRegistryReceiver  INFO multicast.MulticastRegistry:  [DUBBO] Receive multicast message: unregister consumer://192.168.59.18/com.class09.www.service.IService?application=dubbo1-client&category=consumers&check=false&dubbo=2.0.2&interface=com.class09.www.service.IService&methods=sayHello&pid=7328&qos.port=33333&release=2.7.5&side=consumer&sticky=false&timestamp=1578993594190 from /127.0.0.1:1234, dubbo version: 2.7.5, current host: 192.168.59.18
DubboShutdownHook  INFO multicast.MulticastRegistry:  [DUBBO] Destroy unregister url consumer://192.168.59.18/com.class09.www.service.IService?application=dubbo1-client&category=consumers&check=false&dubbo=2.0.2&interface=com.class09.www.service.IService&methods=sayHello&pid=7328&qos.port=33333&release=2.7.5&side=consumer&sticky=false&timestamp=1578993594190, dubbo version: 2.7.5, current host: 192.168.59.18
DubboShutdownHook  INFO multicast.MulticastRegistry:  [DUBBO] Unsubscribe: consumer://192.168.59.18/com.class09.www.service.IService?application=dubbo1-client&category=providers,configurators,routers&dubbo=2.0.2&interface=com.class09.www.service.IService&methods=sayHello&pid=7328&qos.port=33333&release=2.7.5&side=consumer&sticky=false&timestamp=1578993594190, dubbo version: 2.7.5, current host: 192.168.59.18
DubboShutdownHook  INFO multicast.MulticastRegistry:  [DUBBO] Unregister: consumer://192.168.59.18/com.class09.www.service.IService?application=dubbo1-client&category=providers,configurators,routers&dubbo=2.0.2&interface=com.class09.www.service.IService&methods=sayHello&pid=7328&qos.port=33333&release=2.7.5&side=consumer&sticky=false&timestamp=1578993594190, dubbo version: 2.7.5, current host: 192.168.59.18
DubboShutdownHook  INFO multicast.MulticastRegistry:  [DUBBO] Send multicast message: unregister consumer://192.168.59.18/com.class09.www.service.IService?application=dubbo1-client&category=providers,configurators,routers&dubbo=2.0.2&interface=com.class09.www.service.IService&methods=sayHello&pid=7328&qos.port=33333&release=2.7.5&side=consumer&sticky=false&timestamp=1578993594190 to /224.5.6.7:1234, dubbo version: 2.7.5, current host: 192.168.59.18
DubboMulticastRegistryReceiver  INFO multicast.MulticastRegistry:  [DUBBO] Receive multicast message: unregister consumer://192.168.59.18/com.class09.www.service.IService?application=dubbo1-client&category=providers,configurators,routers&dubbo=2.0.2&interface=com.class09.www.service.IService&methods=sayHello&pid=7328&qos.port=33333&release=2.7.5&side=consumer&sticky=false&timestamp=1578993594190 from /127.0.0.1:1234, dubbo version: 2.7.5, current host: 192.168.59.18
DubboShutdownHook  INFO multicast.MulticastRegistry:  [DUBBO] Send multicast message: unsubscribe consumer://192.168.59.18/com.class09.www.service.IService?application=dubbo1-client&category=providers,configurators,routers&dubbo=2.0.2&interface=com.class09.www.service.IService&methods=sayHello&pid=7328&qos.port=33333&release=2.7.5&side=consumer&sticky=false&timestamp=1578993594190 to /224.5.6.7:1234, dubbo version: 2.7.5, current host: 192.168.59.18
DubboShutdownHook  INFO multicast.MulticastRegistry:  [DUBBO] Destroy unsubscribe url consumer://192.168.59.18/com.class09.www.service.IService?application=dubbo1-client&category=providers,configurators,routers&dubbo=2.0.2&interface=com.class09.www.service.IService&methods=sayHello&pid=7328&qos.port=33333&release=2.7.5&side=consumer&sticky=false&timestamp=1578993594190, dubbo version: 2.7.5, current host: 192.168.59.18
DubboMulticastRegistryReceiver  INFO multicast.MulticastRegistry:  [DUBBO] Receive multicast message: unsubscribe consumer://192.168.59.18/com.class09.www.service.IService?application=dubbo1-client&category=providers,configurators,routers&dubbo=2.0.2&interface=com.class09.www.service.IService&methods=sayHello&pid=7328&qos.port=33333&release=2.7.5&side=consumer&sticky=false&timestamp=1578993594190 from /127.0.0.1:1234, dubbo version: 2.7.5, current host: 192.168.59.18
DubboShutdownHook  INFO dubbo.DubboProtocol:  [DUBBO] Close dubbo connect: 192.168.59.18:0-->/192.168.59.18:20880, dubbo version: 2.7.5, current host: 192.168.59.18
DubboShutdownHook  INFO dubbo.DubboProtocol:  [DUBBO] Destroy reference: dubbo://192.168.59.18:20880/com.class09.www.service.IService?anyhost=true&application=dubbo1-client&check=false&default=true&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.class09.www.service.IService&methods=sayHello&pid=7328&qos.port=33333&register.ip=192.168.59.18&release=2.7.5&remote.application=dubbo1-server&side=consumer&sticky=false&timestamp=1578984874892, dubbo version: 2.7.5, current host: 192.168.59.18
DubboShutdownHook  INFO server.Server:  [DUBBO] qos-server stopped., dubbo version: 2.7.5, current host: 192.168.59.18
DubboShutdownHook  INFO bootstrap.DubboBootstrap:  [DUBBO] DubboBootstrap is about to shutdown..., dubbo version: 2.7.5, current host: 192.168.59.18
DubboShutdownHook  INFO listener.LoggingEventListener:  [DUBBO] Dubbo Service has been destroyed., dubbo version: 2.7.5, current host: 192.168.59.18

Process finished with exit code 1

----------------------------------------------
我的运行环境是跨物理计算机，两台物理电脑。

在局域网中运行客户端时出现上面的异常，
奇怪的是第一个异常：
org.apache.dubbo.remoting.RemotingException: client(url: dubbo://192.168.59.18:20880/com.class09.www.service.IService?anyhost=true&application=dubbo1-client&check=false&codec=dubbo&default=true&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&heartbeat=60000&interface=com.class09.www.service.IService&methods=sayHello&pid=7328&qos.port=33333&register.ip=192.168.59.18&release=2.7.5&remote.application=dubbo1-server&side=consumer&sticky=false&timestamp=1578984874892) failed to connect to server /192.168.59.18:20880, error message is:Connection refused: no further information: /192.168.59.18:20880

192.168.59.18这个IP是我的IP，服务端根本不在本地，为什么要连接本地呢？连接本地当然报错了，搞了一下午，请教一下啊！

**Comment by startjava** [comment]
@chickenlj
