### ISSUE TITLE
Dubbo2.7.5 报Could not initialize class org.springframework.beans.factory.BeanCreationException

### ISSUE THREAD

**Issue by cookieka** [apache/dubbo#5658]
我的项目配置-Xss时候会引起Could not initialize class org.springframework.beans.factory.BeanCreationException 错误。

1. 当java_mem_opts= -server -Xmx2g -XX:MetaspaceSize=128m -Xss256k  
报
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.springframework.beans.factory.BeanCreationException

2. java_mem_opts= -server -Xmx2g -XX:MetaspaceSize=128m -Xss512k
就不会报，可以正常启动

完成错误日志如下：
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.springframework.beans.factory.BeanCreationException
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:510)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
        at org.apache.dubbo.container.spring.SpringContainer.start(SpringContainer.java:50)
        at org.apache.dubbo.container.Main.main(Main.java:90)

**Comment by mercyblitz** [comment]
It's not an issue, because of a lot API in Spring Framework uses Java reflection or recursive invocations, their stack require more space.
