### ISSUE TITLE
<dubbo:config-center timeout="10000" /> Does not work

### ISSUE THREAD

**Issue by itlihuaxin** [apache/dubbo#5740]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.5
* Operating System version: window
* Java version: 1.8

### Expected Result
registry url timeout=10000

### Actual Result
registry url timeout=3000
Application run failed
java.lang.IllegalStateException: zookeeper not connected
    at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.<init>(CuratorZookeeperClient.java:83)
    at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperTransporter.createZookeeperClient(CuratorZookeeperTransporter.java:26)
    at org.apache.dubbo.remoting.zookeeper.support.AbstractZookeeperTransporter.connect(AbstractZookeeperTransporter.java:68)

**Comment by mercyblitz** [comment]
Duplicated https://github.com/apache/dubbo-spring-boot-project/issues/657

**Comment by chickenlj** [comment]
Fixed by #5518
