### ISSUE TITLE
dubbo update 2.5.3 to 2.7.5 some error

### ISSUE THREAD

**Issue by wangkang007** [apache/dubbo#5755]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.5
* Operating System version: macos 10.15.13
* Java version: 1.8

### Steps to reproduce this issue

1. Spring boot 1.5.2 ,when update dubbo 2.5.3 to 2.7.5 ，I have some problems

2. run spring boot  , and dubbo config is `<dubbo:reference interface="com.xxx.xxx.service.ITaskService" version="${dubbo.api.version}" id="taskService"
                     cluster="failfast"></dubbo:reference>`
3. application.properties  config is dubbo.api.version=1.2.0_dev

### Actual Result

run error

the exception trace:

```
Caused by: java.lang.IllegalStateException: Invalid version="${dubbo.api.version}" contains illegal character, only digit, letter, '-', '_' or '.' is legal.
	at org.apache.dubbo.config.utils.ConfigValidationUtils.checkProperty(ConfigValidationUtils.java:593)
	at org.apache.dubbo.config.utils.ConfigValidationUtils.checkKey(ConfigValidationUtils.java:559)
	at org.apache.dubbo.config.utils.ConfigValidationUtils.validateReferenceConfig(ConfigValidationUtils.java:340)
	at org.apache.dubbo.config.ReferenceConfig.checkAndUpdateSubConfigs(ReferenceConfig.java:401)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:186)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:151)
	at org.apache.dubbo.config.spring.ReferenceBean.getObject(ReferenceBean.java:68)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
	... 64 common frames omitted

```

**Comment by mooseen** [comment]
I also encountered this problem too that placeholder is not going to working in xml for reference bean. I found the reason of this issue is reference bean  has been early initialized when spring can't  infer the target type of factory bean and reference bean is type of factory bean. I has solved this issue by copy a `DubboBeanDefinitionParser` class  and override the default,and follow codes in parse method:
```java
     else if(ReferenceBean.class.equals(beanClass)){
            String interfaceClassName = element.getAttribute("interface");
            if(StringUtils.isNotEmpty(interfaceClassName)){
                Class<?> interfaceClass = ReflectUtils.forName(interfaceClassName);
                beanDefinition.setTargetType(interfaceClass);
            }
        }
```
I have add a pull request for solve this issue, fixed #5710

**Comment by wangkang007** [comment]
thanks，Hope to repair it quickly。when dubbo version <2.7.5 has Serializable bug,so we must update to 2.7.5,but we can't run dubbo

**Comment by mercyblitz** [comment]
Please update the Dubbo Spring Boot 2.7.5
