### ISSUE TITLE
destroyAll method of DubboShutdownHook will be invoke twice when using spring framework

### ISSUE THREAD

**Issue by tswstarplanet** [apache/dubbo#5813]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. run main method of Application of dubbo-demo-xml-consumer.

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

The application will exit without thrown exception

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```log
java.lang.IllegalStateException: There's no ApplicationConfig specified.
	at org.apache.dubbo.config.context.ConfigManager.lambda$getApplicationOrElseThrow$0(ConfigManager.java:88)
	at java.base/java.util.Optional.orElseThrow(Optional.java:401)
	at org.apache.dubbo.config.context.ConfigManager.getApplicationOrElseThrow(ConfigManager.java:88)
	at org.apache.dubbo.rpc.model.ApplicationModel.getApplicationConfig(ApplicationModel.java:100)
	at org.apache.dubbo.rpc.model.ApplicationModel.getName(ApplicationModel.java:104)
	at org.apache.dubbo.rpc.model.ApplicationModel.getApplication(ApplicationModel.java:112)
	at org.apache.dubbo.registry.integration.RegistryProtocol.destroy(RegistryProtocol.java:500)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.destroy(ProtocolFilterWrapper.java:166)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.destroy(ProtocolListenerWrapper.java:80)
	at org.apache.dubbo.config.DubboShutdownHook.destroyProtocols(DubboShutdownHook.java:140)
	at org.apache.dubbo.config.DubboShutdownHook.destroyAll(DubboShutdownHook.java:124)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.destroy(DubboBootstrap.java:1037)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.stop(DubboBootstrap.java:817)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onContextClosedEvent(DubboBootstrapApplicationListener.java:63)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onApplicationContextEvent(DubboBootstrapApplicationListener.java:54)
	at org.apache.dubbo.config.spring.context.OneTimeExecutionApplicationContextEventListener.onApplicationEvent(OneTimeExecutionApplicationContextEventListener.java:40)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:991)
	at org.springframework.context.support.AbstractApplicationContext$2.run(AbstractApplicationContext.java:929)
```
It's because the destroy method of DubboBootstrap is invoked twice when the application is closing.
(1.When the DubboBootstrapApplicationListener accept the ContextClosedEvent, running once.)
(2.The ShutdownHookCallback register when new the DubboBootstrap, running another time.)

**Comment by LiosWong** [comment]
报错问题还没解决:
```
[03/03/20 11:50:06:453 CST] Thread-0  WARN config.DubboShutdownHook:  [DUBBO] There's no ApplicationConfig specified., dubbo version: , current host: 192.168.124.10
java.lang.IllegalStateException: There's no ApplicationConfig specified.
	at org.apache.dubbo.config.context.ConfigManager.lambda$getApplicationOrElseThrow$0(ConfigManager.java:88)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.apache.dubbo.config.context.ConfigManager.getApplicationOrElseThrow(ConfigManager.java:88)
	at org.apache.dubbo.rpc.model.ApplicationModel.getApplicationConfig(ApplicationModel.java:100)
	at org.apache.dubbo.rpc.model.ApplicationModel.getName(ApplicationModel.java:104)
	at org.apache.dubbo.rpc.model.ApplicationModel.getApplication(ApplicationModel.java:112)
	at org.apache.dubbo.registry.integration.RegistryProtocol.destroy(RegistryProtocol.java:500)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.destroy(ProtocolFilterWrapper.java:166)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.destroy(ProtocolListenerWrapper.java:80)
	at org.apache.dubbo.config.DubboShutdownHook.destroyProtocols(DubboShutdownHook.java:138)
	at org.apache.dubbo.config.DubboShutdownHook.destroyAll(DubboShutdownHook.java:121)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.destroy(DubboBootstrap.java:1037)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.stop(DubboBootstrap.java:817)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onContextClosedEvent(DubboBootstrapApplicationListener.java:63)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onApplicationContextEvent(DubboBootstrapApplicationListener.java:54)
	at org.apache.dubbo.config.spring.context.OneTimeExecutionApplicationContextEventListener.onApplicationEvent(OneTimeExecutionApplicationContextEventListener.java:40)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:991)
	at org.springframework.context.support.AbstractApplicationContext$2.run(AbstractApplicationContext.java:929)
[03/03/20 11:50:06:453 CST] DubboShutdownHook  INFO listener.LoggingEventListener:  [DUBBO] Dubbo Service has been destroyed., dubbo version: , current host: 192.168.124.10
```
pr中确实能保证只被执行一次，但是销毁过程中，两个线程操作顺序不能保证，其中一个会把``org.apache.dubbo.config.context.ConfigManager#configsCache``数据删除，另一个线程在销毁``org.apache.dubbo.registry.integration.RegistryProtocol#destroy``会报以上的错

**Comment by LiosWong** [comment]
@chickenlj

**Comment by tswstarplanet** [comment]
为什么会有两个线程能执行呢？不是有锁控制了吗？

**Comment by tswstarplanet** [comment]
@chickenlj I think pr 5814 is right. And I test it, it works. It's because it can ensure the 
```java
        // for compatibility purpose
        DubboShutdownHook.destroyAll();
```

can be strictly be invoked before these
```java
            unregisterServiceInstance();
            unexportMetadataService();
            unexportServices();
            unreferServices();

            destroyRegistries();
            destroyProtocols();
            destroyServiceDiscoveries();

            clear();
            shutdown();
            release();
```

**Comment by chickenlj** [comment]
@tswstarplanet Yes, I agree it can work when using spring. But it may not work properly when using raw Dubbo API, for example, using ServiceConfig or ReferenceConfig directly.

**Comment by chickenlj** [comment]
@LiosWong Do you think a lock will solve the problem.

**Comment by chickenlj** [comment]
https://github.com/apache/dubbo/pull/5856
Please help to take a look at this solution

**Comment by kexianjun** [comment]
org.apache.dubbo.config.bootstrap.DubboBootstrap#destroy will make org.apache.dubbo.config.DubboShutdownHook#destroyProtocols called twice

**Comment by shihzenq** [comment]
So how was it finally resolved

**Comment by ithuangyonghua** [comment]
怎么解决这个问题呢
