### ISSUE TITLE
consumer端自定义异常没有正确反序列化

### ISSUE THREAD

**Issue by mbc3320** [apache/dubbo#5821]
- [ ☑️] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ☑️] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3~2.7.5
* Operating System version: MacOS
* Java version: 1.8

### Steps to reproduce this issue
1. 工程分4个子模块 api、common、consumer、provider
2. 自定义异常、状态码定义在common模块
3. 定义了两类自定义异常，一个BaseException直接继承RuntimeException；一个BaseRpcException继承RpcException。
4. 具体查看以下提供的示例工程

Pls. provide [GitHub address] to reproduce this issue.

```
https://github.com/mbc3320/dubbo-demo-custom-exception.git
```

### Expected Result

consumer端能正常序列化自定义异常并正确抛出

What do you expected from the above steps？

### Actual Result
 provider端抛出DemoException、DemoRpcException自定义异常，consumer端俘获并处理异常，测试了4种方式，都存在不同程度的问题
   （1）继承BaseException的异常，方法不签名抛出异常类型，consumer端会直接序列化为RuntimeException，consumer只会调用一次Provider
   （2）继承BaseException的异常，方法签名抛出BaseException，会序列化为RuntimeException，consumer只会调用一次Provider
   （3）继承BaseException的异常，方法签名抛出DemoException，报空指针且序列化失败，consumer会调用三次Provider
   （4）继承BaseRpcException的异常，方法不签名抛出异常类型，报空指针且序列化失败，consumer会调用三次Provider
   （5）如果dubbo.provider.filter设置了-exception，则所有以上情况，结果都会跟（4）一样，报空指针且序列化失败，consumer会调用三次Provider
![image](https://user-images.githubusercontent.com/5523726/75736696-dcab7f80-5d38-11ea-8449-3c5bec4143b9.png)

What actually happens?

If there is an exception, please attach the exception trace:

```
Caused by: org.apache.dubbo.remoting.RemotingException: com.alibaba.com.caucho.hessian.io.HessianProtocolException: 'cn.c3p0.cloud.demo1.exception.DemoRpcException' could not be instantiated
com.alibaba.com.caucho.hessian.io.HessianProtocolException: 'cn.c3p0.cloud.demo1.exception.DemoRpcException' could not be instantiated
	at com.alibaba.com.caucho.hessian.io.JavaDeserializer.instantiate(JavaDeserializer.java:316)
	at com.alibaba.com.caucho.hessian.io.JavaDeserializer.readObject(JavaDeserializer.java:201)
	at com.alibaba.com.caucho.hessian.io.SerializerFactory.readObject(SerializerFactory.java:536)
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObjectInstance(Hessian2Input.java:2820)
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2743)
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2278)
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2717)
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2278)
	at org.apache.dubbo.common.serialize.hessian2.Hessian2ObjectInput.readObject(Hessian2ObjectInput.java:85)
	at org.apache.dubbo.common.serialize.ObjectInput.readThrowable(ObjectInput.java:75)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.handleException(DecodeableRpcResult.java:151)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:97)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:113)
	at org.apache.dubbo.remoting.transport.DecodeHandler.decode(DecodeHandler.java:57)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:48)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:77)
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:175)
	at org.apache.dubbo.rpc.protocol.AsyncToSyncInvoker.invoke(AsyncToSyncInvoker.java:61)
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:78)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:89)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:49)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:55)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:82)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:255)
	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:78)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:60)
	at org.apache.dubbo.common.bytecode.proxy0.testRpcException(proxy0.java)
	at cn.c3p0.cloud.demo1.endpoint.DemoController.test(DemoController.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.alibaba.com.caucho.hessian.io.JavaDeserializer.instantiate(JavaDeserializer.java:312)
	... 84 more
Caused by: java.lang.NullPointerException
	at cn.c3p0.cloud.demo1.exception.BaseRpcException.<init>(BaseRpcException.java:11)
	at cn.c3p0.cloud.demo1.exception.DemoRpcException.<init>(DemoRpcException.java:8)
	... 89 more

	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.doReceived(DefaultFuture.java:212) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:175) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:163) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleResponse(HeaderExchangeHandler.java:60) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:181) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:77) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:175) ~[dubbo-2.7.5.jar:2.7.5]
	... 67 common frames omitted

```

**Comment by xylsh** [comment]
dubbo在ExceptionFilter里面有判断provider对异常是直接抛出还是用RuntimeException包装一次，楼主可以看看呢。

**Comment by mbc3320** [comment]
第五种情况已经排除ExceptionFilter，结果一样空指针异常。
调试发现，如果继承RpcException，在provider端，到AbstractInvoker的invoke得出来的结果AsyncRpcResult的responseFuture的值，能取到具体的异常信息具体的异常实例；
单独调试consumer端，发现反序列化后，由于反序列化失败，直接按超时异常处理，接着就重复调用多2次（总共三次调用），这个有点奇怪。

**Comment by mbc3320** [comment]
> dubbo在ExceptionFilter里面有判断provider对异常是直接抛出还是用RuntimeException包装一次，楼主可以看看呢。

第五种情况已经排除ExceptionFilter，结果一样空指针异常。
调试发现，如果继承RpcException，在provider端，到AbstractInvoker的invoke得出来的结果AsyncRpcResult的responseFuture的值，能取到具体的异常信息具体的异常实例；
单独调试consumer端，发现反序列化后，由于反序列化失败，直接按超时异常处理，接着就重复调用多2次（总共三次调用），这个有点奇怪。

**Comment by takeseem** [comment]
@mbc3320 正常rpc中入参和返回对象的反序列化的问题我们很容易注意到，但异常是java语言隐含的，异常的反序列化问题我们经常会遗忘：

- RuntimeException：有很多子类，provider中存在的，consumer中不一定存在，如provider有spring包装的jdbc异常，而consumer中不一定包含spring-jdbc包
- 某些异常无法通过反射反序列化，需编码才能实例化，跨rpc时必然会出问题

我的建议是：自己参考ExceptionFilter，实现异常过滤器，在框架中定义一个`ApiException`，全公司的产品都继承框架：

- 注意case和expressed也需要转换为ApiException，jvm语言自身异常不会转换为ApiException
- 转换时保持堆栈
- 要获取原始异常类使用ex字段

示例：
```
ApiException {
  ex: "RPC传递时，原始异常类"
  code: "异常码",
  httpCode: "int: 如果是http直接返回时的状态码",
  msg: "消息",
  args: [……], // 需要传递的数据
  i18n: '需要国际化展示时的code',
  i18nArgs: [], // 国际化格式参数
}
```

**Comment by mbc3320** [comment]
> @mbc3320 正常rpc中入参和返回对象的反序列化的问题我们很容易注意到，但异常是java语言隐含的，异常的反序列化问题我们经常会遗忘：
> 
> * RuntimeException：有很多子类，provider中存在的，consumer中不一定存在，如provider有spring包装的jdbc异常，而consumer中不一定包含spring-jdbc包
> * 某些异常无法通过反射反序列化，需编码才能实例化，跨rpc时必然会出问题
> 
> 我的建议是：自己参考ExceptionFilter，实现异常过滤器，在框架中定义一个`ApiException`，全公司的产品都继承框架：
> 
> * 注意case和expressed也需要转换为ApiException，jvm语言自身异常不会转换为ApiException
> * 转换时保持堆栈
> * 要获取原始异常类使用ex字段
> 
> 示例：
> 
> ```
> ApiException {
>   ex: "RPC传递时，原始异常类"
>   code: "异常码",
>   httpCode: "int: 如果是http直接返回时的状态码",
>   msg: "消息",
>   args: [……], // 需要传递的数据
>   i18n: '需要国际化展示时的code',
>   i18nArgs: [], // 国际化格式参数
> }
> ```

多系统交互这个我有想过的，其实我大体的设计思路如下：
![image](https://user-images.githubusercontent.com/5523726/75836836-172b2000-5dfe-11ea-8cf8-f7ddce744db6.png)
1. 异常、状态码都放在各个项目的common模块
2. api接口分内部跟对公，分别都依赖common模块，这样异常、状态码就能公用了
3. 其他系统比如b系统调用a系统，需依赖a-open-api模块，这样就间接依赖了a-common模块
4. 假如b-provider没有特别处理a系统服务抛出来的异常，那会直接往b-consumer抛，这时候如果b-consumer没有a系统的自定义异常，就会出现序列化问题；但是，b-consumer只要单独依赖a-common.jar，那么b-consumer也有了a系统+b系统的所有异常，就不会存在序列化问题。
5.  我提供的示例也是类似的设计 BaseException 基类异常，所有业务子异常都继承基类异常，然后接口方法标注throw BaseException，这样理论上应该能正常反序列化，实则反序列化出现空指针导致无法程序异常了。
6. 最后，其实整个问题的关注点还是在异常实例的值，为何会在consumer端反序列化的时候丢失了。原因是在provider端序列化的时候，就没有正常序列化；还是在consumer端接收的过程，出现异常丢失参数值，这个还需要理解RPC交互的流程，并且调试观察看看。

**Comment by xylsh** [comment]
demo里面，空指针异常似乎是因为这个枚举的反序列化有问题

**Comment by mbc3320** [comment]
> demo里面，空指针异常似乎是因为这个枚举的反序列化有问题

这个问题，我已经找到具体的原因了：**问题是在自定义异常类，缺少了无参构造。**

由于设计之初，考虑到开发可能会滥用无参构造，抛出异常而不指明具体的错误，所以一开始就计划将无参构造移除，实例化自定义异常必须传出具体的错误。
但是没想到，序列化/反序列化的时候，实例化时当没有无参构造方法，就调用了带参构造，而且参数还传了null，导致无法实例化，就出现NPE了。

**Comment by takeseem** [comment]
@mbc3320 如果用x-common来公开异常，异常在跨RPC链传递时，上上游的consumer不一定会依赖x-common导致反序列化失败。

ApiException（是RuntimeException）作为一个唯一的业务异常，放在框架中，承担的作用

1. 任何项目都有此异常，且跨 RPC 时非 JDK 内置异常都会包装转换为此异常（注意case、supperessed也要转换），保证 RPC 链中能正常处理异常
2. 以前用 instanceof 判定特异常，ApiException 是通过code，非要判断原始异常时用：ex字段（'原始异常的类全名'）来判断

**Comment by spilledyear** [comment]
> > demo里面，空指针异常似乎是因为这个枚举的反序列化有问题
> 
> 这个问题，我已经找到具体的原因了：**问题是在自定义异常类，缺少了无参构造。**
> 
> 由于设计之初，考虑到开发可能会滥用无参构造，抛出异常而不指明具体的错误，所以一开始就计划将无参构造移除，实例化自定义异常必须传出具体的错误。
> 但是没想到，序列化/反序列化的时候，实例化时当没有无参构造方法，就调用了带参构造，而且参数还传了null，导致无法实例化，就出现NPE了。

参数为什么会传null呢？
