### ISSUE TITLE
cause: INTERNAL: Panic! This is a bug!

### ISSUE THREAD

**Issue by twfx7758** [apache/dubbo#5825]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.5
* Operating System version: win10
* Java version: 1.8

Pls. provide [GitHub address] to reproduce this issue.

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.apache.dubbo.rpc.RpcException: Failed to invoke remote service: interface com.wenbin.grpc.services.DubboGreeterGrpc$IGreeter, method: sayHello, cause: INTERNAL: Panic! This is a bug!] with root cause

```
java.lang.AbstractMethodError: io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.newClientTransport(Ljava/net/SocketAddress;Lio/grpc/internal/ClientTransportFactory$ClientTransportOptions;Lio/grpc/ChannelLogger;)Lio/grpc/internal/ConnectionClientTransport;
	at io.grpc.internal.CallCredentialsApplyingTransportFactory.newClientTransport(CallCredentialsApplyingTransportFactory.java:49) ~[grpc-core-1.22.1.jar:1.22.1]
	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:246) ~[grpc-core-1.22.1.jar:1.22.1]
	at io.grpc.internal.InternalSubchannel.access$400(InternalSubchannel.java:65) ~[grpc-core-1.22.1.jar:1.22.1]
	at io.grpc.internal.InternalSubchannel$2.run(InternalSubchannel.java:196) ~[grpc-core-1.22.1.jar:1.22.1]
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95) ~[grpc-api-1.22.1.jar:1.22.1]
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127) ~[grpc-api-1.22.1.jar:1.22.1]
	at io.grpc.internal.ManagedChannelImpl$NameResolverListener.onResult(ManagedChannelImpl.java:1365) ~[grpc-core-1.22.1.jar:1.22.1]
	at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:311) ~[grpc-core-1.22.1.jar:1.22.1]
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:213) ~[grpc-core-1.22.1.jar:1.22.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
```

**Comment by chickenlj** [comment]
Were you using gRPC? How do you use it, can you give some detailed configuration?

**Comment by twfx7758** [comment]
> Were you using gRPC? How do you use it, can you give some detailed configuration?

grpc-core version problem, resolved
