### ISSUE TITLE
Consumer will lose subscribed service information when use Nacos as registry center

### ISSUE THREAD

**Issue by tswstarplanet** [apache/dubbo#5871]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7-SNAPSHOT
* Operating System version: MacOS
* Java version: OpenJDK 13

### Steps to reproduce this issue

1. Open the dubbo-demo-xml project
2. Modify the registry center both of provider and consumer to Nacos；Open the check switch of consumer
3. Run the provider
4.Run the consumer

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

The rpc can work properly.

### Actual Result

It fails.

If there is an exception, please attach the exception trace:

```
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoService': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: Failed to check the status of the service org.apache.dubbo.demo.DemoService. No provider available for the service org.apache.dubbo.demo.DemoService from the url nacos://127.0.0.1:8848/org.apache.dubbo.registry.RegistryService?application=demo-consumer&dubbo=2.0.2&init=false&interface=org.apache.dubbo.demo.DemoService&methods=sayHello,sayHelloAsync&pid=90344&qos.port=33333&register.ip=127.0.0.1&side=consumer&sticky=false&timestamp=1584323664330 to the consumer 127.0.0.1 use dubbo version 
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:177)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1640)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:254)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1086)
	at org.apache.dubbo.demo.consumer.Application.main(Application.java:33)
Caused by: java.lang.IllegalStateException: Failed to check the status of the service org.apache.dubbo.demo.DemoService. No provider available for the service org.apache.dubbo.demo.DemoService from the url nacos://127.0.0.1:8848/org.apache.dubbo.registry.RegistryService?application=demo-consumer&dubbo=2.0.2&init=false&interface=org.apache.dubbo.demo.DemoService&methods=sayHello,sayHelloAsync&pid=90344&qos.port=33333&register.ip=127.0.0.1&side=consumer&sticky=false&timestamp=1584323664330 to the consumer 127.0.0.1 use dubbo version 
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:350)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:258)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:158)
	at org.apache.dubbo.config.spring.ReferenceBean.getObject(ReferenceBean.java:68)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:170)
	... 6 more
```

**Comment by vergilyn** [comment]
2.7.6.RELEASE 也存在该问题。

备注：
`NacosRegistry#notifySubscriber(...)` 创建了protocol "empty://...."。
并且在接下来的`RegistryDirectory#refreshInvoker(...)`中满足  "forbidden" 并 destroyAllInvokers...

**Comment by tswstarplanet** [comment]
> 2.7.6.RELEASE 也存在该问题。
> 
> 备注：
> `NacosRegistry#notifySubscriber(...)` 创建了protocol "empty://...."。
> 并且在接下来的`RegistryDirectory#refreshInvoker(...)`中满足 "forbidden" 并 destroyAllInvokers...

生成empty的protocol是正常的。否则会出现服务端全部下线，但是客户端还有一个订阅的服务端的代理一直存在的情况

**Comment by vergilyn** [comment]
> > 2.7.6.RELEASE 也存在该问题。
> > 备注：
> > `NacosRegistry#notifySubscriber(...)` 创建了protocol "empty://...."。
> > 并且在接下来的`RegistryDirectory#refreshInvoker(...)`中满足 "forbidden" 并 destroyAllInvokers...
> 
> 生成empty的protocol是正常的。否则会出现服务端全部下线，但是客户端还有一个订阅的服务端的代理一直存在的情况

👍 学到了。

个人遇到的情况是 启动测试项目的时候（非dubbo-samples）因为这个empty的protocol，导致invokers=EMPTY，所以抛出异常"No provider available。"

**Comment by tswstarplanet** [comment]
> > > 2.7.6.RELEASE 也存在该问题。
> > > 备注：
> > > `NacosRegistry#notifySubscriber(...)` 创建了protocol "empty://...."。
> > > 并且在接下来的`RegistryDirectory#refreshInvoker(...)`中满足 "forbidden" 并 destroyAllInvokers...
> > 
> > 
> > 生成empty的protocol是正常的。否则会出现服务端全部下线，但是客户端还有一个订阅的服务端的代理一直存在的情况
> 
> 👍 学到了。
> 
> 个人遇到的情况是 启动测试项目的时候（非dubbo-samples）因为这个empty的protocol，导致invokers=EMPTY，所以抛出异常"No provider available。"

只有一个provider，而且没下线？那不应该。 你可以单独提个issue

**Comment by vergilyn** [comment]
> > > > 2.7.6.RELEASE 也存在该问题。
> > > > 备注：
> > > > `NacosRegistry#notifySubscriber(...)` 创建了protocol "empty://...."。
> > > > 并且在接下来的`RegistryDirectory#refreshInvoker(...)`中满足 "forbidden" 并 destroyAllInvokers...
> > > 
> > > 
> > > 生成empty的protocol是正常的。否则会出现服务端全部下线，但是客户端还有一个订阅的服务端的代理一直存在的情况
> > 
> > 
> > 👍 学到了。
> > 个人遇到的情况是 启动测试项目的时候（非dubbo-samples）因为这个empty的protocol，导致invokers=EMPTY，所以抛出异常"No provider available。"
> 
> 只有一个provider，而且没下线？那不应该。 你可以单独提个issue

#5885
