### ISSUE TITLE
Dubbo泛化调用是否可以考虑支持多种日期格式

### ISSUE THREAD

**Issue by chocotan** [apache/dubbo#5928]
现在只支持yyyy-MM-dd HH:mm:ss一种，导致调用方必须把时间戳或者没有时分秒的字段，转换成这种格式才行。

```
java.lang.IllegalStateException: Failed to parse date 2020-03-27 by format yyyy-MM-dd HH:mm:ss, cause: Unparseable date: "2020-03-27"
        at com.alibaba.dubbo.common.utils.CompatibleTypeUtils.compatibleTypeConvert(CompatibleTypeUtils.java:86)
        at com.alibaba.dubbo.common.utils.PojoUtils.realize0(PojoUtils.java:301)
        at com.alibaba.dubbo.common.utils.PojoUtils.realize0(PojoUtils.java:450)
```

另外一个问题，在此类异常发生的时候，服务消费方，try-catch异常时，拿到的异常code为
RpcException.NETWORK_EXCEPTION

**Comment by DIscord010** [comment]
@htynkn If needed.Can we use `Date date = org.apache.commons.lang3.time.DateUtils.DateUtils.parseDate(string, "yyyy-MM-dd HH:mm:ss", "yyyy-MM-dd");`  
replace `Date date = new SimpleDateFormat(DATE_FORMAT).parse(string);`?

**Comment by SYSNPE** [comment]
相同的问题 我们是为客户端提供http接口 之后gateway转化为dubbo协议调用dubbo接口 如果不使用泛化调用的方式 yyyy-MM-dd这种是可以直接调用的 但是使用泛化调用之后 日期类型的json数据必须为yyyy-MM-dd HH:mm:ss 这样很多老接口都需要改造 这个应该是公共问题吧

**Comment by SYSNPE** [comment]
希望在泛化调用方面投入多一些 基于dubbo的架构 gateway都不好做

**Comment by thinking-in-code** [comment]
如果自己所用的dubbo版本不支持多种日期格式解析，可以在 provider 里面写一个filter，自己去适配多种日期解析格式，也可以适配时间戳，可以参考dubbo的org.apache.dubbo.rpc.filter.GenericFilter。
