### ISSUE TITLE
dubbo 提供者中增加feign依赖启动报错

### ISSUE THREAD

**Issue by jianbo-chen** [apache/dubbo#5944]
### Environment

* Dubbo version: 2.7.3
* Operating System version: windows10
* Java version: 1.8

### Steps to reproduce this issue

1. 项目同时依赖feign和dubbo
2. 在dubbo的提供类里面注入feign
3. 启动时会报错，异常如下

Caused by: java.lang.IllegalStateException: No application config found or it's not a valid config! Please add <dubbo:application name="..." /> to your spring config.
	at org.apache.dubbo.config.AbstractInterfaceConfig.checkApplication(AbstractInterfaceConfig.java:216)
	at org.apache.dubbo.config.ServiceConfig.checkAndUpdateSubConfigs(ServiceConfig.java:299)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:369)
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:336)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:114)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:60)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:409)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:897)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
	at org.springframework.cloud.context.named.NamedContextFactory.createContext(NamedContextFactory.java:120)
	at org.springframework.cloud.context.named.NamedContextFactory.getContext(NamedContextFactory.java:88)
	at org.springframework.cloud.context.named.NamedContextFactory.getInstance(NamedContextFactory.java:129)
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.get(FeignClientFactoryBean.java:208)
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.feign(FeignClientFactoryBean.java:87)
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.getTarget(FeignClientFactoryBean.java:244)
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.getObject(FeignClientFactoryBean.java:235)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:171)
	... 96 common frames omitted

**Comment by chenyingjie1001** [comment]
我也发现了，好像引一个不会报错，引入两个以上就会报错。

**Comment by mr-szw** [comment]
这里也有这个问题 https://github.com/apache/dubbo/issues/3990
