### ISSUE TITLE
 No application config found or it's not a valid config

### ISSUE THREAD

**Issue by wangkang007** [apache/dubbo#5976]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.6
* Operating System version: macos 10.15.13
* Java version: xxx

### Steps to reproduce this issue

1. Spring boot 1.5.2 ,when update dubbo 2.5.3 to 2.7.6 ，I have some problems
2.  my config is  <dubbo:application name="indicatiors" owner="xxx"/>
3.  No application config found or it's not a valid config! Please add <dubbo:application name="..." />

只在特定的项目里面发生这个问题，但是整体的环境都是一样的

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

run error

the exception trace:

```
Caused by: java.lang.IllegalStateException: No application config found or it's not a valid config! Please add <dubbo:application name="..." /> to your spring config.
	at org.apache.dubbo.config.utils.ConfigValidationUtils.validateApplicationConfig(ConfigValidationUtils.java:371)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.checkGlobalConfigs(DubboBootstrap.java:526)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.initialize(DubboBootstrap.java:513)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.init(DubboBootstrap.java:494)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:190)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:158)
	at org.apache.dubbo.config.spring.ReferenceBean.getObject(ReferenceBean.java:68)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
	... 64 common frames omitted
```

**Comment by wangkang007** [comment]
<beans xmlns:dubbo="http://dubbo.apache.org/schema/dubbo" xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd      http://dubbo.apache.org/schema/dubbo http://dubbo.apache.org/schema/dubbo/dubbo.xsd">

**Comment by wangkang007** [comment]
```<beans xmlns:dubbo="http://dubbo.apache.org/schema/dubbo" xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd      http://dubbo.apache.org/schema/dubbo http://dubbo.apache.org/schema/dubbo/dubbo.xsd">
```

**Comment by supenBenny** [comment]
* Dubbo version: 2.7.6
* Operating System version: win10
* Java version: 11
* spring boot:2.2.6.RELEASE
使用注解@EnableDubbo正式，但通过@ImportResource("dubbo.xml") 出现同样问题，但使用main函数自己new ClassPathXmlApplicationContext("dubbo.xml")也正常通过ImportResource就不行
debug发现差异org.apache.dubbo.configAbstractConfig#addIntoConfigManager 是否执行，ImportResource里 @PostConstruct 失效了；但容器内其他类的PostConstruct 正常，dubbo注入的类失效

**Comment by xiyt** [comment]
> * bbo正常运行，但通过@ImportResource("dubbo.xml") 出现同样问题，但使用main函数自己new ClassPathXmlApplicationContext("dubbo.xml")也正常，通过ImportResource就不行debug发现差异org.apache.dubbo.configAbstractConfig#addIntoConfigManager 是否执行，ImportResource里 @PostConstruct 失效了；但容器内其他类的PostConstruct 正常，dubbo注入

我也是这个现象啊，我是2.7.7的版本，通过@ImportResource("dubbo.xml")方式加载的。addIntoConfigManager没有执行。原因是我发现有个BeanFactoryPostProcessor，里面注入了Environment，Spring在执行这个BeanFactoryPostProcessor时，在解决其需要的Environment依赖时，就会去创建dubbo服务的bean，然后就会先创建ApplicationConfig对象了。这时候，@PostConstruct还没有被解析呢。所以没有执行addIntoConfigManager。
