### ISSUE TITLE
java.io.IOException: 文件名、目录名或卷标语法不正确。

### ISSUE THREAD

**Issue by iwhalecloud-platform** [apache/dubbo#5990]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4.1
* Operating System version: mac
* Java version: 8

#### 错误
>020-04-10 10:36:22.117  WARN 12008 --- [Report-thread-1] o.a.d.m.s.z.ZookeeperMetadataReport      :  [DUBBO] Failed to save service store file, cause: 文件名、目录名或卷标语法不正确。, dubbo version: 2.7.4.1.ZDUBBO-SNAPSHOT, current host: 10.45.19.17
java.io.IOException: 文件名、目录名或卷标语法不正确。
  at java.io.WinNTFileSystem.createFileExclusively(Native Method) ~[na:1.8.0_101]
  at java.io.File.createNewFile(File.java:1012) ~[na:1.8.0_101]
  at org.apache.dubbo.metadata.support.AbstractMetadataReport.doSaveProperties(AbstractMetadataReport.java:144) [dubbo-2.7.4.1.ZDUBBO-SNAPSHOT.jar:2.7.4.1.ZDUBBO-SNAPSHOT]
  at org.apache.dubbo.metadata.support.AbstractMetadataReport.access$100(AbstractMetadataReport.java:70) [dubbo-2.7.4.1.ZDUBBO-SNAPSHOT.jar:2.7.4.1.ZDUBBO-SNAPSHOT]
  at org.apache.dubbo.metadata.support.AbstractMetadataReport$SaveProperties.run(AbstractMetadataReport.java:224) [dubbo-2.7.4.1.ZDUBBO-SNAPSHOT.jar:2.7.4.1.ZDUBBO-SNAPSHOT]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
  at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]

配置zk地址配置成：127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183就会出现，改成
zookeeper://127.0.0.1:2181?backup=127.0.0.1:2182,127.0.0.1:2183 就好了

**Comment by hengyunabc** [comment]
这个有具体可重现的demo不？ 或者具体重现的步骤。

**Comment by chickenlj** [comment]
地址会成为文件名的一部分，可能是其中的 `,` 未转移
`127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183`

**Comment by chickenlj** [comment]
暂无法复现，请贴出出错的文件全路径名后再 reopen。

**Comment by cccccong** [comment]
我这里的情况是由于在window下文件夹名不能包含':'导致的
