### ISSUE TITLE
first call time consumption too long

### ISSUE THREAD

**Issue by KindHunter** [apache/dubbo#6004]
- [√ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [√ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3  with redis register
* Operating System version: WIN10
* Java version: JAVA8

In our production environment, i found the first time dubbo api time consumption is alwarys too long when we re-deloy cluster, sometimes will case some complex dubbo api timeout. any clue to avoid this situation?

below is a demo i wrote , also showing first time consumption is always longer than other time, on my computer is firsttime: 100+ms, other times: 10-ms

DEMO GitHub address: https://github.com/KindHunter/dubbo_test.git

### Expected Result

Expect every time consumption is similar

### Actual Result

first time call time consumption is always too long!

**Comment by cyb-code** [comment]
我也遇到了相同的问题，服务端重启，消费端就会超时！

**Comment by vergilyn** [comment]
dubbo 2.7.6（snapshot）也遇到过，类似`sayHello()`简单的demo。consumer启动并立即调用@DubboService(timeout = 1000, retries = 2)`，会出现EXCEPTION。但是因为重试机制，所以是会调用成功的
```
dubbo 2.7.6（snapshot）也遇到过，类似`sayHello()`简单的demo。consumer启动并立即调用@DubboService(timeout = 1000, retries = 2)`，会出现EXCEPTION。但是因为重试机制，所以是会调用成功的
```
2020-04-17 16:26:33.610  INFO 19644 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 13 endpoint(s) beneath base path '/actuator'
2020-04-17 16:26:33.702  INFO 19644 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 19020 (http) with context path ''
2020-04-17 16:26:33.707  INFO 19644 --- [           main] c.v.e.ConsumerExamplesApplication        : Started ConsumerExamplesApplication in 12.471 seconds (JVM running for 14.196)
2020-04-17 16:26:35.324  WARN 19644 --- [:20880-thread-1] o.a.d.r.exchange.support.DefaultFuture   :  [DUBBO] The timeout response finally returned at 2020-04-17 16:26:35.324, response Response [id=0, version=null, status=20, event=false, error=null, result=AppResponse [value=[dubbo-provider-application][ProviderFirstApiImpl] >>>>>>>> Hello, vergilyn, exception=null]], channel: /127.0.0.1:60075 -> /127.0.0.1:20880, dubbo version: 2.7.6.RELEASE, current host: 127.0.0.1
2020-04-17 16:26:35.942  WARN 19644 --- [           main] o.a.d.r.c.s.FailoverClusterInvoker       :  [DUBBO] Although retry the method sayHello in the service com.vergilyn.examples.api.ProviderFirstApi was successful by the provider 127.0.0.1:20880, but there have been failed providers [127.0.0.1:20880] (1/1) from the registry localhost:8848 on the consumer 127.0.0.1 using the dubbo version 2.7.6.RELEASE. Last error is: Invoke remote method timeout. method: sayHello, provider: dubbo://127.0.0.1:20880/com.vergilyn.examples.api.ProviderFirstApi?anyhost=true&application=dubbo-consumer-application&category=providers&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&init=false&interface=com.vergilyn.examples.api.ProviderFirstApi&logger=log4j2&methods=sayHello,sayGoodbye&path=com.vergilyn.examples.api.ProviderFirstApi&pid=19644&protocol=dubbo&register.ip=127.0.0.1&release=2.7.6.RELEASE&remote.application=dubbo-provider-application&revision=1.0.0&side=consumer&sticky=false&timeout=1000&timestamp=1587111923200&version=1.0.0, cause: org.apache.dubbo.remoting.TimeoutException: Waiting server-side response timeout by scan timer. start time: 2020-04-17 16:26:33.875, end time: 2020-04-17 16:26:34.906, client elapsed: 241 ms, server elapsed: 790 ms, timeout: 1000 ms, request: Request [id=0, version=2.0.2, twoway=true, event=false, broken=false, data=null], channel: /127.0.0.1:60075 -> /127.0.0.1:20880, dubbo version: 2.7.6.RELEASE, current host: 127.0.0.1

org.apache.dubbo.rpc.RpcException: Invoke remote method timeout. method: sayHello, provider: dubbo://127.0.0.1:20880/com.vergilyn.examples.api.ProviderFirstApi?anyhost=true&application=dubbo-consumer-application&category=providers&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&init=false&interface=com.vergilyn.examples.api.ProviderFirstApi&logger=log4j2&methods=sayHello,sayGoodbye&path=com.vergilyn.examples.api.ProviderFirstApi&pid=19644&protocol=dubbo&register.ip=127.0.0.1&release=2.7.6.RELEASE&remote.application=dubbo-provider-application&revision=1.0.0&side=consumer&sticky=false&timeout=1000&timestamp=1587111923200&version=1.0.0, cause: org.apache.dubbo.remoting.TimeoutException: Waiting server-side response timeout by scan timer. start time: 2020-04-17 16:26:33.875, end time: 2020-04-17 16:26:34.906, client elapsed: 241 ms, server elapsed: 790 ms, timeout: 1000 ms, request: Request [id=0, version=2.0.2, twoway=true, event=false, broken=false, data=null], channel: /127.0.0.1:60075 -> /127.0.0.1:20880
	at org.apache.dubbo.rpc.protocol.AsyncToSyncInvoker.invoke(AsyncToSyncInvoker.java:86) ~[classes/:na]
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:78) ~[classes/:na]
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:89) ~[classes/:na]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[classes/:na]
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:51) ~[classes/:na]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[classes/:na]
	at org.apache.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:55) ~[classes/:na]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[classes/:na]
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56) ~[classes/:na]
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:82) ~[classes/:na]
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:259) [classes/:na]
	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47) [classes/:na]
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92) [classes/:na]
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:82) [classes/:na]
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:95) [classes/:na]
	at org.apache.dubbo.common.bytecode.proxy0.sayHello(proxy0.java) [classes/:na]
	at com.vergilyn.examples.ConsumerExamplesApplication.run(ConsumerExamplesApplication.java:33) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784) [spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768) [spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at com.vergilyn.examples.ConsumerExamplesApplication.main(ConsumerExamplesApplication.java:28) [classes/:na]
Caused by: java.util.concurrent.ExecutionException: org.apache.dubbo.remoting.TimeoutException: Waiting server-side response timeout by scan timer. start time: 2020-04-17 16:26:33.875, end time: 2020-04-17 16:26:34.906, client elapsed: 241 ms, server elapsed: 790 ms, timeout: 1000 ms, request: Request [id=0, version=2.0.2, twoway=true, event=false, broken=false, data=null], channel: /127.0.0.1:60075 -> /127.0.0.1:20880
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[na:1.8.0_171]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915) ~[na:1.8.0_171]
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:181) ~[classes/:na]
	at org.apache.dubbo.rpc.protocol.AsyncToSyncInvoker.invoke(AsyncToSyncInvoker.java:79) ~[classes/:na]
	... 20 common frames omitted
Caused by: org.apache.dubbo.remoting.TimeoutException: Waiting server-side response timeout by scan timer. start time: 2020-04-17 16:26:33.875, end time: 2020-04-17 16:26:34.906, client elapsed: 241 ms, server elapsed: 790 ms, timeout: 1000 ms, request: Request [id=0, version=2.0.2, twoway=true, event=false, broken=false, data=null], channel: /127.0.0.1:60075 -> /127.0.0.1:20880
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.doReceived(DefaultFuture.java:223) ~[classes/:na]
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:188) ~[classes/:na]
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture$TimeoutCheckTask.notifyTimeout(DefaultFuture.java:311) ~[classes/:na]
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture$TimeoutCheckTask.lambda$run$0(DefaultFuture.java:298) ~[classes/:na]
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:93) ~[classes/:na]
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:179) ~[classes/:na]
	... 21 common frames omitted

2020-04-17 16:26:35.943  INFO 19644 --- [           main] c.v.e.ConsumerExamplesApplication        : [dubbo-provider-application][ProviderFirstApiImpl] >>>>>>>> Hello, vergilyn
2020-04-17 16:26:35.946  INFO 19644 --- [           main] c.v.e.ConsumerExamplesApplication        : [dubbo-provider-application][ProviderSecondApiImpl] >>>>>>>> print, vergilyn
2020-04-17 16:26:35.946  INFO 19644 --- [           main] c.v.e.ConsumerExamplesApplication        : >>>> finish <<<<
```
```

**Comment by vergilyn** [comment]
可以尝试设置`timeout`，例如 `@Reference(timeout=2s)`（缺省值 1s）。
个人也遇到了类似问题，跟你写的demo差不多。
第1次可能timeout，但因为retries=2（默认值），第2次重试却能正常响应。

备注：
1. provider 的业务方法内 `sleep(1s)`
2. consumer `@Reference(timeout = 1s)`

理论上来说，始终都是timeout，但是实际是第2+次可以成功。
这跟dubbo的timeout检测机制有关。

重试机制代码：
- `FailoverClusterInvoker#doInvoke(Invocation, List<Invoker<T>>, LoadBalance )`

timeout 的开始时间: 
- `HeaderExchangeChannel#request(Object, int, ExecutorService)` -> `DefaultFuture#newFuture(...)`

timeout 的结束时间:
- `NettyClientHandler#write(...)`

第1次调用 和 重试调用的时间差，主要是由 `NettyClientHandler#write(...)` 中的`super.write()`造成，即netty 的 `ChannelDuplexHandler#write()`造成。
我通过简单的测试，第1次可能需要花费80ms，但第2+次只需要1ms左右。

所以，重试时server多了80ms的交互时间来检测timeout。另外加上timeout检测机制的误差，可能多出100ms，所以重试（即第2+次）**可能成功！**
