### ISSUE TITLE
应用优雅退出时，DubboShutdownHook.destroyAll错误

### ISSUE THREAD

**Issue by haoxz11** [apache/dubbo#6109]
### Environment

* Dubbo version: 2.7.6
* Java version: 1.8

### Steps to reproduce this issue

1. dubbo应用正常优雅关闭
2. 应用日志中打出错误日志

### Actual Result

2020-05-07 08:36:06.391 [SpringContextShutdownHook] WARN  o.s.c.a.AnnotationConfigApplicationContext:1015 :: [] => Exception thrown from ApplicationListener handling ContextClosedEvent
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1471)
	at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
	at org.apache.dubbo.registry.support.AbstractRegistryFactory.destroyAll(AbstractRegistryFactory.java:85)
	at org.apache.dubbo.config.DubboShutdownHook.destroyAll(DubboShutdownHook.java:128)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.destroy(DubboBootstrap.java:1039)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.stop(DubboBootstrap.java:818)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onContextClosedEvent(DubboBootstrapApplicationListener.java:63)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onApplicationContextEvent(DubboBootstrapApplicationListener.java:54)
	at org.apache.dubbo.config.spring.context.OneTimeExecutionApplicationContextEventListener.onApplicationEvent(OneTimeExecutionApplicationContextEventListener.java:40)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1012)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:948)

**Comment by marstalk** [comment]
multi-registries?

**Comment by haoxz11** [comment]
> multi-registries?

单个注册点，<2.7.6的版本都是好的

**Comment by DIscord010** [comment]
和 #6027是一个问题吧，已经修复了。

**Comment by haoxz11** [comment]
> 和 #6027 是一个问题吧，已经修复了。

目测一个问题，只有使用Nacos才会复现T_T
