### ISSUE TITLE
缓存文件找不到, 导致的死循环

### ISSUE THREAD

**Issue by lizhibo0914** [apache/dubbo#6140]
正式项目中, 发现dubbo在运行中 ,出现了缓存文件找不到的现象出现了死循环, 疯狂打印日志, 导致cpu特别高, 一直循环打印:  Failed to save registry store file, cause: 没有那个文件活目录

**Comment by Huangxuny1** [comment]
hello @lizhibo0914 , 

by given information , `Failed to save registry store file, cause: 没有那个文件活目录` maybe print from [AbstractRegistry.java](https://github.com/apache/dubbo/blob/cb2f6afcaeee9786062693afa9b1d6289108d0f9/dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java#L209)

I am try to reproduce by a test   in [AbstractRegistryTest.java](https://github.com/apache/dubbo/blob/master/dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/support/AbstractRegistryTest.java)

```java
    @Test
    public void testDoSaveProperties() throws NoSuchFieldException, IllegalAccessException, IOException {
        String defaultFilename = System.getProperty("user.home") + "/.dubbo/dubbo-registry-" + testUrl.getParameter(APPLICATION_KEY) + "-" + testUrl.getAddress().replaceAll(":", "-") + ".cache";
        File mockFile = spy(new File(defaultFilename));
        Field fileField = abstractRegistry.getClass().getSuperclass().getDeclaredField("file");
        fileField.setAccessible(true);
        fileField.set(abstractRegistry, mockFile);

        doReturn(false).when(mockFile).exists();
        doThrow(new IOException(" no such file or dir ")).when(mockFile).createNewFile();
        abstractRegistry.doSaveProperties(1);
    }
```

but I cannot reproduce it

it's output
```
[17/05/20 15:09:53:263 CST]  WARN support.AbstractRegistryTest$1:  [DUBBO] Failed to save registry cache file, will retry, cause:  no such file or dir , dubbo version: , current host: 192.168.1.83
java.io.IOException:  no such file or dir 
	at org.apache.dubbo.registry.support.AbstractRegistry.doSaveProperties(AbstractRegistry.java:187)
	at org.apache.dubbo.registry.support.AbstractRegistry$SaveProperties.run(AbstractRegistry.java:526)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[17/05/20 15:09:53:263 CST]  WARN support.AbstractRegistryTest$1:  [DUBBO] Failed to save registry cache file, will retry, cause:  no such file or dir , dubbo version: , current host: 192.168.1.83
java.io.IOException:  no such file or dir 
	at org.apache.dubbo.registry.support.AbstractRegistry.doSaveProperties(AbstractRegistry.java:187)
	at org.apache.dubbo.registry.support.AbstractRegistry$SaveProperties.run(AbstractRegistry.java:526)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[17/05/20 15:09:53:289 CST]  WARN support.AbstractRegistryTest$1:  [DUBBO] Failed to save registry cache file after retrying 3 times, cause:  no such file or dir , dubbo version: , current host: 192.168.1.83
java.io.IOException:  no such file or dir 
	at org.apache.dubbo.registry.support.AbstractRegistry.doSaveProperties(AbstractRegistry.java:187)
	at org.apache.dubbo.registry.support.AbstractRegistry$SaveProperties.run(AbstractRegistry.java:526)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

maybe it'd fixed in #3748

can you give a demo program to reproduce 
or tell us  **more information** such as `dubbo version` or `StackTrace` ?
