### ISSUE TITLE
dubbo泛化调用设置了group的提供者服务时，consul的健康检查不通过

### ISSUE THREAD

**Issue by AlwaysAldom** [apache/dubbo#6205]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.6
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue

1. 本地启动最简单的dubbo provider进程，注册中心选择consul
2. 本地单测通过dubbo泛化调步骤1的provider

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

dubbo泛化正常

### Actual Result

若provider未设置group可正常调用；否则报“org.apache.dubbo.rpc.RpcException: No provider available from registry xxx for service group/service on consumer...”异常

If there is an exception, please attach the exception trace:

```
org.apache.dubbo.rpc.RpcException: No provider available from registry localhost:8500 for service g1/fake.service.FakeService on consumer 172.28.42.23 use dubbo version 2.7.6, please check status of providers(disabled, not registered or in blacklist).
	at org.apache.dubbo.registry.integration.RegistryDirectory.doList(RegistryDirectory.java:599)
	at org.apache.dubbo.rpc.cluster.directory.AbstractDirectory.list(AbstractDirectory.java:75)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.list(AbstractClusterInvoker.java:291)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:256)
	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:82)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:74)
	at org.apache.dubbo.common.bytecode.proxy0.$invoke(proxy0.java)
	at dubbo.DubboTest.invoke(DubboTest.java:65)

```

**Comment by AlwaysAldom** [comment]
> * [x]  I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
> * [x]  I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.
> 
> ### Environment
> * Dubbo version: 2.7.6
> * Operating System version: win10
> * Java version: 1.8
> 
> ### Steps to reproduce this issue
> 1. 本地启动最简单的dubbo provider进程，注册中心选择consul
> 2. 本地单测通过dubbo泛化调步骤1的provider
> 
> Pls. provide [GitHub address] to reproduce this issue.
> 
> ### Expected Result
> dubbo泛化正常
> 
> ### Actual Result
> 若provider未设置group可正常调用；否则报“org.apache.dubbo.rpc.RpcException: No provider available from registry xxx for service group/service on consumer...”异常
> 
> If there is an exception, please attach the exception trace:
> 
> ```
> org.apache.dubbo.rpc.RpcException: No provider available from registry localhost:8500 for service g1/fake.service.FakeService on consumer 172.28.42.23 use dubbo version 2.7.6, please check status of providers(disabled, not registered or in blacklist).
> 	at org.apache.dubbo.registry.integration.RegistryDirectory.doList(RegistryDirectory.java:599)
> 	at org.apache.dubbo.rpc.cluster.directory.AbstractDirectory.list(AbstractDirectory.java:75)
> 	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.list(AbstractClusterInvoker.java:291)
> 	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:256)
> 	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)
> 	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)
> 	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:82)
> 	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:74)
> 	at org.apache.dubbo.common.bytecode.proxy0.$invoke(proxy0.java)
> 	at dubbo.DubboTest.invoke(DubboTest.java:65)
> ```

调试发现com.ecwid.consul.v1.health.HealthConsulClient#getHealthServices(java.lang.String, com.ecwid.consul.v1.health.HealthServicesRequest)，consul在做健康检查时，会检查“/v1/health/service/服务group名/服务名”，拉不到健康服务，导致泛化调用时，provider的状态是forbidden的

**Comment by jianpeng957** [comment]
问题定位到：org/apache/dubbo/registry/consul/ConsulRegistry.java:330，此处获取的逻辑应当与: org/apache/dubbo/registry/consul/ConsulRegistry.java:141保持一致

**Comment by AlwaysAldom** [comment]
> 问题定位到：org/apache/dubbo/registry/consul/ConsulRegistry.java:330，此处获取的逻辑应当与: org/apache/dubbo/registry/consul/ConsulRegistry.java:141保持一致

什么时候打个补丁到release分支呢？
