### ISSUE TITLE
applicat startup appear TargetNamespace.1: 应为名称空间 'http://dubbo.apache.org/schema/dubbo', 但方案文档的目标名称空间为 'http://code.alibabatech.com/schema/dubbo'

### ISSUE THREAD

**Issue by copyshop** [apache/dubbo#6218]
### Environment

* Dubbo version: 2.7.4.1
* Operating System version: win10
* Java version: 8

consumer.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:dubbo="http://dubbo.apache.org/schema/dubbo"
       xmlns="http://www.springframework.org/schema/beans"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
       http://dubbo.apache.org/schema/dubbo http://dubbo.apache.org/schema/dubbo/dubbo.xsd">

  
    <dubbo:consumer version="1.0" retries="0" check="false" lazy="true"/>

    <dubbo:reference id="..." interface="..."/>

</beans>
```

provide.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:dubbo="http://dubbo.apache.org/schema/dubbo"
       xmlns="http://www.springframework.org/schema/beans"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
       http://dubbo.apache.org/schema/dubbo http://dubbo.apache.org/schema/dubbo/dubbo.xsd">
	   
	   
    <dubbo:application name="${dubbo.application.name}">
        <dubbo:parameter key="qos.enable" value="true"/>
        <dubbo:parameter key="qos.accept.foreign.ip" value="false"/>
        <dubbo:parameter key="qos.port" value="33331"/>
    </dubbo:application>
    <dubbo:registry protocol="zookeeper" address="${dubbo.registry.address}"/>


    <dubbo:protocol name="dubbo" port="${dubbo.protocol.port}"/>

    <dubbo:provider id="mcu_stockcenter_provider" timeout="5000" version="1.0" retries="0">
        <dubbo:parameter key="shutdown.timeout" value="80000"/>
    </dubbo:provider>

    <dubbo:service interface="......" ref="..." retries="0" timeout="8000"/>
	
	......
</beans>
```

application start have a error:

```

Caused by: org.xml.sax.SAXParseException: TargetNamespace.1: 应为名称空间 'http://dubbo.apache.org/schema/dubbo', 但方案文档的目标名称空间为 'http://code.alibabatech.com/schema/dubbo'。
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)

```
I cannot understand this why， 3q，

**Comment by copyshop** [comment]
排除掉旧的依赖即可
