### ISSUE TITLE
dubbo 2.7.6&2.7.7必现服务调不通bug，内含复现demo

### ISSUE THREAD

**Issue by supercocoa** [apache/dubbo#6228]
### Environment

* Dubbo version: 2.7.6 or 2.7.7
* Operating System version: all
* Java version: 1.8

#### 链路1
1. 使用附件中的demo，先起consumer，consumer起来运行几秒
2. 起provider
3. consumer持续报错，调不通provider。

```log
java.lang.NullPointerException
	at org.apache.dubbo.rpc.model.ConsumerModel.initMethodModels(ConsumerModel.java:141)
	at org.apache.dubbo.rpc.model.ConsumerModel.init(ConsumerModel.java:69)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:264)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:158)
	at com.demo.dubbo.Consumer.getHelloService(Consumer.java:29)
	at com.demo.dubbo.Consumer.main(Consumer.java:42)
```

上述操作不分zk还是nacos都有问题，但如果先起provider就没问题
consumer换成dubbo 2.7.5也没问题
更新：此链路用2.7.在 consumer demo里增加reference.setCheck(false) 可以规避

#### 链路2
1. 注册中心使用zk，先把zk杀掉
2. 使用附件中的demo，先起consumer，consumer起来运行几秒
3. 启动zk，确定2181端口起来后，再起provider
4. consumer持续报错，调不通provider。

```log
java.lang.NullPointerException
	at org.apache.dubbo.rpc.model.ConsumerModel.initMethodModels(ConsumerModel.java:141)
	at org.apache.dubbo.rpc.model.ConsumerModel.init(ConsumerModel.java:69)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:264)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:158)
	at com.demo.dubbo.Consumer.getHelloService(Consumer.java:29)
	at com.demo.dubbo.Consumer.main(Consumer.java:42)
```
上述操作只是用zk有问题nacos没问题，consumer换成dubbo 2.7.5也没问题
此链路用2.7.7在consumer demo里增加 registryConfig.setCheck(false); 和 reference.setCheck(false); 也不起作用。

### Expected Result

1. 先起consumer也能正常
2. zk先关后起再起provider也能正常

### Actual Result

1. 先起consumer再起provider就调不通了
2. zk先关后起再起provider就调不通了

附件demo：
[dubbo-nacos-demo.zip](https://github.com/apache/dubbo/files/4734538/dubbo-nacos-demo.zip)

**Comment by supercocoa** [comment]
必现问题，可以的话请尽快修复发布bugfix版
@beiwei30 @cvictory @tswstarplanet @chickenlj

**Comment by foreveryang321** [comment]
consumer增加check="false"
> 单个服务
```xml
<dubbo:reference id="helloService" interface="com.demo.dubbo.IHelloService" check="false"/>
```
> 所有服务
```xml
<dubbo:consumer check="false"/>
```

**Comment by supercocoa** [comment]
这个`check` 2.7.5和以前的版本也有，但是2.7.5和以前的版本没有设置成false也可以调通，2.7.6&2.7.7不行。 @foreveryang321

**Comment by wenit** [comment]
我也遇到此问题，dubbo版本为2.7.7

**Comment by wenit** [comment]
增加consumer增加check="false" 可以解决问题

> consumer增加check="false"
> 
> > 单个服务
> 
> ```
> <dubbo:reference id="helloService" interface="com.demo.dubbo.IHelloService" check="false"/>
> ```
> 
> > 所有服务
> 
> ```
> <dubbo:consumer check="false"/>
> ```

经验证，增加此参数可以解决问题
