### ISSUE TITLE
栈溢出

### ISSUE THREAD

**Issue by guoweibo** [apache/dubbo#6260]
1.查询数据量少的话不会出现这个bug，但是数据量大就出现了

java.lang.StackOverflowError
	at org.apache.commons.beanutils.PropertyUtilsBean.getPropertyDescriptors(PropertyUtilsBean.java:962)
	at org.apache.commons.beanutils.PropertyUtilsBean.getPropertyDescriptors(PropertyUtilsBean.java:1075)
	at org.apache.commons.beanutils.PropertyUtilsBean.getPropertyDescriptor(PropertyUtilsBean.java:903)
	at org.apache.commons.beanutils.PropertyUtilsBean.getSimpleProperty(PropertyUtilsBean.java:1310)
	at org.apache.commons.beanutils.PropertyUtilsBean.getNestedProperty(PropertyUtilsBean.java:762)
	at org.apache.commons.beanutils.PropertyUtilsBean.getProperty(PropertyUtilsBean.java:837)
	at org.apache.commons.beanutils.PropertyUtils.getProperty(PropertyUtils.java:426)
	at net.sf.json.JSONObject.defaultBeanProcessing(JSONObject.java:749)
	at net.sf.json.JSONObject._fromBean(JSONObject.java:699)
	at net.sf.json.JSONObject.fromObject(JSONObject.java:172)
	at net.sf.json.JSONSerializer.toJSON(JSONSerializer.java:108)
	at net.sf.json.AbstractJSON._processValue(AbstractJSON.java:238)
	at net.sf.json.JSONArray._processValue(JSONArray.java:2513)
	at net.sf.json.JSONArray.processValue(JSONArray.java:2538)
	at net.sf.json.JSONArray.addValue(JSONArray.java:2525)
	at net.sf.json.JSONArray.element(JSONArray.java:1724)
	at net.sf.json.JSONArray.fromObject(JSONArray.java:159)
	at net.sf.json.JSONSerializer.toJSON(JSONSerializer.java:113)
	at net.sf.json.AbstractJSON._processValue(AbstractJSON.java:238)
	at net.sf.json.JSONArray._processValue(JSONArray.java:2513)
	at net.sf.json.JSONArray.processValue(JSONArray.java:2538)
	at net.sf.json.JSONArray.addValue(JSONArray.java:2525)
	at net.sf.json.JSONArray.element(JSONArray.java:1724)
	at net.sf.json.JSONArray.fromObject(JSONArray.java:159)
	at net.sf.json.JSONSerializer.toJSON(JSONSerializer.java:113)
	at net.sf.json.AbstractJSON._processValue(AbstractJSON.java:238)
	at net.sf.json.JSONArray._processValue(JSONArray.java:2513)
	at net.sf.json.JSONArray.processValue(JSONArray.java:2538)
	at net.sf.json.JSONArray.addValue(JSONArray.java:2525)
	at net.sf.json.JSONArray.element(JSONArray.java:1724)
	at net.sf.json.JSONArray.fromObject(JSONArray.java:159)
	at net.sf.json.JSONSerializer.toJSON(JSONSerializer.java:113)
	at net.sf.json.AbstractJSON._processValue(AbstractJSON.java:238)
	at net.sf.json.JSONArray._processValue(JSONArray.java:2513)
	at net.sf.json.JSONArray.processValue(JSONArray.java:2538)
	at net.sf.json.JSONArray.addValue(JSONArray.java:2525)
	at net.sf.json.JSONArray.element(JSONArray.java:1724)
	at net.sf.json.JSONArray.fromObject(JSONArray.java:159)
	at net.sf.json.JSONSerializer.toJSON(JSONSerializer.java:113)
	at net.sf.json.AbstractJSON._processValue(AbstractJSON.java:238)
	at net.sf.json.JSONArray._processValue(JSONArray.java:2513)
	at net.sf.json.JSONArray.processValue(JSONArray.java:2538)
	at net.sf.json.JSONArray.addValue(JSONArray.java:2525)
	at net.sf.json.JSONArray.element(JSONArray.java:1724)
	at net.sf.json.JSONArray.fromObject(JSONArray.java:159)
	at net.sf.json.JSONSerializer.toJSON(JSONSerializer.java:113)
	at net.sf.json.AbstractJSON._processValue(AbstractJSON.java:238)
	at net.sf.json.JSONArray._processValue(JSONArray.java:2513)
	at net.sf.json.JSONArray.processValue(JSONArray.java:2538)
	at net.sf.json.JSONArray.addValue(JSONArray.java:2525)
	at net.sf.json.JSONArray.element(JSONArray.java:1724)
	at net.sf.json.JSONArray.fromObject(JSONArray.java:159)
	at net.sf.json.JSONSerializer.toJSON(JSONSerializer.java:113)
	at net.sf.json.AbstractJSON._processValue(AbstractJSON.java:238)
	at net.sf.json.JSONArray._processValue(JSONArray.java:2513)
	at net.sf.json.JSONArray.processValue(JSONArray.java:2538)
	at net.sf.json.JSONArray.addValue(JSONArray.java:2525)
	at net.sf.json.JSONArray.element(JSONArray.java:1724)

### Environment

* Dubbo version: 
* Operating System version: xxx
* Java version: 1.8

**Comment by mercyblitz** [comment]
I think it's not an issue about Dubbo.
