### ISSUE TITLE
[Bug] Dubbo2.7.7 provider重启后，consumer无法消费: Not found exported service

### ISSUE THREAD

**Issue by Starbucksstar** [apache/dubbo#6276]
### Environment

* Dubbo version: 2.7.7
* Operating System version: MacOs
* Java version: 1.8
* Nacos:1.2.1
* dubbo-registry-nacos:2.7.7

### Steps to reproduce this issue

1. 先启动provider注册服务到nacos，然后在启动consumer注册到nacos，然后调用cusmer接口消费provider接口正常。服务注册信息如下：
![image](https://user-images.githubusercontent.com/20951983/83901783-e0aec980-a78d-11ea-9c5a-597c469d8db0.png)

2. 此时重启provider端，在次调用consumer端接口，发现泛化调用失败，报错信息如下：
```
Failed to invoke remote method: queryUser, provider: dubbo://192.168.6.101:20880/com.star.dubboprovider.api.service.UserService?anyhost=true&application=dubbo-consumer&category=providers&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&group=dubbo&init=false&interface=com.star.dubboprovider.api.service.UserService&metadata-type=remote&methods=insertUSer,deleteUser,updateUser,queryUser&metrics.port=20880&metrics.protocol=dubbo&path=com.star.dubboprovider.api.service.UserService&pid=39667&protocol=dubbo&qos.enable=true&qos.port=33333&reference.filter=metrics&register.ip=192.168.6.101&release=2.7.7&remote.application=dubboprovider&revision=0.0.1-SNAPSHOT&side=consumer&sticky=false&timestamp=1591374210010&version=1.0.0, cause: org.apache.dubbo.remoting.RemotingException: org.apache.dubbo.remoting.RemotingException: **Not found exported service**: dubbo/com.star.dubboprovider.api.service.UserService:1.0.0:20880 in [org.apache.dubbo.monitor.MetricsService:20880], may be version or group mismatch ,
```
3. 为何nacos没有将新的provider服务注册信息push
给consumer端

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？
provider端重启，group,version和接口名没有发生变动的情况下，消费方不应该无法找到暴露的服务，影响正常的rpc调用。
### Actual Result

What actually happens?
我不知道是不是消费方注册有问题，还是dubbo和nacos之间的服务订阅存在问题？？？
If there is an exception, please attach the exception trace:

```
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.apache.dubbo.rpc.RpcException: Failed to invoke the method queryUser in the service com.star.dubboprovider.api.service.UserService. Tried 3 times of the providers [192.168.6.101:20880] (1/1) from the registry localhost:8848 on the consumer 192.168.6.101 using the dubbo version 2.7.7. Last error is: Failed to invoke remote method: queryUser, provider: dubbo://192.168.6.101:20880/com.star.dubboprovider.api.service.UserService?anyhost=true&application=dubbo-consumer&category=providers&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&group=dubbo&init=false&interface=com.star.dubboprovider.api.service.UserService&metadata-type=remote&methods=insertUSer,deleteUser,updateUser,queryUser&metrics.port=20880&metrics.protocol=dubbo&path=com.star.dubboprovider.api.service.UserService&pid=39667&protocol=dubbo&qos.enable=true&qos.port=33333&reference.filter=metrics&register.ip=192.168.6.101&release=2.7.7&remote.application=dubboprovider&revision=0.0.1-SNAPSHOT&side=consumer&sticky=false&timestamp=1591374210010&version=1.0.0, cause: org.apache.dubbo.remoting.RemotingException: org.apache.dubbo.remoting.RemotingException: Not found exported service: dubbo/com.star.dubboprovider.api.service.UserService:1.0.0:20880 in [org.apache.dubbo.monitor.MetricsService:20880], may be version or group mismatch , channel: consumer: /192.168.6.101:62499 --> provider: /192.168.6.101:20880, message:RpcInvocation [methodName=queryUser, parameterTypes=[class com.star.dubboprovider.api.dto.UserKeyDTO], arguments=[com.star.dubboprovider.api.dto.UserKeyDTO@140a8d08], attachments={input=361, path=com.star.dubboprovider.api.service.UserService, remote.application=dubbo-consumer, dubbo=2.0.2, interface=com.star.dubboprovider.api.service.UserService, version=1.0.0, group=dubbo}]
org.apache.dubbo.remoting.RemotingException: Not found exported service: dubbo/com.star.dubboprovider.api.service.UserService:1.0.0:20880 in [org.apache.dubbo.monitor.MetricsService:20880], may be version or group mismatch , channel: consumer: /192.168.6.101:62499 --> provider: /192.168.6.101:20880, message:RpcInvocation [methodName=queryUser, parameterTypes=[class com.star.dubboprovider.api.dto.UserKeyDTO], arguments=[com.star.dubboprovider.api.dto.UserKeyDTO@140a8d08], attachments={input=361, path=com.star.dubboprovider.api.service.UserService, remote.application=dubbo-consumer, dubbo=2.0.2, interface=com.star.dubboprovider.api.service.UserService, version=1.0.0, group=dubbo}]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:265)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:120)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:100)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:175)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
] with root cause

org.apache.dubbo.remoting.RemotingException: org.apache.dubbo.remoting.RemotingException: Not found exported service: dubbo/com.star.dubboprovider.api.service.UserService:1.0.0:20880 in [org.apache.dubbo.monitor.MetricsService:20880], may be version or group mismatch , channel: consumer: /192.168.6.101:62499 --> provider: /192.168.6.101:20880, message:RpcInvocation [methodName=queryUser, parameterTypes=[class com.star.dubboprovider.api.dto.UserKeyDTO], arguments=[com.star.dubboprovider.api.dto.UserKeyDTO@140a8d08], attachments={input=361, path=com.star.dubboprovider.api.service.UserService, remote.application=dubbo-consumer, dubbo=2.0.2, interface=com.star.dubboprovider.api.service.UserService, version=1.0.0, group=dubbo}]
org.apache.dubbo.remoting.RemotingException: Not found exported service: dubbo/com.star.dubboprovider.api.service.UserService:1.0.0:20880 in [org.apache.dubbo.monitor.MetricsService:20880], may be version or group mismatch , channel: consumer: /192.168.6.101:62499 --> provider: /192.168.6.101:20880, message:RpcInvocation [methodName=queryUser, parameterTypes=[class com.star.dubboprovider.api.dto.UserKeyDTO], arguments=[com.star.dubboprovider.api.dto.UserKeyDTO@140a8d08], attachments={input=361, path=com.star.dubboprovider.api.service.UserService, remote.application=dubbo-consumer, dubbo=2.0.2, interface=com.star.dubboprovider.api.service.UserService, version=1.0.0, group=dubbo}]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:265)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:120)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:100)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:175)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.doReceived(DefaultFuture.java:212) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:175) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:163) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleResponse(HeaderExchangeHandler.java:60) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:181) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:93) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:179) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.rpc.protocol.AsyncToSyncInvoker.invoke(AsyncToSyncInvoker.java:61) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:78) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.monitor.dubbo.MetricsFilter.invoke(MetricsFilter.java:102) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:89) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:51) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:69) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:82) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:259) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:82) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:74) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.common.bytecode.proxy0.queryUser(proxy0.java) ~[dubbo-2.7.7.jar:2.7.7]
	at com.star.dubboconsumer.controller.DubboConsumerController.queryUserById(DubboConsumerController.java:25) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_211]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_211]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_211]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_211]


```

**Comment by Starbucksstar** [comment]
发现是项目中有zk的依赖和配置，会优先加载zk注册，去掉相关zk依赖和配置，nacos会将provider服务动态变化后的注册信息推送给consumer。
