### ISSUE TITLE
dubbo 2.7.5 no provider bug

### ISSUE THREAD

**Issue by envyer** [apache/dubbo#6292]
once you bootstrap application as a consumer side when service already registered on ZK, if you configurate a error consumer filter, you will get a no provider exception. The exception confuse developer.
RegistryDirectory class, line 438

**Comment by lebron374** [comment]
let us create pr

**Comment by lebron374** [comment]
can you provider some more detail info, what's the meaning of "configurate a error consumer filter"

**Comment by envyer** [comment]
e.g.
yml config
![image](https://user-images.githubusercontent.com/11310064/84463990-e3d21a00-aca5-11ea-973b-856706634f80.png)
META-INF/dubbo/org.apache.dubbo.rpc.filter
![image](https://user-images.githubusercontent.com/11310064/84464381-ea14c600-aca6-11ea-8c69-28eb28529450.png)
issue will reproduce when class not find

**Comment by manzhizhen** [comment]
let me see，I get it before

**Comment by manzhizhen** [comment]
[ERROR][2020-10-12 14:10:13.058+0800]  [DUBBO] Failed to refer invoker for interface:interface com.manzhizhen.dubbo.new1.api.DubboNew1RemoteService,url:(dubbo://172.23.161.103:12345/com.manzhizhen.dubbo.new1.api.DubboNew1RemoteService?anyhost=true&application=mzz-study-new2-server&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&init=false&interface=com.manzhizhen.dubbo.new1.api.DubboNew1RemoteService&metadata-type=remote&methods=queryInfo1,queryInfo2,queryInfo&pid=32403&reference.filter=DLConsumerFilter&register.ip=172.23.161.103&release=2.7.8&remote.application=mzz-study-dubbo-new1&revision=1.0.0_stable&side=consumer&sticky=false&timeout=1000&timestamp=1602482704202&token=d41f8160-12d7-47c1-8d2d-b8fe1a6e0733&version=1.0.0_stable)Failed to load extension class (interface: interface org.apache.dubbo.rpc.Filter, class line: com.mzz.filter.DLConsumerFilter) in file:/Users/didi/Documents/github/mzz-study/dubbo-study/dubbo-new2/dubbo-new2-server/target/classes/META-INF/dubbo/org.apache.dubbo.rpc.Filter, cause: com.mzz.filter.DLConsumerFilter, dubbo version: 2.7.8, current host: 172.23.161.103
java.lang.IllegalStateException: Failed to load extension class (interface: interface org.apache.dubbo.rpc.Filter, class line: com.mzz.filter.DLConsumerFilter) in file:/Users/didi/Documents/github/mzz-study/dubbo-study/dubbo-new2/dubbo-new2-server/target/classes/META-INF/dubbo/org.apache.dubbo.rpc.Filter, cause: com.mzz.filter.DLConsumerFilter
	at org.apache.dubbo.common.extension.ExtensionLoader.loadResource(ExtensionLoader.java:868)
	at org.apache.dubbo.common.extension.ExtensionLoader.loadDirectory(ExtensionLoader.java:836)
	at org.apache.dubbo.common.extension.ExtensionLoader.loadExtensionClasses(ExtensionLoader.java:777)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtensionClasses(ExtensionLoader.java:760)
	at org.apache.dubbo.common.extension.ExtensionLoader.getActivateExtension(ExtensionLoader.java:264)
	at org.apache.dubbo.common.extension.ExtensionLoader.getActivateExtension(ExtensionLoader.java:248)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.buildInvokerChain(ProtocolFilterWrapper.java:56)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:163)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:75)
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at org.apache.dubbo.registry.integration.RegistryDirectory.toInvokers(RegistryDirectory.java:455)
	at org.apache.dubbo.registry.integration.RegistryDirectory.refreshInvoker(RegistryDirectory.java:312)
	at org.apache.dubbo.registry.integration.RegistryDirectory.refreshOverrideAndInvoker(RegistryDirectory.java:271)
	at org.apache.dubbo.registry.integration.RegistryDirectory.notify(RegistryDirectory.java:254)
	at org.apache.dubbo.registry.support.AbstractRegistry.notify(AbstractRegistry.java:426)
	at org.apache.dubbo.registry.support.FailbackRegistry.doNotify(FailbackRegistry.java:407)
	at org.apache.dubbo.registry.support.FailbackRegistry.notify(FailbackRegistry.java:398)
	at org.apache.dubbo.registry.zookeeper.ZookeeperRegistry.doSubscribe(ZookeeperRegistry.java:181)
	at org.apache.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:333)
	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:105)
	at org.apache.dubbo.registry.integration.RegistryDirectory.subscribe(RegistryDirectory.java:185)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:469)
	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:454)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:72)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:161)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:73)
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:367)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:305)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:205)
	at org.apache.dubbo.config.spring.ReferenceBean.getObject(ReferenceBean.java:68)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:170)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1640)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:254)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:220)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1018)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:345)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:340)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1092)
	at com.manzhizhen.dubbo.new2.server.DubboNew2SpringMain.main(DubboNew2SpringMain.java:25)
Caused by: java.lang.ClassNotFoundException: com.mzz.filter.DLConsumerFilter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.dubbo.common.extension.ExtensionLoader.loadResource(ExtensionLoader.java:865)
	... 40 more

**Comment by manzhizhen** [comment]
this is dubbo 2.7.5 error info ：
[INFO][2020-10-13 11:13:45.268+0800]  [DUBBO] Unregister: consumer://172.23.161.79/com.manzhizhen.dubbo.new1.api.DubboNew1RemoteService?application=mzz-study-new2-server&category=consumers&check=false&dubbo=2.0.2&init=false&interface=com.manzhizhen.dubbo.new1.api.DubboNew1RemoteService&methods=queryInfo1,queryInfo2,queryInfo&pid=61137&reference.filter=DLConsumerFilter&release=2.7.5&revision=1.0.0_stable&side=consumer&sticky=false&timeout=1000&timestamp=1602558814363&version=1.0.0_stable, dubbo version: 2.7.5, current host: 172.23.161.79
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dubboNew1RemoteService': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: Failed to check the status of the service com.manzhizhen.dubbo.new1.api.DubboNew1RemoteService. No provider available for the service com.manzhizhen.dubbo.new1.api.DubboNew1RemoteService:1.0.0_stable from the url zookeeper://10.78.128.20:10010/org.apache.dubbo.registry.RegistryService?anyhost=true&application=mzz-study-new2-server&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&init=false&interface=com.manzhizhen.dubbo.new1.api.DubboNew1RemoteService&methods=queryInfo1,queryInfo2,queryInfo&pid=61137&reference.filter=DLConsumerFilter&register.ip=172.23.161.79&release=2.7.5&remote.application=mzz-study-dubbo-new1&revision=1.0.0_stable&side=consumer&sticky=false&timeout=1000&timestamp=1602558814363&token=b8fbb031-9116-4e2f-8843-6400bc325fd5&version=1.0.0_stable to the consumer 172.23.161.79 use dubbo version 2.7.5
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:177)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1640)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:254)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:220)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1018)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:345)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:340)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1092)
	at com.manzhizhen.dubbo.new2.server.DubboNew2SpringMain.main(DubboNew2SpringMain.java:25)
Caused by: java.lang.IllegalStateException: Failed to check the status of the service com.manzhizhen.dubbo.new1.api.DubboNew1RemoteService. No provider available for the service com.manzhizhen.dubbo.new1.api.DubboNew1RemoteService:1.0.0_stable from the url zookeeper://10.78.128.20:10010/org.apache.dubbo.registry.RegistryService?anyhost=true&application=mzz-study-new2-server&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&init=false&interface=com.manzhizhen.dubbo.new1.api.DubboNew1RemoteService&methods=queryInfo1,queryInfo2,queryInfo&pid=61137&reference.filter=DLConsumerFilter&register.ip=172.23.161.79&release=2.7.5&remote.application=mzz-study-dubbo-new1&revision=1.0.0_stable&side=consumer&sticky=false&timeout=1000&timestamp=1602558814363&token=b8fbb031-9116-4e2f-8843-6400bc325fd5&version=1.0.0_stable to the consumer 172.23.161.79 use dubbo version 2.7.5
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:355)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:266)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:151)
	at org.apache.dubbo.config.spring.ReferenceBean.getObject(ReferenceBean.java:68)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:170)

**Comment by manzhizhen** [comment]
> e.g.
> yml config
> ![image](https://user-images.githubusercontent.com/11310064/84463990-e3d21a00-aca5-11ea-973b-856706634f80.png)
> META-INF/dubbo/org.apache.dubbo.rpc.filter
> ![image](https://user-images.githubusercontent.com/11310064/84464381-ea14c600-aca6-11ea-8c69-28eb28529450.png)
> issue will reproduce when class not find

2.7.8 already fix this
