### ISSUE TITLE
all the time reconnect dubbo provider

### ISSUE THREAD

**Issue by debugsw** [apache/dubbo#6404]
* Dubbo version: 2.7.6
* Operating System version: centos 7.4
* Java version: 1.8

This 88.88.106.163:20880 is a service provider and has been offline from the Nacos registry, but consumers have been reconnecting with the provider. What is the problem?

The error report is as follows：

org.apache.dubbo.remoting.RemotingException: client(url: dubbo://88.88.106.163:20880/com.alibaba.cloud.dubbo.service.DubboMetadataService?anyhost=true&application=account-system-account-api&bind.ip=88.88.106.163&bind.port=20880&check=false&codec=dubbo&deprecated=false&dubbo=2.0.2&dynamic=true&generic=true&group=account-system-account-core-service&heartbeat=60000&interface=com.alibaba.cloud.dubbo.service.DubboMetadataService&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=100928&qos.enable=false&register.ip=88.88.16.88&release=2.7.6&remote.application=account-system-account-core-service&retries=0&revision=2.2.1.RELEASE&service.filter=-exception,defaultException&side=consumer&sticky=false&timeout=30000&timestamp=1593590233507&version=1.0.0) failed to connect to server /88.88.106.163:20880, error message is:Connection refused: /88.88.106.163:20880
	at org.apache.dubbo.remoting.transport.netty4.NettyClient.doConnect(NettyClient.java:169) ~[dubbo-2.7.6.jar!/:2.7.6]
	at org.apache.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:191) ~[dubbo-2.7.6.jar!/:2.7.6]
	at org.apache.dubbo.remoting.transport.AbstractClient.reconnect(AbstractClient.java:247) ~[dubbo-2.7.6.jar!/:2.7.6]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeClient.reconnect(HeaderExchangeClient.java:166) ~[dubbo-2.7.6.jar!/:2.7.6]
	at org.apache.dubbo.remoting.exchange.support.header.ReconnectTimerTask.doTask(ReconnectTimerTask.java:49) ~[dubbo-2.7.6.jar!/:2.7.6]
	at org.apache.dubbo.remoting.exchange.support.header.AbstractTimerTask.run(AbstractTimerTask.java:87) [dubbo-2.7.6.jar!/:2.7.6]
	at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:648) [dubbo-2.7.6.jar!/:2.7.6]
	at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:727) [dubbo-2.7.6.jar!/:2.7.6]
	at org.apache.dubbo.common.timer.HashedWheelTimer$Worker.run(HashedWheelTimer.java:449) [dubbo-2.7.6.jar!/:2.7.6]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /88.88.106.163:20880
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_102]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_102]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[netty-all-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-all-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702) ~[netty-all-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-all-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-all-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-all-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-all-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.45.Final.jar!/:4.1.45.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]

**Comment by YsoulM** [comment]
请问这个问题现在被修复了么？

**Comment by zrlw** [comment]
#8752
