### ISSUE TITLE
优雅滚动更新生产者(新IP已注册，老的IP已执行Unregister)后, 消费者依然调用生产者老的IP

### ISSUE THREAD

**Issue by zjwon** [apache/dubbo#6489]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: `2.7.3`
* Operating System version: `Centos 7`
* Java version: `1.8`
* Spring Boot version: `2.1.7.RELEASE`
* Spring Cloud version: `Greenwich.SR5`
* Nacos version: `1.3.1`
* Nacos集群、Dubbo生产者、Dubbo消费者均部署在K8s环境中

### Steps to reproduce this issue

1. 正常启动Nacos集群、生产者、消费者
2. 滚动更新生产者服务，确保新IP已注册，老的IP已执行Unregister
3. 查看消费者日志，出现异常。但是此时可以正常调用生产者服务

### Expected Result

- 消费者可以正常切换到生产者新的IP

### Actual Result

1. 正常启动Nacos集群、生产者、消费者
2. 滚动更新生产者服务，确保新IP已注册，老的IP已执行Unregister
- 新的IP已注册
![image](https://user-images.githubusercontent.com/12381829/87759110-505dad00-c840-11ea-8735-b16fd54403a4.png)

- 老的IP已执行Unregister
![image](https://user-images.githubusercontent.com/12381829/87759186-6ec3a880-c840-11ea-9b5d-daf69adcc6f3.png)
![image](https://user-images.githubusercontent.com/12381829/87759220-826f0f00-c840-11ea-955d-bf43525efb23.png)

3. 查看消费者日志，发现报错如下
![image](https://user-images.githubusercontent.com/12381829/87760083-d29aa100-c841-11ea-9484-7abfa754d824.png)
![image](https://user-images.githubusercontent.com/12381829/87760108-daf2dc00-c841-11ea-9df0-3e5303f17f25.png)
![image](https://user-images.githubusercontent.com/12381829/87760132-e6460780-c841-11ea-80b1-c8da2a5ca0d2.png)

4. 几分钟后，会循环打印下面截图所示错误日志
![image](https://user-images.githubusercontent.com/12381829/87760015-beef3a80-c841-11ea-952e-5701477bd81b.png)

If there is an exception, please attach the exception trace:

```
2020-07-17 14:48:09,908 [com.alibaba.nacos.naming.client.listener] ERROR [c.a.c.d.s.DubboMetadataServi
ceInvocationHandler] DubboMetadataServiceInvocationHandler.java:59 - [failed 5 times] Failed to invoke
 the method getExportedURLs in the service org.apache.dubbo.rpc.service.GenericService. Tried 3 times 
of the providers [172.30.2.17:20880] (1/1) from the registry localhost:9090 on the consumer 172.30.3.1
59 using the dubbo version 2.7.3. Last error is: Failed to invoke remote method: $invoke, provider: du
bbo://172.30.2.17:20880/com.alibaba.cloud.dubbo.service.DubboMetadataService?anyhost=true&application=
com-petkit-message-service&bind.ip=172.30.2.17&bind.port=20880&check=false&deprecated=false&dubbo=2.0.
2&dynamic=true&generic=true&group=com-petkit-sms-service&interface=com.alibaba.cloud.dubbo.service.Dub
boMetadataService&lazy=false&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllEx
portedURLs&pid=6&qos.enable=false&register=true&register.ip=172.30.3.159&release=2.7.3&remote.applicat
ion=com-petkit-sms-service&revision=2.1.1.RELEASE&side=consumer&sticky=false&timestamp=1594901114548&v
ersion=1.0.0, cause: message can not send, because channel is closed . url:dubbo://172.30.2.17:20880/c
om.alibaba.cloud.dubbo.service.DubboMetadataService?anyhost=true&application=com-petkit-message-servic
e&bind.ip=172.30.2.17&bind.port=20880&check=false&codec=dubbo&deprecated=false&dubbo=2.0.2&dynamic=tru
e&generic=true&group=com-petkit-sms-service&heartbeat=60000&interface=com.alibaba.cloud.dubbo.service.
DubboMetadataService&lazy=false&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAl
lExportedURLs&pid=6&qos.enable=false&register=true&register.ip=172.30.3.159&release=2.7.3&remote.appli
cation=com-petkit-sms-service&revision=2.1.1.RELEASE&side=consumer&sticky=false&timestamp=159490111454
8&version=1.0.0
org.apache.dubbo.rpc.RpcException: Failed to invoke the method getExportedURLs in the service org.apac
he.dubbo.rpc.service.GenericService. Tried 3 times of the providers [172.30.2.17:20880] (1/1) from the
 registry localhost:9090 on the consumer 172.30.3.159 using the dubbo version 2.7.3. Last error is: Fa
iled to invoke remote method: $invoke, provider: dubbo://172.30.2.17:20880/com.alibaba.cloud.dubbo.ser
vice.DubboMetadataService?anyhost=true&application=com-petkit-message-service&bind.ip=172.30.2.17&bind
.port=20880&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=true&group=com-petkit-sms-se
rvice&interface=com.alibaba.cloud.dubbo.service.DubboMetadataService&lazy=false&methods=getAllServiceK
eys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=6&qos.enable=false&register=true&reg
ister.ip=172.30.3.159&release=2.7.3&remote.application=com-petkit-sms-service&revision=2.1.1.RELEASE&s
ide=consumer&sticky=false&timestamp=1594901114548&version=1.0.0, cause: message can not send, because 
channel is closed . url:dubbo://172.30.2.17:20880/com.alibaba.cloud.dubbo.service.DubboMetadataService
?anyhost=true&application=com-petkit-message-service&bind.ip=172.30.2.17&bind.port=20880&check=false&c
odec=dubbo&deprecated=false&dubbo=2.0.2&dynamic=true&generic=true&group=com-petkit-sms-service&heartbe
at=60000&interface=com.alibaba.cloud.dubbo.service.DubboMetadataService&lazy=false&methods=getAllServi
ceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=6&qos.enable=false&register=true&
register.ip=172.30.3.159&release=2.7.3&remote.application=com-petkit-sms-service&revision=2.1.1.RELEAS
E&side=consumer&sticky=false&timestamp=1594901114548&version=1.0.0
        at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:113)
        at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:248)
        at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:78)
        at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:55)
        at org.apache.dubbo.common.bytecode.proxy6.$invoke(proxy6.java)
        at com.alibaba.cloud.dubbo.service.DubboMetadataServiceInvocationHandler.invoke(DubboMetadataServiceInvocationHandler.java:54)
        at com.sun.proxy.$Proxy138.getExportedURLs(Unknown Source)
        at com.alibaba.cloud.dubbo.registry.AbstractSpringCloudRegistry.getExportedURLs(AbstractSpringCloudRegistry.java:338)
        at com.alibaba.cloud.dubbo.registry.AbstractSpringCloudRegistry.subscribeDubboServiceURL(AbstractSpringCloudRegistry.java:272)
        at com.alibaba.cloud.dubbo.registry.AbstractSpringCloudRegistry$1.onApplicationEvent(AbstractSpringCloudRegistry.java:195)
        at com.alibaba.cloud.dubbo.registry.AbstractSpringCloudRegistry$1.onApplicationEvent(AbstractSpringCloudRegistry.java:188)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
        at com.alibaba.cloud.dubbo.autoconfigure.DubboServiceDiscoveryAutoConfiguration.dispatchServiceInstancesChangedEvent(DubboServiceDiscoveryAutoConfiguration.java:168)
        at com.alibaba.cloud.dubbo.autoconfigure.DubboServiceDiscoveryAutoConfiguration.access$200(DubboServiceDiscoveryAutoConfiguration.java:105)
        at com.alibaba.cloud.dubbo.autoconfigure.DubboServiceDiscoveryAutoConfiguration$NacosConfiguration.lambda$subscribeEventListener$1(DubboServiceDiscoveryAutoConfiguration.java:551)
        at com.alibaba.nacos.client.naming.core.EventDispatcher$Notifier.run(EventDispatcher.java:128)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.dubbo.remoting.RemotingException: message can not send, because channel is closed . url:dubbo://172.30.2.17:20880/com.alibaba.cloud.dubbo.service.DubboMetadataService?anyhost=true&application=com-petkit-message-service&bind.ip=172.30.2.17&bind.port=20880&check=false&codec=dubbo&deprecated=false&dubbo=2.0.2&dynamic=true&generic=true&group=com-petkit-sms-service&heartbeat=60000&interface=com.alibaba.cloud.dubbo.service.DubboMetadataService&lazy=false&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=6&qos.enable=false&register=true&register.ip=172.30.3.159&release=2.7.3&remote.application=com-petkit-sms-service&revision=2.1.1.RELEASE&side=consumer&sticky=false&timestamp=1594901114548&version=1.0.0
        at org.apache.dubbo.remoting.transport.AbstractClient.send(AbstractClient.java:175)
        at org.apache.dubbo.remoting.transport.AbstractPeer.send(AbstractPeer.java:53)
        at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeChannel.request(HeaderExchangeChannel.java:118)
        at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeClient.request(HeaderExchangeClient.java:84)
        at org.apache.dubbo.rpc.protocol.dubbo.ReferenceCountExchangeClient.request(ReferenceCountExchangeClient.java:80)
        at org.apache.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:97)
        at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:155)
        at org.apache.dubbo.rpc.protocol.AsyncToSyncInvoker.invoke(AsyncToSyncInvoker.java:52)
        at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:78)
        at org.apache.dubbo.rpc.filter.GenericImplFilter.invoke(GenericImplFilter.java:119)
        at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
        at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:92)
        at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
        at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:54)
        at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
        at org.apache.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:58)
        at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
        at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$CallbackRegistrationInvoker.invoke(ProtocolFilterWrapper.java:157)
        at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
        at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:82)
        ... 22 common frames omitted
2020-07-17 14:48:42,077 [dubbo-client-idleCheck-thread-1] INFO  [o.a.d.r.exchange.support.header.ReconnectTimerTask] ReconnectTimerTask.java:48 -  [DUBBO] Initial connection to HeaderExchangeClient [channel=org.apache.dubbo.remoting.transport.netty4.NettyClient [172.30.3.159:0 -> /172.30.2.17:20880]], dubbo version: 2.7.3, current host: 172.30.3.159
2020-07-17 14:48:45,084 [dubbo-client-idleCheck-thread-1] ERROR [o.a.d.r.exchange.support.header.ReconnectTimerTask] ReconnectTimerTask.java:51 -  [DUBBO] Fail to connect to HeaderExchangeClient [channel=org.apache.dubbo.remoting.transport.netty4.NettyClient [172.30.3.159:0 -> /172.30.2.17:20880]], dubbo version: 2.7.3, current host: 172.30.3.159
org.apache.dubbo.remoting.RemotingException: client(url: dubbo://172.30.2.17:20880/com.alibaba.cloud.dubbo.service.DubboMetadataService?anyhost=true&application=com-petkit-message-service&bind.ip=172.30.2.17&bind.port=20880&check=false&codec=dubbo&deprecated=false&dubbo=2.0.2&dynamic=true&generic=true&group=com-petkit-sms-service&heartbeat=60000&interface=com.alibaba.cloud.dubbo.service.DubboMetadataService&lazy=false&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=6&qos.enable=false&register=true&register.ip=172.30.3.159&release=2.7.3&remote.application=com-petkit-sms-service&revision=2.1.1.RELEASE&side=consumer&sticky=false&timestamp=1594901114548&version=1.0.0) failed to connect to server /172.30.2.17:20880 client-side timeout 3000ms (elapsed: 3002ms) from netty client 172.30.3.159 using dubbo version 2.7.3
        at org.apache.dubbo.remoting.transport.netty4.NettyClient.doConnect(NettyClient.java:171)
        at org.apache.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:190)
        at org.apache.dubbo.remoting.transport.AbstractClient.reconnect(AbstractClient.java:246)
        at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeClient.reconnect(HeaderExchangeClient.java:155)
        at org.apache.dubbo.remoting.exchange.support.header.ReconnectTimerTask.doTask(ReconnectTimerTask.java:49)
        at org.apache.dubbo.remoting.exchange.support.header.AbstractTimerTask.run(AbstractTimerTask.java:87)
        at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:648)
        at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:727)
        at org.apache.dubbo.common.timer.HashedWheelTimer$Worker.run(HashedWheelTimer.java:449)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by naturezhm** [comment]
我也遇到过类似的问题，不过没有用spring boot，只用了spring mvc
环境为：
Dubbo version:  `2.7.3`
Operating System version: `Centos 7.8`
Java version: `1.8.0251`
Nacos version: `1.3.1`
spring-mvc: `5.2.7`
nacos，provider ，consumer均部署在K8s环境中

**Comment by mercyblitz** [comment]
Please report this issue on https://github.com/alibaba/spring-cloud-alibaba/
