### ISSUE TITLE
com.alibaba.dubbo.common.utils.PojoUtils can not access a member of class com.ztjy.imbase.api.model.response.GetJoinGroupsResponse$Group with modifiers "public"

### ISSUE THREAD

**Issue by yanchunhuo** [apache/dubbo#6509]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.0
* Operating System version: CentOS 6.8
* Java version: 1.8.0_171

### Steps to reproduce this issue

1. Use generic invocation to call interfaces

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

call success 

### Actual Result

response error

If there is an exception, please attach the exception trace:

```
java.lang.RuntimeException: Class com.alibaba.dubbo.common.utils.PojoUtils can not access a member of class com.ztjy.imbase.api.model.response.GetJoinGroupsResponse$Group with modifiers "public"
	at com.alibaba.dubbo.common.utils.PojoUtils.generalize(PojoUtils.java:184)
	at com.alibaba.dubbo.common.utils.PojoUtils.generalize(PojoUtils.java:92)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:123)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:37)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:37)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:98)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:96)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:168)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:50)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:79)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Class com.alibaba.dubbo.common.utils.PojoUtils can not access a member of class com.ztjy.imbase.api.model.response.GetJoinGroupsResponse$Group with modifiers "public"
	at com.alibaba.dubbo.common.utils.PojoUtils.generalize(PojoUtils.java:164)
	at com.alibaba.dubbo.common.utils.PojoUtils.generalize(PojoUtils.java:143)
	at com.alibaba.dubbo.common.utils.PojoUtils.generalize(PojoUtils.java:181)
	... 15 more
Caused by: java.lang.IllegalAccessException: Class com.alibaba.dubbo.common.utils.PojoUtils can not access a member of class com.ztjy.imbase.api.model.response.GetJoinGroupsResponse$Group with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Method.invoke(Method.java:491)
	at com.alibaba.dubbo.common.utils.PojoUtils.generalize(PojoUtils.java:162)
	... 17 more

	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:113)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:248)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:78)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:55)
	at org.apache.dubbo.common.bytecode.proxy0.$invoke(proxy0.java)
	at com.tools.DubboClient.request(DubboClient.java:293)
	at com.tools.DubboClient.main(DubboClient.java:50)
Caused by: java.util.concurrent.ExecutionException: org.apache.dubbo.remoting.RemotingException: java.lang.RuntimeException: Class com.alibaba.dubbo.common.utils.PojoUtils can not access a member of class com.ztjy.imbase.api.model.response.GetJoinGroupsResponse$Group with modifiers "public"
java.lang.RuntimeException: Class com.alibaba.dubbo.common.utils.PojoUtils can not access a member of class com.ztjy.imbase.api.model.response.GetJoinGroupsResponse$Group with modifiers "public"
	at com.alibaba.dubbo.common.utils.PojoUtils.generalize(PojoUtils.java:184)
	at com.alibaba.dubbo.common.utils.PojoUtils.generalize(PojoUtils.java:92)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:123)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:37)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:37)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:98)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:96)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:168)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:50)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:79)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Class com.alibaba.dubbo.common.utils.PojoUtils can not access a member of class com.ztjy.imbase.api.model.response.GetJoinGroupsResponse$Group with modifiers "public"
	at com.alibaba.dubbo.common.utils.PojoUtils.generalize(PojoUtils.java:164)
	at com.alibaba.dubbo.common.utils.PojoUtils.generalize(PojoUtils.java:143)
	at com.alibaba.dubbo.common.utils.PojoUtils.generalize(PojoUtils.java:181)
	... 15 more
Caused by: java.lang.IllegalAccessException: Class com.alibaba.dubbo.common.utils.PojoUtils can not access a member of class com.ztjy.imbase.api.model.response.GetJoinGroupsResponse$Group with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Method.invoke(Method.java:491)
	at com.alibaba.dubbo.common.utils.PojoUtils.generalize(PojoUtils.java:162)
	... 17 more

	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.apache.dubbo.rpc.protocol.AsyncToSyncInvoker.invoke(AsyncToSyncInvoker.java:56)
	at org.apache.dubbo.rpc.filter.GenericImplFilter.invoke(GenericImplFilter.java:119)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:92)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:54)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:58)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$CallbackRegistrationInvoker.invoke(ProtocolFilterWrapper.java:157)
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:78)
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:82)
	... 6 more
Caused by: org.apache.dubbo.remoting.RemotingException: java.lang.RuntimeException: Class com.alibaba.dubbo.common.utils.PojoUtils can not access a member of class com.ztjy.imbase.api.model.response.GetJoinGroupsResponse$Group with modifiers "public"
java.lang.RuntimeException: Class com.alibaba.dubbo.common.utils.PojoUtils can not access a member of class com.ztjy.imbase.api.model.response.GetJoinGroupsResponse$Group with modifiers "public"
	at com.alibaba.dubbo.common.utils.PojoUtils.generalize(PojoUtils.java:184)
	at com.alibaba.dubbo.common.utils.PojoUtils.generalize(PojoUtils.java:92)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:123)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:37)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:37)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:98)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:96)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:168)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:50)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:79)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Class com.alibaba.dubbo.common.utils.PojoUtils can not access a member of class com.ztjy.imbase.api.model.response.GetJoinGroupsResponse$Group with modifiers "public"
	at com.alibaba.dubbo.common.utils.PojoUtils.generalize(PojoUtils.java:164)
	at com.alibaba.dubbo.common.utils.PojoUtils.generalize(PojoUtils.java:143)
	at com.alibaba.dubbo.common.utils.PojoUtils.generalize(PojoUtils.java:181)
	... 15 more
Caused by: java.lang.IllegalAccessException: Class com.alibaba.dubbo.common.utils.PojoUtils can not access a member of class com.ztjy.imbase.api.model.response.GetJoinGroupsResponse$Group with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Method.invoke(Method.java:491)
	at com.alibaba.dubbo.common.utils.PojoUtils.generalize(PojoUtils.java:162)
	... 17 more

	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.doReceived(DefaultFuture.java:191)
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:153)
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:141)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleResponse(HeaderExchangeHandler.java:62)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:199)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

the com.ztjy.imbase.api.model.response.GetJoinGroupsResponse$Group  source is:

```
public class GetJoinGroupsResponse extends YunCommunicationResponse
{
  private List<String> groupIds;

  @JSONField(name="GroupIdList")
  public List<Group> groupIdList;

  public GetJoinGroupsResponse(String actionStatus, String errorInfo)
  {
    super(actionStatus, errorInfo);
  }

  public GetJoinGroupsResponse() {
  }

  public static GetJoinGroupsResponse fail() {
    return new GetJoinGroupsResponse("FAIL", "未知错误");
  }

  private List<Group> getGroupIdList()
  {
    return this.groupIdList;
  }
  public void setGroupIdList(List<Group> groupIdList) {
    this.groupIdList = groupIdList;
  }

  public List<String> getGroupIds()
  {
    if (this.groupIds == null) {
      this.groupIds = new ArrayList();
      for (Group group : getGroupIdList()) {
        this.groupIds.add(group.getGroupId());
      }
    }
    return this.groupIds;
  }

  class Group
    implements Serializable
  {

    @JSONField(name="GroupId")
    private String groupId;

    Group()
    {
    }

    public String getGroupId()
    {
      return this.groupId;
    }
    public void setGroupId(String groupId) {
      this.groupId = groupId;
    }
  }
}
```

**Comment by yanchunhuo** [comment]
?

**Comment by helong2048** [comment]
use dubbo api reflect method can fix this problem

**Comment by CrazyHZM** [comment]
I have not received feedback for a long time, so I will close the issues temporarily. If there are any problems, I can open the issues at any time.
