### ISSUE TITLE
Dubbo  hessian协议的接口的mock服务降级

### ISSUE THREAD

**Issue by auroraMR921** [apache/dubbo#6516]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.0
* Operating System version: windows 10
* Java version: 1.8.1

### Steps to reproduce this issue

1. hessian协议的接口使用配置mock，comsumr端发生异常

2、下面是对应的（hessian协议）Mock配置
_@Service(version = "1.0.0", timeout = 10000, retries = 0, interfaceClass = LoadFileService.class,
        protocol = "hessian",
        mock = "com.dubbo.provider.service.file.LoadFileServiceMock")_
3. 下面是另一个接口（dubbo协议）的Mock配置
_@Service(version = "1.0.0", timeout = 10000, interfaceClass = DefectService.class, protocol = "dubbo", mock = "com.dubbo.provider.service.defect.DefectServiceMock")_

配置dubbo协议的接口能正常使用mock返回，但是hessian的方法的consumer端会发生下面的警告，而且hessian协议接口的方法超时也不能正常返回mock的内容

_com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method $echo in the service com.service.file.LoadFileService. Tried 3 times of the providers [169.254.126.158:20081] (1/1) from the registry 172.168.0.24:2181 on the consumer 169.254.126.158 using the dubbo version 2.6.0. Last error is: Failed to invoke remote proxy method $echo to hessian://169.254.126.158:20081/com.keystar.eprdms.service.file.LoadFileService?anyhost=true&application=consumer&check=false&dubbo=2.6.0&generic=false&interface=com.service.file.LoadFileService&methods=checkFileNameCriterion,generatePdfReport,checkDownloadFileCriterion,downloadReportPictures,downloadPreviewPicture,checkSingleFileNameCriterion,parallelDownloadPicture,uploadPicture,setThumbImageSize,deletePicture&mock=com.keystar.eprdms.dubbo.provider.service.file.LoadFileServiceMock&pid=15812&register.ip=169.254.126.158&remote.timestamp=1595574795792&revision=1.0.0&server=jetty&side=consumer&timeout=10000&timestamp=1595574818277&version=1.0.0, cause: Not found method "$echo" in class com.service.file.LoadFileService.
	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:101)
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:232)
	at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:80)
	at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:51)
	at com.alibaba.dubbo.common.bytecode.proxy5.$echo(proxy5.java)
	at com.alibaba.dubbo.spring.boot.health.DubboHealthIndicator.doHealthCheck(DubboHealthIndicator.java:29)
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:84)
	at org.springframework.boot.actuate.health.CompositeHealthIndicator.health(CompositeHealthIndicator.java:98)
	at org.springframework.boot.actuate.health.HealthEndpoint.health(HealthEndpoint.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:246)
	at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:76)
	at org.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:61)
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:126)
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:99)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.GeneratedMethodAccessor260.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.alibaba.dubbo.common.bytecode.NoSuchMethodException: Not found method "$echo" in class com.service.file.LoadFileService.
	at com.alibaba.dubbo.common.bytecode.Wrapper5.invokeMethod(Wrapper5.java)
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:45)
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invok_

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by chickenlj** [comment]
感谢关注，不过暂无计划支持其他协议的 mock 特性，因此只对 dubbo 工作
