### ISSUE TITLE
获取IP地址的方法不统一

### ISSUE THREAD

**Issue by caichy** [apache/dubbo#6540]
### Environment

* Dubbo version: 2.7.7
* Operating System version: linux
* Java version: 1.8

### Steps to reproduce this issue

ServiceConfig 中查找的IP可能不正确，导致服务注册的地址无效，
跟踪代码发现两处取IP方法不同：
- 服务注册时查找IP是在ServiceConfig.findConfigedHosts方法中，用的InetAddress.getLocalHost()
- logger中用的是NetUtils.getLocalHost()

**Comment by MessianicZZQ** [comment]
可以看到在NetUtils.getLocalHost()中，它是先用NetworkInterface来获取本地网卡的IP信息，获取不到再用InetAddress.getLocalHost()获取dns上的ip地址，不知道为啥这两处获取IP的规则不一致，但应该不会有问题。
能否打个日志出来看看NetUtils.getLocalHost()和InetAddress.getLocalHost()的具体获取到的IP是什么？

**Comment by soglad** [comment]
如果/etc/hosts里配置了对应hostname的IP，而这个IP和ifconfig获得IP不一致，就会看到不同的结果了。

**Comment by caob1234** [comment]
[06/08/20 23:32:07:867 UTC] main  INFO zookeeper.ZookeeperTransporter:  [DUBBO] find valid zookeeper client from the cache for address: zookeeper://127.0.0.1:2181/org.apache.dubbo.metadata.report.MetadataReport, dubbo version: 2.7.7, current host: 172.17.0.1
[06/08/20 23:32:07:957 UTC] main  INFO bootstrap.DubboBootstrap:  [DUBBO] DubboBootstrap has been initialized!, dubbo version: 2.7.7, current host: 172.17.0.1
[06/08/20 23:32:07:957 UTC] main  INFO bootstrap.DubboBootstrap:  [DUBBO] DubboBootstrap is starting..., dubbo version: 2.7.7, current host: 172.17.0.1
[06/08/20 23:32:08:094 UTC] main  INFO config.ServiceConfig:  [DUBBO] No valid ip found from environment, try to find valid host from DNS., dubbo version: 2.7.7, current host: 172.17.0.1
[06/08/20 23:32:08:097 UTC] main  WARN config.ServiceConfig:  [DUBBO] client-23-238-49-6.hostwindsdns.com: client-23-238-49-6.hostwindsdns.com: 未知的名称或服务, dubbo version: 2.7.7, current host: 172.17.0.1
java.net.UnknownHostException: client-23-238-49-6.hostwindsdns.com: client-23-238-49-6.hostwindsdns.com: 未知的名称或服务
	at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
	at org.apache.dubbo.config.ServiceConfig.findConfigedHosts(ServiceConfig.java:575)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:443)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:325)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:300)

**Comment by chickenlj** [comment]
Maybe we can cache the IP retrieved from `ServiceConfig.findConfigedHosts`  and use this IP in every place. I am not sure if this is necessary.

**Comment by guohao** [comment]
1. ServiceConfig 可能不存在，所以 consumer 侧的日志不能直接依赖 ServiceConfig 里面计算的 IP。
2. 计算 bind  IP 时  /etc/hosts 的优先级最高。

**Comment by caichy** [comment]
> 1. ServiceConfig 可能不存在，所以 consumer 侧的日志不能直接依赖 ServiceConfig 里面计算的 IP。
> 2. 计算 bind  IP 时  /etc/hosts 的优先级最高。

抱歉抱歉,，没有跟踪反馈细节，这个问题是要怎么解决呢？之前是发现logger里打印的IP是对的，而ServiceConfig获取的IP不对，机器有双网卡的时候，Provider端可能出现取的IP不对，注册之后无法提供服务。
