### ISSUE TITLE
dubbo2.7.6抛出异常must have a bug

### ISSUE THREAD

**Issue by JayeShen** [apache/dubbo#6567]
### Environment

* Dubbo version: 2.7.6
* Operating System version: linux
* Java version: 1.8

```log
2020-08-06 18:29:03.742 [org.apache.dubbo.rpc.protocol.dubbo.LazyConnectExchangeClient|]-[WARN] safe guard client , should not be called ,must have a bug.
java.lang.IllegalStateException: safe guard client , should not be called ,must have a bug.
	at org.apache.dubbo.rpc.protocol.dubbo.LazyConnectExchangeClient.warning(LazyConnectExchangeClient.java:138)
	at org.apache.dubbo.rpc.protocol.dubbo.LazyConnectExchangeClient.request(LazyConnectExchangeClient.java:127)
	at org.apache.dubbo.rpc.protocol.dubbo.ReferenceCountExchangeClient.request(ReferenceCountExchangeClient.java:91)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:100)
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:162)
	at org.apache.dubbo.rpc.protocol.AsyncToSyncInvoker.invoke(AsyncToSyncInvoker.java:52)
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:78)
	at com.guohualife.common.util.rpc.dubbo.filter.ClientTraceFilter.invoke(ClientTraceFilter.java:40)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:89)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:51)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:55)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:82)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:259)
	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:82)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:74)
	at org.apache.dubbo.common.bytecode.proxy0.updateCustomerInfo(proxy0.java)
	at sun.reflect.GeneratedMethodAccessor1709.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by chendifan** [comment]
同遇到

**Comment by chickenlj** [comment]
I am trying to look into this issue, can u provide any clue on how to reproduce this issue?

**Comment by tianshuang** [comment]
@chickenlj , same problem, this excepiton keeps appearing after upgrading from 2.7.2 to 2.7.6.

**Comment by tianshuang** [comment]
I see this warning in the log every time I publish the app.

**Comment by tianshuang** [comment]
Is it because the service is not offline normally? We have already used QOS to offline the service before publish.

**Comment by bigbenfather** [comment]
什么原因啊

**Comment by wikiwikiwiki** [comment]
#6959 里面修复了一下，@chickenlj 看看呢

**Comment by zcgewu** [comment]
还有多少坑，从2.7.0踩到2.7.6了
