### ISSUE TITLE
NPE may occur when calling AbstractDynamicConfiguration.execute()

### ISSUE THREAD

**Issue by likemoongg** [apache/dubbo#6575]
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: macOS Catalina
* Java version: 1.8

### Steps to reproduce this issue
`TreePathDynamicConfiguration#publishConfig` will call `AbstractDynamicConfiguration.execute()` to execute Callable and result type required `boolean`。execute() will return `null` when some Exception throw during execute Callable and then NPE will throw. Also `AbstractDynamicConfiguration#removeConfig` has the same problem.

```java
    public final boolean publishConfig(String key, String group, String content) {
        String pathKey = buildPathKey(group, key);
       // NPE may occur if execute(...) return null
        return execute(() -> doPublishConfig(pathKey, content), getDefaultTimeout());
    }
```

```java
    protected final <V> V execute(Callable<V> task, long timeout) {
        V value = null;
        try {
            if (timeout < 1) { // less or equal 0
                value = task.call();
            } else {
                Future<V> future = workersThreadPool.submit(task);
                value = future.get(timeout, TimeUnit.MILLISECONDS);
            }
        } catch (Exception e) {
           // will return null
            if (logger.isErrorEnabled()) {
                logger.error(e.getMessage(), e);
            }
        }
        return value;
    }
```

### Expected Result

`TreePathDynamicConfiguration#publishConfig` return  false when some Exception happened during execute Callable

### Actual Result

throw NPE

If there is an exception, please attach the exception trace:

```
Caused by: org.apache.zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth for /home/qianqian/dubbo/metadata
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:116)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:792)
	at org.apache.curator.framework.imps.CreateBuilderImpl$17.call(CreateBuilderImpl.java:1177)
	at org.apache.curator.framework.imps.CreateBuilderImpl$17.call(CreateBuilderImpl.java:1158)
	at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:64)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100)
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:1155)
	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:605)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:595)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:573)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:49)
	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.createPersistent(CuratorZookeeperClient.java:90)
	... 16 common frames omitted
java.lang.NullPointerException: null
	at org.apache.dubbo.common.config.configcenter.TreePathDynamicConfiguration.publishConfig(TreePathDynamicConfiguration.java:90)
	at org.apache.dubbo.metadata.report.support.ConfigCenterBasedMetadataReport.saveMetadata(ConfigCenterBasedMetadataReport.java:123)
	at org.apache.dubbo.metadata.report.support.ConfigCenterBasedMetadataReport.doStoreConsumerMetadata(ConfigCenterBasedMetadataReport.java:67)
	at org.apache.dubbo.metadata.report.support.AbstractMetadataReport.storeConsumerMetadataTask(AbstractMetadataReport.java:309)
	at org.apache.dubbo.metadata.report.support.AbstractMetadataReport.lambda$storeConsumerMetadata$1(AbstractMetadataReport.java:295)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by hzmartin** [comment]
i have two enironments, test and online, test zookeeper is standalone mode, and online is cluster mode, both have setacl for root node(/), below is my dubbo config
    <dubbo:application name="${dubbo.application.name}">
        <dubbo:parameter key="qos.enable" value="${dubbo.application.qos.enable}"/>
        <dubbo:parameter key="qos.accept.foreign.ip" value="false"/>
        <dubbo:parameter key="qos.port" value="${dubbo.application.qos.port}"/>
    </dubbo:application>

    <dubbo:registry client="curator" address="${dubbo.zk.address}" username="${dubbo.zk.username}" password="${dubbo.zk.password}"/>

    <dubbo:protocol name="${dubbo.protocol.name}" port="${dubbo.protocol.port}" threads="${dubbo.protocol.threads}"/>
    <dubbo:provider server="${dubbo.provider.server}" filter="${dubbo.provider.filter}" timeout="15000"/>
	
in my test enironment, the application works fine, but when i promote to online, the application reports error like below

java.lang.NullPointerException: null
        at org.apache.dubbo.common.config.configcenter.TreePathDynamicConfiguration.publishConfig(TreePathDynamicConfiguration.java:90)
        at org.apache.dubbo.metadata.report.support.ConfigCenterBasedMetadataReport.saveMetadata(ConfigCenterBasedMetadataReport.java:123)
        at org.apache.dubbo.metadata.report.support.ConfigCenterBasedMetadataReport.doStoreProviderMetadata(ConfigCenterBasedMetadataReport.java:62)
        at org.apache.dubbo.metadata.report.support.AbstractMetadataReport.storeProviderMetadataTask(AbstractMetadataReport.java:280)
        at org.apache.dubbo.metadata.report.support.AbstractMetadataReport.lambda$storeProviderMetadata$0(AbstractMetadataReport.java:267)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
		
[ERROR]2021-02-03 10:45:48.894 [DubboSaveMetadataReport-thread-1]ZookeeperDynamicConfiguration[106] |  [DUBBO] KeeperErrorCode = NoAuth for /dubbo/metadata, dubbo version: 2.7.8, current host: ****
java.lang.IllegalStateException: KeeperErrorCode = NoAuth for /dubbo/metadata
        at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.createPersistent(CuratorZookeeperClient.java:94)
        at org.apache.dubbo.remoting.zookeeper.support.AbstractZookeeperClient.create(AbstractZookeeperClient.java:89)
        at org.apache.dubbo.remoting.zookeeper.support.AbstractZookeeperClient.create(AbstractZookeeperClient.java:84)
        at org.apache.dubbo.remoting.zookeeper.support.AbstractZookeeperClient.create(AbstractZookeeperClient.java:84)
        at org.apache.dubbo.remoting.zookeeper.support.AbstractZookeeperClient.create(AbstractZookeeperClient.java:84)
        at org.apache.dubbo.remoting.zookeeper.support.AbstractZookeeperClient.create(AbstractZookeeperClient.java:84)
        at org.apache.dubbo.remoting.zookeeper.support.AbstractZookeeperClient.create(AbstractZookeeperClient.java:175)
        at org.apache.dubbo.configcenter.support.zookeeper.ZookeeperDynamicConfiguration.doPublishConfig(ZookeeperDynamicConfiguration.java:87)
        at org.apache.dubbo.common.config.configcenter.TreePathDynamicConfiguration.lambda$publishConfig$0(TreePathDynamicConfiguration.java:90)
        at org.apache.dubbo.common.config.configcenter.AbstractDynamicConfiguration.execute(AbstractDynamicConfiguration.java:208)
        at org.apache.dubbo.common.config.configcenter.TreePathDynamicConfiguration.publishConfig(TreePathDynamicConfiguration.java:90)
        at org.apache.dubbo.metadata.report.support.ConfigCenterBasedMetadataReport.saveMetadata(ConfigCenterBasedMetadataReport.java:123)
        at org.apache.dubbo.metadata.report.support.ConfigCenterBasedMetadataReport.doStoreProviderMetadata(ConfigCenterBasedMetadataReport.java:62)
        at org.apache.dubbo.metadata.report.support.AbstractMetadataReport.storeProviderMetadataTask(AbstractMetadataReport.java:280)
        at org.apache.dubbo.metadata.report.support.AbstractMetadataReport.lambda$storeProviderMetadata$0(AbstractMetadataReport.java:267)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth for /dubbo/metadata
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:113)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783)
        at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:740)
        at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:723)
        at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109)
        at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:720)
        at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:484)
        at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:474)
        at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:454)
        at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:44)
        at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.createPersistent(CuratorZookeeperClient.java:90)
        ... 17 common frames omitted


and I add config-center and metadata-report config as following, but it still doesn't work in online enironment
    <dubbo:config-center address="${dubbo.zk.address}" username="${dubbo.zk.username}" password="${dubbo.zk.password}">
    </dubbo:config-center>
    <dubbo:metadata-report  address="${dubbo.zk.address}" username="${dubbo.zk.username}" password="${dubbo.zk.password}"/>
	
test enironment always works fine, can any one give me some sugguestion? thanks

**Comment by AlbumenJ** [comment]
> test enironment always works fine, can any one give me some sugguestion? thanks

@hzmartin hi, would you please create a new issue to describe this with more detailed information ( such as env and version ) ?
