### ISSUE TITLE
Fail to connect to HeaderExchangeClient

### ISSUE THREAD

**Issue by yuezhenyu0208** [apache/dubbo#6627]
这个问题我本地也复现了
https://github.com/apache/dubbo/issues/5293

### Environment

* Dubbo version: 2.7.6
* Operating System version: ubuntu 20.04
* Java version: 1.8
* nacos 1.2.0
* spring cloud alibaba 2.2.1

### Steps to reproduce this issue

1. 启动provider 指定dubbo端口20880 
2. 启动consumer 服务正常
3. 关闭第一个provider 启动第二个provider 端口为20882
4. 观察consumer日志 一致在重连第一个已经关掉的provider

Pls. provide [GitHub address] to reproduce this issue.

```
2020-08-20 12:43:28.651   [dubbo-client-idleCheck-thread-1][] INFO  [Log4j2Logger.java:61] -  [DUBBO] Close netty channel [id: 0x47c86626, L:/192.168.17.238:43208 ! R:/192.168.17.238:20884], dubbo version: 2.7.6, current host: 10.8.0.38
2020-08-20 12:43:28.660   [dubbo-client-idleCheck-thread-1][] ERROR [Log4j2Logger.java:101] -  [DUBBO] Fail to connect to HeaderExchangeClient [channel=org.apache.dubbo.remoting.transport.netty4.NettyClient [/192.168.17.238:43208 -> /192.168.17.238:20884]], dubbo version: 2.7.6, current host: 10.8.0.38
org.apache.dubbo.remoting.RemotingException: client(url: dubbo://192.168.17.238:20884/com.dianfeng.cloud.live.api.service.live.AnchorService?anyhost=true&application=cloud-live-web&check=false&codec=dubbo&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&group=live-cloud-platform&heartbeat=60000&init=false&interface=com.dianfeng.cloud.live.api.service.live.AnchorService&logger=log4j2&methods=getAnchorInfo,loginOut,getLoginAnchorDto&pid=772755&qos.enable=false&register.ip=10.8.0.38&release=2.7.6&remote.application=cloud-live-service&revision=1.0.0&service.filter=dubboExceptionFilter,-exception&side=consumer&sticky=false&timeout=30000&timestamp=1597895120857&version=1.0.0) failed to connect to server /192.168.17.238:20884, error message is:拒绝连接: /192.168.17.238:20884
	at org.apache.dubbo.remoting.transport.netty4.NettyClient.doConnect(NettyClient.java:169)
	at org.apache.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:191)
	at org.apache.dubbo.remoting.transport.AbstractClient.reconnect(AbstractClient.java:247)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeClient.reconnect(HeaderExchangeClient.java:166)
	at org.apache.dubbo.remoting.exchange.support.header.ReconnectTimerTask.doTask(ReconnectTimerTask.java:49)
	at org.apache.dubbo.remoting.exchange.support.header.AbstractTimerTask.run(AbstractTimerTask.java:87)
	at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:648)
	at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:727)
	at org.apache.dubbo.common.timer.HashedWheelTimer$Worker.run(HashedWheelTimer.java:449)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: 拒绝连接: /192.168.17.238:20884
Caused by: java.net.ConnectException: 拒绝连接
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2020-08-20 12:43:29.714   [com.alibaba.nacos.naming.client.listener][] INFO  [DubboServiceDiscoveryAutoConfiguration.java:164] - The event of the service instances[name : cloud-live-service , size : 1] change is about to be dispatched
移出urldubbo://10.8.0.38:20885/com.alibaba.cloud.dubbo.service.DubboMetadataService?anyhost=true&application=cloud-live-service&bind.ip=10.8.0.38&bind.port=20885&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&group=cloud-live-service&interface=com.alibaba.cloud.dubbo.service.DubboMetadataService&logger=log4j2&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=776221&qos.enable=false&release=2.7.6&revision=2.2.1.RELEASE&service.filter=dubboExceptionFilter,-exception&side=provider&timestamp=1597898608638&version=1.0.0
exchangeClientsnull

```

**Comment by yuezhenyu0208** [comment]
这个重连能不能有个次数限制，不要一直重连下去

**Comment by AlbumenJ** [comment]
如果可以的话，请问能否给出具体的测试用例以方便复现。
另外在注册中心移除地址之后还会继续重连吗？

**Comment by wghdir** [comment]
我这也出现了，不知道原因。(Dubbo version: 2.7.6,docker部署的应用)
00:56:55.114 [dubbo-client-idleCheck-thread-1] ERROR o.a.d.r.e.s.h.ReconnectTimerTask - [doTask,51] -  [DUBBO] Fail to connect to HeaderExchangeClient [channel=org.apache.dubbo.remoting.transport.netty4.NettyClient [/10.10.0.81:55314 -> /10.10.0.75:20880]], dubbo version: 2.7.6, current host: 172.19.0.3,
org.apache.dubbo.remoting.RemotingException: client(url: dubbo://10.10.0.75:20880/com.alibaba.cloud.dubbo.service.DubboMetadataService?anyhost=true&application=by-pay-app&bind.ip=10.10.0.75&bind.port=20880&check=false&codec=dubbo&deprecated=false&dubbo=2.0.2&dynamic=true&generic=true&group=by-pay-service&heartbeat=60000&interface=com.alibaba.cloud.dubbo.service.DubboMetadataService&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=1&qos.enable=false&register.ip=172.19.0.3&release=2.7.6&remote.application=by-pay-service&revision=2.2.1.RELEASE&side=consumer&sticky=false&timestamp=1597978981938&version=1.0.0) failed to connect to server /10.10.0.75:20880 client-side timeout 3000ms (elapsed: 3000ms) from netty client 172.19.0.3 using dubbo version 2.7.6,
	at org.apache.dubbo.remoting.transport.netty4.NettyClient.doConnect(NettyClient.java:174),
	at org.apache.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:191),
	at org.apache.dubbo.remoting.transport.AbstractClient.reconnect(AbstractClient.java:247),
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeClient.reconnect(HeaderExchangeClient.java:166),
	at org.apache.dubbo.remoting.exchange.support.header.ReconnectTimerTask.doTask(ReconnectTimerTask.java:49),
	at org.apache.dubbo.remoting.exchange.support.header.AbstractTimerTask.run(AbstractTimerTask.java:87),
	at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:648),
	at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:727),
	at org.apache.dubbo.common.timer.HashedWheelTimer$Worker.run(HashedWheelTimer.java:449),
	at java.lang.Thread.run(Unknown Source),

**Comment by horizonzy** [comment]
@AlbumenJ 我这边也发现了相同的问题。dubbo2.7.2。用的zk当注册中心。provider容器部署，provider重新发布之后consumer这边感知到了zk上providers的节点变化。和新的provider建立了连接（通过netstat确认）。但是HeaderExchangeClient的reconnectTask一直在执行报错。按照我的想法，consumer端收到了zk的节点通知，应该会销毁老的invoker,在销毁过程中,reconnectTask应该就会被取消掉。不知道这个问题是因为没有销毁老的invoker，还是在销毁老的invoker时取消重连任务失败导致的。
ps:当时发生这个问题时，消费者有10台左右，就只有一台出现了这个问题。之前遇到过有人反馈这个问题吗

**Comment by Themis2017** [comment]
@wghdir  同样的问题，你解决了没？

**Comment by horizonzy** [comment]
> @wghdir 同样的问题，你解决了没？

你那边发生这种情况的时候，是不是服务在上下线的同时，切换了动态配置。

**Comment by Themis2017** [comment]
> > @wghdir 同样的问题，你解决了没？
> 
> 你那边发生这种情况的时候，是不是服务在上下线的同时，切换了动态配置。

配置没变，就是服务上下线的时候会出现，而且还不是必现。

**Comment by horizonzy** [comment]
> > > @wghdir 同样的问题，你解决了没？
> > 
> > 
> > 你那边发生这种情况的时候，是不是服务在上下线的同时，切换了动态配置。
> 
> 配置没变，就是服务上下线的时候会出现，而且还不是必现。

你那边这个重新连接的日志不会一直刷吧，是不是就那么几条

**Comment by hao031410** [comment]
我也出现了，而且不是服务提供的所有接口，特定的一两个接口，不停的刷。。

**Comment by vio-lin** [comment]
我遇到了差不多同样的问题，我尝试重现了下。
1. 请求已经经过了选址，到负载均衡及其后面的逻辑 卡主这个请求
2. 客户端收到服务端拉出的消息，并且尝试销毁invoker 
3. invoker销毁之后，放掉前面在负载均衡的请求，它触发建立Channel 
4. 因为服务端的ip还能ping 通，chananle建立定时任务去重连
5. 因为前面invoker已经被销毁，不会有人来destry这个channel，陷入循环。

**Comment by vio-lin** [comment]
大家都想怎么去解决呢，公司换了动态Ip之后 这个问题更严重了。

**Comment by spilledyear** [comment]
> 我遇到了差不多同样的问题，我尝试重现了下。
> 
> 1. 请求已经经过了选址，到负载均衡及其后面的逻辑 卡主这个请求
> 2. 客户端收到服务端拉出的消息，并且尝试销毁invoker
> 3. invoker销毁之后，放掉前面在负载均衡的请求，它触发建立Channel
> 4. 因为服务端的ip还能ping 通，chananle建立定时任务去重连
> 5. 因为前面invoker已经被销毁，不会有人来destry这个channel，陷入循环。

看代码没有发现你说的这个逻辑啊

**Comment by vio-lin** [comment]
> > 我遇到了差不多同样的问题，我尝试重现了下。
> > 
> > 1. 请求已经经过了选址，到负载均衡及其后面的逻辑 卡主这个请求
> > 2. 客户端收到服务端拉出的消息，并且尝试销毁invoker
> > 3. invoker销毁之后，放掉前面在负载均衡的请求，它触发建立Channel
> > 4. 因为服务端的ip还能ping 通，chananle建立定时任务去重连
> > 5. 因为前面invoker已经被销毁，不会有人来destry这个channel，陷入循环。
> 
> 看代码没有发现你说的这个逻辑啊， 我用你的方法试了下， 消费端报错 message can not send, because channel is closed

少说了一个东西，客户端有使用lazy这个参数吗。假如有的话发送的时候会建立一次连接。

**Comment by spilledyear** [comment]
@vio-lin 
没有使用lazy参数， 我加上了各种关闭时的日志，发现在destroy invoke的时候， ReferenceCountExchangeClient 中的 referenceCount > 0，最终导致定时任务没有关闭，不知道为啥会出现这种情况

**Comment by JiangHaonan** [comment]
@vio-lin 老哥，这个问题后来解决了吗？请教一下

**Comment by vio-lin** [comment]
> @vio-lin 老哥，这个问题后来解决了吗？请教一下
报错太多了，改了task的报错逻辑。状态改变的时候打印报错。
因为本身是hashwheel 不会导致开很多线程 后面就没有管理了。

**Comment by coderliguoqing** [comment]
> 如果可以的话，请问能否给出具体的测试用例以方便复现。 另外在注册中心移除地址之后还会继续重连吗？

注册中心没有地址一样会继续重连下去的

**Comment by AlbumenJ** [comment]
> > 如果可以的话，请问能否给出具体的测试用例以方便复现。 另外在注册中心移除地址之后还会继续重连吗？
> 
> 注册中心没有地址一样会继续重连下去的

升级到 3.1.4 版本看一下还有没有问题

可能与 https://github.com/apache/dubbo/issues/8752#issuecomment-1313479077 有关

**Comment by hesy007** [comment]
请问在 2.7.x 版本有没有修复这个问题 @AlbumenJ
