### ISSUE TITLE
spring2.5版本整合dubbo2.6.x版本错误：java.lang.NoClassDefFoundError: org/springframework/beans/factory/NoUniqueBeanDefinitionException

### ISSUE THREAD

**Issue by laxhcxh** [apache/dubbo#6668]
具体日志为：
Caused By: java.lang.NoClassDefFoundError: org/springframework/beans/factory/NoUniqueBeanDefinitionException
        at com.alibaba.dubbo.config.spring.ReferenceBean.setApplicationContext(ReferenceBean.java:62)
        at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:70)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:350)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1331)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:473)
        Truncated. see log file for complete stacktrace

**Comment by zhuyulan** [comment]
解决了？同求

**Comment by htynkn** [comment]
spring版本太低，NoUniqueBeanDefinitionException应该是2013年的时候在3.X版本引入的

**Comment by laxhcxh** [comment]
@zhuyulan  可以试着在项目中增加spring-bean的4.1.6以上版本的jar包；若是还有有问题只能调整源码中的spring依赖版本，重新打包。
