### ISSUE TITLE
generic invoke error when parameter is org.apache.dubbo.common.URL

### ISSUE THREAD

**Issue by horizonzy** [apache/dubbo#6686]
### Steps to reproduce this issue

1. def a method with param (org.apache.dubbo.common.URL)
2. invoke this method by generic

If there is an exception, please attach the exception trace:

Exception in thread "main" java.lang.RuntimeException: Failed to set pojo URL property serviceInterface value xxx(class java.lang.String), cause: null
	at org.apache.dubbo.common.utils.PojoUtils.realize0(PojoUtils.java:488)
	at org.apache.dubbo.common.utils.PojoUtils.realize(PojoUtils.java:207)
	at org.apache.dubbo.common.URL.main(URL.java:330)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.dubbo.common.utils.PojoUtils.realize0(PojoUtils.java:483)
	... 2 more
Caused by: java.lang.NullPointerException
	at org.apache.dubbo.common.URL.addParameter(URL.java:1146)
	at org.apache.dubbo.common.URL.setServiceInterface(URL.java:1563)
	... 7 more

**Comment by manzhizhen** [comment]
Please tell me which dubbo version you using?

**Comment by horizonzy** [comment]
2.7.2。the reason is the URL designed nonstandard, it's protect construcor exist problem. if we use it as generic invoke param. when providers received param.  PojoUtils.realize param. the error will occur.
