### ISSUE TITLE
2.7.8 Invalid token 

### ISSUE THREAD

**Issue by mestarshine** [apache/dubbo#6707]
消费者版本 2.7.8服务提供这2.7 以下的版本时会报：Invalid token!
把消费者回退到2.6.9 问题就存在了

### Environment

* Dubbo version: 2.7.8
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue

1. 服务提供者2.7.x 以下版本，服务开启token 认证
2. 2.7.8 作为消费者调该服务及可重新
3. 服务消费者降到2.7.x 问题不存在

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
com.alibaba.dubbo.rpc.RpcException: Invalid token! Forbid invoke remote service interface com.xxxxx method xxxMethod() from consumer 192.168.1.24 to provider 192.168.1.215
	at com.alibaba.dubbo.rpc.filter.TokenFilter.invoke(TokenFilter.java:46)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:60)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:112)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:108)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:84)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:170)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
	at com.alibaba.dubbo.remoting.transport.dispather.ChannelEventRunnable.run(ChannelEventRunnable.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by puzeyu** [comment]
这个是因为版本升级导致的吧

**Comment by mestarshine** [comment]
是的，升级时新旧版本同时存在发现的，旧服务版本比较低使用的2.7.x以下的版本提供服务并开启了token，当时使用2.7.x的版本调用服务时就会出现上面的错误

**Comment by manzhizhen** [comment]
let me have a look

**Comment by manzhizhen** [comment]
> 这个是因为版本升级导致的吧

Who's your picture?

**Comment by manzhizhen** [comment]
> 这个是因为版本升级导致的吧

Who's your picture?

**Comment by manzhizhen** [comment]
I use 2.7.6 as provider, 2.7.8 as consumer and open token check，but I see invoke sucess，you said  "服务提供者2.7.x 以下版本，服务开启token 认证" is which version ?

**Comment by mestarshine** [comment]
> I use 2.7.6 as provider, 2.7.8 as consumer and open token check，but I see invoke sucess，you said "服务提供者2.7.x 以下版本，服务开启token 认证" is which version ?
在2.4.7及2.6.9都存在

**Comment by mestarshine** [comment]
> I use 2.7.6 as provider, 2.7.8 as consumer and open token check，but I see invoke sucess，you said "服务提供者2.7.x 以下版本，服务开启token 认证" is which version ?

在2.4.7中发现，使用2.6.9进行验证发现也存在该问题
