### ISSUE TITLE
Close jedis connection twice when using redis subscribed to a pattern.

### ISSUE THREAD

**Issue by UltimateRedx** [apache/dubbo#6721]
### Environment

* Dubbo version: 2.7.8-release
* Operating System version: windows 10
* Java version: 8u_211
* Jedis version: 2.10.2

### Steps to reproduce this issue

1. Configre Dubbo with redis:
```properties
dubbo.application.name=gtm-super-admin
dubbo.registry.address=redis://root:pass@127.0.0.1:6379
dubbo.registry.register=true
```
With `@EnableDubbo` annotated.
2. Start application.
3. Shut down application.

### Expected Result
No exception thrown when shuting down.

### Actual Result
Exception actually thrown:
```java
[DUBBO] Failed to subscribe service from redis registry. registry: 127.0.0.1:6379, cause: java.net.SocketException: Socket is closed, dubbo version: 2.7.8, current host: <my host>

redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Socket is closed
	at redis.clients.jedis.Connection.rollbackTimeout(Connection.java:108) ~[jedis-2.10.2.jar:na]
	at redis.clients.jedis.Jedis.psubscribe(Jedis.java:2832) ~[jedis-2.10.2.jar:na]
	at org.apache.dubbo.registry.redis.RedisRegistry$Notifier.run(RedisRegistry.java:627) ~[dubbo-2.7.8.jar:2.7.8]
Caused by: java.net.SocketException: Socket is closed
	at java.net.Socket.setSoTimeout(Socket.java:1137) ~[na:1.8.0_211]
	at redis.clients.jedis.Connection.rollbackTimeout(Connection.java:105) ~[jedis-2.10.2.jar:na]
	... 2 common frames omitted
```

Code in [RedisRegistry](https://github.com/apache/dubbo/blob/2.7.8-release/dubbo-registry/dubbo-registry-redis/src/main/java/org/apache/dubbo/registry/redis/RedisRegistry.java):
```java
@Override
    public void destroy() {
      //...
        try {
            for (Notifier notifier : notifiers.values()) {
                notifier.shutdown();                //*
            }
        } catch (Throwable t) {
            logger.warn(t.getMessage(), t);
        }
       //...
    }
private class Notifier extends Thread {
    @Override
    public void run() {
        try{
            jedis.psubscribe(new NotifySub(jedisPool), service);  //**  Code from L620
        } finally {
            jedis.close();
        }
    }

    public void shutdown() {
        try {
            running = false;
            jedis.disconnect();  //*
        } catch (Throwable t) {
            logger.warn(t.getMessage(), t);
        }
    }

}
```
I think the problem is, when shuting down,  `destory` called then at `*` jedis connections are all closed. Then the jedis connection of subscribe thread disconnect from `psubscribe` and calls `close` another time caused the exception above.

**Comment by xiaoheng1** [comment]
Can you provide the steps to reproduce the problem？
