### ISSUE TITLE
NPE in org.apache.dubbo.registry.client.InstanceAddressURL#addConsumerParams

### ISSUE THREAD

**Issue by horizonzy** [apache/dubbo#6757]
### Environment

* Dubbo version: master branch update-to-date commit a5685180
* Operating System version: macOs
* Java version: jdk8

### Steps to reproduce this issue
1. run the dubbo-demo-xml provider and consumer
2.execute a rpc request

### Expected Result
execute a rpc request without error

### Actual Result

What actually happens?
![image](https://user-images.githubusercontent.com/22524871/93424855-73ade280-f8eb-11ea-8db2-41dde9c7bee8.png)
![image](https://user-images.githubusercontent.com/22524871/93424891-858f8580-f8eb-11ea-8b91-661eb8dc52c7.png)

`Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoService': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:176)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:101)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1827)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1265)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:261)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1115)
	at org.apache.dubbo.demo.consumer.Application.main(Application.java:34)
Caused by: java.lang.NullPointerException
	at org.apache.dubbo.registry.client.InstanceAddressURL.addConsumerParams(InstanceAddressURL.java:284)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.toInvokers(ServiceDiscoveryRegistryDirectory.java:157)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.refreshInvoker(ServiceDiscoveryRegistryDirectory.java:109)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.notify(ServiceDiscoveryRegistryDirectory.java:89)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.lambda$notifyAddressChanged$3(ServiceInstancesChangedListener.java:182)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.notifyAddressChanged(ServiceInstancesChangedListener.java:180)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.onEvent(ServiceInstancesChangedListener.java:145)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.lambda$subscribeURLs$3(ServiceDiscoveryRegistry.java:323)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribeURLs(ServiceDiscoveryRegistry.java:321)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.doSubscribe(ServiceDiscoveryRegistry.java:266)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribe(ServiceDiscoveryRegistry.java:255)
	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:105)
	at org.apache.dubbo.registry.integration.DynamicDirectory.subscribe(DynamicDirectory.java:137)
	at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getServiceDiscoveryInvoker(InterfaceCompatibleRegistryProtocol.java:93)
	at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.doRefer(InterfaceCompatibleRegistryProtocol.java:71)
	at org.apache.dubbo.registry.client.RegistryProtocol.refer(RegistryProtocol.java:452)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:72)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:161)
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:366)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:304)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:204)
	at org.apache.dubbo.config.spring.ReferenceBean.getObject(ReferenceBean.java:68)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:169)
	... 7 more`

**Comment by Leedding** [comment]
I have report a same issue and pull a request
https://github.com/apache/dubbo/pull/6748
Could you help me review the code and if it's right ?

**Comment by horizonzy** [comment]
> I have report a same issue and pull a request
> #6748
> Could you help me review the code and if it's right ?

sorry, I didn't read the master's update-to-date code, I'm not sure I can help you
