### ISSUE TITLE
dubbo2.6.x以上版本javassist无法动态加载class

### ISSUE THREAD

**Issue by zhaozengbin** [apache/dubbo#6769]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.0及以上
* Operating System version: mac
* Java version: 1.8

### Steps to reproduce this issue

1. 2.5.3版本通过javassist动态加载class，没有任何问题
2. 2.6.0及以上版本通过javassist加载class，在idea内启动项目没有问题，但是通过springboot java -jar启动后会报javassist.NotFoundException异常。

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result
Caused by: javassist.NotFoundException: com.alibaba.dubbo.common.bytecode.Wrapper
	at javassist.ClassPool.get(ClassPool.java:452)
	at com.alibaba.dubbo.common.bytecode.ClassGenerator.toClass(ClassGenerator.java:263)

What do you expected from the above steps？

### Actual Result
无法正常加载业务class
What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issues
