### ISSUE TITLE
No provider available in 

### ISSUE THREAD

**Issue by ruijing** [apache/dubbo#6813]
Errors occur occasionally

No provider available in [invoker :interface rose.gen.api.com.chaoxing.statistics.service.IStatisticsDeleteServiceSVC -> zookeeper://10.0.xx.xx:9688/com.alibaba.dubbo.registry.RegistryService?application=educate-task-consumer&default.check=false&default.group=mooc-thor&default.loadbalance=roundrobin&default.retries=2&dubbo=2.0.1&interface=rose.gen.api.com.chaoxing.statistics.service.IStatisticsDeleteServiceSVC&methods=removeCourseByCourseId,removeTeacherById,removeClazzByClazzId,removeStudentClazz,removeClazzByCourseId,removeCourseById,removeClazzById,removeTeacherClazzById,removeStudentClazzByPersonIdAndClazzId,removeTeacherCourseById,removeTeacherClazzByPersonIdAndClazzId&pid=7&register.ip=172.30.69.7&revision=0.0.1-SNAPSHOT&side=consumer&timestamp=1602649000213,directory: com.alibaba.dubbo.registry.integration.RegistryDirectory@67599bae, invoker :interface rose.gen.api.com.chaoxing.statistics.service.IStatisticsDeleteServiceSVC -> zookeeper://10.0.xx.xx:9688/com.alibaba.dubbo.registry.RegistryService?application=educate-task-consumer&default.check=false&default.group=mooc-thor&default.loadbalance=roundrobin&default.retries=2&dubbo=2.0.1&interface=rose.gen.api.com.chaoxing.statistics.service.IStatisticsDeleteServiceSVC&methods=removeCourseByCourseId,removeTeacherById,removeClazzByClazzId,removeStudentClazz,removeClazzByCourseId,removeCourseById,removeClazzById,removeTeacherClazzById,removeStudentClazzByPersonIdAndClazzId,removeTeacherCourseById,removeTeacherClazzByPersonIdAndClazzId&pid=7&register.ip=172.30.69.7&revision=0.0.1-SNAPSHOT&side=consumer&timestamp=1602649000213,directory: com.alibaba.dubbo.registry.integration.RegistryDirectory@199d1fb7] com.alibaba.dubbo.rpc.RpcException: No provider available in [invoker :interface rose.gen.api.com.chaoxing.statistics.service.IStatisticsDeleteServiceSVC -> zookeeper://10.0.xx.xx:9688/com.alibaba.dubbo.registry.RegistryService?application=educate-task-consumer&default.check=false&default.group=mooc-thor&default.loadbalance=roundrobin&default.retries=2&dubbo=2.0.1&interface=rose.gen.api.com.chaoxing.statistics.service.IStatisticsDeleteServiceSVC&methods=removeCourseByCourseId,removeTeacherById,removeClazzByClazzId,removeStudentClazz,removeClazzByCourseId,removeCourseById,removeClazzById,removeTeacherClazzById,removeStudentClazzByPersonIdAndClazzId,removeTeacherCourseById,removeTeacherClazzByPersonIdAndClazzId&pid=7&register.ip=172.30.69.7&revision=0.0.1-SNAPSHOT&side=consumer&timestamp=1602649000213,directory: com.alibaba.dubbo.registry.integration.RegistryDirectory@67599bae, invoker :interface rose.gen.api.com.chaoxing.statistics.service.IStatisticsDeleteServiceSVC -> zookeeper://10.0.xx.xx:9688/com.alibaba.dubbo.registry.RegistryService?application=educate-task-consumer&default.check=false&default.group=mooc-thor&default.loadbalance=roundrobin&default.retries=2&dubbo=2.0.1&interface=rose.gen.api.com.chaoxing.statistics.service.IStatisticsDeleteServiceSVC&methods=removeCourseByCourseId,removeTeacherById,removeClazzByClazzId,removeStudentClazz,removeClazzByCourseId,removeCourseById,removeClazzById,removeTeacherClazzById,removeStudentClazzByPersonIdAndClazzId,removeTeacherCourseById,removeTeacherClazzByPersonIdAndClazzId&pid=7&register.ip=172.30.69.7&revision=0.0.1-SNAPSHOT&side=consumer&timestamp=1602649000213,directory: com.alibaba.dubbo.registry.integration.RegistryDirectory@199d1fb7]	at com.alibaba.dubbo.rpc.cluster.support.AvailableCluster$1.doInvoke(AvailableCluster.java:46)	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:232)	at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:70)	at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:51)	at com.alibaba.dubbo.common.bytecode.proxy35.removeTeacherCourseById(proxy35.java)	at sun.reflect.GeneratedMethodAccessor772.invoke(Unknown Source)	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	at java.lang.reflect.Method.invoke(Method.java:498)	at net.paoding.rose.jade.statement.JavaMethodStatement.realExecute(JavaMethodStatement.java:28)	at net.paoding.rose.jade.statement.TopLevelStatement.execute(TopLevelStatement.java:23)	at net.paoding.rose.jade.statement.JavaMethodStatement.execute(JavaMethodStatement.java:1)	at net.paoding.rose.jade.statement.cached.CachedStatement.execute(CachedStatement.java:96)	at net.paoding.rose.jade.context.JavaJadeInvocationHandler.jadeInvoke(JavaJadeInvocationHandler.java:121)	at net.paoding.rose.jade.context.JavaJadeInvocationHandler.intercept(JavaJadeInvocationHandler.java:69)	at rose.gen.api.com.chaoxing.statistics.service.IStatisticsDeleteServiceSVC$$EnhancerByCGLIB$$a37bb4ca.removeTeacherCourseById(<generated>)	at com.chaoxing.statistics.service.RealTimeTeacherCourseStatisticsService.delete(RealTimeTeacherCourseStatisticsService.java:189)	at com.chaoxing.statistics.service.RealTimeTeacherCourseStatisticsService.deleteTeacherCourseData(RealTimeTeacherCourseStatisticsService.java:171)	at com.chaoxing.statistics.service.RealTimeTeacherCourseStatisticsService$$FastClassBySpringCGLIB$$b1dbc020.invoke(<generated>)	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)	at com.chaoxing.statistics.service.RealTimeTeacherCourseStatisticsService$$EnhancerBySpringCGLIB$$90d8bc1.deleteTeacherCourseData(<generated>)	at com.chaoxing.statistics.service.TeacherStatisticsInfoService.lambda$deleteDirtyData$0(TeacherStatisticsInfoService.java:159)	at java.util.ArrayList.forEach(ArrayList.java:1249)	at com.chaoxing.statistics.service.TeacherStatisticsInfoService.deleteDirtyData(TeacherStatisticsInfoService.java:158)	at com.chaoxing.statistics.task.RealTimeTeacherStatisticsJob$1.lambda$run$0(RealTimeTeacherStatisticsJob.java:114)	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040)	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by manzhizhen** [comment]
Can you tell me some more?

**Comment by ruijing** [comment]
Environment
Dubbo version: 2.5.9
Operating System version: linux
Java version: 1.8
registry:zookeeper

**Comment by manzhizhen** [comment]
Did the provider restart or release when printing this log?
打印这个日志的时候provider端有重启或发布吗？
