### ISSUE TITLE
Consumer aborted with ArrayIndexOutOfBoundsException when subscribing services from Nacos with '*' in group or version

### ISSUE THREAD

**Issue by FinalVersion** [apache/dubbo#6814]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: reproduced with 2.7.3, 2.7.8
* Operating System version: Windows 10
* Java version: 1.8.0

### Steps to reproduce this issue

1. Register a service with a non-dubbo service name (e.g. `user-service`) in a Nacos registry
2. Start a dubbo provider registering to the same Nacos registry 
3. Start a dubbo consumer consuming the service provided by the former provider, with a wildcard selector ('*') in group or version

### Expected Result

The consumer can initialize and call services successfully.

### Actual Result

What actually happens?

The consumer aborted during initialization, with the following exception:

```
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoServiceComponent': Injection of @DubboReference dependencies is failed; nested exception is java.lang.IllegalStateException: Failed to subscribe consumer://192.168.1.241/org.apache.dubbo.demo.DemoService?application=dubbo-demo-annotation-consumer&category=providers,configurators,routers&dubbo=2.0.2&group=*&init=false&interface=org.apache.dubbo.demo.DemoService&methods=sayHello,sayHelloAsync&pid=10232&side=consumer&sticky=false&timestamp=1603163878386, cause: 1
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.postProcessPropertyValues(AbstractAnnotationBeanPostProcessor.java:146)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1268)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
	at org.apache.dubbo.demo.consumer.Application.main(Application.java:34)
Caused by: java.lang.IllegalStateException: Failed to subscribe consumer://192.168.1.241/org.apache.dubbo.demo.DemoService?application=dubbo-demo-annotation-consumer&category=providers,configurators,routers&dubbo=2.0.2&group=*&init=false&interface=org.apache.dubbo.demo.DemoService&methods=sayHello,sayHelloAsync&pid=10232&side=consumer&sticky=false&timestamp=1603163878386, cause: 1
	at org.apache.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:350)
	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:105)
	at org.apache.dubbo.registry.integration.RegistryDirectory.subscribe(RegistryDirectory.java:185)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:469)
	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:449)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:72)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:161)
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:356)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:296)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:200)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.doGetInjectedBean(ReferenceAnnotationBeanPostProcessor.java:144)
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.getInjectedObject(AbstractAnnotationBeanPostProcessor.java:359)
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor$AnnotatedFieldElement.inject(AbstractAnnotationBeanPostProcessor.java:539)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.postProcessPropertyValues(AbstractAnnotationBeanPostProcessor.java:142)
	... 12 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.apache.dubbo.registry.nacos.NacosServiceName.<init>(NacosServiceName.java:80)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.apache.dubbo.registry.nacos.NacosRegistry.lambda$filterServiceNames$4(NacosRegistry.java:303)
	at org.apache.dubbo.registry.nacos.NacosRegistry.execute(NacosRegistry.java:583)
	at org.apache.dubbo.registry.nacos.NacosRegistry.filterServiceNames(NacosRegistry.java:295)
	at org.apache.dubbo.registry.nacos.NacosRegistry.getServiceNames0(NacosRegistry.java:286)
	at org.apache.dubbo.registry.nacos.NacosRegistry.getServiceNames(NacosRegistry.java:267)
	at org.apache.dubbo.registry.nacos.NacosRegistry.doSubscribe(NacosRegistry.java:178)
	at org.apache.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:333)
	... 27 more
```

### Root Cause

When NacosRegistry tries to subscribe dubbo services with wildcard in group or version, it will fetch and parse all service names from nacos. However the parsing logic made a wrong assumption that all services names conform to the dubbo service format like `providers:org.apache.dubbo.demo.DemoService:1.0.0:group1`, while there may be other service names like `user-service` in the registry.

**Comment by chickenlj** [comment]
Seems like a Nacos specific issue. Do you think it's right to just ignore the services that don't have the expected format?

**Comment by frlzk** [comment]
* Dubbo version: 3.0.2.1
* Operating System version: Ubuntu
* Java version: 1.8

`ServiceConfig<NameService> ns1=new ServiceConfig();
		ns1.setRegistry(r);
		ns1.setInterface(NameService.class);
		ns1.setRef(new NameServiceImpl());
		ns1.setGroup("group1");
		ns1.export();
		
		ServiceConfig<NameService> ns2=new ServiceConfig();
		ns2.setRegistry(r);
		ns2.setInterface(NameService.class);
		ns2.setRef(new NameServiceImpl());
		ns2.setGroup("group2");
		ns2.export();`

`ReferenceConfig<NameService> nameRef = new ReferenceConfig<>();
        nameRef.setRegistry(rc);
        nameRef.setInterface(NameService.class);
        nameRef.setGroup("*");
        NameService nameServ = nameRef.get();
        String name = nameServ.getName("dubbo");`

`Exception in thread "main" java.lang.IllegalStateException: Failed to subscribe dubbo://10.2.77.247/org.example.provider.test.NameService?application=first-consumer&category=providers,configurators,routers&dubbo=2.0.2&group=*&interface=org.example.provider.test.NameService&methods=getName,getSupportCodes&pid=13407&release=3.0.2.1&side=consumer&sticky=false&timestamp=1629444044395, cause: Failed to filter serviceName from nacos, url: nacos://127.0.0.1:8848/org.apache.dubbo.registry.RegistryService?application=first-consumer&dubbo=2.0.2&interface=org.apache.dubbo.registry.RegistryService&pid=13407&release=3.0.2.1, serviceName: providers:org.example.provider.test.NameService::*, cause: 1
	at org.apache.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:315)
	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:106)
	at org.apache.dubbo.registry.integration.RegistryDirectory.subscribe(RegistryDirectory.java:107)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doCreateInvoker(RegistryProtocol.java:515)
	at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getInvoker(InterfaceCompatibleRegistryProtocol.java:58)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshInterfaceInvoker(MigrationInvoker.java:448)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToApplicationFirstInvoker(MigrationInvoker.java:239)
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.refreshInvoker(MigrationRuleHandler.java:73)
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:57)
	at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:211)
	at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:486)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:468)
	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:448)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:74)
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:68)
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:51)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:73)
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:391)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:327)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:204)
	at org.example.provider.test.TestConumer.main(TestConumer.java:31)
Caused by: org.apache.dubbo.rpc.RpcException: Failed to filter serviceName from nacos, url: nacos://127.0.0.1:8848/org.apache.dubbo.registry.RegistryService?application=first-consumer&dubbo=2.0.2&interface=org.apache.dubbo.registry.RegistryService&pid=13407&release=3.0.2.1, serviceName: providers:org.example.provider.test.NameService::*, cause: 1
	at org.apache.dubbo.registry.nacos.NacosRegistry.filterServiceNames(NacosRegistry.java:316)
	at org.apache.dubbo.registry.nacos.NacosRegistry.getServiceNames0(NacosRegistry.java:298)
	at org.apache.dubbo.registry.nacos.NacosRegistry.getServiceNames(NacosRegistry.java:279)
	at org.apache.dubbo.registry.nacos.NacosRegistry.doSubscribe(NacosRegistry.java:193)
	at org.apache.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:298)
	... 21 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.apache.dubbo.registry.nacos.NacosServiceName.<init>(NacosServiceName.java:77)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.apache.dubbo.registry.nacos.NacosRegistry.filterServiceNames(NacosRegistry.java:313)
	... 25 more`

**Comment by AlbumenJ** [comment]
https://github.com/apache/dubbo/issues/8572
I will fix it

**Comment by AlbumenJ** [comment]
This problem occurs when both reigster interface level and instance level.

**Comment by CrazyHZM** [comment]
Already resolved.

**Comment by zanglw** [comment]
Has this problem been solved? How was it solved? Can you send me the solution? thinks@FinalVersion

**Comment by FinalVersion** [comment]
> Has this problem been solved? How was it solved? Can you send me the solution? thinks@FinalVersion

I think it's resolved as mentioned [here](https://github.com/apache/dubbo/issues/6814#issuecomment-903472363). The solution should be there in the PR description.
