### ISSUE TITLE
DubboHandlerRegistry#removeService NPE问题

### ISSUE THREAD

**Issue by xianliguang** [apache/dubbo#6856]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7
* Operating System version: macOs Mojave 10.14.5
* Java version: 1.8

### Steps to reproduce this issue

1. 使用dubbo启动一个任意grpc Provider进程
2. 关闭进程

### Expected Result

进程正常关闭，资源回收，无任何异常

### Actual Result

有NullPointerException报出

```
java.lang.NullPointerException: null
	at org.apache.dubbo.rpc.protocol.grpc.DubboHandlerRegistry.removeService(DubboHandlerRegistry.java:66) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.rpc.protocol.grpc.GrpcProtocol.lambda$doExport$1(GrpcProtocol.java:97) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.rpc.protocol.AbstractProxyProtocol$1.unexport(AbstractProxyProtocol.java:95) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.rpc.listener.ListenerExporterWrapper.unexport(ListenerExporterWrapper.java:71) [dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.config.ServiceConfig.unexport(ServiceConfig.java:170) [dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.lambda$unexportServices$17(DubboBootstrap.java:952) [dubbo-2.7.7.jar:2.7.7]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_231]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.unexportServices(DubboBootstrap.java:950) [dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.destroy(DubboBootstrap.java:1072) [dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap$1.callback(DubboBootstrap.java:193) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.common.function.ThrowableAction.execute(ThrowableAction.java:46) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.common.lang.ShutdownHookCallbacks.lambda$callback$0(ShutdownHookCallbacks.java:70) ~[dubbo-2.7.7.jar:2.7.7]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_231]
	at org.apache.dubbo.common.lang.ShutdownHookCallbacks.callback(ShutdownHookCallbacks.java:70) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.config.DubboShutdownHook.callback(DubboShutdownHook.java:85) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.config.DubboShutdownHook.run(DubboShutdownHook.java:73) ~[dubbo-2.7.7.jar:2.7.7]

```

**Comment by xianliguang** [comment]
如下两个地方都会去调用 DubboHandlerRegistry#removeService，但这个方法貌似没有重复调用的情况，重复调用会NPE
1. DubboShutdownHook#destroyProtocols
2. DubboBootstrap#unexportServices

```
  void removeService(String serviceKey) {
        ServerServiceDefinition service = services.remove(serviceKey); // 此处service可能为空
        for (ServerMethodDefinition<?, ?> method : service.getMethods()) {
            methods.remove(method.getMethodDescriptor().getFullMethodName(), method);
        }
    }
```

**Comment by xiaoheng1** [comment]
Can you provide detailed steps to reproduce? I tested it here and it didn’t reproduce the NPE.
