### ISSUE TITLE
消费方配置version为*时，无法调用配置了version的服务方

### ISSUE THREAD

**Issue by yangf159** [apache/dubbo#6892]
**

- Environment

**

Dubbo version: 2.6.2
Operating System version: Centos 7
Java version: 1.8
Spring Boot version: 2.1.1.RELEASE
Zookeeper version: 3.4.11

**

- Steps to reproduce this issue

**

正常启动Zookeeper集群、生产者、消费者
其中生产者配置版本号
dubbo.provider.version=1.0.0
消费者配置
dubbo.consumer.version=*

**

- Actual result :

**

调用报错

**

- 生产者日志：

**

`[DUBBO]Not found exported service: ezcs-dubbo-provider/ezcs.dubbo.test.api.IDemoService:*:20883 in [ezcs-dubbo-provider/ezcs.dubbo.test.api.IDemoService:1.0.0:20883], may be version or group mismatch , channel: consumer: /22.22.22.22:60464 --> provider: /22.22.22.22:20883, message:RpcInvocation [methodName=demo, parameterTypes=[interface java.util.Map], arguments=null, attachments={path=ezcs.dubbo.test.api.IDemoService, input=414, dubbo=2.6.2, interface=ezcs.dubbo.test.api.IDemoService, version=*, generic=true, group=ezcs-dubbo-provider}], dubbo version: 2.6.2, current host: 22.22.22.22

com.alibaba.dubbo.remoting.RemotingException: Not found exported service: ezcs-dubbo-provider/ezcs.dubbo.test.api.IDemoService:*:20883 in [ezcs-dubbo-provider/ezcs.dubbo.test.api.IDemoService:1.0.0:20883], may be version or group mismatch , channel: consumer: /22.22.22.22:60464 --> provider: /22.22.22.22:20883, message:RpcInvocation [methodName=demo, parameterTypes=[interface java.util.Map], arguments=null, attachments={path=ezcs.dubbo.test.api.IDemoService, input=414, dubbo=2.6.2, interface=ezcs.dubbo.test.api.IDemoService, version=*, generic=true, group=ezcs-dubbo-provider}]
 at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:212) ~[dubbo-2.6.2.jar:2.6.2]
 at com.alibaba.dubbo.rpc.protocol.dubbo.CallbackServiceCodec.decodeInvocationArgument(CallbackServiceCodec.java:270) [dubbo-2.6.2.jar:2.6.2]
 at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:131) [dubbo-2.6.2.jar:2.6.2]
 at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:70) [dubbo-2.6.2.jar:2.6.2]
 at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCodec.decodeBody(DubboCodec.java:129) [dubbo-2.6.2.jar:2.6.2]
 at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:124) [dubbo-2.6.2.jar:2.6.2]
 at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:84) [dubbo-2.6.2.jar:2.6.2]
 at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCountCodec.decode(DubboCountCodec.java:46) [dubbo-2.6.2.jar:2.6.2]
 at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalDecoder.messageReceived(NettyCodecAdapter.java:133) [dubbo-2.6.2.jar:2.6.2]
 at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80) [netty-3.2.5.Final.jar:?]
 at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.2.5.Final.jar:?]
 at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.2.5.Final.jar:?]
 at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274) [netty-3.2.5.Final.jar:?]
 at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261) [netty-3.2.5.Final.jar:?]
 at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:349) [netty-3.2.5.Final.jar:?]
 at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280) [netty-3.2.5.Final.jar:?]
 at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200) [netty-3.2.5.Final.jar:?]
 at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.2.5.Final.jar:?]
 at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:44) [netty-3.2.5.Final.jar:?]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
 at java.lang.Thread.run(Thread.java:748)  #[?:1.8.0_161] `

**

- 消费者日志：

**

`2020-11-10 09:19:52.727  INFO 16556 --- [0882-thread-193] c.b.e.d.t.c.DubboConsumerService         : input:{sysid=10002}
2020-11-10 09:19:52.737 ERROR 16556 --- [0882-thread-193] c.a.d.r.f.ExceptionFilter                :  [DUBBO] Got unchecked and undeclared exception which called by 22.22.22.22. service: ezcs.dubbo.test.consumer.DubboTestService, method: test, exception: com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method demo in the service ezcs.dubbo.test.api.IDemoService. Tried 3 times of the providers [22.22.22.22:20883] (1/1) from the registry 22.11.15.91:2181 on the consumer 22.22.22.22 using the dubbo version 2.6.2. Last error is: Failed to invoke remote method: demo, provider: dubbo://22.22.22.22:20883/ezcs.dubbo.test.api.IDemoService?anyhost=true&application=ezcs-dubbo-consumer&check=false&default.check=false&default.group=ezcs-dubbo-provider&default.version=*&dubbo=2.6.2&generic=false&interface=ezcs.dubbo.test.api.IDemoService&methods=demo&pid=16556&register.ip=22.22.22.22&remote.timestamp=1604971107818&side=consumer&timestamp=1604971077919, cause: com.alibaba.dubbo.remoting.RemotingException: Not found exported service: ezcs-dubbo-provider/ezcs.dubbo.test.api.IDemoService:*:20883 in [ezcs-dubbo-provider/ezcs.dubbo.test.api.IDemoService:1.0.0:20883], may be version or group mismatch , channel: consumer: /22.22.22.22:60464 --> provider: /22.22.22.22:20883, message:RpcInvocation [methodName=demo, parameterTypes=[interface java.util.Map], arguments=[{sysid=10002}], attachments={path=ezcs.dubbo.test.api.IDemoService, input=297, dubbo=2.6.2, interface=ezcs.dubbo.test.api.IDemoService, version=*, generic=true, group=ezcs-dubbo-provider}]
com.alibaba.dubbo.remoting.RemotingException: Not found exported service: ezcs-dubbo-provider/ezcs.dubbo.test.api.IDemoService:*:20883 in [ezcs-dubbo-provider/ezcs.dubbo.test.api.IDemoService:1.0.0:20883], may be version or group mismatch , channel: consumer: /22.22.22.22:60464 --> provider: /22.22.22.22:20883, message:RpcInvocation [methodName=demo, parameterTypes=[interface java.util.Map], arguments=[{sysid=10002}], attachments={path=ezcs.dubbo.test.api.IDemoService, input=297, dubbo=2.6.2, interface=ezcs.dubbo.test.api.IDemoService, version=*, generic=true, group=ezcs-dubbo-provider}]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:212)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:78)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:96)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:172)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
, dubbo version: 2.6.2, current host: 22.22.22.22

com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method demo in the service ezcs.dubbo.test.api.IDemoService. Tried 3 times of the providers [22.22.22.22:20883] (1/1) from the registry 22.11.15.91:2181 on the consumer 22.22.22.22 using the dubbo version 2.6.2. Last error is: Failed to invoke remote method: demo, provider: dubbo://22.22.22.22:20883/ezcs.dubbo.test.api.IDemoService?anyhost=true&application=ezcs-dubbo-consumer&check=false&default.check=false&default.group=ezcs-dubbo-provider&default.version=*&dubbo=2.6.2&generic=false&interface=ezcs.dubbo.test.api.IDemoService&methods=demo&pid=16556&register.ip=22.22.22.22&remote.timestamp=1604971107818&side=consumer&timestamp=1604971077919, cause: com.alibaba.dubbo.remoting.RemotingException: Not found exported service: ezcs-dubbo-provider/ezcs.dubbo.test.api.IDemoService:*:20883 in [ezcs-dubbo-provider/ezcs.dubbo.test.api.IDemoService:1.0.0:20883], may be version or group mismatch , channel: consumer: /22.22.22.22:60464 --> provider: /22.22.22.22:20883, message:RpcInvocation [methodName=demo, parameterTypes=[interface java.util.Map], arguments=[{sysid=10002}], attachments={path=ezcs.dubbo.test.api.IDemoService, input=297, dubbo=2.6.2, interface=ezcs.dubbo.test.api.IDemoService, version=*, generic=true, group=ezcs-dubbo-provider}]
com.alibaba.dubbo.remoting.RemotingException: Not found exported service: ezcs-dubbo-provider/ezcs.dubbo.test.api.IDemoService:*:20883 in [ezcs-dubbo-provider/ezcs.dubbo.test.api.IDemoService:1.0.0:20883], may be version or group mismatch , channel: consumer: /22.22.22.22:60464 --> provider: /22.22.22.22:20883, message:RpcInvocation [methodName=demo, parameterTypes=[interface java.util.Map], arguments=[{sysid=10002}], attachments={path=ezcs.dubbo.test.api.IDemoService, input=297, dubbo=2.6.2, interface=ezcs.dubbo.test.api.IDemoService, version=*, generic=true, group=ezcs-dubbo-provider}]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:212)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:78)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:96)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:172)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:102) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:238) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:75) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.common.bytecode.proxy0.demo(proxy0.java) ~[dubbo-2.6.2.jar:2.6.2]
	at ezcs.dubbo.test.consumer.DubboConsumerService.test(DubboConsumerService.java:27) ~[classes/:?]
	at com.alibaba.dubbo.common.bytecode.Wrapper2.invokeMethod(Wrapper2.java) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:76) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:52) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:62) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:72) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:105) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:103) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:96) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:172) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:80) [dubbo-2.6.2.jar:2.6.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: com.alibaba.dubbo.remoting.RemotingException: com.alibaba.dubbo.remoting.RemotingException: Not found exported service: ezcs-dubbo-provider/ezcs.dubbo.test.api.IDemoService:*:20883 in [ezcs-dubbo-provider/ezcs.dubbo.test.api.IDemoService:1.0.0:20883], may be version or group mismatch , channel: consumer: /22.22.22.22:60464 --> provider: /22.22.22.22:20883, message:RpcInvocation [methodName=demo, parameterTypes=[interface java.util.Map], arguments=[{sysid=10002}], attachments={path=ezcs.dubbo.test.api.IDemoService, input=297, dubbo=2.6.2, interface=ezcs.dubbo.test.api.IDemoService, version=*, generic=true, group=ezcs-dubbo-provider}]
com.alibaba.dubbo.remoting.RemotingException: Not found exported service: ezcs-dubbo-provider/ezcs.dubbo.test.api.IDemoService:*:20883 in [ezcs-dubbo-provider/ezcs.dubbo.test.api.IDemoService:1.0.0:20883], may be version or group mismatch , channel: consumer: /22.22.22.22:60464 --> provider: /22.22.22.22:20883, message:RpcInvocation [methodName=demo, parameterTypes=[interface java.util.Map], arguments=[{sysid=10002}], attachments={path=ezcs.dubbo.test.api.IDemoService, input=297, dubbo=2.6.2, interface=ezcs.dubbo.test.api.IDemoService, version=*, generic=true, group=ezcs-dubbo-provider}]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:212)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:78)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:96)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:172)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.returnFromResponse(DefaultFuture.java:222) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:139) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:112) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:95) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:148) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:54) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:77) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:78) ~[dubbo-2.6.2.jar:2.6.2]
	... 34 more
`

**

- Expected Result：

**

消费者在版本号配置*时，可以随机调用任意版本的服务方

**Comment by dkisser** [comment]
先检查下你的配置，我本地按照你说的方式测试，可以调通。但若是provider不配置version而consumer的version配置为 * 时，确实会出现你说的问题。
解释如下：
请求到provider端会根据group、version、interfaceName等关键信息得到serviceKey并在exporterMap中匹配.关键代码`
String serviceKey = serviceKey(port, path, inv.getAttachments().get(Constants.VERSION_KEY), inv.getAttachments().get(Constants.GROUP_KEY));
DubboExporter<?> exporter = (DubboExporter<?>) exporterMap.get(serviceKey);`

> 具体实现看DubboProtocol

**Comment by yangf159** [comment]
后续经过测试，使用注解的形式
@reference（version＝“*”）
和@service（version＝“2.0.1”）
可以达到标题描述的目的

使用springboot starter的配置文件
dubbo.provider.version＝2.0.1
dubbo.consumer.version＝*
就会出现上述错误

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issues
