### ISSUE TITLE
No such extension LoadBalance

### ISSUE THREAD

**Issue by fuhaopai** [apache/dubbo#6922]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.4
* Operating System version: linux
* Java version: jdk1.8

### Steps to reproduce this issue

1. provider提供者自定义loadbalance扩展
`
<dubbo:service interface="com.xxx.XxApi" ref="xxApi"
        <dubbo:method name="method" loadbalance="hashLoadBalance">
            <dubbo:parameter key="hash.arguments" value="0,1" />
        </dubbo:method>
</dubbo:service>
`

2. 服务提供者文件配置对应扩展
src
|-main
|-java
|-com
|-xxx
|-XxxLoadBalance.java (实现LoadBalance接口)
|-resources
|-META-INF
|-dubbo
|-org.apache.dubbo.rpc.cluster.LoadBalance (纯文本文件，内容为：hashLoadBalance=com.xxx.HashLoadBalance)

3.消费者调用
`  @Reference
    private XxApi xxApi;

   public void xx() {
       xxApi.method()
   }
`

Pls. provide [GitHub address] to reproduce this issue.

### Actual Result

消费者调用不能识别提供者方法上配置的自定义hashLoadBalance扩展

```
java.lang.IllegalStateException: No such extension com.alibaba.dubbo.rpc.cluster.LoadBalance by name hashLoadBalance
	at com.alibaba.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:482)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:489)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:309)
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:240)
	at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:75)
	at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52)
	at com.alibaba.dubbo.common.bytecode.proxy0.measure(proxy0.java)
	at com.daimler.visual.LbsVssManager.measure(LbsVssManager.java:38)
	at com.daimler.visual.LbsVssManager$$FastClassBySpringCGLIB$$d6590229.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.daimler.visual.LbsVssManager$$EnhancerBySpringCGLIB$$419b98e9.measure(<generated>)
	at com.daimler.visual.dubbo.CompassApiTest.test_lbs(CompassApiTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by LiosWong** [comment]
因为dubbo版本是2.6.4，包名不对
```
**META-INF/dubbo/org.apache.dubbo.rpc.cluster.LoadBalance  ==》 META-INF/dubbo/com.alibaba.dubbo.rpc.cluster.LoadBalance**   
```

**Comment by fuhaopai** [comment]
> 因为dubbo版本是2.6.4，文件名不对
> 
> ```
> META-INF/dubbo/org.apache.dubbo.rpc.cluster.LoadBalance  ==》 META-INF/dubbo/com.alibaba.dubbo.rpc.cluster.LoadBalance
> ```

是我贴错了，实际报错用的是com.alibaba.dubbo.rpc.cluster.LoadBalance。
provider注册到zk的时候元数据是带有LoadBalance的。consumer调用的时候因为是自定义的所以找不到LoadBalance

**Comment by dkisser** [comment]
loadblance应cunsumer端

**Comment by dkisser** [comment]
Loadbalance应放在Consumer端
