### ISSUE TITLE
dubbuo2.7.6泛华调用的问题AnnotationConfigApplicationContext close

### ISSUE THREAD

**Issue by etdick** [apache/dubbo#6950]
dubbuo2.7.6泛华调用时，发现AnnotationConfigApplicationContext close
dubbo version 2.7.6
=========================================================================================
java.lang.IllegalStateException: org.springframework.context.annotation.AnnotationConfigApplicationContext@5579bb86 has been closed already
	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1093)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1126)
	at com.alibaba.cloud.dubbo.registry.SpringCloudRegistryFactory.init(SpringCloudRegistryFactory.java:82)
	at com.alibaba.cloud.dubbo.registry.SpringCloudRegistryFactory.getRegistry(SpringCloudRegistryFactory.java:94)
	at org.apache.dubbo.registry.RegistryFactoryWrapper.getRegistry(RegistryFactoryWrapper.java:34)
	at org.apache.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)
	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:397)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:73)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:70)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:159)
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:318)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:258)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:158)
	at org.apache.dubbo.config.utils.ReferenceConfigCache.lambda$get$3(ReferenceConfigCache.java:114)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.apache.dubbo.config.utils.ReferenceConfigCache.get(ReferenceConfigCache.java:113)
	at com.crc.crcloud.itsm.core.utils.DubboUtils.getDubboService(DubboUtils.java:108)
	at com.crc.crcloud.itsm.core.utils.DubboUtils.getDubboGenericService(DubboUtils.java:77)
	at com.crc.crcloud.itsm.core.utils.DubboUtils.callDubboServiceByGenericService(DubboUtils.java:145)
	at com.crc.crcloud.itsm.core.utils.DubboUtils.callDubboServiceByGenericService(DubboUtils.java:129)
	at com.crc.crcloud.itsm.backend.consumer.CommonConsumer.dealDubbo(CommonConsumer.java:109)
	at com.crc.crcloud.itsm.backend.consumer.CommonConsumer.lambda$registerConsumer$0(CommonConsumer.java:82)
	at org.apache.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService$ConsumeRequest.run(ConsumeMessageConcurrentlyService.java:412)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by xiaoheng1** [comment]
can you provider a demo ?

**Comment by etdick** [comment]
问题解决了，但是没明白。我的版本是spring-cloud-alibaba 和 nacos ，版本如下，把nacos的监听注释掉就好了
<spring-boot-dependencies.version>2.3.2.RELEASE</spring-boot-dependencies.version>
<spring-cloud-dependencies.version>Hoxton.SR8</spring-cloud-dependencies.version>
<spring-cloud-alibaba-dependencies.version>2.2.5.RELEASE</spring-cloud-alibaba-dependencies.version>


![image](https://user-images.githubusercontent.com/31947496/120896820-c126d700-c655-11eb-8847-89f63792a86f.png)
