### ISSUE TITLE
A deadlock occurs when Dubbo integrates Spring

### ISSUE THREAD

**Issue by RobertLiu0905** [apache/dubbo#6969]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

Main thread is creating dubbo bean, so this thread hold the ```DefaultSingletonBeanRegistry.getSingleton``` sync lock, then doSubscribe zookeeper registry, in this time, main thread also will try to get RegistryDirect's lock。In the same time, suppose some provider information has changed, zookeeper event thread will notify registry directory and get RegistryDirect's lock, then create new dubbo bean。Coincidently deadlock problems happen。

### Environment

* Dubbo version: 2.7.8
* Operating System version: centos 6.7
* Java version: 1.8

### Steps to reproduce this issue

1. Start application

### Expected Result

2. Sometimes the system throws a deadlock exception

### Actual Result

Thread stack : 

```
================================================================
"localhost-startStop-1-EventThread" Id=219 BLOCKED on java.util.concurrent.ConcurrentHashMap@41d80cd owned by "localhost-startStop-1" Id=199
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:179)
	-  blocked on java.util.concurrent.ConcurrentHashMap@41d80cd
	at org.springframework.beans.factory.support.AbstractBeanFactory.isTypeMatch(AbstractBeanFactory.java:493)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:520)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:483)
	at org.springframework.context.support.AbstractApplicationContext.getBeanNamesForType(AbstractApplicationContext.java:1220)
	at org.springframework.beans.factory.BeanFactoryUtils.beanNamesForTypeIncludingAncestors(BeanFactoryUtils.java:227)
	at com.alibaba.spring.util.BeanFactoryUtils.getBeans(BeanFactoryUtils.java:81)
	at com.alibaba.spring.util.BeanFactoryUtils.getOptionalBean(BeanFactoryUtils.java:59)
	at org.apache.dubbo.config.spring.extension.SpringExtensionFactory.getExtension(SpringExtensionFactory.java:69)
	at org.apache.dubbo.common.extension.factory.AdaptiveExtensionFactory.getExtension(AdaptiveExtensionFactory.java:47)
	at org.apache.dubbo.common.extension.ExtensionLoader.injectExtension(ExtensionLoader.java:708)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:649)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:440)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:424)
	at org.apache.dubbo.common.extension.ExtensionLoader.getActivateExtension(ExtensionLoader.java:295)
	at org.apache.dubbo.common.extension.ExtensionLoader.getActivateExtension(ExtensionLoader.java:259)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.buildInvokerChain(ProtocolFilterWrapper.java:56)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:163)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:75)
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at org.apache.dubbo.registry.integration.RegistryDirectory.toInvokers(RegistryDirectory.java:455)
	at org.apache.dubbo.registry.integration.RegistryDirectory.refreshInvoker(RegistryDirectory.java:312)
	at org.apache.dubbo.registry.integration.RegistryDirectory.refreshOverrideAndInvoker(RegistryDirectory.java:271)
	at org.apache.dubbo.registry.integration.RegistryDirectory.notify(RegistryDirectory.java:254)
	at org.apache.dubbo.registry.support.AbstractRegistry.notify(AbstractRegistry.java:426)
	at org.apache.dubbo.registry.support.FailbackRegistry.doNotify(FailbackRegistry.java:407)
	at org.apache.dubbo.registry.support.FailbackRegistry.notify(FailbackRegistry.java:398)
	at org.apache.dubbo.registry.zookeeper.ZookeeperRegistry.lambda$null$5(ZookeeperRegistry.java:174)
	at org.apache.dubbo.registry.zookeeper.ZookeeperRegistry$$Lambda$571/1841318036.childChanged(Unknown Source)
	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient$CuratorWatcherImpl.process(CuratorZookeeperClient.java:293)
	at org.apache.curator.framework.imps.NamespaceWatcher.process(NamespaceWatcher.java:83)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:532)

"localhost-startStop-1" Id=199 BLOCKED on org.apache.dubbo.registry.integration.RegistryDirectory@3d6b7536 owned by "localhost-startStop-1-EventThread" Id=219
	at org.apache.dubbo.registry.integration.RegistryDirectory.notify(RegistryDirectory.java:230)
	-  blocked on org.apache.dubbo.registry.integration.RegistryDirectory@3d6b7536
	at org.apache.dubbo.registry.support.AbstractRegistry.notify(AbstractRegistry.java:426)
	at org.apache.dubbo.registry.support.FailbackRegistry.doNotify(FailbackRegistry.java:407)
	at org.apache.dubbo.registry.support.FailbackRegistry.notify(FailbackRegistry.java:398)
	at org.apache.dubbo.registry.zookeeper.ZookeeperRegistry.doSubscribe(ZookeeperRegistry.java:181)
	at org.apache.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:333)
	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:105)
	at org.apache.dubbo.registry.integration.RegistryDirectory.subscribe(RegistryDirectory.java:185)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:469)
	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:454)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:72)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:161)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:73)
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:368)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:306)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:206)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.doGetInjectedBean(ReferenceAnnotationBeanPostProcessor.java:144)
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.getInjectedObject(AbstractAnnotationBeanPostProcessor.java:359)
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor$AnnotatedFieldElement.inject(AbstractAnnotationBeanPostProcessor.java:539)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.postProcessPropertyValues(AbstractAnnotationBeanPostProcessor.java:142)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1409)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$180/548977112.getObject(Unknown Source)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:847)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)

================================================================
```

**Comment by RobertLiu0905** [comment]
@chickenlj 是否有什么好的解决方案？

**Comment by RobertLiu0905** [comment]
@chickenlj 目前是打算修改dubbo的代码，把org.apache.dubbo.registry.integration.RegistryDirectory#notify这个方法级别的锁细化到接口级。。。

**Comment by CrazyHZM** [comment]
@RobertLiu0905 Try it with the latest version.

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.

**Comment by qixiaobo** [comment]
like https://github.com/apache/dubbo/issues/6037
Now we should add startup probe in k8s pod to avoid it
