### ISSUE TITLE
Dubbo关闭时报Exception in thread "DubboShutdownHook" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by skiof007** [apache/dubbo#7009]
Environment
Dubbo version: 2.7.5
Java version: 1.8
Steps to reproduce this issue
dubbo应用正常优雅关闭
应用日志中打出错误日志
Actual Result
Exception in thread "DubboShutdownHook" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/apache/dubbo/common/function/ThrowableAction
	at org.apache.dubbo.common.lang.ShutdownHookCallbacks.lambda$callback$0(ShutdownHookCallbacks.java:70)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.apache.dubbo.common.lang.ShutdownHookCallbacks.callback(ShutdownHookCallbacks.java:70)
	at org.apache.dubbo.config.DubboShutdownHook.callback(DubboShutdownHook.java:81)
	at org.apache.dubbo.config.DubboShutdownHook.run(DubboShutdownHook.java:69)
Caused by: java.lang.NoClassDefFoundError: org/apache/dubbo/common/function/ThrowableAction
	... 5 more
Caused by: java.lang.ClassNotFoundException: org.apache.dubbo.common.function.ThrowableAction
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1720)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
	... 5 more

**Comment by skiof007** [comment]
经过验证将ShutdownHookCallbacks类的callback()修改如下后异常消失:
        /**
           验证代码，非正式代码
         **/
        Collection<ShutdownHookCallback>  ls = getCallbacks();
    	for (ShutdownHookCallback shutdownHookCallback : ls) {
    		try{
    			
    			shutdownHookCallback.callback();
    		}catch(Throwable ex){
    			
    			ex.printStackTrace();
    		}
	}

原方法内容:  getCallbacks().forEach(callback -> execute(callback::callback));

**Comment by skiof007** [comment]
请教下，这不是一个BUG么？这个异常将会影响容器对资源的释放!

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issues.
