### ISSUE TITLE
dubbo 2.7.7升至2.7.8 项目启动 @DubboReference 报空指针

### ISSUE THREAD

**Issue by dengjin001** [apache/dubbo#7018]
### Environment

* Dubbo version: 2.7.8
* Operating System version: win10
* Java version:  8

### Steps to reproduce this issue

项目集成dubbo+seate 1.3.0 

`@Component
@Slf4j
public class AsyncTask {

    @DubboReference
    private OrderService orderService;`

启动报以下错误：
```log
`Injection of @DubboReference dependencies is failed; nested exception is java.lang.RuntimeException: java.lang.NullPointerException
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.postProcessPropertyValues(AbstractAnnotationBeanPostProcessor.java:145)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1427)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330)
	... 62 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at io.seata.spring.annotation.GlobalTransactionScanner.wrapIfNecessary(GlobalTransactionScanner.java:245)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.getEarlyBeanReference(AbstractAutoProxyCreator.java:240)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getEarlyBeanReference(AbstractAutowireCapableBeanFactory.java:965)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$doCreateBean$1(AbstractAutowireCapableBeanFactory.java:588)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:184)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:164)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:249)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1114)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.getServiceBean(ReferenceAnnotationBeanPostProcessor.java:286)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.exportServiceBeanIfNecessary(ReferenceAnnotationBeanPostProcessor.java:278)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.prepareReferenceBean(ReferenceAnnotationBeanPostProcessor.java:271)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.doGetInjectedBean(ReferenceAnnotationBeanPostProcessor.java:138)
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.getInjectedObject(AbstractAnnotationBeanPostProcessor.java:358)
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor$AnnotatedFieldElement.inject(AbstractAnnotationBeanPostProcessor.java:538)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:116)
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.postProcessPropertyValues(AbstractAnnotationBeanPostProcessor.java:141)
	... 70 common frames omitted
Caused by: java.lang.NullPointerException: null
	at io.seata.rm.tcc.remoting.parser.DefaultRemotingParser.parserRemotingServiceInfo(DefaultRemotingParser.java:170)
	at io.seata.spring.util.TCCBeanParserUtils.parserRemotingServiceInfo(TCCBeanParserUtils.java:147)
	at io.seata.spring.util.TCCBeanParserUtils.isTccAutoProxy(TCCBeanParserUtils.java:48)
	at io.seata.spring.annotation.GlobalTransactionScanner.wrapIfNecessary(GlobalTransactionScanner.java:208)
	... 86 common frames omitted`
```

**Comment by dengjin001** [comment]
dubbo 2.7.7 则没有问题

**Comment by kimmking** [comment]
看起来是seata的判断问题

**Comment by Lianghuige** [comment]
这个问题怎么解决的

**Comment by dengjin001** [comment]
暂时没法解决 seata和dubbo的最新版本都试过，没有用。 暂时用2.7.7吧

**Comment by Lianghuige** [comment]
我的问题找到了，是项目下面有别的项目没有更改为2.7.8还是原来的，改过后就正常可以运行了
