### ISSUE TITLE
 No provider available in XXXXX

### ISSUE THREAD

**Issue by cxdhefei** [apache/dubbo#7074]
**Which Component**
 nacos-server: 1.3.1
 spring-boot: 2.2.6.RELEASE
 spring-cloud-alibaba: 2.2.1.RELEASE (dubbo: 2.7.6、nacos-client: 1.2.1)
 spring-cloud: Hoxton.SR4

**Describe the bug**
服务提供者重启后，消费者无法发现服务提供者，出现如下错误（**这个问题是偶现的**）：
After the service provider restarts, the consumer cannot find the service provider, and the following error occurs(**This problem is occasional**)：

```
2021-01-04 13:40:00.088 ERROR [http-nio-2130-exec-5] com.xy.sdx.common.web.handler.GlobalExceptionHandler:116 [e251b3e36b154c68bb289f5ce06d1a46] No provider available in [invoker :interface com.xy.sdx.admin.api.RpcUserService -> spring-cloud://localhost:9090/org.apache.dubbo.registry.RegistryService?anyhost=true&application=sdx-manage-uaa&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&init=false&interface=com.xy.sdx.admin.api.RpcUserService&methods=removeById,addUser,lambdaQuery,modifyStatus,removeByMap,findAppUserListByKeywordsAndAppCode,listByIds,saveUserRoleRelationship,removeUser,findListByRoleRegion,updateBatchById,modifyUserAddRoleRegionRelationship,findAppUserListByPage,saveUserRoleRegionRelationship,saveOrUpdate,removeRecordById,findByIds,query,findUserAppResource,count,listObjs,findByIdCard,list,getMap,getById,getOne,page,saveUserRoleBranchRelationship,findListByOperableRoles,save,update,getObj,saveOrUpdateBatch,remove,getBaseMapper,findListByPage,removeByIds,findPageListByRegion,findUserRoleBrandApp,findById,lambdaUpdate,modifyUserAddRoleBranchRelationship,listMaps,forgetPwd,updatePwd,saveBatch,modifyUserAddRoleRelationship,checkUserMobile,modifyUserRoleBranchRelationship,verifyPwd,updateById,pageMaps,modifyUserRoleRegionRelationship,findAppUserPageListByRegionAndAppCode,resetPwd,findAppUserListByRoleRegionAndAppCode,findByUsername,listByMap,findAppUserListByOperableRolesAndAppCode,findListByKeywords&pid=35713&qos.enable=false&register.ip=192.168.3.16&release=2.7.6&remote.application=sdx-admin&retries=0&service.filter=-exception&side=consumer&sticky=false&timeout=60000&timestamp=1609729666751,directory: org.apache.dubbo.registry.integration.RegistryDirectory@1fab0394, invoker :interface com.xy.sdx.admin.api.RpcUserService -> nacos://localhost:8848/org.apache.dubbo.registry.RegistryService?anyhost=true&application=sdx-manage-uaa&category=providers&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&init=false&interface=com.xy.sdx.admin.api.RpcUserService&methods=removeById,addUser,lambdaQuery,modifyStatus,removeByMap,findAppUserListByKeywordsAndAppCode,listByIds,saveUserRoleRelationship,removeUser,findListByRoleRegion,updateBatchById,modifyUserAddRoleRegionRelationship,findAppUserListByPage,saveUserRoleRegionRelationship,saveOrUpdate,removeRecordById,findByIds,query,findUserAppResource,count,listObjs,findByIdCard,list,getMap,getById,getOne,page,saveUserRoleBranchRelationship,findListByOperableRoles,save,update,getObj,saveOrUpdateBatch,remove,getBaseMapper,findListByPage,removeByIds,findPageListByRegion,findUserRoleBrandApp,findById,lambdaUpdate,modifyUserAddRoleBranchRelationship,listMaps,forgetPwd,updatePwd,saveBatch,modifyUserAddRoleRelationship,checkUserMobile,modifyUserRoleBranchRelationship,verifyPwd,updateById,pageMaps,modifyUserRoleRegionRelationship,findAppUserPageListByRegionAndAppCode,resetPwd,findAppUserListByRoleRegionAndAppCode,findByUsername,listByMap,findAppUserListByOperableRolesAndAppCode,findListByKeywords&path=com.xy.sdx.admin.api.RpcUserService&pid=35713&protocol=dubbo&qos.enable=false&register.ip=192.168.3.16&release=2.7.6&remote.application=sdx-admin&retries=0&service.filter=-exception&side=consumer&sticky=false&timeout=60000&timestamp=1609729666751,directory: org.apache.dubbo.registry.integration.RegistryDirectory@2a191f83]
org.apache.dubbo.rpc.RpcException: No provider available in [invoker :interface com.xy.sdx.admin.api.RpcUserService -> spring-cloud://localhost:9090/org.apache.dubbo.registry.RegistryService?anyhost=true&application=sdx-manage-uaa&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&init=false&interface=com.xy.sdx.admin.api.RpcUserService&methods=removeById,addUser,lambdaQuery,modifyStatus,removeByMap,findAppUserListByKeywordsAndAppCode,listByIds,saveUserRoleRelationship,removeUser,findListByRoleRegion,updateBatchById,modifyUserAddRoleRegionRelationship,findAppUserListByPage,saveUserRoleRegionRelationship,saveOrUpdate,removeRecordById,findByIds,query,findUserAppResource,count,listObjs,findByIdCard,list,getMap,getById,getOne,page,saveUserRoleBranchRelationship,findListByOperableRoles,save,update,getObj,saveOrUpdateBatch,remove,getBaseMapper,findListByPage,removeByIds,findPageListByRegion,findUserRoleBrandApp,findById,lambdaUpdate,modifyUserAddRoleBranchRelationship,listMaps,forgetPwd,updatePwd,saveBatch,modifyUserAddRoleRelationship,checkUserMobile,modifyUserRoleBranchRelationship,verifyPwd,updateById,pageMaps,modifyUserRoleRegionRelationship,findAppUserPageListByRegionAndAppCode,resetPwd,findAppUserListByRoleRegionAndAppCode,findByUsername,listByMap,findAppUserListByOperableRolesAndAppCode,findListByKeywords&pid=35713&qos.enable=false&register.ip=192.168.3.16&release=2.7.6&remote.application=sdx-admin&retries=0&service.filter=-exception&side=consumer&sticky=false&timeout=60000&timestamp=1609729666751,directory: org.apache.dubbo.registry.integration.RegistryDirectory@1fab0394, invoker :interface com.xy.sdx.admin.api.RpcUserService -> nacos://localhost:8848/org.apache.dubbo.registry.RegistryService?anyhost=true&application=sdx-manage-uaa&category=providers&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&init=false&interface=com.xy.sdx.admin.api.RpcUserService&methods=removeById,addUser,lambdaQuery,modifyStatus,removeByMap,findAppUserListByKeywordsAndAppCode,listByIds,saveUserRoleRelationship,removeUser,findListByRoleRegion,updateBatchById,modifyUserAddRoleRegionRelationship,findAppUserListByPage,saveUserRoleRegionRelationship,saveOrUpdate,removeRecordById,findByIds,query,findUserAppResource,count,listObjs,findByIdCard,list,getMap,getById,getOne,page,saveUserRoleBranchRelationship,findListByOperableRoles,save,update,getObj,saveOrUpdateBatch,remove,getBaseMapper,findListByPage,removeByIds,findPageListByRegion,findUserRoleBrandApp,findById,lambdaUpdate,modifyUserAddRoleBranchRelationship,listMaps,forgetPwd,updatePwd,saveBatch,modifyUserAddRoleRelationship,checkUserMobile,modifyUserRoleBranchRelationship,verifyPwd,updateById,pageMaps,modifyUserRoleRegionRelationship,findAppUserPageListByRegionAndAppCode,resetPwd,findAppUserListByRoleRegionAndAppCode,findByUsername,listByMap,findAppUserListByOperableRolesAndAppCode,findListByKeywords&path=com.xy.sdx.admin.api.RpcUserService&pid=35713&protocol=dubbo&qos.enable=false&register.ip=192.168.3.16&release=2.7.6&remote.application=sdx-admin&retries=0&service.filter=-exception&side=consumer&sticky=false&timeout=60000&timestamp=1609729666751,directory: org.apache.dubbo.registry.integration.RegistryDirectory@2a191f83]
	at org.apache.dubbo.rpc.cluster.support.registry.ZoneAwareClusterInvoker.doInvoke(ZoneAwareClusterInvoker.java:101)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:259)
	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)
	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:82)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:74)
	at org.apache.dubbo.common.bytecode.proxy3.findByUsername(proxy3.java)
	at com.xy.sdx.uaa.service.UserServiceImpl.login(UserServiceImpl.java:92)
	at com.xy.sdx.uaa.controller.LoginController.login(LoginController.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.xy.sdx.common.web.filter.TraceIdHttpFilter.doFilter(TraceIdHttpFilter.java:64)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cxdhefei** [comment]
@manzhizhen 
This problem is similar to this [issue ](https://github.com/apache/dubbo/issues/6813)

**Comment by chengj1** [comment]
dubbo 2.7.8 版本也存在此问题

**Comment by xiaoheng1** [comment]
> dubbo 2.7.8 版本也存在此问题

@chengj1 能提供一个配置重现这个问题不？

**Comment by chengj1** [comment]
**_Which Component_**
nacos-server: 1.3.2
zooker: 3.6.2
dubbo:  2.7.8
spring framework:  4.3.28.RELEASE
私有云容器化部署，服务量 1000+

**_Describe the bug_**
服务提供者重启后，消费者需要重启才能正确消费服务，否则不是报 no provider 错误  就是  调用的URL地址还是旧的地址，刚开始怀疑是Nacos的问题，后来换成 zookeeper 问题还在。另外我通过 RegistryService.subscribe(url, notifyListener) 订阅服务时，后台会疯狂打印日志（这个刚开始很正常，一天日志就200M左右，运行几周后才会这样），一个节点一天能输出 10+G 的日志量（都是订阅的服务地址信息，内容都是重复的，可以确定当时并没有大量的容量频繁重启的现象），而且订阅的服务量和在nacos consule 上查询到的数量对不上（按接口统计的）。

**Comment by xiaoheng1** [comment]
服务提供者只是单纯的重启不？有没有修改提供者的参数配置？

**Comment by xiaoheng1** [comment]
@chengj1  我在本地进行来测试，一个生产者，一个消费者，生产这重启，消费者能否正确消费服务。

代码如下：

dubbo2.7.8

provider：

```
public class Application {
    private static String zookeeperHost = System.getProperty("zookeeper.address", "127.0.0.1");

    public static void main(String[] args) throws Exception {
        ServiceConfig<GreetingsService> service = new ServiceConfig<>();
        service.setScope("remote");
        service.setApplication(new ApplicationConfig("first-dubbo-provider"));
        RegistryConfig registryConfig = new RegistryConfig("zookeeper://" + zookeeperHost + ":2181");
        HashMap<String, String> map = new HashMap<>();
        //map.put("registry-type", "service");
        registryConfig.setParameters(map);
        //registryConfig.setSimplified(true);
        service.setRegistry(registryConfig);

        service.setInterface(GreetingsService.class);
        service.setRef(new GreetingsServiceImpl());
        service.export();

        System.out.println("dubbo service started");
        new CountDownLatch(1).await();
    }
}
```

comsuner：

```
public class Application {
    private static String zookeeperHost = System.getProperty("zookeeper.address", "127.0.0.1");

    public static void main(String[] args) throws InterruptedException {
        for(int i=0; i<3; i++){
            ReferenceConfig<GreetingsService> reference = new ReferenceConfig<>();
            reference.setApplication(new ApplicationConfig("first-dubbo-consumer"));
            RegistryConfig registryConfig = new RegistryConfig("zookeeper://" + zookeeperHost + ":2181");
           // registryConfig.setSimplified(true);
            reference.setRegistry(registryConfig);
            reference.setTimeout(1000 * 60);
            reference.setInterface(GreetingsService.class);
            GreetingsService service = reference.get();
            String message = service.sayHi("dubbo");
            System.out.println(message);
            Thread.sleep(60 * 1000 * 2);
        }

    }
}
```

**Comment by chengj1** [comment]
这样是没有问题的，我们在开发环境都很正常。问题在生产环境应用重启后IP就变了，而且每个应用都是多节点部署的，重启速度很快。

**Comment by xiaoheng1** [comment]
> 这样是没有问题的，我们在开发环境都很正常。问题在生产环境应用重启后IP就变了，而且每个应用都是多节点部署的，重启速度很快。

你的意思说容器重启后，导致 ip 发生变化，那这种情况下消费者调用不到生产者逻辑上应该算正常的。

**Comment by chengj1** [comment]
关键是这个问不光会在重启过程中，在重启完成后不重启消费者的话就会一直调不到

**Comment by xiaoheng1** [comment]
明白你的意思了，我这边测试下这种情况。

**Comment by xiaoheng1** [comment]
能提供一些日志不？

**Comment by ethanas** [comment]
我提供改一个我们的修复思路：

**Comment by ethanas** [comment]
萌新初到，抛砖引玉，我debug过类似的情况

场景：service可能会频繁上下线（同一个服务，所有参数都一样）

问题定位：我们的服务调用失败的原因是服务没有下线彻底的情况又注册上来。失败的报错一样。为什么调用失败我就不细说了，大概的方位是生产者收到消息后，在serviceMap上没找到调用的key。此错误很容易被容错机制所掩盖。

提供一个我们的修复思路（给服务上线加个锁），此方法需要用到API暴露服务：
1. 建立支持并发访问的本地服务列表缓存
2. 实现ExporterListener扩展 ，在上线的时候记录上线的host（因为不知道为什么，同一个服务unexported的时候会有多个host不同的unexported事件，其中有个127.0.0.1，为了防止暴露服务的时候选择的host不一样，所以在这个地方记录下用来在unexported的时候判断是否解除上线锁定）。同时给服务放到本地服务列表缓存上（key你可以根据自己的服务来定义一个extra key，同时暴露到url中）。

2.在下线的时候unexported根据host筛选出已经上线的服务，在服务缓存列表中删除

3.在服务上线的时候检查该服务是否在缓存中，在的话忽略等待下次处理（因为我们是循环检测，所以服务在下次循环还会被检测到未在缓存中），如果不存在就走正常上线。

**Comment by xiaoheng1** [comment]
没有下线彻底，又重现注册上来了，这种情况下，应该不会报 no provider 这个错吧？

**Comment by ethanas** [comment]
> 没有下线彻底，又重现注册上来了，这种情况下，应该不会报 no provider 这个错吧？

我尽量给您一个重现的例子，我是通过unexport方法实现服务下线，这个方法完全下线需要点时间，我重新new一个一样的ServiceConfig 然后export，交替几次就能重现。不管服务怎么上下先serviceMap中的数量都保持不变，所以在provider端用url key在map中找服务的时候找不到。

**Comment by xiaoheng1** [comment]
> > 没有下线彻底，又重现注册上来了，这种情况下，应该不会报 no provider 这个错吧？
> 
> 我尽量给您一个重现的例子，我是通过unexport方法实现服务下线，这个方法完全下线需要点时间，我重新new一个一样的ServiceConfig 然后export，交替几次就能重现。不管服务怎么上下线，serviceMap中的数量都保持不变（我debug的时候都是比实际的少），所以在provider端用url key在map中找服务的时候找不到。

好的，感谢，提供一个demo，我这边试下。多试几次的也行，能大概率重现就好。

**Comment by qiufang1314** [comment]
> 萌新初到，抛砖引玉，我debug过类似的情况
> 
> 场景：service可能会频繁上下线（同一个服务，所有参数都一样）
> 
> 问题定位：我们的服务调用失败的原因是服务没有下线彻底的情况又注册上来。失败的报错一样。为什么调用失败我就不细说了，大概的方位是生产者收到消息后，在serviceMap上没找到调用的key。此错误很容易被容错机制所掩盖。
> 
> 提供一个我们的修复思路（给服务上线加个锁），此方法需要用到API暴露服务：
> 
> 1. 建立支持并发访问的本地服务列表缓存
> 2. 实现ExporterListener扩展 ，在上线的时候记录上线的host（因为不知道为什么，同一个服务unexported的时候会有多个host不同的unexported事件，其中有个127.0.0.1，为了防止暴露服务的时候选择的host不一样，所以在这个地方记录下用来在unexported的时候判断是否解除上线锁定）。同时给服务放到本地服务列表缓存上（key你可以根据自己的服务来定义一个extra key，同时暴露到url中）。
> 
> 3.在下线的时候unexported根据host筛选出已经上线的服务，在服务缓存列表中删除
> 
> 4.在服务上线的时候检查该服务是否在缓存中，在的话忽略等待下次处理（因为我们是循环检测，所以服务在下次循环还会被检测到未在缓存中），如果不存在就走正常上线。
> 
> ip变化也同理，监听ip的变化，如果变了了给原来的服务彻底下线，然后再上线，就会用最新的ip暴露服务

我们这边也遇到同样的问题，能给下修复代码参考下不

**Comment by xiaoheng1** [comment]
按照这个修复的看下：https://github.com/apache/dubbo/pull/7126/commits/d731a0c0c6362bcc8499727b3239f878a960d67b

建议在获取锁的时候，按照 url 维度。

**Comment by xiaoheng1** [comment]
url 维度，可以保留住关键信息，去掉例如像时间戳这样的数据

**Comment by qiufang1314** [comment]
> 按照这个修复的看下：[d731a0c](https://github.com/apache/dubbo/commit/d731a0c0c6362bcc8499727b3239f878a960d67b)

您好，请问下这个有合并到发布的分支不~

**Comment by xiaoheng1** [comment]
> > 按照这个修复的看下：[d731a0c](https://github.com/apache/dubbo/commit/d731a0c0c6362bcc8499727b3239f878a960d67b)
> 
> 您好，请问下这个有合并到发布的分支不~

现在还没有合并到发布分支

**Comment by qiufang1314** [comment]
> > > 按照这个修复的看下：[d731a0c](https://github.com/apache/dubbo/commit/d731a0c0c6362bcc8499727b3239f878a960d67b)
> > 
> > 
> > 您好，请问下这个有合并到发布的分支不~
> 
> 现在还没有合并到发布分支

您好，能多说点，这个问题发生的原因不，还是有点不明白什么样的case会发生这样的问题，十分感谢~~

**Comment by xiaoheng1** [comment]
> > > > 按照这个修复的看下：[d731a0c](https://github.com/apache/dubbo/commit/d731a0c0c6362bcc8499727b3239f878a960d67b)
> > > 
> > > 
> > > 您好，请问下这个有合并到发布的分支不~
> > 
> > 
> > 现在还没有合并到发布分支
> 
> 您好，能多说点，这个问题发生的原因不，还是有点不明白什么样的case会发生这样的问题，十分感谢~~

看下这个问题 https://github.com/apache/dubbo/issues/7125

**Comment by ethanas** [comment]
我试试，我最近重新还原了重现的代码，发现还是会存在，正在尝试修改

**Comment by ethanas** [comment]
重新还原了重现的代码,使用https://github.com/apache/dubbo/commit/d731a0c0c6362bcc8499727b3239f878a960d67b  此修复方案，发现还是会存在，我重现的代码是同一个服务在一个spring容器中会多次上线的情况，service唯一的区别就是extrakey以及protocol的端口号。复现代码的话可以email我(codeops#163#com)，或者留个邮箱，我打包发下

https://github.com/apache/dubbo/commit/d731a0c0c6362bcc8499727b3239f878a960d67b 还有个问题

ZookeeperRegistry 194行 ChildListener zkListener = listeners.putIfAbsent(listener, childListener);第一put会有null

**Comment by ethanas** [comment]
复现代码已发送我这边的现象是 https://github.com/apache/dubbo/blob/0be2a1bbbf9168490acecaf1eed1bd16cb8db402/dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java#L261  这边根据url是找不到的，导致Not found exported service，实际已经发布

**Comment by ethanas** [comment]
更新：我们在生产环境已经解决此问题，原因是下线、上线消息被监听的时候servicekey是一样的，但是监听消息到达的顺序出现了问题导致应该在exporterMap中的key被后收到下线的消息给remove了（因为上下线的服务key一样），更新了zookeeperRegistry相关代码，代码层次加入类似etcd的消息版本字段，从而判断是否顺序一致。

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issues.
