### ISSUE TITLE
dubbo2.7.7泛化调用找不到方法，下方是具体报错

### ISSUE THREAD

**Issue by Daibhid666** [apache/dubbo#7085]
org.apache.dubbo.rpc.RpcException: Failed to invoke the method searchReportByFilter in the service org.apache.dubbo.rpc.service.GenericService. Tried 1 times of the providers [xxxxxx:20880] (1/1) from the registry xxxxx:2181 on the consumer xxxxxx using the dubbo version 2.7.7. Last error is: Failed to invoke remote method: $invoke, provider: dubbo://xxxxxx:20880/cn.sto.service.manage.protocol.IndexSearchService?anyhost=true&application=share_web_consumer&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=true&init=false&interface=cn.sto.service.manage.protocol.IndexSearchService&metadata-type=remote&methods=searchIndexListByFilter,searchIndexByFilter,searchIndexDetailByFilter,searchReportByFilter&monitor=dubbo%3A%2F%2F192.168.122.73%3A2181%2Forg.apache.dubbo.registry.RegistryService%3Fapplication%3Dshare_web_consumer%26backup%3D192.168.122.74%3A2181%2C192.168.122.75%3A2181%26dubbo%3D2.0.2%26pid%3D49320%26protocol%3Dregistry%26qos.enable%3Dfalse%26refer%3Dapplication%253Dshare_web_consumer%2526dubbo%253D2.0.2%2526interface%253Dorg.apache.dubbo.monitor.MonitorService%2526pid%253D49320%2526qos.enable%253Dfalse%2526register.ip%253D192.168.14.209%2526release%253D2.7.7%2526timestamp%253D1609999040343%26registry%3Dzookeeper%26release%3D2.7.7%26timestamp%3D1609999040340&pid=49320&qos.enable=false&register.ip=192.168.14.209&release=2.7.7&remote.application=sto-service-manage&retries=0&revision=1.0.0&side=consumer&sticky=false&timeout=3000&timestamp=1609988936017&version=1.0.0, cause: org.apache.dubbo.remoting.RemotingException: org.apache.dubbo.rpc.RpcException: cn.sto.service.manage.protocol.IndexSearchService.searchReportByFilter(java.lang.String)
org.apache.dubbo.rpc.RpcException: xxxxx.xxxxx.xxxx(java.lang.String)
	at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:149)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:41)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:145)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:100)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:175)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at com.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:51)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodException:xxxxx.xxxx.xxxxx(java.lang.String)

**Comment by xiaoheng1** [comment]
能提供一个 demo 不？

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
