### ISSUE TITLE
Dubbo 2.7.8 has dependency compatibility [apache commons-lang3] with nacos 1.4.1

### ISSUE THREAD

**Issue by lishangbu** [apache/dubbo#7105]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: macos 
* Java version: 11

### Steps to reproduce this issue

1. upgrade spring-cloud-alibaba 2.2.4.RELEASE
2. startup application

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

Upgraded successfully.

### Actual Result

Application  start up failed because it cannot found commons-lang3 dependency. It removed in nacos 1.4.1,see  [nacos 1.4.1 changelog](https://github.com/alibaba/nacos/releases/tag/1.4.1) 

What actually happens?

If there is an exception, please attach the exception trace:

```
java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
	at org.apache.dubbo.registry.nacos.NacosRegistry.appendIfPresent(NacosRegistry.java:327)
	at org.apache.dubbo.registry.nacos.NacosRegistry.getLegacySubscribedServiceName(NacosRegistry.java:319)
	at org.apache.dubbo.registry.nacos.NacosRegistry.getServiceNames0(NacosRegistry.java:280)
	at org.apache.dubbo.registry.nacos.NacosRegistry.getServiceNames(NacosRegistry.java:267)
	at org.apache.dubbo.registry.nacos.NacosRegistry.doSubscribe(NacosRegistry.java:178)
	at org.apache.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:333)
	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:105)
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:225)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:62)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:153)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:64)
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:492)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:325)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:300)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:206)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.lambda$exportServices$15(DubboBootstrap.java:1103)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:976)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.exportServices(DubboBootstrap.java:1090)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:901)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onContextRefreshedEvent(DubboBootstrapApplicationListener.java:59)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onApplicationContextEvent(DubboBootstrapApplicationListener.java:52)
	at org.apache.dubbo.config.spring.context.OneTimeExecutionApplicationContextEventListener.onApplicationEvent(OneTimeExecutionApplicationContextEventListener.java:40)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:426)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:943)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:591)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at com.demo.Provider.main(Provider.java:16)

```

**Comment by kevinw66** [comment]
You can try add commons-lang3 dependency on your own

**Comment by lishangbu** [comment]
> You can try add commons-lang3 dependency on your own

Of course.But I think that too many same methods is unnecessarily.such as ```org.apache.dubbo.registry.nacos.NacosRegistry#appendIfPresent```

```java

    private void appendIfPresent(StringBuilder target, URL url, String parameterName) {
        String parameterValue = url.getParameter(parameterName);
        if (!org.apache.commons.lang3.StringUtils.isBlank(parameterValue)) {
            target.append(SERVICE_NAME_SEPARATOR).append(parameterValue);
        }
    }
```

MayBe it's a better way to use ```org.apache.dubbo.common.utils.StringUtils``` rather than ```org.apache.commons.lang3.StringUtils``` like other methods in same file,then we do not need to add ```commons-lang3```  dependency when using dubbo and nacos any more.

**Comment by kevinw66** [comment]
Thanks for your advise, I have created a pull request for this issue. [#7106](https://github.com/apache/dubbo/pull/7106)
