### ISSUE TITLE
No such extension com.alibaba.dubbo.registry.RegistryFactory by name nacos

### ISSUE THREAD

**Issue by Chunghwa-2018** [apache/dubbo#7111]
2021-01-19 17:45:17.822 [main] ERROR o.s.boot.SpringApplication-823 Application run failed
java.lang.IllegalStateException: No such extension com.alibaba.dubbo.registry.RegistryFactory by name nacos
	at com.alibaba.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:482)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:489)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:309)
	at com.alibaba.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:206)
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:140)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:98)
	at com.alibaba.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:55)
	at com.alibaba.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:60)
	at com.alibaba.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at com.alibaba.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:515)
	at com.alibaba.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:360)
	at com.alibaba.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:319)
	at com.alibaba.dubbo.config.ServiceConfig.export(ServiceConfig.java:217)
	at com.alibaba.dubbo.config.spring.ServiceBean.export(ServiceBean.java:266)
	at com.alibaba.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:106)
	at com.alibaba.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:53)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:896)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at cn.hx.order.application.OrderServiceApplication.main(OrderServiceApplication.java:19)

see Spring XML configuration driver sample，
No error in configuration。

version Info:

com.alibaba
dubbo-registry-nacos
2.7.6

com.alibaba.nacos
nacos-client
1.4.1

com.alibaba
dubbo
2.6.7

com.alibaba.spring
spring-context-support
1.0.3

**Comment by github-ganyu** [comment]
I think you can use apache dubbo to try.

**Comment by Chunghwa-2018** [comment]
> I think you can use apache dubbo to try.

apache dubbo 也存在此问题，应该是 nacos的包版本太高， dubbo包的版本太低造成的，如果把nacos的版本降低到 2.6.7 以下，【0.0.1，2.67】
