### ISSUE TITLE
泛化实现时Provider端设置 generic 参数无法透传到Consumer端

### ISSUE THREAD

**Issue by gentryhuang** [apache/dubbo#7230]
### Environment

* Dubbo version: 2.7.7
* Java version: 1.8

### Steps to reproduce this issue

1. 泛化实现

   ```java
    @Service
    public class MyGenericService implements GenericService {
    @Override
    public Object $invoke(String method, String[] parameterTypes, Object[] args) throws GenericException {
        if ("sayHello".equals(method)) {
            return "print " + args[0];
        }
        return Result.successResult("not find method!");
      }
   }
   ```

2. 暴露泛化服务

   ```java
   public interface DemoService {
       String sayHello(String var1);
       String work(GenericRequest var1);
     }
   ```

   ```xml
   <dubbo:service interface="com.code.dubbo.DemoService" ref="myGenericService" generic="true"/>
   ```

3. 引用服务

   ```xml
   <dubbo:reference id="demoService" check="false" interface="com.code.dubbo.DemoService"/>
   ```

### Actual Result

```text
java.lang.IllegalArgumentException: Service not found:com.code.dubbo.DemoService, sayHello
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:134)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:80)
	at org.apache.dubbo.remoting.transport.DecodeHandler.decode(DecodeHandler.java:57)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:44)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### 在消费端配置 generic 就可以正常调用

   ```xml
<dubbo:reference id="demoService" check="false" interface="com.code.dubbo.DemoService" generic="true"/>
   ```

**Comment by xiaoheng1** [comment]
In my opinion, this is not a bug. If the consumer does not specify a generalized call when calling, the client will check whether this interface exists.

**Comment by gentryhuang** [comment]
> In my opinion, this is not a bug. If the consumer does not specify a generalized call when calling, the client will check whether this interface exists.

ok，thanks
