### ISSUE TITLE
Dubbo 2.7.8 在消费者端报类型转换错误

### ISSUE THREAD

**Issue by jinshengyong** [apache/dubbo#7274]
服务提供者能够正常启动，但是消费端出现错误
# dubbo 配置
```
# Dubbo
dubbo:
  scan:
    base-packages: cn.funtk.dmy.cloud.fastdfs.controller
  application:
    id: dubbo
    name: dubbo
  protocol:
    id: dubbo
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://${base.config.nacos.hostname}
    port: ${base.config.nacos.port}
```

# 报错的日志
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'uploadController': Injection of @DubboReference dependencies is failed; nested exception is java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Class
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.postProcessPropertyValues(AbstractAnnotationBeanPostProcessor.java:183) ~[spring-context-support-1.0.11.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1425) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.8.RELEASE.jar:2.3.8.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.3.8.RELEASE.jar:2.3.8.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.8.RELEASE.jar:2.3.8.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405) [spring-boot-2.3.8.RELEASE.jar:2.3.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.8.RELEASE.jar:2.3.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.8.RELEASE.jar:2.3.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.8.RELEASE.jar:2.3.8.RELEASE]
	at cn.funtk.dmy.cloud.fastdfs.CloudFastDFSApplication.main(CloudFastDFSApplication.java:22) [classes/:na]
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Class
	at org.apache.dubbo.config.spring.util.DubboAnnotationUtils.resolveServiceInterfaceClass(DubboAnnotationUtils.java:95) ~[dubbo-2.7.8.jar:2.7.8]
	at org.apache.dubbo.config.spring.util.DubboAnnotationUtils.resolveInterfaceName(DubboAnnotationUtils.java:78) ~[dubbo-2.7.8.jar:2.7.8]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ServiceBeanNameBuilder.<init>(ServiceBeanNameBuilder.java:65) ~[dubbo-2.7.8.jar:2.7.8]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ServiceBeanNameBuilder.create(ServiceBeanNameBuilder.java:78) ~[dubbo-2.7.8.jar:2.7.8]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.buildReferencedBeanName(ReferenceAnnotationBeanPostProcessor.java:303) ~[dubbo-2.7.8.jar:2.7.8]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.buildInjectedObjectCacheKey(ReferenceAnnotationBeanPostProcessor.java:292) ~[dubbo-2.7.8.jar:2.7.8]
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.getInjectedObject(AbstractAnnotationBeanPostProcessor.java:404) ~[spring-context-support-1.0.11.jar:na]
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor$AnnotatedFieldElement.inject(AbstractAnnotationBeanPostProcessor.java:626) ~[spring-context-support-1.0.11.jar:na]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.postProcessPropertyValues(AbstractAnnotationBeanPostProcessor.java:179) ~[spring-context-support-1.0.11.jar:na]
	... 18 common frames omitted
```

# 我采用的注解
* @DubboReference(version = DubboVersion.VERSION)
	private StorageService storageService;
* @DubboService(version = DubboVersion.VERSION)

**Comment by huyunhaode** [comment]
Could you pls. provide your config file in your provider?

**Comment by jinshengyong** [comment]
> Could you pls. provide your config file in your provider?

# 提供者配置文件
```
base:
  config:
    nacos:
      hostname: 127.0.0.1
      port: 8848

# Dubbo
dubbo:
  scan:
    base-packages: cn.funtk.dmy.cloud.fastdfs.provider.service
  application:
    id: dubbo
    name: dubbo
  protocol:
    id: dubbo
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://${base.config.nacos.hostname}
    port: ${base.config.nacos.port}
```

# 消费者配置文件
```
base:
  config:
    nacos:
      hostname: 127.0.0.1
      port: 8848

# Dubbo
dubbo:
  scan:
    base-packages: cn.funtk.dmy.cloud.fastdfs.controller
  application:
    id: dubbo
    name: dubbo
  protocol:
    id: dubbo
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://${base.config.nacos.hostname}
    port: ${base.config.nacos.port}

```

**Comment by jinshengyong** [comment]
> > Could you pls. provide your config file in your provider?
> 
> # 提供者配置文件
> ```
> base:
>   config:
>     nacos:
>       hostname: 127.0.0.1
>       port: 8848
> 
> # Dubbo
> dubbo:
>   scan:
>     base-packages: cn.funtk.dmy.cloud.fastdfs.provider.service
>   application:
>     id: dubbo
>     name: dubbo
>   protocol:
>     id: dubbo
>     name: dubbo
>     port: -1
>     serialization: kryo
>   registry:
>     address: nacos://${base.config.nacos.hostname}
>     port: ${base.config.nacos.port}
> ```
> 
> # 消费者配置文件
> ```
> base:
>   config:
>     nacos:
>       hostname: 127.0.0.1
>       port: 8848
> 
> # Dubbo
> dubbo:
>   scan:
>     base-packages: cn.funtk.dmy.cloud.fastdfs.controller
>   application:
>     id: dubbo
>     name: dubbo
>   protocol:
>     id: dubbo
>     name: dubbo
>     port: -1
>     serialization: kryo
>   registry:
>     address: nacos://${base.config.nacos.hostname}
>     port: ${base.config.nacos.port}
> ```



> Could you pls. provide your config file in your provider?

不知道是什么问题导致的

**Comment by AlbumenJ** [comment]
@jinshengyong 根据日志显示的是对应的 `uploadController` 的 bean 出现问题，而不是 `private StorageService storageService;` 导致的问题

**Comment by HeZhanfeng** [comment]
请问这个问题解决了吗?我也遇到了同样的问题

**Comment by HeZhanfeng** [comment]
最后降低了spring-context-support版本问题解决
之前用的1.0.11降为1.0.10

**Comment by jason19659** [comment]
我也遇到了dubbo 2.7.10,curator-recipes 5.1.0 ,zookeeper 3.7.0

**Comment by wuwen5** [comment]
+1

**Comment by jinshengyong** [comment]
> 最后降低了spring-context-support版本问题解决
> 之前用的1.0.11降为1.0.10

# 确实是这样，降低到 1.0.10 版本就可以了

**Comment by AlbumenJ** [comment]
Shall we remove `spring-context-support` dependency in the future?

**Comment by cl-Rainful** [comment]
这个是因为 服务端启动的时候 服务端用的是dubbo自带的ServiceClassPostProcessor 这个类里面getAnnotationAttributes()方法中传进去的classValuesAsString参数是false 这样 @DubboService里面的interfaceClass是void.class是类对象 但是消费者端的@DubboReference被spring-context-support-1.0.11中的AbstractAnnotationBeanPostProcessor这个类解析了 这个类里面getAnnotationAttributes() 方法传进去的参数是true,这样会导致void.class变成字符串  最后在返回的时候  因为接收DubboAnnotationUtils中95行直接使用Class<?>这个类来接收 就会导致报错
具体方法就是升级dubbo的版本到2.7.13目前解决了这个问题
