### ISSUE TITLE
Too many instance bean created for same @DubboReference annotation？

### ISSUE THREAD

**Issue by zhangyz-hd** [apache/dubbo#7367]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.10-SNAPSHOT/master
* Operating System version: ANY
* Java version: 8

### Steps to reproduce this issue

**按节点服务发现**，消费者扫描注解，有2个Bean中通过注解订阅同一个服务，订阅配置相同，但都使用parameters属性。
```
    @DubboReference(version = "2.0", check = false, parameters = {"a", "1"})
    private DemoServiceA1 a1;
```

问题1：先启动提供者，在启动消费者，服务调用正常，然后关闭提供者：消费者不停重连已经下线的提供者，日志报reconnect-timer-task错误信息，同7366的问题2。

问题2：先启动消费者，再启动提供者：消费者分别调用2个service，其中一个service报告noProvider。
```
org.apache.dubbo.rpc.RpcException: No provider available from registry 127.0.0.1:2182 for service org.apache.dubbo.demo.DemoServiceA1:2.0 on consumer 192.168.0.239 use dubbo version , please check status of providers(disabled, not registered or in blacklist).
	at org.apache.dubbo.registry.integration.DynamicDirectory.doList(DynamicDirectory.java:165)
	at org.apache.dubbo.rpc.cluster.directory.AbstractDirectory.list(AbstractDirectory.java:95)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.list(AbstractClusterInvoker.java:297)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:262)
	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:93)
	at org.apache.dubbo.registry.client.migration.ServiceDiscoveryMigrationInvoker.invoke(ServiceDiscoveryMigrationInvoker.java:59)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:95)
	at org.apache.dubbo.common.bytecode.proxy0.sayHello(proxy0.java)
	at org.apache.dubbo.demo.consumer.comp.MyBean1.test(MyBean1.java:31)
	at org.apache.dubbo.demo.consumer.ConsumerAnnot.main(ConsumerAnnot.java:42)
```

### 初步分析：

ReferenceAnnotationBeanPostProcessor#generateReferenceBeanName中，对于parameters的数组，直接entry.getValue()拿到的是数组对象，因此buildReferenceBeanIfAbsent就判断为不同，最后产生了2个Reference实例。
```
        if (!attributes.isEmpty()) {
            beanNameBuilder.append('(');
            for (Map.Entry<String, Object> entry : attributes.entrySet()) {
                beanNameBuilder.append(entry.getKey())
                        .append('=')
                        .append(entry.getValue()) // <----- HERE
                        .append(',');
            }
            // replace the latest "," to be ")"
            beanNameBuilder.setCharAt(beanNameBuilder.lastIndexOf(","), ')');
        }
```

对于问题1：消费者启动时，referenceCount计数器是0>1>2，提供者下线时，消费者referenceCount是2>1，也就是没有回到0，HeaderExchangeClient未close。

对于问题2：提供者启动后时完成注册，消费者其实只刷新了1个Reference的订阅数据，另一个没刷新，造成noProvider。

示例：https://github.com/70-cloud-lab/dubbo-issues/tree/main/210311-reconnect-timer-task-is-still-alive

**Comment by zhangyz-hd** [comment]
## 问题探讨
当我们在让用户使用注解@Reference/@DubboReference时，到底在注解中写哪些属性？如果参照xml属性都开放，势必带来2个问题：
1. 一不小心就产生了多个Reference instance。
2. 当修改同一个订阅服务的属性值时（如timeout）要修改n个地方。
3. 用id表示相同订阅服务的话，那么相同id不同属性（如不同timeout）最后以哪个为准生效？（另，Reference不支持id属性）
4. 问题1和问题2对于传统按接口服务发现，实际也会产生了2个Reference instance，但都无问题1和2。

## 一点想法
- @Reference/@DubboReference上应该只开放部分属性，如用于识别服务的serviceKey的group、interfaceName、version，同时在ReferenceAnnotationBeanPostProcessor生成BeanName时参照serviceKey格式去生成。
- 其余reference属性，都要求配置到properties中（技术上2.7已支持）。
