### ISSUE TITLE
Redis Registry 2.7.9 consumer 启动失败

### ISSUE THREAD

**Issue by hexw** [apache/dubbo#7434]
### Environment

* Dubbo version: 2.7.9
* Operating System version: xxx
* Java version: 1.8

**Comment by hexw** [comment]
从2.7.8升级到2.7.9 使用redis Registry 客户端启动报错

**Comment by hexw** [comment]
由 InterfaceCompatibleRegistryProtocol 引发这个问题

**Comment by hexw** [comment]
直接使用dubbo-demo-annotation 
配置
dubbo.application.name=dubbo-demo-annotation-consumer
dubbo.registry.address=redis://redis:password@$127.0.0:6379?db.index=0
报错
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoServiceComponent': Injection of @DubboReference dependencies is failed; nested exception is java.lang.IllegalStateException: No such extension org.apache.dubbo.registry.client.ServiceDiscovery by name redis, no related exception was found, please check whether related SPI module is missing.
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.postProcessPropertyValues(AbstractAnnotationBeanPostProcessor.java:149)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1425)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:89)
	at org.apache.dubbo.demo.consumer.Application.main(Application.java:34)

**Comment by AlbumenJ** [comment]
> 直接使用dubbo-demo-annotation
> 配置
> dubbo.application.name=dubbo-demo-annotation-consumer
> dubbo.registry.address=redis://redis:password@127.0.0.1:6379?db.index=0
> 报错
> Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoServiceComponent': Injection of @DubboReference dependencies is failed; nested exception is java.lang.IllegalStateException: No such extension org.apache.dubbo.registry.client.ServiceDiscovery by name redis, no related exception was found, please check whether related SPI module is missing.
> at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.postProcessPropertyValues(AbstractAnnotationBeanPostProcessor.java:149)
> at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1425)
> at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
> at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
> at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
> at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
> at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
> at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
> at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897)
> at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
> at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
> at org.springframework.context.annotation.AnnotationConfigApplicationContext.(AnnotationConfigApplicationContext.java:89)
> at org.apache.dubbo.demo.consumer.Application.main(Application.java:34)

For this exception, you may need to import dubbo-registry-redis module.

**Comment by hexw** [comment]
> > 直接使用dubbo-demo-annotation
> > 配置
> > dubbo.application.name=dubbo-demo-annotation-consumer
> > dubbo.registry.address=redis://redis:password@127.0.0.1:6379?db.index=0
> > 报错
> > Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoServiceComponent': Injection of @DubboReference dependencies is failed; nested exception is java.lang.IllegalStateException: No such extension org.apache.dubbo.registry.client.ServiceDiscovery by name redis, no related exception was found, please check whether related SPI module is missing.
> > at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.postProcessPropertyValues(AbstractAnnotationBeanPostProcessor.java:149)
> > at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1425)
> > at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
> > at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
> > at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
> > at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
> > at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
> > at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
> > at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897)
> > at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
> > at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
> > at org.springframework.context.annotation.AnnotationConfigApplicationContext.(AnnotationConfigApplicationContext.java:89)
> > at org.apache.dubbo.demo.consumer.Application.main(Application.java:34)
> 
> For this exception, you may need to import dubbo-registry-redis module.
已经添加依赖
      <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-registry-redis</artifactId>
        </dependency>

**Comment by AlbumenJ** [comment]
This might be redis registry not compatiable with new-model service discovery. We will fix it later.

**Comment by HuRuWo** [comment]
redis 这个问题修复了吗

**Comment by AlbumenJ** [comment]
> redis 这个问题修复了吗

请尝试升级到 2.7.10 看看

**Comment by nosixtools** [comment]
使用内部自研注册中心，提示没有ServiceDiscovery的扩展，这个扩展可以关闭掉，还是要求必须实现这个扩展

[ERROR][2021-07-14T13:39:53.918+0800][org.springframework.boot.SpringApplication:837] _undef||_msg=Application run failed||exception=org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'purchaseUserCityController': Injection of @DubboReference dependencies is failed; nested exception is java.lang.IllegalStateException: No such extension org.apache.dubbo.registry.client.ServiceDiscovery by name disf, no related exception was found, please check whether related SPI module is missing.

**Comment by AlbumenJ** [comment]
> 使用内部自研注册中心，提示没有ServiceDiscovery的扩展，这个扩展可以关闭掉，还是要求必须实现这个扩展
> 
> [ERROR][2021-07-14T13:39:53.918+0800][org.springframework.boot.SpringApplication:837] _undef||_msg=Application run failed||exception=org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'purchaseUserCityController': Injection of @DubboReference dependencies is failed; nested exception is java.lang.IllegalStateException: No such extension org.apache.dubbo.registry.client.ServiceDiscovery by name disf, no related exception was found, please check whether related SPI module is missing.

请升级到 2.7 新版本，这个在高版本已经修复了

**Comment by nosixtools** [comment]
> > 使用内部自研注册中心，提示没有ServiceDiscovery的扩展，这个扩展可以关闭掉，还是要求必须实现这个扩展
> > [ERROR][2021-07-14T13:39:53.918+0800][org.springframework.boot.SpringApplication:837] _undef||_msg=Application run failed||exception=org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'purchaseUserCityController': Injection of @DubboReference dependencies is failed; nested exception is java.lang.IllegalStateException: No such extension org.apache.dubbo.registry.client.ServiceDiscovery by name disf, no related exception was found, please check whether related SPI module is missing.
> 
> 请升级到 2.7 新版本，这个在高版本已经修复了

刚才漏写了，已经用的是2.7.9的版本了，升级到2.7.10还是不行，使用2.7.X 最新的版本吗

**Comment by nosixtools** [comment]
> > > 使用内部自研注册中心，提示没有ServiceDiscovery的扩展，这个扩展可以关闭掉，还是要求必须实现这个扩展
> > > [ERROR][2021-07-14T13:39:53.918+0800][org.springframework.boot.SpringApplication:837] _undef||_msg=Application run failed||exception=org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'purchaseUserCityController': Injection of @DubboReference dependencies is failed; nested exception is java.lang.IllegalStateException: No such extension org.apache.dubbo.registry.client.ServiceDiscovery by name disf, no related exception was found, please check whether related SPI module is missing.
> > 
> > 
> > 请升级到 2.7 新版本，这个在高版本已经修复了
> 
> 刚才漏写了，已经用的是2.7.9的版本了，升级到2.7.10还是不行，使用2.7.X 最新的版本吗

[ERROR][2021-07-14T14:07:47.184+0800][org.springframework.boot.SpringApplication:837] _undef||_msg=Application run failed||exception=org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'purchaseUserCityController': Injection of @DubboReference dependencies is failed; nested exception is java.lang.NullPointerException
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.postProcessPropertyValues(AbstractAnnotationBeanPostProcessor.java:149)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1427)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:895)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at com.cxyx.iscm.flow.purchase.FlowPurchaseServiceApplication.main(FlowPurchaseServiceApplication.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.NullPointerException: null
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribe(ServiceDiscoveryRegistry.java:252)
	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:105)
	at org.apache.dubbo.registry.integration.DynamicDirectory.subscribe(DynamicDirectory.java:151)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doCreateInvoker(RegistryProtocol.java:507)
	at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getServiceDiscoveryInvoker(InterfaceCompatibleRegistryProtocol.java:65)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshServiceDiscoveryInvoker(MigrationInvoker.java:291)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToServiceDiscoveryInvoker(MigrationInvoker.java:112)
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:60)
	at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:103)
	at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:480)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:466)
	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:460)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:72)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:73)
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:373)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:308)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:206)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.doGetInjectedBean(ReferenceAnnotationBeanPostProcessor.java:163)
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.getInjectedObject(AbstractAnnotationBeanPostProcessor.java:362)
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor$AnnotatedFieldElement.inject(AbstractAnnotationBeanPostProcessor.java:542)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.postProcessPropertyValues(AbstractAnnotationBeanPostProcessor.java:145)
	... 26 common frames omitted

**Comment by AlbumenJ** [comment]
> > > 使用内部自研注册中心，提示没有ServiceDiscovery的扩展，这个扩展可以关闭掉，还是要求必须实现这个扩展
> > > [ERROR][2021-07-14T13:39:53.918+0800][org.springframework.boot.SpringApplication:837] _undef||_msg=Application run failed||exception=org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'purchaseUserCityController': Injection of @DubboReference dependencies is failed; nested exception is java.lang.IllegalStateException: No such extension org.apache.dubbo.registry.client.ServiceDiscovery by name disf, no related exception was found, please check whether related SPI module is missing.
> > 
> > 
> > 请升级到 2.7 新版本，这个在高版本已经修复了
> 
> 刚才漏写了，已经用的是2.7.9的版本了，升级到2.7.10还是不行，使用2.7.X 最新的版本吗

请升级到2.7.12看看

**Comment by Everan-1994** [comment]
@nosixtools @AlbumenJ  我的问题也是这样，然后我从3.0.1一直往下试到2.7.9终于成功了 。😀

**Comment by AlbumenJ** [comment]
> @nosixtools @AlbumenJ 我的问题也是这样，然后我从3.0.1一直往下试到2.7.9终于成功了 。😀

Dubbo 3 目前还不支持 Redis 注册中心，预计会在九月份支持

**Comment by linlinjie** [comment]
Dubbo 3 支持 Redis 注册中心了吗

**Comment by hexw** [comment]
> Dubbo 3 支持 Redis 注册中心了吗

https://github.com/apache/dubbo-spi-extensions
