### ISSUE TITLE
If the provider is not started and the consumer is started first, the whole service will not be started

### ISSUE THREAD

**Issue by 15168326318** [apache/dubbo#7470]
dubbo:2.7.9
jdk:1.8
os:windows 10

如果提供者没启动，先启动消费者的话整个服务就启动不了。

**Comment by 15168326318** [comment]
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-03-29 15:09:09,556 ERROR [dubbo-provider] [main] [o.s.boot.SpringApplication:823] trace[] - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hkServiceImpl': Injection of @DubboReference dependencies is failed; nested exception is java.lang.IllegalStateException: Should has at least one way to know which services this interface belongs to, subscription url: consumer://192.168.43.34/com.example.service.UserService?REGISTRY_CLUSTER=ewellRegistryconfig&application=dubbo-provider&category=providers,configurators,routers&check=false&client=curator&default=true&dubbo=2.0.2&id=ewellRegistryconfig&init=false&interface=com.example.service.UserService&metadata-type=remote&methods=getUser,getUserName,testFescar,dubboGenericityTest&pid=9476&qos.enable=false&registry=zookeeper&registry-type=service&release=2.7.9&side=consumer&sticky=false&timeout=12000&timestamp=1617001749289
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.postProcessPropertyValues(AbstractAnnotationBeanPostProcessor.java:149)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1407)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:591)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:866)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at com.example.DubboProviderApplication.main(DubboProviderApplication.java:49)
Caused by: java.lang.IllegalStateException: Should has at least one way to know which services this interface belongs to, subscription url: consumer://192.168.43.34/com.example.service.UserService?REGISTRY_CLUSTER=ewellRegistryconfig&application=dubbo-provider&category=providers,configurators,routers&check=false&client=curator&default=true&dubbo=2.0.2&id=ewellRegistryconfig&init=false&interface=com.example.service.UserService&metadata-type=remote&methods=getUser,getUserName,testFescar,dubboGenericityTest&pid=9476&qos.enable=false&registry=zookeeper&registry-type=service&release=2.7.9&side=consumer&sticky=false&timeout=12000&timestamp=1617001749289
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.doSubscribe(ServiceDiscoveryRegistry.java:263)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribe(ServiceDiscoveryRegistry.java:255)
	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:105)
	at org.apache.dubbo.registry.integration.DynamicDirectory.subscribe(DynamicDirectory.java:137)
	at org.apache.dubbo.registry.client.RegistryProtocol.getInvoker(RegistryProtocol.java:483)
	at org.apache.dubbo.registry.client.RegistryProtocol.doRefer(RegistryProtocol.java:456)
	at org.apache.dubbo.registry.client.RegistryProtocol.refer(RegistryProtocol.java:452)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:72)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:161)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:73)
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:367)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:305)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:204)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.doGetInjectedBean(ReferenceAnnotationBeanPostProcessor.java:144)
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.getInjectedObject(AbstractAnnotationBeanPostProcessor.java:362)
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor$AnnotatedFieldElement.inject(AbstractAnnotationBeanPostProcessor.java:542)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.postProcessPropertyValues(AbstractAnnotationBeanPostProcessor.java:145)
	... 17 common frames omitted
2021-03-29 15:09:10,453 INFO  [dubbo-provider] [DubboShutdownHook] [o.a.dubbo.config.DubboShutdownHook:66] trace[] -  [DUBBO] Run shutdown hook now., dubbo version: 2.7.9, current host: 192.168.43.34
2021-03-29 15:09:10,457 INFO  [dubbo-provider] [DubboShutdownHook] [o.a.d.r.s.AbstractRegistryFactory:66] trace[] -  [DUBBO] Close all registries [org.apache.dubbo.registry.client.ServiceDiscoveryRegistry@2abbf288], dubbo version: 2.7.9, current host: 192.168.43.34

**Comment by kevinw66** [comment]
能麻烦提供一个可以复现的例子吗？

**Comment by 15168326318** [comment]
@Service
@Slf4j
public class HkServiceImpl implements HkService {
    @DubboReference(check = false)
    private com.example.service.UserService UserService;

    @Autowired
    private McsLabOrderAlertMapper mcsLabOrderAlertMapper;

就这样简单的就启动不了啊 @kevinw66

**Comment by 15168326318** [comment]
官方有服务自省的的例子吗，我测试下官方的也行。

**Comment by 15168326318** [comment]
public void doSubscribe(URL url, NotifyListener listener) {
        this.writableMetadataService.subscribeURL(url);
        Set<String> serviceNames = this.getServices(url, listener);
        if (CollectionUtils.isEmpty(serviceNames)) {
            throw new IllegalStateException("Should has at least one way to know which services this interface belongs to, subscription url: " + url);
        } else {
            this.subscribeURLs(url, listener, serviceNames);
        }
    }

服务端没启动，在config/mapping下确实应该没有这个接口的映射信息，找不到是正常的。但不该报错退出，应该是继续间监听自动连接服务端。

**Comment by kevinw66** [comment]
应用级服务发现相关的内容在2.7支持不完善，不建议使用。完善的功能会在3.0版本提供支持

**Comment by 15168326318** [comment]
dubbo 3.2.pre这个完善了吗

**Comment by kevinw66** [comment]
> dubbo 3.0.pre这个完善了吗

pre版本的话应用级服务发现应该是没问题的，可以试一试

**Comment by 15168326318** [comment]
@kevinw66   问个其他为问题，  泛化调用是不是不支持泛型参数啊，我测试发现服务端接收到的对象变成map了。

**Comment by kevinw66** [comment]
> @kevinw66 问个其他为问题， 泛化调用是不是不支持泛型参数啊，我测试发现服务端接收到的对象变成map了。

genericService默认返回的是Map

**Comment by 15168326318** [comment]
我升级到3.0.0.pre.消费端先启动，服务端后启动，那消费端还是不能自动和服务端建立连接。

org.apache.dubbo.rpc.RpcException: Failed to invoke the method getUser in the service com.example.service.UserService. No provider available for the service com.example.service.UserService from registry localhost:2181 on the consumer 192.168.40.145 using the dubbo version 3.0.0.preview. Please check if the providers have been started and registered.
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.checkInvokers(AbstractClusterInvoker.java:288)
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:59)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:265)

**Comment by kevinw66** [comment]
> 我升级到3.0.0.pre.消费端先启动，服务端后启动，那消费端还是不能自动和服务端建立连接。
> 
> org.apache.dubbo.rpc.RpcException: Failed to invoke the method getUser in the service com.example.service.UserService. No provider available for the service com.example.service.UserService from registry localhost:2181 on the consumer 192.168.40.145 using the dubbo version 3.0.0.preview. Please check if the providers have been started and registered.
> at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.checkInvokers(AbstractClusterInvoker.java:288)
> at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:59)
> at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:265)

可以参考一下3.0-preview分支的dubbo-demo里的工程

**Comment by 15168326318** [comment]
我说的是请求参数，不是返回值。我的请求参数是泛型。

**Comment by kevinw66** [comment]
> > > @kevinw66 问个其他为问题， 泛化调用是不是不支持泛型参数啊，我测试发现服务端接收到的对象变成map了。
> > 
> > 
> > genericService默认返回的是Map
> 
> 我说的是请求参数，不是返回值。我的请求参数是泛型。

没有具体了解过这种使用方式，你接口的定义是怎么样的？调用方式呢？我帮你看看

**Comment by AlbumenJ** [comment]
Please feel free to reopen if you have any question.
