### ISSUE TITLE
dubbo(2.5.3)添加自定义filter，jar包方式启动报错

### ISSUE THREAD

**Issue by malversation** [apache/dubbo#7472]
异常如下
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.dubbo.config.ProviderConfig': Error setting property values; nested
xception is org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'filter' threw exception; nested exception is java.lang.IllegalStateException: No such ext
nsion dubboProviderFilter for filter/com.alibaba.dubbo.rpc.Filter
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1639)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1354)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:572)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:514)
        at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1206)
        at org.springframework.beans.factory.BeanFactoryUtils.beansOfTypeIncludingAncestors(BeanFactoryUtils.java:327)
        at com.alibaba.dubbo.config.spring.ServiceBean.afterPropertiesSet(ServiceBean.java:123)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1758)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1695)
        ... 12 more
1、com.alibaba.dubbo.rpc.Filter文件已放在 resources/META-INF/dubbo下，同时也试了resources/META-INF/dubbo/internal路径
2、idea中启动main类没有问题，打成jar包启动报以上异常，已被折磨了两天了
3、跪求解决方案

**Comment by horizonzy** [comment]
检查一下是否是打包方式的问题。解压你的jar包，看里面的内容是否符合你的预期

**Comment by malversation** [comment]
jar包内容符合预期，添加的文件路径也一致。










在 2021-03-30 22:46:02，"赵延" ***@***.***> 写道：

检查一下是否是打包方式的问题。解压你的jar包，看里面的内容是否符合你的预期

**Comment by AlbumenJ** [comment]
Could you please provide your filter configuration file and implement class?

**Comment by CrazyHZM** [comment]
Temporarily close the issues first, if there are still problems, you can open the issues at any time
