### ISSUE TITLE
No provider available for the service xxxx

### ISSUE THREAD

**Issue by wjtien** [apache/dubbo#7473]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.9
* Operating System version: Ubuntu18.04
* Java version: OracleJDK 1.8.171
* 除了zookeeper，全都是在同一台机器上运行，zookeeper是在远程局域网的机子，防火墙已关，iptables全accept
* 同一个zookeeper:
* [zk: 192.168.61.201(CONNECTED) 13] ls /dubbo-test/com.abc.searcher.service.NameService/providers 
[dubbo%3A%2F%2F192.168.61.141%3A20890%2Fcom.abc.searcher.service.NameService%3Fanyhost%3Dfalse%26application%3Dprovider%26deprecated%3Dfalse%26dubbo%3D2.0.2%26dynamic%3Dtrue%26generic%3Dfalse%26interface%3Dcom.abc.searcher.service.NameService%26metadata-type%3Dremote%26methods%3DgetTop10%26pid%3D30820%26release%3D2.7.9%26side%3Dprovider%26timestamp%3D1617010974485]

### Steps to reproduce this issue

1. 起动provider(服务注册成功)
2. 起动consumer
2.1. consumer报错

Pls. provide [GitHub address] to reproduce this issue.

[https://github.com/wjtien/dubbo-test](https://github.com/wjtien/dubbo-test)

### Expected Result

能够正常消费提供的服务

### Actual Result

在[Dubbo-Admin：https://github.com/apache/dubbo-admin](https://github.com/apache/dubbo-admin)中能够消费服务。

If there is an exception, please attach the exception trace:

```

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'namesController': Injection of @DubboReference dependencies is failed; nested exception is java.lang.IllegalStateException: Failed to check the status of the service com.abc.searcher.service.NameService. No provider available for the service com.abc.searcher.service.NameService from the url consumer://192.168.61.141/com.abc.searcher.service.NameService?application=consumer&category=providers,configurators,routers&dubbo=2.0.2&group=dubbo-test&id=org.apache.dubbo.config.RegistryConfig&init=false&interface=com.abc.searcher.service.NameService&metadata-type=remote&methods=getTop10&pid=30505&qos.enable=false&release=2.7.9&side=consumer&sticky=false&timeout=6000&timestamp=1617010835961 to the consumer 192.168.61.141 use dubbo version 2.7.9
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.postProcessPropertyValues(AbstractAnnotationBeanPostProcessor.java:149) ~[spring-context-support-1.0.10.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1420) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:608) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:923) ~[spring-context-5.3.2.jar:5.3.2]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588) ~[spring-context-5.3.2.jar:5.3.2]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.1.jar:2.4.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[spring-boot-2.4.1.jar:2.4.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-2.4.1.jar:2.4.1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[spring-boot-2.4.1.jar:2.4.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[spring-boot-2.4.1.jar:2.4.1]
	at com.abc.consumer.ConsumerApplication.main(ConsumerApplication.java:16) [main/:na]
Caused by: java.lang.IllegalStateException: Failed to check the status of the service com.abc.searcher.service.NameService. No provider available for the service com.abc.searcher.service.NameService from the url consumer://192.168.61.141/com.abc.searcher.service.NameService?application=consumer&category=providers,configurators,routers&dubbo=2.0.2&group=dubbo-test&id=org.apache.dubbo.config.RegistryConfig&init=false&interface=com.abc.searcher.service.NameService&metadata-type=remote&methods=getTop10&pid=30505&qos.enable=false&release=2.7.9&side=consumer&sticky=false&timeout=6000&timestamp=1617010835961 to the consumer 192.168.61.141 use dubbo version 2.7.9
	at org.apache.dubbo.config.ReferenceConfig.checkInvokerAvailable(ReferenceConfig.java:414) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:315) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:204) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.doGetInjectedBean(ReferenceAnnotationBeanPostProcessor.java:144) ~[dubbo-2.7.9.jar:2.7.9]
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.getInjectedObject(AbstractAnnotationBeanPostProcessor.java:362) ~[spring-context-support-1.0.10.jar:na]
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor$AnnotatedFieldElement.inject(AbstractAnnotationBeanPostProcessor.java:542) ~[spring-context-support-1.0.10.jar:na]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.3.2.jar:5.3.2]
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.postProcessPropertyValues(AbstractAnnotationBeanPostProcessor.java:145) ~[spring-context-support-1.0.10.jar:na]
	... 16 common frames omitted

2021-03-29 17:40:36.685  INFO 30505 --- [tor-Framework-0] o.a.c.f.imps.CuratorFrameworkImpl        : backgroundOperationsLoop exiting
2021-03-29 17:40:36.693  INFO 30505 --- [bboShutdownHook] org.apache.zookeeper.ZooKeeper           : Session: 0x1005c9363c00784 closed
2021-03-29 17:40:36.693  INFO 30505 --- [ain-EventThread] org.apache.zookeeper.ClientCnxn          : EventThread shut down for session: 0x1005c9363c00784
Disconnected from the target VM, address: '127.0.0.1:47273', transport: 'socket'

Process finished with exit code 1
```

**Comment by wjtien** [comment]
已解决，消费端必须指定group
org/apache/dubbo/registry/integration/RegistryDirectory.java:206
在org.apache.dubbo.registry.integration.DynamicDirectory#forbidden=true的实候要小心。

在这里打断点：org.apache.dubbo.registry.zookeeper.ZookeeperRegistry#toUrlsWithoutEmpty

org.apache.dubbo.common.utils.UrlUtils#isMatch的方法：
`
public static boolean isMatch(URL consumerUrl, URL providerUrl) {
        String consumerInterface = consumerUrl.getServiceInterface();
        String providerInterface = providerUrl.getServiceInterface();
        //FIXME accept providerUrl with '*' as interface name, after carefully thought about all possible scenarios I think it's ok to add this condition.
        if (!(ANY_VALUE.equals(consumerInterface)
                || ANY_VALUE.equals(providerInterface)
                || StringUtils.isEquals(consumerInterface, providerInterface))) {
            return false;
        }

        if (!isMatchCategory(providerUrl.getParameter(CATEGORY_KEY, DEFAULT_CATEGORY),
                consumerUrl.getParameter(CATEGORY_KEY, DEFAULT_CATEGORY))) {
            return false;
        }
        if (!providerUrl.getParameter(ENABLED_KEY, true)
                && !ANY_VALUE.equals(consumerUrl.getParameter(ENABLED_KEY))) {
            return false;
        }

        String consumerGroup = consumerUrl.getParameter(GROUP_KEY);
        String consumerVersion = consumerUrl.getParameter(VERSION_KEY);
        String consumerClassifier = consumerUrl.getParameter(CLASSIFIER_KEY, ANY_VALUE);

        String providerGroup = providerUrl.getParameter(GROUP_KEY);
        String providerVersion = providerUrl.getParameter(VERSION_KEY);
        String providerClassifier = providerUrl.getParameter(CLASSIFIER_KEY, ANY_VALUE);
        return (ANY_VALUE.equals(consumerGroup) || StringUtils.isEquals(consumerGroup, providerGroup) || StringUtils.isContains(consumerGroup, providerGroup))
                && (ANY_VALUE.equals(consumerVersion) || StringUtils.isEquals(consumerVersion, providerVersion))
                && (consumerClassifier == null || ANY_VALUE.equals(consumerClassifier) || StringUtils.isEquals(consumerClassifier, providerClassifier));
    }`

同时dto也要实现 java.io.Serializable。
Serialized class com.abc.searcher.service.NamesAggOutboundDto must implement java.io.Serializable
