### ISSUE TITLE
Injection of @DubboReference dependencies is failed; nested exception is java.lang.NullPointerException

### ISSUE THREAD

**Issue by wghdir** [apache/dubbo#7636]
I use etcd3 as register center.
    dubbo.application.name=dubbo-demo-annotation-consumer
    dubbo.registry.address=etcd3://127.0.0.1:2379
but run error.
Caused by: java.lang.NullPointerException
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribe(ServiceDiscoveryRegistry.java:252)
	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:105)
	at org.apache.dubbo.registry.integration.DynamicDirectory.subscribe(DynamicDirectory.java:151)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doCreateInvoker(RegistryProtocol.java:507)
the ServiceDiscoveryRegistry not have getUrl,default return null. why?
how to use etcd ?who can give me a demo.

**Comment by xiaoheng1** [comment]
Please provide information about the environment, configuration, dubbo version, etc.

**Comment by wghdir** [comment]
use 2.7.8 and 2.7.9 have no promblem

**Comment by wghdir** [comment]
In ServiceDiscoveryRegistry.java
 @Override
    public final void subscribe(URL url, NotifyListener listener) {
        if (!shouldSubscribe(url)) { // Should Not Subscribe
            return;
        }
        String registryCluster = serviceDiscovery.getUrl().getParameter(ID_KEY);
        if (registryCluster != null && url.getParameter(REGISTRY_CLUSTER_KEY) == null) {
            url = url.addParameter(REGISTRY_CLUSTER_KEY, registryCluster);
        }
        doSubscribe(url, listener);
    }
but in EtcdServiceDiscovery.java has no getUrl(),default call ServiceDiscover.java getUrl()
default URL getUrl() {
        return null;
    }
so return 
 Caused by: java.lang.NullPointerException
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribe(ServiceDiscoveryRegistry.java:252)

**Comment by xiaoheng1** [comment]
Please provide the dubbo version

**Comment by xiaoheng1** [comment]
Sorry, I read the master code, there should be this problem, I submit a pr to fix this problem.

**Comment by AlbumenJ** [comment]
close #7636 via #7659
