### ISSUE TITLE
Apache Dubbo 2.5.7 version heartbeat issue this problem and consumer rpc provider also the same problem

### ISSUE THREAD

**Issue by shinebar** [apache/dubbo#7710]
com.alibaba.dubbo.remoting.exchange.support.header.HeartBeatTask][84]: [DUBBO] Exception when heartbeat to remote channel /10.9.65.168:20811, dubbo version: 2.5.7, current host: 10.10.129.186
com.alibaba.dubbo.remoting.RemotingException: Failed to send message Request [id=185, version=2.0.0, twoway=true, event=true, broken=false, data=null] to /10.9.65.168:20811, cause: No such extension com.alibaba.dubbo.common.serialize.Serialization by name hessian2
	at com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send(NettyChannel.java:108) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.remoting.transport.AbstractClient.send(AbstractClient.java:258) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeChannel.send(HeaderExchangeChannel.java:87) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeChannel.send(HeaderExchangeChannel.java:77) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeClient.send(HeaderExchangeClient.java:108) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.remoting.exchange.support.header.HeartBeatTask.run(HeartBeatTask.java:64) [dubbo-2.5.7.jar:2.5.7]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) [?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IllegalStateException: No such extension com.alibaba.dubbo.common.serialize.Serialization by name hessian2
	at com.alibaba.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:489) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:496) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:317) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.remoting.transport.CodecSupport.getSerialization(CodecSupport.java:62) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.remoting.transport.AbstractCodec.getSerialization(AbstractCodec.java:52) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.encodeRequest(ExchangeCodec.java:206) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.encode(ExchangeCodec.java:68) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCountCodec.encode(DubboCountCodec.java:39) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalEncoder.encode(NettyCodecAdapter.java:81) ~[dubbo-2.5.7.jar:2.5.7]
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:66) ~[netty-3.10.6.Final.jar:?]
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:59) ~[netty-3.10.6.Final.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591) ~[netty-3.10.6.Final.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784) ~[netty-3.10.6.Final.jar:?]
	at org.jboss.netty.channel.SimpleChannelHandler.writeRequested(SimpleChannelHandler.java:292) ~[netty-3.10.6.Final.jar:?]
	at com.alibaba.dubbo.remoting.transport.netty.NettyHandler.writeRequested(NettyHandler.java:99) ~[dubbo-2.5.7.jar:2.5.7]
	at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:254) ~[netty-3.10.6.Final.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591) ~[netty-3.10.6.Final.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582) ~[netty-3.10.6.Final.jar:?]
	at org.jboss.netty.channel.Channels.write(Channels.java:704) ~[netty-3.10.6.Final.jar:?]
	at org.jboss.netty.channel.Channels.write(Channels.java:671) ~[netty-3.10.6.Final.jar:?]
	at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:347) ~[netty-3.10.6.Final.jar:?]
	at com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send(NettyChannel.java:98) ~[dubbo-2.5.7.jar:2.5.7]
	... 13 more
is there jar not dependent on?I can not find this hession2.thanks

**Comment by shinebar** [comment]
[2021-05-10 10:49:05.965][http-nio-8087-exec-10][ERROR][?][]:Failed to invoke the method queryForPage in the service com.cfne.cuckoo.motor.service.sys.IDicService. Tried 1 times of the providers [10.9.65.167:20810] (1/2) from the registry 10.7.71.187:2181 on the consumer 10.10.129.186 using the dubbo version 2.5.7. Last error is: Failed to invoke remote method: queryForPage, provider: dubbo://10.9.65.167:20810/com.cfne.cuckoo.motor.service.sys.IDicService?anyhost=true&application=cuckoo-consumer-motor&check=false&default.check=false&default.cluster=failover&default.dispatcher=message&default.loadbalance=random&default.payload=50000000&default.retries=0&default.timeout=600000&dispatcher=message&dubbo=2.5.7&generic=false&interface=com.cfne.cuckoo.motor.service.sys.IDicService&logger=log4j&methods=saveDic,queryCarType,queryDic,findMaxCode,updateDic,queryCodeValue,selectById,queryForPage,deleteDic&pid=19420&register.ip=10.10.129.186&remote.timestamp=1620612953081&retries=0&revision=0.0.1-SNAPSHOT&side=consumer&timeout=600000&timestamp=1620614864516, cause: Failed to send message Request [id=9, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=queryForPage, parameterTypes=[interface com.cfne.cuckoo.framework.web.context.IRequestArgumentBody], arguments=[com.cfne.cuckoo.framework.web.context.RequestArgumentBody@115408d0], attachments={path=com.cfne.cuckoo.motor.service.sys.IDicService, interface=com.cfne.cuckoo.motor.service.sys.IDicService, version=0.0.0, timeout=600000}]] to /10.9.65.167:20810, cause: No such extension com.alibaba.dubbo.common.serialize.Serialization by name hessian2
com.alibaba.dubbo.remoting.RemotingException: Failed to send message Request [id=9, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=queryForPage, parameterTypes=[interface com.cfne.cuckoo.framework.web.context.IRequestArgumentBody], arguments=[com.cfne.cuckoo.framework.web.context.RequestArgumentBody@115408d0], attachments={path=com.cfne.cuckoo.motor.service.sys.IDicService, interface=com.cfne.cuckoo.motor.service.sys.IDicService, version=0.0.0, timeout=600000}]] to /10.9.65.167:20810, cause: No such extension com.alibaba.dubbo.common.serialize.Serialization by name hessian2

**Comment by xiaoheng1** [comment]
Please upgrade the dubbo version to the latest version

**Comment by AlbumenJ** [comment]
For 2.5.x version is no longer maintained. For this problem, you can try merge hessian2 implementation from 2.6.x to your version.

**Comment by pinxiong** [comment]
@shinebar Can this issue be close? If necessary, we can open it again.

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
