### ISSUE TITLE
No provider Exception after write or delete configurators

### ISSUE THREAD

**Issue by zhangyz-hd** [apache/dubbo#7976]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 
* 提供者：2.7.12
* 消费者：3.0.0-SNAPSHOT
* Operating System version: ANY(win, mac)
* Java version: 8

### Steps to reproduce this issue

注册中心：zookeeper，按接口注册模式

1. 启动服务提供者、启动服务消费者、消费者定时调用服务，调用正常；

2. 向zookeeper写入DemoService的权重修改配置
```
String url = "override://0.0.0.0/org.apache.dubbo.demo.DemoService?category=configurators&dynamic=false&weight=200";
registry.register(URL.valueOf(url));
```
此时消费者端短线短暂的No provider available
```
result :Hello world, response from provider: 192.168.0.46:20880
[14/06/21 00:21:43:278 CST] main-EventThread  INFO support.CacheableFailbackRegistry:  [DUBBO] Evicting urls for service org.apache.dubbo.demo.DemoService, size 1, dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
[14/06/21 00:21:43:278 CST] main-EventThread  INFO zookeeper.ZookeeperRegistry:  [DUBBO] Notify urls for subscribe url dubbo://192.168.0.46/org.apache.dubbo.demo.DemoService?application=dubbo-demo-annotation-consumer&category=providers,configurators,routers&dubbo=2.0.2&interface=org.apache.dubbo.demo.DemoService&metadata-type=remote&methods=sayHello,sayHelloAsync&pid=5000&qos.enable=false&release=3.0.0-SNAPSHOT&side=consumer&sticky=false&timestamp=1623601256583, url size: 1, dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
[14/06/21 00:21:43:278 CST] main-EventThread  INFO integration.RegistryDirectory:  [DUBBO] New url total size, 1, destroyed total size 1, dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
[14/06/21 00:21:43:278 CST] main-EventThread  INFO migration.DefaultMigrationAddressComparator:  [DUBBO] No instance address available, stop compare., dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
result :Hello world, response from provider: 192.168.0.46:20880
[14/06/21 00:21:48:287 CST] main-EventThread  INFO support.CacheableFailbackRegistry:  [DUBBO] Evicting urls for service org.apache.dubbo.demo.DemoService, size 1, dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
[14/06/21 00:21:48:287 CST] main-EventThread  INFO zookeeper.ZookeeperRegistry:  [DUBBO] Notify urls for subscribe url dubbo://192.168.0.46/org.apache.dubbo.demo.DemoService?application=dubbo-demo-annotation-consumer&category=providers,configurators,routers&dubbo=2.0.2&interface=org.apache.dubbo.demo.DemoService&metadata-type=remote&methods=sayHello,sayHelloAsync&pid=5000&qos.enable=false&release=3.0.0-SNAPSHOT&side=consumer&sticky=false&timestamp=1623601256583, url size: 1, dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
[14/06/21 00:21:48:289 CST] main-EventThread  INFO netty4.NettyChannel:  [DUBBO] Close netty channel [id: 0x8f6b7187, L:/192.168.0.46:9340 - R:/192.168.0.46:20880], dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
[14/06/21 00:21:48:291 CST] main-EventThread  WARN dubbo.ReferenceCountExchangeClient:  [DUBBO] 192.168.0.46:20880 org.apache.dubbo.demo.DemoService safe guard client , should not be called ,must have a bug., dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
[14/06/21 00:21:48:292 CST] NettyClientWorker-1-1  INFO netty4.NettyClientHandler:  [DUBBO] The connection of /192.168.0.46:9340 -> /192.168.0.46:20880 is disconnected., dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
org.apache.dubbo.rpc.RpcException: No provider available from registry 127.0.0.1:2181 for service org.apache.dubbo.demo.DemoService on consumer 192.168.0.46 use dubbo version 3.0.0-SNAPSHOT, please check status of providers(disabled, not registered or in blacklist).
	at org.apache.dubbo.registry.integration.RegistryDirectory.doList(RegistryDirectory.java:504)
	at org.apache.dubbo.rpc.cluster.directory.AbstractDirectory.list(AbstractDirectory.java:110)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.list(AbstractClusterInvoker.java:308)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:262)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:89)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:51)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.cluster.filter.support.ConsumerContextFilter.invoke(ConsumerContextFilter.java:101)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$ClusterFilterInvoker.invoke(AbstractCluster.java:93)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:93)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.invoke(MigrationInvoker.java:277)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:95)
	at org.apache.dubbo.common.bytecode.proxy0.sayHello(proxy0.java)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205)
	at com.sun.proxy.$Proxy27.sayHello(Unknown Source)
	at org.apache.dubbo.demo.consumer.comp.DemoServiceComponent.sayHello(DemoServiceComponent.java:33)
	at org.apache.dubbo.demo.consumer.AppConsumer.main(AppConsumer.java:39)
org.apache.dubbo.rpc.RpcException: No provider available from registry 127.0.0.1:2181 for service org.apache.dubbo.demo.DemoService on consumer 192.168.0.46 use dubbo version 3.0.0-SNAPSHOT, please check status of providers(disabled, not registered or in blacklist).
	at org.apache.dubbo.registry.integration.RegistryDirectory.doList(RegistryDirectory.java:504)
	at org.apache.dubbo.rpc.cluster.directory.AbstractDirectory.list(AbstractDirectory.java:110)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.list(AbstractClusterInvoker.java:308)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:262)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:89)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:51)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.cluster.filter.support.ConsumerContextFilter.invoke(ConsumerContextFilter.java:101)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$ClusterFilterInvoker.invoke(AbstractCluster.java:93)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:93)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.invoke(MigrationInvoker.java:277)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:95)
	at org.apache.dubbo.common.bytecode.proxy0.sayHello(proxy0.java)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205)
	at com.sun.proxy.$Proxy27.sayHello(Unknown Source)
	at org.apache.dubbo.demo.consumer.comp.DemoServiceComponent.sayHello(DemoServiceComponent.java:33)
	at org.apache.dubbo.demo.consumer.AppConsumer.main(AppConsumer.java:39)
[14/06/21 00:21:53:288 CST] main-EventThread  INFO zookeeper.ZookeeperRegistry:  [DUBBO] Notify urls for subscribe url dubbo://192.168.0.46/org.apache.dubbo.demo.DemoService?application=dubbo-demo-annotation-consumer&category=providers,configurators,routers&dubbo=2.0.2&interface=org.apache.dubbo.demo.DemoService&metadata-type=remote&methods=sayHello,sayHelloAsync&pid=5000&qos.enable=false&release=3.0.0-SNAPSHOT&side=consumer&sticky=false&timestamp=1623601256583, url size: 1, dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
[14/06/21 00:21:53:288 CST] main-EventThread  INFO migration.DefaultMigrationAddressComparator:  [DUBBO] No instance address available, stop compare., dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
[14/06/21 00:21:54:801 CST] main  INFO dubbo.LazyConnectExchangeClient:  [DUBBO] Lazy connect to dubbo://192.168.0.46:20880/org.apache.dubbo.demo.DemoService?anyhost=true&application=dubbo-demo-annotation-provider&check=false&codec=dubbo&connect.lazy.initial.state=true&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&heartbeat=60000&interface=org.apache.dubbo.demo.DemoService&metadata-type=remote&methods=sayHello,sayHelloAsync&release=2.7.12&send.reconnect=true&service.name=ServiceBean:/org.apache.dubbo.demo.DemoService&side=provider, dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
[14/06/21 00:21:54:801 CST] main  INFO transport.AbstractClient:  [DUBBO] Successed connect to server /192.168.0.46:20880 from NettyClient 192.168.0.46 using dubbo version 3.0.0-SNAPSHOT, channel is NettyChannel [channel=[id: 0x1588cc69, L:/192.168.0.46:9353 - R:/192.168.0.46:20880]], dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
[14/06/21 00:21:54:801 CST] NettyClientWorker-1-2  INFO netty4.NettyClientHandler:  [DUBBO] The connection of /192.168.0.46:9353 -> /192.168.0.46:20880 is established., dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
[14/06/21 00:21:54:801 CST] main  INFO transport.AbstractClient:  [DUBBO] Start NettyClient /192.168.0.46 connect to the server /192.168.0.46:20880, dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
result :Hello world, response from provider: 192.168.0.46:20880

```
3. 删除该条权重修改配置
```
String url = "override://0.0.0.0/org.apache.dubbo.demo.DemoService?category=configurators&dynamic=false&weight=200";
registry.unregister(URL.valueOf(url));
```
消费者端又出现短暂的No provider available
```
result :Hello world, response from provider: 192.168.0.46:20880
[14/06/21 00:22:08:340 CST] main-EventThread  INFO support.CacheableFailbackRegistry:  [DUBBO] Evicting urls for service org.apache.dubbo.demo.DemoService, size 1, dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
[14/06/21 00:22:08:340 CST] main-EventThread  INFO zookeeper.ZookeeperRegistry:  [DUBBO] Notify urls for subscribe url dubbo://192.168.0.46/org.apache.dubbo.demo.DemoService?application=dubbo-demo-annotation-consumer&category=providers,configurators,routers&dubbo=2.0.2&interface=org.apache.dubbo.demo.DemoService&metadata-type=remote&methods=sayHello,sayHelloAsync&pid=5000&qos.enable=false&release=3.0.0-SNAPSHOT&side=consumer&sticky=false&timestamp=1623601256583, url size: 1, dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
[14/06/21 00:22:08:341 CST] main-EventThread  INFO netty4.NettyChannel:  [DUBBO] Close netty channel [id: 0x1588cc69, L:/192.168.0.46:9353 - R:/192.168.0.46:20880], dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
[14/06/21 00:22:08:341 CST] NettyClientWorker-1-2  INFO netty4.NettyClientHandler:  [DUBBO] The connection of /192.168.0.46:9353 -> /192.168.0.46:20880 is disconnected., dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
org.apache.dubbo.rpc.RpcException: No provider available from registry 127.0.0.1:2181 for service org.apache.dubbo.demo.DemoService on consumer 192.168.0.46 use dubbo version 3.0.0-SNAPSHOT, please check status of providers(disabled, not registered or in blacklist).
	at org.apache.dubbo.registry.integration.RegistryDirectory.doList(RegistryDirectory.java:504)
	at org.apache.dubbo.rpc.cluster.directory.AbstractDirectory.list(AbstractDirectory.java:110)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.list(AbstractClusterInvoker.java:308)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:262)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:89)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:51)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.cluster.filter.support.ConsumerContextFilter.invoke(ConsumerContextFilter.java:101)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$ClusterFilterInvoker.invoke(AbstractCluster.java:93)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:93)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.invoke(MigrationInvoker.java:277)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:95)
	at org.apache.dubbo.common.bytecode.proxy0.sayHello(proxy0.java)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205)
	at com.sun.proxy.$Proxy27.sayHello(Unknown Source)
	at org.apache.dubbo.demo.consumer.comp.DemoServiceComponent.sayHello(DemoServiceComponent.java:33)
	at org.apache.dubbo.demo.consumer.AppConsumer.main(AppConsumer.java:39)
org.apache.dubbo.rpc.RpcException: No provider available from registry 127.0.0.1:2181 for service org.apache.dubbo.demo.DemoService on consumer 192.168.0.46 use dubbo version 3.0.0-SNAPSHOT, please check status of providers(disabled, not registered or in blacklist).
	at org.apache.dubbo.registry.integration.RegistryDirectory.doList(RegistryDirectory.java:504)
	at org.apache.dubbo.rpc.cluster.directory.AbstractDirectory.list(AbstractDirectory.java:110)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.list(AbstractClusterInvoker.java:308)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:262)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:89)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:51)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.cluster.filter.support.ConsumerContextFilter.invoke(ConsumerContextFilter.java:101)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$ClusterFilterInvoker.invoke(AbstractCluster.java:93)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:93)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.invoke(MigrationInvoker.java:277)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:95)
	at org.apache.dubbo.common.bytecode.proxy0.sayHello(proxy0.java)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205)
	at com.sun.proxy.$Proxy27.sayHello(Unknown Source)
	at org.apache.dubbo.demo.consumer.comp.DemoServiceComponent.sayHello(DemoServiceComponent.java:33)
	at org.apache.dubbo.demo.consumer.AppConsumer.main(AppConsumer.java:39)
[14/06/21 00:22:13:340 CST] main-EventThread  INFO zookeeper.ZookeeperRegistry:  [DUBBO] Notify urls for subscribe url dubbo://192.168.0.46/org.apache.dubbo.demo.DemoService?application=dubbo-demo-annotation-consumer&category=providers,configurators,routers&dubbo=2.0.2&interface=org.apache.dubbo.demo.DemoService&metadata-type=remote&methods=sayHello,sayHelloAsync&pid=5000&qos.enable=false&release=3.0.0-SNAPSHOT&side=consumer&sticky=false&timestamp=1623601256583, url size: 1, dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
org.apache.dubbo.rpc.RpcException: No provider available from registry 127.0.0.1:2181 for service org.apache.dubbo.demo.DemoService on consumer 192.168.0.46 use dubbo version 3.0.0-SNAPSHOT, please check status of providers(disabled, not registered or in blacklist).
	at org.apache.dubbo.registry.integration.RegistryDirectory.doList(RegistryDirectory.java:504)
	at org.apache.dubbo.rpc.cluster.directory.AbstractDirectory.list(AbstractDirectory.java:110)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.list(AbstractClusterInvoker.java:308)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:262)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:89)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:51)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.cluster.filter.support.ConsumerContextFilter.invoke(ConsumerContextFilter.java:101)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$ClusterFilterInvoker.invoke(AbstractCluster.java:93)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:93)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.invoke(MigrationInvoker.java:277)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:95)
	at org.apache.dubbo.common.bytecode.proxy0.sayHello(proxy0.java)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205)
	at com.sun.proxy.$Proxy27.sayHello(Unknown Source)
	at org.apache.dubbo.demo.consumer.comp.DemoServiceComponent.sayHello(DemoServiceComponent.java:33)
	at org.apache.dubbo.demo.consumer.AppConsumer.main(AppConsumer.java:39)
[14/06/21 00:22:18:347 CST] main-EventThread  INFO zookeeper.ZookeeperRegistry:  [DUBBO] Notify urls for subscribe url dubbo://192.168.0.46/org.apache.dubbo.demo.DemoService?application=dubbo-demo-annotation-consumer&category=providers,configurators,routers&dubbo=2.0.2&interface=org.apache.dubbo.demo.DemoService&metadata-type=remote&methods=sayHello,sayHelloAsync&pid=5000&qos.enable=false&release=3.0.0-SNAPSHOT&side=consumer&sticky=false&timestamp=1623601256583, url size: 1, dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
[14/06/21 00:22:18:349 CST] main-EventThread  INFO migration.DefaultMigrationAddressComparator:  [DUBBO] No instance address available, stop compare., dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
[14/06/21 00:22:18:881 CST] main  INFO dubbo.LazyConnectExchangeClient:  [DUBBO] Lazy connect to dubbo://192.168.0.46:20880/org.apache.dubbo.demo.DemoService?anyhost=true&application=dubbo-demo-annotation-provider&check=false&codec=dubbo&connect.lazy.initial.state=true&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&heartbeat=60000&interface=org.apache.dubbo.demo.DemoService&metadata-type=remote&methods=sayHello,sayHelloAsync&release=2.7.12&send.reconnect=true&service.name=ServiceBean:/org.apache.dubbo.demo.DemoService&side=provider, dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
[14/06/21 00:22:18:881 CST] NettyClientWorker-1-3  INFO netty4.NettyClientHandler:  [DUBBO] The connection of /192.168.0.46:9354 -> /192.168.0.46:20880 is established., dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
[14/06/21 00:22:18:881 CST] main  INFO transport.AbstractClient:  [DUBBO] Successed connect to server /192.168.0.46:20880 from NettyClient 192.168.0.46 using dubbo version 3.0.0-SNAPSHOT, channel is NettyChannel [channel=[id: 0x1a949419, L:/192.168.0.46:9354 - R:/192.168.0.46:20880]], dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
[14/06/21 00:22:18:881 CST] main  INFO transport.AbstractClient:  [DUBBO] Start NettyClient /192.168.0.46 connect to the server /192.168.0.46:20880, dubbo version: 3.0.0-SNAPSHOT, current host: 192.168.0.46
result :Hello world, response from provider: 192.168.0.46:20880

```

**Comment by zhangyz-hd** [comment]
补充场景：
DemoService有2个提供者下，禁用其中一个提供者，再启用它后（即registry.register和registry.unregister时指定提供者URL），消费者端也出现No provider available from registry
