### ISSUE TITLE
Dubbo 2.6.x may not support multi group consumer

### ISSUE THREAD

**Issue by qixiaobo** [apache/dubbo#7985]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.4
* Operating System version: *unix
* Java version: 1.8

### Steps to reproduce this issue

1. set dubbo producer group   test
2. not set dubbo service group
3. set dubbo reference group multi_group(test,xxx)

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

dubbo can invoke specify group service 

### Actual Result

dubbo throws exception

If there is an exception, please attach the exception trace:

```
com.alibaba.dubbo.remoting.RemotingException: Not found exported service: devp495,f6-test/xxx.UserOrgApi:20880 in [f6-test/xxx], may be version or group mismatch , channel: consumer: /10.203.67.52:33238 --> provider: /10.203.64.14:20880, message:RpcInvocation [methodName=queryPermissionOrgIdsByUserId, parameterTypes=[class java.math.BigInteger], arguments=[xxx], attachments={path=xxx.UserOrgApi, input=782, dubboApplication=f6-maintain, _clientInfo={"idOwnOrg":"10907434497393153693","remoteIp":null,"idOwnGroup":"10907434497393152194","udf":null,"from":"maintain","user":"14870719207238203027"}, dubbo=2.0.2, interface=xxx.UserOrgApi version=0.0.0, timeout=3000, group=devp495,f6-test}]
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:213)
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:79)
        at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:96)
        at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:173)
        at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
        at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:100)
```

**Comment by qixiaobo** [comment]
I found that dubbo url class  has some special features
```java
    public String getParameter(String key) {
        String value = parameters.get(key);
        if (value == null || value.length() == 0) {
            value = parameters.get(Constants.DEFAULT_KEY_PREFIX + key);
        }
        return value;
    }
```
As we see, if xxx has no value then it may fallback to default.xxx
But in this case, dubbo just use the map.
```java
 Map<String, String> remoteMap = remoteUrl.getParameters();
```
So ，it may ignore some case.
From my opion
```java

            String defaultVersion = remoteMap.get(Constants.DEFAULT_KEY_PREFIX +Constants.VERSION_KEY);
            if (defaultVersion != null && defaultVersion.length() > 0) {
                map.put(Constants.DEFAULT_KEY_PREFIX +Constants.VERSION_KEY, defaultVersion);
            }
            String version = remoteMap.get(Constants.VERSION_KEY);
            if (version != null && version.length() > 0) {
                map.put(Constants.VERSION_KEY, version);
            }
           String defaultGroup = remoteMap.get(Constants.DEFAULT_KEY_PREFIX + Constants.GROUP_KEY);
            if (defaultGroup != null && defaultGroup.length() > 0) {
                map.put(Constants.DEFAULT_KEY_PREFIX +Constants.GROUP_KEY, defaultGroup);
            }
            String group = remoteMap.get(Constants.GROUP_KEY);
            if (group != null && group.length() > 0) {
                map.put(Constants.GROUP_KEY, group);
            }
           
```

So it may be add a method to do this.
In my case ，I cannot modify dubbo version. So I just add a javaagent to make workaroud.

```java
@Override
    protected void before(Advice advice) throws ProcessControlException, InvocationTargetException,
            NoSuchMethodException,
            IllegalAccessException {
        Map<String, String> localParametersMap = (Map<String, String>) advice.getParameterArray()[1];
        if (localParametersMap != null && localParametersMap.size() > 0) {
            Map<String, String> copyOfLocalMap = new HashMap<>(localParametersMap);
            copyOfLocalMap.remove(GROUP_KEY);
            copyOfLocalMap.remove(DEFAULT_KEY_PREFIX + GROUP_KEY);
            advice.changeParameter(1, copyOfLocalMap);
            logger.info("we remove default.group and group to avoid multi group support exception .Plz ref to " +
                    "https://github.com/apache/dubbo/issues/7985 !");
        }

```
I would remove local map to do this just like add a remote key!

**Comment by qixiaobo** [comment]
I would try to  make a pr to fix this
