### ISSUE TITLE
[3.0] Zookeeper watcher cannot remove correctly

### ISSUE THREAD

**Issue by kevinw66** [apache/dubbo#8009]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.0-SNAPSHOT

### Steps to reproduce this issue

1. Run dubbo-demo-annotation-provider
2.Run dubbo-demo-annotation-consumer

```
08/06/21 19:18:57:463 CST] DubboShutdownHook  INFO config.DubboShutdownHook:  [DUBBO] Run shutdown hook now., dubbo version: , current host: 192.168.100.176
[08/06/21 19:18:57:464 CST] SpringContextShutdownHook  INFO annotation.ReferenceAnnotationBeanPostProcessor: class org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor was destroying!
[08/06/21 19:18:57:477 CST] DubboShutdownHook  WARN integration.DynamicDirectory:  [DUBBO] unexpected error when unsubscribe service org.apache.dubbo.demo.DemoServicefrom registryzookeeper://127.0.0.1:2181/org.apache.dubbo.registry.RegistryService?application=dubbo-demo-annotation-consumer&dubbo=2.0.2&interface=org.apache.dubbo.registry.RegistryService&pid=36142, dubbo version: , current host: 192.168.100.176
java.lang.IllegalArgumentException: unsubscribe url == null
	at org.apache.dubbo.registry.support.AbstractRegistry.unsubscribe(AbstractRegistry.java:326)
	at org.apache.dubbo.registry.support.FailbackRegistry.unsubscribe(FailbackRegistry.java:328)
	at org.apache.dubbo.registry.ListenerRegistryWrapper.unsubscribe(ListenerRegistryWrapper.java:130)
	at org.apache.dubbo.registry.integration.DynamicDirectory.destroy(DynamicDirectory.java:239)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.destroy(AbstractClusterInvoker.java:110)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.destroy(MockClusterInvoker.java:78)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.destroy(MigrationInvoker.java:300)
	at org.apache.dubbo.config.ReferenceConfig.destroy(ReferenceConfig.java:222)
	at org.apache.dubbo.config.utils.ReferenceConfigCache.lambda$destroyAll$6(ReferenceConfigCache.java:220)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.apache.dubbo.config.utils.ReferenceConfigCache.destroyAll(ReferenceConfigCache.java:219)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.unreferServices(DubboBootstrap.java:1325)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.destroy(DubboBootstrap.java:1404)
	at org.apache.dubbo.common.function.ThrowableAction.execute(ThrowableAction.java:46)
	at org.apache.dubbo.common.lang.ShutdownHookCallbacks.lambda$callback$0(ShutdownHookCallbacks.java:70)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.apache.dubbo.common.lang.ShutdownHookCallbacks.callback(ShutdownHookCallbacks.java:70)
	at org.apache.dubbo.config.DubboShutdownHook.callback(DubboShutdownHook.java:84)
	at org.apache.dubbo.config.DubboShutdownHook.run(DubboShutdownHook.java:71)
[08/06/21 19:18:57:488 CST] DubboShutdownHook  INFO listener.ServiceInstancesChangedListener:  [DUBBO] Interface listener of interface org.apache.dubbo.demo.DemoService:dubbo removed., dubbo version: , current host: 192.168.100.176
[08/06/21 19:18:57:488 CST] DubboShutdownHook  INFO listener.ServiceInstancesChangedListener:  [DUBBO] No interface listeners exist, will stop instance listener for [127.0.0.1, dubbo-demo-annotation-provider], dubbo version: , current host: 192.168.100.176
[08/06/21 19:18:57:489 CST] DubboShutdownHook  WARN integration.DynamicDirectory:  [DUBBO] unexpected error when unsubscribe service org.apache.dubbo.demo.DemoServicefrom registryzookeeper://127.0.0.1:2181/org.apache.dubbo.registry.RegistryService?application=dubbo-demo-annotation-consumer&dubbo=2.0.2&interface=org.apache.dubbo.registry.RegistryService&pid=36142, dubbo version: , current host: 192.168.100.176
java.lang.NullPointerException
	at org.apache.dubbo.registry.zookeeper.ZookeeperServiceDiscovery.lambda$removeServiceInstancesChangedListener$5(ZookeeperServiceDiscovery.java:186)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.apache.dubbo.registry.zookeeper.ZookeeperServiceDiscovery.removeServiceInstancesChangedListener(ZookeeperServiceDiscovery.java:184)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.removeListener(ServiceInstancesChangedListener.java:191)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.doUnsubscribe(ServiceDiscoveryRegistry.java:275)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.unsubscribe(ServiceDiscoveryRegistry.java:255)
	at org.apache.dubbo.registry.ListenerRegistryWrapper.unsubscribe(ListenerRegistryWrapper.java:130)
	at org.apache.dubbo.registry.integration.DynamicDirectory.destroy(DynamicDirectory.java:239)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.destroy(AbstractClusterInvoker.java:110)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.destroy(MockClusterInvoker.java:78)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.destroy(MigrationInvoker.java:303)
	at org.apache.dubbo.config.ReferenceConfig.destroy(ReferenceConfig.java:222)
	at org.apache.dubbo.config.utils.ReferenceConfigCache.lambda$destroyAll$6(ReferenceConfigCache.java:220)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.apache.dubbo.config.utils.ReferenceConfigCache.destroyAll(ReferenceConfigCache.java:219)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.unreferServices(DubboBootstrap.java:1325)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.destroy(DubboBootstrap.java:1404)
	at org.apache.dubbo.common.function.ThrowableAction.execute(ThrowableAction.java:46)
	at org.apache.dubbo.common.lang.ShutdownHookCallbacks.lambda$callback$0(ShutdownHookCallbacks.java:70)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.apache.dubbo.common.lang.ShutdownHookCallbacks.callback(ShutdownHookCallbacks.java:70)
	at org.apache.dubbo.config.DubboShutdownHook.callback(DubboShutdownHook.java:84)
	at org.apache.dubbo.config.DubboShutdownHook.run(DubboShutdownHook.java:71)
```

**Comment by chickenlj** [comment]
https://github.com/apache/dubbo/pull/7996
