### ISSUE TITLE
[3.0] Dubbo service export encountered java.lang.IllegalStateException: the metadata report was not inited.

### ISSUE THREAD

**Issue by kevinw66** [apache/dubbo#8033]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.0-SNAPSHOT
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. run dubbo-demo-annotation-provider

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
[11/06/21 16:25:16:602 CST] main  WARN metadata.MetadataServiceNameMapping:  [DUBBO] the metadata report was not inited., dubbo version: , current host: 192.168.100.176
java.lang.IllegalStateException: the metadata report was not inited.
	at org.apache.dubbo.metadata.report.MetadataReportInstance.checkInit(MetadataReportInstance.java:83)
	at org.apache.dubbo.metadata.report.MetadataReportInstance.getMetadataReport(MetadataReportInstance.java:72)
	at org.apache.dubbo.registry.client.metadata.MetadataServiceNameMapping.lambda$map$0(MetadataServiceNameMapping.java:56)
	at org.apache.dubbo.registry.client.metadata.MetadataServiceNameMapping.execute(MetadataServiceNameMapping.java:103)
	at org.apache.dubbo.registry.client.metadata.MetadataServiceNameMapping.map(MetadataServiceNameMapping.java:50)
	at org.apache.dubbo.config.ServiceConfig.lambda$exported$0(ServiceConfig.java:221)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.apache.dubbo.config.ServiceConfig.exported(ServiceConfig.java:219)
	at org.apache.dubbo.config.spring.ServiceBean.exported(ServiceBean.java:113)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:315)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:213)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.exportServices(DubboBootstrap.java:1266)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:1070)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onContextRefreshedEvent(DubboBootstrapApplicationListener.java:70)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onApplicationContextEvent(DubboBootstrapApplicationListener.java:63)
	at com.alibaba.spring.context.OnceApplicationContextEventListener.onApplicationEvent(OnceApplicationContextEventListener.java:52)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:898)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:89)
	at org.apache.dubbo.demo.provider.Application.main(Application.java:29)
```

**Comment by horizonzy** [comment]
3.0 branch's service introspection based on metadataReport, so it should depends on metadata-report dependency.

**Comment by horizonzy** [comment]
![image](https://user-images.githubusercontent.com/22524871/121675675-4e4ead80-cae6-11eb-8b41-81f4b1a52a2d.png)

If the metadataReport dependency absent, the registry won't be as metadata-report.
