### ISSUE TITLE
[Dubbo 3] Load custom filter failed

### ISSUE THREAD

**Issue by kylixs** [apache/dubbo#8110]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.x
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. Custom a filter
```java
import org.apache.dubbo.rpc.Filter;
...
public class MockFilter implements Filter {
...
}
```

2. Use the filter in `@DubboReference` annotation
```java
@DubboReference(filter = {"mymock"})
private HelloService helloService;
```

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

Load the filter successfully.

### Actual Result

What actually happens?

Load filter failed.

```
java.lang.IllegalStateException: No such extension org.apache.dubbo.rpc.cluster.filter.ClusterFilter by name mymock, no related exception was found, please check whether related SPI module is missing.

	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:670)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:677)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:477)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:461)
	at org.apache.dubbo.common.extension.ExtensionLoader.getActivateExtension(ExtensionLoader.java:334)
	at org.apache.dubbo.common.extension.ExtensionLoader.getActivateExtension(ExtensionLoader.java:265)
	at org.apache.dubbo.rpc.cluster.filter.DefaultFilterChainBuilder.buildClusterInvokerChain(DefaultFilterChainBuilder.java:55)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$ClusterFilterInvoker.<init>(AbstractCluster.java:85)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster.buildClusterInterceptors(AbstractCluster.java:49)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster.join(AbstractCluster.java:62)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterWrapper.join(MockClusterWrapper.java:39)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doCreateInvoker(RegistryProtocol.java:516)
	at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getInvoker(InterfaceCompatibleRegistryProtocol.java:58)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshInterfaceInvoker(MigrationInvoker.java:449)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToApplicationFirstInvoker(MigrationInvoker.java:240)
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.refreshInvoker(MigrationRuleHandler.java:80)
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:64)
	at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:151)
	at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:485)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:467)
	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:452)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:74)
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:68)
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:392)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:328)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:205)
```

**Comment by Johnson-Jia** [comment]
一样的问题。
配置 org.apache.dubbo.rpc.Filter 自定义Filter 会自动采用  org.apache.dubbo.rpc.cluster.filter.ClusterFilter  去匹配对应的自定义 Filter

**Comment by Johnson-Jia** [comment]
一样的问题。
配置 org.apache.dubbo.rpc.Filter 自定义Filter 会自动采用  org.apache.dubbo.rpc.cluster.filter.ClusterFilter  去匹配对应的自定义 Filter


```
java.lang.IllegalStateException: No such extension org.apache.dubbo.rpc.cluster.filter.ClusterFilter by name dubboContentConsumerFilter, no related exception was found, please check whether related SPI module is missing.
	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:670)
```

![image](https://user-images.githubusercontent.com/13517143/124886682-0fd5e100-e007-11eb-9104-5c54e75d2ec2.png)

**Comment by Johnson-Jia** [comment]
@kylixs   因为如下代码引起的问题， 意思是否为 增加Filter  必须也增加一个 ClusterFilter的SPI 文件配置
![image](https://user-images.githubusercontent.com/13517143/124887794-144ec980-e008-11eb-80c2-5d011f538032.png)

**Comment by Johnson-Jia** [comment]
解决了  @kylixs   需要在  org.apache.dubbo.rpc.cluster.filter.ClusterFilter  上加一个与之同名的 Filter 如下：
@AlbumenJ  这是一个bug 吗？
![image](https://user-images.githubusercontent.com/13517143/124893027-f768c500-e00c-11eb-8223-2e95a2bf9241.png)

**Comment by AlbumenJ** [comment]
> 解决了 @kylixs 需要在 org.apache.dubbo.rpc.cluster.filter.ClusterFilter 上加一个与之同名的 Filter 如下：
> @AlbumenJ 这是一个bug 吗？
> ![image](https://user-images.githubusercontent.com/13517143/124893027-f768c500-e00c-11eb-8223-2e95a2bf9241.png)

这个在下个版本修复下 `buildClusterInvokerChain` 的兼容逻辑，不应该在其他过滤器下加同名 Filter 的

**Comment by Johnson-Jia** [comment]
soga

**Comment by EarthChen** [comment]
> 一样的问题。
> 配置 org.apache.dubbo.rpc.Filter 自定义Filter 会自动采用 org.apache.dubbo.rpc.cluster.filter.ClusterFilter 去匹配对应的自定义 Filter
> 
> ```
> java.lang.IllegalStateException: No such extension org.apache.dubbo.rpc.cluster.filter.ClusterFilter by name dubboContentConsumerFilter, no related exception was found, please check whether related SPI module is missing.
> 	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:670)
> ```
> 
> ![image](https://user-images.githubusercontent.com/13517143/124886682-0fd5e100-e007-11eb-9104-5c54e75d2ec2.png)

同样的问题，目前的方案是写一个filter然后filter和clusterfilter都配置一遍嘛？  
在问个相关问题  自定义exceptionfilter实现抛出自定义异常  在提供者配置好，消费者拿到的还是rpcexception 这是啥问题？

**Comment by CrazyHZM** [comment]
The problem has been resolved in the 3.0.4 version
