### ISSUE TITLE
dubbo2.7.8升级到dubbo3.0后自定义Filter失效,无法启动

### ISSUE THREAD

**Issue by caohenghui** [apache/dubbo#8193]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.0
* Operating System version: centos7.0
* Java version: 1.8

### Steps to reproduce this issue

dubbo2.7.8升级到dubbo3.0后自定义Filter失效,无法启动

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
java.lang.IllegalStateException: No such extension logSessionFilter for file/org.apache.dubbo.rpc.Filter
	at org.apache.dubbo.config.utils.ConfigValidationUtils.checkMultiExtension(ConfigValidationUtils.java:615)
	at org.apache.dubbo.config.utils.ConfigValidationUtils.validateAbstractInterfaceConfig(ConfigValidationUtils.java:378)
	at org.apache.dubbo.config.utils.ConfigValidationUtils.validateServiceConfig(ConfigValidationUtils.java:395)
	at org.apache.dubbo.config.ServiceConfig.checkAndUpdateSubConfigs(ServiceConfig.java:298)
	at org.apache.dubbo.config.ServiceConfig.postProcessRefresh(ServiceConfig.java:305)
	at org.apache.dubbo.config.AbstractConfig.refresh(AbstractConfig.java:545)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.checkGlobalConfigs(DubboBootstrap.java:606)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.initialize(DubboBootstrap.java:556)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:1085)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onContextRefreshedEvent(DubboBootstrapApplicationListener.java:70)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onApplicationContextEvent(DubboBootstrapApplicationListener.java:63)
	at com.alibaba.spring.context.OnceApplicationContextEventListener.onApplicationEvent(OnceApplicationContextEventListener.java:52)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:898)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236)
	at com.ecommerce.spider.engine.Application.main(Application.java:15)
```

**Comment by AlbumenJ** [comment]
Please try use Dubbo 3.0.1.

**Comment by MrLiuFang** [comment]
哥们我和你一样的问题  你解决了没

**Comment by MrLiuFang** [comment]
![1](https://user-images.githubusercontent.com/25580414/133542905-7fd0614a-1b7c-409a-be0f-17a4c9acdfd3.png)
经过N个小时的问题排查,追踪到源码,发现无法找到自定义的org.apache.dubbo.rpc.Filter(jar中的文件)
但是其它第三方的org.apache.dubbo.rpc.Filter(jar中的文件)能找得到 比如sentinel(sentinel-apache-dubbo-adapter-1.8.1.jar)自定义的org.apache.dubbo.rpc.Filter(jar中的文件)就能找的到
奇了怪了.继续找原因

**Comment by AlbumenJ** [comment]
3.0.0 版本无法自定义 Filter，升级版本解决

**Comment by CrazyHZM** [comment]
Try to upgrade to solve the problem, temporarily close the issue, if there are other issues, you can reopen the issue.
@caohenghui
