### ISSUE TITLE
dubbo不支持rmi协议了吗？

### ISSUE THREAD

**Issue by zhendiao** [apache/dubbo#8226]
在2.7.5-2.7.8测试rmi协议都没有问题。3.0.1提示
Exception in thread "main" java.lang.IllegalStateException: No such extension org.apache.dubbo.rpc.Protocol by name rmi, no related exception was found, please check whether related SPI module is missing.
	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:670)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:677)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:477)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:461)
	at org.apache.dubbo.config.ServiceConfig.findConfigedPorts(ServiceConfig.java:682)

**Comment by xiaoheng1** [comment]
please see https://github.com/apache/dubbo/issues/7781

This will be supported in the summer 2021 of Open Source Promotion Plan.

**Comment by CrazyHZM** [comment]
You can just follow the progress of #7781.
