### ISSUE TITLE
Dubbo provider and consumer  stop throw exception

### ISSUE THREAD

**Issue by opver** [apache/dubbo#8240]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.12
* Operating System version: mac
* Java version: jdk1.8

### Steps to reproduce this issue

1. start dubbo provider
2. start dubbo consumer
3. stop dubbo consumer
4. stop dubbo provider

### Expected Result

not throw exception

### Actual Result

java.lang.IllegalStateException: There's no ApplicationConfig specified.
	at org.apache.dubbo.config.context.ConfigManager.lambda$getApplicationOrElseThrow$0(ConfigManager.java:89)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.apache.dubbo.config.context.ConfigManager.getApplicationOrElseThrow(ConfigManager.java:89)
	at org.apache.dubbo.rpc.model.ApplicationModel.getApplicationConfig(ApplicationModel.java:100)
	at org.apache.dubbo.rpc.model.ApplicationModel.getName(ApplicationModel.java:104)
	at org.apache.dubbo.rpc.model.ApplicationModel.getApplication(ApplicationModel.java:112)
	at org.apache.dubbo.registry.integration.RegistryProtocol.destroy(RegistryProtocol.java:575)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.destroy(ProtocolListenerWrapper.java:82)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.destroy(ProtocolFilterWrapper.java:88)
	at org.apache.dubbo.config.DubboShutdownHook.destroyProtocols(DubboShutdownHook.java:142)
	at org.apache.dubbo.config.DubboShutdownHook.destroyAll(DubboShutdownHook.java:129)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.destroy(DubboBootstrap.java:1276)
	at org.apache.dubbo.common.function.ThrowableAction.execute(ThrowableAction.java:46)
	at org.apache.dubbo.common.lang.ShutdownHookCallbacks.lambda$callback$0(ShutdownHookCallbacks.java:70)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.apache.dubbo.common.lang.ShutdownHookCallbacks.callback(ShutdownHookCallbacks.java:70)
	at org.apache.dubbo.config.DubboShutdownHook.callback(DubboShutdownHook.java:85)
	at org.apache.dubbo.config.DubboShutdownHook.run(DubboShutdownHook.java:73)

reason：
1：service  stop first remove config
2：destroy protocol  find applicationConfig

**Comment by AlbumenJ** [comment]
@kylixs PTAL

**Comment by kathetina** [comment]
同问,我也出现了,从dubbo 2.7.3 升级到dubbo2.7.12

**Comment by opver** [comment]
> 同问,我也出现了,从dubbo 2.7.3 升级到dubbo2.7.12

我看他们master代码好像已经修复了该问题

**Comment by ChinaJeckXu** [comment]
2.7.9-->2.7.13 同问题

**Comment by linxiaobai** [comment]
我本地实验了下：
dubbo 2.7.13 + com.alibaba.spring:spring-context-support:1.0.11      也是会有相同的问题
换成
dubbo 2.7.10 + com.alibaba.spring:spring-context-support:1.0.10    则是正常的

不过抛java.lang.IllegalStateException: There's no ApplicationConfig specified.异常之前，注册到注册中心的服务我看已经正常被摘除掉了，所以应该对调用方无影响？

**Comment by wangchengming666** [comment]
I will fix it.

**Comment by CrazyHZM** [comment]
Resolved in #8927
