### ISSUE TITLE
Dubbo 3.0 Triple consumer throws NPE 

### ISSUE THREAD

**Issue by linsida1** [apache/dubbo#8244]
when  calling the dubbo method, service failed with the below exception. I use the dubbo 3 with triple protocol.
Could any one tell me why the rpc calling failed?
When I debug the code, I found consumer can find the provider successfully, but the RpcServiceContext  consumerUrl is null.
The detail log as below:

java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.apache.dubbo.rpc.model.ServiceRepository.lookupReferredService(ServiceRepository.java:180)
	at org.apache.dubbo.rpc.protocol.tri.TripleClientHandler.writeRequest(TripleClientHandler.java:72)
	at org.apache.dubbo.rpc.protocol.tri.TripleClientHandler.write(TripleClientHandler.java:48)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:110)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:265)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:89)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:51)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.cluster.filter.support.ConsumerContextFilter.invoke(ConsumerContextFilter.java:101)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$ClusterFilterInvoker.invoke(AbstractCluster.java:93)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:93)
	at org.apache.dubbo.registry.client.migration.ServiceDiscoveryMigrationInvoker.invoke(ServiceDiscoveryMigrationInvoker.java:68)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:95)
	at org.apache.dubbo.common.bytecode.proxy1.sayHello(proxy1.java)
	at cn.xlink.dubbo.demo.application.DubboTripleConsumerSample.main(DubboTripleConsumerSample.java:43)
Caused by: java.util.concurrent.ExecutionException: org.apache.dubbo.remoting.RemotingException: java.lang.NullPointerException

![image](https://user-images.githubusercontent.com/18373569/124890166-5b3dbe80-e00a-11eb-881b-ee4874869b57.png)

**Comment by xiaoheng1** [comment]
can you provider a demo to reproduce this problem ?

**Comment by linsida1** [comment]
> can you provider a demo to reproduce this problem ?

Sure, the attachment is my demo project. Could you help me check what is the problem?
 Thank you.
[dubbo-demo.zip](https://github.com/apache/dubbo/files/6789874/dubbo-demo.zip)

**Comment by xiaoheng1** [comment]
ok, i will check it later.

**Comment by xiaoheng1** [comment]
@linsida1 There may be a problem here, let me think about how to solve this problem.
