### ISSUE TITLE
No such extension org.apache.dubbo.metadata.report.MetadataReportFactory by name dubbo, no related exception was found, please check whether related SPI module is missing

### ISSUE THREAD

**Issue by changwei0708** [apache/dubbo#8266]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.1
* Operating System version: Linux or Win
* Java version: 1.8

### Steps to reproduce this issue

1. Start Dubbo by xml  use of org.apache.dubbo.container.Main

### xml config of dubbo service  ( it is both of provider and comsumer )

```
<dubbo:application name="demo-service" owner="${dubbo.owner}" organization="${dubbo.organization}"
					   metadata-type="remote" />


	<dubbo:metadata-report address="${zookeeper.address}"/>
	<dubbo:config-center address="${zookeeper.address}"/>

	<dubbo:registry protocol="zookeeper" address="${zookeeper.address}" file="${dubbo.registry.cache}"/>

	<dubbo:provider timeout="${dubbo.service.timeout}" version="${dubbo.service.version}"/>
	
	<dubbo:consumer timeout="${dubbo.service.timeout}" version="${dubbo.service.version}" retries="0"/>

	<dubbo:monitor protocol="${platform.dubbo.monitor}"/>

 	<dubbo:protocol name="dubbo" serialization="kryo" host="${dubbo.host}" port="${dubbo.port}" payload="104857600" />

```

### all config of POM relative with Dubbo

```
<dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo</artifactId>
            <version>3.0.1</version>
        </dependency>

        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-registry-multicast</artifactId>
            <version>3.0.1</version>
            <type>pom</type>
        </dependency>

        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-registry-zookeeper</artifactId>
            <version>3.0.1</version>
            <type>pom</type>
        </dependency>

        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-configcenter-zookeeper</artifactId>
            <version>3.0.1</version>
            <type>pom</type>
        </dependency>

        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-dependencies-zookeeper</artifactId>
            <version>3.0.1</version>
            <type>pom</type>
        </dependency>

        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-metadata-api</artifactId>
            <version>3.0.1</version>
            <type>pom</type>
        </dependency>

        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-metadata-report-zookeeper</artifactId>
            <version>3.0.1</version>
            <type>pom</type>
        </dependency>

        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-rpc-dubbo</artifactId>
            <version>3.0.1</version>
            <type>pom</type>
        </dependency>

        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-config-spring</artifactId>
            <version>3.0.1</version>
            <type>pom</type>
        </dependency>

        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-remoting-netty4</artifactId>
            <version>3.0.1</version>
            <type>pom</type>
        </dependency>

        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-qos</artifactId>
            <version>3.0.1</version>
            <type>pom</type>
        </dependency>

 

        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-serialization-kryo</artifactId>
            <version>2.7.12</version>
        </dependency>
```

 exception trace:

```
[2021-07-11 23:10:10] [ERROR] -  [DUBBO] No such extension org.apache.dubbo.metadata.report.MetadataReportFactory by name dubbo, no related exception was found, please check whether related SPI module is missing., dubbo version: 3.0.1, current host: 169.254.166.203
java.lang.IllegalStateException: No such extension org.apache.dubbo.metadata.report.MetadataReportFactory by name dubbo, no related exception was found, please check whether related SPI module is missing.
	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:670)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:677)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:477)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:461)
	at org.apache.dubbo.metadata.report.MetadataReportFactory$Adaptive.getMetadataReport(MetadataReportFactory$Adaptive.java)
	at org.apache.dubbo.metadata.report.MetadataReportInstance.init(MetadataReportInstance.java:60)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.startMetadataCenter(DubboBootstrap.java:767)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.initialize(DubboBootstrap.java:561)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:1091)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onContextRefreshedEvent(DubboBootstrapApplicationListener.java:80)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onApplicationContextEvent(DubboBootstrapApplicationListener.java:72)
	at com.alibaba.spring.context.OnceApplicationContextEventListener.onApplicationEvent(OnceApplicationContextEventListener.java:52)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:898)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554)
	at org.apache.dubbo.container.spring.SpringContainer.start(SpringContainer.java:50)
	at org.apache.dubbo.container.Main.main(Main.java:90)
```

**Comment by horizonzy** [comment]
```
<dubbo:metadata-report address="${zookeeper.address}"/>
```
->

```
<dubbo:metadata-report protocol="zookeeper" address="${zookeeper.address}"/>
```

**Comment by changwei0708** [comment]
@horizonzy 
thx ! 
but  <dubbo:metadata-report ... /> is not support  attribute   “protocol ”, 
it is only work at 
```
<dubbo:registry protocol="zookeeper" 
```

just like my description ~

**Comment by horizonzy** [comment]
Ok, I will make it support protocol later.
Supply a workaround, config ${zookeeper.address} with protocol, like "zookeeper://xx.xx.xx.xx:2181".

**Comment by changwei0708** [comment]
@horizonzy 
thx ! 
it is work for me ,but take another exception trace 
```
java.lang.RuntimeException: [source error] getExportedURLs() not found in org.apache.dubbo.registry.client.metadata.store.InMemoryWritableMetadataService
```

**Comment by AlbumenJ** [comment]
> InMemoryWritableMetadataService

Please check if all of the dubbo dependencies are the same version

**Comment by changwei0708** [comment]
@AlbumenJ 
thx ! 
but I comfirm all about the Dubbo use the same version,  because they are import by this :

```
...
<version>3.0.1</version>
...

```

**Comment by changwei0708** [comment]
@AlbumenJ 
Another important thing , The above configuration works in  dubbo-2.7.11

**Comment by AlbumenJ** [comment]
> @AlbumenJ
> thx !
> but I comfirm all about the Dubbo use the same version, because they are import by this :
> 
> ```
> ...
> <version>3.0.1</version>
> ...
> ```

`getExportedURLs` method, which is added in dubbo 3.0.0, is appeared in https://github.com/apache/dubbo/blob/2e8dca636792f354f31661eca0d151e12a79cd4f/dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/store/InMemoryWritableMetadataService.java#L141

**Comment by AlbumenJ** [comment]
Please check if you are depend on both dubbo 2.7 and 3.0.

**Comment by changwei0708** [comment]
thx ~ , I'll confirm it carefully again

**Comment by changwei0708** [comment]
and I check another different between 2.7.x and 3.0.x  like this in class DubboBootstrap 
```
executorRepository.nextScheduledExecutor().scheduleAtFixedRate(() -> {
            InMemoryWritableMetadataService localMetadataService = (InMemoryWritableMetadataService) WritableMetadataService.getDefaultExtension();
            localMetadataService.blockUntilUpdated();
            try {
                ServiceInstanceMetadataUtils.refreshMetadataAndInstance(serviceInstance);
            } catch (Exception e) {
                logger.error("Refresh instance and metadata error", e);
            }
        }, 0, ConfigurationUtils.get(METADATA_PUBLISH_DELAY_KEY, DEFAULT_METADATA_PUBLISH_DELAY), TimeUnit.MILLISECONDS);
```

in other word InMemoryWritableMetadataService  Is automatically initialized, Is it related to this place?

**Comment by changwei0708** [comment]
@AlbumenJ 

it is actually not present both dubbo 2.7 and 3.0， and only 3.0.1

**Comment by changwei0708** [comment]
I will close this issue ,  and create new isssue for the new question , and the solution of this issue is confirm all  dubbo dependencies are the same version ，and  the dubbo-config.xml should be set the registry correctly just like  : 

```
<dubbo:registry id="registry1" address="zookeeper://192.168.1.110:2181?registry-type=service" check="false"/>
	<dubbo:config-center address="zookeeper://192.168.1.110:2181"/>
	<dubbo:metadata-report address="zookeeper://192.168.1.110:2181"/>
```
