### ISSUE TITLE
[DUBBO] Refresh instance and metadata error, dubbo version: 3.0.1 系统停止时会报这种错

### ISSUE THREAD

**Issue by hyberbin** [apache/dubbo#8299]
### Environment

* Dubbo version: 3.0.1
* Operating System version: win10 /centos 7
* Java version: 1.8

### Steps to reproduce this issue

退出dubbo相关的应用程序时会报这种错，2.7.8版本的时候没有这种问题

### Actual Result
win10下报错
```
[Dubbo-framework-scheduler-thread-1] ERROR o.a.d.c.bootstrap.DubboBootstrap -  [DUBBO] Refresh instance and metadata error, dubbo version: 3.0.1, current host: 192.168.xxxx
java.lang.IllegalStateException: instance must be started before calling this method
	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.createPersistent(CuratorZookeeperClient.java:130)
	at org.apache.dubbo.remoting.zookeeper.support.AbstractZookeeperClient.create(AbstractZookeeperClient.java:183)
	at org.apache.dubbo.metadata.store.zookeeper.ZookeeperMetadataReport.publishAppMetadata(ZookeeperMetadataReport.java:145)
	at org.apache.dubbo.registry.client.metadata.store.RemoteMetadataServiceImpl.lambda$publishMetadata$0(RemoteMetadataServiceImpl.java:72)
	at java.util.concurrent.ConcurrentHashMap.forEach(Unknown Source)
	at org.apache.dubbo.registry.client.metadata.store.RemoteMetadataServiceImpl.publishMetadata(RemoteMetadataServiceImpl.java:59)
	at org.apache.dubbo.registry.client.metadata.ServiceInstanceMetadataUtils.refreshMetadataAndInstance(ServiceInstanceMetadataUtils.java:262)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.lambda$registerServiceInstance$10(DubboBootstrap.java:1386)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: instance must be started before calling this method
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.create(CuratorFrameworkImpl.java:416)
	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.createPersistent(CuratorZookeeperClient.java:122)
	... 15 common frames omitted
```

centos报错

```
 [DUBBO] Refresh instance and metadata error, dubbo version: 3.0.1, current host: 192.168.xxxxjava.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1479)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1477)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:206)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
	at com.google.gson.Gson.toJson(Gson.java:704)

```

**Comment by kevinw66** [comment]
本地无法复现，能否提供一个可复现的demo并且告知一下复现方式呢？

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
