### ISSUE TITLE
启动tomcat出现此异常：Default config not found for ApplicationConfig

### ISSUE THREAD

**Issue by startjava** [apache/dubbo#8364]
29-Jul-2021 08:29:18.479 严重 [RMI TCP Connection(3)-127.0.0.1] org.apache.catalina.core.StandardContext.listenerStart 异常将上下文初始化事件发送到类的侦听器实例.[org.apache.dubbo.config.spring.context.DubboBootstrapServletContextListener]
	java.lang.IllegalStateException: Default config not found for ApplicationConfig
		at org.apache.dubbo.config.bootstrap.DubboBootstrap.checkDefaultAndValidateConfigs(DubboBootstrap.java:635)
		at org.apache.dubbo.config.bootstrap.DubboBootstrap.checkGlobalConfigs(DubboBootstrap.java:585)
		at org.apache.dubbo.config.bootstrap.DubboBootstrap.initialize(DubboBootstrap.java:558)
		at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:1091)
		at org.apache.dubbo.config.spring.context.DubboBootstrapServletContextListener.contextInitialized(DubboBootstrapServletContextListener.java:47)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4768)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5230)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:728)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:696)
		at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1783)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:293)
		at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(Unknown Source)
		at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(Unknown Source)
		at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:460)
		at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:408)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:293)
		at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(Unknown Source)
		at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(Unknown Source)
		at com.sun.jmx.remote.security.MBeanServerAccessController.invoke(Unknown Source)
		at javax.management.remote.rmi.RMIConnectionImpl.doOperation(Unknown Source)
		at javax.management.remote.rmi.RMIConnectionImpl.access$300(Unknown Source)
		at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(Unknown Source)
		at java.security.AccessController.doPrivileged(Native Method)
		at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(Unknown Source)
		at javax.management.remote.rmi.RMIConnectionImpl.invoke(Unknown Source)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
		at sun.rmi.transport.Transport$1.run(Unknown Source)
		at sun.rmi.transport.Transport$1.run(Unknown Source)
		at java.security.AccessController.doPrivileged(Native Method)
		at sun.rmi.transport.Transport.serviceCall(Unknown Source)
		at sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
		at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
		at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
		at java.security.AccessController.doPrivileged(Native Method)
		at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at java.lang.Thread.run(Unknown Source)
29-Jul-2021 08:29:18.530 严重 [RMI TCP Connection(3)-127.0.0.1] org.apache.catalina.core.StandardContext.listenerStop 例外情况发送上下文删除事件[org.apache.dubbo.config.spring.context.DubboBootstrapServletContextListener]，以便列表实例
	java.lang.RuntimeException: java.lang.IllegalStateException: Dubbo config was cleaned prematurely
		at org.apache.dubbo.common.function.ThrowableAction.execute(ThrowableAction.java:48)
		at org.apache.dubbo.common.lang.ShutdownHookCallbacks.lambda$callback$0(ShutdownHookCallbacks.java:70)
		at java.lang.Iterable.forEach(Unknown Source)
		at org.apache.dubbo.common.lang.ShutdownHookCallbacks.callback(ShutdownHookCallbacks.java:70)
		at org.apache.dubbo.config.DubboShutdownHook.callback(DubboShutdownHook.java:77)
		at org.apache.dubbo.config.DubboShutdownHook.run(DubboShutdownHook.java:64)
		at org.apache.dubbo.config.spring.context.DubboBootstrapServletContextListener.contextDestroyed(DubboBootstrapServletContextListener.java:54)
		at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4816)
		at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5477)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:187)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:728)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:696)
		at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1783)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:293)
		at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(Unknown Source)
		at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(Unknown Source)
		at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:460)
		at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:408)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:293)
		at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(Unknown Source)
		at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(Unknown Source)
		at com.sun.jmx.remote.security.MBeanServerAccessController.invoke(Unknown Source)
		at javax.management.remote.rmi.RMIConnectionImpl.doOperation(Unknown Source)
		at javax.management.remote.rmi.RMIConnectionImpl.access$300(Unknown Source)
		at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(Unknown Source)
		at java.security.AccessController.doPrivileged(Native Method)
		at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(Unknown Source)
		at javax.management.remote.rmi.RMIConnectionImpl.invoke(Unknown Source)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
		at sun.rmi.transport.Transport$1.run(Unknown Source)
		at sun.rmi.transport.Transport$1.run(Unknown Source)
		at java.security.AccessController.doPrivileged(Native Method)
		at sun.rmi.transport.Transport.serviceCall(Unknown Source)
		at sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
		at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
		at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
		at java.security.AccessController.doPrivileged(Native Method)
		at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at java.lang.Thread.run(Unknown Source)
	Caused by: java.lang.IllegalStateException: Dubbo config was cleaned prematurely
		at org.apache.dubbo.config.bootstrap.DubboBootstrap.checkConfigState(DubboBootstrap.java:1488)
		at org.apache.dubbo.config.bootstrap.DubboBootstrap.destroy(DubboBootstrap.java:1455)
		at org.apache.dubbo.common.function.ThrowableAction.execute(ThrowableAction.java:46)
		... 54 more

百度也搜不到怎么回事，，
使用的是dubbo3.0.1版本，需要添加什么配置?

感谢

**Comment by startjava** [comment]
# Spring boot application
dubbo.application.name=Provider
spring.application.name=dubbo-registry-nacos-provider-sample
# Base packages to scan Dubbo Component: @org.apache.dubbo.config.annotation.Service
dubbo.scan.base-packages=com.ghy.www.remote
# Dubbo Application
## The default value of dubbo.application.name is ${spring.application.name}
## dubbo.application.name=${spring.application.name}
nacos.server-address=127.0.0.1
nacos.port=8848
nacos.username=nacos
nacos.password=nacos
# Dubbo Protocol
dubbo.protocol.name=dubbo
## Random port
dubbo.protocol.port=-1
## Dubbo Registry
dubbo.registry.address=nacos://${nacos.server-address}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}
## DemoService version
demo.service.version=1.0.0


配置文件如上，这是官方DEMO中的。

**Comment by startjava** [comment]
```
# Spring boot application
dubbo.application.name=Provider
spring.application.name=dubbo-registry-nacos-provider-sample
# Base packages to scan Dubbo Component: @org.apache.dubbo.config.annotation.Service
dubbo.scan.base-packages=com.ghy.www.remote
# Dubbo Application
## The default value of dubbo.application.name is ${spring.application.name}
## dubbo.application.name=${spring.application.name}
nacos.server-address=127.0.0.1
nacos.port=8848
nacos.username=nacos
nacos.password=nacos
# Dubbo Protocol
dubbo.protocol.name=dubbo
## Random port
dubbo.protocol.port=-1
## Dubbo Registry
dubbo.registry.address=nacos://${nacos.server-address}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}
## DemoService version
demo.service.version=1.0.0
```

这是官方DEMO中的，不知道缺啥配置。

**Comment by startjava** [comment]
关了，是版本的事
