### ISSUE TITLE
Dubbo 2.7.13ClassNotFoundException: org.apache.dubbo.config.spring.beans.factory.annotation.ServiceAnnotationPostProcessor

### ISSUE THREAD

**Issue by kukukakiki** [apache/dubbo#8476]
### Environment
* Dubbo version:2.7.13
* Operating System version:win10
* Java version:1.8
### Steps to reproduce this issue
1. spring-cloud-alibaba-dependencies版本是2.2.6.RELEASE
2. 查看dubbo依赖版本是2.7.13
3. 启动项目报找不到ServiceAnnotationPostProcessor
4. 查找问题发现dubbo-config中此类是在3.0.0版本后才出现，所以2.7.13确实没有
### Expected Result
项目能够正常启动
### Actual Result
启动报错：
```
Caused by: java.lang.ClassNotFoundException: org.apache.dubbo.config.spring.beans.factory.annotation.ServiceAnnotationPostProcessor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_251]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_251]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) ~[na:1.8.0_251]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_251]
	... 43 common frames omitted
```

**Comment by AlbumenJ** [comment]
确定依赖的是 Dubbo 2.7.13 版本但是使用到了 ServiceAnnotationPostProcessor？

**Comment by kukukakiki** [comment]
> 确定依赖的是 Dubbo 2.7.13 版本但是使用到了 ServiceAnnotationPostProcessor？

spring-cloud-alibaba2.2.6.RELEASE依赖的dubbo是2.7.8，我自己的父pom把dubbo升级到了2.7.13
需要升级几个依赖包就好了

**Comment by xujianjs** [comment]
我直接从gitee的镜像clone下来的，未做任何变动。同样的问题，看源码提示：
Service Annotation Bean Definition Registry Post Processor
Deprecated
Recommend ServiceClassPostProcessor as the substitute
Since:
2.5.8
官方引入的包不是2.7.8吗，怎么还用到了丢弃的类？帮忙核实下
