### ISSUE TITLE
3.0.1不配置metadata-report抛出异常

### ISSUE THREAD

**Issue by Clinan** [apache/dubbo#8482]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.1
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue

不配置metadata-report时，抛出异常
 

### Expected Result

What do you expected from the above steps？
不抛出异常

### Actual Result
 
If there is an exception, please attach the exception trace:

```
 2021-08-12 13:37:39.303 [main   ] WARN  o.a.d.r.client.metadata.MetadataServiceNameMapping -  [DUBBO] the metadata report was not inited., dubbo version: 3.0.1, current host: 172.20.11.30
java.lang.IllegalStateException: the metadata report was not inited.
	at org.apache.dubbo.metadata.report.MetadataReportInstance.checkInit(MetadataReportInstance.java:83)
	at org.apache.dubbo.metadata.report.MetadataReportInstance.getMetadataReport(MetadataReportInstance.java:72)
	at org.apache.dubbo.registry.client.metadata.MetadataServiceNameMapping.lambda$map$0(MetadataServiceNameMapping.java:56)
	at org.apache.dubbo.registry.client.metadata.MetadataServiceNameMapping.execute(MetadataServiceNameMapping.java:121)
	at org.apache.dubbo.registry.client.metadata.MetadataServiceNameMapping.map(MetadataServiceNameMapping.java:50)
	at org.apache.dubbo.config.ServiceConfig.lambda$exported$0(ServiceConfig.java:244)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.apache.dubbo.config.ServiceConfig.exported(ServiceConfig.java:242)
	at org.apache.dubbo.config.spring.ServiceBean.exported(ServiceBean.java:113)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:339)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:231)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.exportServices(DubboBootstrap.java:1301)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:1096)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onContextRefreshedEvent(DubboBootstrapApplicationListener.java:80)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onApplicationContextEvent(DubboBootstrapApplicationListener.java:72)
	at com.alibaba.spring.context.OnceApplicationContextEventListener.onApplicationEvent(OnceApplicationContextEventListener.java:52)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:898)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554)
```

**Comment by kevinw66** [comment]
能否提供一个demo呢？我这边启动正常的

**Comment by kevinw66** [comment]
你这是没有配置注册中心哈，写上去就好了。不过报错信息有点问题，我再看看

**Comment by kevinw66** [comment]
https://github.com/apache/dubbo/pull/8234/files#diff-139de645871ec8476f1d5d7ba848c5010933e5f75e9383d132094ea7436ce7baR53-R55

已经在这个PR里修复了 对应的代码会发布在3.0.2版本中
