### ISSUE TITLE
dubbo3.0.1升级到3.0.2，启动报Caused by: java.lang.ClassNotFoundException: io.fabric8.kubernetes.client.KubernetesClient

### ISSUE THREAD

**Issue by gang0713** [apache/dubbo#8512]
2021-08-16 15:30:18 ERROR org.springframework.boot.SpringApplication:834 - Application run failed
java.lang.IllegalStateException: Extension instance (name: kubernetes, class: interface org.apache.dubbo.rpc.cluster.router.mesh.route.MeshEnvListener) couldn't be instantiated: io/fabric8/kubernetes/client/KubernetesClient
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:730) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:495) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:475) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.common.extension.ExtensionLoader.getSupportedExtensionInstances(ExtensionLoader.java:542) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.rpc.cluster.router.mesh.route.MeshRuleManager.subscribeAppRule(MeshRuleManager.java:46) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.rpc.cluster.router.mesh.route.MeshRuleAddressListenerInterceptor.notify(MeshRuleAddressListenerInterceptor.java:43) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.notify(ServiceDiscoveryRegistryDirectory.java:125) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.addListenerAndNotify(ServiceInstancesChangedListener.java:182) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribeURLs(ServiceDiscoveryRegistry.java:321) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.doSubscribe(ServiceDiscoveryRegistry.java:234) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribe(ServiceDiscoveryRegistry.java:211) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:106) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.registry.integration.DynamicDirectory.subscribe(DynamicDirectory.java:136) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.subscribe(ServiceDiscoveryRegistryDirectory.java:76) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.registry.integration.RegistryProtocol.doCreateInvoker(RegistryProtocol.java:515) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getServiceDiscoveryInvoker(InterfaceCompatibleRegistryProtocol.java:65) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshServiceDiscoveryInvoker(MigrationInvoker.java:425) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToForceApplicationInvoker(MigrationInvoker.java:202) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.refreshInvoker(MigrationRuleHandler.java:76) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:57) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:211) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:486) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:468) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:453) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:74) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:68) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:73) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:51) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:391) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:327) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:204) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.config.utils.ReferenceConfigCache.lambda$get$3(ReferenceConfigCache.java:113) ~[dubbo-3.0.2.jar:3.0.2]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_201]
	at org.apache.dubbo.config.utils.ReferenceConfigCache.get(ReferenceConfigCache.java:112) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.lambda$referServices$12(DubboBootstrap.java:1459) ~[dubbo-3.0.2.jar:3.0.2]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) ~[?:1.8.0_201]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.referServices(DubboBootstrap.java:1438) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.doStart(DubboBootstrap.java:1153) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:1119) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onContextRefreshedEvent(DubboBootstrapApplicationListener.java:109) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onApplicationContextEvent(DubboBootstrapApplicationListener.java:101) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onApplicationEvent(DubboBootstrapApplicationListener.java:78) ~[dubbo-3.0.2.jar:3.0.2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:898) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402) [spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247) [spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236) [spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at cn.raysonblog.shopserviceconsumer.ShopServiceConsumerApplication.main(ShopServiceConsumerApplication.java:45) [classes/:?]
Caused by: java.lang.NoClassDefFoundError: io/fabric8/kubernetes/client/KubernetesClient
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_201]
	at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_201]
	at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_201]
	at org.apache.dubbo.common.extension.ExtensionLoader.injectExtension(ExtensionLoader.java:745) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:703) ~[dubbo-3.0.2.jar:3.0.2]
	... 57 more
Caused by: java.lang.ClassNotFoundException: io.fabric8.kubernetes.client.KubernetesClient
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_201]
	at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_201]
	at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_201]
	at org.apache.dubbo.common.extension.ExtensionLoader.injectExtension(ExtensionLoader.java:745) ~[dubbo-3.0.2.jar:3.0.2]
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:703) ~[dubbo-3.0.2.jar:3.0.2]
	... 57 more

**Comment by gang0713** [comment]
引入下面的包才不报错，但是我并没有用到kubernetes作为注册中心。不应该强依赖吧。
<dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-registry-kubernetes</artifactId>
            <version>3.0.2</version>
        </dependency>

**Comment by AlbumenJ** [comment]
I will fix it in the next release.

**Comment by AlbumenJ** [comment]
Fix in 3.0.2.1
