### ISSUE TITLE
org.apache.dubbo.remoting.TimeoutException: Waiting server-side response timeout by scan timer. start time: 2021-08-15 23:04:35.615, end time: 2021-08-15 23:05:06.234, client elapsed: 20491 ms, server elapsed: 10128 ms, timeout: 100 ms

### ISSUE THREAD

**Issue by LiWenGu** [apache/dubbo#8513]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: Red Hat 4.8.5
* Java version: openjdk8

### Steps to reproduce this issue

It happened online. I tried it locally and couldn't replicate it.

online log:
```log
org.apache.dubbo.remoting.TimeoutException: Waiting server-side response timeout by scan timer. start time: 2021-08-15 23:04:35.615, end time: 2021-08-15 23:05:06.234, client elapsed: 20491 ms, server elapsed: 10128 ms, timeout: 100 ms, request: Request
```
A timeline based on online consumer and provider logs:

| client | server |
| :-: | :-: |
| start 1629039875615(2021-08-15 23:04:35.615) | |
| send  1629039896106(2021-08-15 23:04:56.106)  | |
|  | server biz process start(2021-08-15 23:04:56.106) |
|  | server biz process end(2021-08-15 23:04:56.109) |
| received 1629039906234(2021-08-15 23:05:06.234) | |

### Expected Result

Why does the consumer timeout period not take effect

relation issues: #4732 #103

**Comment by dkisser** [comment]
First, check network status, the log shows that it took more than 10s for client got response.Second, check application status, it also shows that application had took more than 20s for sending request

**Comment by LiWenGu** [comment]
当时我们有很多接口在请求，就这一个接口出现这种情况，第一次碰到这种 client start -> send 需要 20s 的情况，极其夸张，这种。通过 zabbix 查看当前机器的性能还有网络，指标也是正常的。该应用的其它接口请求是正常的。我本地测试也没法复现当时的情况。很奇怪。另外我看很久之前就有人问过这个类似的问题，但是没有解决方案

**Comment by xiaoheng1** [comment]
查过线程池的状态了没？

**Comment by LiWenGu** [comment]
> 查过线程池的状态了没？

我去查看了，发现 005 机器线程数量飙升，这个日志就是 005 机器爆的异常。至于线程池状态没法定位到当时的快照信息。我再看看当时的业务日志有什么异常，这个线程数量突然变多是导致这个的原因？

![image](https://user-images.githubusercontent.com/15909210/130206815-4bfdd70a-f5e3-493e-8d8a-41da95efdeab.png)

**Comment by xiaoheng1** [comment]
> 我去查看了，发现 005 机器线程数量飙升，这个日志就是 005 机器爆的异常。至于线程池状态没法定位到当时的快照信息。我再看看当时的业务日志有什么异常，这个线程数量突然变多是导致这个的原因？

线程数量飙升可能会引起这个问题。具体确认的话，还是要结合当时的日志，机器状态来确认。

方便贴下你们线程池这块的配置不？

**Comment by LiWenGu** [comment]
dubbo线程池用的 cached 
![image](https://user-images.githubusercontent.com/15909210/130544849-37d951f6-286d-49a5-b798-c9507f7641e7.png)

我看了下 AbortPolicyWithReport.java 类，也打印出当前的线程栈信息了

![image](https://user-images.githubusercontent.com/15909210/130545532-33a5b676-ec89-439f-b452-08e1fde004ff.png)

可能需要先分析下这个线程栈信息才能解决当时的问题

**Comment by LiWenGu** [comment]
这是那个时间点的 dubbo_Stack.log 文件，ip做了处理。我使用各种工具分析都说识别不出这个文件为标准的 线程 dump 文件。

[Dubbo_JStack.log.2021-08-15_23:03:40.TXT](https://github.com/apache/dubbo/files/7036164/Dubbo_JStack.log.2021-08-15_23.03.40.TXT)

**Comment by xiaoheng1** [comment]
你把 dispatcher 换成 all 试试，看还会不会出现问题

**Comment by tianshuang** [comment]
2.7.5 昨天也遇到该问题，持续一分钟左右自动恢复，排除了 FullGC, 暂时没找到原因
```
Caused by: org.apache.dubbo.remoting.TimeoutException: Waiting server-side response timeout by scan timer. start time: 2021-09-12 17:07:02.423, end time: 2021-09-12 17:07:22.432, client elapsed: 19217 ms, server elapsed: 791 ms, timeout: 20000 ms, request: Request [id=9841521, version=2.0.2, twoway=true, event=false, broken=false, data=null], channel: /172.31.168.27:43984 -> /172.31.135.36:20891
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.doReceived(DefaultFuture.java:210) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:175) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture$TimeoutCheckTask.notifyTimeout(DefaultFuture.java:297) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture$TimeoutCheckTask.lambda$run$0(DefaultFuture.java:284) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:77) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:175) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.protocol.AsyncToSyncInvoker.invoke(AsyncToSyncInvoker.java:61) ~[dubbo-2.7.5.jar:2.7.5]
	at com.yunti.dubbo.filter.DubboConsumerFilter.invoke(DubboConsumerFilter.java:61) ~[yunti-dubbo-tool-1.0-SNAPSHOT.jar:?]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:89) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[dubbo-2.7.5.jar:2.7.5]
	at com.alibaba.csp.sentinel.adapter.dubbo.DubboAppContextFilter.invoke(DubboAppContextFilter.java:43) ~[sentinel-apache-dubbo-adapter-1.8.0.jar:?]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:49) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:55) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:78) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:82) ~[dubbo-2.7.5.jar:2.7.5]
	... 51 more
```

**Comment by tianshuang** [comment]
服务提供方没有 dubbo 异常日志

**Comment by xiaoheng1** [comment]
配置信息方便贴下不 provider 端的

**Comment by tianshuang** [comment]
```java
<dubbo:protocol threadpool="eager" threads="200" queues="1024" name="dubbo" port="20891"/>
<dubbo:provider timeout="60000" retries="0" filter="-exception,traceProviderFilter,methodFilter,exceptionFilter" />
```

**Comment by xiaoheng1** [comment]
dispatcher 选择的是哪一个

**Comment by tianshuang** [comment]
默认的，没调过

**Comment by xiaoheng1** [comment]
那你这种情况看不出来是啥原因导致的，我记得 2.7.5 中有一个是关于 dispatcher 的问题，会导致 server 没有发包给 client 导致超时的问题

**Comment by CrazyHZM** [comment]
@tianshuang 
Has this problem been resolved?

**Comment by tianshuang** [comment]
> @tianshuang
> Has this problem been resolved?
no

**Comment by CrazyHZM** [comment]
@tianshuang 
2.7.14 Does the problem exist?

**Comment by tianshuang** [comment]
> @tianshuang 2.7.14 Does the problem exist?

We haven’t upgraded the version, so we don’t know. 😄

**Comment by CrazyHZM** [comment]
@tianshuang 
It is recommended to upgrade to 2.7.14 and observe whether the problem can be reproduced. 2.7.5 is not recommended for production and large-scale use

**Comment by tianshuang** [comment]
> @tianshuang It is recommended to upgrade to 2.7.14 and observe whether the problem can be reproduced. 2.7.5 is not recommended for production and large-scale use

We are mainly worried about compatibility issues, because production services need to remain stable.

**Comment by tianshuang** [comment]
这几天问题又出现了，Dubbo 版本 2.7.5, 我们有方法设置的超时时间为 20min, 在发起调用 15min 左右我去拉了提供端的栈帧，没有与该接口调用的 DubboServerHandler 线程栈帧，几乎都在 TIMED_WAITING 等待任务状态，到 20min 时消费端抛出超时异常。

**Comment by helei810304** [comment]
> * [x]  I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
> * [x]  I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.
> 
> ### Environment
> * Dubbo version: 2.7.3
> * Operating System version: Red Hat 4.8.5
> * Java version: openjdk8
> 
> ### Steps to reproduce this issue
> It happened online. I tried it locally and couldn't replicate it.
> 
> online log:
> 
> ```
> org.apache.dubbo.remoting.TimeoutException: Waiting server-side response timeout by scan timer. start time: 2021-08-15 23:04:35.615, end time: 2021-08-15 23:05:06.234, client elapsed: 20491 ms, server elapsed: 10128 ms, timeout: 100 ms, request: Request
> ```
> 
> A timeline based on online consumer and provider logs:
> 
> client	server
> start 1629039875615(2021-08-15 23:04:35.615)	
> send 1629039896106(2021-08-15 23:04:56.106)	
> server biz process start(2021-08-15 23:04:56.106)
> server biz process end(2021-08-15 23:04:56.109)
> received 1629039906234(2021-08-15 23:05:06.234)	
> ### Expected Result
> Why does the consumer timeout period not take effect
> 
> relation issues: #4732 #103

问题解决了么，我是dubbo2.7.3，也会出这样的问题

**Comment by totalo** [comment]
+1昨天我们也出现了，服务提供方没有异常，然后版本是2.7.6

**Comment by 90706827** [comment]
<img width="1542" alt="image" src="https://user-images.githubusercontent.com/19201070/209569962-006c7643-d6e9-40d1-b78b-36186567f477.png">

**Comment by AlbumenJ** [comment]
> dubbo 3.1.4 nacos 测试用例报错 找不到任何原因 哪位那位大哥帮帮忙 <img alt="image" width="1542" src="https://user-images.githubusercontent.com/19201070/209569962-006c7643-d6e9-40d1-b78b-36186567f477.png">

单机的检查是否有 socks5 的代理

**Comment by worker24h** [comment]
Caused by: org.apache.dubbo.remoting.TimeoutException: Waiting server-side response timeout by scan timer. start time: 2023-05-22 20:54:49.553, end time: 2023-05-22 20:54:50.572, client elapsed: 1 ms, server elapsed: 1018 ms, timeout: 1000 ms, request: Request [id=5978, version=2.0.2, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=sendGatewayMsg, parameterTypes=[class com.neolix.mars.model.MarsMessage], arguments=[MarsMessage{productName='auto-distribute', deviceName='0000-0302-0001', traceId='904da41ecc5c49f58207dcc58112e7591684760087528', qos=0, notify=false, generatedTime=1684760087528, expire=0, handleType=32, version=24, msgId=77, data=[123, 34, 104, 97, 110, 100, 108, 101, 95, 116, 121, 112, 101, 34, 58, 51, 50, 44, 34, 99, 117, 114, 95, 115, 112, 101, 101, 100, 34, 58, 48, 44, 34, 104, 101, 97, 100, 95, 98, 97, 116, 116, 101, 114, 121, 95, 118, 111, 108, 34, 58, 51, 56, 49, 54, 53, 44, 34, 99, 117, 114, 95, 108, 111, 99, 97, 116, 105, 111, 110, 34, 58, 49, 49, 51, 56, 44, 34, 116, 97, 105, 108, 95, 98, 97, 116, 116, 101, 114, 121, 95, 118, 111, 108, 34, 58, 52, 57, 53, 56, 52, 44, 34, 115, 121, 115, 116, 105, 99, 107, 34, 58, 54, 57, 54, 50, 49, 44, 34, 108, 105, 100, 97, 114, 95, 115, 116, 97, 116, 101, 34, 58, 48, 125]}], attachments={path=com.neolix.mars.api.internal.MarsGatewayService, remote.application=mars-server, interface=com.neolix.mars.api.internal.MarsGatewayService, version=0.0.0}]], channel: /10.100.113.5:38460 -> /10.100.113.6:10202
        at org.apache.dubbo.remoting.exchange.support.DefaultFuture.doReceived(DefaultFuture.java:205)
        at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:170)
        at org.apache.dubbo.remoting.exchange.support.DefaultFuture$TimeoutCheckTask.notifyTimeout(DefaultFuture.java:288)
        at org.apache.dubbo.remoting.exchange.support.DefaultFuture$TimeoutCheckTask.lambda$run$0(DefaultFuture.java:275)
        at org.apache.dubbo.common.threadpool.ThreadlessExecutor$RunnableWrapper.run(ThreadlessExecutor.java:196)
        at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:99)
        at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:179)
        ... 49 common frames omitted
        
        
Dubbo 2.7.15

**Comment by dongjiancom** [comment]
解决了吗？2024-05-22 09:14:58；dubbo版本2.7.15也遇到了这个问题

**Comment by dongjiancom** [comment]
12个pod只有1个或2个出现这个问题，dubbo 线程池设置为3000，有问题的pod都满了，其他机器正常。
