### ISSUE TITLE
Consumer is shutting down and this call is going to be stopped without receiving any result, usually this is called by a slow provider instance or bad service implementation.

### ISSUE THREAD

**Issue by 294033186** [apache/dubbo#8563]
- [ ] 已经有类似的issue了[issues](https://github.com/apache/dubbo/issues/6294)，但是没有看到合理的解决方式

### Environment

* Dubbo version: 2.7.9
* Operating System version: centos7
* Java version: 1.8

### 我的dubbo config：
```
    <!-- 使用multicast广播注册中心暴露服务地址 -->
    <dubbo:registry protocol="zookeeper" timeout="${dubbo.registry.timeout}" address="${dubbo.registry.address}" check="false" use-as-config-center="false" use-as-metadata-center="false"/>
    <dubbo:consumer retries="0" version="${dubbo.consumer.version}" group="soc_${activeprofile}" check="false" timeout="300000" filter="countInvoke">
        <dubbo:parameter key="send.reconnect" value="true" />
        <dubbo:parameter key="keep.alive" value="true"/>
    </dubbo:consumer>
    <!---->
    <dubbo:provider timeout="300000" retries="0" version="${dubbo.provider.version}" group="soc_${activeprofile}" filter="countInvoke"/>
    <!-- 用dubbo协议在20880端口暴露服务 -->
    <dubbo:protocol name="dubbo" port="20881" payload="52428800">
    </dubbo:protocol>
    <!--扫描的方式-->
    <dubbo:annotation package="com.ouyeel.account" />
```
### 我的hsf provider config：
```
<hsf:provider id="EomAccountLotResourceApi" interface="com.baosight.shgt.service.yy.api.eomAccount.EomAccountLotResourceApi"
                  version="0.0.1" ref="EomAccountLotResourceApiImpl" clientTimeout="500000" group="yy_${activeprofile}" invokeType="hsf,dubbo"/>
```
### 我的dubbo consumer config：
```
<dubbo:reference id="EomAccountSalePresaleAccountApi" interface="com.baosight.shgt.service.yy.api.eomAccount.EomAccountSalePresaleAccountApi"  version="0.0.1" group="yy_${activeprofile}" timeout="500000" ></dubbo:reference>
```
### Steps to reproduce this issue

1. 服务提供端是hsf，edas-sdk版本是1.5.1，Pandora版本是3.0，服务调用端是dubbo2.7.9。
2. 调用端是调用一个会耗时大概2分钟的hsf服务。
3. 在1分30秒到2分钟之间dubbo会抛错Consumer is shutting down and this call is going to be stopped without receiving any result, usually this is called by a slow provider instance or bad service implementation，此时服务端hsf线程还在执行。

If there is an exception, please attach the exception trace:

```
2021-08-21 19:07:28 ERROR [http-nio-8080-exec-4] o.s.b.w.s.s.ErrorPageFilter - Forwarding to error page from request [/invoke] due to exception [Failed to invoke the method queryEomAccountSalePresaleMain in the service com.baosight.shgt.service.yy.api.eomAccount.EomAccountSalePresaleAccountApi. Tried 1 times of the providers [10.xx.xx.81:12200] (1/4) from the registry 10.xx.xx.45.1:2181 on the consumer 10.xx.xxx.xxx using the dubbo version 2.7.9. Last error is: Failed to invoke remote method: queryEomAccountSalePresaleMain, provider: dubbo://10.xx.xx.81:12200/com.baosight.shgt.service.yy.api.eomAccount.EomAccountSalePresaleAccountApi?application=fss-account-center&check=false&group=yy_run&init=false&interface=com.baosight.shgt.service.yy.api.eomAccount.EomAccountSalePresaleAccountApi&invokeType=DUBBO&keep.alive=true&pid=71709&reference.filter=oyaccesslog,countInvoke,oplatConsumerLogFilter&register.ip=10.70.114.154&remote.application=285a890d-8137-4e55-b6eb-dcd1b7cba94d&retries=0&revision=0.0.3-release-SNAPSHOT&send.reconnect=true&side=consumer&sticky=false&timeout=500000&version=0.0.1, cause: org.apache.dubbo.remoting.RemotingException: Channel NettyChannel [channel=[id: 0xea8a2de3, L:0.0.0.0/0.0.0.0:12792]] is inactive. Directly return the unFinished request : Request [id=126, version=2.0.2, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=queryEomAccountSalePresaleMain, parameterTypes=[class com.oyys.yjyg.service.yy.api.eomAccount.command.PresaleCommand], arguments=[PresaleCommand(segNo=C001, periodCode=202108, presaleType=10, method=ouyeel.apis.gateway.asc.sales.presale, appId=OYXH, sign=NA, timestamp=2021-08-21 18:56:58, customFields=1629543955398, costCenterList=[BSWWAA00], pageIndex=1, pageSize=1000)], attachments={path=com.baosight.shgt.service.yy.api.eomAccount.EomAccountSalePresaleAccountApi, remote.application=fss-account-center, interface=com.baosight.shgt.service.yy.api.eomAccount.EomAccountSalePresaleAccountApi, version=0.0.1, ePlatErrorId=ff526afbe3e94ed68bb17d9687d8481a, consumerApp=fss-account-center, group=yy_run}]]]
% org.apache.dubbo.rpc.RpcException: Failed to invoke the method queryEomAccountSalePresaleMain in the service com.baosight.shgt.service.yy.api.eomAccount.EomAccountSalePresaleAccountApi. Tried 1 times of the providers [10.70.14.81:12200] (1/4) from the registry 10.70.45.1:2181 on the consumer 10.70.114.154 using the dubbo version 2.7.9. Last error is: Failed to invoke remote method: queryEomAccountSalePresaleMain, provider: dubbo://10.70.14.81:12200/com.baosight.shgt.service.yy.api.eomAccount.EomAccountSalePresaleAccountApi?application=fss-account-center&check=false&group=yy_run&init=false&interface=com.baosight.shgt.service.yy.api.eomAccount.EomAccountSalePresaleAccountApi&invokeType=DUBBO&keep.alive=true&pid=71709&reference.filter=oyaccesslog,countInvoke,oplatConsumerLogFilter&register.ip=10.70.114.154&remote.application=285a890d-8137-4e55-b6eb-dcd1b7cba94d&retries=0&revision=0.0.3-release-SNAPSHOT&send.reconnect=true&side=consumer&sticky=false&timeout=500000&version=0.0.1, cause: org.apache.dubbo.remoting.RemotingException: Channel NettyChannel [channel=[id: 0xea8a2de3, L:0.0.0.0/0.0.0.0:12792]] is inactive. Directly return the unFinished request : Request [id=126, version=2.0.2, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=queryEomAccountSalePresaleMain, parameterTypes=[class com.oyys.yjyg.service.yy.api.eomAccount.command.PresaleCommand], arguments=[PresaleCommand(segNo=C001, periodCode=202108, presaleType=10, method=ouyeel.apis.gateway.asc.sales.presale, appId=OYXH, sign=NA, timestamp=2021-08-21 18:56:58, customFields=1629543955398, costCenterList=[BSWWAA00], pageIndex=1, pageSize=1000)], attachments={path=com.baosight.shgt.service.yy.api.eomAccount.EomAccountSalePresaleAccountApi, remote.application=fss-account-center, interface=com.baosight.shgt.service.yy.api.eomAccount.EomAccountSalePresaleAccountApi, version=0.0.1, ePlatErrorId=ff526afbe3e94ed68bb17d9687d8481a, consumerApp=fss-account-center, group=yy_run}]]
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:113) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:265) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:93) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol$MigrationInvoker.invoke(InterfaceCompatibleRegistryProtocol.java:132) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:83) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.common.bytecode.proxy0.queryEomAccountSalePresaleMain(proxy0.java) ~[dubbo-2.7.9.jar:2.7.9]
	at com.ouyeel.account.lot.domain.impl.MsstProxyEomAccountSalePresaleAccountApiImpl.queryEomAccountSalePresaleMain(MsstProxyEomAccountSalePresaleAccountApiImpl.java:14) ~[classes/:1.0-SNAPSHOT]
	at com.ouyeel.account.lot.domain.impl.MsstContrller.sss(MsstContrller.java:20) ~[classes/:1.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648) ~[servlet-api.jar:?]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292) ~[catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-websocket.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.33]
	at com.baosight.iplat4j.core.web.filter.DiagnoseFilter.doFilter(DiagnoseFilter.java:71) ~[iplat4j-core-6.2.1231.4.jar:6.2.1231.4]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.33]
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90) ~[spring-boot-actuator-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.33]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.33]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.33]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.33]
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:130) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:105) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:123) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.33]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117) ~[spring-boot-actuator-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106) ~[spring-boot-actuator-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.33]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) ~[catalina.jar:8.0.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) ~[catalina.jar:8.0.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) ~[catalina.jar:8.0.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) ~[catalina.jar:8.0.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) ~[catalina.jar:8.0.33]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616) ~[catalina.jar:8.0.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) ~[catalina.jar:8.0.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522) ~[catalina.jar:8.0.33]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095) ~[tomcat-coyote.jar:8.0.33]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672) ~[tomcat-coyote.jar:8.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502) ~[tomcat-coyote.jar:8.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458) ~[tomcat-coyote.jar:8.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_91]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.0.33]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.util.concurrent.ExecutionException: org.apache.dubbo.remoting.RemotingException: Channel NettyChannel [channel=[id: 0xea8a2de3, L:0.0.0.0/0.0.0.0:12792]] is inactive. Directly return the unFinished request : Request [id=126, version=2.0.2, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=queryEomAccountSalePresaleMain, parameterTypes=[class com.oyys.yjyg.service.yy.api.eomAccount.command.PresaleCommand], arguments=[PresaleCommand(segNo=C001, periodCode=202108, presaleType=10, method=ouyeel.apis.gateway.asc.sales.presale, appId=OYXH, sign=NA, timestamp=2021-08-21 18:56:58, customFields=1629543955398, costCenterList=[BSWWAA00], pageIndex=1, pageSize=1000)], attachments={path=com.baosight.shgt.service.yy.api.eomAccount.EomAccountSalePresaleAccountApi, remote.application=fss-account-center, interface=com.baosight.shgt.service.yy.api.eomAccount.EomAccountSalePresaleAccountApi, version=0.0.1, ePlatErrorId=ff526afbe3e94ed68bb17d9687d8481a, consumerApp=fss-account-center, group=yy_run}]]
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_91]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915) ~[?:1.8.0_91]
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:181) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.rpc.protocol.AsyncToSyncInvoker.invoke(AsyncToSyncInvoker.java:61) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:78) ~[dubbo-2.7.9.jar:2.7.9]
	at com.oplatdubbo.filter.OplatConsumerLogFilter.invoke(OplatConsumerLogFilter.java:40) ~[eplat-service-dubbo-core-1.0.0-alpha-SNAPSHOT.jar:1.0.0-alpha-SNAPSHOT]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:83) ~[dubbo-2.7.9.jar:2.7.9]
	at com.ouyeel.eplat.dubbo.rpc.log.filter.CountInvokeFilter.invoke(CountInvokeFilter.java:103) ~[eplat-service-dubbo-core-1.0.0-alpha-SNAPSHOT.jar:1.0.0-alpha-SNAPSHOT]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:83) ~[dubbo-2.7.9.jar:2.7.9]
	at com.ouyeel.eplat.dubbo.filter.accesslog.AccessLogFilter.invoke(AccessLogFilter.java:115) ~[eplat-service-dubbo-core-1.0.0-alpha-SNAPSHOT.jar:1.0.0-alpha-SNAPSHOT]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:83) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:89) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:83) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:51) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:83) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:69) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:83) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:82) ~[dubbo-2.7.9.jar:2.7.9]
	... 82 more
Caused by: org.apache.dubbo.remoting.RemotingException: Channel NettyChannel [channel=[id: 0xea8a2de3, L:0.0.0.0/0.0.0.0:12792]] is inactive. Directly return the unFinished request : Request [id=126, version=2.0.2, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=queryEomAccountSalePresaleMain, parameterTypes=[class com.oyys.yjyg.service.yy.api.eomAccount.command.PresaleCommand], arguments=[PresaleCommand(segNo=C001, periodCode=202108, presaleType=10, method=ouyeel.apis.gateway.asc.sales.presale, appId=OYXH, sign=NA, timestamp=2021-08-21 18:56:58, customFields=1629543955398, costCenterList=[BSWWAA00], pageIndex=1, pageSize=1000)], attachments={path=com.baosight.shgt.service.yy.api.eomAccount.EomAccountSalePresaleAccountApi, remote.application=fss-account-center, interface=com.baosight.shgt.service.yy.api.eomAccount.EomAccountSalePresaleAccountApi, version=0.0.1, ePlatErrorId=ff526afbe3e94ed68bb17d9687d8481a, consumerApp=fss-account-center, group=yy_run}]]
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.doReceived(DefaultFuture.java:212) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:175) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:163) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.closeChannel(DefaultFuture.java:156) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.disconnected(HeaderExchangeHandler.java:134) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.remoting.transport.AbstractChannelHandlerDelegate.disconnected(AbstractChannelHandlerDelegate.java:48) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:73) ~[dubbo-2.7.9.jar:2.7.9]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_91]

```

**Comment by HTFX-Cloud** [comment]
您好  我看问题关闭了。请问是怎么解决的呢？
