### ISSUE TITLE
nacos多注册中心consumer本地缓存服务列表不刷新

### ISSUE THREAD

**Issue by wangly0122** [apache/dubbo#8575]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.2
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

1. 在k8s 启动 consumer,
2. 在k8s 启动provider, 如ip为10.233.87.181

当provider 挂掉重启后， ip变为为10.233.68.188， consumer 本地缓存的服务列表 provider仍然为10.233.87.181，这样consumer消费的还是之前挂掉的ip，
这样每次provider重启后，consumer不得不一起重启

问题：

consumer本地缓存的服务列表为啥不更新，比如有个心跳检测机制，剔除那些挂掉的节点，从而刷新consumer本地的服务列表

```
Just put your stack trace here!
```

**Comment by tangtaotao2021** [comment]
我也遇到同样的问题
**运行环境**
nacos服务端：2.0.2
nacos客户端 ：1.3.3
dubbo：2.7.12

**问题**
应用是采用k8s部署，服务端之前IP地址是172.18.2.28，重启后注册地址更改为 172.18.0.174，查看客户端日志有收到 地址变为172.18.0.174记录，但是再次调用时依旧使用的172.18.2.28调用，导致报错。

2021-08-24 00:32:13.368 [com.alibaba.nacos.naming.push.receiver] INFO com.alibaba.nacos.client.naming:228 - current ips:(1) service: product team@@srm-account -> [{"instanceId":"172.18.0.174#11000#DEFAULT#product team@@srm-account","ip":"172.18.0.174","port":11000,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"product team@@srm-account","metadata":{"dubbo.metadata-service.urls":"[ "dubbo://172.18.0.174:20880/com.alibaba.cloud.dubbo.service.DubboMetadataService?anyhost=true&application=srm-account&bind.ip=172.18.0.174&bind.port=20880&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&group=srm-account&interface=com.alibaba.cloud.dubbo.service.DubboMetadataService&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=7&qos.enable=false&release=2.7.12&revision=2.2.3.RELEASE&service.name=ServiceBean:srm-account/com.alibaba.cloud.dubbo.service.DubboMetadataService:1.0.0&side=provider&timestamp=1629736306804&version=1.0.0" ]","preserved.register.source":"SPRING_CLOUD","dubbo.protocols.dubbo.port":"20880"},"ipDeleteTimeout":30000,"instanceHeartBeatTimeOut":15000,"instanceHeartBeatInterval":5000}]
2021-08-24 00:33:00.547 [dubbo-client-idleCheck-thread-1] ERROR o.a.d.r.exchange.support.header.ReconnectTimerTask:51 - [DUBBO] Fail to connect to HeaderExchangeClient [channel=org.apache.dubbo.remoting.transport.netty4.NettyClient [/172.18.2.91:54346 -> /172.18.2.28:20880]], dubbo version: 2.7.12, current host: 172.18.2.91 org.apache.dubbo.remoting.RemotingException: client(url: dubbo://172.18.2.28:20880/com.alibaba.cloud.dubbo.service.DubboMetadataService?anyhost=true&application=srm-message&bind.ip=172.18.2.28&bind.port=20880&check=false&codec=dubbo&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&group=srm-account&heartbeat=60000&interface=com.alibaba.cloud.dubbo.service.DubboMetadataService&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=7&qos.enable=false®ister.ip=172.18.2.91&release=2.7.12&remote.application=srm-account&revision=2.2.3.RELEASE&service.name=ServiceBean:srm-account/com.alibaba.cloud.dubbo.service.DubboMetadataService:1.0.0&side=consumer&sticky=false&timeout=5000×tamp=1629732897642&version=1.0.0) failed to connect to server /172.18.2.28:20880 client-side timeout 3000ms (elapsed: 3001ms) from netty client 172.18.2.91 using dubbo version 2.7.12 at org.apache.dubbo.remoting.transport.netty4.NettyClient.doConnect(NettyClient.java:174) at org.apache.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:198) at org.apache.dubbo.remoting.transport.AbstractClient.reconnect(AbstractClient.java:254) at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeClient.reconnect(HeaderExchangeClient.java:166) at org.apache.dubbo.remoting.exchange.support.header.ReconnectTimerTask.doTask(ReconnectTimerTask.java:49) at org.apache.dubbo.remoting.exchange.support.header.AbstractTimerTask.run(AbstractTimerTask.java:87) at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:648) at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:727) at org.apache.dubbo.common.timer.HashedWheelTimer$Worker.run(HashedWheelTimer.java:449) at java.lang.Thread.run(Thread.java:748)

**Comment by plusmancn** [comment]
See #7822

**Comment by plusmancn** [comment]
@tangtaotao2021 Have a try with Nacos Client 2.0 +.

**Comment by kuailejiandan** [comment]
@tangtaotao2021 确认下是否开启了dubbo的消费者订阅,这个应该是服务提供者接口列表更新不及时的问题

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
