### ISSUE TITLE
Failed to deserialize response

### ISSUE THREAD

**Issue by pengweijun1988** [apache/dubbo#8576]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

threadpool=cached&timestamp=1629701590849, cause: org.apache.dubbo.remoting.RemotingException: Failed to deserialize response
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:110) ~[dubbo-3.0.2.jar!/:3.0.2]
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:265) ~[dubbo-3.0.2.jar!/:3.0.2]
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:89) ~[dubbo-3.0.2.jar!/:3.0.2]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82) ~[dubbo-3.0.2.jar!/:3.0.2]
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:51) ~[dubbo-3.0.2.jar!/:3.0.2]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82) ~[dubbo-3.0.2.jar!/:3.0.2]
	at org.apache.dubbo.rpc.cluster.filter.support.ConsumerContextFilter.invoke(ConsumerContextFilter.java:101) ~[dubbo-3.0.2.jar!/:3.0.2]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:82) ~[dubbo-3.0.2.jar!/:3.0.2]
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$ClusterFilterInvoker.invoke(AbstractCluster.java:93) ~[dubbo-3.0.2.jar!/:3.0.2]
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:93) ~[dubbo-3.0.2.jar!/:3.0.2]
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.invoke(MigrationInvoker.java:276) ~[dubbo-3.0.2.jar!/:3.0.2]
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:95) ~[dubbo-3.0.2.jar!/:3.0.2]

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by AlbumenJ** [comment]
Please upgrade to 3.0.2.1

**Comment by CrazyHZM** [comment]
Close this issue temporarily, if there are still problems after the upgrade, you can open the issue at any time.
