### ISSUE TITLE
consumer version 2.6.2 provider 2.7.4  java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by BoyLearnGit** [apache/dubbo#8625]
provider no error，consumer‘s error is ava.util.ConcurrentModificationException
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:769)
        at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:778)
        at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2140)
        at org.apache.dubbo.rpc.AsyncRpcResult.whenCompleteWithContext(AsyncRpcResult.java:153)
        at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$CallbackRegistrationInvoker.invoke(ProtocolFilterWrapper.java:159)
        at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:152)
        at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:102)
        at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:193)
        at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
        at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1471)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1469)
        at java.util.HashMap.putMapEntries(HashMap.java:511)
        at java.util.HashMap.putAll(HashMap.java:784)
        at org.apache.dubbo.rpc.AppResponse.addAttachments(AppResponse.java:138)
        at org.apache.dubbo.rpc.filter.ContextFilter$ContextListener.onResponse(ContextFilter.java:117)
        at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$CallbackRegistrationInvoker.lambda$invoke$0(ProtocolFilterWrapper.java:167)
        at org.apache.dubbo.rpc.AsyncRpcResult.lambda$whenCompleteWithContext$0(AsyncRpcResult.java:155)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
        ... 12 more

**Comment by CrazyHZM** [comment]
Temporarily close the issue first, if there is still a problem, you can reopen the issue.
