### ISSUE TITLE
URL.equals抛出npe

### ISSUE THREAD

**Issue by houseyoung** [apache/dubbo#8638]
使用dubbo 2.7.13作为客户端时（2.7.10、2.7.12也都试过），provider发布时，consumer报出如下异常：

Failed to notify addresses for subscribe consumer://172.20.9.10/XXXXXX?application=YYYYY&category=providers,configurators,routers&check=false&dubbo=2.0.2&init=false&interface=ZZZZZ&metadata-type=remote&methods=AAA,BBB,CCC&pid=1&release=2.7.13&revision=1.0.3-rel-SNAPSHOT&side=consumer&sticky=false&timeout=6000&timestamp=1630303343085, cause: null, dubbo version: 2.7.13, current host: 172.20.9.10 java.lang.NullPointerException: null
	at org.apache.dubbo.common.URL.equals(URL.java:1693)
at java.util.HashMap.getNode(HashMap.java:572) 	at java.util.HashMap.containsKey(HashMap.java:596) 	at java.util.HashSet.contains(HashSet.java:204) 	at org.apache.dubbo.registry.integration.RegistryDirectory.toInvokers(RegistryDirectory.java:312) 	at org.apache.dubbo.registry.integration.RegistryDirectory.refreshInvoker(RegistryDirectory.java:190) 	at org.apache.dubbo.registry.integration.RegistryDirectory.refreshOverrideAndInvoker(RegistryDirectory.java:150) 	at org.apache.dubbo.registry.integration.RegistryDirectory.notify(RegistryDirectory.java:132) 	at org.apache.dubbo.registry.support.AbstractRegistry.notify(AbstractRegistry.java:429) 	at org.apache.dubbo.registry.support.FailbackRegistry.doNotify(FailbackRegistry.java:372)

1693行是if (!parameters.get(key).equals(other.parameters.get(key))) {
我理解这个地方是不可能出现npe的吧？

最头痛的事，测试环境也没有出现，日志也一行都没有打，我们也不可能在线上环境做远程调试……现在完全没办法排查问题。

**Comment by houseyoung** [comment]
原因找到了，是provider出现了双重注册，一个ip注册了两个node导致的。

**Comment by houseyoung** [comment]
已解决，我们用的是阿里云的mse做zk，mse的服务治理如果没开通，会写入一个空的remote.project.name字段到zk，只有key没有value，所以导致了npe。
