### ISSUE TITLE
dubbo:provider has tag  group java.lang.NullPointerException

### ISSUE THREAD

**Issue by TraceRoad** [apache/dubbo#8649]
### Environment

* Dubbo version: 2.7.5
* Operating System version: win10
* Java version: 1.8.0_251

### Steps to reproduce this issue

1. spring-dubbo.xml:<dubbo:provider id="playload" application="dubbo-provider-xml-demo" payload="20140" accepts="" group="112233"/>
2.java.lang.NullPointerException
	at org.apache.dubbo.registry.integration.RegistryProtocol.register(RegistryProtocol.java:178)
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:209)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:60)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:64)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:143)
3. cause:registeredProviderUrl.getServiceKey()=“112233/com.mq.demo.service.DubboService” can not find from ServiceRepository.providers

**Comment by RuoBingCoder** [comment]
Are you sure your service is registered?
