### ISSUE TITLE
dubbo3.0 使用nacos作为注册中心无法注册，3.0版本是否支持nacos作为注册中心？

### ISSUE THREAD

**Issue by sakka6868** [apache/dubbo#8652]
### Environment

* Dubbo version: 3.0.0
* Operating System version: win10
* Java version: open-jdk-8

### Steps to reproduce this issue
![image](https://user-images.githubusercontent.com/23228684/131674056-138253dc-d224-4a44-a7e8-8576dc041738.png)
在dubbo3.0 我想使用nacos作为配置中心，但是一直注册不成功
`[01/09/21 08:51:13:013 CST] main ERROR nacos.NacosRegistry:  [DUBBO] Request nacos server failed: , dubbo version: 3.0.0, current host: 192.168.1.3
ErrCode:500, ErrMsg:Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:213)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:101)
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:95)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:139)
	at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.registerInstance(NacosNamingServiceWrapper.java:57)
	at org.apache.dubbo.registry.nacos.NacosRegistry.lambda$doRegister$1(NacosRegistry.java:164)
	at org.apache.dubbo.registry.nacos.NacosRegistry$$Lambda$145/16664573.callback(Unknown Source)
	at org.apache.dubbo.registry.nacos.NacosRegistry.execute(NacosRegistry.java:567)
	at org.apache.dubbo.registry.nacos.NacosRegistry.doRegister(NacosRegistry.java:164)
	at org.apache.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:205)
	at org.apache.dubbo.registry.ListenerRegistryWrapper.register(ListenerRegistryWrapper.java:58)
	at org.apache.dubbo.registry.integration.RegistryProtocol.register(RegistryProtocol.java:183)
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:219)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:64)
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:60)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:64)
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:511)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:344)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:320)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:219)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.exportServices(DubboBootstrap.java:1295)`

**Comment by plusmancn** [comment]
@plusmancn mark

**Comment by AlbumenJ** [comment]
dubbo 3.0 需要使用 nacos 2.0.0 及以上版本

**Comment by sakka6868** [comment]
> dubbo 3.0 需要使用 nacos 2.0.0 及以上版本

改用nacos 2.0.3 同样服务注册

`[09/09/21 10:50:58:058 CST] main ERROR nacos.NacosRegistry:  [DUBBO] Request nacos server failed: , dubbo version: 3.0.0, current host: 192.168.1.4
ErrCode:500, ErrMsg:Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:213)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:101)
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:95)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:139)
	at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.registerInstance(NacosNamingServiceWrapper.java:57)
	at org.apache.dubbo.registry.nacos.NacosRegistry.lambda$doRegister$1(NacosRegistry.java:164)
	at org.apache.dubbo.registry.nacos.NacosRegistry$$Lambda$145/30306181.callback(Unknown Source)
	at org.apache.dubbo.registry.nacos.NacosRegistry.execute(NacosRegistry.java:567)
	at org.apache.dubbo.registry.nacos.NacosRegistry.doRegister(NacosRegistry.java:164)
	at org.apache.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:205)
	at org.apache.dubbo.registry.ListenerRegistryWrapper.register(ListenerRegistryWrapper.java:58)
	at org.apache.dubbo.registry.integration.RegistryProtocol.register(RegistryProtocol.java:183)
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:219)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:64)
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:60)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:64)
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:511)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:344)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:320)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:219)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.exportServices(DubboBootstrap.java:1295)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:1090)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onContextRefreshedEvent(DubboBootstrapApplicationListener.java:70)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onApplicationContextEvent(DubboBootstrapApplicationListener.java:63)
	at com.alibaba.spring.context.OnceApplicationContextEventListener.onApplicationEvent(OnceApplicationContextEventListener.java:52)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
	at org.apache.dubbo.samples.ProviderBootstrap.main(ProviderBootstrap.java:32)
Caused by: ErrCode:-401, ErrMsg:Client not connected,current status:STARTING
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:628)
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:608)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:203)
	... 34 more`

**Comment by plusmancn** [comment]
@sakka6868 Please provide a demo application to reproduce the problem.

**Comment by AlbumenJ** [comment]
> > dubbo 3.0 需要使用 nacos 2.0.0 及以上版本
> 
> 改用nacos 2.0.3 同样服务注册
> 
> `[09/09/21 10:50:58:058 CST] main ERROR nacos.NacosRegistry: [DUBBO] Request nacos server failed: , dubbo version: 3.0.0, current host: 192.168.1.4 ErrCode:500, ErrMsg:Request nacos server failed: at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:213) at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:101) at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:95) at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:139) at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.registerInstance(NacosNamingServiceWrapper.java:57) at org.apache.dubbo.registry.nacos.NacosRegistry.lambda$doRegister$1(NacosRegistry.java:164) at org.apache.dubbo.registry.nacos.NacosRegistry$$Lambda$145/30306181.callback(Unknown Source) at org.apache.dubbo.registry.nacos.NacosRegistry.execute(NacosRegistry.java:567) at org.apache.dubbo.registry.nacos.NacosRegistry.doRegister(NacosRegistry.java:164) at org.apache.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:205) at org.apache.dubbo.registry.ListenerRegistryWrapper.register(ListenerRegistryWrapper.java:58) at org.apache.dubbo.registry.integration.RegistryProtocol.register(RegistryProtocol.java:183) at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:219) at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:64) at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:60) at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:64) at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:511) at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:344) at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:320) at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:219) at org.apache.dubbo.config.bootstrap.DubboBootstrap.exportServices(DubboBootstrap.java:1295) at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:1090) at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onContextRefreshedEvent(DubboBootstrapApplicationListener.java:70) at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onApplicationContextEvent(DubboBootstrapApplicationListener.java:63) at com.alibaba.spring.context.OnceApplicationContextEventListener.onApplicationEvent(OnceApplicationContextEventListener.java:52) at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393) at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347) at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883) at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84) at org.apache.dubbo.samples.ProviderBootstrap.main(ProviderBootstrap.java:32) Caused by: ErrCode:-401, ErrMsg:Client not connected,current status:STARTING at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:628) at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:608) at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:203) ... 34 more`

nacos 服务端也需要升级

**Comment by sakka6868** [comment]
> @sakka6868 Please provide a demo application to help us to reproduce the problem.

[https://github.com/sakka6868/dubbo-demo.git](url)

**Comment by sakka6868** [comment]
> > > dubbo 3.0 需要使用 nacos 2.0.0 及以上版本
> > 
> > 
> > 改用nacos 2.0.3 同样服务注册
> > `[09/09/21 10:50:58:058 CST] main ERROR nacos.NacosRegistry: [DUBBO] Request nacos server failed: , dubbo version: 3.0.0, current host: 192.168.1.4 ErrCode:500, ErrMsg:Request nacos server failed: at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:213) at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:101) at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:95) at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:139) at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.registerInstance(NacosNamingServiceWrapper.java:57) at org.apache.dubbo.registry.nacos.NacosRegistry.lambda$doRegister$1(NacosRegistry.java:164) at org.apache.dubbo.registry.nacos.NacosRegistry$$Lambda$145/30306181.callback(Unknown Source) at org.apache.dubbo.registry.nacos.NacosRegistry.execute(NacosRegistry.java:567) at org.apache.dubbo.registry.nacos.NacosRegistry.doRegister(NacosRegistry.java:164) at org.apache.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:205) at org.apache.dubbo.registry.ListenerRegistryWrapper.register(ListenerRegistryWrapper.java:58) at org.apache.dubbo.registry.integration.RegistryProtocol.register(RegistryProtocol.java:183) at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:219) at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:64) at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:60) at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:64) at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:511) at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:344) at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:320) at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:219) at org.apache.dubbo.config.bootstrap.DubboBootstrap.exportServices(DubboBootstrap.java:1295) at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:1090) at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onContextRefreshedEvent(DubboBootstrapApplicationListener.java:70) at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onApplicationContextEvent(DubboBootstrapApplicationListener.java:63) at com.alibaba.spring.context.OnceApplicationContextEventListener.onApplicationEvent(OnceApplicationContextEventListener.java:52) at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393) at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347) at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883) at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84) at org.apache.dubbo.samples.ProviderBootstrap.main(ProviderBootstrap.java:32) Caused by: ErrCode:-401, ErrMsg:Client not connected,current status:STARTING at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:628) at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:608) at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:203) ... 34 more`
> 
> nacos 服务端也需要升级

![image](https://user-images.githubusercontent.com/23228684/134111549-46b0fd9b-d449-436f-83e3-43df0ffb2564.png)
使用的正是2.0.0以上的版本

**Comment by AlbumenJ** [comment]
![image](https://user-images.githubusercontent.com/9292748/134208337-45608b6e-05bd-44ad-ab02-68fbd557a93f.png)

@sakka6868 sample 在我这边运行时正常的，我的 Nacos Server 是 2.0.1 版本的，请求 500 或者 401 可以去 nacos 社区看下有没有相关问题，或者是具体开启下 nacos 的详细日志（如果有）。

**Comment by CrazyHZM** [comment]
@sakka6868  Close the issue temporarily, if you have other questions, you can reopen the issue.

**Comment by sakka6868** [comment]
> ![image](https://user-images.githubusercontent.com/9292748/134208337-45608b6e-05bd-44ad-ab02-68fbd557a93f.png)
> 
> @sakka6868 sample 在我这边运行时正常的，我的 Nacos Server 是 2.0.1 版本的，请求 500 或者 401 可以去 nacos 社区看下有没有相关问题，或者是具体开启下 nacos 的详细日志（如果有）。
![image](https://user-images.githubusercontent.com/23228684/134336293-bd4503ed-310a-4f96-a50b-e0afaa082c09.png)
找到原因了😂nacos 2.0后用grpc通信，我的nacos是在容器里的，没有暴露那两个端口
