### ISSUE TITLE
[3.0] ServiceDiscoveryRegistryDirectory的refreshInvoker方法和isAvailable存在并行执行冲突

### ISSUE THREAD

**Issue by zrlw** [apache/dubbo#8675]
### Environment

* Dubbo version: 3.0
集成构建时，执行GenericServiceTest测试方法下面的语句时，
```
        // Test generic service without interface class locally
        result = genericServiceWithoutInterfaceRef.$invoke("sayHello", new String[]{"java.lang.String"}, new Object[]{"generic"});
```
ReferenceConfig的checkInvokerAvailable方法有时会抛异常，导致集成构建失败，异常信息如下：
java.lang.IllegalStateException: Failed to check the status of the service org.apache.dubbo.config.spring.api.LocalMissClass. No provider available for the service org.apache.dubbo.config.spring.api.LocalMissClass from the url dubbo://10.1.0.184/org.apache.dubbo.config.spring.api.LocalMissClass?application=dubbo-generic-consumer&dubbo=2.0.2&file.cache=false&generic=true&init=false&interface=org.apache.dubbo.config.spring.api.LocalMissClass&metadata-type=remote&pid=9816&register.ip=10.1.0.184&release=3.0.3-SNAPSHOT&side=consumer&sticky=false&timestamp=1630699707283 to the consumer 10.1.0.184 use dubbo version 3.0.3-SNAPSHOT
	at org.apache.dubbo.config.spring.schema.GenericServiceTest.testGeneric(GenericServiceTest.java:97)

* 更新2021-09-10：
执行ServiceDiscoveryRegistryDirectory的refreshInvoker方法刷新urlInvokerMap的线程和执行ReferenceConfig的init方法的线程不是一个线程，刷新的线程名是main-EventThread，执行init的线程是main线程。而refreshInvoker方法调用toInvokers时会先把当前的this.urlInvokerMap里面的entry全清，在将newUrlInvokerMap重新赋值给this.urlInvokerMap前，如果恰好遇到执行init的main线程在执行isAvailable判断就会因为this.urlInvokerMap没有entry而返回false。
重现方法：在ServiceDiscoveryRegistryDirectory的toInvokers方法调用返回的下一行代码设置断点，在isAvailable的Map<String, Invoker<T>> localUrlInvokerMap = urlInvokerMap处设置断点，执行到toInvokers返回时暂停main-EventThread线程执行，切换到停留在isAvailable的main线程继续执行，就能重现这个issue。

PS：
采用genericServiceWithoutInterface方式的JavaConfigReferenceBeanTest的testGenericServiceAnnotationBean方法的165行有时也抛异常
* 更新2021-09-10：这个RpcException异常可能是上一个测试方法执行AfterEach释放了全局资源干扰了仍在运行的dubbo后台线程导致的，已另开issue
```
        Object sayHelloResult = genericServiceWithoutInterface.$invoke("sayHello", new String[]{"java.lang.String"}, new Object[]{"Dubbo"});
```
只是抛的异常是RpcException: Directory already destroyed
```
2021-09-03T18:39:04.9792146Z org.apache.dubbo.rpc.RpcException: Directory already destroyed .url: zookeeper://127.0.0.1:2181/org.apache.dubbo.registry.RegistryService?application=consumer-app&dubbo=2.0.2&file.cache=false&pid=8884&release=3.0.3-SNAPSHOT&timestamp=1630694303313
2021-09-03T18:39:04.9797067Z 	at org.apache.dubbo.config.spring.reference.javaconfig.JavaConfigReferenceBeanTest.testGenericServiceAnnotationBean(JavaConfigReferenceBeanTest.java:165)
```

**Comment by EarthChen** [comment]
Have you found any rules that can help？

**Comment by zrlw** [comment]
感觉这个问题和 #8676 是同一个问题，github自动构建环境可能有多块网卡，没有配置DUBBO_IP_TO_BIND参数时，ServiceConfig的findConfigedHosts调用InetAddress.getLocalHost().getHostAddress()获得GenericServiceTest测试类的服务绑定IP地址是随机的，而ReferenceConfig构造Reference引用调用的是NetUtils.getLocalHost()，多网卡环境下二者返回地址会不一致。

**Comment by zrlw** [comment]
从github构建日志看，genericServiceWithoutInterface.$invoke这个ReferenceBean是lazy initializing: 
```
2021-09-04T20:19:48.3314340Z 20:19:47.115 [main] DEBUG org.apache.dubbo.config.spring.ReferenceBean$DubboReferenceLazyInitTargetSource - Initializing lazy target object
```
也就是说单元测试执行到下面这条语句时才会创建这个ReferenceBean：
```
result = genericServiceWithoutInterfaceRef.$invoke("sayHello", new String[]{"java.lang.String"}, new Object[]{"generic"});
```
但是ReferenceConfig的init方法最后要调用checkInvokerAvailable去检查invoker连接是否已经ok，节奏是不是有点太快了，延迟初始化的ReferenceBean刚完成构建，相关的连接立马就ok？
github日志显示100ms后，mian线程收到一个null应答后就开始Unsubscribe了：
```
2021-09-04T20:19:48.3751852Z 20:19:47.246 [main-SendThread(MiningMadness.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x10000493ad40000, packet:: clientPath:null serverPath:null finished:false header:: 147,2  replyHeader:: 147,41,0  request:: '/dubbo/org.apache.dubbo.config.spring.api.LocalMissClass/consumers/dubbo%253A%252F%252F172.17.16.1%252Forg.apache.dubbo.config.spring.api.LocalMissClass%253Fapplication%253Ddubbo-generic-consumer%2526category%253Dconsumers%2526check%253Dfalse%2526dubbo%253D2.0.2%2526file.cache%253Dfalse%2526generic%253Dtrue%2526init%253Dfalse%2526interface%253Dorg.apache.dubbo.config.spring.api.LocalMissClass%2526metadata-type%253Dremote%2526pid%253D6992%2526release%253D3.0.3-SNAPSHOT%2526side%253Dconsumer%2526sticky%253Dfalse%2526timestamp%253D1630786787116,-1  response:: null
2021-09-04T20:19:48.3759385Z [04/09/21 20:19:47:247 UTC] main  INFO zookeeper.ZookeeperRegistry:  [DUBBO] Unsubscribe: dubbo://172.17.16.1/org.apache.dubbo.config.spring.api.LocalMissClass?application=dubbo-generic-consumer&category=providers,configurators,routers&dubbo=2.0.2&file.cache=false&generic=true&init=false&interface=org.apache.dubbo.config.spring.api.LocalMissClass&metadata-type=remote&pid=6992&release=3.0.3-SNAPSHOT&side=consumer&sticky=false&timestamp=1630786787116, dubbo version: 3.0.3-SNAPSHOT, current host: 172.17.16.1
```
完整日志见：
https://github.com/apache/dubbo/runs/3514650085?check_suite_focus=true  点设置里的download log archive，下载后打开里面的 4_Unit Test On windows-2019 (JDK 11).txt，文件很大，记事本打不开或者龟速，需要用notepad++之类的大文件编辑工具看。

**Comment by zrlw** [comment]
今天几个PR触发的构建失败日志，发现里面也有
GenericServiceTest.testGeneric:97 » IllegalState Failed to check the status of...

**Comment by zrlw** [comment]
前面92行的demoServiceRef.$invoke调用成功说明网络没有问题，日志里没有netty连接断开的信息，这两个Reference用的是一个长连接。
跟踪了一下checkInvokerAvailable，调用的是ServiceDiscoveryRegistryDirectory的isAvailable方法：
```
    public boolean isAvailable() {
        if (isDestroyed()) {
            return false; <== 如果已经destroyed，则会触发Failed to check the status
        }
        Map<String, Invoker<T>> localUrlInvokerMap = urlInvokerMap;  <== 这个如果为空，那么也会触发
        if (localUrlInvokerMap != null && localUrlInvokerMap.size() > 0) {
            for (Invoker<T> invoker : new ArrayList<>(localUrlInvokerMap.values())) {
                if (invoker.isAvailable()) {
                    return true;
                }
            }
        }
        return false;
    }
```
日志里没看到和destroy相关的信息，怀疑urlInvokerMap这个东西是空导致的问题，看了代码，这个东西是refreshInvoker刷进来的，跟踪了一下，貌似刷新的线程和执行ReferenceConfig的init方法的线程不是一个，刷新的线程名是main-EventThread，执行init的线程是main线程。跟进去refreshInvoker方法，发现这个方法调用toInvokers先把当前的urlInvokerMap里面的内容全清掉，在this.urlInvokerMap = newUrlInvokerMap重新赋值前，如果执行init的main线程去执行isAvailable就会返回false，debug在toInvokers方法后暂停main-EventThread线程继续执行，就能重新这个场景。
做了个PR，才发现最新3.0分支的GenericServiceTest拆成了两个测试类，分拆之后原来的代码出异常的概率可能就小了。

**Comment by zrlw** [comment]
看了一下3.0的RegistryDirectory，isAvailable和refreshInvoker也存在同样的问题啊，弱引用不该这么用的吧，
两个方法都去弱引用urlInvokerMap这个集合，main线程执行isAvailable方法检查弱引用集合是否为空、不为空则进行遍历的时候，main-eventThread线程执行refreshInvoker对弱引用集合里面的entry直接进行remove，合适么？
