### ISSUE TITLE
github构建日志里有很多涉及RegistryProtocol的异常

### ISSUE THREAD

**Issue by zrlw** [apache/dubbo#8681]
### Environment

* Dubbo version: 3.0

### Steps to reproduce this issue
翻看github构建日志本来是去找GenericServiceTest为啥常常出现java.lang.IllegalStateException: Failed to check the status of the service org.apache.dubbo.config.spring.api.LocalMissClass的线索，相关的线索没找到，却找到了这个
2021-09-04T20:19:48.3933128Z [04/09/21 20:19:47:427 UTC] main  WARN integration.RegistryProtocol:  [DUBBO] unsubscribe listener == null, dubbo version: 3.0.3-SNAPSHOT, current host: 172.17.16.1
2021-09-04T20:19:48.3934495Z java.lang.IllegalArgumentException: unsubscribe listener == null
2021-09-04T20:19:48.3936385Z 	at org.apache.dubbo.registry.support.AbstractRegistry.unsubscribe(AbstractRegistry.java:329)
2021-09-04T20:19:48.3938947Z 	at org.apache.dubbo.registry.support.FailbackRegistry.unsubscribe(FailbackRegistry.java:328)
2021-09-04T20:19:48.3942540Z 	at org.apache.dubbo.registry.ListenerRegistryWrapper.unsubscribe(ListenerRegistryWrapper.java:134)
2021-09-04T20:19:48.3945186Z 	at org.apache.dubbo.registry.integration.RegistryProtocol$ExporterChangeableWrapper.unexport(RegistryProtocol.java:876)
2021-09-04T20:19:48.3948433Z 	at org.apache.dubbo.registry.integration.RegistryProtocol$DestroyableExporter.unexport(RegistryProtocol.java:669)
2021-09-04T20:19:48.3950662Z 	at org.apache.dubbo.config.ServiceConfig.unexport(ServiceConfig.java:187)
2021-09-04T20:19:48.3952706Z 	at org.apache.dubbo.config.bootstrap.DubboBootstrap.lambda$unexportServices$9(DubboBootstrap.java:1487)
2021-09-04T20:19:48.3954404Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2021-09-04T20:19:48.3956255Z 	at org.apache.dubbo.config.bootstrap.DubboBootstrap.unexportServices(DubboBootstrap.java:1484)
2021-09-04T20:19:48.3958714Z 	at org.apache.dubbo.config.bootstrap.DubboBootstrap.destroy(DubboBootstrap.java:1635)
2021-09-04T20:19:48.3960885Z 	at org.apache.dubbo.config.bootstrap.DubboBootstrap.reset(DubboBootstrap.java:239)
2021-09-04T20:19:48.3963018Z 	at org.apache.dubbo.config.bootstrap.DubboBootstrap.reset(DubboBootstrap.java:225)
2021-09-04T20:19:48.3965492Z 	at org.apache.dubbo.config.spring.schema.GenericServiceTest.tearDown(GenericServiceTest.java:67)
并且不止这一个测试类抛这个异常，有十多个测试类都抛这个东西，看了看代码，感觉应该是重复注销导致的，RegistryProtocol注销listener前检查一下是否为null应该就能避免这个异常了。

**Comment by zrlw** [comment]
顺便看了一下2.7.x的构建日志，RegistryProtocol也有问题：
1. NPE （invoker尚未创建就去或取invoker的url）
2021-09-04T18:15:20.5853500Z java.lang.NullPointerException
2021-09-04T18:15:20.5855218Z 	at org.apache.dubbo.registry.integration.RegistryProtocol$OverrideListener.doOverrideIfNecessary(RegistryProtocol.java:691)
2021-09-04T18:15:20.5857572Z 	at org.apache.dubbo.registry.integration.RegistryProtocol$OverrideListener.notify(RegistryProtocol.java:672)
2021-09-04T18:15:20.5859640Z 	at org.apache.dubbo.registry.support.AbstractRegistry.notify(AbstractRegistry.java:429)
2021-09-04T18:15:20.5861641Z 	at org.apache.dubbo.registry.support.FailbackRegistry.doNotify(FailbackRegistry.java:372)
2021-09-04T18:15:20.5863623Z 	at org.apache.dubbo.registry.support.FailbackRegistry.notify(FailbackRegistry.java:364)
2021-09-04T18:15:20.5865836Z 	at org.apache.dubbo.registry.zookeeper.ZookeeperRegistry.doSubscribe(ZookeeperRegistry.java:181)
2021-09-04T18:15:20.5868092Z 	at org.apache.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:299)
2021-09-04T18:15:20.5870274Z 	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:105)
2021-09-04T18:15:20.5872504Z 	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:232)
2021-09-04T18:15:20.5874770Z 	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:62)
2021-09-04T18:15:20.5877025Z 	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:73)
2021-09-04T18:15:20.5878629Z 	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
2021-09-04T18:15:20.5880268Z 	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:518)
2021-09-04T18:15:20.5882154Z 	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:339)
2021-09-04T18:15:20.5883655Z 	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:314)
2021-09-04T18:15:20.5885108Z 	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:238)
2021-09-04T18:15:20.5886991Z 	at org.apache.dubbo.config.ReferenceConfigTest.testReferenceRetry(ReferenceConfigTest.java:135)
2. 空对象触发的IllegalStateException（applicationconfig已被remove过，重复remove，这个和3.0的重复remove问题是一样的）
2021-09-04T18:15:20.6212943Z [04/09/21 18:15:20:515 UTC] main  WARN config.DubboShutdownHook:  [DUBBO] There's no ApplicationConfig specified., dubbo version: 2.7.14-SNAPSHOT, current host: 172.30.128.1
2021-09-04T18:15:20.6214168Z java.lang.IllegalStateException: There's no ApplicationConfig specified.
2021-09-04T18:15:20.6215788Z 	at org.apache.dubbo.config.context.ConfigManager.lambda$getApplicationOrElseThrow$0(ConfigManager.java:90)
2021-09-04T18:15:20.6217286Z 	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
2021-09-04T18:15:20.6219073Z 	at org.apache.dubbo.config.context.ConfigManager.getApplicationOrElseThrow(ConfigManager.java:90)
2021-09-04T18:15:20.6221553Z 	at org.apache.dubbo.rpc.model.ApplicationModel.getApplicationConfig(ApplicationModel.java:100)
2021-09-04T18:15:20.6223542Z 	at org.apache.dubbo.rpc.model.ApplicationModel.getName(ApplicationModel.java:104)
2021-09-04T18:15:20.6225416Z 	at org.apache.dubbo.rpc.model.ApplicationModel.getApplication(ApplicationModel.java:112)
2021-09-04T18:15:20.6227550Z 	at org.apache.dubbo.registry.integration.RegistryProtocol.destroy(RegistryProtocol.java:576)
2021-09-04T18:15:20.6229816Z 	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.destroy(ProtocolListenerWrapper.java:82)
2021-09-04T18:15:20.6232100Z 	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.destroy(ProtocolFilterWrapper.java:88)
2021-09-04T18:15:20.6234226Z 	at org.apache.dubbo.config.DubboShutdownHook.destroyProtocols(DubboShutdownHook.java:143)
2021-09-04T18:15:20.6236115Z 	at org.apache.dubbo.config.DubboShutdownHook.doDestroy(DubboShutdownHook.java:118)
2021-09-04T18:15:20.6237851Z 	at org.apache.dubbo.config.DubboShutdownHook.destroyAll(DubboShutdownHook.java:131)
2021-09-04T18:15:20.6239637Z 	at org.apache.dubbo.config.bootstrap.DubboBootstrap.destroy(DubboBootstrap.java:1280)
2021-09-04T18:15:20.6241433Z 	at org.apache.dubbo.config.bootstrap.DubboBootstrap.reset(DubboBootstrap.java:1435)
2021-09-04T18:15:20.6243204Z 	at org.apache.dubbo.config.bootstrap.DubboBootstrap.reset(DubboBootstrap.java:1423)
2021-09-04T18:15:20.6245035Z 	at org.apache.dubbo.config.ReferenceConfigTest.tearDown(ReferenceConfigTest.java:53)

**Comment by zrlw** [comment]
3.0的 org.apache.dubbo.registry.integration.RegistryProtocol.destroy()方法同样存在ApplicationConfig已释放的问题，github构建日志片段内容摘录如下：
（Unit Test On windows-2019 (JDK: 8)完整日志：https://github.com/zrlw/dubbo/runs/3565948379?check_suite_focus=true ）
```
[10/09/21 10:17:42:258 UTC] main  WARN bootstrap.DubboBootstrap:  [DUBBO] There's no ApplicationConfig specified., dubbo version: 3.0.3-SNAPSHOT, current host: 172.17.224.1
java.lang.IllegalStateException: There's no ApplicationConfig specified.
	at org.apache.dubbo.config.context.ConfigManager.lambda$getApplicationOrElseThrow$0(ConfigManager.java:162)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.apache.dubbo.config.context.ConfigManager.getApplicationOrElseThrow(ConfigManager.java:162)
	at org.apache.dubbo.rpc.model.ApplicationModel.getCurrentConfig(ApplicationModel.java:246)
	at org.apache.dubbo.rpc.model.ApplicationModel.getApplicationName(ApplicationModel.java:250)
	at org.apache.dubbo.registry.integration.RegistryProtocol.destroy(RegistryProtocol.java:605)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.destroy(ProtocolListenerWrapper.java:89)
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.destroy(ProtocolFilterWrapper.java:79)
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.destroy(ProtocolSerializationWrapper.java:57)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.destroyProtocols(DubboBootstrap.java:1716)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.destroy(DubboBootstrap.java:1646)
	at org.apache.dubbo.config.ReferenceConfigTest.testCreateInvokerForRemoteRefer(ReferenceConfigTest.java:540)
```

PS：
考虑到master分支github日志ReferenceConfigTest测试方法在RegistryProtocol的doOverrideIfNecessary()里获取currentUrl时出现NPE：
```
    URL currentUrl = exporter.getInvoker().getUrl();
```
3.0分支的此处获取currentUrl的代码也可能存在出现NPE风险。
