### ISSUE TITLE
[3.0] 单元测试AfterEach执行DubboBootstrap.reset时与dubbo后台线程存在冲突，可能是后续单元测试运行失败的诱因

### ISSUE THREAD

**Issue by zrlw** [apache/dubbo#8725]
### Environment

* Dubbo version: 3.0
很多测试方法结束后执行DubboBootstrap.reset操作，但是：
1. all registries will be destroyed by DubboBootstrap.reset(), 
2. if running these test case concurrently, DubboBootstrap.start() and DubboBootstrap.reset() might be called at the same time,  a RuntimeException might be thrown out of MetadataServiceNameMapping.map() because of registerServiceAppMapping method failure.
（更正：下面日志中的问题不是因为单元测试并行执行，dubbo目前是once forkMode串行构建的，日志显示的问题是执行DubboBootstrap.reset关闭zk的时候，DubboSaveMetadataReport线程还在运行，但是执行storeMetadata操作异常，紧接着下一个测试方法启动DubboBootstrap时注册zk操作也出现异常）
比如DubboBootstrapMultiInstanceTest：
```
2021-09-06T23:17:04.3783873Z [06/09/21 23:17:04:369 UTC] main  INFO support.AbstractRegistryFactory:  [DUBBO] Close all registries [org.apache.dubbo.registry.client.ServiceDiscoveryRegistry@6faf0232, zookeeper://127.0.0.1:34385/org.apache.dubbo.registry.RegistryService?application=consumer-app&dubbo=2.0.2&environment=product&file.cache=false&interface=org.apache.dubbo.registry.RegistryService&pid=9244&release=3.0.3-SNAPSHOT], dubbo version: 3.0.3-SNAPSHOT, current host: 10.1.0.234
2021-09-06T23:17:04.3788871Z [06/09/21 23:17:04:369 UTC] main  INFO zookeeper.ZookeeperRegistry:  [DUBBO] Destroy registry:zookeeper://127.0.0.1:34385/org.apache.dubbo.registry.RegistryService?application=consumer-app&dubbo=2.0.2&environment=product&file.cache=false&interface=org.apache.dubbo.registry.RegistryService&pid=9244&release=3.0.3-SNAPSHOT, dubbo version: 3.0.3-SNAPSHOT, current host: 10.1.0.234
2021-09-06T23:17:04.3798680Z [06/09/21 23:17:04:372 UTC] DubboSaveMetadataReport-thread-1 ERROR zookeeper.ZookeeperMetadataReport:  [DUBBO] Failed to put consumer metadata org.apache.dubbo.metadata.report.identifier.MetadataIdentifier@27cfcb4f;  org.apache.dubbo.common.url.component.URLParam$URLParamMap@c7a36a43, cause: Expected state [STARTED] was [STOPPED], dubbo version: 3.0.3-SNAPSHOT, current host: 10.1.0.234
2021-09-06T23:17:04.3801771Z java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED]
2021-09-06T23:17:04.3803955Z 	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.deletePath(CuratorZookeeperClient.java:193)
2021-09-06T23:17:04.3806956Z 	at org.apache.dubbo.remoting.zookeeper.AbstractZookeeperClient.delete(AbstractZookeeperClient.java:66)
2021-09-06T23:17:04.3809616Z 	at org.apache.dubbo.remoting.zookeeper.AbstractZookeeperClient.create(AbstractZookeeperClient.java:170)
2021-09-06T23:17:04.3814840Z 	at org.apache.dubbo.metadata.store.zookeeper.ZookeeperMetadataReport.storeMetadata(ZookeeperMetadataReport.java:134)
2021-09-06T23:17:04.3818645Z 	at org.apache.dubbo.metadata.store.zookeeper.ZookeeperMetadataReport.doStoreConsumerMetadata(ZookeeperMetadataReport.java:96)
2021-09-06T23:17:04.3822638Z 	at org.apache.dubbo.metadata.report.support.AbstractMetadataReport.storeConsumerMetadataTask(AbstractMetadataReport.java:289)
2021-09-06T23:17:04.3826257Z 	at org.apache.dubbo.metadata.report.support.AbstractMetadataReport.lambda$storeConsumerMetadata$1(AbstractMetadataReport.java:275)
2021-09-06T23:17:04.3831984Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-09-06T23:17:04.3833764Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-09-06T23:17:04.3835097Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-09-06T23:17:04.3836142Z Caused by: java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED]
2021-09-06T23:17:04.3838157Z 	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:721)
2021-09-06T23:17:04.3840779Z 	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkState(CuratorFrameworkImpl.java:426)
2021-09-06T23:17:04.3843184Z 	at org.apache.curator.framework.imps.CuratorFrameworkImpl.delete(CuratorFrameworkImpl.java:446)
2021-09-06T23:17:04.3846081Z 	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.deletePath(CuratorZookeeperClient.java:190)
... ... ...
2021-09-06T23:17:04.6300294Z [06/09/21 23:17:04:530 UTC] main ERROR config.ServiceConfig:  [DUBBO] Failed register interface application mapping for service org.apache.dubbo.config.api.DemoService:2.0, dubbo version: 3.0.3-SNAPSHOT, current host: 10.1.0.234
2021-09-06T23:17:04.6301602Z java.lang.RuntimeException
2021-09-06T23:17:04.6303393Z 	at org.apache.dubbo.registry.client.metadata.MetadataServiceNameMapping.map(MetadataServiceNameMapping.java:88)
2021-09-06T23:17:04.6306097Z 	at org.apache.dubbo.config.ServiceConfig.lambda$exported$1(ServiceConfig.java:270)
2021-09-06T23:17:04.6307317Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2021-09-06T23:17:04.6308654Z 	at org.apache.dubbo.config.ServiceConfig.exported(ServiceConfig.java:266)
2021-09-06T23:17:04.6310056Z 	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:371)
2021-09-06T23:17:04.6311444Z 	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:244)
2021-09-06T23:17:04.6318288Z 	at org.apache.dubbo.config.bootstrap.DubboBootstrap.exportServices(DubboBootstrap.java:1476)
2021-09-06T23:17:04.6320287Z 	at org.apache.dubbo.config.bootstrap.DubboBootstrap.doStart(DubboBootstrap.java:1190)
2021-09-06T23:17:04.6322235Z 	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:1166)
2021-09-06T23:17:04.6325718Z 	at org.apache.dubbo.config.bootstrap.DubboBootstrapMultiInstanceTest.testMultiModuleApplication(DubboBootstrapMultiInstanceTest.java:200)
```

**Comment by zrlw** [comment]
看了一下代码，如果采用测试类加@net.jcip.annotations.NotThreadSafe注解单线程执行，几乎大部分测试类都需要加，不可行。
把AbstractRegistryFactory加个引用计数吧，就像ReferenceCountExchangeClient那样，计数降到0之后再做destroy，如何？

**Comment by zrlw** [comment]
提个建议哈，要么干脆把parent的pom里面forkMode从once改成always算了，然后把UT的timeout调得大大大大。。。。的

**Comment by zrlw** [comment]
我对forkMode的理解有错误，
forkMode=once 对应的是 forkCount=1 && reuseForks=true 创建一个新进程用于每个测试（复用）
forkMode=always 对应的是 forkCount=1 && reuseForks=false 为每一个测试创建一个新进程
从日志内容看，once forkMode方式下AfterEach的reset关闭zk连接的动作竟然在和下一个测试方法并行执行
