### ISSUE TITLE
Invalid character found in method name org.apache.dubbo.metadata.MetadataService

### ISSUE THREAD

**Issue by frlzk** [apache/dubbo#8754]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.2.1
* Operating System version: ubuntu20
* Java version: 1.8

### Steps to reproduce this issue

1. Start provider application.
2. Can see provider information on nacos service list.
3. Start consumer application.

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

No exception throw.

### Actual Result

A IllegalArgumentException thrown.

If there is an exception, please attach the exception trace:

```
2021-09-09 17:24:44.761  INFO 4886 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-09-09 17:24:44.762  INFO 4886 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 896 ms
2021-09-09 17:24:44.824  INFO 4886 --- [           main] o.a.d.c.s.c.DubboConfigBeanInitializer   : loading dubbo config beans ...
2021-09-09 17:24:44.826  INFO 4886 --- [           main] o.a.d.c.s.c.DubboConfigBeanInitializer   : dubbo config beans are loaded.
2021-09-09 17:24:45.222  INFO 4886 --- [           main] o.a.d.c.s.reference.ReferenceCreator     : The configBean[type:ReferenceConfig] has been built.
2021-09-09 17:24:45.409  INFO 4886 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-09-09 17:24:45.617  INFO 4886 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService 'Nacos-Watch-Task-Scheduler'
2021-09-09 17:24:45.796  WARN 4886 --- [           main] iguration$LoadBalancerCaffeineWarnLogger : Spring Cloud LoadBalancer is currently working with the default cache. You can switch to using Caffeine cache, by adding it and org.springframework.cache.caffeine.CaffeineCacheManager to the classpath.
2021-09-09 17:24:46.003  INFO 4886 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 9002 (http) with context path ''
2021-09-09 17:24:46.013  INFO 4886 --- [           main] c.a.c.n.registry.NacosServiceRegistry    : nacos registry, DEFAULT_GROUP consumer 10.2.78.155:9002 register finished
2021-09-09 17:24:47.948  INFO 4886 --- [nio-9002-exec-1] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character found in method name [0xda0xbb0xc20x000x000x000x000x000x000x000x000x000x000x000x000xc20x052.0.20)org.apache.dubbo.metadata.MetadataService0x051.0.00x0fgetMetadataInfo0x12Ljava/lang/String;NM0x17java.util.LinkedHashMap0x05group0x08consumer0x04path0)org.apache.dubbo.metadata.MetadataService0x07version0x051.0.0...]. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:417) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:261) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) [tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.45.jar:9.0.45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_172]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.45.jar:9.0.45]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_172]

2021-09-09 17:24:54.240  INFO 4886 --- [           main] o.example.consumer.ConsumerApplication   : Started ConsumerApplication in 12.095 seconds (JVM running for 12.548)
```

**Comment by EarthChen** [comment]
Can you provide a demo of reproduction？

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
