### ISSUE TITLE
Upgrade Dubbo to 2.7.13 with error

### ISSUE THREAD

**Issue by ljwps** [apache/dubbo#8764]
- [ x ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ x ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.13
* Operating System version: win10
* Java version: 1.8
* nacos：2.0.0

### Steps to reproduce this issue

Upgrade 
Dubbo 2.7.10 -> 2.7.13
dubbo-registry-nacos 2.7.10 -> 2.7.13
dubbo-spring-boot-starter 2.7.10 -> 2.7.13
nacos-client 1.33 -> 1.4.2
spring-context-support   -> 1.0.11

**After the upgrade, there is an error in the startup program. There is no error before the upgrade**

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

no error

### Actual Result

There is an error in the startup program after the upgrade is completed

If there is an exception, please attach the exception trace:

```
2021-09-10 15:33:55.238 [yourproject-server-1.0.0] [8e05ea8b36274a6688513c873705f01c] ERROR ServiceInstancesChangedListener:187 -  [DUBBO] Failed to load service metadata, metadata type is local, dubbo version: 2.7.13, current host: 192.168.83.115 
java.lang.IllegalStateException: You have enabled introspection service discovery mode for instance DefaultServiceInstance{id='192.168.83.115#8089#DEFAULT#DEFAULT_GROUP@@common-file-server', serviceName='common-file-server', host='192.168.83.115', port=8089, enabled=true, healthy=true, metadata={spring.application.group.key=group, spring.application.name=common-file-server, spring.application.register.control.enabled=true, spring.boot.version=2.2.10.RELEASE, spring.application.discovery.version=6.0.1, spring.application.discovery.plugin=Nacos, version=3.3.0, spring.application.config.rest.control.enabled=true, spring.application.context-path=/common-file-server, spring.application.type=service, spring.application.discovery.control.enabled=true, region=xxx, preserved.register.source=SPRING_CLOUD, group=GRAY-GROUP}}, but no metadata service can build from it.
	at org.apache.dubbo.registry.client.metadata.MetadataUtils.lambda$getMetadataServiceProxy$0(MetadataUtils.java:90)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.apache.dubbo.registry.client.metadata.MetadataUtils.getMetadataServiceProxy(MetadataUtils.java:74)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.getMetadataInfo(ServiceInstancesChangedListener.java:180)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.onEvent(ServiceInstancesChangedListener.java:116)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.lambda$subscribeURLs$3(ServiceDiscoveryRegistry.java:337)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribeURLs(ServiceDiscoveryRegistry.java:334)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.doSubscribe(ServiceDiscoveryRegistry.java:269)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribe(ServiceDiscoveryRegistry.java:256)
	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:105)
	at org.apache.dubbo.registry.integration.DynamicDirectory.subscribe(DynamicDirectory.java:154)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doCreateInvoker(RegistryProtocol.java:525)
	at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getServiceDiscoveryInvoker(InterfaceCompatibleRegistryProtocol.java:77)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshServiceDiscoveryInvoker(MigrationInvoker.java:295)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToServiceDiscoveryInvoker(MigrationInvoker.java:112)
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:58)
	at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:103)
	at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:498)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:483)
	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:477)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:72)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:73)
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:378)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:313)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:206)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.doGetInjectedBean(ReferenceAnnotationBeanPostProcessor.java:165)
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.getInjectedObject(AbstractAnnotationBeanPostProcessor.java:409)
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor$AnnotatedFieldElement.inject(AbstractAnnotationBeanPostProcessor.java:626)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.postProcessPropertyValues(AbstractAnnotationBeanPostProcessor.java:179)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1425)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
```

**Comment by AlbumenJ** [comment]
2.7.x 版本不建议开启应用级服务发现，开启需要同时保证元数据中心工作正常

**Comment by ljwps** [comment]
> 2.7.x 版本不建议开启应用级服务发现，开启需要同时保证元数据中心工作正常

多谢回复，我还有3个问题。
1、用2.7.10的时候是好的没遇到应用级服务发现、也没有弄过元数据中心。难道是2.7.13默认开启了你说的“应用级服务发现”么，2.7.10的时候是默认关闭的么？
2、如何关闭应用级服务发现，关闭了之后有什么影响（与2.7.10的时候对比有什么影响）。
3、如果不关闭应用级服务发现，元数据中心是怎么搭建的？

**Comment by AlbumenJ** [comment]
https://github.com/apache/dubbo/pull/8836

**Comment by ljwps** [comment]
> #8836

请问下，这个问题哪个版本修复阿

**Comment by AlbumenJ** [comment]
> #8836

2.7.15
