### ISSUE TITLE
调试 grpoc 代码生成器的时候 总是抛错  org.apache.dubbo.gen.dubbo.DubboGenerator 输入参数是啥 proto的文件吗 

### ISSUE THREAD

**Issue by vio-lin** [apache/dubbo#8875]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

调试 grpoc 代码生成器的时候 总是抛错  org.apache.dubbo.gen.dubbo.DubboGenerator 输入参数是啥 proto的文件吗

**Comment by yangzan0816** [comment]
能附带一下错误信息的截图么

**Comment by vio-lin** [comment]
倒是没有报错。 
org.apache.dubbo.gen.grpc.DubboGrpcGenerator dubbo的的代码里面生成grpc  代码的 maven插件代码  
```
public class DubboGrpcGenerator extends AbstractGenerator {

    public static void main(String[] args) {
        if (false) {
            ProtocPlugin.generate(new DubboGrpcGenerator());
        } else {
            ProtocPlugin.debug(new DubboGrpcGenerator(),"D:\\Users\\guo.lin\\git\\cdubbo\\cdubbo-demo3\\src\\main\\proto\\Greeter.proto");
        }
    }
}
```
我传递proto 文件进去 然后有如下报错
```
com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
	at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:115)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:551)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:514)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:633)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:295)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readGroup(CodedInputStream.java:856)
```
所以第二个参数需要传递什么进去才可以做到调试呢。

**Comment by vio-lin** [comment]
我改了代码 把对象获取到写在了本地文件。看样子是protobufc 输出 protobuf格式的生成请求的对象到本地。   
不管如何可以进行调试了。
