### ISSUE TITLE
k8s环境不断重连已经关闭的pod

### ISSUE THREAD

**Issue by NoRedsquare** [apache/dubbo#8932]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.2
* Operating System version: Kubernetes
* Java version: 1.8

### Steps to reproduce this issue

1.nacos是2.0.3， 并且服务提供者已经下线。
2.本地启动与jar启动没有出现此场景。
3.k8s环境服务重启以后出现一直重连旧的服务。

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

请问怎么处理这种情况。

### Actual Result

If there is an exception, please attach the exception trace:

```
2021-09-24 19:15:38[ dubbo-client-idleCheck-thread-1:3829053 ]-[ INFO ]  [DUBBO] Initial connection to HeaderExchangeClient [channel=org.apache.dubbo.remoting.transport.netty4.NettyClient [/10.3.4.13:56218 -> /10.3.4.7:20880]], dubbo version: 3.0.2.1, current host: 10.3.4.13
2021-09-24 19:15:38[ dubbo-client-idleCheck-thread-1:3829053 ]-[ INFO ]  [DUBBO] Close netty channel [id: 0x7f5c5841, L:/10.3.4.13:56218 ! R:/10.3.4.7:20880], dubbo version: 3.0.2.1, current host: 10.3.4.13
2021-09-24 19:15:41[ dubbo-client-idleCheck-thread-1:3832054 ]-[ ERROR ]  [DUBBO] Fail to connect to HeaderExchangeClient [channel=org.apache.dubbo.remoting.transport.netty4.NettyClient [/10.3.4.13:56218 -> /10.3.4.7:20880]], dubbo version: 3.0.2.1, current host: 10.3.4.13
org.apache.dubbo.remoting.RemotingException: client(url: dubbo://10.3.4.7:20880/com.duizhuang.opc.user.service.DynamicEsSearchService?anyhost=true&application=dz-opc-user&category=providers&codec=dubbo&delay=-1&deprecated=false&dispatcher=message&dubbo=2.0.2&dynamic=true&generic=false&heartbeat=60000&interface=com.duizhuang.opc.user.service.DynamicEsSearchService&logger=log4j2&metadata-type=remote&methods=getNewTopDynamics,getKnowledgeDynamics,getUserDynamic,getTopDynamicArticles,getHotOrLatestDynamics,getRecommendDynamics,getTodayMaxScoreDynamic,getLiveNewDynamic,getLiveDynamic,getNewRecommendDynamics,getUserDynamicLikes,getTopRecommendDynamics,getAppraisalDynamic,getTopDynamics,getUserFollowDynamic,getDynamicByUserTopic,getDynamicByTypeAndLabel,getDynamicNews,getAppraisalIndexDynamic,getDynamicByTopic,getUserVideoDynamics&path=com.duizhuang.opc.user.service.DynamicEsSearchService&pid=7&protocol=dubbo&release=3.0.2.1&service-name-mapping=true&side=provider&threadpool=cached&threads=200&timeout=30000&timestamp=1632477139767) failed to connect to server /10.3.4.7:20880 client-side timeout 3000ms (elapsed: 3001ms) from netty client 10.3.4.13 using dubbo version 3.0.2.1
	at org.apache.dubbo.remoting.transport.netty4.NettyClient.doConnect(NettyClient.java:176)
	at org.apache.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:197)
	at org.apache.dubbo.remoting.transport.AbstractClient.reconnect(AbstractClient.java:253)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeClient.reconnect(HeaderExchangeClient.java:166)
	at org.apache.dubbo.remoting.exchange.support.header.ReconnectTimerTask.doTask(ReconnectTimerTask.java:49)
	at org.apache.dubbo.remoting.exchange.support.header.AbstractTimerTask.run(AbstractTimerTask.java:87)
	at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:648)
	at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:727)
	at org.apache.dubbo.common.timer.HashedWheelTimer$Worker.run(HashedWheelTimer.java:449)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by AlbumenJ** [comment]
检查下 dubbo-registry-nacos 是不是和主版本一致的

**Comment by boog14** [comment]
3.0.3不行的，还是Fail to connect to HeaderExchangeClient

**Comment by hxz393** [comment]
配置
dubbo.metadata-report.address = ${dubbo.registry.address}
dubbo.application.metadata-type = remote
