### ISSUE TITLE
Failed to invoke the method collect in the service org.apache.dubbo.monitor.MonitorService. address cache not build  on the consumer 

### ISSUE THREAD

**Issue by gang0713** [apache/dubbo#8953]
dubbo版本3.0.3会报这个错，有知道原因的不。

ERROR [DynamicDirectory:187] 2021-09-29 14:46:11,219 -  [DUBBO] Failed to execute router: nacos://127.0.0.1:8848/org.apache.dubbo.monitor.MonitorService?application=spring-boot-consumer-user&check=false&dubbo=2.0.2&file=/root/dubbo-cache/spring-boot-consumer-user/pro/dubbo.cache&group=pro&interface=org.apache.dubbo.monitor.MonitorService&pid=22123&protocol=registry&qos.accept.foreign.ip=false&qos.enable=false&reference.filter=-monitor&release=3.0.3&timestamp=1632897890364, cause: Failed to invoke the method collect in the service org.apache.dubbo.monitor.MonitorService. address cache not build  on the consumer 172.16.0.13 using the dubbo version 3.0.3., dubbo version: 3.0.3, current host: 172.16.0.13
**org.apache.dubbo.rpc.RpcException: Failed to invoke the method collect in the service org.apache.dubbo.monitor.MonitorService. address cache not build  o**n the consumer 172.16.0.13 using the dubbo version 3.0.3.
	at org.apache.dubbo.rpc.cluster.RouterChain.route(RouterChain.java:176)
	at org.apache.dubbo.registry.integration.DynamicDirectory.doList(DynamicDirectory.java:185)
	at org.apache.dubbo.rpc.cluster.directory.AbstractDirectory.list(AbstractDirectory.java:117)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.list(AbstractClusterInvoker.java:327)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:265)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:89)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:84)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:51)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:84)
	at org.apache.dubbo.rpc.cluster.filter.support.ConsumerContextFilter.invoke(ConsumerContextFilter.java:108)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:84)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$ClusterFilterInvoker.invoke(AbstractCluster.java:92)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:94)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.invoke(MigrationInvoker.java:276)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:92)
	at org.apache.dubbo.common.bytecode.proxy54.collect(proxy54.java)
	at org.apache.dubbo.monitor.dubbo.DubboMonitor.send(DubboMonitor.java:122)
	at org.apache.dubbo.monitor.dubbo.DubboMonitor.lambda$new$0(DubboMonitor.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
ERROR [DubboMonitor:79] 2021-09-29 14:46:11,221 -  [DUBBO] Unexpected error occur at send statistic, cause: Failed to invoke the method collect in the service org.apache.dubbo.monitor.MonitorService. No provider available for the service org.apache.dubbo.monitor.MonitorService from registry 127.0.0.1:8848 on the consumer 172.16.0.13 using the dubbo version 3.0.3. Please check if the providers have been started and registered., dubbo version: 3.0.3, current host: 172.16.0.13
org.apache.dubbo.rpc.RpcException: Failed to invoke the method collect in the service org.apache.dubbo.monitor.MonitorService. No provider available for the service org.apache.dubbo.monitor.MonitorService from registry 127.0.0.1:8848 on the consumer 172.16.0.13 using the dubbo version 3.0.3. Please check if the providers have been started and registered.
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.checkInvokers(AbstractClusterInvoker.java:291)
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:59)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:268)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:89)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:84)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:51)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:84)
	at org.apache.dubbo.rpc.cluster.filter.support.ConsumerContextFilter.invoke(ConsumerContextFilter.java:108)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$FilterChainNode.invoke(FilterChainBuilder.java:84)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$ClusterFilterInvoker.invoke(AbstractCluster.java:92)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:94)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.invoke(MigrationInvoker.java:276)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:92)
	at org.apache.dubbo.common.bytecode.proxy54.collect(proxy54.java)
	at org.apache.dubbo.monitor.dubbo.DubboMonitor.send(DubboMonitor.java:122)
	at org.apache.dubbo.monitor.dubbo.DubboMonitor.lambda$new$0(DubboMonitor.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by candyaaa** [comment]
能否更加详细的描述你的问题，比如是什么情况下出现该异常。

**Comment by gang0713** [comment]
目前不太清楚，看到日志有报这个错，但是又好象不影响使用。

**Comment by candyaaa** [comment]
能否提供一个报错的demo

**Comment by gang0713** [comment]
> 我也遇到过这个问题，后来发现是nacos版本不统一，同步版本号后问题解决了。

版本一致也是这样。
下面开的端口应该没有问题吧。
docker run --name nacos8849  -d -p 8849:8848 -p 9848:9848 -p 9849:9849 --privileged=true --restart=always -e JVM_XMS=256m -e JVM_XMX=256m -e JVM_XMN=512m -e MODE=standalone -v  /opt/conf/nacos8849/logs:/home/nacos/logs -v  /opt/conf/nacos2.0.0/custom.properties:/home/nacos/init.d/custom.properties nacos/nacos-server:2.0.3
