### ISSUE TITLE
注册管理getRegistries获取的Registry没有去重；以及application共享zookeeper client导致destroy抛异常

### ISSUE THREAD

**Issue by zrlw** [apache/dubbo#9014]
### Environment

* Dubbo version: 3.0 / master
3.0的RegistryManager以及master的AbstractRegistryFactory的getRegistries获取的Registry可能会有重复，后果就是重复注册、解注册、destroy时会抛异常，比如这样：
```
[11/10/21 09:42:05:873 CST] main ERROR zookeeper.ZookeeperRegistry:  [DUBBO] Failed to unregister dubbo://192.168.1.23/org.apache.dubbo.config.api.DemoService?application=consumer-app&background=false&category=consumers&check=false&dubbo=2.0.2&environment=product&file.cache=false&injvm=false&interface=org.apache.dubbo.config.api.DemoService&metadata-type=remote&methods=callInnerClass,sayName,getUsers,echo,getBox,throwDemoException&pid=10228&release=&revision=2.0&side=consumer&sticky=false&timestamp=1633916525391&version=2.0, waiting for retry, cause: Failed to unregister dubbo://192.168.1.23/org.apache.dubbo.config.api.DemoService?application=consumer-app&background=false&category=consumers&check=false&dubbo=2.0.2&environment=product&file.cache=false&injvm=false&interface=org.apache.dubbo.config.api.DemoService&metadata-type=remote&methods=callInnerClass,sayName,getUsers,echo,getBox,throwDemoException&pid=10228&release=&revision=2.0&side=consumer&sticky=false&timestamp=1633916525391&version=2.0 to zookeeper zookeeper://127.0.0.1:36010/org.apache.dubbo.registry.RegistryService?application=consumer-app&dubbo=2.0.2&environment=product&file.cache=false&interface=org.apache.dubbo.registry.RegistryService&pid=10228, cause: Expected state [STARTED] was [STOPPED], dubbo version: , current host: 192.168.1.23
org.apache.dubbo.rpc.RpcException: Failed to unregister dubbo://192.168.1.23/org.apache.dubbo.config.api.DemoService?application=consumer-app&background=false&category=consumers&check=false&dubbo=2.0.2&environment=product&file.cache=false&injvm=false&interface=org.apache.dubbo.config.api.DemoService&metadata-type=remote&methods=callInnerClass,sayName,getUsers,echo,getBox,throwDemoException&pid=10228&release=&revision=2.0&side=consumer&sticky=false&timestamp=1633916525391&version=2.0 to zookeeper zookeeper://127.0.0.1:36010/org.apache.dubbo.registry.RegistryService?application=consumer-app&dubbo=2.0.2&environment=product&file.cache=false&interface=org.apache.dubbo.registry.RegistryService&pid=10228, cause: Expected state [STARTED] was [STOPPED]
	at org.apache.dubbo.registry.zookeeper.ZookeeperRegistry.doUnregister(ZookeeperRegistry.java:136)
	at org.apache.dubbo.registry.support.FailbackRegistry.unregister(FailbackRegistry.java:254)
	at org.apache.dubbo.registry.support.AbstractRegistry.destroy(AbstractRegistry.java:488)
	at org.apache.dubbo.registry.support.FailbackRegistry.destroy(FailbackRegistry.java:408)
	at org.apache.dubbo.registry.zookeeper.ZookeeperRegistry.destroy(ZookeeperRegistry.java:114)
	at org.apache.dubbo.registry.support.RegistryManager.destroyAll(RegistryManager.java:105)
```

**Comment by zrlw** [comment]
问题没有那么简单，同一个URL创建多个Registry实例的情况怎么办，比如其中一个是ZookeeperRegistry，另一个是ServiceDiscoveryRegistry，用的同一个zk URL，这样重复操作zk也抛异常。
