### ISSUE TITLE
[3.0] TripleClientRequestHandler的writeRequest获取compressor的代码可能有问题

### ISSUE THREAD

**Issue by zrlw** [apache/dubbo#9022]
### Environment

* Dubbo version: 3.0
TriWrapConsumerTest、TriGenericTest、TriPbConsumerTest、ApiConsumerIT等集成测试都会出NPE：
https://github.com/apache/dubbo/runs/3858761933?check_suite_focus=true
```
Failed to invoke the method xxx in the service xxx.xxx. Tried 3 times of the providers xxx from the registry xxx on the consumer xxx using the dubbo version 3.0.4-SNAPSHOT. Last error is: Failed to invoke remote method: xxx, provider: xxx, dubbo.metadata-service.url-params=xxx, service{xxx}, cause: org.apache.dubbo.remoting.RemotingException: java.lang.NullPointerException
java.lang.NullPointerException
	at org.apache.dubbo.registry.client.InstanceAddressURL.getScopeModel(InstanceAddressURL.java:498)
	at org.apache.dubbo.rpc.protocol.tri.TripleClientRequestHandler.writeRequest(TripleClientRequestHandler.java:82)
	at org.apache.dubbo.rpc.protocol.tri.TripleClientRequestHandler.write(TripleClientRequestHandler.java:58)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
看起来是尚未完成注册时不能调用InstanceAddressURL.getScopeModel这个方法。
@XIACYBING

**Comment by EarthChen** [comment]
https://github.com/apache/dubbo/pull/9024
