### ISSUE TITLE
3.0.3 expected single matching bean but found N candidates for type 

### ISSUE THREAD

**Issue by NoRedsquare** [apache/dubbo#9042]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.3
* Operating System version: Kubernetes
* Java version: 1.8

### Steps to reproduce this issue

1.线上时不时会出现这种情况

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

请问怎么处理这种情况。

### Actual Behavior

If there is an exception, please attach the exception trace:

```
org.apache.dubbo.common.beans.ScopeBeanException: expected single matching bean but found 5 candidates for type [org.apache.dubbo.registry.integration.RegistryDirectory$ConsumerConfigurationListener]: [org.apache.dubbo.registry.integration.RegistryDirectory$ConsumerConfigurationListener#1, org.apache.dubbo.registry.integration.RegistryDirectory$ConsumerConfigurationListener#2, org.apache.dubbo.registry.integration.RegistryDirectory$ConsumerConfigurationListener#3, org.apache.dubbo.registry.integration.RegistryDirectory$ConsumerConfigurationListener#4, org.apache.dubbo.registry.integration.RegistryDirectory$ConsumerConfigurationListener#5]
	at org.apache.dubbo.common.beans.factory.ScopeBeanFactory.getBeanInternal(ScopeBeanFactory.java:211) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.common.beans.factory.ScopeBeanFactory.getBean(ScopeBeanFactory.java:171) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.common.beans.factory.ScopeBeanFactory.getOrRegisterBean(ScopeBeanFactory.java:125) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.common.beans.factory.ScopeBeanFactory.getOrRegisterBean(ScopeBeanFactory.java:121) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.registry.integration.RegistryDirectory.getConsumerConfigurationListener(RegistryDirectory.java:121) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.registry.integration.RegistryDirectory.<init>(RegistryDirectory.java:109) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getInvoker(InterfaceCompatibleRegistryProtocol.java:57) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshInterfaceInvoker(MigrationInvoker.java:448) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToApplicationFirstInvoker(MigrationInvoker.java:239) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.refreshInvoker(MigrationRuleHandler.java:72) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:56) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:233) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:526) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:495) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:480) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:74) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:83) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:71) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:52) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.config.ReferenceConfig.createInvokerForRemote(ReferenceConfig.java:469) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:380) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:267) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:204) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.config.spring.ReferenceBean.getCallProxy(ReferenceBean.java:348) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.config.spring.ReferenceBean.access$100(ReferenceBean.java:98) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.apache.dubbo.config.spring.ReferenceBean$DubboReferenceLazyInitTargetSource.createObject(ReferenceBean.java:355) ~[dubbo-3.0.3.jar!/:3.0.3]
	at org.springframework.aop.target.AbstractLazyCreationTargetSource.getTarget(AbstractLazyCreationTargetSource.java:88) ~[spring-aop-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:192) ~[spring-aop-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
	at com.sun.proxy.$Proxy160.getLiveLastRecordByRoomCode(Unknown Source) ~[na:na]=
	at sun.reflect.GeneratedMethodAccessor329.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
```

**Comment by NoRedsquare** [comment]
getConsumerConfigurationListener  加上synchronized  关键字暂时解决。
