### ISSUE TITLE
Failed to notify addresses for subscribe 抛出 NEP

### ISSUE THREAD

**Issue by NoRedsquare** [apache/dubbo#9044]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.3
* Operating System version: k8s
* Java version: 1.8

### Steps to reproduce this issue

1. 某个服务一直起不来
2. 重启无效

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
2021-10-16 11:42:04.448 ERROR 1 --- [           main] o.a.dubbo.registry.nacos.NacosRegistry   :  [DUBBO] Failed to notify addresses for subscribe dubbo://10.1.4.225/com.xxx.opc.product.service.ProductPriceService?application=sell

er-api-web&category=providers,configurators,routers&check=false&dubbo=2.0.2&interface=com.xxx.opc.product.service.ProductPriceService&loadbalance=leastactive&logger=log4j2&metadata-type=remote&methods=buildPriceTip,buildPrice&pid=

1&qos.enable=false&reference.filter=traceFilter&release=3.0.3&side=consumer&sticky=false&timestamp=1634355724370, cause: null, dubbo version: 3.0.3, current host: 10.1.4.225


java.lang.NullPointerException: null

at org.apache.dubbo.common.extension.ExtensionLoader.getExtensionLoader(ExtensionLoader.java:198) ~[dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.rpc.cluster.router.mesh.route.MeshRuleManager.subscribeAppRule(MeshRuleManager.java:48) ~[dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.rpc.cluster.router.mesh.route.MeshRuleAddressListenerInterceptor.notify(MeshRuleAddressListenerInterceptor.java:45) ~[dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.registry.integration.RegistryDirectory.notify(RegistryDirectory.java:159) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.registry.support.AbstractRegistry.notify(AbstractRegistry.java:435) ~[dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.registry.support.FailbackRegistry.doNotify(FailbackRegistry.java:371) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.registry.support.FailbackRegistry.notify(FailbackRegistry.java:363) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.registry.nacos.NacosRegistry.notifySubscriber(NacosRegistry.java:540) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.registry.nacos.NacosRegistry.doSubscribe(NacosRegistry.java:226) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.registry.nacos.NacosRegistry.doSubscribe(NacosRegistry.java:203) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:298) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:109) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.registry.integration.RegistryDirectory.subscribe(RegistryDirectory.java:117) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.registry.integration.RegistryProtocol.doCreateInvoker(RegistryProtocol.jav a:557) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getInvoker(InterfaceCompatibleRegistryProtocol.java:58) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshInterfaceInvoker(MigrationInvoker.java:448) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToApplicationFirstInvoker(MigrationInvoker.java:239) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.refreshInvoker(MigrationRuleHandler.java:72) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:56) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:233) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:526) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:495) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:480) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:74) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:83) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:71) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:52) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.config.ReferenceConfig.createInvokerForRemote(ReferenceConfig.java:469) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:380) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:267) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:204) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.config.utils.SimpleReferenceCache.get(SimpleReferenceCache.java:117) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$5(DefaultModuleDeployer.java:304) [dubbo-3.0.3.jar!/:3.0.3]

at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) ~[na:1.8.0_212]

at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:283) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:130) [dubbo-3.0.3.jar!/:3.0.3]

at org.apache.dubbo.config.spring.context.DubboDeployApplica
```

**Comment by CrazyHZM** [comment]
@NoRedsquare  Try it with 3.0.4.

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
