### ISSUE TITLE
dubbo3.x消费端配置FORCE_APPLICATION启动异常

### ISSUE THREAD

**Issue by xiaokunliu** [apache/dubbo#9067]
dubbo3.x的消费端服务使用配置dubbo.application.service-discovery.migration=FORCE_APPLICATION时出现以下异常:

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-10-19 12:10:17.475`[main]`ERROR`o.s.boot.SpringApplication`Application run failed
java.lang.IllegalStateException: Failed to check the status of the service nono.rec.protoc.DubboHelloServiceGrpc$IHelloService. No provider available for the service nono.rec.protoc.DubboHelloServiceGrpc$IHelloService from the url grpc://192.168.16.176/nono.rec.protoc.DubboHelloServiceGrpc$IHelloService?application=dubbo-consumer-service&dubbo=2.0.2&injvm=false&interface=nono.rec.protoc.DubboHelloServiceGrpc$IHelloService&metadata-type=remote&methods=pingpongAsync,pingpong&pid=9038&protocol=grpc&qos.enable=false&register.ip=192.168.16.176&release=3.0.0&side=consumer&sticky=false&timestamp=1634616617288 to the consumer 192.168.16.176 use dubbo version 3.0.0
	at org.apache.dubbo.config.ReferenceConfig.checkInvokerAvailable(ReferenceConfig.java:463)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:338)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:205)
	at org.apache.dubbo.config.utils.ReferenceConfigCache.lambda$get$3(ReferenceConfigCache.java:114)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.apache.dubbo.config.utils.ReferenceConfigCache.get(ReferenceConfigCache.java:113)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.lambda$referServices$8(DubboBootstrap.java:1342)
	at java.util.HashMap$Values.forEach(HashMap.java:981)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.referServices(DubboBootstrap.java:1321)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:1100)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onContextRefreshedEvent(DubboBootstrapApplicationListener.java:70)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onApplicationContextEvent(DubboBootstrapApplicationListener.java:63)
	at com.alibaba.spring.context.OnceApplicationContextEventListener.onApplicationEvent(OnceApplicationContextEventListener.java:52)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:898)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at gup.dubbo.consumers.DubboConsumerBootstrap.main(DubboConsumerBootstrap.java:17)

**Comment by xiaokunliu** [comment]
使用etcd作为注册中心的方式

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
