### ISSUE TITLE
upgrade 3.0.3 consumer finished happen error

### ISSUE THREAD

**Issue by gcsy0924** [apache/dubbo#9075]
java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
	at java.lang.Runtime.removeShutdownHook(Runtime.java:239)
	at org.apache.dubbo.config.DubboShutdownHook.unregister(DubboShutdownHook.java:89)
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.unRegisterShutdownHook(DefaultApplicationDeployer.java:158)
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.destroy(DefaultApplicationDeployer.java:791)
	at org.apache.dubbo.rpc.model.ApplicationModel.onDestroy(ApplicationModel.java:218)
	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:105)
	at org.apache.dubbo.config.DubboShutdownHook.doDestroy(DubboShutdownHook.java:67)
	at org.apache.dubbo.config.DubboShutdownHook.run(DubboShutdownHook.java:62)

**Comment by syshenyao** [comment]
> 能否更加详细描述？或者提供可以复现的Demo呢？


ok，this is demo code！when you run consumer,you can reproduce it
https://github.com/syshenyao/File/blob/main/DubboDemo.zip
