### ISSUE TITLE
[3.0] 新增的GlobalResourcesRepository全局资源管理功能可能和github构建的并行策略有冲突

### ISSUE THREAD

**Issue by zrlw** [apache/dubbo#9079]
* Dubbo version: 3.0

实测发现GlobalResourcesRepository对github的单元测试和集成测试均有影响。

首先说一下github集成测试时，如下所示，当启动一个测试类时，却开始去执行前面一个测试类的全局资源释放操作，导致正在启动的测试类各种异常：
```
2021-10-20T13:28:53.6306484Z Running org.apache.dubbo.samples.version.VersionServiceStarIT 
<== 开始测试VersionServiceStarIT 
2021-10-20T13:28:53.6317495Z [20/10/21 01:28:12:012 UTC] main  INFO support.DefaultTestContextBootstrapper: Loaded default TestExecutionListener class names from location [META-INF/spring.factories]: 
<== 加载TestExecutionListener （这个新增的TestExecutionListener 也会导致用全局资源的测试类出现问题，另开了issue）
...
2021-10-20T13:28:53.6419566Z [20/10/21 01:28:12:012 UTC] main  INFO deploy.DefaultApplicationDeployer:  [DUBBO] Dubbo application[1.1] is stopping., dubbo version: 3.0.4-SNAPSHOT, current host: 192.168.160.5
<==  application[1.1] 是前面已经完成测试的VersionService1IT创建的，现在才开始销毁了

2021-10-20T13:28:53.6558073Z [20/10/21 01:28:12:012 UTC] main  INFO model.FrameworkModel:  [DUBBO] Dubbo framework[1] is destroying ..., dubbo version: 3.0.4-SNAPSHOT, current host: 192.168.160.5
<== 开始销毁VersionService1IT的framework model

2021-10-20T13:28:53.6559810Z [20/10/21 01:28:12:012 UTC] main  INFO dubbo.DubboProtocol:  [DUBBO] Destroying protocol [DubboProtocol] ..., dubbo version: 3.0.4-SNAPSHOT, current host: 192.168.160.5
2021-10-20T13:28:53.6577037Z [20/10/21 01:28:12:012 UTC] main  INFO model.FrameworkModel:  [DUBBO] Dubbo framework[1] is destroyed, dubbo version: 3.0.4-SNAPSHOT, current host: 192.168.160.5
2021-10-20T13:28:53.6578732Z [20/10/21 01:28:12:012 UTC] main  INFO resource.GlobalResourcesRepository:  [DUBBO] Destroying global resources ..., dubbo version: 3.0.4-SNAPSHOT, current host: 192.168.160.5
2021-10-20T13:28:53.6580622Z [20/10/21 01:28:12:012 UTC] main  INFO resource.GlobalResourcesRepository:  [DUBBO] Dubbo is completely destroyed, dubbo version: 3.0.4-SNAPSHOT, current host: 192.168.160.5
<== 销毁完毕

<== 然后开始测试就直接抛DubboProtocol is destroyed异常
2021-10-20T13:28:53.6694315Z [20/10/21 01:28:13:013 UTC] main ERROR integration.RegistryDirectory:  [DUBBO] Failed to refer invoker for interface:interface org.apache.dubbo.samples.version.api.VersionService,url:(dubbo://192.168.160.3:20880/org.apache.dubbo.samples.version.api.VersionService?anyhost=true&application=version-provider&background=false&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=org.apache.dubbo.samples.version.api.VersionService&metadata-type=remote&methods=sayHello&release=3.0.4-SNAPSHOT&revision=1.0.0&service-name-mapping=true&side=provider&token=1de93a01-b8f8-4f81-aa28-653b638e83ed&version=1.0.0)DubboProtocol is destroyed, dubbo version: 3.0.4-SNAPSHOT, current host: 192.168.160.5
2021-10-20T13:28:53.6699094Z java.lang.IllegalStateException: DubboProtocol is destroyed
2021-10-20T13:28:53.6700889Z 	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.checkDestroyed(DubboProtocol.java:346)
2021-10-20T13:28:53.6703229Z 	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.refer(DubboProtocol.java:421)
2021-10-20T13:28:53.6705268Z 	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:85)
2021-10-20T13:28:53.6707565Z 	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:77)
2021-10-20T13:28:53.6710150Z 	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:74)
2021-10-20T13:28:53.6712930Z 	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:52)
2021-10-20T13:28:53.6714976Z 	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
2021-10-20T13:28:53.6716909Z 	at org.apache.dubbo.registry.integration.RegistryDirectory.toInvokers(RegistryDirectory.java:376)
2021-10-20T13:28:53.6719727Z 	at org.apache.dubbo.registry.integration.RegistryDirectory.refreshInvoker(RegistryDirectory.java:235)
2021-10-20T13:28:53.6723032Z 	at org.apache.dubbo.registry.integration.RegistryDirectory.refreshOverrideAndInvoker(RegistryDirectory.java:187)
2021-10-20T13:28:53.6726085Z 	at org.apache.dubbo.registry.integration.RegistryDirectory.notify(RegistryDirectory.java:164)
2021-10-20T13:28:53.6728400Z 	at org.apache.dubbo.registry.support.AbstractRegistry.notify(AbstractRegistry.java:439)
2021-10-20T13:28:53.6730626Z 	at org.apache.dubbo.registry.support.FailbackRegistry.doNotify(FailbackRegistry.java:371)
2021-10-20T13:28:53.6732859Z 	at org.apache.dubbo.registry.support.FailbackRegistry.notify(FailbackRegistry.java:363)
2021-10-20T13:28:53.6816166Z 	at org.apache.dubbo.registry.zookeeper.ZookeeperRegistry.doSubscribe(ZookeeperRegistry.java:190)
2021-10-20T13:28:53.6818703Z 	at org.apache.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:298)
2021-10-20T13:28:53.6821130Z 	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:109)
2021-10-20T13:28:53.6823746Z 	at org.apache.dubbo.registry.integration.RegistryDirectory.subscribe(RegistryDirectory.java:119)
2021-10-20T13:28:53.6826502Z 	at org.apache.dubbo.registry.integration.RegistryProtocol.doCreateInvoker(RegistryProtocol.java:560)
2021-10-20T13:28:53.6830203Z 	at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getInvoker(InterfaceCompatibleRegistryProtocol.java:58)
2021-10-20T13:28:53.6834332Z 	at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshInterfaceInvoker(MigrationInvoker.java:448)
2021-10-20T13:28:53.6838444Z 	at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToApplicationFirstInvoker(MigrationInvoker.java:239)
2021-10-20T13:28:53.6842415Z 	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.refreshInvoker(MigrationRuleHandler.java:73)
2021-10-20T13:28:53.6845753Z 	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:57)
2021-10-20T13:28:53.6848930Z 	at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:241)
2021-10-20T13:28:53.6852265Z 	at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:529)
2021-10-20T13:28:53.6855117Z 	at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:498)
2021-10-20T13:28:53.6857492Z 	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:483)
2021-10-20T13:28:53.6860176Z 	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:83)
2021-10-20T13:28:53.6862490Z 	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:74)
2021-10-20T13:28:53.6865071Z 	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:71)
2021-10-20T13:28:53.6867853Z 	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:52)
2021-10-20T13:28:53.6870057Z 	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
2021-10-20T13:28:53.6872000Z 	at org.apache.dubbo.config.ReferenceConfig.createInvokerForRemote(ReferenceConfig.java:474)
2021-10-20T13:28:53.6874192Z 	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:379)
2021-10-20T13:28:53.6875945Z 	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:266)
2021-10-20T13:28:53.6877534Z 	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:203)
2021-10-20T13:28:53.6879403Z 	at org.apache.dubbo.config.utils.SimpleReferenceCache.get(SimpleReferenceCache.java:117)
2021-10-20T13:28:53.6881786Z 	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:326)
2021-10-20T13:28:53.6883898Z 	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
2021-10-20T13:28:53.6886142Z 	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:306)
2021-10-20T13:28:53.6888758Z 	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:146)
2021-10-20T13:28:53.6892449Z 	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:108)
2021-10-20T13:28:53.6897335Z 	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:98)
2021-10-20T13:28:53.6901894Z 	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:44)

```
详细日志见：https://github.com/apache/dubbo/runs/3951950812?check_suite_focus=true

类似的失败构建日志有很多，比如这个也是：
https://github.com/apache/dubbo/runs/3959438481?check_suite_focus=true

**Comment by zrlw** [comment]
看日志是VersionService1IT结束后的framework model destroy和VersionServiceStarIT的启动过程同步执行所致，VersionService1IT的framework编号是1

**Comment by zrlw** [comment]
现在ServiceConfigTest.testDelayExport第222行抛RejectedExecution：
```
Error:  org.apache.dubbo.config.ServiceConfigTest.testDelayExport  Time elapsed: 0.351 s  <<< ERROR!
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@33a910c5 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@2e7c932c[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at org.apache.dubbo.config.ServiceConfigTest.testDelayExport(ServiceConfigTest.java:222)
```
github构建也经常遇到，比如：
https://github.com/apache/dubbo/runs/4058917480?check_suite_focus=true
https://github.com/apache/dubbo/runs/4058917494?check_suite_focus=true

**Comment by zrlw** [comment]
貌似DefaultExecutorRepository的serviceExportExecutor的scope应该改成framework，不应该随着每个application进行shutdown

**Comment by zrlw** [comment]
新情况:
1. NPE at org.apache.dubbo.rpc.model.ApplicationModel.onDestroy(ApplicationModel.java:255)
2. IllegalStateException at org.apache.dubbo.rpc.model.FrameworkModel.checkDestroyed(FrameworkModel.java:257)
3. NPE at org.apache.dubbo.registry.client.migration.DefaultMigrationAddressComparatorTest.test(DefaultMigrationAddressComparatorTest.java:83)
```
2021-11-01T09:29:56.8368167Z [INFO] Running org.apache.dubbo.registry.client.migration.DefaultMigrationAddressComparatorTest
2021-11-01T09:29:56.8372225Z [DubboTestChecker] Run test method: org.apache.dubbo.registry.client.migration.DefaultMigrationAddressComparatorTest#test
2021-11-01T09:29:57.3850014Z [INFO] [01/11/21 09:29:57:255 UTC]  WARN listener.ServiceInstancesChangedListener:  [DUBBO] Received address refresh retry event, 1635758987187, dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.4474706Z [INFO] [01/11/21 09:29:57:302 UTC]  WARN listener.ServiceInstancesChangedListener:  [DUBBO] Retrying address notification..., dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.4912968Z [INFO] [01/11/21 09:29:57:465 UTC]  INFO migration.DefaultMigrationAddressComparator:  [DUBBO] No instance address available, stop compare., dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.5006954Z [INFO] [01/11/21 09:29:57:468 UTC]  INFO migration.DefaultMigrationAddressComparator:  [DUBBO] No interface address available, stop compare., dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.5012279Z [INFO] [01/11/21 09:29:57:473 UTC]  INFO model.FrameworkModel:  [DUBBO] Reset global default application from null to Dubbo Application[22.0](unknown), dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.5034212Z [INFO] [01/11/21 09:29:57:474 UTC]  INFO model.ApplicationModel:  [DUBBO] Dubbo Application[22.0](unknown) is created, dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.5036248Z [INFO] [01/11/21 09:29:57:464 UTC]  INFO model.FrameworkModel:  [DUBBO] Reset global default framework from null to Dubbo Framework[22], dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.5037972Z [INFO] [01/11/21 09:29:57:489 UTC]  INFO model.FrameworkModel:  [DUBBO] Dubbo Framework[22] is created, dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.5253170Z [INFO] [01/11/21 09:29:57:491 UTC]  INFO model.FrameworkModel:  [DUBBO] Destroying default framework model: Dubbo Framework[22], dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.5283856Z [INFO] [01/11/21 09:29:57:491 UTC]  INFO model.FrameworkModel:  [DUBBO] Dubbo Framework[22] is destroying ..., dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.5288063Z [INFO] [01/11/21 09:29:57:492 UTC]  INFO model.FrameworkModel:  [DUBBO] Reset global default application from Dubbo Application[22.0](unknown) to null, dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.5314733Z [INFO] [01/11/21 09:29:57:492 UTC] ERROR model.ScopeModel:  [DUBBO] Error happened when destroying ScopeModel., dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.5316630Z [INFO] java.lang.NullPointerException
2021-11-01T09:29:57.5318763Z [INFO] 	at org.apache.dubbo.rpc.model.ApplicationModel.onDestroy(ApplicationModel.java:255)
2021-11-01T09:29:57.5327542Z [INFO] 	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:108)
2021-11-01T09:29:57.5329957Z [INFO] 	at org.apache.dubbo.rpc.model.FrameworkModel.onDestroy(FrameworkModel.java:113)
2021-11-01T09:29:57.5331977Z [INFO] 	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:108)
2021-11-01T09:29:57.5396105Z [INFO] 	at org.apache.dubbo.rpc.model.FrameworkModel.destroyAll(FrameworkModel.java:191)
2021-11-01T09:29:57.5399043Z [INFO] 	at org.apache.dubbo.test.check.DubboTestChecker.executionFinished(DubboTestChecker.java:224)
2021-11-01T09:29:57.5402410Z [INFO] 	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.lambda$executionFinished$10(TestExecutionListenerRegistry.java:109)
2021-11-01T09:29:57.6126030Z [INFO] 	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.lambda$notifyEach$1(TestExecutionListenerRegistry.java:67)
2021-11-01T09:29:57.6192054Z [INFO] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2021-11-01T09:29:57.6195195Z [INFO] 	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.notifyEach(TestExecutionListenerRegistry.java:65)
2021-11-01T09:29:57.6198609Z [INFO] 	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.access$200(TestExecutionListenerRegistry.java:32)
2021-11-01T09:29:57.6202334Z [INFO] 	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.executionFinished(TestExecutionListenerRegistry.java:108)
2021-11-01T09:29:57.6205993Z [INFO] 	at org.junit.platform.launcher.core.ExecutionListenerAdapter.executionFinished(ExecutionListenerAdapter.java:56)
2021-11-01T09:29:57.6209704Z [INFO] 	at org.junit.platform.launcher.core.DelegatingEngineExecutionListener.executionFinished(DelegatingEngineExecutionListener.java:46)
2021-11-01T09:29:57.6214176Z [INFO] 	at org.junit.platform.launcher.core.OutcomeDelayingEngineExecutionListener.executionFinished(OutcomeDelayingEngineExecutionListener.java:63)
2021-11-01T09:29:57.6218067Z [INFO] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.reportCompletion(NodeTestTask.java:179)
2021-11-01T09:29:57.6220817Z [INFO] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:85)
2021-11-01T09:29:57.6222744Z [INFO] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2021-11-01T09:29:57.6228400Z [INFO] 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2021-11-01T09:29:57.6232453Z [INFO] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
2021-11-01T09:29:57.6302426Z [INFO] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-11-01T09:29:57.6305699Z [INFO] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
2021-11-01T09:29:57.6308183Z [INFO] 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
2021-11-01T09:29:57.6310647Z [INFO] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
2021-11-01T09:29:57.6313738Z [INFO] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-11-01T09:29:57.6317051Z [INFO] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
2021-11-01T09:29:57.6320053Z [INFO] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
2021-11-01T09:29:57.6327453Z [INFO] 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
2021-11-01T09:29:57.6332779Z [INFO] 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2021-11-01T09:29:57.6336286Z [INFO] 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
2021-11-01T09:29:57.6338980Z [INFO] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
2021-11-01T09:29:57.6341036Z [INFO] 	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
2021-11-01T09:29:57.6343553Z [INFO] 	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
2021-11-01T09:29:57.6345995Z [INFO] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
2021-11-01T09:29:57.6348034Z [INFO] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
2021-11-01T09:29:57.6350497Z [INFO] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
2021-11-01T09:29:57.6353828Z [INFO] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
2021-11-01T09:29:57.6357010Z [INFO] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
2021-11-01T09:29:57.6359648Z [INFO] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
2021-11-01T09:29:57.6361849Z [INFO] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2021-11-01T09:29:57.6363694Z [INFO] 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
2021-11-01T09:29:57.6365415Z [INFO] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
2021-11-01T09:29:57.6366913Z [INFO] [01/11/21 09:29:57:496 UTC]  INFO model.FrameworkModel:  [DUBBO] Dubbo Framework[22] is destroyed, dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.6368526Z [INFO] [01/11/21 09:29:57:508 UTC] ERROR listener.ServiceInstancesChangedListener:  [DUBBO] Failed to load service metadata, meta type is local, dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.6370073Z [INFO] java.lang.IllegalStateException: FrameworkModel is destroyed
2021-11-01T09:29:57.6371663Z [INFO] 	at org.apache.dubbo.rpc.model.FrameworkModel.checkDestroyed(FrameworkModel.java:257)
2021-11-01T09:29:57.6374015Z [INFO] 	at org.apache.dubbo.rpc.model.FrameworkModel.addApplication(FrameworkModel.java:224)
2021-11-01T09:29:57.6376021Z [INFO] 	at org.apache.dubbo.rpc.model.ApplicationModel.<init>(ApplicationModel.java:203)
2021-11-01T09:29:57.6377750Z [INFO] 	at org.apache.dubbo.rpc.model.FrameworkModel.initialize(FrameworkModel.java:91)
2021-11-01T09:29:57.6379829Z [INFO] 	at org.apache.dubbo.rpc.model.FrameworkModel.<init>(FrameworkModel.java:77)
2021-11-01T09:29:57.6381788Z [INFO] 	at org.apache.dubbo.rpc.model.FrameworkModel.defaultModel(FrameworkModel.java:169)
2021-11-01T09:29:57.6385378Z [INFO] 	at org.apache.dubbo.rpc.model.ApplicationModel.defaultModel(ApplicationModel.java:93)
2021-11-01T09:29:57.6388229Z [INFO] 	at org.apache.dubbo.rpc.model.ScopeModelUtil.getOrDefaultApplicationModel(ScopeModelUtil.java:64)
2021-11-01T09:29:57.6390912Z [INFO] 	at org.apache.dubbo.rpc.model.ScopeModelUtil.getApplicationModel(ScopeModelUtil.java:59)
2021-11-01T09:29:57.6393684Z [INFO] 	at org.apache.dubbo.registry.client.ServiceInstance.getOrDefaultApplicationModel(ServiceInstance.java:103)
2021-11-01T09:29:57.6396521Z [INFO] 	at org.apache.dubbo.registry.client.metadata.MetadataUtils.referProxy(MetadataUtils.java:81)
2021-11-01T09:29:57.6399207Z [INFO] 	at org.apache.dubbo.registry.client.metadata.MetadataUtils.lambda$getMetadataServiceProxy$0(MetadataUtils.java:67)
2021-11-01T09:29:57.6401910Z [INFO] 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
2021-11-01T09:29:57.6425235Z [INFO] 	at org.apache.dubbo.registry.client.metadata.MetadataUtils.getMetadataServiceProxy(MetadataUtils.java:67)
2021-11-01T09:29:57.6429434Z [INFO] 	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.doGetMetadataInfo(ServiceInstancesChangedListener.java:379)
2021-11-01T09:29:57.6434446Z [INFO] 	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.getRemoteMetadata(ServiceInstancesChangedListener.java:330)
2021-11-01T09:29:57.6439047Z [INFO] 	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.onEvent(ServiceInstancesChangedListener.java:143)
2021-11-01T09:29:57.6443918Z [INFO] 	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener$AddressRefreshRetryTask.run(ServiceInstancesChangedListener.java:493)
2021-11-01T09:29:57.6446773Z [INFO] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2021-11-01T09:29:57.6448073Z [INFO] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2021-11-01T09:29:57.6449942Z [INFO] 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
2021-11-01T09:29:57.6452140Z [INFO] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-11-01T09:29:57.6453987Z [INFO] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-11-01T09:29:57.6455206Z [INFO] 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-11-01T09:29:57.6456790Z [INFO] [01/11/21 09:29:57:510 UTC] ERROR listener.ServiceInstancesChangedListener:  [DUBBO] Failed to get MetadataInfo for instance 30.10.0.8:20880?revision=444&cluster=default, wait for retry., dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.6458613Z [INFO] [01/11/21 09:29:57:510 UTC]  INFO model.FrameworkModel:  [DUBBO] Reset global default framework from Dubbo Framework[22] to null, dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.6460134Z [INFO] [01/11/21 09:29:57:510 UTC]  INFO resource.GlobalResourcesRepository:  [DUBBO] Destroying global resources ..., dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.6461754Z [INFO] [01/11/21 09:29:57:510 UTC]  INFO resource.GlobalResourcesRepository:  [DUBBO] Dubbo is completely destroyed, dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.6463306Z [INFO] [01/11/21 09:29:57:530 UTC]  INFO model.FrameworkModel:  [DUBBO] Reset global default framework from null to Dubbo Framework[23], dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.6464836Z [INFO] [01/11/21 09:29:57:530 UTC]  INFO model.FrameworkModel:  [DUBBO] Dubbo Framework[23] is created, dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.6466131Z [INFO] [01/11/21 09:29:57:535 UTC]  INFO model.ApplicationModel:  [DUBBO] Dubbo Application[23.0](unknown) is created, dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.6467375Z [INFO] [01/11/21 09:29:57:535 UTC]  INFO model.ScopeModel:  [DUBBO] Dubbo Module[23.0.0] is created, dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.6469126Z [INFO] [01/11/21 09:29:57:542 UTC]  INFO context.AbstractConfigManager:  [DUBBO] Config settings: {dubbo.config.mode=STRICT, dubbo.config.ignore-duplicated-interface=false}, dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.6471516Z [INFO] [01/11/21 09:29:57:545 UTC]  INFO context.AbstractConfigManager:  [DUBBO] Config settings: {dubbo.config.mode=STRICT, dubbo.config.ignore-duplicated-interface=false}, dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.6474386Z [INFO] [01/11/21 09:29:57:550 UTC]  INFO model.FrameworkModel:  [DUBBO] Reset global default application from null to Dubbo Application[23.1](unknown), dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.6476243Z [INFO] [01/11/21 09:29:57:550 UTC]  INFO model.ApplicationModel:  [DUBBO] Dubbo Application[23.1](unknown) is created, dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.6477676Z [INFO] [01/11/21 09:29:57:550 UTC]  INFO model.ScopeModel:  [DUBBO] Dubbo Module[23.1.0] is created, dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.6479448Z [INFO] [01/11/21 09:29:57:552 UTC]  INFO context.AbstractConfigManager:  [DUBBO] Config settings: {dubbo.config.mode=STRICT, dubbo.config.ignore-duplicated-interface=false}, dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.6485027Z [INFO] [01/11/21 09:29:57:553 UTC]  INFO context.AbstractConfigManager:  [DUBBO] Config settings: {dubbo.config.mode=STRICT, dubbo.config.ignore-duplicated-interface=false}, dubbo version: 3.0.5-SNAPSHOT, current host: 172.23.96.1
2021-11-01T09:29:57.6488630Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.692 s <<< FAILURE! - in org.apache.dubbo.registry.client.migration.DefaultMigrationAddressComparatorTest
2021-11-01T09:29:57.6492111Z [ERROR] org.apache.dubbo.registry.client.migration.DefaultMigrationAddressComparatorTest.test  Time elapsed: 0.66 s  <<< ERROR!
2021-11-01T09:29:57.6494343Z java.lang.NullPointerException
2021-11-01T09:29:57.6496881Z 	at org.apache.dubbo.registry.client.migration.DefaultMigrationAddressComparatorTest.test(DefaultMigrationAddressComparatorTest.java:83)
```
