### ISSUE TITLE
从3.0.2.1升级到3.0.3   Can not create registry 

### ISSUE THREAD

**Issue by q2186609** [apache/dubbo#9085]
### Environment

* Dubbo version: 3.0.3
* Operating System version: window11
* Java version: 1.8

从3.0.2.1 升级 dubbo 到3.0.3

启动失败
`Exception in thread "main" java.lang.RuntimeException: Can not create registry service-discovery-registry://192.168.2.228:2181/org.apache.dubbo.registry.RegistryService?application=stream-provider&dubbo=2.0.2&interface=org.apache.dubbo.registry.RegistryService&pid=25560&registry=zookeeper&release=3.0.3
	at org.apache.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:89)
	at org.apache.dubbo.registry.RegistryFactoryWrapper.getRegistry(RegistryFactoryWrapper.java:33)
	at org.apache.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)
	at org.apache.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:386)
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:237)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:64)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:74)
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:58)
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47)
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ServiceConfig.doExportUrl(ServiceConfig.java:650)
	at org.apache.dubbo.config.ServiceConfig.exportRemote(ServiceConfig.java:624)
	at org.apache.dubbo.config.ServiceConfig.exportUrl(ServiceConfig.java:584)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:415)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:403)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:378)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:231)
	at DubboProvider.main(DubboProvider.java:46)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: failed to connect to zookeeper server
	at org.apache.dubbo.common.function.ThrowableAction.execute(ThrowableAction.java:48)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.createServiceDiscovery(ServiceDiscoveryRegistry.java:115)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.<init>(ServiceDiscoveryRegistry.java:91)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryFactory.createRegistry(ServiceDiscoveryRegistryFactory.java:35)
	at org.apache.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:86)
	... 17 more
Caused by: java.lang.IllegalStateException: failed to connect to zookeeper server
	at org.apache.dubbo.registry.zookeeper.util.CuratorFrameworkUtils.buildCuratorFramework(CuratorFrameworkUtils.java:75)
	at org.apache.dubbo.registry.zookeeper.ZookeeperServiceDiscovery.doInitialize(ZookeeperServiceDiscovery.java:76)
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.initialize(AbstractServiceDiscovery.java:38)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.lambda$createServiceDiscovery$0(ServiceDiscoveryRegistry.java:115)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry$$Lambda$105/115945887.execute(Unknown Source)
	at org.apache.dubbo.common.function.ThrowableAction.execute(ThrowableAction.java:46)
	... 21 more`

3.0.2.1  可以正常启动。没有更改任何配置文件

![image](https://user-images.githubusercontent.com/78395988/138244690-f06808d5-a750-488f-a86e-e47d94eb33bf.png)

**Comment by twz007** [comment]
Can you tell me how to solve it?

**Comment by gonnaup** [comment]
遇到了，估计是zookeeper版本支持问题，经测试（dubbo3.0.7），3.4.13及以下版本正常运行，3.4.14后报错。估计是3.4.14及以后版本对连接字符（dubbo将一些元数据放入了连接串中）中某些字符或格式不支持导致连接失败。异常抛出点org.apache.dubbo.registry.zookeeper.util.CuratorFrameworkUtils#buildCuratorFramework

**Comment by gonwan** [comment]
same issue and stacktrace, dubbo 3.0.9.
works when downgrade and stick zookeeper client to 3.4.13. please fix this.

**Comment by XuYijie000416** [comment]
same issue in dubbo 3.1.0.

**Comment by AlbumenJ** [comment]
> same issue in dubbo 3.1.0.

可以提一个完整的 samples 吗

**Comment by ilaotan** [comment]
哎，zk3.8.0没问题，3.8.1就时不时的 Can not create registry service-discovery-registry

**Comment by gonwan** [comment]
Find some time to debug the issue. It seems to only affects Windows. The root cause is that zookeeper clients invoke `InetAddress#getHostName()` when connecting to remote nodes. The method involves host name resolution, which may be very slow under Windows. The error stack is actually a timeout error.

And here are the workarounds:
Option1: Enlarge timeout value:
```
dubbo.registry.timeout=30000
dubbo.registry.parameters.blockUntilConnectedWait=30
```
Option2: Add addresses of zookeeper nodes to the local `hosts` file.
