### ISSUE TITLE
Service mapping failure on multiple registry centers

### ISSUE THREAD

**Issue by kylixs** [apache/dubbo#9194]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.5
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. Build and run ` rpc-one-server`, `rpc-two-server`
2. Build and run `rpc-two-consumer`

Relative issue: #9172
Demo:  [dubbo-issue-9172.zip](https://github.com/apache/dubbo/files/7465357/dubbo-issue-9172.zip)

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

Expect  `BookTwoService`  mapping path is : `/dubbo/rpc-two-server/mapping/two.common.service.BookTwoService`
but got : `/dubbo/rpc-one-server/mapping/two.common.service.BookTwoService`

Debug point:
```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.apache.dubbo.metadata.store.zookeeper.ZookeeperMetadataReport.getServiceAppMapping(ZookeeperMetadataReport.java:157)
	  at org.apache.dubbo.registry.client.metadata.MetadataServiceNameMapping.getAndListen(MetadataServiceNameMapping.java:108)
	  at org.apache.dubbo.metadata.AbstractServiceNameMapping.getAndListenServices(AbstractServiceNameMapping.java:101)
	  at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.doSubscribe(ServiceDiscoveryRegistry.java:218)
	  at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribe(ServiceDiscoveryRegistry.java:206)
	  at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:109)
	  at org.apache.dubbo.registry.integration.DynamicDirectory.subscribe(DynamicDirectory.java:159)
	  at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.subscribe(ServiceDiscoveryRegistryDirectory.java:106)
	  at org.apache.dubbo.registry.integration.RegistryProtocol.doCreateInvoker(RegistryProtocol.java:562)
	  at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getServiceDiscoveryInvoker(InterfaceCompatibleRegistryProtocol.java:65)
	  at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshServiceDiscoveryInvoker(MigrationInvoker.java:424)
	  at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToApplicationFirstInvoker(MigrationInvoker.java:240)
	  at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.refreshInvoker(MigrationRuleHandler.java:73)
	  at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:57)
	  - locked <0x23a1> (a org.apache.dubbo.registry.client.migration.MigrationRuleHandler)
	  at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:241)
	  at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:531)
	  at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:500)
	  at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:485)
	  at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:74)
	  at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:83)
	  at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:71)
	  at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:52)
	  at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java:-1)
	  at org.apache.dubbo.config.ReferenceConfig.createInvokerForRemote(ReferenceConfig.java:472)
	  at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:377)
	  at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:266)
```

logs:
```
2021-11-03 12:33:07.532  INFO 27270 --- [           main] o.a.d.r.c.m.MetadataServiceNameMapping   :  [DUBBO] two.common.service.BookTwoService mapping to [] instructed by remote metadata center., dubbo version: 3.0.5-SNAPSHOT, current host: 30.250.193.142
```

```
2021-11-03 12:38:25.823 ERROR 27270 --- [           main] o.a.d.c.deploy.DefaultModuleDeployer     :  [DUBBO] Dubbo Module[1.1.1] refer catch error, dubbo version: 3.0.5-SNAPSHOT, current host: 30.250.193.142

java.lang.IllegalStateException: Should has at least one way to know which services this interface belongs to, subscription url: dubbo://30.250.193.142/two.common.service.BookTwoService?REGISTRY_CLUSTER=registry-rpc-two&application=rpc-two-consumer&background=false&category=providers,configurators,routers&check=true&compiler=javassist&dubbo=2.0.2&interface=two.common.service.BookTwoService&lazy=true&logger=slf4j&metadata-type=remote&methods=getById&organization=test&owner=com.test&pid=27270&qos.enable=true&release=3.0.5-SNAPSHOT&side=consumer&sticky=false&timeout=15000&timestamp=1635913745806
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.doSubscribe(ServiceDiscoveryRegistry.java:225) ~[dubbo-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribe(ServiceDiscoveryRegistry.java:206) ~[dubbo-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:109) ~[dubbo-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.apache.dubbo.registry.integration.DynamicDirectory.subscribe(DynamicDirectory.java:159) ~[dubbo-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.subscribe(ServiceDiscoveryRegistryDirectory.java:106) ~[dubbo-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.apache.dubbo.registry.integration.RegistryProtocol.doCreateInvoker(RegistryProtocol.java:562) ~[dubbo-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getServiceDiscoveryInvoker(InterfaceCompatibleRegistryProtocol.java:65) ~[dubbo-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshServiceDiscoveryInvoker(MigrationInvoker.java:424) ~[dubbo-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToApplicationFirstInvoker(MigrationInvoker.java:240) ~[dubbo-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.refreshInvoker(MigrationRuleHandler.java:73) ~[dubbo-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:57) ~[dubbo-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:241) ~[dubbo-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:531) ~[dubbo-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:500) ~[dubbo-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:485) ~[dubbo-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:74) ~[dubbo-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:83) ~[dubbo-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:71) ~[dubbo-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:52) ~[dubbo-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java) ~[dubbo-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.apache.dubbo.config.ReferenceConfig.createInvokerForRemote(ReferenceConfig.java:472) ~[dubbo-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:377) ~[dubbo-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:266) ~[dubbo-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:207) ~[dubbo-3.0.5-SNAPSHOT.jar:3.0.5-SNAPSHOT]

```

**Comment by chickenlj** [comment]
configuration of `dubbo.registry.group=xxx` should be supported by both ServiceDiscovery and MetadataReport

**Comment by chickenlj** [comment]
related https://github.com/apache/dubbo/issues/9427

**Comment by complone** [comment]
@chickenlj  I want to try to follow up on this issue

**Comment by complone** [comment]
@chickenlj I am willing to follow up, please assign this issue to me

**Comment by complone** [comment]
@chickenlj 


The original purpose of this requirement is that when the user uses the provider side configuration, the current way that the user uses in dubbo 2.7 and 3.0 is by specifying ``` in xml <dubbo:registry id="registry1" address="zookeeper:// 127.0.0.1:2181" group="dubbo"/>
The ``` method can take effect. The problem currently encountered is not the inconsistency between the configuration center and the metadata center group, but as in [issue-9188](https://github.com/apache/dubbo/issues/9188) The desired group shown is that services can be differentiated according to the environment. Since this issue does not provide a full demo reproduction, I will try to reproduce the problem


Below is the pass-by-value call chain that I track the value of the "register" property, I'll add more later

https://www.processon.com/view/link/61f94596e0b34d06c3b9458d

**Comment by complone** [comment]
The essence of this problem is that when the registry is used as the metadata center, the consumer cannot get the relevant address information from the registry, thus reporting an error.

![2022-02-04-12-56-01](https://user-images.githubusercontent.com/20021404/152474396-ee7aca5b-7e81-4023-8478-6c377f82dabd.jpg)

I will fix the relevant details to support the address of the registration center and the metadata center to be consistent, where group already exists as one of the first-level temporary nodes in zk

**Comment by chickenlj** [comment]
https://github.com/apache/dubbo/issues/9427
