### ISSUE TITLE
[2.7.x] ConfigCenterBean#includeSpringEnv can not work

### ISSUE THREAD

**Issue by zhuangjinjin** [apache/dubbo#9207]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.14
* Operating System version: Mac OS 11.5.2
* Java version: jdk1.8.0_261

### Steps to reproduce this issue

I want to get spring environment properties via ConfigurationUtils

In my demo, Application.java
```java
@SpringBootApplication
public class Application {

    @Bean
    public ApplicationRunner applicationRunner() {
        return (args) ->
            Assert.notNull(ConfigurationUtils.getProperty("server.name"), "serverName must not be null");
    }

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
```
application.yml
```yaml
server:
  name: dubbo-demo
  port: 0

dubbo:
  application:
    name: dubbo-demo
  config-center:
    include-spring-env: true
```

### Expected Behavior
I hope the above assertion will pass

### Actual Behavior
When I run the Application, it thrown assertion exception

```
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:789) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.example.Application.main(Application.java:24) [classes/:na]
Caused by: java.lang.IllegalArgumentException: serverName must not be null
	at org.apache.dubbo.common.utils.Assert.notNull(Assert.java:27) ~[dubbo-2.7.14.jar:2.7.14]
	at org.example.Application.lambda$applicationRunner$0(Application.java:20) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	... 5 common frames omitted
```

**Comment by kylixs** [comment]
It seems misunderstanding of `includeSpringEnv` of `config-center`, please see the example: [dubbo-samples-configcenter-externalconfiguration](https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-configcenter/dubbo-samples-configcenter-externalconfiguration).

At the same time, `dubbo.config-center.include-spring-env` was not processed correctly, and external configuration was not loaded correctly from Spring Environment.

**Temporary solution: Define `config-center` through xml/java bean.**

This bug will be fixed in 3.0.x, and the 2.7.x may not be fixed.
