### ISSUE TITLE
[3.0] TripleProtocolTest的testDemoProtocol测试方法创建的StreamObserver直到方法结束才有机会执行

### ISSUE THREAD

**Issue by zrlw** [apache/dubbo#9225]
### Environment

* Dubbo version: 3.0
TripleProtocolTest的testDemoProtocol测试方法创建的StreamObserver直到方法结束才有机会执行，可导致后续测试异常：
```
2021-11-07T02:19:11.1560924Z [INFO] Running org.apache.dubbo.rpc.protocol.tri.TripleProtocolTest
2021-11-07T02:19:11.7912854Z [DubboTestChecker] Run test method: org.apache.dubbo.rpc.protocol.tri.TripleProtocolTest#testDemoProtocol
2021-11-07T02:19:13.9549175Z srt=hello world
2021-11-07T02:19:13.9738328Z [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.81 s - in 
org.apache.dubbo.rpc.protocol.tri.TripleProtocolTest
<=== TripleProtocolTest方法结束

2021-11-07T02:19:13.9859194Z [INFO] Running org.apache.dubbo.rpc.protocol.tri.UnaryClientStreamTest
2021-11-07T02:19:13.9862189Z [DubboTestChecker] Run test method: org.apache.dubbo.rpc.protocol.tri.UnaryClientStreamTest#testInit
2021-11-07T02:19:14.0179103Z java.lang.RuntimeException: Failed to unwrap resp
2021-11-07T02:19:14.0181174Z 	at org.apache.dubbo.rpc.protocol.tri.AbstractClientStream.unwrapResp(AbstractClientStream.java:337)
2021-11-07T02:19:14.0184137Z 	at org.apache.dubbo.rpc.protocol.tri.AbstractClientStream.deserializeResponse(AbstractClientStream.java:319)
2021-11-07T02:19:14.0187187Z 	at org.apache.dubbo.rpc.protocol.tri.ClientStream$ClientStreamInboundTransportObserverImpl.lambda$onData$0(ClientStream.java:79)
2021-11-07T02:19:14.0189917Z 	at org.apache.dubbo.common.threadpool.serial.SerializingExecutor.run(SerializingExecutor.java:99)
2021-11-07T02:19:14.0192219Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-11-07T02:19:14.0194032Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-11-07T02:19:14.0195909Z 	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
2021-11-07T02:19:14.0197325Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-11-07T02:19:14.0198285Z Caused by: java.lang.IllegalStateException: FrameworkModel is destroyed
2021-11-07T02:19:14.0199893Z 	at org.apache.dubbo.rpc.model.FrameworkModel.checkDestroyed(FrameworkModel.java:259)
2021-11-07T02:19:14.0202009Z 	at org.apache.dubbo.rpc.model.FrameworkModel.addApplication(FrameworkModel.java:226)
2021-11-07T02:19:14.0203850Z 	at org.apache.dubbo.rpc.model.ApplicationModel.<init>(ApplicationModel.java:203)
2021-11-07T02:19:14.0205616Z 	at org.apache.dubbo.rpc.model.FrameworkModel.initialize(FrameworkModel.java:91)
2021-11-07T02:19:14.0207307Z 	at org.apache.dubbo.rpc.model.FrameworkModel.<init>(FrameworkModel.java:77)
2021-11-07T02:19:14.0209055Z 	at org.apache.dubbo.rpc.model.FrameworkModel.defaultModel(FrameworkModel.java:167)
2021-11-07T02:19:14.0211187Z 	at org.apache.dubbo.rpc.model.ScopeModelUtil.getFrameworkModel(ScopeModelUtil.java:85)
2021-11-07T02:19:14.0213461Z 	at org.apache.dubbo.common.URL.getOrDefaultFrameworkModel(URL.java:604)
2021-11-07T02:19:14.0216179Z 	at org.apache.dubbo.common.serialize.DefaultMultipleSerialization.deserialize(DefaultMultipleSerialization.java:41)
2021-11-07T02:19:14.0240429Z 	at org.apache.dubbo.rpc.protocol.tri.AbstractClientStream.unwrapResp(AbstractClientStream.java:333)
2021-11-07T02:19:14.0242220Z 	... 7 more
2021-11-07T02:19:14.0242662Z onCompleted
<=== TripleProtocolTest方法创建的StreamObserver的onCompleted回调方法到此时才执行

2021-11-07T02:19:14.0244737Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.03 s <<< FAILURE! - in org.apache.dubbo.rpc.protocol.tri.UnaryClientStreamTest
2021-11-07T02:19:14.0247038Z [ERROR] org.apache.dubbo.rpc.protocol.tri.UnaryClientStreamTest.testInit  Time elapsed: 0.002 s  <<< ERROR!
2021-11-07T02:19:14.0248641Z java.lang.NullPointerException
2021-11-07T02:19:14.0250439Z 	at org.apache.dubbo.rpc.protocol.tri.UnaryClientStreamTest.testInit(UnaryClientStreamTest.java:38)
```

**Comment by zrlw** [comment]
GrpcProtocolTest存在同样的问题。
