### ISSUE TITLE
[3.0] Zookeeper全局测试注册中心存在的问题

### ISSUE THREAD

**Issue by zrlw** [apache/dubbo#9227]
### Environment

* Dubbo version: 3.0
* Operating System version: win7

自从测试使用全局ZK注册中心之后，github构建有时失败，而我本地win7单元测试SpringAnnotationBeanTest和SpringXmlConfigTest就没有成功过。
1. 下载的zk执行过程中缺少jar包：
```
java.lang.NoClassDefFoundError: org/xerial/snappy/SnappyInputStream
	at org.apache.zookeeper.server.persistence.Util.makeSnapshotName(Util.java:97)
	at org.apache.zookeeper.server.persistence.FileTxnSnapLog.save(FileTxnSnapLog.java:469)
	at org.apache.zookeeper.server.persistence.FileTxnSnapLog.restore(FileTxnSnapLog.java:291)
	at org.apache.zookeeper.server.ZKDatabase.loadDataBase(ZKDatabase.java:285)
	at org.apache.zookeeper.server.ZooKeeperServer.loadData(ZooKeeperServer.java:484)
	at org.apache.zookeeper.server.ZooKeeperServer.startdata(ZooKeeperServer.java:655)
	at org.apache.zookeeper.server.NIOServerCnxnFactory.startup(NIOServerCnxnFactory.java:758)
	at org.apache.zookeeper.server.ServerCnxnFactory.startup(ServerCnxnFactory.java:130)
	at org.apache.zookeeper.server.ZooKeeperServerMain.runFromConfig(ZooKeeperServerMain.java:159)
	at org.apache.zookeeper.server.ZooKeeperServerMain.initializeAndRun(ZooKeeperServerMain.java:112)
	at org.apache.zookeeper.server.ZooKeeperServerMain.main(ZooKeeperServerMain.java:67)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:140)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:90)
Caused by: java.lang.ClassNotFoundException: org.xerial.snappy.SnappyInputStream
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
```
2. 下载zk的过程没有考虑并行测试的情况，并行测试同时下载的压缩文件是解不开的，而且之后会一直尝试用这个损坏的压缩文件，解不开直接退出而不是重新下载。
3. 众所周知的原因，下载的速度奇慢无比，花费几分钟时间等待是否合适，对于封闭无互联网环境，还要自己debug跟踪确认需要拷贝进来的文件版本，很不方便。

建议：
直接把使用的zk及执行过程中依赖的文件放到dubbo测试目录，pull拉dubbo代码的时候直接拉到本地。

**Comment by pinxiong** [comment]
Thanks for your feedback, I'll fix this issue!

**Comment by kylixs** [comment]
I think that `apache-zookeeper-bin.zip` should not be submitted to the dubbo warehouse to avoid submitting larger binary files to increase the size of the git submission history.   
The zookeeper version may need to be updated, and there may be other registration centers in the future, such as nacos, which cannot all be placed in the git repository. 
What about to cache to a directory in the dubbo project,  such as `mvnw`?

**Comment by kylixs** [comment]
@pinxiong You can improve the download processing:
First download to a temporary file, if successful, rename/move to the official file name, if it fails, download again next time.

**Comment by kylixs** [comment]
User can download it manually from  [https://zookeeper.apache.org/releases.html#download](https://zookeeper.apache.org/releases.html#download), and copy it to dubbo project.

**Comment by pinxiong** [comment]
@kylixs @zrlw I tried to solve this issue, you can see #9274 

Hope to get more suggestions.

**Comment by zrlw** [comment]
> @kylixs @zrlw I tried to solve this issue, you can see #9274
> 
> Hope to get more suggestions.

windows本机测试SpringAnnotationBeanTest和SpringXmlConfigTest已成功。
