### ISSUE TITLE
nacos密码带&时注册失败

### ISSUE THREAD

**Issue by feng996** [apache/dubbo#9252]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.4
* Operating System version: centos  7
* Java version: 11

### Steps to reproduce this issue

dubbo:
  registry:
    address: nacos://${nacos.host}:${nacos.port}?username=${nacos.username}&password=${nacos.password}&namespace=${nacos.namespace}

If there is an exception, please attach the exception trace:

ause: Request nacos server failed: 
	at org.apache.dubbo.registry.nacos.NacosRegistry.doRegister(NacosRegistry.java:174) ~[dubbo-3.0.4.jar!/:3.0.4]
	at org.apache.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:205) ~[dubbo-3.0.4.jar!/:3.0.4]
	... 43 more
Caused by: com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:279) ~[nacos-client-2.0.3.jar!/:?]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:129) ~[nacos-client-2.0.3.jar!/:?]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:115) ~[nacos-client-2.0.3.jar!/:?]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:95) ~[nacos-client-2.0.3.jar!/:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:145) ~[nacos-client-2.0.3.jar!/:?]
	at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.registerInstance(NacosNamingServiceWrapper.java:59) ~[dubbo-3.0.4.jar!/:3.0.4]
	at org.apache.dubbo.registry.nacos.NacosRegistry.doRegister(NacosRegistry.java:171) ~[dubbo-3.0.4.jar!/:3.0.4]
	at org.apache.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:205) ~[dubbo-3.0.4.jar!/:3.0.4]
	... 43 more
Caused by: com.alibaba.nacos.api.exception.NacosException: unknown user!
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:271) ~[nacos-client-2.0.3.jar!/:?]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:129) ~[nacos-client-2.0.3.jar!/:?]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:115) ~[nacos-client-2.0.3.jar!/:?]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:95) ~[nacos-client-2.0.3.jar!/:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:145) ~[nacos-client-2.0.3.jar!/:?]
	at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.registerInstance(NacosNamingServiceWrapper.java:59) ~[dubbo-3.0.4.jar!/:3.0.4]
	at org.apache.dubbo.registry.nacos.NacosRegistry.doRegister(NacosRegistry.java:171) ~[dubbo-3.0.4.jar!/:3.0.4]
	at org.apache.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:205) ~[dubbo-3.0.4.jar!/:3.0.4]
	... 43 more

**Comment by EarthChen** [comment]
urlencode 一下试试 因为放在 url 上会当参数解析

**Comment by feng996** [comment]
> urlencode 一下试试 因为放在 url 上会当参数解析

密码url encode和转义都试过了，不行

**Comment by EarthChen** [comment]
> > urlencode 一下试试 因为放在 url 上会当参数解析
> 
> 密码url encode和转义都试过了，不行

问题还是在于对 query params 的判断是 ?后面使用&截取的，还是建议换个密码

**Comment by feng996** [comment]
改密码解决
