### ISSUE TITLE
[3.0] InstanceAddressURL不支持ReferenceCountExchangeClient的replaceWithLazyClient方法，无论scope model是否destroyed都会NPE

### ISSUE THREAD

**Issue by zrlw** [apache/dubbo#9283]
### Environment

* Dubbo version: 3.0 

如果URL是InstanceAddressURL，那么创建LazyConnectExchangeClient对象时new ServiceConfigURL调用就会NPE。
因为创建ServiceConfigURL要调用url.getPath()方法，url类型是InstanceAddressURL，getPath()从RpcContext的rpcServiceContext获取consumerUrl，作为入参传入metadataInfo.getServiceInfo方法。
InstanceAddressURL每次rpc之后都会清掉RpcContext的rpcServiceContext，url.getPath()从已被remove的thread local获取的consumerUrl为null，将null传入metadataInfo.getServiceInfo方法作为key进行ConcurrentHashMap.get就NPE了：
```
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.apache.dubbo.metadata.MetadataInfo.getServiceInfo(MetadataInfo.java:174)
	at org.apache.dubbo.registry.client.InstanceAddressURL.getPath(InstanceAddressURL.java:133)
	at org.apache.dubbo.rpc.protocol.dubbo.LazyConnectExchangeClient.<init>(LazyConnectExchangeClient.java:65)
	at org.apache.dubbo.rpc.protocol.dubbo.ReferenceCountExchangeClient.replaceWithLazyClient(ReferenceCountExchangeClient.java:217)
	at org.apache.dubbo.rpc.protocol.dubbo.ReferenceCountExchangeClient.closeInternal(ReferenceCountExchangeClient.java:187)
	at org.apache.dubbo.rpc.protocol.dubbo.ReferenceCountExchangeClient.close(ReferenceCountExchangeClient.java:164)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboInvoker.destroyInternal(DubboInvoker.java:174)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboInvoker.destroy(DubboInvoker.java:141)
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.destroy(ListenerInvokerWrapper.java:89)
	at org.apache.dubbo.rpc.Invoker.destroyAll(Invoker.java:50)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.destroyAllInvokers(ServiceDiscoveryRegistryDirectory.java:344)
	at org.apache.dubbo.registry.integration.DynamicDirectory.destroy(DynamicDirectory.java:297)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.destroy(AbstractClusterInvoker.java:126)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.destroy(MockClusterInvoker.java:80)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.destroy(MigrationInvoker.java:316)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:72)
	at org.apache.dubbo.common.bytecode.proxy4.$destroy(proxy4.java)
	at org.apache.dubbo.config.utils.SimpleReferenceCache.destroyReference(SimpleReferenceCache.java:244)
	at org.apache.dubbo.config.utils.SimpleReferenceCache.lambda$5(SimpleReferenceCache.java:234)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.apache.dubbo.config.utils.SimpleReferenceCache.destroyAll(SimpleReferenceCache.java:232)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.unreferServices(DefaultModuleDeployer.java:402)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.postDestroy(DefaultModuleDeployer.java:205)
	at org.apache.dubbo.rpc.model.ModuleModel.onDestroy(ModuleModel.java:107)
	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:108)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextClosedEvent(DubboDeployApplicationListener.java:127)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:100)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:1)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:96)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:335)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1059)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1020)
	at org.apache.dubbo.test.spring.SpringXmlConfigTest.test(SpringXmlConfigTest.java:69)
```
实际上清掉rpcServiceContext之后，除了getPath()NPE这个问题外，url.getProtocol()和url.getParameters()这两个方法也获取不了原来ReferenceCountExchangeClient使用的url参数，构建不了LazyConnectExchangeClient。

#9284 在SpringXmlConfigTest测试类增加了上述场景的验证测试。

**Comment by zrlw** [comment]
#9284 修改了ReferenceCountExchangeClient的replaceWithLazyClient方法，在创建LazyConnectExchangeClient之前增加了RpcContext.getServiceContext().getConsumerUrl()非null判断，为null则直接返回以避免NPE。
存在的不足：
1. 不容易理解；
2. 不通用：严格意义上目前只有InstanceAddressURL类型的URL才会出现NPE，如果只对InstanceAddressURL类型的URL做上述判断，dubbo-rpc-dubbo要增加dubbo-registry-api依赖，然后ReferenceCountExchangeClient才能使用InstanceAddressURL类型进行判定。

如果能直接获得当前ScopeModel的destroyed状态就好了，用destroy状态进行判定不仅容易理解，而且更支持URL类型扩展。

**Comment by zrlw** [comment]
最终还是把InstanceAddressURL给改了，构造方法先把consumerUrl保存下来，从service context获取consumerUrl的相关方法都改为直接读取构造方法保存的consumerUrl，这样scope model销毁之后（service context清掉consumer url），这些方法就不会再NPE了（从service context获取的consumerUrl为null）。

**Comment by zrlw** [comment]
现在 #9284 回到了最初的方式，每次rpc调用时将当前的rpcServiceContext保存到InstanceAddressURL以备使用。

**Comment by zrlw** [comment]
重新读了一遍相关的代码，现在的 #9284 是在下次rpc调用前清理上次rpcServiceContext，每次rpc调用完不再清理rpcServiceContext了，这么修订主要基于如下考量。
1. rpcServiceContext的核心是consumerUrl，每次rpc调用完留着rpcServiceContext除了消耗了一点thread local内存，没有其他副作用；
2. 相关的unit test同步修订，每次rpc调用后如果需要清理rpcServiceContext，需要手工清理；
3. 支持LazyConnectExchangeClient。

**Comment by zrlw** [comment]
LazyConnectExchangeClient 要被作废了，所以这个issue先关了。
