### ISSUE TITLE
problems run in java17

### ISSUE THREAD

**Issue by landon30** [apache/dubbo#9315]
- [X] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.4
* Operating System version:  mac
* Java version: 17

### Steps to reproduce this issue

1. samples: https://github.com/apache/dubbo-samples/blob/master/dubbo-samples-api
2. registry center: zookeeper
3. launch the privider application and the consumer application

### Expected Behavior

rpc sayHi run success

### Actual Behavior

1. first exception
    - __fixed__ with the jvm arguments:  --add-opens java.base/java.lang=ALL-UNNAMED
```
Exception in thread "main" java.lang.IllegalStateException: Failed to create adaptive instance: java.lang.IllegalStateException: Can't create adaptive extension interface org.apache.dubbo.rpc.Protocol, cause: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @3a4afd8d
	at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtension(ExtensionLoader.java:666)
```
2. second exception
    __try__: registry timeout,centerConfig timeout is not work
```
Exception in thread "main" java.lang.IllegalStateException: zookeeper not connected
	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.<init>(CuratorZookeeperClient.java:87)
```
but my zookeeper is started
```
% jps 
2804 QuorumPeerMain

% zkServer status
/usr/bin/java
ZooKeeper JMX enabled by default
Using config: /usr/local/etc/zookeeper/zoo.cfg
Client port found: 2181. Client address: localhost.
Mode: standalone

```

### the final solution
i switched 2 __java8__，everything is ok

### conclusion
dubbo is not supported in java17 environment

**Comment by landon30** [comment]
may be it's the zkclient bug in the java17

**Comment by chickenlj** [comment]
support of JDK17 is still under development. please focus on #9062
