### ISSUE TITLE
dubbo3.0.4 使用grpc协议时，在编译时报错找不到或无法加载主类 org.apache.dubbo.gen.grpc.DubboRpcGrpcGenerator

### ISSUE THREAD

**Issue by Leeloing** [apache/dubbo#9319]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.4
* Operating System version: mac 
* Java version: 1.8

### Steps to reproduce this issue

1. 引入dubbo-rpc-grpc maven依赖
```xml
<dependency>
  <groupId>org.apache.dubbo</groupId>
  <artifactId>dubbo-rpc-grpc</artifactId>
  <version>${dubbo.version}</version>
</dependency>
<build>
  <extensions>
    <extension>
      <groupId>kr.motd.maven</groupId>
      <artifactId>os-maven-plugin</artifactId>
      <version>1.7.0</version>
    </extension>
  </extensions>
  <plugins>
    <plugin>
      <groupId>org.xolstice.maven.plugins</groupId>
      <artifactId>protobuf-maven-plugin</artifactId>
      <version>0.6.1</version>
      <configuration>
        <protocArtifact>com.google.protobuf:protoc:3.7.1:exe:${os.detected.classifier}</protocArtifact>
        <pluginId>grpc-java</pluginId>
        <pluginArtifact>io.grpc:protoc-gen-grpc-java:${grpc.version}:exe:${os.detected.classifier}</pluginArtifact>
        <outputDirectory>src/main/java</outputDirectory>
        <clearOutputDirectory>true</clearOutputDirectory>
        <protocPlugins>
          <protocPlugin>
            <id>dubbo-grpc</id>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-compiler</artifactId>
            <version>${dubbo.compiler.version}</version>
            <mainClass>org.apache.dubbo.gen.grpc.DubboGrpcGenerator</mainClass>
          </protocPlugin>
        </protocPlugins>
      </configuration>
      <executions>
        <execution>
          <goals>
            <goal>compile</goal>
            <goal>test-compile</goal>
          </goals>
        </execution>
      </executions>
    </plugin>
  </plugins>
</build>
```
2. proto文件
```protobuf
syntax = "proto3";

option java_multiple_files = true;
option java_package = "org.zeus.bom.service";
option java_outer_classname = "BomServiceProto";


package org.zeus.bom.service;

message Bom{
  int64  bom_id = 1;
  int64  tenant_id = 2;
  string name = 3;
  string revision = 4;
  string bom_type = 5;
  string bom_status = 6;
}

message BomRequest{
  repeated int64 id = 1;
}

message BomResponse{
  repeated Bom boms = 1;
}

service BomService{
  rpc getBomByIds(BomRequest) returns (BomResponse) {}

  rpc getBomWithIds(BomRequest) returns (stream BomResponse) {}

  rpc saveBom(stream BomResponse) returns (BomRequest) {}

  rpc saveBom2(stream BomResponse) returns (stream BomRequest) {}
}
```
3. 执行mvn clean install时报错
[INFO] Compiling 1 proto file(s) to /Users/apple/my-project/示例项目/SpringBoot-Labs/lab-30/lab-30-dubbo-annotations-nacos/user-rpc-service-api-03/src/main/java
[ERROR] PROTOC FAILED: java.lang.RuntimeException: Could not find resource DubboGrpcInterfaceStub.mustache
        at com.salesforce.jprotoc.Generator.applyTemplate(Generator.java:66)
        at org.apache.dubbo.gen.AbstractGenerator.buildFile(AbstractGenerator.java:220)
        at org.apache.dubbo.gen.AbstractGenerator.generateFiles(AbstractGenerator.java:201)
        at org.apache.dubbo.gen.AbstractGenerator.generateFiles(AbstractGenerator.java:76)
        at com.salesforce.jprotoc.ProtocPlugin.lambda$generate$1(ProtocPlugin.java:192)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
        at java.util.Collections$2.tryAdvance(Collections.java:4717)
        at java.util.Collections$2.forEachRemaining(Collections.java:4725)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.salesforce.jprotoc.ProtocPlugin.generate(ProtocPlugin.java:197)
        at com.salesforce.jprotoc.ProtocPlugin.generate(ProtocPlugin.java:81)
        at com.salesforce.jprotoc.ProtocPlugin.generate(ProtocPlugin.java:52)
        at com.salesforce.jprotoc.ProtocPlugin.generate(ProtocPlugin.java:44)
        at org.apache.dubbo.gen.grpc.DubboGrpcGenerator.main(DubboGrpcGenerator.java:27)
--dubbo-grpc_out: protoc-gen-dubbo-grpc: Plugin failed with status code 1.

**Comment by yl-yue** [comment]
3.x版本都有这个问题
同时还有这个问题：#7719

**Comment by Leeloing** [comment]
这边是将之前是使用的0.0.3 ,版本降低之后可以编译<dubbo.compiler.version>0.0.1</dubbo.compiler.version>
