### ISSUE TITLE
org.apache.dubbo.remoting.RemotingException: grpc: compressed flag set with identity or empty encoding

### ISSUE THREAD

**Issue by javaXN** [apache/dubbo#9387]
provider使用golang，dubbogo3。
consumer使用java，dubbo3、spring boot。
使用dubbo3最新的triple协议。注册中心使用nacos。
寻求各位大佬帮助，谢谢。

java 出现如下错误：org.apache.dubbo.remoting.RemotingException: grpc: compressed flag set with identity or empty encoding
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture2.doReceived(DefaultFuture2.java:193)
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture2.received(DefaultFuture2.java:149)
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture2.received(DefaultFuture2.java:138)
	at org.apache.dubbo.rpc.protocol.tri.UnaryClientStream$UnaryClientTransportObserver.lambda$onError$1(UnaryClientStream.java:93)
	at org.apache.dubbo.common.threadpool.serial.SerializingExecutor.run(SerializingExecutor.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
	at java.lang.Thread.run(Thread.java:748)

**Comment by guohao** [comment]
Can you provide a simple demo to reproduce this issue?

**Comment by javaXN** [comment]
***@***.*** 邮箱







At 2021-12-13 14:04:26, "GuoHao" ***@***.***> wrote:

Can you provide a simple demo to reproduce this issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
