### ISSUE TITLE
[3.0] MessageDigest ArrayIndexOutOfBoundsException, seems like a md5 thread safe issue

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo#9402]
```java
2021-12-13 21:40:43.580 ERROR [Dubbo-shared-scheduler-thread-1] org.apache.dubbo.config.deploy.DefaultApplicationDeployer[766] -  [DUBBO] Refresh instance and metadata error, dubbo version: 3.0.4, current host: 10.8.0.14
java.lang.ArrayIndexOutOfBoundsException: null
	at java.lang.System.arraycopy(Native Method)
	at sun.security.provider.DigestBase.engineUpdate(DigestBase.java:115)
	at sun.security.provider.MD5.implDigest(MD5.java:109)
	at sun.security.provider.DigestBase.engineDigest(DigestBase.java:183)
	at sun.security.provider.DigestBase.engineDigest(DigestBase.java:162)
	at java.security.MessageDigest$Delegate.engineDigest(MessageDigest.java:617)
	at java.security.MessageDigest.digest(MessageDigest.java:368)
	at org.apache.dubbo.common.utils.MD5Utils.getMd5(MD5Utils.java:51)
	at org.apache.dubbo.metadata.RevisionResolver.calRevision(RevisionResolver.java:27)
	at org.apache.dubbo.metadata.MetadataInfo.calAndGetRevision(MetadataInfo.java:121)
	at org.apache.dubbo.registry.client.metadata.ServiceInstanceMetadataUtils.calInstanceRevision(ServiceInstanceMetadataUtils.java:233)
	at org.apache.dubbo.registry.client.metadata.ServiceInstanceMetadataUtils.lambda$refreshMetadataAndInstance$2(ServiceInstanceMetadataUtils.java:280)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.apache.dubbo.registry.client.metadata.ServiceInstanceMetadataUtils.refreshMetadataAndInstance(ServiceInstanceMetadataUtils.java:272)
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.lambda$registerServiceInstance$3(DefaultApplicationDeployer.java:762)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by whoisje** [comment]
看了下3.0.4的 tag 中 #9176 还没有合并进去，升级一下应该就好了。 @chickenlj @wangchengming666
