### ISSUE TITLE
The following warn log was found when running the official 'dubbo-demo-xml' from the main repo

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo#9403]
```java
[14/12/21 14:33:00:066 CST] DubboClientHandler-thread-1  WARN dubbo.DecodeableRpcResult:  [DUBBO] Decode rpc result failed: null, dubbo version: , current host: 30.225.12.132
java.lang.NullPointerException
	at org.apache.dubbo.registry.client.InstanceAddressURL.getScopeModel(InstanceAddressURL.java:498)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:127)
	at org.apache.dubbo.remoting.transport.DecodeHandler.decode(DecodeHandler.java:57)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:48)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
	at java.lang.Thread.run(Thread.java:748)
Hello, rest from separated thread.
Triple! from separated thread.

```

**Comment by chickenlj** [comment]
fixed by #9290
