### ISSUE TITLE
[3.0] The shutdown process of 3.0 needs to be further verified.

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo#9422]
The shutdown process of 3.0 needs to be verified.

Make sure `address un-registration from the registry` and `read-only notification event to the consumer` are done first before any internal resource destroy.

```java
// DubboShutdownHook.java

  private void doDestroy() {
      this.applicationModel.destroy();
  }
```

**Comment by chickenlj** [comment]
```java
  public void preDestroy() {
        if (!this.isStopping() && !this.isStopped()) {
            this.onStopping();
            this.unRegisterShutdownHook();
            if (this.asyncMetadataFuture != null) {
                this.asyncMetadataFuture.cancel(true);
            }

            this.unregisterServiceInstance();
            this.unexportMetadataService();
        }
    }
```


ApplicationModel.java  
```java
    protected void onDestroy() {
        if (this.deployer != null) {
            this.deployer.preDestroy();
        }

        Iterator var1 = (new ArrayList(this.moduleModels)).iterator();

        while(var1.hasNext()) {
            ModuleModel moduleModel = (ModuleModel)var1.next();
            if (moduleModel != this.internalModule) {
                moduleModel.destroy();
            }
        }

        this.internalModule.destroy();
        if (defaultInstance == this) {
            Class var5 = ApplicationModel.class;
            synchronized(ApplicationModel.class) {
                this.frameworkModel.removeApplication(this);
                defaultInstance = null;
            }
        } else {
            this.frameworkModel.removeApplication(this);
        }

        if (this.deployer != null) {
            this.deployer.postDestroy();
        }

        this.notifyDestroy();
        if (this.environment != null) {
            this.environment.destroy();
            this.environment = null;
        }

        if (this.configManager != null) {
            this.configManager.destroy();
            this.configManager = null;
        }

        if (this.serviceRepository != null) {
            this.serviceRepository.destroy();
            this.serviceRepository = null;
        }

        this.frameworkModel.tryDestroy();
    }
```

**Comment by chickenlj** [comment]
Make sure the following still gets executed first on destroy:

Registry.unregister()/destroy()
Protocol.destroy()
HeaderExchangeChannel.sendChannelReadonlyEvent

**Comment by chickenlj** [comment]
Typical exception occurred during shutdown:

```java
Caused by: java.util.concurrent.ExecutionException: org.apache.dubbo.remoting.RemotingException: Fail to decode request due to: java.io.IOException: Service org.apache.dubbo.samples.api.GreetingService with version 1.0.0 not found, invocation rejected.
java.io.IOException: Service org.apache.dubbo.samples.api.GreetingService with version 1.0.0 not found, invocation rejected.
	at org.apache.dubbo.remoting.transport.CodecSupport.checkSerialization(CodecSupport.java:164)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:138)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:93)
	at org.apache.dubbo.remoting.transport.DecodeHandler.decode(DecodeHandler.java:57)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:44)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:181)
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:256)
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:179)
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:78)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invokeWithContext(AbstractClusterInvoker.java:300)
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:79)
	... 21 more

```

**Comment by ilaotan** [comment]
found the same problm.

**Comment by ilaotan** [comment]
官网说dubbo3在很多公司使用了: "在阿里巴巴内部，众多业务线包括电商系统的考拉、交易平台，以及饿了么、钉钉等都已经成功迁移到 Dubbo3 版本。同样全程参与在 Dubbo3 开发与验证试点过程中的企业用户包括工商银行、携程、斗鱼、小米等"  
我就有个疑问,dubbo3.0的graceful shutdown有问题的话,以上企业是如何做的graceful shutdown? 难不成每次发布服务都报一堆错误?

**Comment by ilaotan** [comment]
retries>0时好像可以避免这个错误.但是这个参数加上后,所有服务都要做幂等处理.

**Comment by ilaotan** [comment]
dubbo3.0.5降级到2.7.15. 测试没问题.
