### ISSUE TITLE
dubbo 2.7.10 RegistryProtocol.java:183 NPE

### ISSUE THREAD

**Issue by xiehong0114** [apache/dubbo#9457]
java.lang.NullPointerException: null
	at org.apache.dubbo.registry.integration.RegistryProtocol.registerStatedUrl(RegistryProtocol.java:183) ~[dubbo-2.7.10.jar!/:2.7.10]
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:218) ~[dubbo-2.7.10.jar!/:2.7.10]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:62) ~[dubbo-2.7.10.jar!/:2.7.10]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:73) ~[dubbo-2.7.10.jar!/:2.7.10]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:64) ~[dubbo-2.7.10.jar!/:2.7.10]
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) ~[dubbo-2.7.10.jar!/:2.7.10]
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:494) ~[dubbo-2.7.10.jar!/:2.7.10]
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:327) ~[dubbo-2.7.10.jar!/:2.7.10]
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:303) ~[dubbo-2.7.10.jar!/:2.7.10]
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:204) ~[dubbo-2.7.10.jar!/:2.7.10]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.lambda$exportServices$14(DubboBootstrap.java:1088) ~[dubbo-2.7.10.jar!/:2.7.10]
	at java.util.HashMap$Values.forEach(HashMap.java:981) ~[na:1.8.0_242]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.exportServices(DubboBootstrap.java:1075) ~[dubbo-2.7.10.jar!/:2.7.10]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:889) ~[dubbo-2.7.10.jar!/:2.7.10]
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onContextRefreshedEvent(DubboBootstrapApplicationListener.java:69) ~[dubbo-2.7.10.jar!/:2.7.10]
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onApplicationContextEvent(DubboBootstrapApplicationListener.java:62) ~[dubbo-2.7.10.jar!/:2.7.10]
	at com.alibaba.spring.context.OnceApplicationContextEventListener.onApplicationEvent(OnceApplicationContextEventListener.java:52) ~[spring-context-support-1.0.10.jar!/:na]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403) ~[spring-context-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360) ~[spring-context-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:897) ~[spring-context-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162) ~[spring-boot-2.1.17.RELEASE.jar!/:2.1.17.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) ~[spring-context-5.1.18.RELEASE.jar!/:5.1.18.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.1.17.RELEASE.jar!/:2.1.17.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744) [spring-boot-2.1.17.RELEASE.jar!/:2.1.17.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391) [spring-boot-2.1.17.RELEASE.jar!/:2.1.17.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-2.1.17.RELEASE.jar!/:2.1.17.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.1.17.RELEASE.jar!/:2.1.17.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204) [spring-boot-2.1.17.RELEASE.jar!/:2.1.17.RELEASE]
	
	
升级到dubbo 2.7.10 报NPE 有什么解法？

**Comment by CrazyHZM** [comment]
2.7.14是否存在该问题

**Comment by xiehong0114** [comment]
> 2.7.14是否存在该问题

暂时没用这个版本，打算按这个版本升级下。

**Comment by RongXiong2016** [comment]
I also had the same problem

**Comment by RongXiong2016** [comment]
这个问题找到解决办法了？

**Comment by AlbumenJ** [comment]
Please try upgrade to 2.7.18

**Comment by RongXiong2016** [comment]
> Please try upgrade to 2.7.18

已尝试过，未报错但是无法注册nacos2.1.1上，故一个个版本往下降；目前使用2.7.8正常启动并注册

**Comment by AlbumenJ** [comment]
> 已尝试过，未报错但是无法注册nacos2.1.1上，故一个个版本往下降；目前使用2.7.8正常启动并注册

可以在报错行打个断点，看一下 `registeredProviderUrl.getServiceKey()` 的结果是什么吗

**Comment by RongXiong2016** [comment]
> > 已尝试过，未报错但是无法注册nacos2.1.1上，故一个个版本往下降；目前使用2.7.8正常启动并注册

> 
> 可以在报错行打个断点，看一下 `registeredProviderUrl.getServiceKey()` 的结果是什么吗

<img width="1399" alt="Snipaste_2022-12-26_15-35-05" src="https://user-images.githubusercontent.com/18466554/209519824-c02fd34c-5008-4c91-becc-e9e2498a983b.png">
debug发现，底层providers map变量中key 缺少 前group:default 和 后version：1.0.0，导致得到的model变量为null。请问这个得如何修改

**Comment by AlbumenJ** [comment]
看了一下应该是 2.7 高版本处理 dubbo.provider 这个默认配置的时候的问题，通过 `dubbo.provider` 配置 group 和 version 会有冲突。可以改成通过 `dubbo.service` 尝试配置看看，或者升级到 3.1.4 版本

**Comment by AlbumenJ** [comment]
@RongXiong2016
