### ISSUE TITLE
Optimize argument decode exception handling.

### ISSUE THREAD

**Issue by tianshuang** [apache/dubbo#9489]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.5
* Operating System version: Mac OS
* Java version: 8

### Steps to reproduce this issue

[dubbo-samples/dubbo-samples-serialization/dubbo-samples-serialization-hessian2/src/main/java/org/apache/dubbo/samples/serialization at master · tianshuang/dubbo-samples · GitHub](https://github.com/tianshuang/dubbo-samples/tree/master/dubbo-samples-serialization/dubbo-samples-serialization-hessian2/src/main/java/org/apache/dubbo/samples/serialization)
Run org.apache.dubbo.samples.serialization.DubboProvider, and run org.apache.dubbo.samples.serialization.DubboConsumer.

### Expected Behavior
When the [User](https://github.com/tianshuang/dubbo-samples/blob/master/dubbo-samples-serialization/dubbo-samples-serialization-hessian2/src/main/java/org/apache/dubbo/samples/serialization/dto/User.java) constructor contains non-primitive objects that cause an exception in the constructor, we hope that the consumer can obtain the original exception information. We want the consumer to get IllegalArgumentException instead of NullPointerException, that is, it should get the original exception.

### Actual Behavior

What we get is the NullPointerException thrown in the provider method body, not the original IllegalArgumentException in the constructor. The reason is that the decode exception is caught and the exception is not thrown to the consumer.

```
Exception in thread "main" java.lang.NullPointerException
	at org.apache.dubbo.samples.serialization.impl.UserServiceImpl.find(UserServiceImpl.java:31)
	at org.apache.dubbo.common.bytecode.Wrapper1.invokeMethod(Wrapper1.java)
	at org.apache.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47)
	at org.apache.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:84)
	at org.apache.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:56)
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
	at org.apache.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:52)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:89)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:44)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:81)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:102)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:149)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:41)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:150)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:100)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:175)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by tianshuang** [comment]
[dubbo-hessian-lite/JavaDeserializer.java at master · apache/dubbo-hessian-lite · GitHub](https://github.com/apache/dubbo-hessian-lite/blob/master/src/main/java/com/alibaba/com/caucho/hessian/io/JavaDeserializer.java#L137):
```java
    /**
     * Creates a map of the classes fields.
     */
    protected static Object getParamArg(Class cl) {
        if (!cl.isPrimitive())
            return null;
        else if (boolean.class.equals(cl))
            return Boolean.FALSE;
        else if (byte.class.equals(cl))
            return new Byte((byte) 0);
        else if (short.class.equals(cl))
            return new Short((short) 0);
        else if (char.class.equals(cl))
            return new Character((char) 0);
        else if (int.class.equals(cl))
            return Integer.valueOf(0);
        else if (long.class.equals(cl))
            return Long.valueOf(0);
        else if (float.class.equals(cl))
            return Float.valueOf(0);
        else if (double.class.equals(cl))
            return Double.valueOf(0);
        else
            throw new UnsupportedOperationException();
    }
```

During Hessian deserialization, the parameter of the non-primitive type in the constructor will be initialized to null. If the parameter is used in the constructor, the relevant exception will be triggered during deserialization.

**Comment by tianshuang** [comment]
Imagine a scenario where the provider receives a User object and writes it directly to the database, and the User object is null due to a deserialization error, and the data written to the database is null. If the provider's log level is ERROR, then the provider has no exception, the consumer also has no exception, which makes it difficult to troubleshoot the problem.
