### ISSUE TITLE
【3.0】dubbo3.0 workflows cannot execute successfully

### ISSUE THREAD

**Issue by codeimport** [apache/dubbo#9551]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

The workflow of dubbo3.0 cannot be executed successfully. I have tried many times, and each time it is stuck in the same test case. The test case ZookeeperRegistryTest cannot pass the test under jdk17. I guess there is a compatibility problem with this test case in the jdk17 version.

Error:  Errors: 
Error:    ZookeeperRegistryTest.setUp:65 » IllegalState zookeeper not connected
Error:    ZookeeperRegistryTest.setUp:65 » IllegalState zookeeper not connected
Error:    ZookeeperRegistryTest.setUp:65 » IllegalState zookeeper not connected
Error:    ZookeeperRegistryTest.setUp:65 » IllegalState zookeeper not connected
Error:    ZookeeperRegistryTest.setUp:65 » IllegalState zookeeper not connected
Error:    ZookeeperRegistryTest.setUp:65 » IllegalState zookeeper not connected
Error:    ZookeeperRegistryTest.setUp:65 » IllegalState zookeeper not connected
Error:    ZookeeperRegistryTest.setUp:65 » IllegalState zookeeper not connected
Error:    ZookeeperRegistryTest.setUp:65 » IllegalState zookeeper not connected
Error:    ZookeeperRegistryTest.setUp:65 » IllegalState zookeeper not connected
Error:    ZookeeperRegistryTest.setUp:65 » IllegalState zookeeper not connected
Error:    ZookeeperRegistryTest.setUp:65 » IllegalState zookeeper not connected
Error:    CuratorFrameworkUtilsTest.testBuildCuratorFramework:61 » IllegalState failed t...
Error:    CuratorFrameworkUtilsTest.testBuildServiceDiscovery:69 » IllegalState failed t...

**Comment by codeimport** [comment]
I checked other people's pr recently and found that other people also have this problem. This test case cannot pass under jdk17.

**Comment by juzi214032** [comment]
I also found this problem, can you fix it?

**Comment by codeimport** [comment]
Who can help deal with this problem, otherwise everyone's PR can't be submitted
@AlbumenJ @chickenlj @pinxiong

**Comment by codeimport** [comment]
> I also found this problem, can you fix it?

not yet，I found that jdk17 test has been added recently. It may be a compatibility problem

**Comment by juzi214032** [comment]
> not yet，I found that jdk17 test has been added recently. It may be a compatibility problem

This seems to have no relationship with jdk version, I use jdk8 unit test is also failed, you use jdk8 can pass the unit test?
![image](https://user-images.githubusercontent.com/38206169/148693474-ac04afc9-ecdb-4176-86a3-a33f4bac1b06.png)

**Comment by codeimport** [comment]
> > not yet，I found that jdk17 test has been added recently. It may be a compatibility problem
> 
> This seems to have no relationship with jdk version, I use jdk8 unit test is also failed, you use jdk8 can pass the unit test?
> 
> ![image](https://user-images.githubusercontent.com/38206169/148693474-ac04afc9-ecdb-4176-86a3-a33f4bac1b06.png)

work good use jdk8 local

**Comment by pinxiong** [comment]
> Who can help deal with this problem, otherwise everyone's PR can't be submitted @AlbumenJ @chickenlj @pinxiong

@codeimport @juzi214032 I'll fix this issue.

It can be sure that the cause of this problem is that `zookeeper` instances didn't work. There are several steps to check when the failed testcases you have mentioned are running:

1. Check if there are two `zookeeper` processes first
2. Check if the zookeeper archive binary file is downloaded successfully
   + All of download info will be in the given path, if you set `-DembeddedZookeeperPath`
   + and then to check the `.tmp/zookeeper` directory in `user.home`
   + finally you can check the `.tmp/zookeeper` directory in `java.io.tmpdir`

In most cases, this problem is caused by zooKeeper not being downloaded.

If there is no internet in the running environment, you also can copy the downloaded zookeeper archive binary (it's version should be equal or greater than `3.6.0`) in  the `.tmp/zookeeper` directory in `user.home`. Here is an example below:

Suppose you didn't set `-DembeddedZookeeperPath` and
+ `user.home` is `/Users/myhostname`
+ The copied zookeeper archive binary file is named `apache-zookeeper-3.6.3-bin.tar.gz`

What you need to do as below:
+ Create a directory named `.tmp/zookeeper` in `/Users/myhostname`
+ Copy the file `apache-zookeeper-3.6.3-bin.tar.gz` in `/Users/myhostname/.tmp/zookeeper`
+ Rename the file `apache-zookeeper-3.6.3-bin.tar.gz` to `apache-zookeeper-bin.tar.gz`

And then you can have a try.

**Comment by pinxiong** [comment]
I have reproduce this problem in my local machine.

The exception occurred as below:

```java
Connected to the target VM, address: '127.0.0.1:56915', transport: 'socket'
log4j:WARN No appenders could be found for logger (org.apache.dubbo.test.check.registrycenter.ZookeeperRegistryCenter).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Jan 11, 2022 9:10:25 PM org.junit.platform.launcher.core.TestExecutionListenerRegistry lambda$notifyEach$1
WARNING: TestExecutionListener [org.apache.dubbo.test.check.RegistryCenterStarted] threw exception for method: testPlanExecutionStarted(org.junit.platform.launcher.core.InternalTestPlan@553f1d75)
java.lang.IllegalStateException: Failed to start zookeeper instance in unit test
	at org.apache.dubbo.test.check.RegistryCenterStarted.testPlanExecutionStarted(RegistryCenterStarted.java:37)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.lambda$testPlanExecutionStarted$12(TestExecutionListenerRegistry.java:115)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.lambda$notifyEach$1(TestExecutionListenerRegistry.java:67)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.notifyEach(TestExecutionListenerRegistry.java:65)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.access$200(TestExecutionListenerRegistry.java:32)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.testPlanExecutionStarted(TestExecutionListenerRegistry.java:115)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:200)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.RuntimeException: Download zookeeper binary archive failed, download url:https://archive.apache.org/dist/zookeeper/zookeeper-3.6.0/apache-zookeeper-3.6.0-bin.tar.gz, file path:/var/folders/qb/c5lkt6s932s1v2gvx702sqx40000gp/T/zookeeper/apache-zookeeper-3.6.0-bin.tar.gz.
Or you can do something to avoid this problem as below:
1. Download zookeeper binary archive manually regardless of the version
2. Rename the downloaded file named 'apache-zookeeper-{version}-bin.tar.gz' to 'apache-zookeeper-bin.tar.gz'
3. Put the renamed file in /Users/xxxx/.tmp/zookeeper/apache-zookeeper-bin.tar.gz, you maybe need to create the directory if necessary.

	at org.apache.dubbo.test.check.registrycenter.initializer.DownloadZookeeperInitializer.doInitialize(DownloadZookeeperInitializer.java:113)
	at org.apache.dubbo.test.check.registrycenter.initializer.ZookeeperInitializer.initialize(ZookeeperInitializer.java:41)
	at org.apache.dubbo.test.check.registrycenter.ZookeeperRegistryCenter.startup(ZookeeperRegistryCenter.java:220)
	at org.apache.dubbo.test.check.registrycenter.GlobalRegistryCenter.startup(GlobalRegistryCenter.java:35)
	at org.apache.dubbo.test.check.RegistryCenterStarted.testPlanExecutionStarted(RegistryCenterStarted.java:34)
	... 16 more
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to archive.apache.org/138.201.131.134:443 after 30000 ms
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
	at org.apache.dubbo.test.check.registrycenter.initializer.DownloadZookeeperInitializer.download(DownloadZookeeperInitializer.java:175)
	at org.apache.dubbo.test.check.registrycenter.initializer.DownloadZookeeperInitializer.doInitialize(DownloadZookeeperInitializer.java:111)
	... 20 more
Caused by: java.util.concurrent.TimeoutException: Request timeout to archive.apache.org/138.201.131.134:443 after 30000 ms
	at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
	at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

[DubboTestChecker] Project dir: /Users/xxxx/Documents/workspace/java/dubbo/dubbo-registry/dubbo-registry-zookeeper
```

I think you can copy the downloaded zookeeper archive binary file to the specified path where you can find in error info.

For example: `/Users/xxxx/.tmp/zookeeper/apache-zookeeper-bin.tar.gz`

```java
Caused by: java.lang.RuntimeException: Download zookeeper binary archive failed, download url:https://archive.apache.org/dist/zookeeper/zookeeper-3.6.0/apache-zookeeper-3.6.0-bin.tar.gz, file path:/var/folders/qb/c5lkt6s932s1v2gvx702sqx40000gp/T/zookeeper/apache-zookeeper-3.6.0-bin.tar.gz.
Or you can do something to avoid this problem as below:
1. Download zookeeper binary archive manually regardless of the version
2. Rename the downloaded file named 'apache-zookeeper-{version}-bin.tar.gz' to 'apache-zookeeper-bin.tar.gz'
3. Put the renamed file in /Users/xxxx/.tmp/zookeeper/apache-zookeeper-bin.tar.gz, you maybe need to create the directory if necessary.
```

**Comment by pinxiong** [comment]
I have reproduce this problem in my local machine.

The exception occurred as below:

```java
Connected to the target VM, address: '127.0.0.1:56915', transport: 'socket'
log4j:WARN No appenders could be found for logger (org.apache.dubbo.test.check.registrycenter.ZookeeperRegistryCenter).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Jan 11, 2022 9:10:25 PM org.junit.platform.launcher.core.TestExecutionListenerRegistry lambda$notifyEach$1
WARNING: TestExecutionListener [org.apache.dubbo.test.check.RegistryCenterStarted] threw exception for method: testPlanExecutionStarted(org.junit.platform.launcher.core.InternalTestPlan@553f1d75)
java.lang.IllegalStateException: Failed to start zookeeper instance in unit test
	at org.apache.dubbo.test.check.RegistryCenterStarted.testPlanExecutionStarted(RegistryCenterStarted.java:37)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.lambda$testPlanExecutionStarted$12(TestExecutionListenerRegistry.java:115)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.lambda$notifyEach$1(TestExecutionListenerRegistry.java:67)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.notifyEach(TestExecutionListenerRegistry.java:65)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.access$200(TestExecutionListenerRegistry.java:32)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.testPlanExecutionStarted(TestExecutionListenerRegistry.java:115)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:200)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.RuntimeException: Download zookeeper binary archive failed, download url:https://archive.apache.org/dist/zookeeper/zookeeper-3.6.0/apache-zookeeper-3.6.0-bin.tar.gz, file path:/var/folders/qb/c5lkt6s932s1v2gvx702sqx40000gp/T/zookeeper/apache-zookeeper-3.6.0-bin.tar.gz.
Or you can do something to avoid this problem as below:
1. Download zookeeper binary archive manually regardless of the version
2. Rename the downloaded file named 'apache-zookeeper-{version}-bin.tar.gz' to 'apache-zookeeper-bin.tar.gz'
3. Put the renamed file in /Users/xxxx/.tmp/zookeeper/apache-zookeeper-bin.tar.gz, you maybe need to create the directory if necessary.

	at org.apache.dubbo.test.check.registrycenter.initializer.DownloadZookeeperInitializer.doInitialize(DownloadZookeeperInitializer.java:113)
	at org.apache.dubbo.test.check.registrycenter.initializer.ZookeeperInitializer.initialize(ZookeeperInitializer.java:41)
	at org.apache.dubbo.test.check.registrycenter.ZookeeperRegistryCenter.startup(ZookeeperRegistryCenter.java:220)
	at org.apache.dubbo.test.check.registrycenter.GlobalRegistryCenter.startup(GlobalRegistryCenter.java:35)
	at org.apache.dubbo.test.check.RegistryCenterStarted.testPlanExecutionStarted(RegistryCenterStarted.java:34)
	... 16 more
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to archive.apache.org/138.201.131.134:443 after 30000 ms
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
	at org.apache.dubbo.test.check.registrycenter.initializer.DownloadZookeeperInitializer.download(DownloadZookeeperInitializer.java:175)
	at org.apache.dubbo.test.check.registrycenter.initializer.DownloadZookeeperInitializer.doInitialize(DownloadZookeeperInitializer.java:111)
	... 20 more
Caused by: java.util.concurrent.TimeoutException: Request timeout to archive.apache.org/138.201.131.134:443 after 30000 ms
	at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
	at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

[DubboTestChecker] Project dir: /Users/xxxx/Documents/workspace/java/dubbo/dubbo-registry/dubbo-registry-zookeeper
```

I think you can copy the downloaded zookeeper archive binary file to the specified path where you can find in error info.

For example: `/Users/xxxx/.tmp/zookeeper/apache-zookeeper-bin.tar.gz`

```java
Caused by: java.lang.RuntimeException: Download zookeeper binary archive failed, download url:https://archive.apache.org/dist/zookeeper/zookeeper-3.6.0/apache-zookeeper-3.6.0-bin.tar.gz, file path:/var/folders/qb/c5lkt6s932s1v2gvx702sqx40000gp/T/zookeeper/apache-zookeeper-3.6.0-bin.tar.gz.
Or you can do something to avoid this problem as below:
1. Download zookeeper binary archive manually regardless of the version
2. Rename the downloaded file named 'apache-zookeeper-{version}-bin.tar.gz' to 'apache-zookeeper-bin.tar.gz'
3. Put the renamed file in /Users/xxxx/.tmp/zookeeper/apache-zookeeper-bin.tar.gz, you maybe need to create the directory if necessary.
```

**Comment by pinxiong** [comment]
> > > not yet，I found that jdk17 test has been added recently. It may be a compatibility problem
> > 
> > 
> > This seems to have no relationship with jdk version, I use jdk8 unit test is also failed, you use jdk8 can pass the unit test?
> > ![image](https://user-images.githubusercontent.com/38206169/148693474-ac04afc9-ecdb-4176-86a3-a33f4bac1b06.png)
> 
> work good use jdk8 local

**Comment by pinxiong** [comment]
@codeimport @juzi214032 you can get more error info.

![image](https://user-images.githubusercontent.com/7067417/148951916-1db99d2f-5565-47fe-abc6-3dbf5d596231.png)

**Comment by codeimport** [comment]
Thank you for your suggestion. I can solve this problem locally, but this problem also exists when submitting PR for workflow. This problem makes my PR unable to pass the workflow. How to solve this problem?
@pinxiong

**Comment by pinxiong** [comment]
@codeimport  Can you provide your PR's workflow?

**Comment by codeimport** [comment]
i found it have fix by chickenlj
