### ISSUE TITLE
Dubbo2.7.13 bean循环依赖导致 nested exception is java.lang.IllegalStateException: <dubbo:service interface="" /> interface not allow null!

### ISSUE THREAD

**Issue by KishoDai** [apache/dubbo#9556]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.13
* Operating System version: macOS Big Sur 11.5.2
* Java version: 1.8

### Steps to reproduce this issue

1. Dubbo Service A depend on Dubbo Service B
2. Dubbo Service B depend on Dubbo Service A

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

no cycle dependency.

### Actual Behavior

Get an error :"<dubbo:service interface="" /> interface not allow null!", if no cyclic dependency, it works fine.

If there is an exception, please attach the exception trace:

```
 nested exception is java.lang.IllegalStateException: <dubbo:service interface="" /> interface not allow null!
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:601)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
		at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
		at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
		at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
		at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1255)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1175)
		at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:521)
		at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:497)
		at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:637)
		at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:180)
		at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
		at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:322)
		... 366 more
```

**Comment by juzi214032** [comment]
What does your xml configuration look like?

**Comment by KishoDai** [comment]
> 

Hi, I used dubbo annotation (not xml) to export dubbo service.

**Comment by KishoDai** [comment]
There is an important point:  Dubbo Service  A and Dubbo Service B are in the same one java process.

**Comment by KishoDai** [comment]
Any feedback?

**Comment by chickenlj** [comment]
请提供示例 demo github 地址，以便复现问题

**Comment by yellowsand1** [comment]
Also encounter this problem frequently , dubbo version 2.7.23 , spring-boot version 2.6.15. I saw a lot feedback about this problem but no fix or solution but add @Lazy to circular referenced bean.This problem wont reproduce everytime but from time to time.
