### ISSUE TITLE
dubbo3.0.6 对Curator5 兼容存在问题？？

### ISSUE THREAD

**Issue by VirensCn** [apache/dubbo#9738]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.6
* Operating System version: win11
* Java version: 17
* Curator Version: 5.2.0

### Steps to reproduce this issue

1. NodeCache.getListenable提示不存在

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Exception in thread "main" java.lang.NoSuchMethodError: 'org.apache.curator.framework.listen.ListenerContainer org.apache.curator.framework.recipes.cache.NodeCache.getListenable()'
	at org.apache.dubbo.remoting.zookeeper.curator.Curator5ZookeeperClient.addTargetDataListener(Curator5ZookeeperClient.java:295)
	at org.apache.dubbo.remoting.zookeeper.curator.Curator5ZookeeperClient.addTargetDataListener(Curator5ZookeeperClient.java:57)
	at org.apache.dubbo.remoting.zookeeper.AbstractZookeeperClient.addDataListener(AbstractZookeeperClient.java:124)
	at org.apache.dubbo.configcenter.support.zookeeper.ZookeeperDynamicConfiguration.doAddListener(ZookeeperDynamicConfiguration.java:134)
	at org.apache.dubbo.common.config.configcenter.TreePathDynamicConfiguration.addListener(TreePathDynamicConfiguration.java:102)
	at org.apache.dubbo.common.config.configcenter.wrapper.CompositeDynamicConfiguration.lambda$addListener$0(CompositeDynamicConfiguration.java:54)
	at org.apache.dubbo.common.config.configcenter.wrapper.CompositeDynamicConfiguration.iterateListenerOperation(CompositeDynamicConfiguration.java:108)
	at org.apache.dubbo.common.config.configcenter.wrapper.CompositeDynamicConfiguration.addListener(CompositeDynamicConfiguration.java:54)
	at org.apache.dubbo.rpc.cluster.governance.DefaultGovernanceRuleRepositoryImpl.addListener(DefaultGovernanceRuleRepositoryImpl.java:36)
	at org.apache.dubbo.rpc.cluster.governance.GovernanceRuleRepository.addListener(GovernanceRuleRepository.java:36)
	at org.apache.dubbo.registry.integration.AbstractConfiguratorListener.initWith(AbstractConfiguratorListener.java:74)
	at org.apache.dubbo.registry.integration.RegistryProtocol$ProviderConfigurationListener.<init>(RegistryProtocol.java:826)
	at org.apache.dubbo.registry.integration.RegistryProtocol.lambda$getProviderConfigurationListener$6(RegistryProtocol.java:793)
	at org.apache.dubbo.common.beans.factory.ScopeBeanFactory.getOrRegisterBean(ScopeBeanFactory.java:146)
	at org.apache.dubbo.common.beans.factory.ScopeBeanFactory.getOrRegisterBean(ScopeBeanFactory.java:136)
	at org.apache.dubbo.registry.integration.RegistryProtocol.getProviderConfigurationListener(RegistryProtocol.java:792)
	at org.apache.dubbo.registry.integration.RegistryProtocol.getProviderConfigurationListener(RegistryProtocol.java:788)
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:233)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:64)
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:58)
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47)
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ServiceConfig.doExportUrl(ServiceConfig.java:632)
	at org.apache.dubbo.config.ServiceConfig.exportRemote(ServiceConfig.java:610)
	at org.apache.dubbo.config.ServiceConfig.exportUrl(ServiceConfig.java:569)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:400)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:386)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:361)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:233)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServiceInternal(DefaultModuleDeployer.java:338)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServices(DefaultModuleDeployer.java:310)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:142)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:111)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:100)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:45)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586)
```

**Comment by VirensCn** [comment]
[#9559](https://github.com/apache/dubbo/pull/9559)  怕是没测试就合并模块了吧？

**Comment by chickenlj** [comment]
抱歉带来curator5兼容性问题。

之前我们专注在 curator5+jdk17 的支持上，为此，中间有段时间我们的curator默认版本升级到了5.x版本，但考虑到默认curator5用户升级的难度与兼容性问题（尤其是与低版本zookeeper server的互操作性），因此后续我们又进行了curator版本回退，在回退过程中jdk8版本编译后的兼容性没覆盖到。


```xml
        <profile>
            <id>curator5</id>
            <activation>
                <jdk>[17,)</jdk>
            </activation>
            <properties>
                <zookeeper_version>3.7.0</zookeeper_version>
                <curator_version>5.1.0</curator_version>
            </properties>
        </profile>
```

我想我们当前可以通过尽快发布新版本来覆盖 curator5 版本的兼容性问题
