### ISSUE TITLE
程序启动成功后，出现序列化问题org.apache.dubbo.common.serialize.hessian2.Hessian2SerializerFactory.getClassFactory()报没有这个方法

### ISSUE THREAD

**Issue by Jimy-Guo** [apache/dubbo#9757]
Caused by: org.apache.dubbo.remoting.RemotingException: io.netty.handler.codec.EncoderException: java.lang.NoSuchMethodError: org.apache.dubbo.common.serialize.hessian2.Hessian2SerializerFactory.getClassFactory()Lcom/alibaba/com/caucho/hessian/io/ClassFactory;
io.netty.handler.codec.EncoderException: java.lang.NoSuchMethodError: org.apache.dubbo.common.serialize.hessian2.Hessian2SerializerFactory.getClassFactory()Lcom/alibaba/com/caucho/hessian/io/ClassFactory;
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:304)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
	at org.apache.dubbo.remoting.transport.netty4.NettyClientHandler.write(NettyClientHandler.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.apache.dubbo.common.serialize.hessian2.Hessian2SerializerFactory.getClassFactory()Lcom/alibaba/com/caucho/hessian/io/ClassFactory;
	at org.apache.dubbo.common.serialize.hessian2.dubbo.DefaultHessian2FactoryInitializer.createSerializerFactory(DefaultHessian2FactoryInitializer.java:28)
	at org.apache.dubbo.common.serialize.hessian2.dubbo.AbstractHessian2FactoryInitializer.getSerializerFactory(AbstractHessian2FactoryInitializer.java:46)
	at org.apache.dubbo.common.serialize.hessian2.Hessian2ObjectOutput.<init>(Hessian2ObjectOutput.java:37)
	at org.apache.dubbo.common.serialize.hessian2.Hessian2Serialization.serialize(Hessian2Serialization.java:51)
	at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.encodeRequest(ExchangeCodec.java:253)
	at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.encode(ExchangeCodec.java:71)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboCountCodec.encode(DubboCountCodec.java:47)
	at org.apache.dubbo.remoting.transport.netty4.NettyCodecAdapter$InternalEncoder.encode(NettyCodecAdapter.java:69)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	... 21 more

	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.doReceived(DefaultFuture.java:214)
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:176)
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:164)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleResponse(HeaderExchangeHandler.java:60)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:181)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor$RunnableWrapper.run(ThreadlessExecutor.java:184)
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:103)
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:193)
	... 109 common frames omitted

**Comment by CrazyHZM** [comment]
Please provide more detailed information such as Dubbo version.
@Jimy-Guo

**Comment by Jimy-Guo** [comment]
springboot-2.3.5.RELEASE

**Comment by Jimy-Guo** [comment]
spring-boot:2.3.5.RELEASE
org.apache.dubbo:dubbo:3.0.6
@CrazyHZM

**Comment by Jimy-Guo** [comment]
原项目：spring-boot:2.3.5.RELEASE+com.alibaba:dubbo:2.6.2+com.alibaba.boot:dubbo-spring-boot-starter:0.2.0
升级到：spring-boot:2.3.5.RELEASE+org.apache.dubbo:dubbo:3.0.6+org.apache.dubbo:dubbo-spring-boot-starter:3.0.6

**Comment by Jimy-Guo** [comment]
@chickenlj 您好，可以帮忙看一下这个问题嘛？是不是关于Hessian2SerializerFactory有什么变动了呢？

**Comment by CrazyHZM** [comment]
@Jimy-Guo 
加上

**Comment by Jimy-Guo** [comment]
> @Jimy-Guo 加上
> 
> ```
>     <dependency>
>         <groupId>org.apache.dubbo</groupId>
>         <artifactId>dubbo-serialization-hessian2</artifactId>
>     </dependency>
> ```
> 
> 试试

万分感谢，除了这个配置之外还要添加
        <dependency>
            <groupId>com.caucho</groupId>
            <artifactId>hessian</artifactId>
            <version>4.0.38</version>
        </dependency>
之前在使用源代码添加获取工厂类方法生成的对应的hessian的class文件把dubbo:3.0.6中的文件替换，但是不成功。原来可以添加另外打包依赖来更换hessian的工厂类。再次感谢。

**Comment by liuwei12931902** [comment]
加了依赖还是没解决

> > @Jimy-Guo 加上
> > ```
> >     <dependency>
> >         <groupId>org.apache.dubbo</groupId>
> >         <artifactId>dubbo-serialization-hessian2</artifactId>
> >     </dependency>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 试试
> 
> 万分感谢，除了这个配置之外还要添加 com.caucho hessian 4.0.38 之前在使用源代码添加获取工厂类方法生成的对应的hessian的class文件把dubbo:3.0.6中的文件替换，但是不成功。原来可以添加另外打包依赖来更换hessian的工厂类。再次感谢。

加了依赖还是报错呢

**Comment by Jimy-Guo** [comment]
> 加了依赖还是没解决
> 
> > > @Jimy-Guo 加上
> > > ```
> > >     <dependency>
> > >         <groupId>org.apache.dubbo</groupId>
> > >         <artifactId>dubbo-serialization-hessian2</artifactId>
> > >     </dependency>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 试试
> > 
> > 
> > 万分感谢，除了这个配置之外还要添加 com.caucho hessian 4.0.38 之前在使用源代码添加获取工厂类方法生成的对应的hessian的class文件把dubbo:3.0.6中的文件替换，但是不成功。原来可以添加另外打包依赖来更换hessian的工厂类。再次感谢。
> 
> 加了依赖还是报错呢

确认一下自己的依赖是不是冲突了
