### ISSUE TITLE
当我想使用dubbo.application.service-discovery.migration=APPLICATION_FIRST双订阅机制时出现报错

### ISSUE THREAD

**Issue by Jimy-Guo** [apache/dubbo#9776]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
Unconditional classes:
----------------------

    org.springframework.boot.autoconfigure.context.ConfigurationPropertiesAutoConfiguration

    org.springframework.boot.autoconfigure.context.LifecycleAutoConfiguration

    org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration

    org.springframework.boot.autoconfigure.availability.ApplicationAvailabilityAutoConfiguration

    org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration

14:26:46.189 ERROR [main] o.springframework.boot.SpringApplication:837 - Application run failed
java.lang.NullPointerException: null
	at org.apache.dubbo.metadata.MetadataInfo.init(MetadataInfo.java:122)
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.getRemoteMetadata(AbstractServiceDiscovery.java:164)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.doOnEvent(ServiceInstancesChangedListener.java:155)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.onEvent(ServiceInstancesChangedListener.java:113)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribeURLs(ServiceDiscoveryRegistry.java:312)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.doSubscribe(ServiceDiscoveryRegistry.java:216)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribe(ServiceDiscoveryRegistry.java:184)
	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:111)
	at org.apache.dubbo.registry.integration.DynamicDirectory.subscribe(DynamicDirectory.java:180)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.subscribe(ServiceDiscoveryRegistryDirectory.java:107)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doCreateInvoker(RegistryProtocol.java:569)
	at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getServiceDiscoveryInvoker(InterfaceCompatibleRegistryProtocol.java:65)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshServiceDiscoveryInvoker(MigrationInvoker.java:428)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToApplicationFirstInvoker(MigrationInvoker.java:244)
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.refreshInvoker(MigrationRuleHandler.java:73)
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:57)
	at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:241)
	at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:534)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:504)
	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:486)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:74)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:83)
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:71)
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:52)
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ReferenceConfig.createInvokerForRemote(ReferenceConfig.java:493)
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:396)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:279)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:219)
	at org.apache.dubbo.config.utils.SimpleReferenceCache.get(SimpleReferenceCache.java:110)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:384)
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:364)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:151)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:111)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:100)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:45)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:898)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at com.clife.family.sports.api.web.ClifeFamilySportsApiWebApplication.main(ClifeFamilySportsApiWebApplication.java:22)
但是，当我把订阅指向为接口唯一FORCE_INTERFACE时，程序能够正常运行并完成预想效果。
这是为什么呢？是应用级还需要其他什么配置嘛？

**Comment by BurningCN** [comment]
默认情况下，不做特殊配置，就是双注册和双订阅。从日志看已经走双订阅的逻辑了，接口级别订阅已经成功了，应用级别发生了空指针，不过空指针触发的位置有点奇怪，你可以再检查一下，或者可以贴一下你的示例代码和配置信息，我试下能否复现

**Comment by chickenlj** [comment]
请先检查与定位为什么出现了 metadata 为空的情况

**Comment by chickenlj** [comment]
可能和缓存加载有关，从缓存加载的 Metadata 存在 initiated 没正确初始化的情况

**Comment by chickenlj** [comment]
传输Metadata过程中有配置特定协议吗？

**Comment by Jimy-Guo** [comment]
> 传输Metadata过程中有配置特定协议吗？用的dubbo哪个版本

使用了dubbo协议+dubbo3.0.6

**Comment by Jimy-Guo** [comment]
是消费端，在开发过程中能正常运行并调用服务，但是启动程序调试多次之后会出现这种情况

**Comment by Jimy-Guo** [comment]
后面发现在本地启动时偶尔会出现这个问题，但是在docker容器中却没有出现，检查了两者差别之后发现
`injvm://127.0.0.1/org.apache.dubbo.metadata.MetadataService?anyhost=true&application=clife-family-sports-async&background=false&bind.ip=***&bind.port=20881&connections=1&delay=0&deprecated=false&dubbo=2.0.2&dynamic=true&executes=100&generic=false&group=clife-family-sports-async&interface=org.apache.dubbo.metadata.MetadataService&metadata-type=remote&methods=getMetadataURL,isMetadataService,getExportedURLs,serviceName,version,getSubscribedURLs,getExportedServiceURLs,getMetadataInfo,toSortedStrings,getMetadataInfos,getServiceDefinition&pid=2840&qos.accept.foreign.ip=false&qos.enable=false&register-mode=all&release=3.0.6&revision=3.0.6&side=provider&timestamp=1647920490682&version=1.0.0, dubbo version: 3.0.6, current host: ****`
有个服务org.apache.dubbo.metadata.MetadataService是否需要手动设置ConsumerConfig.Injvm为true,才能启动成功呢。
有尝试过其他方法，但那都是随机启动时报错
`java.lang.NullPointerException: null
	at org.apache.dubbo.metadata.MetadataInfo.init(MetadataInfo.java:122)`

**Comment by chickenlj** [comment]
Cannot reproduce
