### ISSUE TITLE
dubbo3.0.6 Exceptions are thrown by two local project startup consoles, but the call between Dubbo is not affected.Exception：Failed to create file store cache. Local file cache will be disabled

### ISSUE THREAD

**Issue by huangyanlin1** [apache/dubbo#9800]
2022-03-17 14:58:15,844 INFO o.a.d.c.c.FileCacheStoreFactory [main]  [DUBBO] Failed to create file store cache. Local file cache will be disabled. Cache file name: C:\Users\Administrator\.dubbo\.metadata.nacos10.79.4.151%003a8815.dubbo.cache, dubbo version: 3.0.6, current host: 10.108.81.111
org.apache.dubbo.common.cache.FileCacheStoreFactory$PathNotExclusiveException: C:\Users\Administrator\.dubbo\.metadata.nacos10.79.4.151%003a8815.dubbo.cache is not exclusive.
	at org.apache.dubbo.common.cache.FileCacheStoreFactory.tryFileLock(FileCacheStoreFactory.java:149) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.common.cache.FileCacheStoreFactory.getFile(FileCacheStoreFactory.java:115) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.common.cache.FileCacheStoreFactory.lambda$getInstance$0(FileCacheStoreFactory.java:82) ~[dubbo-3.0.6.jar:3.0.6]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_261]
	at org.apache.dubbo.common.cache.FileCacheStoreFactory.getInstance(FileCacheStoreFactory.java:82) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.metadata.AbstractCacheManager.init(AbstractCacheManager.java:47) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.registry.client.metadata.store.MetaCacheManager.<init>(MetaCacheManager.java:59) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.<init>(AbstractServiceDiscovery.java:81) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.<init>(AbstractServiceDiscovery.java:64) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.registry.nacos.NacosServiceDiscovery.<init>(NacosServiceDiscovery.java:59) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.registry.nacos.NacosServiceDiscoveryFactory.createDiscovery(NacosServiceDiscoveryFactory.java:27) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.registry.client.AbstractServiceDiscoveryFactory.lambda$getServiceDiscovery$0(AbstractServiceDiscoveryFactory.java:53) ~[dubbo-3.0.6.jar:3.0.6]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_261]
	at org.apache.dubbo.registry.client.AbstractServiceDiscoveryFactory.getServiceDiscovery(AbstractServiceDiscoveryFactory.java:53) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.getServiceDiscovery(ServiceDiscoveryRegistry.java:122) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.createServiceDiscovery(ServiceDiscoveryRegistry.java:109) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.<init>(ServiceDiscoveryRegistry.java:86) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryFactory.createRegistry(ServiceDiscoveryRegistryFactory.java:35) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:89) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.registry.RegistryFactoryWrapper.getRegistry(RegistryFactoryWrapper.java:33) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:392) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getServiceDiscoveryInvoker(InterfaceCompatibleRegistryProtocol.java:63) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshServiceDiscoveryInvoker(MigrationInvoker.java:428) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToApplicationFirstInvoker(MigrationInvoker.java:244) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.refreshInvoker(MigrationRuleHandler.java:73) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:57) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:241) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:534) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:504) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:486) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:83) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:74) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:71) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:52) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.config.ReferenceConfig.createInvokerForRemote(ReferenceConfig.java:493) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:396) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:279) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:219) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.config.utils.SimpleReferenceCache.get(SimpleReferenceCache.java:110) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:384) ~[dubbo-3.0.6.jar:3.0.6]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_261]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:364) [dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:151) [dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:111) [dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:100) [dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:45) [dubbo-3.0.6.jar:3.0.6]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) [spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) [spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) [spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) [spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) [spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938) [spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) [spring-context-5.3.13.jar:5.3.13]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) [spring-boot-2.5.7.jar:2.5.7]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:765) [spring-boot-2.5.7.jar:2.5.7]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:445) [spring-boot-2.5.7.jar:2.5.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) [spring-boot-2.5.7.jar:2.5.7]
	at com.csair.consumer.ConsumerClientApplication.main(ConsumerClientApplication.java:27) [classes/:?]

**Comment by CrazyHZM** [comment]
@huangyanlin1 
1.Check if you have permission to create the file
2.If you don't want to cache local files, you can configure the following configuration to close: 
```
dubbo:
  application:
    enable-file-cache: false
```

**Comment by chickenlj** [comment]
Just ignore this warning exception if were having two processes running on the same machine.

**Comment by huangyanlin1** [comment]
![Uploading 截图.png…]()
This file is generated after the first project is started, and this file is also generated when the second project is started, which leads to this exception. Now I think it should be the problem of file name, rather than identifying consumer and privoder respectively like other files. What should I do with this file name?

**Comment by wslzs** [comment]
@CrazyHZM [CrazyHZM](https://github.com/CrazyHZM) But the MAC system cannot be created '.dubbo' file,MacOS compatibility is recommended

**Comment by wangliuliu1115** [comment]
> [@CrazyHZM](https://github.com/CrazyHZM) [CrazyHZM](https://github.com/CrazyHZM) But the MAC system cannot be created '.dubbo' file,MacOS compatibility is recommended

Especially when multiple providers are required for load balancing, the file lock contention issue is inevitable.
