### ISSUE TITLE
dubbo3+triple协议提示 【 reject to deserialize! Expected】

### ISSUE THREAD

**Issue by luger1990** [apache/dubbo#9816]
dubbo3 使用triple协议，消费者启动失败提示如下错误:
```
org.apache.dubbo.rpc.RpcException: Received inconsistent serialization type from client, reject to deserialize! Expected:hessian2 Actual:luger
	at org.apache.dubbo.rpc.protocol.tri.AbstractClientStream.getThrowableFromTrailers(AbstractClientStream.java:188) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.rpc.protocol.tri.UnaryClientStream$ClientUnaryInboundTransportObserver.onError(UnaryClientStream.java:86) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.rpc.protocol.tri.UnaryClientStream$ClientUnaryInboundTransportObserver.lambda$onComplete$0(UnaryClientStream.java:56) ~[dubbo-3.0.6.jar:3.0.6]
	at org.apache.dubbo.common.threadpool.serial.SerializingExecutor.run(SerializingExecutor.java:99) ~[dubbo-3.0.6.jar:3.0.6]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_161]
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41) ~[dubbo-3.0.6.jar:3.0.6]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
```

启动生产者和消费者之后访问:http://localhost:8882/hello?name=luger
详见:https://gitee.com/luger/spring-boot-dubbo-grpc/tree/feature_tri/

nacos版本 2.0.4

**Comment by guohao** [comment]
已知问题，会在3.0.7 fix，可以先尝试用3.0 分支的 3.0.7-SNAPSHOT

**Comment by luger1990** [comment]
> 已知问题，会在3.0.7 fix，可以先尝试用3.0 分支的 3.0.7-SNAPSHOT

另外问一下dubbo3目前生产环境可用吗？

**Comment by guohao** [comment]
@luger1990 这个问题应该已经修复了，可以试下

**Comment by luger1990** [comment]
> @luger1990 这个问题应该已经修复了，可以试下

多谢！我试试  另外现在生产环境用可以了不？

**Comment by guohao** [comment]
> > @luger1990 这个问题应该已经修复了，可以试下
> 
> 多谢！我试试 另外现在生产环境用可以了不？

建议等这周3.0.7 发布后升级到正式版本部署生产
