### ISSUE TITLE
3.0.7 grpc+register-mode: instance 提示 Failed to check the status of the serviceXXX

### ISSUE THREAD

**Issue by luger1990** [apache/dubbo#9879]
3.0.7 grpc+register-mode: instance 提示 Failed to check the status of the serviceXXX
```
java.lang.IllegalStateException: Failed to check the status of the service me.luger.dubbo3.entity.DubboGreeterGrpc$IGreeter. No provider available for the service me.luger.dubbo3.entity.DubboGreeterGrpc$IGreeter from the url consumer://172.17.2.187/me.luger.dubbo3.entity.DubboGreeterGrpc$IGreeter?application=dubbo-grpc-consumer&background=false&dubbo=2.0.2&interface=me.luger.dubbo3.entity.DubboGreeterGrpc$IGreeter&methods=sayHello,sayHelloAsync&pid=17640&qos.enable=false&register-mode=instance&register.ip=172.17.2.187&release=3.0.7&side=consumer&sticky=false&timestamp=1648829384975 to the consumer 172.17.2.187 use dubbo version 3.0.7
	at org.apache.dubbo.config.ReferenceConfig.checkInvokerAvailable(ReferenceConfig.java:545) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:293) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:219) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.config.utils.SimpleReferenceCache.get(SimpleReferenceCache.java:110) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:387) ~[dubbo-3.0.7.jar:3.0.7]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) ~[na:1.8.0_161]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:367) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:154) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:111) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:100) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:45) ~[dubbo-3.0.7.jar:3.0.7]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.16.jar:5.3.16]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.16.jar:5.3.16]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.16.jar:5.3.16]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.16.jar:5.3.16]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.16.jar:5.3.16]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938) ~[spring-context-5.3.16.jar:5.3.16]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.16.jar:5.3.16]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164) [spring-boot-2.6.4.jar:2.6.4]
	at me.luger.consumer.DubboGrpcConsumerApplication.main(DubboGrpcConsumerApplication.java:12) [classes/:na]
```

详见:https://gitee.com/luger/spring-boot-dubbo-grpc.git

**Comment by chickenlj** [comment]
消费端配置一下
dubbo.consumer.protocol=grpc
或者
配置在 reference 上也行

**Comment by luger1990** [comment]
> 消费端配置一下 dubbo.consumer.protocol=grpc 或者 配置在 reference 上也行

貌似正确的配置方法是:
```
dubbo:
  protocol:
    name: grpc
    #    port: 20888
    id: grpc
    accesslog: false
  consumer:
    parameters:
      protocol: grpc
```
