### ISSUE TITLE
Server returned HTTP response code: 500 for URL: http://nacos.example.com:31000/nacos/v1/cs/configs

### ISSUE THREAD

**Issue by ytqiao3** [apache/dubbo#9880]
nacos server 版本： 2.0.3
dubbo版本：3.0.6
配置好dubbo启动之后控制台报出异常如下，但是查看nacos控制台发现服务已经注册上来：
2022-04-02 09:46:52.901 ERROR 17836 --- [Report-thread-1] c.a.n.c.config.http.ServerHttpAgent      : [NACOS Exception httpPost] currentServerAddr: http://nacos.example.com:31000

java.io.IOException: Server returned HTTP response code: 500 for URL: http://nacos.example.com:31000/nacos/v1/cs/configs
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_301]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_301]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_301]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_301]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1950) ~[na:1.8.0_301]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1945) ~[na:1.8.0_301]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_301]
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1944) ~[na:1.8.0_301]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1514) ~[na:1.8.0_301]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[na:1.8.0_301]
	at com.alibaba.nacos.common.http.client.response.JdkHttpClientResponse.getBody(JdkHttpClientResponse.java:64) ~[nacos-common-1.4.2.jar:na]
	at com.alibaba.nacos.common.http.client.handler.AbstractResponseHandler.handleError(AbstractResponseHandler.java:51) ~[nacos-common-1.4.2.jar:na]
	at com.alibaba.nacos.common.http.client.handler.AbstractResponseHandler.handle(AbstractResponseHandler.java:44) ~[nacos-common-1.4.2.jar:na]
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:483) ~[nacos-common-1.4.2.jar:na]
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.postForm(NacosRestTemplate.java:407) ~[nacos-common-1.4.2.jar:na]
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:155) ~[nacos-client-1.4.2.jar:na]
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:67) [nacos-client-1.4.2.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.publishConfigInner(NacosConfigService.java:267) [nacos-client-1.4.2.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.publishConfig(NacosConfigService.java:123) [nacos-client-1.4.2.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.publishConfig(NacosConfigService.java:118) [nacos-client-1.4.2.jar:na]
	at org.apache.dubbo.metadata.store.nacos.NacosConfigServiceWrapper.publishConfig(NacosConfigServiceWrapper.java:57) [dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.metadata.store.nacos.NacosMetadataReport.storeMetadata(NacosMetadataReport.java:291) [dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.metadata.store.nacos.NacosMetadataReport.doStoreProviderMetadata(NacosMetadataReport.java:169) [dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.metadata.report.support.AbstractMetadataReport.storeProviderMetadataTask(AbstractMetadataReport.java:261) [dubbo-metadata-api-3.0.5.jar:3.0.5]
	at org.apache.dubbo.metadata.report.support.AbstractMetadataReport.lambda$storeProviderMetadata$0(AbstractMetadataReport.java:248) [dubbo-metadata-api-3.0.5.jar:3.0.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_301]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_301]
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://nacos.example.com:31000/nacos/v1/cs/configs
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900) ~[na:1.8.0_301]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[na:1.8.0_301]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_301]
	at com.alibaba.nacos.common.http.client.response.JdkHttpClientResponse.getStatusCode(JdkHttpClientResponse.java:79) ~[nacos-common-1.4.2.jar:na]
	at com.alibaba.nacos.common.http.client.handler.AbstractResponseHandler.handle(AbstractResponseHandler.java:43) ~[nacos-common-1.4.2.jar:na]
	... 15 common frames omitted

**Comment by wuwangben** [comment]
遇到同样的问题
服务端报错：
![image](https://user-images.githubusercontent.com/16200775/161421059-af6d1191-ff8f-42b0-9ac7-d818a7b2f161.png)

**Comment by chickenlj** [comment]
首先，以上是运维 metadata 数据的上报逻辑，报错并不影响服务注册和进程正常运行。

至于这个异常，需要提报到 Nacos 社区进一步的排查原因。
