### ISSUE TITLE
3.0.7 dubbo.cache is not exclusive.

### ISSUE THREAD

**Issue by xtuul** [apache/dubbo#9891]
spring boot 2.6.6
nacos 2.0.4
dubbo 3.0.7

provider启动正常
consumer启动时报如下错误：
```
2022-04-03 16:27:28.360  INFO 33240 --- [           main] o.a.d.c.cache.FileCacheStoreFactory      :  [DUBBO] Failed to create file store cache. Local file cache will be disabled. Cache file name: C:\Users\liguo\.dubbo\.metadata.nacos127.0.0.1%003a8848.dubbo.cache, dubbo version: 3.0.7, current host: 192.168.137.1

org.apache.dubbo.common.cache.FileCacheStoreFactory$PathNotExclusiveException: C:\Users\liguo\.dubbo\.metadata.nacos127.0.0.1%003a8848.dubbo.cache is not exclusive.
	at org.apache.dubbo.common.cache.FileCacheStoreFactory.tryFileLock(FileCacheStoreFactory.java:149) [dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.common.cache.FileCacheStoreFactory.getFile(FileCacheStoreFactory.java:115) [dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.common.cache.FileCacheStoreFactory.lambda$getInstance$0(FileCacheStoreFactory.java:82) [dubbo-3.0.7.jar:3.0.7]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_311]
	at org.apache.dubbo.common.cache.FileCacheStoreFactory.getInstance(FileCacheStoreFactory.java:82) [dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.metadata.AbstractCacheManager.init(AbstractCacheManager.java:47) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.registry.client.metadata.store.MetaCacheManager.<init>(MetaCacheManager.java:59) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.<init>(AbstractServiceDiscovery.java:85) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.<init>(AbstractServiceDiscovery.java:66) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.registry.nacos.NacosServiceDiscovery.<init>(NacosServiceDiscovery.java:59) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.registry.nacos.NacosServiceDiscoveryFactory.createDiscovery(NacosServiceDiscoveryFactory.java:27) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.registry.client.AbstractServiceDiscoveryFactory.lambda$getServiceDiscovery$0(AbstractServiceDiscoveryFactory.java:53) ~[dubbo-3.0.7.jar:3.0.7]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_311]
	at org.apache.dubbo.registry.client.AbstractServiceDiscoveryFactory.getServiceDiscovery(AbstractServiceDiscoveryFactory.java:53) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.getServiceDiscovery(ServiceDiscoveryRegistry.java:122) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.createServiceDiscovery(ServiceDiscoveryRegistry.java:109) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.<init>(ServiceDiscoveryRegistry.java:86) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryFactory.createRegistry(ServiceDiscoveryRegistryFactory.java:35) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:89) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.registry.RegistryFactoryWrapper.getRegistry(RegistryFactoryWrapper.java:33) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:393) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getServiceDiscoveryInvoker(InterfaceCompatibleRegistryProtocol.java:63) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshServiceDiscoveryInvoker(MigrationInvoker.java:428) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToApplicationFirstInvoker(MigrationInvoker.java:244) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.refreshInvoker(MigrationRuleHandler.java:73) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:57) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:243) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:535) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:505) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:487) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:83) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:74) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:71) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:52) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.config.ReferenceConfig.createInvokerForRemote(ReferenceConfig.java:494) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:397) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:285) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:219) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.config.utils.SimpleReferenceCache.get(SimpleReferenceCache.java:110) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:387) ~[dubbo-3.0.7.jar:3.0.7]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) ~[na:1.8.0_311]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:367) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:154) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:111) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:100) ~[dubbo-3.0.7.jar:3.0.7]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:45) ~[dubbo-3.0.7.jar:3.0.7]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.6.jar:2.6.6]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) ~[spring-boot-2.6.6.jar:2.6.6]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) ~[spring-boot-2.6.6.jar:2.6.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-2.6.6.jar:2.6.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[spring-boot-2.6.6.jar:2.6.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.6.jar:2.6.6]
	at org.liguo.dubbo.consumer.ConsumerApplication.main(ConsumerApplication.java:13) ~[classes/:na]
```

dubbo 3.0.5 没有这样的问题！
@chickenlj

**Comment by wslzs** [comment]
我也遇到了同样的问题，我用的是mac系统
![image](https://user-images.githubusercontent.com/35302223/161479885-afcbae55-f381-4d90-89cb-c19c3e799fd9.png)

**Comment by wslzs** [comment]
![image](https://user-images.githubusercontent.com/35302223/161480002-7aa6b8aa-0c4d-4726-92f6-0c7cb1960191.png)

**Comment by CrazyHZM** [comment]
@wslzs @xtuul 
Refer to the discussion of this issue: https://github.com/apache/dubbo/issues/9800

**Comment by xtuul** [comment]
> Refer to the discussion of this issue: https://github.com/apache/dubbo/issues/9800

和我提的问题一样的

在这两个问题的回复当中：
1.  并没有给出明确的解决办法
2. 此问题为什么在3.0.5没有问题，而且在3.0.6，3.0.7出现呢？
3. 目前微服务部署的情况下，在一台机器上运行多个dubbo很正常的！只是忽略这个异常信息就这也一种解决办法吗？有没有更优雅的解决方式吗？

@CrazyHZM @chickenlj

**Comment by HeyChiang** [comment]
@xtuul 前面他回答了，意思就是你别管就行了...

**Comment by chiangho** [comment]
通过查看源码做如下配置，修改他的缓存存储目录
dubbo.mapping.cache.filePath


下面这段是源码
 public MappingCacheManager(String name, ScheduledExecutorService executorService) {
        String filePath = System.getProperty("dubbo.mapping.cache.filePath");
        String fileName = System.getProperty("dubbo.mapping.cache.fileName");
        if (StringUtils.isEmpty(fileName)) {
            fileName = DEFAULT_FILE_NAME;
        }

        if (StringUtils.isNotEmpty(name)) {
            fileName = fileName + "." + name;
        }

        String rawEntrySize = System.getProperty("dubbo.mapping.cache.entrySize");
        int entrySize = StringUtils.parseInteger(rawEntrySize);
        entrySize = (entrySize == 0 ? DEFAULT_ENTRY_SIZE : entrySize);

        String rawMaxFileSize = System.getProperty("dubbo.mapping.cache.maxFileSize");
        long maxFileSize = StringUtils.parseLong(rawMaxFileSize);

        init(filePath, fileName, entrySize,  maxFileSize, 50, executorService);
    }

**Comment by aguu125** [comment]
区分开文件地址，我是启动的时候直接配置了目录是jar包目录，
`
public static void main(String[] args) {
        ApplicationHome home = new ApplicationHome(Dubbo3ConsumerApplication.class);
        File jarFile = home.getSource();
        String dirPath = jarFile.getParentFile().toString();
        String filePath = dirPath + File.separator + ".dubbo";
        System.out.println(filePath);

        System.setProperty("dubbo.meta.cache.filePath", filePath);
        System.setProperty("dubbo.mapping.cache.filePath",filePath);

        //
        SpringApplication.run(Dubbo3ConsumerApplication.class, args);
    }
`

**Comment by js20166098** [comment]
和nacos单机启动集群问题类似，如果想要启动的话idea可以配置环境变量
user.home=/Users/mac/dubbo/provider
![image](https://user-images.githubusercontent.com/56857589/183912983-0a64f6d8-f7cb-40a0-b161-5aacbd6d22e1.png)
对应每个的这个环境配置不一样就可以了

**Comment by chang-shuai** [comment]
> 和nacos单机启动集群问题类似，如果想要启动的话idea可以配置环境变量 user.home=/Users/mac/dubbo/provider ![image](https://user-images.githubusercontent.com/56857589/183912983-0a64f6d8-f7cb-40a0-b161-5aacbd6d22e1.png) 对应每个的这个环境配置不一样就可以了

指定了没效果, 包括关掉 本地缓存 也没效果
```
dubbo:
  application:
    enable-file-cache: false
```
使用 -Duser.home=xxx 后就不报错了

**Comment by albert-get** [comment]
把.dubbo下的文件清空一下再启动就不会报这个问题，可能是1换到2cache文件格式不兼容

**Comment by xiaoming-student** [comment]
> 把.dubbo下的文件清空一下再启动就不会报这个问题，可能是1换到2cache文件格式不兼容

66666

**Comment by Feiyizhan** [comment]
修改启动方法，设置应用启动时修改缓存目录增加应用名子目录。
```java
    public static void main(String[] args) {
        // 创建SpringApplication实例
        SpringApplication application = new SpringApplication(Application.class);
        // 添加自定义的ApplicationContextInitializer
        application.addInitializers(context -> {
            // 获取Environment对象
            Environment env = context.getEnvironment();
            // 从Environment中读取"spring.application.name"属性值
            String appName = env.getProperty("spring.application.name");
            String filePath = System.getProperty("user.home") + File.separator + ".dubbo" +File.separator + appName;
            // 修改dubbo的本地缓存路径，避免缓存冲突
            System.setProperty("dubbo.meta.cache.filePath", filePath);
            System.setProperty("dubbo.mapping.cache.filePath",filePath);
        });
        //启动应用
        application.run(args);
    }
```
