### ISSUE TITLE
分组聚合时，consumer只消费应用级地址时无法调用

### ISSUE THREAD

**Issue by cr6588** [apache/dubbo#9903]
### Environment

* Dubbo version: 3.0.7
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue

1. dubbo-samples中的dubbo-samples-merge项目 https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-merge
2. 更改zk后直接启动2个provider
3. 启动dubbo-samples-merge-consumer增加-Ddubbo.application.service-discovery.migration=FORCE_APPLICATION
4. 若不增加-D参数正常启动
### Expected Behavior

启动正常调用

### Actual Behavior
```
java.lang.IllegalStateException: Failed to check the status of the service org.apache.dubbo.samples.merge.api.MergeService. No provider available for the service */org.apache.dubbo.samples.merge.api.MergeService from the url consumer://192.168.1.57/org.apache.dubbo.samples.merge.api.MergeService?application=merge-consumer&background=false&dubbo=2.0.2&group=*&interface=org.apache.dubbo.samples.merge.api.MergeService&merger=true&methods=mergeResult&pid=33928&register.ip=192.168.1.57&release=3.0.7&side=consumer&sticky=false&timestamp=1649319338193 to the consumer 192.168.1.57 use dubbo version 3.0.7
	at org.apache.dubbo.config.ReferenceConfig.checkInvokerAvailable(ReferenceConfig.java:545)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:293)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:219)
```
####

**Comment by chickenlj** [comment]
This is a known issue, merge feature is currently not supported on 3.0 branch.
