### ISSUE TITLE
提供者设置 payload ，消费者通过泛化调用的使用问题！

### ISSUE THREAD

**Issue by Suremotoo** [apache/dubbo#9914]
由于业务数据包略大，故在 provider 里设置了：`<dubbo:provider payload="83886080"/>`

消费者通过泛化调用 provider 时，业务数据中，有某一字段略大，约为 27Mb， 最终请求时却提示超出限制

```
Caused by: org.apache.dubbo.remoting.transport.ExceedPayloadLimitException: Data length too large: 108336587, max payload: 83886080, channel: NettyChannel [channel=[id: 0x8b0d68ea, L:/127.0.0.1:50214 - R:/127.0.0.1:20882]]
        at org.apache.dubbo.remoting.transport.AbstractCodec.checkPayload(AbstractCodec.java:50)
        at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.encodeRequest(ExchangeCodec.java:247)
        at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.encode(ExchangeCodec.java:69)
        at org.apache.dubbo.rpc.protocol.dubbo.DubboCountCodec.encode(DubboCountCodec.java:40)
        at org.apache.dubbo.remoting.transport.netty4.NettyCodecAdapter$InternalEncoder.encode(NettyCodecAdapter.java:70)
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
        ... 23 more
````

看异常信息，难道是因为会 encode 所以才导致最终请求数据包变大吗？为何会大出如此之多？ 108336587 byte 约为 108M 了!

如果不使用泛化调用，相同的业务数据则可以成功调用。

**Comment by Suremotoo** [comment]
sorry, I found the reason. It's a code problem.

**Comment by amosnothing** [comment]
想问一下，consumer 通过泛化调用是怎么设置 payload 大小的 ？
