### ISSUE TITLE
 [DUBBO] Failed to load service metadata, meta type is local, dubbo version: 3.0.5, current host: 192.168.0.144

### ISSUE THREAD

**Issue by thousmile** [apache/dubbo#9955]
2022-04-22 14:57:16.757 ERROR 7152 --- [      main] .r.c.e.l.ServiceInstancesChangedListener :  [DUBBO] Failed to load service metadata, meta type is local, dubbo version: 3.0.5, current host: 192.168.0.144

org.apache.dubbo.rpc.RpcException: Fail to create remoting client for service(dubbo://192.168.0.144:16610/org.apache.dubbo.metadata.MetadataService?codec=dubbo&connections=1&dubbo=2.0.2&group=oauth2-server&heartbeat=60000&port=16610&protocol=dubbo&release=3.0.7&side=provider&timeout=5000&version=1.0.0): client(url: dubbo://192.168.0.144:16610/org.apache.dubbo.metadata.MetadataService?codec=dubbo&connections=1&dubbo=2.0.2&group=oauth2-server&heartbeat=60000&port=16610&protocol=dubbo&release=3.0.7&side=provider&timeout=5000&version=1.0.0) failed to connect to server /192.168.0.144:16610, error message is:Connection refused: no further information: /192.168.0.144:16610
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.initClient(DubboProtocol.java:650)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getClients(DubboProtocol.java:462)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.protocolBindingRefer(DubboProtocol.java:430)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.refer(DubboProtocol.java:421)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:85)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:77)
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:74)
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:52)
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)

Same code, no problem in dubbo 3.0.4!

Although the error is reported, it is strange that it can work normally

**Comment by 106umao** [comment]
How to reproduce?

**Comment by chickenlj** [comment]
这里有两个问题：
1. error message is:Connection refused: no further information: /192.168.0.144:16610 这个问题看起来是 dubbo 尝试初始化 metadata 的时候对端provider连接出现问题
2. Although the error is reported, it is strange that it can work normally。Dubbo框架自动切到了接口级别的地址在工作

**Comment by chickenlj** [comment]
重点排查第一个问题，看起来并不是一个通用问题。
