### ISSUE TITLE
2.7.12 集群模式调用下的Invalid token

### ISSUE THREAD

**Issue by tonydzt** [apache/dubbo#9962]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.12
* Operating System version: Linux 3.10.0-1160.11.1.el7.x86_64
* Java version: 1.8

### Steps to reproduce this issue

1. consumer 注解配置@DubboReference (cluster = "broadcast2")，使用广播模式调用provider
2. provider共四台机器
3. consumer调用provider，偶发以下"Invalid token"的报错，频率大概在1/100，并且报错时是4台provider机器同时报错。

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior
广播模式正常调用

### Actual Behavior
广播模式下调用，偶发"Invalid token"报错，频率大概在1/100

If there is an exception, please attach the exception trace:

```
ERROR o.a.d.rpc.filter.ExceptionFilter 107 -  [DUBBO] Got unchecked and undeclared exception which called by xxx. service: xxx, exception: org.apache.dubbo.rpc.RpcException: Invalid token! Forbid invoke remote service interface xxx from consumer xxx to provider xxx, consumer incorrect token is null, dubbo version: 2.7.12, current host: xxx
org.apache.dubbo.rpc.RpcException: Invalid token! Forbid invoke remote service interface xxx from consumer xxx to provider xxx, consumer incorrect token is null
	at org.apache.dubbo.rpc.filter.TokenFilter.invoke(TokenFilter.java:52)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at org.apache.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:46)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke$original$aVrbLpER(MonitorFilter.java:91)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke$original$aVrbLpER$accessor$gwUhLDHz(MonitorFilter.java)
	at org.apache.dubbo.monitor.support.MonitorFilter$auxiliary$L23vUzoz.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at org.apache.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:52)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:189)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:41)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at org.apache.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:129)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:146)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:100)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:175)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by AlbumenJ** [comment]
这个应该是集群调用模式下 rpcInvocation 共享了，invocation 中的 attachemnt 是 HashMap 不能并发修改的，可以考虑在 broadcast 集群模式中加入 rpcInvocation 重建的逻辑

**Comment by tonydzt** [comment]
根据建议使用SPI自定义了一个BroadcastClusterInvoker，在其中的每个异步线程里对rpcInvocation进行了重建，测试结果表明确实解决了这个问题

**Comment by acmday** [comment]
pleas assign this to me

**Comment by acmday** [comment]
Please assign this issue to me

**Comment by hjh7516** [comment]
![#9962](https://user-images.githubusercontent.com/33256886/170234736-eea28b0c-dc2e-4f06-988b-6a9461fc84d2.jpg)
@AlbumenJ 通过代码跟踪可以发现，出现这个问题是因为在DubboInvoker#invoke方法中RpcInvocation对象在写入attachment值时使用的是addObjectAttachmentsIfAbsent方法，那么在RpcInvocation共享的情况下这个token就不会被重新设置值，是否可以考虑修改这个地方，这样就不需要在集群容错类中重建RpcInvocation呢
