### ISSUE TITLE
dubbo3 使用多注册中心时如果配置相同则会报错另一个注册中心未注册成功

### ISSUE THREAD

**Issue by YuWan1117** [apache/dubbo#9976]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

#### 配置信息介绍
如下配置，定义了两个注册中心（`common`和`another`），其中他们的配置信息除了default字段不同外，其他字段相同：
```
dubbo:
  registries:
    common:
      address: 10.70.7.11:2181
      protocol: zookeeper
      default: true
    another:
      address: 10.70.7.11:2181
      protocol: zookeeper
      default: false
```
#### 基于Dubbo2使用的情况
> provider端服务启动后，上述配置中的`common`和`another`均注册成功。
#### 基于Dubbo3使用的情况
> provider端服务启动后，上述配置中的`common`注册成功，但是`another`提示"java.lang.IllegalStateException: Registry not found: another"

**Note:本地使用的3.0.4版本**

```
2022-04-27 12:08:43,850 ERROR (DefaultModuleDeployer.java:330) -  [DUBBO] Dubbo module[1.1.1] refer catch error, dubbo version: 3.0.4, current host: 172.16.xx.xx
java.lang.IllegalStateException: Registry not found: another
	at org.apache.dubbo.config.AbstractInterfaceConfig.lambda$convertRegistryIdsToRegistries$5(AbstractInterfaceConfig.java:465) ~[dubbo-3.0.4.kk-20211119.020408-2.jar:3.0.4]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_211]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_211]
	at org.apache.dubbo.config.AbstractInterfaceConfig.convertRegistryIdsToRegistries(AbstractInterfaceConfig.java:459) ~[dubbo-3.0.4.kk-20211119.020408-2.jar:3.0.4]
	at org.apache.dubbo.config.AbstractInterfaceConfig.checkRegistry(AbstractInterfaceConfig.java:244) ~[dubbo-3.0.4.kk-20211119.020408-2.jar:3.0.4]
	at org.apache.dubbo.config.ReferenceConfig.aggregateUrlFromRegistry(ReferenceConfig.java:445) ~[dubbo-3.0.4.kk-20211119.020408-2.jar:3.0.4]
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:376) ~[dubbo-3.0.4.kk-20211119.020408-2.jar:3.0.4]
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:266) ~[dubbo-3.0.4.kk-20211119.020408-2.jar:3.0.4]
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:203) ~[dubbo-3.0.4.kk-20211119.020408-2.jar:3.0.4]
	at org.apache.dubbo.config.utils.SimpleReferenceCache.get(SimpleReferenceCache.java:117) ~[dubbo-3.0.4.kk-20211119.020408-2.jar:3.0.4]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:326) ~[dubbo-3.0.4.kk-20211119.020408-2.jar:3.0.4]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_211]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:306) [dubbo-3.0.4.kk-20211119.020408-2.jar:3.0.4]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:146) [dubbo-3.0.4.kk-20211119.020408-2.jar:3.0.4]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:108) [dubbo-3.0.4.kk-20211119.020408-2.jar:3.0.4]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:98) [dubbo-3.0.4.kk-20211119.020408-2.jar:3.0.4]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:44) [dubbo-3.0.4.kk-20211119.020408-2.jar:3.0.4]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) [spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) [spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400) [spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354) [spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:888) [spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:161) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) [spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.example.hello.HelloServiceApp.main(HelloServiceApp.java:24) [classes/:?]
```

#### 疑问描述
1. Dubbo2 -> Dubbo3 这样一个不兼容变化是出于什么原因？
2. 是否会在后续版本发布中，支持相同配置但是注册中心Id不同的情况（即与Dubbo2一样）？
**Note：之所以会存在这样的场景，是因为在预发布环境不同注册中心id的`address`不同（此时Dubbo3不会报错），但是在其他环境需要维护同样的配置结构，但是`address`又相同，所以导致Dubbo3在其他环境启动的时候会出现报错**

辛苦大佬们解答～ 感谢🙏

**Comment by 106umao** [comment]
目前从官方文档获得的信息是Dubbo3.0 向下兼容（2.5，2.6，2.7） 你2.x是哪个版本？

**Comment by YuWan1117** [comment]
> 目前从官方文档获得的信息是Dubbo3.0 向下兼容（2.5，2.6，2.7） 你2.x是哪个版本？

问题中的2.x是2.6.6版本

**Comment by habertzk** [comment]
> 目前从官方文档获得的信息是Dubbo3.0 向下兼容（2.5，2.6，2.7） 你2.x是哪个版本？

请教个另外的问题，既然向下兼容，但是发现3.0版本 的metrics功能是不支持了吗？

**Comment by 106umao** [comment]
> > 目前从官方文档获得的信息是Dubbo3.0 向下兼容（2.5，2.6，2.7） 你2.x是哪个版本？
> 
> 请教个另外的问题，既然向下兼容，但是发现3.0版本 的metrics功能是不支持了吗？

在#9338中有人说已经弃用了

**Comment by 106umao** [comment]
> > 目前从官方文档获得的信息是Dubbo3.0 向下兼容（2.5，2.6，2.7） 你2.x是哪个版本？
> 
> 问题中的2.x是2.6.6版本

那就看看这个功能是否弃用了，如果没弃用可以添加type/bug标签

**Comment by chickenlj** [comment]
@106umao  感谢反馈。我们将在 3.0.9 版本中尝试复现并修复

**Comment by zrlw** [comment]
Each global configuration could only be defined only once‌ in Dubbo 3.x since https://github.com/apache/dubbo/pull/7891
